### ISSUE TITLE
Text: left the wrong default styles in

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1]

**Comment by necolas** [comment]
@vjeux are you doing anything particular with React Native's `Text` component? or is it mirroring standard `inline` or `inline-block` text elements on web?

**Comment by vjeux** [comment]
It should mirror display: inline but haven't throughly tested all the edge cases. Let me know if you find some divergences and we should fix them in react-native.

Also, unfortunately right now we don't support inline-block elements in react-native, which means that we can't include images or anything else that's not a Text inside of a Text. One day I'll have time to implement that or convince someone to :p

**Comment by necolas** [comment]
Initially I've styled `Text` as `inline-block` since we get that for free on web
