### ISSUE TITLE
Image: support `height` and `width` on `source`

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#10]
If dimensions are provided they can be used to determine the aspect ratio and layout the `Image` before it is downloaded.

**Comment by necolas** [comment]
I wonder if we could write an image loader that automatically includes this information for static assets, rather than just returning a URL string

**Comment by MoOx** [comment]
I have thought about that too!
I have write some loaders, and I think it should be pretty easy to handle. We probably just need to find a nice npm package that helps to get width/height and use it :)

**Comment by necolas** [comment]
The issue to create a new webpack loader is #237. Would appreciate someone taking it on.
