### ISSUE TITLE
Scoped stylesheet

### ISSUE THREAD

**Issue by azproduction** [necolas/react-native-web#100]
At this moment an application based on `react-native-web` expects to be alone on the document. It could be problematic when you want to run it inside existing app and without any frames.

The main problem that it generates global css rules and resets without any scope prefixes.

So it is required to:
- allow many app roots on the single document
- generate unique style elements for every app root
- add scope prefix to all generated css rules
- add scope prefix to all resets

At the end generated code would look like

```html
<div id="your-app-name-1">
  <style>
  #your-app-name-1 {global-reset-style}
  #your-app-name-1 ._s1 {generated-style}
  ...
  <style>
  <div className="s1">Your app</div>
<div>

<div id="your-app-name-2">
  <style>
  #your-app-name-2 {global-reset-style}
  #your-app-name-2 ._s1 {generated-style}
  ...
  <style>
  <div className="s1">Your app</div>
<div>
```

The only big problem I see here that StyleSheet is a global instance.

Do you think it would be hard to implement? I can do it on my own with some of your guidance.

**Comment by necolas** [comment]
Most of those requirements are not needed.

1. Multiple apps on the same page is already supported.
2. Multiple apps can share the same stylesheet.
3. I considered the `_s_` prefix to be the "scope". If it needs to be more obscure to avoid colliding with some existing CSS library, we can do that.
4. The global reset only effects pseudo elements and the root tags. It's pretty uninvasive. What problems have you encountered?

**Comment by necolas** [comment]
One improvement I can make is to render the style sheet above any other `style` or `link` tags (rather than next to the first RN app) to ensure that if a RN app lives within a non-react app, that non-react app's `html` and `body` CSS will override React Native's.

**Comment by necolas** [comment]
Tracking that in #106. I'm going to close this because I think I've answered your concerns. If not, let me know.
