### ISSUE TITLE
focus() and Blur() programmatically stopped working for View 

### ISSUE THREAD

**Issue by shashank-shanks** [necolas/react-native-web#1005]
**The problem**
Views have stopped responding to focus() and blur() methods when done programatically after 0.8.0. 
It was working well in 0.7.3

**How to reproduce**

Simplified test case: https://codesandbox.io/s/xowm2yw084

Steps to reproduce:
1. create a reference to a view 
2. call focus() on the ref programatically

**Expected behavior**
The view needs to be focussed programmatically similar to how it does when going through components using the tab key. 

**Environment (include versions). Did this work in previous versions?**
It worked as expected in 
* React Native for Web (version): 0.7.3
* React (version): "16.3.1"
* Browser: Chrome 67.0.3396.87

**Comment by necolas** [comment]
The test case is using 0.7.3

**Comment by necolas** [comment]
I think the problem here is that you're using `tabIndex` which is no longer forwarded to the underlying DOM node. You can read more about the change in the release notes for 0.8.0

**Comment by shashank-shanks** [comment]
That seems to be the case. Is there a work around to pass that prop to the underlying Node ? or any other alternative to using tabIndex ?

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/packages/website/guides/accessibility.md
