### ISSUE TITLE
"Cannot resolve module react-native." error in flow

### ISSUE THREAD

**Issue by chrisdrackett** [necolas/react-native-web#1007]
**The problem**

I'm setting up flow as described in the docs and adding the following line to my flow config under options:

`module.name_mapper='(react-native)' -> 'react-native-web'`

when I then run flow in my project I get a good number or errors like the following:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/components/core/Button.js:4:42

Cannot resolve module react-native.

     1│ // @flow
     2│
     3│ import * as React from 'react'
     4│ import { TouchableWithoutFeedback } from 'react-native'
     5│
     6│ const touchableProps = [
     7│   'hitSlop',

```

**Comment by necolas** [comment]
I think it should be

```
module.name_mapper='\(react-native\)' -> 'react-native-web'
```

Otherwise figure out what it should be and let me know. Thanks
