### ISSUE TITLE
View - Draggable functionality

### ISSUE THREAD

**Issue by OisinOKeeffe** [necolas/react-native-web#1010]
**The problem**
Views no longer support the following props (they previously did):
draggable
onDragStart
onDragOver
onDrop

took a look at filterSupportedProps and they aren't there. Is there a reason to not allow them? Image component allows for them.

**How to reproduce**
add props to view

**Additional context**
I edited filterSupportedProps for the view and added the props to the whitelist and everything worked as expected with regard to drag and drop functionality

**Comment by necolas** [comment]
Those events aren't supported in react native or mobile web browsers. Image only supports `draggable` for accessibility purposes. You can implement drag and drop (in a reliable and cross platform way) using the `PanResponder` API.

**Comment by skabbes** [comment]
I don't know if this changes anything, but I was trying to use these properties for a cross platform file upload.  onDragEnter and onDrop can be used for "drag and drop" file uploads.

**Comment by skabbes** [comment]
I ended up using `createElement` to get around this restriction.  Just make sure to specify the div a `display: 'flex'` specifically

```
import { createElement } from 'react-native-web'
const DragDiv = (props) => createElement('div', props);
```
