### ISSUE TITLE
Validation Error: Module ... in the ... option was not found with Jest

### ISSUE THREAD

**Issue by AugustoAleGon** [necolas/react-native-web#1012]
**The problem**

I am using ```jest``` and I upgrade to the latest version of ```react-native-web``` suddenly the unit test display the following error message:

```
● Validation Error:

  Module react-native-web/jest/serializer in the snapshotSerializers option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html
```

**How to reproduce**

Create a web application and configure ```jest``` then use the latest version.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.4
* React (version): 16.2.0
* Browser: Chrome 67.0.3396.99

Any ideas @necolas ?

**Comment by necolas** [comment]
Read the release notes for 0.8.0: https://github.com/necolas/react-native-web/releases/tag/0.8.0

https://github.com/necolas/react-native-web/commit/8f0c39c2fe78ea487996d407d37e7f45415d6097

**Comment by alexlevy0** [comment]
@AugustoAleGon Did you figure out what to put in the `snapshotSerializers` ? Thx

**Comment by AugustoAleGon** [comment]
@alexlevy0 sorry for the delay. Yes I solved the problem with `snapshotSerializers`. Just deleted it in your jest and use the preset of `react-native-web`. That solved my problem.
