### ISSUE TITLE
Selection breaks caret for TextInput

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#1018]
**The problem**
Typing does not work as expected. Caret position is not updated properly.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/8zn4213v20

Steps to reproduce:
1. Click to input
2. Write text
3. Caret is not properly updated.

**Expected behavior**
Caret should be properly updated. Now new chars are put after the caret, not before.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): Currect.
* React (version): Last
* Browser: Last Chrome in last macOS

Maybe I am doing something wrong.

**Comment by necolas** [comment]
It's a controlled component, so simply typing doesn't change the selection. What you want is:

```
  handleTextInputChangeText = text => {
    this.setState({ selection: { start: text.length }, value: text });
  };
```

**Comment by necolas** [comment]
It looks like this behaviour is different to what React Native does though

**Comment by steida** [comment]
I confirm it works as expected. Thank you for the brilliant library and support. You are the man.
