### ISSUE TITLE
Export ES6 modules to npm

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#102]
This will be valuable for people using bundlers like webpack@2 and rollup, as the bundles will omit any modules that aren't used by the app.

Probably means ES6-ifying a bunch of RN imports/exports. But I'm not sure how to ensure that the ES5 pattern used through RN apps and components is preserved (e.g., `var Animated = React.Animated`)

**Comment by necolas** [comment]
See if react-native is open to adding options to their allow disabling transform of modules to commonjs: https://github.com/facebook/react-native/commit/98dd91825f65e115cdf13c464689ee6c2bb8e27f

Ref: https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/src/index.js

**Comment by necolas** [comment]
Unnecessary at the moment

**Comment by nhducit** [comment]
hi @necolas, are there any way to reduce bundle size now. in my project, it bundle the whole `react-native-web` lib now. Are there any thing I can help to reduce bundle size?

![screen shot 2018-02-02 at 5 42 15 pm](https://user-images.githubusercontent.com/4246176/35729186-801eaca0-0840-11e8-9a87-5323db678b99.png)

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#adding-to-an-existing-web-app

**Comment by nhducit** [comment]
nice. Thanks a lot

**Comment by OKNoah** [comment]
> https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#adding-to-an-existing-web-app

404

**Comment by eseQ** [comment]
Any update?

**Comment by Daavidaviid** [comment]
Any update ?
