### ISSUE TITLE
WebView: implementation

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1025]
Look into implementing the `WebView` component

**Comment by piranna** [comment]
https://github.com/react-native-web-community/react-native-web-webview

**Comment by necolas** [comment]
`WebView` is being deprecated in React Native and moved to community maintenance https://github.com/react-native-community/react-native-webview

I've open an issue related to web support https://github.com/react-native-community/react-native-webview/issues/76

**Comment by piranna** [comment]
> I've open an issue related to web support [react-native-community/react-native-webview#76](https://github.com/react-native-community/react-native-webview/issues/76)

Thanks for that :-)

**Comment by anuj-nickelfox** [comment]
We have come full circle :D

**Comment by usfslk** [comment]
Please implement webview, definitely needed. Thanks awesome job!!

**Comment by tinni95** [comment]
please I need this, I can help as well
