### ISSUE TITLE
TabBarIOS: Implementation

### ISSUE THREAD

**Issue by piranna** [necolas/react-native-web#1028]
Add support for [TabBarIOS](https://facebook.github.io/react-native/docs/tabbarios.html). Working implementation available at https://github.com/piranna/react-native-web-extended/blob/master/src/components/TabBarIOS/index.js

**Comment by necolas** [comment]
It's an iOS-only component

**Comment by piranna** [comment]
I was proposing it to be API complete. Mayb open an issue at React Native repo to remove platform-specific components?
