### ISSUE TITLE
DrawerLayoutAndroid: implementation

### ISSUE THREAD

**Issue by piranna** [necolas/react-native-web#1029]
Add support for [DrawerLayoutAndroid](https://facebook.github.io/react-native/docs/drawerlayoutandroid.html). The name is a bit of a misnomer, because it's just a side panel so not Android specific, but Android has native APIs for it, that's all. Implementation available for both web and iOS at https://github.com/react-native-community/react-native-drawer-layout.

**Comment by necolas** [comment]
Yeah it's Android-only and you can use that package for cross platform drawer. No need to do anything here

**Comment by piranna** [comment]
What about adding a reference to tje cross-platform drawer in the readme?
