### ISSUE TITLE
Naming collision on fbjs

### ISSUE THREAD

**Issue by tuckerconnelly** [necolas/react-native-web#103]
In the packager, when I run `react-native run-android`:

```
Error: Naming collision detected: /Users/tuckerconnelly/src/tuckerconnelly/client/node_modules/fbjs/package.json collides with /Users/tuckerconnelly/src/tuckerconnelly/client/node_modules/react-native-web/node_modules/fbjs/package.json
```

I'm guessing this is because react-native-web depends on fbjs 0.7.2 and react-native still depends on fbjs 0.6.0 (what? lol)

**Comment by necolas** [comment]
Do you know if the packager trying to including react-native-web, or if it simply checks for collisions throughout `node_modules`?

**Comment by tuckerconnelly** [comment]
I'm pretty sure it's checking for collisions throughout node_modules.

Looks like react-native updated to fbjs 0.7.2 on March 2: https://github.com/facebook/react-native/commit/ad8a33586410c6f9048983f64f8f86e0715e73b8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R142

And then a few days later removed fbjs from the packager blacklist.

I upgraded to react-native@0.22-rc4 and it fixed the naming collision, but ran into other unrelated bugs so had to go back to 0.21.

I recommend moving react-native-web to fbjs 0.6.0 until react-native 0.22 is released.

**Comment by necolas** [comment]
I can probably relax the version range and hope npm installs a shared fbjs package

**Comment by tuckerconnelly** [comment]
Annnnnd react 22 out today haha

**Comment by necolas** [comment]
Let me know if `0.0.20` doesn't have packager error with RN@0.21

**Comment by tuckerconnelly** [comment]
Yup! Worked with .21 and .22 :+1:
