### ISSUE TITLE
TextInput onChangeText is not fired on text change

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#1031]
**The problem**
TextInput onChangeText is not fired on text change

**How to reproduce**
Click to button, check console, onChangeText was not dispatched.

Simplified test case: https://codesandbox.io/s/m77y1y6yz8

**Comment by necolas** [comment]
This matches React Native: https://snack.expo.io/ByIYHrWQX

The callback is only called when user input changes the text. If you're setting the text, you shouldn't need a callback to know what it is.
