### ISSUE TITLE
A guide for displaying existing react native apps on the web

### ISSUE THREAD

**Issue by wh1t3cAt1k** [necolas/react-native-web#1033]
**Describe a solution you'd like**

It would be nice to have a Getting Started section on how to add Web support and run existing react-native apps - **not** created with `create-react-native-app`.

**Comment by necolas** [comment]
That's here https://github.com/necolas/react-native-web/blob/master/packages/website/guides/getting-started.md#web-packaging-for-existing-react-native-apps

**Comment by yuya-kanai** [comment]
The link is not functioning now

**Comment by Secretmapper** [comment]
I believe it is moved to: https://github.com/necolas/react-native-web/blob/master/packages/docs/src/guides/multi-platform-apps.stories.mdx
