### ISSUE TITLE
accessibilityRole="form" does not preserve `onSubmit` handler

### ISSUE THREAD

**Issue by paularmstrong** [necolas/react-native-web#1034]
**The problem**
Using `accessibilityRole="form"` with `onSubmit={someHandler}`, `someHandler` is not called when hitting the return key in a nested `TextInput`.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/6y37n189kn

Steps to reproduce:
1. Go to the codesanbox link
2. Type in the input field
3. Hit your enter/return key to submit the form

**Expected behavior**
Expectation is that the `onSubmit` handler is called and the event is prevented.

**Actual behavior**
The page is submitted and reloaded.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): v0.8.8
* React (version): any
* Browser: any
* Previously worked in v0.5.x, v0.6.x, and v0.7.x: https://codesandbox.io/s/x9kv8xl8l4

**Comment by necolas** [comment]
As we discussed elsewhere, the callback is not supported following the tightening of the API to align with RN in 0.8. You can achieve the desired result by using the `onSubmitEditing` prop on `TextInput`
