### ISSUE TITLE
Breaking React 17 changes

### ISSUE THREAD

**Issue by chaffeqa** [necolas/react-native-web#1035]
**Is your feature request related to a problem? Please describe.**
A lot of lifecycle + server side rendering changes are occurring in React 16.  It would be nice to have a branch of RNW that builds towards those changes (and is a breaking version change that supports `react: ^0.16`)

**Describe alternatives you've considered**
It is hard to do stuff like `render = React.version.minor >= 16 ? ReactDom.hydrate : ReactDom.render`

**Additional context**
A sep branch would be nice because the changes of all component lifecycles to the new approach I'm sure will take time, and need to trace changes to the master branch

**[Edit]**
I realized that [you swap `hydrate` for `render` based on `process.env.NODE_ENV`](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/AppRegistry/renderApplication.js#L18).  Maybe for the time being would you consider allowing to pass in a `renderFn` so users can default to `hydrate`?

Related Warning:
![screenshot 2018-07-13 05 20 18](https://user-images.githubusercontent.com/287640/42683847-7cc62782-865c-11e8-91eb-bfca466aee2a.png)

**Comment by chaffeqa** [comment]
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

> One of the biggest lessons we’ve learned is that some of our legacy component lifecycles tend to > encourage unsafe coding practices. They are:

- componentWillMount
- componentWillReceiveProps
- componentWillUpdate

**Comment by necolas** [comment]
Oh I thought it was something new. I'm aware of this, thanks. I don't think a branch is necessary

**Comment by dcalhoun** [comment]
@necolas are your intentions to address these deprecations within #1172 or somewhere else? Are you interested in me opening a PR adding the `UNSAFE_` prefix to suppress the current warnings from using RNW with React `>=16.9.0`?
