### ISSUE TITLE
No more supported prior to react 16.2 ?

### ISSUE THREAD

**Issue by Kinka** [necolas/react-native-web#1039]
My project still is using react 16.2 and not in plan to upgrade 16.3. But I want to upgrade RNW to v8.x because of FlatList. Now I find that AnimatedComponent is broken since methods like `componentWillMount` was changed to `UNSAFE_componentWillMount`, so that `this._propsAnimated.__getValue();` in the `render` throws an undefined error, because `this._propsAnimated` is inited or changed in componentWillMount or componentWillReceveiProps.

**Comment by necolas** [comment]
Yes the latest version requires React 16.3 or higher and you will need to upgrade
