### ISSUE TITLE
Which Router is used for the manual's router?

### ISSUE THREAD

**Issue by Pneumatic95** [necolas/react-native-web#1040]
Which Router is used for the [manual](http://necolas.github.io/react-native-web/examples/)'? `react-navigation`? `react-router`?
My project needs this performance!!! Thanks!!!

**Comment by Pneumatic95** [comment]
OK, you used local Storage... My mistake :(

**Comment by necolas** [comment]
Those examples are simply what is in react native. You can use any DOM router and react-navigation has some kind of web support but lacks a proper history driver

**Comment by Pneumatic95** [comment]
My APP used react-navigation, it didn't support browser's history,  so it brings some bad experience in the web.Mmaybe using react-navigation in the web is not a good idea
