### ISSUE TITLE
Creating a standalone JS bundle

### ISSUE THREAD

**Issue by ciaranj** [necolas/react-native-web#105]
Hi, how can I create a bundle such as that found at https://wzrd.in/bundle/react-native-web@0.0.19 from a local branch.  I'm pulling my react and react-dom dependencies in directly from facebook and they seem to be compatible with the above link, but they're not when I use them against the artifact provided through npm prepublish.

I *know* this is just my unfamiliarity with the toolchain rather than an issue, but I was hopeful someone could just point me in the right direction! 

Thanks!

**Comment by necolas** [comment]
Are you using the standalone JS bundle found at `react-native-web/dist/react-native-web.js` in the npm package?

**Comment by ciaranj** [comment]
yes. This seems very different from the one in the link above however.

**Comment by necolas** [comment]
The one in the link includes `react` and `react-dom` in the bundle. I've probably broken the UMD bundle on npm.

**Comment by ciaranj** [comment]
hmm, ok, so in my html I'm pulling in react + react-dom direct from the facebook CDNs I guess they're not 'UMD' compatible then ?
