### ISSUE TITLE
Cannot read property '__getValue' of undefined on AnimatedComponent in Storybook web.

### ISSUE THREAD

**Issue by AugustoAleGon** [necolas/react-native-web#1050]
**The problem**

I am currently working with `react-native-web` and `storybook`. I am currently facing an issue in the `AnimatedComponent` on Storybook because they are not displaying an error message. I was debugging and I checked that the problem is in a function that doesn't appear available.

**How to reproduce**

Build a React Native Web project.
And in storybook try to use an `AnimatedComponent` it will display a message that can not be render.
Simplified test case: 

Steps to reproduce:
1. Build React Native Web Add
2. Test Animated Components
3. Displays on Storybook

**Expected behavior**

Render Animated component in Storybook.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.8
* React (version): 16.2.0
* Browser: 67.0.3396.99

**Comment by necolas** [comment]
First, you will need to use React 16.4 or above. The relevant information is in the version release notes on GitHub. The animated components work fine in the RNW examples and shouldn't be in any way effected by Storybook. If there is still an problem, please create a reproducible test case on codesandbox.

**Comment by AugustoAleGon** [comment]
@necolas  Do you have a boilerplate to start the configuration? In order to replicate?

**Comment by necolas** [comment]
Yes the link is included in the issue template

**Comment by AugustoAleGon** [comment]
@necolas Problem solved. You were right. There was a problem in `react-dom-development` that was solved in `react-dom` 16.4.
