### ISSUE TITLE
Appearance is not allowed for <Picker />

### ISSUE THREAD

**Issue by victorhqc** [necolas/react-native-web#1051]
**The problem**
`<Picker />` doesn't add padding in chrome and webkit browsers. To fix it is just matter of adding `appearance: none` but then it shows a warning in console.

**How to reproduce**

[![Live example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9yvmjzv0wr)
Simplified test case:
```js
<Picker selectedValue="mango" style={{ padding: 24, appearance: "none" }}>
  <Picker.Item label="Kiwi" value="kiwi" />
  <Picker.Item label="Apple" value="apple" />
  <Picker.Item label="Mango" value="mango" />
  <Picker.Item label="Watermelon" value="watermelon" />
</Picker>
```

Steps to reproduce:
1. Access codesandbox with chrome.

**Expected behavior**
the rendered `<select>` should have padding, or in any case, allow for the `appearance` property at least in web using `Platform.OS`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.9
* React (version): 16.4.1
* Browser: Chrome

**Comment by necolas** [comment]
Doing that removes the default browser UI, so it's not recommended or supported

**Comment by tastafur** [comment]
On the web, the elements are usually customized, not the UI by default and is what I need to correctly visualize the web part of the project in which I work should be able to do without launching warnings that you are using an incorrect style prop I believe
