### ISSUE TITLE
ViewPagerAndroid

### ISSUE THREAD

**Issue by hushicai** [necolas/react-native-web#1052]
**Is your feature request related to a problem? Please describe.**

no

**Describe a solution you'd like**

I have tried to implement `ViewPagerAndroid` with the `ScrollView` , inspired by [react-native-ViewPager](https://github.com/zbtang/React-Native-ViewPager).

[Here](https://github.com/hushicai/react-native-web/blob/master/packages/react-native-web/src/exports/ViewPager/index.js) is my initial implementation, as well as [examples](https://hushicai.github.io/react-native-web/examples/) .

Would you like to merge this feature?

**Describe alternatives you've considered**

No

**Additional context**

No

**Comment by necolas** [comment]
I'm not implementing platform-specific components. There are also existing OSS solutions for RN drawers that are pure JS
