### ISSUE TITLE
Image Picker, Can I have the file path or the file totally when an Image is Picked

### ISSUE THREAD

**Issue by yarra2296** [necolas/react-native-web#1054]
**Is your feature request related to a problem? Please describe.**
NO

**Describe a solution you'd like**

I need some suggestion on the component I can use or the Method, How to import Total image file or path of the file in WEB Version.

**Describe alternatives you've considered**

I tried using React-native-everywhere-image-picker. But I am getting BASE-64 Image file from it.

**Additional context**

So, Please help me with the Component anything for Directly Uploading the file or the File path. I can also Know the method If anything is not present. 

Thanks in Advance,

**Comment by necolas** [comment]
Also not clear what you're asking for here. Hope to upload an image? You can use react dom and `<input type=file /> for now

**Comment by yarra2296** [comment]
Actually, While I am picking an Image. I am getting Base-64 of the Image. But I need the file path. Since, I can upload it to the server.
