### ISSUE TITLE
I need to Display a HTML Page in Web Version.

### ISSUE THREAD

**Issue by yarra2296** [necolas/react-native-web#1055]
**Is your feature request related to a problem? Please describe.**
NO

**Describe a solution you'd like**

I need to Display the HTML content I am having. So, It will be helpful If I get to know how to use the HTML to print the Page.

**Describe alternatives you've considered**

I tried using WebView in WEB Version which is currently not supported by React native WEB. So, It would be much grateful to know the solution for it.

**Additional context**

Thanks in advance.

**Comment by necolas** [comment]
I'm clear on what you're trying to do, but there's nothing stopping you rendering HTML on web any way you would with react dom

**Comment by yarra2296** [comment]
Yeah, I got it But I did not get how to use the HTML with React DOM. It would be very helpful for my project.
