### ISSUE TITLE
LayoutAnimation might be broken

### ISSUE THREAD

**Issue by tafelito** [necolas/react-native-web#1056]
**The problem**
I tried using the LayoutAnimation from the repo but it seems that is not working. Nothing is being animated 

You can see the example here
https://codesandbox.io/s/woqr7w91q8

Is LayoutAnimation supposed to work? It's marked as implemented 

* React Native for Web (version): 0.8.3
* React (version): 16.4.1
* Browser: any

**Comment by necolas** [comment]
Yes this is mentioned in the Readme

**Comment by tafelito** [comment]
Ok I see it 's missing the web transform I completely missed that, sorry. I'll close this then
