### ISSUE TITLE
how add react-native-web to existing react-native project which was created without using expo

### ISSUE THREAD

**Issue by Mactub07** [necolas/react-native-web#1058]
problem: current initialization 
'create-react-native-app my-app --with-web-support' 
use expo with react-native. 

is there a way to add react-native-web to existing project which was initialized without expo (used command 'react-native init')

**Comment by necolas** [comment]
See https://github.com/necolas/react-native-web/blob/master/packages/website/guides/getting-started.md

**Comment by bvodola** [comment]
https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#configuring-a-module-bundler

**Comment by josprachi** [comment]
> https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#configuring-a-module-bundler

page not found
