### ISSUE TITLE
Space & Enter key events are swallowed by Touchable-Objects

### ISSUE THREAD

**Issue by c-goettert** [necolas/react-native-web#1059]
**The problem**
Key events for Children of Touchable-Objects are not being fired for space & enter keys.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/0xn755kmzv

Steps to reproduce:
1. Use `<textarea />` or `<input type='text' />` inside a `<TouchableOpacity />` tag 
2. Try adding some blank-spaces by pressing space

**Expected behavior**
blanks are added to value in input-field

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): "^0.8.4"
* React (version): 16.4.0
* Browser: Chrome

**Additional context**
I saw this issue is caused by some Hack in web-implementation of [Touchable](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Touchable/index.js). Here is the responsible part:

```
  // HACK (part 2): basic support for touchable interactions using a keyboard (including
  // delays and longPress)
  touchableHandleKeyEvent: function(e: Event) {
    const ENTER = 13;
    const SPACE = 32;
    const { type, which } = e;
    if (which === ENTER || which === SPACE) {
      if (type === 'keydown') {
        if (!this._isTouchableKeyboardActive) {
          if (
            !this.state.touchable.touchState ||
            this.state.touchable.touchState === States.NOT_RESPONDER
          ) {
            this.touchableHandleResponderGrant(e);
            this._isTouchableKeyboardActive = true;
          }
        }
      } else if (type === 'keyup') {
        if (this._isTouchableKeyboardActive) {
          if (
            this.state.touchable.touchState &&
            this.state.touchable.touchState !== States.NOT_RESPONDER
          ) {
            this.touchableHandleResponderRelease(e);
            this._isTouchableKeyboardActive = false;
          }
        }
      }
      e.stopPropagation();
      // prevent the default behaviour unless the Touchable functions as a link
      // and Enter is pressed
      if (!(which === ENTER && AccessibilityUtil.propsToAriaRole(this.props) === 'link')) {
        e.preventDefault();
      }
    }
  }
};
```

I know it's a rather unusual pattern to nest textinputs into touchables, but it still should be possible. I also saw if you swap `<textarea />` with `TextInput` from react-native you can add spaces just fine.

**Comment by necolas** [comment]
I'll have a look at whether the existing behaviour can be preserved without causing this, but you should consider adding DOM text input components directly inside RN touchable components as unsupported

**Comment by necolas** [comment]
Closing this as "WONTFIX" for the reason above. I recommend using `TextInput`, and if you can't for some reason, you can implement your custom text input component similarly to how `TextInput` avoids this problem (but stopping propagation of key events)

**Comment by vicary** [comment]
Sorry about bringing this up, but is there a recommended way to properly capture a touch/click event having all other events pass through?

My use case is to focus on a specific input when user taps/clicks on the empty area (background).
