### ISSUE TITLE
Styling Image inner div 

### ISSUE THREAD

**Issue by tafelito** [necolas/react-native-web#1060]
When using Image, it creates a parent div with a div and an img element. Is it possible to style the child div? All the styling on the Image components is applied to the parent div. 

The reason why I would want to do that is to create something similar of what instagram is doing on their mobile site when you upload a new image, where you can move the image within the parent div. The parent div has a fixed height using padding-bottom, but then the inner div can have a height of > 100%. So I'm thinking on using the PanResponder API to style the inner div while moving around

![large gif 320x321](https://user-images.githubusercontent.com/5973652/43541053-6dbf4fd0-9597-11e8-838e-0a87c9efb6fe.gif)

**Comment by necolas** [comment]
You can put the image inside a view as you would with React Native.

**Comment by tafelito** [comment]
Then I would need to know before loading the image the height to use on the parent View and I can't use the padding to auto determine the height. And even knowing the height, if I use > 100% height on the image, then it will cover the View

IG - The image is bigger than the coainter but is behind it

![image](https://user-images.githubusercontent.com/5973652/43545950-51ac830e-95a5-11e8-9f0b-beb8f988241f.png)

MIne

![image](https://user-images.githubusercontent.com/5973652/43545746-b77dfbd2-95a4-11e8-82eb-c06efe07e799.png)
