### ISSUE TITLE
SectionList section heads are not sticky

### ISSUE THREAD

**Issue by chrisdrackett** [necolas/react-native-web#1066]
**The problem**

Sticky headers not working in `SectionList`

**How to reproduce**

Simplified test case: https://codesandbox.io/s/v3x908zkw7?module=%2Fsrc%2FApp.js

Steps to reproduce:
1. Create a SectionList with section
2. add `stickySectionHeadersEnabled` (should this be default? it is on iOS)
3. Scroll SectionList

**Expected behavior**

Headers stick to the top of the list, are replaced by next header down.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.9
* React (version): 16.4
* Browser: Safari, Chrome

**Comment by necolas** [comment]
Must have been a regression in a patch release

**Comment by brunolemos** [comment]
I was not able to find a version that this works.

**Comment by necolas** [comment]
ListView works. Haven't looked into why SectionList doesn't

**Comment by brunolemos** [comment]
I investigated and gladly it is an easy fix.
The `style` prop is not being handled by the default `CellRendererComponent` from `VirtualizedList`.

Made #1122
