### ISSUE TITLE
Allow accessibilityRole menuitem to route enter to onClick

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#1068]
**Is your feature request related to a problem? Please describe.**
Previously in our dropdowns and lists we used `role=button` for items within the list. Good aria practice suggests that the container should be `role=menu`, with each item as a `role=menuitem`. Currently, RNW routes enter presses on `role=button` to `onClick`, but not `role=menuitem`. This means the change breaks enter handling.

More generally, interested to hear how much of the best practices should live in RNW vs in the app code. (e.g. Would RNW ever handle that up/down navigation within menu roles?)

**Describe a solution you'd like**
One solution would be to extend the handling of enter -> onClick not just for button, but a set of possible roles. See:
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/createElement/index.js#L51

**Describe alternatives you've considered**
The alternative is that in the same code where the app handles up/down within the menu, could additionally handle enter and use that to trigger onClick when RNW does not.

**Additional context**
Demo: https://codesandbox.io/s/zxomy6lr7l
https://www.w3.org/TR/wai-aria-1.1/#menuitem
https://www.w3.org/WAI/GL/wiki/Using_ARIA_menus#Keyboard_Actions_if_focus_is_on_a_menu_item

**Comment by jpstrikesback** [comment]
Was just about to post a query as to whether RNW had an intent to support keyboard nav on role=menu / menuitem (and enter, maybe esc to dismiss focus is out of scope?)

**Comment by necolas** [comment]
Looks like a good idea.

Arrow key / spatial navigation is modeled globally and can be bolted on using existing libraries and hooking into an attribute exposed by RNW https://github.com/necolas/react-native-web/blob/master/packages/website/guides/accessibility.md#spatial-navigation
