### ISSUE TITLE
Space issue on multiLine TextInput

### ISSUE THREAD

**Issue by hundsim** [necolas/react-native-web#1071]
**The problem**
When TextInput is set to `multiLine={true}`, theere's more space to the bottom-border in the browser than on iOS (see comparing screenshots). 

Applied (registered) styles:

`  input: {
    borderColor: '#bbb',
    borderBottomWidth: 1,
  },
` 

**Browser (Chrome 68):**
![screenshot 2018-08-15 17 42 23](https://user-images.githubusercontent.com/1907343/44157406-a81e9700-a0b2-11e8-937e-f5e02da4126c.png)

**iPhone (6/iOS 11):**

![screenshot 2018-08-15 17 44 18](https://user-images.githubusercontent.com/1907343/44157509-eae06f00-a0b2-11e8-849c-f19e044d9c6e.png)

**How to reproduce**
Re-create the styling provided above

**Expected behavior**
There shouldn't be any extra space between inserted text and bottom-border on browser.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.2
* React (version): 16.3.1
* Browser: Chrome 68

**Comment by necolas** [comment]
Please create a test case as required in the issue template. I'll reopen when you do. You should also be on react 16.4

**Comment by hundsim** [comment]
Here you go: https://codesandbox.io/s/yklvzp5z09
