### ISSUE TITLE
Switch component does not pass accessibilityLabel to control

### ISSUE THREAD

**Issue by kellyk** [necolas/react-native-web#1072]
**The problem**
When using a screen reader to interact with a switch, the purpose of the switch control is unclear. Despite passing an accessibilityLabel prop into the Switch, the label is not read.

**How to reproduce**
https://codesandbox.io/s/l58z0p7w09

Steps to reproduce (on Mac):
1. Turn on VoiceOver (cmd+F5)
2. Navigate to Switch using VO keys (ctrl+option+shift+down)
3. Toggle Switch (ctrl+option+space)
4. Observe that the control is read as "unchecked checkbox" 

**Expected behavior**
The control should read "unchecked checkbox, Night mode"

**Environment**

* React Native for Web (version): 0.5.2
* React (version): 16.3.1
* Browser: Chrome 68

**Proposed solution**
Use `accessibilityLabel` prop as `aria-label` on the `input` control instead of the surrounding `View`.

**Additional context**
Making the following change locally fixes the problem:

 ```
var _props = this.props,
        activeThumbColor = _props.activeThumbColor,
        activeTrackColor = _props.activeTrackColor,
        disabled = _props.disabled,
        onValueChange = _props.onValueChange,
        style = _props.style,
        thumbColor = _props.thumbColor,
        trackColor = _props.trackColor,
        value = _props.value,
        onTintColor = _props.onTintColor,
        thumbTintColor = _props.thumbTintColor,
        tintColor = _props.tintColor,
        accessibilityLabel = _props.accessibilityLabel,
        other = _objectWithoutProperties(_props, ['activeThumbColor', 'activeTrackColor', 'disabled', 'onValueChange', 'style', 'thumbColor', 'trackColor', 'value', 'onTintColor', 'thumbTintColor', 'tintColor', 'accessibilityLabel']);

 // ......... some other stuff

    var nativeControl = (0, _createElement2.default)('input', {
      'aria-label': accessibilityLabel,
      checked: value,
      disabled: disabled,
      onBlur: this._handleFocusState,
      onChange: this._handleChange,
      onFocus: this._handleFocusState,
      ref: this._setCheckboxRef,
      style: [styles.nativeControl, styles.cursorInherit],
      type: 'checkbox'
    });
```

**Comment by necolas** [comment]
That seems like a reasonable change. You can also wrap form controls in accessibilityRole=label

**Comment by kellyk** [comment]
I thought about doing this, but we have an interesting case where the label links to a more detailed settings page, and the switch beside it provides easy access to the main setting (Data saver in user dropdown menu on Twitter).

**Comment by necolas** [comment]
Wouldn't you be better off using a label just for the switch that is distinct from the link text? I don't think you'd want the 2 different things being confused in the accessibility tree
