### ISSUE TITLE
TouchableOpacity does not check unmounted component

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#1074]
https://codesandbox.io/s/o5lyy1yxn6

Click to foo and see the error. I suppose this is the perfect use case which should be supported by RNW.

**Comment by necolas** [comment]
Please can you do be a favor and compete the issue template as requested? It makes me life easier and helps other people understand issue context better without having to understand test case code

**Comment by necolas** [comment]
I opened your example in mobile chrome, clicked the touchable and it unmounted with no error shown in the console. This is why you are asked to provide the information requested in the template. I'll reopen when that's done and I can reproduce whatever issue you're experiencing

**Comment by steida** [comment]
Sorry.

* React Native for Web (version): 0.8.9
* React (version): 16.4.2 
* Browser: Chrome last

![screen shot 2018-08-17 at 10 08 35](https://user-images.githubusercontent.com/66249/44255218-8c77d580-a205-11e8-91ba-dba30c6e1eeb.png)

**Comment by steida** [comment]
@necolas Can you reopen it, please?
