### ISSUE TITLE
Disable virtualization if inside jsdom

### ISSUE THREAD

**Issue by jlongster** [necolas/react-native-web#1077]
**Is your feature request related to a problem? Please describe.**

I'm experimenting with running RNW inside jsdom to test components. It works pretty well! One problem I've run into is testing stuff inside a `FlatList` - since it's virtualized, it only ever renders the `initialNumToRender` number of items, and never any more. Since jsdom doesn't support scrolling or whatever other events a ScrollView depends on, it never renders more than that. 

**Describe a solution you'd like**

You never need virtualization when testing, so ideally we'd just disable it. We can simply check if we're inside jsdom with this check: `navigator.userAgent.includes("jsdom")`. Inside `VirtualizedList` we can set `virtualizationDisabled` or whatever that property is to `true` if we detect jsdom.

I could pass `initialNumToRender={10000}` myself and it does render everything, but I don't want to do that wherever I use a FlatList.

**Comment by necolas** [comment]
Are you using jest? It might be a good time to start adding mocks to the jest preset to help with this kind of issue

**Comment by jlongster** [comment]
What would be mocked here to disable virtualization?

**Comment by necolas** [comment]
What's mocked to disable it in react native?

**Comment by necolas** [comment]
Why do you need to render all items in the test?

**Comment by jlongster** [comment]
React Native doesn't have a good testing story at all. So you don't do it because testing itself sucks. I'm using RNW for testing isolated components.

I need to render all of them because I could care less about virtualization in tests - but I do want to query into the document to check the validity of the items and that they are rendered with the right stuff regardless if they are actually scrolled into view or not.

**Comment by necolas** [comment]
Ok, thanks. I think your proposed solution sounds good. You can submit a PR if you'd like to, or I can pick it up shortly.

Do you have any OSS examples of the kind of testing you're doing? I'm curious to see what people are doing :)
