### ISSUE TITLE
Sandbox at Glitch.com is not working as documented in Readme

### ISSUE THREAD

**Issue by wjielim** [necolas/react-native-web#1084]
**The problem**

The sandbox at Glitch.com stuck at "Fetching Project" status

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1. Visit https://glitch.com/edit/#!/react-native on Chrome

**Expected behavior**

A sandbox successfully loaded at Glitch.com

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): N/A
* React (version): N/A
* Browser: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* OS: Windows 10

**Comment by dcalhoun** [comment]
@wjielim I am able to open the Glitch project successfully. Are there any errors in your console or network requests that have failed? Maybe try again in an incognito window.

<img width="1038" alt="rnw-glitch" src="https://user-images.githubusercontent.com/438664/44744707-5a9b2480-aacb-11e8-8245-52f125509934.png">

**Comment by necolas** [comment]
Everything seems to be OK now, but I had the same issue a few days ago when I opened it on my phone. Must have been a temporary service issue for Glitch
