### ISSUE TITLE
After adding react-native-web to an existing react-native app gives so many error regarding can't resolve module in node_modules.

### ISSUE THREAD

**Issue by anjanaNewput** [necolas/react-native-web#1085]
I am integrating react-native-web to an existing react-native app. 
I added webpack.config.js as required and a index.html file also.

I run webpack dev server and its will gives lots of error.

Expected: 
It should work.

Current Scenario: 
Gives lots of error.
![screen shot 2018-08-27 at 5 43 28 pm](https://user-images.githubusercontent.com/17215354/44659483-09832600-aa22-11e8-8508-e89d8e0bf32d.png)

Can you please suggest me how to remove these error or ignore such error?
Also How can I add platform specific node modules for web and mobile?

**Comment by benedictasamoah** [comment]
Yes it does, having a couple of those

**Comment by anjanaNewput** [comment]
@necolas 
Please suggest me.

**Comment by dcalhoun** [comment]
@anjanaNewput it may be easier to help you debug if you provided the `webpack.config.js` file from your project.

**Comment by Ivanca** [comment]
@necolas What do you mean aliased exactly? How do you alias it? (I'm having similar issue)

**Comment by dcalhoun** [comment]
@Ivanca aliasing the `react-native` module name is covered in the [documentation for getting started](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#configuring-a-module-bundler) with this project. Please be sure to read the projects documentation.

**Comment by Ivanca** [comment]
Oh that's what you meant, yeah already did that, helped nothing.
Please be sure to try to sound less condescending.

**Comment by dcalhoun** [comment]
> Oh that's what you meant

@Ivanca I was clarifying Nicolas’ statements. 

I was trying to be helpful. If you would like to provide additional information about what you’re experiencing, I will continue to try to be helpful.
