### ISSUE TITLE
ImageLoader. onload: Decode throws DOMException with SVGs on iOS

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#1087]
**The problem**
In 0.8.0, ImageLoader started using decode to defer decoding of images. However, even when `.decode` is supported, it may sometimes fail. Right now there is no failure handler for the promise, which causes this to bubble as an UnhandledPromiseException: `EncodingError: Invalid image type`.

**How to reproduce**
Simplified test case: https://710p09642q.codesandbox.io/, view in both Chrome and Safari.

Steps to reproduce:
1. Use Image component with SVG in Safari
2. Error

**Expected behavior**
Unhandled Promise Exceptions should not be thrown. There's a few possible solutions:

1) Do not use .decode for SVGs
I'm not entirely sure what decoding means for an SVG, but since some browsers support it, there might be a purpose to supporting it in RNW. We could more specifically target SVGs and Safari as well, but that gets a little crufty and non-progressive.

2) Add a decode failure handler
If we go this route. Decide if this should call onLoad or onError, it's not immediately clear which is correct (technically on iOS the image still loads and displays). Although according to the spec linked below, failure of decode seems to suggest the image didn't load.

Either of these solutions should fix the problem. Happy to discuss further to see which is most appropriate. Still need to work on some code locally to test this in our codebase as the bug seems to be ios only.

**Environment (include versions)**

* React Native for Web (version): 0.8.0+
* React (version): N/A
* Browser: Safari + iOS (incl Safari + Chrome for iOS I think)

**Additional context**
https://github.com/necolas/react-native-web/commit/b8f54f61f05bd84228050d7efd0919f5ababce24
https://groups.google.com/a/chromium.org/forum/#!msg/blink-reviews-html/0vSdi93C0hI/xWKOnYs1AQAJ

img decode spec: https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-decode

Will consider filling a safari / webkit bug too

**Comment by necolas** [comment]
Patched in https://github.com/necolas/react-native-web/commit/b9172ceb8e0779c41e17210e56da36bdcc3e438b
