### ISSUE TITLE
The class name is very large for CEO

### ISSUE THREAD

**Issue by Tyomar** [necolas/react-native-web#1088]
The class name is very large for the CEO. Is it possible to integrate another approach to the formation of styles? More classic, but compatible with the mobile version

sample of rendered on server side:
`<div dir="auto" class="rn-borderTopWidth-13yce4e rn-borderRightWidth-fnigne rn-borderBottomWidth-ndvcnb rn-borderLeftWidth-gxnn5r rn-boxSizing-deolkf rn-color-homxoj rn-display-1471scf rn-fontFamily-14xgk7a rn-fontSize-1b43r93 rn-fontStyle-o11vmf rn-fontVariant-ebii48 rn-fontWeight-gul640 rn-lineHeight-t9a87b rn-marginTop-1mnahxq rn-marginRight-61z16t rn-marginBottom-p1pxzi rn-marginLeft-11wrixw rn-paddingTop-wk8lta rn-paddingRight-9aemit rn-paddingBottom-1mdbw0j rn-paddingLeft-gy4na3 rn-textDecoration-bauka4 rn-whiteSpace-q42fyq rn-wordWrap-qvutc0">Hello, world!</div>`

needed transform to:
`<div class='no more 20 symbols">Hello, world!<div/>`

**Comment by necolas** [comment]
No. This is a good way to do it
