### ISSUE TITLE
Future of react-native-web regarding React-Native Fabric and React Fire

### ISSUE THREAD

**Issue by johakr** [necolas/react-native-web#1094]
Hi,

regarding the latest announcements of [React-Native Fabric](http://facebook.github.io/react-native/blog/2018/06/14/state-of-react-native-2018) and [React Fire](https://github.com/facebook/react/issues/13525), I think it might be a good idea to have a consolidated place to discuss the implications of these two changes on react-native-web and develop strategies to realize a smooth transition phase of react-native-web.

**Comment by necolas** [comment]
See https://github.com/necolas/react-native-web/issues/1089

**Comment by johakr** [comment]
So your are not interested in getting help and ideas from the community, I guess...
