### ISSUE TITLE
TextInput: value state not working with keyboardType='numeric'

### ISSUE THREAD

**Issue by piu130** [necolas/react-native-web#1098]
**The problem**
First problem: As soon as I add `keyboardType="numeric"` to my `TextInput` the `value` prop does not work anymore. In the example when I add a letter (first TextInput) it should remove it. This only works when I remove `keyboardType="numeric"` (second TextInput).

Second Problem: `onChangeText` is only triggered (with `keyboardType="numeric"`) when I add a string matching the regex `/^\d+\D?$/`. In words: one or more digits and optional one (only one) letter at the end. It should trigger always.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/llvy0zymjq

Steps to reproduce:
1. The two TextInput are exact the same expect `keyboardType="numeric"` is removed in the second.
2. Test them

**Expected behavior**
`value` prop should work on `TextInput` and `onChangeText` should always trigger with `keyboardType="numeric"`

**Comment by piu130** [comment]
Oh sorry. I'm using `react-native-web` in the laptops browser (Firefox), where I have a physical keyboard. So I can type any letter I want. So for example when I type `8` onChangeText is fired. Then when I type `8k` onChangeText is fired again but passed text is empty and state seems to break. When I type `8kk` onChangeText is not fired anymore.

In the second field it works as expected: when I type `8` onChangeText is fired. `8k` fires onChangeText and removes the `k`.

**Comment by necolas** [comment]
> I'm using react-native-web in the laptops browser (Firefox)

The browser is an important detail that is asked for in the issue template, but you removed that section.

Firefox seems to have a bad implementation of the number type, and behaves like the iOS implementation in React Native.

**Comment by necolas** [comment]
It looks like Firefox produces an empty string `""` when a letter is added to a numeric input, so this might be something I can detect and prevent in `TextInput` for controlled components (like what you're doing). No promises though

**Comment by piu130** [comment]
Many thanks. Haven't thought that this is browser dependent (as always). :)

I think it would be hard to implement, because there is not way to detect if a user first type `8` then `k` or removes the `8`. Would both return an empty string.

So I'll wait for Firefox to fix that issue and test it in Chromium.

**Comment by mcmonkeys1** [comment]
This bug is still present in Firefox. No simple workaround.

**Comment by NorhanMostafa94** [comment]
HTML use event keypress:
(keypress)="preventCharInNumber($event)"
JavaScript:
preventCharInNumber(event) {
    if (this.type === 'number' && event.code.startsWith('Key')) {
      event.preventDefault();
    }
