### ISSUE TITLE
Impossible to render TouchableOpacity with tabIndex -1

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#1099]
**The problem**
accessible false should set tabIndex -1 imho.

**How to reproduce**
https://codesandbox.io/s/n9mw16954m

**Expected behavior**
For Keyboard-navigable_JavaScript_widgets roving tabIndex we need to set tabIndex -1 somehow, but it seems that React Native Web does not have an API for that.

**Comment by steida** [comment]
I think workaround can be componentDidMount with setNativeProps to tabIndex -1

**Comment by necolas** [comment]
Your test case sets it to `true`

**Comment by necolas** [comment]
There's no issue that I can see here. Everything works as expected. And `tabIndex=-1` is only needed on DOM elements that are focusable by default

**Comment by steida** [comment]
@necolas But what about this recommendation? As I understand it, my TouchableOpacity buttons should have tabIndex -1, because:

> Don't assume that all focus changes will come via key and mouse events: assistive technologies such as screen readers can set the focus to any focusable element.

Without tabIndex -1 I can not implement it properly I suppose.

![screen shot 2018-09-09 at 21 29 30](https://user-images.githubusercontent.com/66249/45268031-77463d80-b477-11e8-995f-5b6b05b832be.png)

https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets

**Comment by necolas** [comment]
If you set `accessible={true}` or `accessibilityRole='button'` it will add `tabIndex=0` which makes the element focusable.

**Comment by steida** [comment]
Sure, but the other buttons should be focusable but not tab-able. tabIndex -1.

![screen shot 2018-09-09 at 21 40 04](https://user-images.githubusercontent.com/66249/45268215-fbe58b80-b478-11e8-8f93-1aaa9bbe8702.png)

**Comment by necolas** [comment]
I don't understand why you consistently open issues without including the relevant context. You can't expect me to guess at what you're trying to say from the tiny amount of information you initially provide.

**Comment by necolas** [comment]
Feel free to put up a PR that explains what you're trying to accomplish.

**Comment by steida** [comment]
Sorry about that. I will.

**Comment by steida** [comment]
Keyboard-navigable_JavaScript_widgets via React API is PITA.

- almost impossible to get ref via focus via all higher order components etc.
- RNW does not suppose tabIndex -1

As result, this logic must be totally out of React and RNW. Use findDOMNode and fok that shit.

**Comment by necolas** [comment]
There's possibly something to improve here but you don't take the time to explain or be clear, so it makes it hard to help.

**Comment by steida** [comment]
I realized that controlling tabIndex and focus out of React API leads to less and simpler code. Also, it's browser only thing. Sorry I can not help more right now.

**Comment by steida** [comment]
Again, I need tabIndex -1, so here is an example for the others with the same problem.

```js
// @flow
import * as React from 'react';
import { View } from 'react-native';

type FocusOnMountProps = {|
  children: React.Node,
|};

// https://medium.com/@robdel12/single-page-apps-routers-are-broken-255daa310cf
class FocusOnMount extends React.PureComponent<FocusOnMountProps> {
  ref = React.createRef();

  componentDidMount() {
    const { current } = this.ref;
    if (!current) return;
    // https://github.com/necolas/react-native-web/issues/1099
    current.setNativeProps({
      tabIndex: -1,
      style: { outline: 'none' },
    });
    current.focus();
  }

  render() {
    return <View ref={this.ref}>{this.props.children}</View>;
  }
}

export default FocusOnMount;
```

From http://github.com/este/este.

**Comment by necolas** [comment]
Why did you close this issue then?

**Comment by siarheipashkevich** [comment]
@necolas I have the same issue on the web, could you share your solution please?

**Comment by necolas** [comment]
Use 'focusable'. It's in the docs
