### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by eightyfive** [necolas/react-native-web#1101]
**Is your feature request related to a problem? Please describe.**
It would be nice to trigger the native date picker of modern browsers to mimic RN `DatePickerIOS` / `DatePickerAndroid`.

**Describe a solution you'd like**
I thought rendering a simple `<input type="date" />` could do the trick. In the same way the `Picker` component is implemented for web (using a simple `<select />`).

**Describe alternatives you've considered**
Anything else than this solution would not belong in [react-native-web](https://github.com/necolas/react-native-web) imo.

**Additional context**
I did not find any issue/discussion about the matter, is that something that has already been discussed? If so feel free to close the issue.

**Comment by necolas** [comment]
There's no cross-platform DatePicker in RN and the platform-specific ones have been moved to community projects.
