### ISSUE TITLE
TextInput: maxLength property not respected when type is numeric (Chrome)

### ISSUE THREAD

**Issue by ghost** [necolas/react-native-web#1103]
**The problem**
When using the `maxLength` property of the `<TextInput>` component, it is not enforced on web when using Chrome 69.0.3497.81. The issue does not appear to be present in Microsoft Edge 40.15063.674.0, Internet Explorer 11.1088.15063.0 or Android 9. I did not test Firefox or Safari.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/501k18r7lp

**Expected behavior**
When using the `maxLength` property on a `<TextInput>` component, it is respected on web regardless of browser.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.9
* React (version): 16.4.1
* Browser: Chrome 69.0.3497.81 (see above for full list tested)
This is my first use with RNW so I have no previous versions to compare against.

**Comment by necolas** [comment]
Unfortunately the web decided `maxlength` doesn't apply to `type=number`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength. This is something we can probably fix inside `TextInput`

**Comment by komcal** [comment]
@necolas should we handle `maxlength` in `_handleChange` in `TextInput` ?
I can help to fix.

**Comment by necolas** [comment]
Sure. I'll review a PR for this

**Comment by pcooney10** [comment]
@necolas could we possibly just remove these lines? Or would that have a negative impact on accessibility/functionality: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TextInput/index.js#L232-L235

React Native / React Native Web still treats the input value a as string, so even though we set `type = 'number'` on the DOM element, `onChangeText` will always pass back a string. [Example](https://codesandbox.io/s/nk484m6mq4)

We would lose the benefit of `<input type="number" />` only permitting numeric values, but `keyboardType="numeric"` would still function as described in the RN docs (displaying a numeric keyboard).

**Comment by necolas** [comment]
This is probably fixed by 9ed0c407a93e55db6550f0322923546f74fa0e39
