### ISSUE TITLE
TouchableHighlight crashes when children are wrapped in Fragment

### ISSUE THREAD

**Issue by nickjanssen** [necolas/react-native-web#1105]
**The problem**
In React Native, you can wrap children of a TouchableHighlight in a Fragment to get around the problem of having to forward setNativeProps. This crashes in RNW.

**How to reproduce**

Snack: https://snack.expo.io/@laska/touchablehighlight-with-fragment (works)
Codesandbox: https://codesandbox.io/s/94o324mj1y (same code, crashes)

**Expected behavior**

Not crashing? Not sure what's expected actually or if this is a bug in RN.

**Environment (include versions). Did this work in previous versions?**

* React Native (Expo): 0.55.4 (expo SDK 29)
* React Native for Web (version): 0.8.x
* React (version): 16.4.0
* Browser: Chrome 68.0 (macOS)

**Additional context**

I'm confused on how this is supposed to work. Is this a bug on the React Native side? 
A TouchableHighlight can only have 1 child, but apparently wrapping it in a Fragment works. Is this intended?

**Comment by patsissons** [comment]
Not sure if this is related or if it's a separate issue, but `TouchableHighlight` is also causing issues with the [`_setChildRef`](https://github.com/necolas/react-native-web/blob/8ce5750d3437d1caa3d74a74a3625c70c54b66ab/packages/react-native-web/src/exports/TouchableHighlight/index.js#L267) assignment when the child is a functional component. In this case, wrapping the child in a `<View />` solves the problem. I ran into this while playing with `react-native-web` and `react-native-elements` (more details in https://github.com/react-native-training/react-native-elements/issues/1456#issuecomment-464591791).
