### ISSUE TITLE
Add object spread to babel config

### ISSUE THREAD

**Issue by jaredreich** [necolas/react-native-web#1108]
**Is your feature request related to a problem? Please describe.**
When trying to use `react-navigation` in a `react-native-web` app, you can never compile, because of something like this:
```bash
./node_modules/react-navigation/src/views/StackView/StackViewTransitionConfigs.js
Module parse failed: Unexpected token (100:6)You may need an appropriate loader to handle this file type.
   if (transitionConfigurer) {
     return {
       ...defaultConfig,
       ...transitionConfigurer(transitionProps, prevTransitionProps, isModal),
     };
```
I think it's because the babel config that ships with `react-native-web` doesn't have object spread support.

**Describe a solution you'd like**
Adding a later staged babel preset to `react-native-web`'s inner babel config

**Describe alternatives you've considered**
Tried ejecting, and manually adjusting the babel config with:
`babel-preset-stage-2`,
`babel-plugin-transform-object-rest-spread`,
and a few others, but nothing seemed to work.

EDIT:
Currently trying my hand at making a PR for this... but confused since `babel-plugin-transform-object-rest-spread` is already part of the babel config.

**Comment by necolas** [comment]
You can follow this guide - https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md - or ask react navigation to compile their code before publishing to npm. This repo only uses Babel internally and doesn't export a Babel config

**Comment by jaredreich** [comment]
@necolas Ok thank you for the help and for your work on this lib.
