### ISSUE TITLE
New accessibility props

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1112]
**Is your feature request related to a problem? Please describe.**

React Native 0.57 has added support for `accessibilityRole`, `accessibilityStates`, and `accessibilityHint`. https://facebook.github.io/react-native/blog/2018/08/13/react-native-accessibility-updates

**Describe a solution you'd like**

Map `accessibilityStates` to ARIA states like `aria-disabled`, `aria-pressed`, and `aria-selected`. Investigate other states that may fit here.

Implement `accessibilityHint` as it is done on Android: append the hint text to the `accessibilityLabel`. Consider exposing an option (e.g., on `AccessibilityInfo`) to disable hints on web, as unlike iOS (and like Android) there is no system-level option to disable hints.

**Additional context**

The current RN implementation of these props crashes on Android when the value isn't recognized, and we should fix RN so that doesn't happen as web will have more roles and states than the shared native ones. I think it's important to allow the web to support more than the limited subset of roles RN currently supports.

**Comment by alexleone** [comment]
Is this ready to be used? We use react-native-web extensively and but need to upgrade react-native to .57.
