### ISSUE TITLE
problems with updated dependencies

### ISSUE THREAD

**Issue by PrinzAndreVonLandmann** [necolas/react-native-web#1114]
![image](https://user-images.githubusercontent.com/39174514/45737749-f7df0980-bbee-11e8-9eb0-9bf6a31f993c.png)
**The problem**

due some updates of other packages I always get this error (see picture)

**How to reproduce**

Steps to reproduce:
1. delete "yarn.lock", "package-lock.json" and "node_modules"
2. reinstall modules with "yarn install" or "npm install"
3."yarn web" then then error occurs 

**Expected behavior**

well I expect that it compiles the same as it does with the old modules

**Environment (include versions). Did this work in previous versions?**
thats my package.json:
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.2.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@fortawesome/free-solid-svg-icons": "^5.2.0",
    "@fortawesome/react-fontawesome": "0.1.0-11",
    "@types/react": "^16.4.7",
    "@types/react-native": "^0.56.4",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "d3": "^5.5.0",
    "prop-types": "^15.6.2",
    "react": "16.3.1",
    "react-art": "^16.4.1",
    "react-d3-speedometer": "^0.3.2",
    "react-dom": "^16.4.1",
    "react-native": "~0.55.2",
    "react-native-dialog": "^5.1.0",
    "react-native-easy-toast": "^1.1.0",
    "react-native-i18n": "^2.0.15",
    "react-native-module": "0.0.1",
    "react-native-speedometer-chart": "^0.6.2",
    "react-native-web": "^0.8.6",
    "react-navigation": "^2.5.5",
    "rnpm": "^1.9.0",
    "typescript": "^2.9.2",
    "webpack": "^4.16.1",
    "webpack-dev-server": "^3.1.4"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-react-native-web": "^0.4.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-imports": "^1.4.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-react-native": "4.0.0",
    "css-loader": "^0.28.7",
    "eslint": "^4.0.0",
    "file-loader": "^1.1.7",
    "jest": "22.4.3",
    "prettier": "^1.13.5",
    "react-native-scripts": "latest",
    "react-test-renderer": "16.3.1",
    "style-loader": "^0.19.0",
    "url-loader": "^1.0.1",
    "webpack": "^4.14.0",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4"
  },

with this package.json AND package-lock.json everything works fine 
but with exactly the same package.json whithout a lock-file present I get the error

**Comment by necolas** [comment]
Update react to 16.4, update babel-plugin-react-native-web to the same version as rnw

**Comment by PrinzAndreVonLandmann** [comment]
Thanks necolas. 
Due your suggestet version cahnges the compiler-errors vanished but the error just moved to the console in the browser
is this still relatetd to the previous problem or a seperate problem?


![image](https://user-images.githubusercontent.com/39174514/45866115-001a7e80-bd80-11e8-9b9b-8390bbebf64d.png)

**Comment by grit96** [comment]
@PrinzAndreVonLandmann this is related to a bug in react-navigation https://github.com/react-navigation/react-navigation/issues/5004

**Comment by PrinzAndreVonLandmann** [comment]
@grit96 
Thanks! seems thats was the problem  
well I now got a mobx problem but that seems unrelatet to this here
