### ISSUE TITLE
Viro React implementation

### ISSUE THREAD

**Issue by MirkoAlo** [necolas/react-native-web#1121]
Thank for this amazing work, 
I tryed to implement viroreact but whitout success I don’t know if is possible... Do you have some advices? Thank you in advance

**Comment by necolas** [comment]
Sorry I don't know what you're taking about

**Comment by MirkoAlo** [comment]
Hi necolas! ViroReact is a framework for Ar/Vr that’s run on react native... I want use it on react-native-web but doesn’t work... I paste the link of viroReact here: https://viromedia.com/viroreact/

Thank you and I hope you can help me

**Comment by necolas** [comment]
I don't know how that library works (not open source) but it probably uses native Apis and doesn't work on web
