### ISSUE TITLE
How to add react-native-web to an existing react-native app?

### ISSUE THREAD

**Issue by hszeto** [necolas/react-native-web#1126]
Is adding react-native-web to an existing react-native app possible? if so, is there a how-to detailing the steps? Thanks.

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md#web-packaging-for-existing-react-native-apps

**Comment by ataravati** [comment]
@necolas I followed the instructions on that link, but it didn't work. There are so many missing pieces. The webpack config file is referring to an index.web.js file, but there's no information on how to create that. Also, how to config the babel config file?
