### ISSUE TITLE
Using onLayout causes memory leak

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#1133]
**The problem**
Running through memory traces of Twitter, one large source of held memory was Views being held by the resize observer. In poking around in this area, I see that there's a mapping of ids to component instances that's held by `applyLayout` so that when Resize observer calls back, it can notify the component instance. However there's a mismatch in the mapping logic.

When observing, we either assign the generated id to the node if it exists, or the instance if not:
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/applyLayout/index.js#L49-L63

When unobserving however, we always assume the id lays on the instance.
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/applyLayout/index.js#L65-L76

This means that when removing, we do not remove the component instance from the map and it's therefore retained by JS even after unmounting.

**How to reproduce**
I don't have a good test case / link here as determining this requires changing RNW itself to log or doing heap traces. One way to verify this is to alter RNW to log `registry[instance._layoutId]` in the `unobserve` function. You'll notice it's undefined.

**Expected behavior**
The applyLayout method should allow components to fully clean up after themselves.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): > 0.9.0
* React (version): Any
* Browser: Any

**Fix**
I've attached a sample fix, but there's many ways of getting similar behavior.

**Comment by giuseppeg** [comment]
ew man, test-less development 😅 sorry for the bugs
