### ISSUE TITLE
Support for react-native .57

### ISSUE THREAD

**Issue by alexleone** [necolas/react-native-web#1135]
**Is your feature request related to a problem? Please describe.**
Yes, the react-native-web library breaks when using react-native .57.

**Describe a solution you'd like**
The library to work with the latest react-native. 

**Describe alternatives you've considered**
Trying to help contribute to this project to support the effort for making it work with react-native .57.

**Comment by necolas** [comment]
Yeah I don't think I need an issue to track this. But explaining details is more helpful than "it breaks"

**Comment by AaronFriel** [comment]
Hey @alexleone, what issues did you have with targeting React Native 0.57? I was able to get this working tonight without too much work, perhaps my second commit on this repo will help? https://github.com/AaronFriel/react-native-web-ts-starter

**Comment by dagatsoin** [comment]
I hook here instead of opening another useless issue. Is there any roadmap to know the priorities of the development?

@necolas I am developing a cross platform UI and would like to stick to the latest expo version, so the latest RN version.
The readme states that the actual compatible version is 0.55. Is it the minimum requirements or a fixed dependency version?

Thx.

**Comment by jstheoriginal** [comment]
I attempted to upgrade to RN 0.56/0.57 but hit issues with jest/enzyme no longer working correctly for web tests.

One example I remember is that all RN components like `View`, `Text`, etc. in snapshot tests changed to all be `Component` instead.

**Comment by dagatsoin** [comment]
Ok, so it seems that RNW takes the RN version as a strict version dependency. As this plugin is so popular, would not be possible to write a contribution guide for updating monthly to the next version ?

**Comment by necolas** [comment]
It's not a strict dependency, as you can see there is no direct dependency on RN. Stuff that was introduced in RN >0.55 won't work. And the changes internally are quite large at the moment

**Comment by dagatsoin** [comment]
Thx for the precisions :)

**Comment by ggdegreat** [comment]
Hopely it will support 0.57 later. most of new projects are using the latest version of RN.

**Comment by necolas** [comment]
1172
