### ISSUE TITLE
Unpkg bundle file for this repo

### ISSUE THREAD

**Issue by gwenf** [necolas/react-native-web#1139]
I'm working on a project that necessitates a cdn link instead of an npm module for this. Can we make this project work with unpkg.com?

https://unpkg.com/#/

**Comment by necolas** [comment]
Doesn't it already? Using an externalCDN is a bad idea though, because you won't be able to take advantage of tree-shaking or import rewriting to limit the bundle size to what you're actually using

**Comment by gwenf** [comment]
I have to use a cdn. I thought that there was some configuration needed, but I guess it shows up here: https://unpkg.com/react-native-web@0.9.3/dist/cjs/index.js

**Comment by gwenf** [comment]
Thanks for your help.
