### ISSUE TITLE
Add clipPath to allowed ViewStylePropTypes for web platform

### ISSUE THREAD

**Issue by reicheltp** [necolas/react-native-web#1141]
**Is your feature request related to a problem? Please describe.**
`ViewStylePropTypes` allows several properties dedicated for platform web, among others: `clip`. As `clip` is deprecated in favor of `clip-path` (see https://developer.mozilla.org/en-US/docs/Web/CSS/clip) and `clip-path` is supported in all major browser engines (except Edge) we should add `clipPath` as allowed `ViewStylePropTypes` to prevent the following runtime error:

> Warning: Failed prop type: Invalid props.style key `clipPath` supplied to `View`.

**Describe a solution you'd like**
Add `clipPath: string` to `ViewStylePropTypes`.

PR follows.

**Comment by necolas** [comment]
Closing for the same reason as the linked PR
