### ISSUE TITLE
Provide API for transformation of CSS properties

### ISSUE THREAD

**Issue by nathggns** [necolas/react-native-web#1144]
**Is your feature request related to a problem? Please describe.**

React Native Web makes a number of transformations to style sheets for you:

Some of these are:

- Adding vendor prefixes
- Converting JSS property names like `borderRadius` to `border-radius`
- Converting React Native properties like `padding-vertical` to `padding-top`, `padding-bottom`
- Adding units to React Native values where you would expect them.
- Converts an object of style definitions into a CSS string 
- Expands properties like `border-width` to `border-top-width`, `border-bottom-width`, etc

Broadly speaking, I believe these are done in two internal parts of the `StyleSheet` API, `createReactDOMStyle` and `createRuleBlock`.

Currently, you can make use of these with the use of `getStyleSheet`, which will return your "transformed" styles as a `style` React component. 

However, it is not possible to arbitrarily use these APIs without reaching into internals of RNW. 

**Describe a solution you'd like**

A public API for applying these transformations to an object of styles, with the **option** of applying each transformation

It could look like the following:

```js
StyleSheet.transform({
    borderRadius: 5,
    paddingVertical: 10,
    lineHeight: 1.5
}, {
    applyVendorPrefixes: true,
    hyphenateProperties: true,
    normalizeValues: true,
    expandCSSProperties: true,
    expandReactNativeProperties: true,
    convertToCSS: true
})
```

which would return

```
-webkit-border-top-left-radius: 5px;
-moz-border-top-left-radius: 5px;
-ms-border-top-left-radius: 5px;
border-top-left-radius: 5px;
-webkit-border-top-right-radius: 5px;
-moz-border-top-right-radius: 5px;
-ms-border-top-right-radius: 5px;
border-top-right-radius: 5px;
-webkit-border-bottom-right-radius: 5px;
-moz-border-bottom-right-radius: 5px;
-ms-border-bottom-right-radius: 5px;
border-bottom-right-radius: 5px;
-webkit-border-bottom-left-radius: 5px;
-moz-border-bottom-left-radius: 5px;
-ms-border-bottom-left-radius: 5px;
border-bottom-left-radius: 5px;
padding-top: 10px;
padding-bottom: 10px;
line-height: 1.5
```
The optional transformations should be self explanatory, but in case they are not

**applyVendorPrefixes** – Duplicate each property with the required vendor prefixes
**hyphenateProperties** – Convert `ThisIsAProperty` to `-this-is-a-property`
**normalizeValues** – Add units to the values where appropriate
**expandCSSProperties** – Expand `padding` to `padding-top`, `padding-left`, `padding-right`, `padding-bottom` etc
**expandReactNativeProperties** – Expand properties that only exist in React Native to their CSS equivalents – `padding-vertical` to `padding-top`, `padding-bottom` etc. 
**convertToCSS** – Convert the JSS object to a string of CSS declarations

**Describe alternatives you've considered**

I can kind of emulate bits of this by reaching into RNW internals, but this is brittle and is likely to break in future versions of RNW.

**Comment by nathggns** [comment]
Would also be good to provide the same transformation options for the `getStyleElement` API.

**Comment by necolas** [comment]
Why do you want this? I'm not planning to add more APIs that aren't part of RN

**Comment by nathggns** [comment]
React Native Web does a lot of work for you in terms of transforming styles that can be useful in other circumstances. We want to use it for making our snapshots more uniform with the web output, for example, as seen here: https://github.com/newsuk/times-components/pull/1420 

It would really be a shame to have to duplicate the work that RNW does, and then have to maintain parity with RNW moving forward.

Could you explain your resistance to adding new APIs? This stuff is already available, but only by using what is *essentially a private API*.

**Comment by giuseppeg** [comment]
fwiw there is an experimental API in RN to set a preprocessor for each property but it is danger-area https://facebook.github.io/react-native/docs/stylesheet#setstyleattributepreprocessor 

As far as snapshotting goes I think that you can just write a custom serializer which also leaves the `style` prop as-is?

**Comment by necolas** [comment]
I don't understand the value of the snapshots you're producing. Much of this is internals for a reason, it's an implementation detail that is not stable or something that should be a concern at the app level

**Comment by nathggns** [comment]
As in, you believe the output from this is an implementation detail?

**Comment by necolas** [comment]
Closing this as it's not something there's a compelling reason to expose in a public-facing API

**Comment by gigaSproule** [comment]
I know this is old and has been closed, but I have a reason to use this, which is the only way I can get SVGs to be displayed properly in a web view is by using the format `import { ReactComponent as SvgFile } from './file.svg';` and then exporting a function component to pass in the properties and translating the react native style to CSS for web and using the format `export const LogoEmptyWhite = LogoEmptyWhiteSvg;` for ios/android. This would be a lot easier on my end if I could utilise what you've already done in here, but maybe I'm doing something wrong? It's worth noting, that I'm having to do a similar trick for routes and some other components.

**Comment by necolas** [comment]
Use unstable_createElement to render the svg
