### ISSUE TITLE
Clipboard API value should be cached

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#1149]
**Is your feature request related to a problem? Please describe.**
Trying to dig into some performance, when we render a tweet action, we check if Clipboard.isAvailable() to know if we should show a button for that or not. While on the surface this seems fine, in tracing, it looks like these calls often force a style calculation in Chrome.

![image](https://user-images.githubusercontent.com/542149/47318191-43c30b00-d600-11e8-9078-5fef437716d9.png)

TBH, I don't fully understand why `queryCommandSupported` is causing that to happen. I tried to make a small repro, but it wasn't complex enough to trigger it. It may be because work is happening between calls to alter the styles in other components.

**Describe a solution you'd like**
In any case, caching this value seems like it wouldn't hurt too much and if it helps prevent style recalcs, that might be the most minor of wins. Every little bit counts!

**Describe alternatives you've considered**
The user of RNW could also check and cache the value locally, but doing it in RNW makes it performant by default for all.

**Comment by necolas** [comment]
Cool. No need to open an issue of you have a PR ready. Happy for the context to live with the PR
