### ISSUE TITLE
IOS ShadowPropTypes throw error

### ISSUE THREAD

**Issue by tuckerconnelly** [necolas/react-native-web#115]
Trying to add a cross-platform shadow. Added IOSShadowPropTypes, elevation, and boxShadow, but getting:

```
Warning: Failed propType: Invalid props.style key `shadowColor` supplied to `View`.
```

Only happens if I use `<View>`, doesn't happen if I use a `<div>`.

Edit:

Got around this by conditionally applying styles:

```js
if(Platform.OS === 'web') styles.shadows = '...'
```

New to React Native, does it automatically filter out `elevation: 2` if you're running ios? Or do you always need to conditionally apply styles? Should react-native-web filter out ios- and android-only styles?

**Comment by necolas** [comment]
Yeah I think it should allow unsupported platform-specific styles without blowing up.

**Comment by necolas** [comment]
On the other hand, React Native is going to produce warnings for any web-specific properties it's not currently aware of

**Comment by tuckerconnelly** [comment]
Probably should use `Platform.OS` until this or something similar gets merged into React Native :P

**Comment by ciaran-stackworx** [comment]
I can submit a pr to change the invariant to a fbjs warning, but how should this behaviour be controlled? I am guessing we should make it opt in @necolas ?

**Comment by necolas** [comment]
This is currently a development-mode warning, which seems this the right approach for now. It will let people know which style props are not supported on Web.
