### ISSUE TITLE
On deploy, 504 gateway timeout

### ISSUE THREAD

**Issue by English3000** [necolas/react-native-web#1152]
Deployed [`create-react-native-app --with-web-support`](https://github.com/English3000/svg-practice) via Gigalixir _([backend](https://github.com/English3000/Elixir/tree/master/functional_design/islands) successfully deployed already)_.

Getting [`504 gateway timeout`](https://play-islands.gigalixirapp.com/) and this Firefox error:

> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. 

* React Native for Web (version): `^0.8.9`

**Comment by necolas** [comment]
Not related to RNW

**Comment by English3000** [comment]
@necolas  So it seems if a project is for mobile, you can build from the `crna` repo, but if you're using the exact same code for (mobile) web, you need to move it into your backend project's `js` directory... (since there's no web build for the standalone `crna` repo).

**Comment by English3000** [comment]
`create-react-app` generates a build. I'm confused why when I do `npm run build`, I don't see a `build` folder...

**Comment by English3000** [comment]
Yup, [forgot 2 lines of config](https://gigalixir.readthedocs.io/en/latest/main.html#id1) in `prod.exs`
