### ISSUE TITLE
shiftKey on nativeEvent for Touchables

### ISSUE THREAD

**Issue by nickdima** [necolas/react-native-web#1153]
**Is your feature request related to a problem? Please describe.**

I need to add a separate action for when the user shift clicks on a Touchable element.

**Describe a solution you'd like**

Attaching shiftKey to the nativeEvent object

**Describe alternatives you've considered**

Implementing button components separately for mobile and web

**Additional context**

**Comment by necolas** [comment]
What's the actual problem / use case?

**Comment by dcalhoun** [comment]
@necolas if I'm not mistaken, I believe the goal is determine if specific keys are pressed during a mouse event for a Touchable.

I just ran into this myself. I would like to ignore Touchable clicks (and let the browser handle it) if the user is attempting open a link in a new tab/window, similar to how [Next.js `Link` does](https://github.com/zeit/next.js/blob/d0dd1bc28d354262746eb33020614b3544e83835/packages/next-server/lib/link.js#L60-L64).

Do Touchables pass along the [properties that React includes for mouse events](https://reactjs.org/docs/events.html#mouse-events)?

**Comment by necolas** [comment]
You can't do that from application code using Touchables. The Responder Event System doesn't use `click` events and won't pass them through to the press handlers. There's some library code that's meant to handle this case - https://github.com/necolas/react-native-web/blob/506dba933ce69830feaace08aee85c38ce3e59fb/packages/react-native-web/src/exports/createElement/index.js#L69-L79 - but if it's not working we'll have to look at patching it

**Comment by dcalhoun** [comment]
From my brief testing, it does not appear to be working. I'll try to find some time to create a test case. It may be a few days.

**Comment by necolas** [comment]
This is something I'll look to address in a replacement for the responder system. Using and modifier key will ignore the event and allow the browser's native behavior to occur. Ref #1219

**Comment by necolas** [comment]
This should be available in 0.13 press events
