### ISSUE TITLE
Guidelines around ReactJS package Use

### ISSUE THREAD

**Issue by hobz-** [necolas/react-native-web#1154]
I'd like to start a discussion around better understanding using ReactJS packages with React Native Web. Are you able to provide any guidelines around how to determine if a package will work, or provide any context that would help me come up with a set of guidelines on my own? I'm happy to help build some documentation around this, just curious about high level insights to start with.

I have looked into some of the source for react native web, and it looks like many of the base components (View, Text, Image, etc.) return html elements that would be expected when writing plain ReactJS (div, span, input, img, etc.). What gotchas would one need to watch out for when assuming most of the elements are transpiled to html? 

Are there any concerns around how styles are handled?

Has anyone run into issues in the past using any packages that I could investigate? 

The obvious concern would be that the same packages wouldn't be usable if the code wanted to be shared for mobile devices, but this is a compromise I believe we can live with.

**Comment by necolas** [comment]
You can use any React DOM packages as long as they are only imported in a web context.

RN packages are more a case-by-case basis and anything using native code or APIs for interacting with native code will not currently work.
