### ISSUE TITLE
modality performance issue

### ISSUE THREAD

**Issue by hushicai** [necolas/react-native-web#1155]
**The problem**

Modality cause reflow/layout in chrome/safari.

And make the keyboard very slow to open in IOS.

**How to reproduce**

simple demo:

```
import React from 'react';
import {ScrollView, View, Text, StyleSheet, TextInput} from 'react-native';
import map from 'lodash/map';

const data = new Array(10000).fill(0);

class Test extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <ScrollView style={styles.scroller}>
          {map(data, (v, i) => {
            return (
              <View key={i + 1}>
                <Text>{i}</Text>
              </View>
            );
          })}
        </ScrollView>
        <View style={styles.footer}>
          <TextInput
            style={styles.input}
            placeholder={'enter...'}
            placeholderTextColor={'#ccc'}
          />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  scroller: {
    flex: 1
  },
  footer: {
    height: 36
    // width: '100%',
    // overflow: 'hidden'
  },
  input: {
    flex: 1,
    height: 36
  }
});

export default Test;
```

before remove modality, chrome performance:

![image](https://user-images.githubusercontent.com/1249423/47549560-0972aa00-d92f-11e8-9e24-e816241befaf.png)

![image](https://user-images.githubusercontent.com/1249423/47549715-8140d480-d92f-11e8-81d5-ca210547dd18.png)

As we can see, `recalculate style + layout` costs up to 200ms, maybe more!!

after remove modality in `WebStyleSheet.js`, chrome performance:

![image](https://user-images.githubusercontent.com/1249423/47549822-dbda3080-d92f-11e8-9322-2ade74f589b9.png)

Now just `recalculate style` happened, and it costs less than 1ms.

**Comment by necolas** [comment]
We'll have to look into what part is causing this issue. Maybe modifying the shared stylesheet

**Comment by giuseppeg** [comment]
Yep probably the fact that the rule is prepended to the stylesheet. @necolas I can look into this if you want.

**Comment by necolas** [comment]
Sure
