### ISSUE TITLE
Password field is not contained in a form

### ISSUE THREAD

**Issue by rickysullivan** [necolas/react-native-web#1156]
**The problem**
`[DOM] Password field is not contained in a form:`

**How to reproduce**
Simplified test case:
https://codesandbox.io/embed/7jwz9jjr1

Steps to reproduce:
1. Add `secureTextEntry` to a `TextInput` field.

**Expected behavior**
No warnings from the browser.

* React Native for Web (version): 0.9.4
* React (version): 16.5.1
* Browser: Chrome - 70.0.3538.77

**Comment by rickysullivan** [comment]
Actually. I think I can just use `createElement` to fix it: https://github.com/necolas/react-native-web/blob/master/docs/guides/advanced.md#use-with-existing-react-dom-components

https://codesandbox.io/s/o58wj146q9

**Comment by necolas** [comment]
Use `accessibilityRole=form` on the outer View

**Comment by rickysullivan** [comment]
So I've just upgraded to RN 59 and my native build is throwing an error `Invalid accessibility role value: form`

**Comment by necolas** [comment]
Use `Platform.select`

**Comment by yangm97** [comment]
> Use `accessibilityRole=form` on the outer View

Typescript doesn't seem to like it.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ab1857bbabd9c11d593c5f13fdd0c18ac857884a/types/react-native/v0.65/index.d.ts#L2236:L2263
