### ISSUE TITLE
Batching issues with images

### ISSUE THREAD

**Issue by gre** [necolas/react-native-web#116]
I have about 100 images in a page and I'm using Image#onLoad to handle the visibility (e.g a view hides the Image until it is loaded) as well as doing smart replacement of that image into another image (first loading the thumbnail, then displaying a better image). It's the same code used on a React Native app and it works perfectly there. It also works great in react-web.
But **when using with react-native-web something weird happen, my React rendering takes up to 15s to finish!** When I inspect performance, I see a huge stack of `batchedUpdates`: 
<img width="592" alt="screen shot 2016-03-29 at 12 57 32" src="https://cloud.githubusercontent.com/assets/211411/14105768/da0f0d06-f5ad-11e5-9043-bdf0d155772b.png">

I am wondering if react-native-web should do something about it or if I should deal with a different Batching Strategy on my side (also i'm very curious why react-web works just fine there).

I should try to provide a minimal example to try to reproduce this as I can't share code of my app.

**Comment by gre** [comment]
there must be something weird somewhere, because I can't repro yet on a simple example..

**Comment by gre** [comment]
do you have any hint on what causes this and what's the best way investigating on this problem? thanks

**Comment by necolas** [comment]
Maybe you don't see anything with react-web because it doesn't implement most of `Image` (including `onLoad`)? See: https://github.com/taobaofed/react-web/blob/master/Libraries/Image/Image.web.js

Are you loading 100 images at once over the network? If the rendering blocking everything else or is it happening just on individual images after the network image has loaded? Did you test case load images over the network too?

**Comment by gre** [comment]
These are images over the network, there must be some where setState cascading somewhere, I even tried to disable the "cache" in Chrome Debugger.. I need to give a stronger try soon on investigating/trying to reproduce this on a simple example.

**Comment by necolas** [comment]
Did you ever get a chance to look into this?

**Comment by gre** [comment]
sorry, I ended up simplifying my project to actually just implement things from scratch using react-dom.
Maybe the bug is gone now?
