### ISSUE TITLE
pan-x/pan-y make nested ScrollView failed to Scroll

### ISSUE THREAD

**Issue by hushicai** [necolas/react-native-web#1160]
**The problem**

nested ScrollView can not scroll properly in some android devices.

**How to reproduce**

simple demo:

```
class Test extends React.Component {
  render() {
    return (
        <ScrollView>
          <View>
            <Text>row1</Text>
          </View>
          <View>
            <Text>row2</Text>
          </View>
          <View>
            <Text>row3</Text>
            <ScrollView horizontal={true}>
              <View>
                <Text>1</Text>
              </View>
              <View>
                <Text>2</Text>
              </View>
            </ScrollView>
          </View>
        </ScrollView>
    );
  }
}
```

It is because that horizontal ScrollView only allow touch action `pan-x`, so if you move on the horizontal ScrollView and swipe down to scroll the outside ScrollView, it will fail, outside ScrollView does not scroll at all!

**Expected behavior**

nested ScrollView should not affect outside ScrollView!

I think `pan-x/pan-y` should be removed  at this point.

**Comment by necolas** [comment]
Good spot. Thanks for helping to make this project better by reporting these issues and making PRs 👍
