### ISSUE TITLE
React-native-web how to jump to the page?

### ISSUE THREAD

**Issue by zhushichuan** [necolas/react-native-web#1162]
React-native-web how to jump to the page?

**Comment by necolas** [comment]
I don't know what you mean

**Comment by zhushichuan** [comment]
I use error-native-Navigation in react-native-web to report an error, I want to know if there are other libraries that can be used in react-native-web.

**Comment by zhushichuan** [comment]
> I don't know what you mean
I use error-native-Navigation in react-native-web to report an error, I want to know if there are other libraries that can be used in react-native-web.
