### ISSUE TITLE
Touchable: layout is measured during touch-scroll event

### ISSUE THREAD

**Issue by hushicai** [necolas/react-native-web#1166]
**The problem**

As mentioned in #1157, Touchable `_remeasureMetricsOnActivation` was called when we touch to scroll, and cause  browser  Layout due to the `getRect`:

![image](https://user-images.githubusercontent.com/1249423/48052526-29358800-e1e3-11e8-9736-d95286692f49.png)

I have find out that it is called on native too.

![image](https://user-images.githubusercontent.com/1249423/48052994-723a0c00-e1e4-11e8-9077-9a36fdd27719.png)

But there is no performance problem in native.

Browser Layout costs so much times, making the scroll performance so bad!

**How to reproduce**

A large List, with Touchable items, can reproduce the problem.

```js
<ScrollView>
   // the more complicated of the TouchableOpacity view tree, the easier to reproduce.
  <TouchableOpacity style={styles.item}></TouchableOpacity>
  // ...
  // ...
  // ...
</ScrollView>

const styles = StyleSheet.create({
  // The bigger the visual rect, the easier to reproduce.
  item: {width: '100%', height: 100} 
});
```

**Expected behavior**

Hope to look for a solution, and improve the scroll performance.

**Comment by hushicai** [comment]
Use `TouchableWithoutFeedback` instead of `TouchableOpacity` in my large FlatList, solved the peformance problemn.

And there is not `Layout` performance now:

![image](https://user-images.githubusercontent.com/1249423/48116195-4bd9a680-e2a0-11e8-8eb6-b935fba3c0df.png)

**Comment by hushicai** [comment]
Maybe settting `opactiy` and  `getRect` in the meantime cause  this problem?

**Comment by necolas** [comment]
Interesting! Thanks for investigating. How does TouchableHighlight look? I wonder if using `will-change:opacity` helps the browser to optimize this path and avoid triggering layout on other elements

**Comment by necolas** [comment]
The touchables are going to change in RN. If there's nothing we can do for web (rAF, will-change, etc) then I'll bring the issue of performing layout measurement during scroll with the team. I think it's probably good to avoid that situation in general. Thanks again for continuing to look into layout perf 😍

**Comment by hushicai** [comment]
`will-change` is useless, maybe useful for `repaint`.

![image](https://user-images.githubusercontent.com/1249423/48175289-59496c00-e346-11e8-87b7-7119262a4329.png)

It will lift up lots of `Compositing Layers`, which increase memory:

![image](https://user-images.githubusercontent.com/1249423/48174960-f0adbf80-e344-11e8-9e7d-63b268aa08c4.png)

I suggest to delay highlight with `TouchableOpacity` for now, it is very useful for quick scrolling in large FlatList.

**Comment by necolas** [comment]
If it's about the opacity, transitioning to 0.99 instead of 1.0 used to be a hack to avoid browsers doing extra work.

Changing the delay will make it inconsistent with RN and doesn't fix cases where people are setting their own short delays

**Comment by necolas** [comment]
This is something I think we can fix by replacing RN's `Touchable` mixin with a hook that implements slightly different behaviour (that also feels more native to the web) to avoid measuring views during the user interaction.

**Comment by necolas** [comment]
Please try version `0.0.0-33f8505d6` (a canary release). This problem should be resolved. See  #1538
