### ISSUE TITLE
Upgrade to Babel 7

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1170]
Looking for someone to help upgrade the internal tools and the published babel plugin to rely on Babel 7.

**Comment by murtraja** [comment]
I don't have much experience using React Native but I want to contribute. Please do provide some pointers to help beginners get started on this Good First Issue.

Looking at [package.json](https://github.com/necolas/react-native-web/blob/master/package.json) and [babel preset](https://github.com/necolas/react-native-web/blob/master/scripts/babel/preset.js), I am guessing that we are using Babel 6 plugins that need to be converted to Babel 7 by following this [migration guide](https://babeljs.io/docs/en/v7-migration) from the Babel folks

**Comment by necolas** [comment]
This is done in branch `react-native-0.57`
