### ISSUE TITLE
ScrollTo not working on Horizontal ScrollView

### ISSUE THREAD

**Issue by murtraja** [necolas/react-native-web#1173]
**ScrollTo not working on Horizontal ScrollView**

**How to reproduce**

[Reproducible Demo](https://codesandbox.io/s/130z3pro67)

Steps to reproduce:
1. Add a horizontal prop to ScrollView
2. Register a ref
3. Use it to fire ScrollTo, notice that it doesn't work, but works when horizontal prop is removed

**Expected behavior**
The ScrollView should scroll horizontally

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.9.6 
* React (version): 16.6.0
* Browser: Firefox 63.0 (Works on Chrome Version 69.0.3497.100 (Official Build) unknown (64-bit))

OPTIONAL:

**Additional context**
Creating new issue as requested in #956
 
I am trying to implement [draggable scrolling](https://stackoverflow.com/a/40985662/9167004).

**Comment by murtraja** [comment]
Ahh, yes it does indeed! Sorry for that. 

It doesn't work on Firefox 63.0 (64-bit) though

**Comment by necolas** [comment]
Hmm this seems to be caused by `scroll-behavior:smooth` but I can't reproduce it in a simple JS example https://codesandbox.io/s/jnplz8p9j5

**Comment by brunolemos** [comment]
Can confirm horizontal `scrollToIndex` doesn't work on Firefox, got a couple reports about this on DevHub. And on Safari (desktop or mobile) it works, but without the animation.

**Comment by brunolemos** [comment]
I was investigating this issue on Firefox and seems to be caused by this line:

https://github.com/necolas/react-native-web/blob/4b3f6efb21edaeea48a14e581491bcaf72f9e3bf/packages/react-native-web/src/modules/ScrollResponder/index.js#L378

Removing `scrollBehavior` makes it work (but without the animation).
It seems #1203 have the same conclusion and proposed a solution.

**Comment by necolas** [comment]
Yeah that confirms my findings in https://github.com/necolas/react-native-web/issues/1173#issuecomment-439562522

**Comment by murtraja** [comment]
I can confirm that this issue is fixed in 0.9.13
Thanks @kristerkari @brunolemos @necolas
