### ISSUE TITLE
StrictMode

### ISSUE THREAD

**Issue by unindented** [necolas/react-native-web#1180]
**Is your feature request related to a problem? Please describe.**
Some upcoming React features are only going to work in `AsyncMode`.

**Describe a solution you'd like**
Solution seems to be to drop legacy context, hooks (e.g. `componentWillReceiveProps`) and methods (e.g. `findDOMNode`).

**Describe alternatives you've considered**
I don't know if there are alternatives

**Additional context**
Right now my app throws warnings for every RNW component:

<img width="1440" alt="screen shot 2018-11-18 at 5 26 52 pm" src="https://user-images.githubusercontent.com/69485/48681411-2d549480-eb57-11e8-9d3e-75f7c28e7049.png">

**Comment by unindented** [comment]
@necolas if you have a plan for how to migrate to the new context API, I can help execute.

**Comment by necolas** [comment]
Thanks. See https://github.com/necolas/react-native-web/issues/1172 and the React Native JS

**Comment by unindented** [comment]
Ah, nice. I'll close this one then.
