### ISSUE TITLE
`accessibilityElementsHidden` warning

### ISSUE THREAD

**Issue by eightyfive** [necolas/react-native-web#1187]
**The problem**
Console shows [`accessibilityElementsHidden`](https://facebook.github.io/react-native/docs/accessibility#accessibilityelementshidden-ios) property warning

**How to reproduce**
```js
<View accessibilityElementsHidden />
```

**Expected behavior**
No console warning

**Environment (include versions)**

* React Native for Web (version): ^0.9.4
* React (version): ^16.6.0
* Browser: Chrome

![Image of Yaktocat](https://user-images.githubusercontent.com/929878/48877744-ee208f00-ee47-11e8-84b9-83fad1646f58.png)

**Comment by necolas** [comment]
accessibilityElementsHidden isn't part of the RN 0.55 API

**Comment by eightyfive** [comment]
I don't see it in:
[src/exports/View/filterSupportedProps.js](https://github.com/necolas/react-native-web/blob/2b4fd63f646ff3fab689f22aab812e97326adcac/packages/react-native-web/src/exports/View/filterSupportedProps.js)

([commit](https://github.com/necolas/react-native-web/commit/2b4fd63f646ff3fab689f22aab812e97326adcac#diff-6ef4ddb537353c33d07911750fa6f200))

**Comment by necolas** [comment]
Well you're adding it to Text, not View

**Comment by eightyfive** [comment]
Im sorry Im confused. I did not add anything, I was just copying one of your commit for RN 0.57 support.

**Comment by necolas** [comment]
Fixed by 1ad16930391303da511c98879fa7b2002b28c822
