### ISSUE TITLE
ActivityIndicator: insert keyframes css rule cause "SYNTAX_ERR: DOM Exception 12".

### ISSUE THREAD

**Issue by hushicai** [necolas/react-native-web#1199]
**The problem**

In ActivityIndicator, insert keyframes css rule cause "SYNTAX_ERR: DOM Exception 12" in Android 5.1.

if i change keyframes prefix to:

![image](https://user-images.githubusercontent.com/1249423/49784952-d444de80-fd59-11e8-99c5-ecabcb3a5288.png)

Everything become ok!

I don't know why! 

Here is some debug log:

![image](https://user-images.githubusercontent.com/1249423/49784230-84fdae80-fd57-11e8-9797-d39d3ed42e9e.png)

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version):0.9.6
* React (version): 16.0.0-beta.5
* Browser: Android 5.1 HuaWei Browser

**Additional context**

https://bugs.chromium.org/p/chromium/issues/detail?id=136043&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

https://heycam.github.io/webidl/#syntaxerror

**Comment by hushicai** [comment]
It seams that catching `insertRule` fixed my problem:

![image](https://user-images.githubusercontent.com/1249423/49787665-3efa1800-fd62-11e8-8563-8547cde89fa6.png)
 
And `ActivityIndicator` rotates normally.

Maybe it is a browser bug, there is nothing wrong with the css rule, but inserting the rule cause exceptions, so I think `insertRule` should be catched to prevent such problems.

**Comment by hushicai** [comment]
Maybe old android browser considers that `@keyframes` is not illegal, because it only support `@-webkit-keyframes`? and cause the `SYNTAX_ERR`.

**Comment by necolas** [comment]
Yes maybe. Please could you try inserting unprefixed keyframe rule with / without prefixed properties (like transform)?

**Comment by koulmomo** [comment]
similar to the issue described here: https://github.com/styletron/styletron/pull/282

**Comment by necolas** [comment]
related fix for non-keyframes is here: https://github.com/necolas/react-native-web/blob/0.9.9/packages/react-native-web/src/exports/StyleSheet/initialRules.js#L10

**Comment by hushicai** [comment]
@necolas 

I tried it like this:

```
const safeRule = rule => `@media all{\n${rule}\n}`;
const k1 = `
  @keyframes k1 {
    0%{transform: rotate(0deg);}
    100%{transform: rotate(360deg);}
  }
`;
const k2 = `
  @keyframes k2 {
    0%{-webkit-transform: rotate(0deg); }
    100%{-webkit-transform: rotate(360deg); }
  }
`;
const k3 = `
  @-webkit-keyframes k3 {
    0%{-webkit-transform: rotate(0deg); transform: rotate(0deg); }
    100%{-webkit-transform: rotate(360deg); transform: rotate(360deg); }
  }
`;
webStyleSheet.insertRuleOnce(safeRule(k1)); // failed
webStyleSheet.insertRuleOnce(safeRule(k2)); // failed
webStyleSheet.insertRuleOnce(safeRule(k3)); // success
```

only `-webkit-keyframes` can work in my case.

**Comment by necolas** [comment]
Please try this patch and let me know if you're still seeing errors: https://github.com/necolas/react-native-web/pull/1210

**Comment by hushicai** [comment]
Thanks, i will try it soon.
