### ISSUE TITLE
TextInput: implement `placeholder` and `placeholderTextColor`

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#12]
Looks like placeholder will need to be reimplemented because we can't get at the shadow DOM without a CSS pseudo-element selector.

**Comment by gary-domain** [comment]
placeholderTextColorThis was reverted in https://github.com/necolas/react-native-web/commit/89f5a13891a5c99f5a25bfb95ee8d54a91595b4f

Should we re-open this issue?

**Comment by wordyallen** [comment]
Any status on whether or not `placeholderTextColor` will be reimplemented?
