### ISSUE TITLE
Scroll behaviour changed in 0.6.0?

### ISSUE THREAD

**Issue by JerryGreen** [necolas/react-native-web#1207]
I found that something changed with the scroll behaviour in `0.6.0` (till, at least, `0.8.11`, but I believe till `0.9.9` including) - the scroll simply stopped working in my app

So I have to use `0.5.4` version

Sorry if you feel this issue is useless - it's more like a comment/discuss, than a real issue/bug (at least for me), because I'm okay with that, I don't need any functionality on top of that right now

But if you know something about that, I would appreciate your feedback - I may wanna upgrade in future

P.S. 1.0.0 is coming? wohoo!

**Comment by necolas** [comment]
Please fill out the issue template, including things like a test case. I'm closing this issue due to lack of requested information, as mentioned in the template.

**Comment by JerryGreen** [comment]
I found [an issue about this](https://github.com/necolas/react-native-web/issues/902) and [patch notes](https://github.com/necolas/react-native-web/releases/tag/0.6.0) and [one of reasons, probably](https://github.com/necolas/react-native-web/commit/a9cacb2ef5b88d815a0a87838e3da7a063c5a647)

I tried to spend a little bit of time to play with it, to add `position: absolute` on root div - but no success, so whatever, I don't need upgrade yet anyway
