### ISSUE TITLE
Using with iOS/Android dependencies

### ISSUE THREAD

**Issue by DVassilev** [necolas/react-native-web#121]
If I have created an app that requires various iOS or Android dependencies (such as google analytics etc.) is it possible to use it directly with this and make it work for web or would I have to replace the dependencies with web-compatible ones?

**Comment by necolas** [comment]
The docs suggest that you use separate files for significant cross-platform differences: index.ios.js, index.android.js, index.web.js.

You can avoid importing native dependencies into the *.web.js files.
