### ISSUE TITLE
Clipboard: add support on the Web

### ISSUE THREAD

**Issue by grigio** [necolas/react-native-web#122]
Hi, is this project going to mimic the React "Native Clipboard API"? 
It should work almost everywhere on the Web. (not in Safari because it doesn't expose a low level API)

**Comment by necolas** [comment]
How would you implement this on web?

**Comment by grigio** [comment]
I could submit a PR of `Clipboard.setString(..)` that does behind the scene something like:
```
function copytext(text) {
    var textField = document.createElement('textarea');
    textField.innerText = text;
    document.body.appendChild(textField);
    textField.select();
    document.execCommand('copy');
    textField.remove();
}
```

**Comment by grigio** [comment]
This https://github.com/necolas/react-native-web/pull/125
