### ISSUE TITLE
use StyleSheet with regular web elements?

### ISSUE THREAD

**Issue by alidcastano** [necolas/react-native-web#1221]
I know this is not the primary goal of the project, but to what extend would it be possible to use rnw's stylesheet with regular web elements - or is it meant primarily for react-native[-web] components?

Other than the `style` attribute not accepting an array, to what extent would it make sense mixing this into to a web app in place of other css-in-js libs, since I much prefer react-native's way of declaring styles

(I tried creating the styles and setting them on the className, but that didn't work, so I'm guessing it's not 100% compatible now, but opening up this issue for discussion)

**Comment by alidcastano** [comment]
here's an example of of wrapper of rnw styles I'm using, I'd love to bring this css-in-js API to the web

what I love is
- declare all styles together (rather than seperating them per component)
- mixture of both static and dynamic styles 
- could also take advanted of react hooks to further improve performance (hence `use` keyword)
- they get combined by prop key automatically, so can seperate dynamic styles for easier composition

```
const useStyles = css.combine( // organize style props by key
 css.static({ // same as StyleSheet.create
   button: {
     justifyContent: 'center',
     alignItems: 'center',
     borderWidth: 1,
     borderRadius: 5,
   },
   label: { 
     color: '#fff'
   }
 }),
// dynamic styles
 function colorStyles({ color }) {
    if (color === 'primary') {
      return {
        button: {
          backgroundColor: theme.primary,
          borderColor: theme.tertiaryDark,
        },
        label: {
          color: '#fff',
        }
      }
    } else if (color === 'secondary') {
      return {
        button: {
          backgroundColor: theme.primaryInverse,
          borderColor: theme.tertiaryDark,
        },
        label: {
          color: theme.primaryText
        }
      }
    }
  }),
function sizeStyles({ size }) {
    if (size === 'large') {
      return {
        button: {
          paddingTop: 24,
          paddingRight: 36,
          paddingBottom: 24,
          paddingLeft: 36,
        },
        label: {
          fontSize: 20
        }
      }
    } else {
      return {
        button: {
          paddingTop: 8,
          paddingRight: 36,
          paddingBottom: 8,
          paddingLeft: 36,
        },
        label: {
          fontSize: 16
        }
      }
    }
)
export default function Button({ type = {}, style, children, ...props }: Props) {
  const styles = useStyles(type)
  return (
    <TouchableHighlight style={[...styles.button, style]} {...props}>
      <Text style={styles.label}>
        {children}
      </Text>
    </TouchableHighlight>
  )
}
```

**Comment by necolas** [comment]
See https://github.com/necolas/react-native-web/blob/master/docs/guides/advanced.md#use-with-existing-react-dom-components

`StyleSheet` doesn't really makes as much sense without being combined with components like View that provide a means of dynamically changing styles in response to layout and interaction state changes.

**Comment by vrgimael** [comment]
What happened to this? Seems like arrays of styles was supported before?

https://github.com/necolas/react-native-web/commit/715c71b21564061f2c71917c53b49e9a6b92bd6a
