### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by haf** [necolas/react-native-web#1222]
**The problem**

Navigating to https://necolas.github.io/react-native-web/storybook/?selectedKind=Example%20apps&selectedStory=Calculator&full=0&addons=0&stories=1&panelRight=0 and other examples shows apps that don't work as they should.

**How to reproduce**
Go to the link and click a button on the calculator.

**Expected behavior**
The button should work and the number be displayed in the number-display.

**Environment (include versions). Did this work in previous versions?**

Don't know how/when it last worked.

* React Native for Web (version): no idea, whatever your examples run
* React (version): same
* Browser: Firefox for macOS, Chromium via Homebrew for macOS.

**Comment by necolas** [comment]
It's due to a React version mismatch in the monorepo. But I'm planning to remove the storybook for 0.10 so probably won't backport a fix

**Comment by haf** [comment]
@necolas Having samples is an excellent way of getting started. In the perfect world these samples would still be available somehow, even if not using storybook.

**Comment by necolas** [comment]
There's the entire "examples" app for that

**Comment by necolas** [comment]
They should be working again now
