### ISSUE TITLE
server-rendering styles that rely on dimension/layout APIs

### ISSUE THREAD

**Issue by alidcastano** [necolas/react-native-web#1225]
is there a way to server render styles that rely on dimensions/layout APIs? the issue that is that since the `window` object is undefined in server, the styles are rendered incorrectly.

How should one handle server-rendering responsive styles with rnw? 

Currently, I'm cloaking the app until the styles are updated with the correct dimensions.

**Comment by necolas** [comment]
See the docs for `Dimensions.set`: http://necolas.github.io/react-native-web/storybook/?selectedKind=APIs&selectedStory=Dimensions. You can use whatever means you choose to infer the dimensions of the viewport that the server is rendering for, and set them there. Layout information is not available on the server and requires a client-side render.
