### ISSUE TITLE
have AsyncStorage support cookies for ssr apps

### ISSUE THREAD

**Issue by alidcastano** [necolas/react-native-web#1232]
**Is your feature request related to a problem? Please describe.**

For ssr apps, the server doesn't have access to local storage, but it does receive the cookies with the response. So it'd be better for ssr apps to have AsyncStorage access cookies.

**Describe a solution you'd like**

I could see why local storage would be prefered for client side apps, so not sure if this is a feature for rnw. 

One alternative is to provide support for it via a different export,  i.e. `AsyncStorageCookies`, and have users alias it correctly for the web. This shouldn't be much of a difficulty since we already have to alias rnw ourselves.

Otherwise I guess the recommended solution is creating our own wrapper for `AsyncStorage` to handle this use case (this is what I'm currently doing), but figured I'd open up this issue anway for discussion

**Comment by necolas** [comment]
Working with cookies is a different use case to working with client-side storage. I don't understand why AsyncStorage should be used for both purposes.

**Comment by alidcastano** [comment]
for authentication,

in my native app I use AsyncStorage to store a session token, in my server rendered web app I alias AsyncStorage to use my cookies implementation

**Comment by necolas** [comment]
You could write your own auth module that uses `AsyncStorage` on the client and another mechanism (cookies or whatever) on the server.

**Comment by alidcastano** [comment]
ok, i'll go ahead and close this then, thanks
