### ISSUE TITLE
Work as PWA.

### ISSUE THREAD

**Issue by vlimag** [necolas/react-native-web#1236]
Hello,
I would like to know if PWA is current supported?

The app that I am integrating with react-native-web runs on chrome and safari normally.
The issue is that when I create the home shortcut, on Android, the app displays a blank screen, and on IOS the app shows up as on the Browser. (with search bar, but components are rendered normally)

And suggestion to get this solved?

Best Regards and congratulations for the initiative.

**Comment by RangerMauve** [comment]
I think that's related to configuration in your HTML file rather than any of the JS in react-native-web. 😅

I'd suggest double checking [your manifest](https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Add_to_home_screen#Manifest) and checking for errors in the dev tools.

**Comment by necolas** [comment]
This is a component library for React DOM, so it will work for any PWA. The problems you are having are unrelated to this library. Perhaps ask on Stackoverflow or similar

**Comment by pcooney10** [comment]
Hey @vlimag, as @RangerMauve and @necolas stated, this library is simply a way to render React Native components in React DOM. The way your app is bundled and distributed is entirely up to you, and out of the scope of this library.

As a suggestion, you could lean on something like `create-react-app` so you don't have to worry as much about configuring builds, and you can see an example of what that'd look like here: #1192. But as @RangerMauve said, it seems like this issue has to do with your `manifest.json`, and not the entire build in general. There is some documentation on PWA's and CRA here: https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app
