### ISSUE TITLE
Can't understand how to setup it up

### ISSUE THREAD

**Issue by fedemengo** [necolas/react-native-web#1239]
I read the "getting started" page, but I cannot understand how to setup everything. I'm new to react/react-native and I'd like to test my app on the browser. I tried to follow this [guide](https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/) but I get several compilations error and it also seems a bit outdated.  

**How to reproduce**

Simplified test case: 

From a `react-native` project, I didn't understand how to setup `react-native-web`. I used to run the project with
```
react-native run-android
```
But I have no clue what I should do with `react-native-web`

**Expected behavior**

Run the app on the browser

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: TBC

My deps in `package.json`

```
  "dependencies": {
    "babel-loader": "^8.0.5",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-native": "^0.58.3",
    "react-native-web": "^0.10.0",
    "webpack": "^4.29.1",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "^3.1.14"
  },
```

**Comment by axhamre** [comment]
Dif you read the README? Here’s a fully working exemple: https://codesandbox.io/s/q4qymyp2l6

If you intend to run a RN app in the browser it not work out-of-the-box.

**Comment by fedemengo** [comment]
Yeah, I read it but I still don't understand what I should modify in my RN android project
