### ISSUE TITLE
Document the focus-visible polyfill and how to override the focus styles

### ISSUE THREAD

**Issue by colmbrady** [necolas/react-native-web#1242]
**Is your feature request related to a problem? Please describe.**

I noticed you have recently implemented a 'focus-visible' polyfill to resolve #310. My feature request is for some documentation on best practice around using the focus indicator. 

Id specifically like to know how I can override the default focus styles the RNW way within my application.

**Describe a solution you'd like**

I would like some best practice documented with possibly a recipe.

My current solution is to add some CSS into a stylesheet like so:

```
:focus[data-rn-focusvisible-x92cna="true"] {
    outline:#204A65 solid 1px !important;
    outline-offset: -1px;
}

:focus[data-rn-x92cna="true"] {
    outline:#204A65 solid 1px !important;
    outline-offset: -1px;
}
```
 
However, im not sure if this is the recommended way to do it or should I be using the Stylesheet API to programatically add the styles when my app loads??

**Describe alternatives you've considered**

N/A

**Additional context**

Im happy to create a P.R into the documentation if I get some guidance on best practice.

**Comment by giuseppeg** [comment]
I think you could hack something like this together:

```js
function modalityStyles(sheet, resetDeclarations, declarations) {
  const selector = sheet.cssRules[0].selectorText
  if (!selector.startsWith(':focus:not(')) {
    throw new Error('could not find modality styles')
  }
  sheet.removeRule(0)
  sheet.insertRule(`${selector} { ${resetDeclarations} }`, 0)
  sheet.insertRule(`:focus { ${declarations} }`, sheet.cssRules.length)
}


modalityStyles(
  document.querySelector('#react-native-stylesheet').sheet,
  `
    outline: none;
    box-shadow: none;
  `,
  `
    box-shadow: 0 0 30px hotpink
  `
)
```

but I am not sure if @necolas wants to encourage that.

**Comment by colmbrady** [comment]
Thanks @giuseppeg 

Im happy to add a recipe for this pattern and link it to the documentation somehow if its something that @necolas thinks should be documented.

Otherwise, suggest we close the issue.

Many thanks.

**Comment by necolas** [comment]
At the moment there is no support for globally overriding the focus style. Custom focus styles must be applied on a per-component basis (but can be defined in one place and imported as needed).
