### ISSUE TITLE
incorrect flexWrap: 'wrap' behavior

### ISSUE THREAD

**Issue by gut4** [necolas/react-native-web#1243]
**The problem**
View with style: `
flexDirection: 'column',
flexWrap: 'wrap',
maxHeight: 100
` is displayed incorrectly

**How to reproduce**
https://codesandbox.io/s/k9oqk1z285

**Expected behavior**
Expo and react-native is displayed this correctly
https://snack.expo.io/Syt3vCWHV

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.10.0
* React (version): 16.8.1
* Browser: chrome

**Comment by necolas** [comment]
React Native/ Yoga will be one that gets it "wrong" compared the web standard

**Comment by gut4** [comment]
Looks like it is problem with browsers not yoga.
https://bugs.chromium.org/p/chromium/issues/detail?id=507397
https://stackoverflow.com/posts/33899301/revisions

**Comment by necolas** [comment]
Ok good to know. Either way there's nothing I can do about it
