### ISSUE TITLE
Animated.Image doesn't animate `blurRadius`

### ISSUE THREAD

**Issue by viggyfresh** [necolas/react-native-web#1244]
**The problem**
Using `Animated.Image`'s `blurRadius` property with an `Animated.Value` doesn't animate as expected - instead, it remains stuck at the original blur radius value. By extension, animating an `ImageBackground` also doesn't blur 😢

**How to reproduce**
Simplified test case: [here](https://codesandbox.io/s/43jwmwn189)

Steps to reproduce:
1. Create an `Animated.Image`
2. Try to animate its `blurRadius` property (see CodeSandbox above)

**Expected behavior**
Blur Radius should animate! See [here](https://snack.expo.io/By2_bfQHN) for functioning Expo Snack

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.10.x
* React (version): 16.5.2 in Sandbox, 16.6.x, 16.7.x, and 16.8.x in own app
* Browser: Chrome 72.0.3626.109, Safari 12.0.3 (13606.4.5.3.1)

**Additional context**
Super happy to take a look at this and file a PR, if someone can point me in the right direction!

**Comment by Dominic-Pace** [comment]
Has there been any updates on this? Running into the same exact issue.

**Comment by pisacode** [comment]
You can add an event listener to change state with the animated value as follows
`this.state.blurAnimation.addListener(({value}) => this.setState({blurValue:value}));`

**Comment by GollyJer** [comment]
Using state instead of animate works fine on iOS, but the image flickers with each state update on Android.
@viggyfresh Did you ever find a solution?

**Comment by viggyfresh** [comment]
@GollyJer i did not - will try to dig into the latest RNW code to try to see if I can track down the discrepancy. might be resolved in the latest release candidate?

**Comment by DaniAkash** [comment]
Facing this issue on both iOS & Android :(

**Comment by daxaxelrod** [comment]
Facing the issue here too with 0.61.2 on android.

**Comment by necolas** [comment]
It doesn't seem to work properly on any platform. The `blurRadius` value must be a number, it cannot be an `AnimatedValue`.

The approach @pisacode described works better across platforms:

https://snack.expo.io/W_753WCjy
