### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by hobochild** [necolas/react-native-web#1246]
Hey, :wave: 

Not sure if this has been asked recently but I'm just wondering what the status of the project is? I know there are several high-profile projects that are/were using it? Are they still using it? Is anyone sponsoring the development to keep up with RN? Are you still actively working on it?

**Comment by necolas** [comment]
Yes they're still using it and I'm still working on the project. I'm on vacation right now.

**Comment by hobochild** [comment]
Cool thanks for the quick reply, enjoy your vacay :+1:
