### ISSUE TITLE
Support for Schema code for view componet

### ISSUE THREAD

**Issue by thecachedbyte** [necolas/react-native-web#1247]
[Schema code](https://schema.org/docs/gs.html)

Currently global attributes like [itemtype](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemtype) or [itemscope](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemscope) or [itemprop](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemprop) are not present in [View filterSupportedProp](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/View/filterSupportedProps.js).

Is there any workaround already present to support schema code? or we will need to depend on custom implementation to support schema code?

**Comment by varzaman** [comment]
Was this ever implemented?

I see it was tagged for the 0.10.x milestone, but I don't actually see this functionality anywhere.

**Comment by varzaman** [comment]
Hi.
Wanted to follow up with this closed issue.

I noticed that these props don't exist in the latest versions. I was just wondering what the reason for removal was. (It just wasn't apparent to me, and I didn't find anything written in the release notes).

Thanks!

**Comment by necolas** [comment]
> Removed support for HTML microdata props. Microdata has been removed from the HTML spec.

https://github.com/necolas/react-native-web/releases/tag/0.13.0

**Comment by varzaman** [comment]
> > Removed support for HTML microdata props. Microdata has been removed from the HTML spec.
> 
> https://github.com/necolas/react-native-web/releases/tag/0.13.0

You know I just learned they were called microdata.....haha thanks for the help.
