### ISSUE TITLE
Image lazy loading support inside list component

### ISSUE THREAD

**Issue by thecachedbyte** [necolas/react-native-web#1253]
Currently, all images are loading for the list item component, even if it is not in the viewport.

Is there any existing props or workaround to support lazy loading of images?

I tried to put a wrapper of [react-lazy-load](https://www.npmjs.com/package/react-lazy-load) on top of the Image component, but the behavior is inconsistent.

**Comment by necolas** [comment]
Are you using a virtualized list?

**Comment by thecachedbyte** [comment]
I am using FlatList

**Comment by necolas** [comment]
And FlatList renders some items off screen. In the future we could include the browser's native image lazy loading but then people might complain that the images aren't yet loaded by the time they scroll into view, and all the loading event callbacks might not get called
