### ISSUE TITLE
Default styles override specified

### ISSUE THREAD

**Issue by plentylife** [necolas/react-native-web#1268]
**The problem**
I have a Text component with a custom style. The style sets the fontSize to 30.
The text component doesn't render with that style, because it get overridden by the (default) style of fontSize 14.
The Text component is wrapped in a single top level View, that has no style

**How to reproduce**
https://gist.github.com/plentylife/f4e302d6ee88f1865300d097a24983b9

**Expected behavior**
Text rendered with size 30

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.10
* React (version): 16.7.0
* Browser: Chrome

EDIT:
Interestingly enough adding `<Text style={{fontSize: 35}}>test</Text>` under the top-level View makes all styles render properly

**Comment by necolas** [comment]
Please include a codesandbox link. Then I'll reopen if that indicates a problem
