### ISSUE TITLE
Deploying application to AWS cloudfront

### ISSUE THREAD

**Issue by kluz9** [necolas/react-native-web#1271]
Hello,

I deployed my react native web app to AWS cloudfront and it works fine with the cloudfront url.

However, I added an alternate domain name and configured my DNS service to point to cloudfront distribution.

Once I do that, and I do www.mydomain.com I see an empty page.  (Just a note: accessing the page using cloudfront url still works.)
By inspecting the code I see that the title and other meta tags are rendered but script in body gives error. I see error on the console as follows

- Did not parse stylesheet at 'http://www.mydomain.com/static/css/1.ddb12958.chunk.css' because non CSS MIME types are not allowed in strict mode.
- SyntaxError: Unexpected token '<'

Any idea why ?

**Comment by necolas** [comment]
Open the CSS file and you can see that it's an HTML file.

This is a problem related to your hosting and isn't related to RNW, so I will be closing this issue.
