### ISSUE TITLE
Touchable A‘s onPress trigger the onPress of Touchable B the same place behind of A

### ISSUE THREAD

**Issue by huangxing1995** [necolas/react-native-web#1274]
**The problem**

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1.
2.
3.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: TBC

**Comment by necolas** [comment]
Please compete the template to provide the necessary details https://raw.githubusercontent.com/necolas/react-native-web/master/.github/ISSUE_TEMPLATE/bug.md
