### ISSUE TITLE
Support for `maxFontSizeMultiplier`

### ISSUE THREAD

**Issue by janicduplessis** [necolas/react-native-web#1276]
**Is your feature request related to a problem? Please describe.**
RN recently added a prop to limit how text scales with accessibility settings `maxFontSizeMultiplier`. Right now the props get forwarded to react-dom and cause an invalid prop warning.

**Describe a solution you'd like**
`maxFontSizeMultiplier` should limit the font size multiplier or at least not trigger a react-dom warning.

**Describe alternatives you've considered**
N/A

**Additional context**
https://facebook.github.io/react-native/docs/next/text#maxfontsizemultiplier

**Comment by necolas** [comment]
Closing as the warning is now prevented
