### ISSUE TITLE
Running `yarn website` returns `Module not found: Error: Can't resolve 'react-native'`

### ISSUE THREAD

**Issue by destinf** [necolas/react-native-web#1279]
**The problem**
Cloning react-native-web and running `yarn install`, then `yarn website` causes error `Module not found: Error: Can't resolve 'react-native'`

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1. `yarn install`
2. `yarn website`
3. Errors occur on command line and in the storybook website `localhost:9001`

**Expected behavior**

There are no errors and storybook displays correctly.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): Commit 9ce2b5bf0cfa3e985c669bc3042fd326df965c67

**Comment by necolas** [comment]
You need to run `yarn compile` first
