### ISSUE TITLE
Invalid props.style key `borderRadius` supplied to `Image`

### ISSUE THREAD

**Issue by holmesal** [necolas/react-native-web#128]
Great job on react-native-web - I've been having a blast using it!

Ran across this today: when using the `borderRadius` style prop with an image, I get an error that it isn't a supported key:
![image](https://cloud.githubusercontent.com/assets/1147390/14732097/fdd864b0-080b-11e6-8488-03cacbf7c87b.png)

**Comment by MoOx** [comment]
Got the same issue. According to react-native doc and some example I see that `borderRadius` expect a number, which is what I provided (like in the example above). Not sure what is wrong here (and the `borderRadius` seems to works "as expected").

**Comment by MoOx** [comment]
It's a bit weird since the definition seems correct https://github.com/necolas/react-native-web/blob/6a73d77030a8b48afb5f3db780409e451145d2a9/src/apis/StyleSheet/BorderPropTypes.js#L13
