### ISSUE TITLE
Unimplemented modules are causing extra modules to be bundled. 

### ISSUE THREAD

**Issue by EvanBacon** [necolas/react-native-web#1281]
**The problem**

Importing a module `UnimplementedView` or an `emptyObject` causes the majority of `react-native-web` to be included. I'm thinking this is because the babel preset cannot reassign the import to use a `react-native-web` internal.

**How to reproduce**

```ts
import { Settings } from 'react-native';
console.log(Settings);
```

In the webpack report you should see `react-art` being included, amongst other unwanted things.

<img width="1255" alt="Screen Shot 2019-03-11 at 8 12 53 PM" src="https://user-images.githubusercontent.com/9664363/54172075-15708b80-443a-11e9-8bd3-497e5e739ba9.png">

**Expected behavior**

Webpack should be able to shake out any unused modules. Slider for instance is unimplemented but because it has a designated path, extra libraries are removed. 

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): `0.10.0`

**Comment by EvanBacon** [comment]
I can a PR to fix this if you would like.

**Comment by necolas** [comment]
> I'm thinking this is because the babel preset cannot reassign the import to use a react-native-web internal.

That sounds right. Is this only in situations where you can't rely on tree-shaking?

> I can a PR to fix this if you would like.

That would be great, thanks!
