### ISSUE TITLE
onMomentumScrollEnd don't fire on ScrollView

### ISSUE THREAD

**Issue by kations** [necolas/react-native-web#1283]
**The problem**
onMomentumScrollEnd don't fire on ScrollView use case is a Swiper with pagingEnabled

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.10.0
* React (version): 16.8
* Browser: Latest Safari and Chrome

**Comment by necolas** [comment]
Duplicate of https://github.com/necolas/react-native-web/issues/1021
