### ISSUE TITLE
The Jest preset seems broken

### ISSUE THREAD

**Issue by liron-navon** [necolas/react-native-web#1284]
**The problem**
This is the test repo: `https://github.com/liron-navon/react-native-web-components-boilerplate`

I'm trying to make a component library for use in multiple projects using RNW that can be imported as an npm package and work for web and mobile, but I can't get Jest to work properly, the tests fail annoyingly over internal imports in RNW.
I followed the instructions in the [getting started guide](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md)

So my jest config is:
```
{
  "preset": "react-native-web"
}
```

**How to reproduce**
```
git clone https://github.com/liron-navon/react-native-web-components-boilerplate rnw-components
cd rnw-components
npm install
npm test
```

And the output will be:
```
  ● Test suite failed to run

    /Users/lna23126/Desktop/rnw-components/node_modules/react-native-web/dist/exports/Text/index.js:14
    import applyLayout from '../../modules/applyLayout';
           ^^^^^^^^^^^

    SyntaxError: Unexpected identifier



      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:451:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:493:19)
      at Object.<anonymous> (src/lib/ActionTextInput/ActionTextInput.jsx:11:13)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.798s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

```

**versions**
"react-native-web": "^0.10.1"
"react": "^16.8.4"
"react-dom": "^16.8.4"
"jest": "^24.4.0"

node v11.7.0

**Comment by necolas** [comment]
The preset is only for React Native Web related things; it doesn't deal with any other part of the Jest config. And it looks like you haven't configured Jest beyond adding a preset - https://github.com/liron-navon/react-native-web-components-boilerplate/blob/35adcee1b2543868966f809e4cfec92112f0e4f6/jest.config.json

**Comment by liron-navon** [comment]
@necolas 
But do you know what I need to add? The bug is from the internals of RNW, I currently can't test projects that are built with RNW.
```
/Users/lna23126/Desktop/rnw-components/node_modules/react-native-web/dist/exports/Text/index.js:14
    import applyLayout from '../../modules/applyLayout';
           ^^^^^^^^^^^
```

**Comment by codymurphyjones** [comment]
I know this post is closed, but this post completely avoid the real issue which is the applyLayout syntax error.

I am also getting the same exact issue and there is no indication of it being addressed in anyway.
