### ISSUE TITLE
Compatibility break in v0.11.0 with native-base and react-native-elements

### ISSUE THREAD

**Issue by jasonuwbadger** [necolas/react-native-web#1288]
**The problem**
Compatibility break with native-base and react-native-elements.
When using "export * from 'react-native'", like react-native-vector-icons does, the following exception is thrown:
TypeError: Cannot convert undefined or null to object
./node_modules/react-native-vector-icons/lib/react-native.js
node_modules/react-native-vector-icons/lib/react-native.js:1
> 1 | export * from 'react-native';

**How to reproduce**
Put following in example code that uses react-native-web:
export * from 'react-native';

Simplified test case: none

Steps to reproduce:
1. Create sample react-native-web project
2. Create new file (like reactnative.js) with export * from 'react-native';
3. import { Button } from 'reactnative'

**Expected behavior**
for "Export * from 'react-native'" to work with react-native-web

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.0
* React (version): 16.7.0
* Browser:Chrome, Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by necolas** [comment]
You should have included a simplified test case, please. It's a required item and makes things a lot easier for me to help you.

I tried to reproduce the issue and couldn't - https://codesandbox.io/s/88qxp898z8

**Comment by startupgurukul** [comment]
It was broken due to this
https://github.com/ovr/react-native-status-bar-height/issues/10
