### ISSUE TITLE
import external components fails

### ISSUE THREAD

**Issue by vlimag** [necolas/react-native-web#1289]
**What I am trying to do:**
I am trying to use some external components (React native only - JSX)

**The problem:**
When launching on web, it raises the error: 'need apropriate loader to handle JSX files'

**Provisory Solution**
When local (under src folder) the component works just fine.

Should the components have react native web installed from within their structure as well?

Thanks in advance.

**Comment by necolas** [comment]
I think webpack is telling you to process uncompiled node modules - https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md
