### ISSUE TITLE
Style warnings

### ISSUE THREAD

**Issue by JerryGreen** [necolas/react-native-web#1293]
Is there any way to disable style warning like this?

```
Warning: Failed prop type: Invalid props.style key `pointerEvents` supplied to `View`.
Warning: Failed prop type: Invalid props.style key `whiteSpace` supplied to `View`.
```

I understand that "[the aim isn't to support everything that is possible in CSS](https://github.com/necolas/react-native-web/issues/206#issuecomment-247855724)" - I like these warnings (overall). But sometimes I intentionally write web-specific code, and I don't want these warnings to appear. Is there a workaround?

Just to use `div` instead of `View`? (Probably so...)

But @necolas, any idea how can [Platform.select](https://facebook.github.io/react-native/docs/platform-specific-code.html) be integrated with `react-native-macos`? Maybe we can somehow indicate that these styles are "platform specific code" and say "so there's no need to throw such warnings". If you think it's a good idea and not too hard - then, with little guiding, I could make a PR.

**Comment by necolas** [comment]
`View` has a `pointerEvents` prop, and it doesn't support raw text nodes as children, so the text styles aren't allowed on a `View`. You should apply those to a `Text`

**Comment by JerryGreen** [comment]
@necolas but the thing the `pointerEvents` isn't just a text property. I have a scrollable area under my fixed positioned block. I want the browser to ignore that whole block in order to give an ability to scroll a block beneath, even if you point your cursor on that fixed block. So I need that `pointerEvents` on a whole `View`, not just on a `Text`

(Currently what I do is wrapping up all its content into a `div` with a `pointerEvents: 'none'` prop)

**Comment by necolas** [comment]
`<View pointerEvents="none">`

**Comment by JerryGreen** [comment]
@necolas yea but it prints the warning message I posted earlier:

```
Warning: Failed prop type: Invalid props.style key `pointerEvents` supplied to `View`.
W
```

**Comment by necolas** [comment]
You're adding it as a style. Use the prop
