### ISSUE TITLE
VirtualizedList never removes elements from the DOM

### ISSUE THREAD

**Issue by calebmer** [necolas/react-native-web#1295]
*It’s very possible that I’m misunderstanding something here and that this isn’t actually a bug.*

**The problem**

When a component in a `<VirtualizedList>` scrolls offscreen it is not unmounted or removed from the DOM.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/0x83rq0m3p

Steps to reproduce:
1. Scroll a bit.
2. Open the elements panel.
3. Observe that the first item is still rendered in the DOM.

**Expected behavior**

Offscreen elements will be removed from the DOM. Like in [`react-window`](https://react-window.now.sh).

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.1
* React (version): 16.8.3
* Browser: Chrome

**Additional context**

Currently, in the app I’m working on, using the React profiler to debug the performance of my app it looks like _all_ of the items are being re-rendered every time the component updates.

**Comment by necolas** [comment]
I think you're right. I recall noticing something like this a while ago. Not sure what the cause is but longer term the web implementation of `VirtualizedList` should probably integrate whatever Brian figures out for `react-window`

**Comment by brunolemos** [comment]
Can confirm, came here to report the same thing.

But based on #1077, it used to remove, right? So maybe it's a regression?

**Comment by brunolemos** [comment]
Just made some more tests and it does remove the elements from the dom.

The problem is that the initial `windowSize` is way too big (`21`), if you set it to `windowSize={2}`, for example, you can see more easily the dom elements being removed.

**Comment by necolas** [comment]
Yeah I noticed it does remove elements. It's just not designed to run well on the web and has some perf issues even for native.
