### ISSUE TITLE
Image disappears in high contrast mode.

### ISSUE THREAD

**Issue by evcohen** [necolas/react-native-web#1298]
**The problem**
Images disappear in high contrast mode on Windows OS browsers because high contrast mode strips away background images and [the accessibility image has opacity:0](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Image/index.js#L395).

![image](https://user-images.githubusercontent.com/7098243/54719855-33fe1300-4b1b-11e9-8441-cccdc3b34809.png)

**How to reproduce**
1. Use a windows laptop and turn on high contrast mode.
2. Navigate to a user profile on mobile.twitter.com in Firefox, for example.
3. Notice the profile image is not visible.

**Expected behavior**
The image is accessible.

**Other information**
Windows has a `-ms-high-contrast` media query that can be used to detect high contrast mode, otherwise I'm unsure of detection mechanisms.

**Comment by necolas** [comment]
Apparently high contrast mode is meant to support background images - https://blogs.windows.com/msedgedev/2016/04/20/building-a-more-accessible-web-platform/

**Comment by evcohen** [comment]
I believe that's just for edge?

**Comment by necolas** [comment]
Closing as this feature is being tracked in #1786
