### ISSUE TITLE
Text: implement `numberOfLines` > 1

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#13]
As far as I know, this is non trivial cross-browser but should be possible using `document.createRange` and `getClientRects`: https://developer.mozilla.org/en-US/docs/Web/API/Range

**Comment by basketofsoftkittens** [comment]
+1

**Comment by nbclark** [comment]
Webkit only, but:

`    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
`

http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/

**Comment by nbclark** [comment]
https://github.com/doubledutch/react-native-web/commit/c817f39ffbea4ae0e64e6538a7031b98aee8a5ea

Will submit a pull once I add a test+sample

**Comment by necolas** [comment]
Unfortunately, `-webkit-line-clamp` has poor i18n support. It doesn't work when the layout is RTL, or when the language has no spaces, and it doesn't render a language-appropriate equivalent of `…`.

**Comment by VinceBT** [comment]
+1

**Comment by lstrrs** [comment]
I can try and take a shot at this but would like some comments in the approach I have in mind. 

The gist of it is:

- Use `getBoundingClientRect` to get a targetWidth
- Use `getComputedStyle` to get the text styles
- Use a `Canvas` and `measureText` method
- Break the targeted text into lines with the specified "ellipsis" component/text

Any comments? Of course there are some performance considerations.

**Comment by steida** [comment]
I think we can use https://github.com/necolas/react-native-web/issues/795 and compute the current number of lines via `height / lineHeight`, then restrict it.

**Comment by tafelito** [comment]
will any of this solutions work with rnw? [react-text-truncate](https://github.com/ShinyChang/React-Text-Truncate) or [react-lines-ellipsis](https://github.com/xiaody/react-lines-ellipsis)

**Comment by brunolemos** [comment]
Isn't using `-webkit-line-clamp` better than nothing? 🤔

**Comment by necolas** [comment]
That demo doesn't show ellipsis for LTR and clips the Arabic text vertically. Still looks broken to me against that criteria alone

**Comment by brunolemos** [comment]
Okay... I'm glad we can just use our forks.

**Comment by drumnation** [comment]
Was able to get react-lines-ellipsis working using Platform.OS === 'web'

**Comment by greenais** [comment]
@drumnation, thank you for tip - I can confirm it works. 
Only thing to note - one should explicitly set width of parent, otherwise it replaces whole text with ellipsis only after first word

**Comment by tafelito** [comment]
@necolas Have you seen how ant-design's [Input](https://ant.design/components/input/) handle number of lines? Is that something that might work in rnw?

**Comment by necolas** [comment]
@tafelito that's an input component, not a text component

**Comment by tafelito** [comment]
Sorry, this is the one I meant 

https://pro.ant.design/components/Ellipsis/

**Comment by necolas** [comment]
I don't think so. That looks like it will be expensive to perform on many text nodes, and all the `innerHTML` calls are probably an XSS vector

**Comment by stubbornella** [comment]
This makes a lot of sense to me and I brought it up to our engineers a
couple months ago. It’s something we probably need for virtual scroller.
Let me follow up again. How would you see it working? Same as line clamp?

**Comment by necolas** [comment]
Yes please, something like `line-clamp` with localization considerations built-in. Thank you :)

**Comment by stubbornella** [comment]
What are the localization considerations? (Thank you for catching me up!)

**Comment by necolas** [comment]
It needs to support RTL languages and I believe it needs to provide language-specific symbols to indicate "truncation". Not every language can use ellipsis. But I don't know the extent of the complexities involved in localization or accessibility (should screen readers read the full text or the truncated text?), just that `-webkit-line-clamp` falls well short

**Comment by stubbornella** [comment]
I wonder if there is a good resource for reading about the failings of
`-webkit-line-clamp`? /me goes to search

**Comment by necolas** [comment]
There are a couple of links in https://github.com/necolas/react-native-web/issues/13#issuecomment-449417403

**Comment by kopax-polyconseil** [comment]
How do you use numberOfLines in Web as it still didn't work in rnw for us. Thanks!
