### ISSUE TITLE
Add support for `Platform.select({ native: ... })`

### ISSUE THREAD

**Issue by SnidelyWhiplash** [necolas/react-native-web#1301]
**Is your feature request related to a problem? Please describe.**
Not so much a problem, but IMO it's unexpected that there is no `native` target within `Platform.select()` since there is a `web` target. I think it would be great if we could use the `Platform` module to select non-web (eg: native only) targets, regardless of their specific OS.

**Describe a solution you'd like**
Something like:
```
const fontFamily = Platform.select({
  native: 'system font',
  web: 'Some Fancy Font',
})
```

**Describe alternatives you've considered**
Right now you have to do something like:
```
let fontFamily = 'system font'
if (Platform.OS === 'web') {
  systemFont = 'Some Fancy Font'
}
```
which is fine, but not as clean IMO.

**Additional context**
This may be something core should add upstream, considering they do, in fact, support [`.native.js` file extensions](https://facebook.github.io/react-native/docs/0.55/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web), but since the `web` target within `Platform.select()` was added in this lib (I believe?), it seems like there should also be an inverse option.

Cheers!

**Comment by necolas** [comment]
React Native supports `ios`, `android`, and `default` options. This package only needs to include `web`

**Comment by SnidelyWhiplash** [comment]
Oh, I didn't realize there was a `default` option; doesn't seem to be in the RN docs. That'll suffice, thanks! 👍
