### ISSUE TITLE
How do you ignore `.native.js` files?

### ISSUE THREAD

**Issue by SnidelyWhiplash** [necolas/react-native-web#1303]
**The problem**
RN supports naming a file with `.native.js` and this lib supports naming them with `.web.js` which is great. However, I have made an `Image.native.js` and a `Image.web.js` but the webpack build fails with errors from within the native file.

**How to reproduce**
_(codesandbox doesn't have webpack)_

Relevant webpack config is:
```
module: {
  rules: [
    {
      test: /\.js$/i,
      include: [
        path.resolve(projectRoot, 'node_modules'),
        path.resolve(projectRoot, 'app'),
        path.resolve(projectRoot, 'index.web.js'),
      ],
      use: {
        loader: 'babel-loader',
        options: {
          presets: [
            'react-native'
          ],
          plugins: [
            'react-native-web',
          ],
        },
      },
    },
  ],
}
```
I tried adding `exclude: /\.native\.js$/` but it didn't change anything.

Steps to reproduce:
1. Create a file with a `.native.js` extension
2. Create a file of the same name with a `.web.js` extension
3. Run webpack

**Expected behavior**
`*.native.js` should be ignored altogether

**Actual behavior**
webpack build fails with errors from within the native file

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.1
* React (version): 16.8.4
* Browser: Chrome

**Comment by SnidelyWhiplash** [comment]
I should add that everything works fine when I just have a `Image.js` and a `Image.web.js` though.

**Comment by necolas** [comment]
Your webpack configuration can define the extensions it resolves and their order https://github.com/necolas/react-native-web/blob/0.11.1/docs/guides/multi-platform-apps.md#web-packaging-for-existing-react-native-apps

**Comment by SnidelyWhiplash** [comment]
If you mean in `resolve.extensions`, yes I have that (not mentioned above, sorry). But is seems to only take an array of strings:

```
  resolve: {
    alias: {
      'react-native$': 'react-native-web',
    },
    extensions: [
      '.web.js',
      '.js',
    ],
  },
```

So how can I _exclude_ `.native.js` considering it does, in fact, end with a `.js`?

**Comment by necolas** [comment]
It shouldn't ever be importing `Image.native.js` if your import is `import Image from './Image`

**Comment by FunkyLambda** [comment]
@necolas 

> It shouldn't ever be importing `Image.native.js` if your import is `import Image from './Image`

Oh but it is.

**Comment by twboc** [comment]
The error is not part of bundling process. What happens here is that webpack processes first the files based on the resolve.extensions property which matches both native.js and .js files since you have passed '.js' extension but in the background webpack builds all files before bundling so without the loaders just the dependencies presented in these files. I am 99% sure that if you put a method in test property for your js module:

replace /\.js/ regex with function(path){ console.log(path); return true}

none of the files printed by function will include the native.js extension.

**Comment by KeitelDOG** [comment]
@necolas I salute your perseverance and good works despite the fact of having to deal with us, frustrated developers when we are desperate for something not working 😁. I usually prefer to listen carefully to Top Devs like you, try the suggestions first and search on it before throwing dislike on the go. Taking pro advices has proven to be 99% more efficient on solving bugs.

Webpack extensions are resolved with priority, once it finds the first match, it stops and ignore the rest. If anyone want documentation, https://webpack.js.org/configuration/resolve/#resolveextensions :

> [string] = ['.js', '.json', '.wasm']
> 
> Attempt to resolve these extensions in order. If multiple files share the same name but have different extensions, webpack will resolve the one with the extension listed first in the array and skip the rest.

For NextJS, what happened for me was just a matter of runtime cache that was still looking for the old deleted `App.js`. Once I stop next and run it again, it found `App.web.js` and ignored `App.native.js`.
