### ISSUE TITLE
Unexpected ReactNativeStyleResolver module missing ?

### ISSUE THREAD

**Issue by momsse** [necolas/react-native-web#1304]
**The problem**

The module `packages/react-native-web/src/exports/StyleSheet/ReactNativeStyleResolver.js` have been deleted on this commit: [Fix copyright headers](https://github.com/necolas/react-native-web/commit/b732cec83ef54abaddf02b124f9de0692744fb56)

I guess it's a bad move given the commit message?

That actualy break injection of `react-native-web` on `react-primitives` lib (see [here](https://github.com/lelandrichardson/react-primitives/blob/master/src/injection/react-native-web.js#L19))

```
Could not find module in path: 'react-native-web/dist/cjs/exports/StyleSheet/ReactNativeStyleResolver' relative to '/node_modules/react-primitives/lib/injection/react-native-web.js'
```

**How to reproduce**

Simplified test case: https://codesandbox.io/s/618w52082r

Steps to reproduce:
1. Just go to the landing page of  https://codesandbox.io/s/618w52082r

**Expected behavior**

No crash.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): `0.12`
* React (version): `16`
* Browser: TBC

**Comment by necolas** [comment]
Someone needs to patch react primitives

**Comment by ljharb** [comment]
Removing a file is still a breaking change; in this case done in a minor version.

**Comment by necolas** [comment]
And pre-1.0.0 that should be expected. Plus primitives is using a private API
