### ISSUE TITLE
animatedprops error only in production

### ISSUE THREAD

**Issue by sirpy** [necolas/react-native-web#1306]
**The problem**
When compiling with react in production mode some errors are introduced.
Specifically I found that BABEL_ENV=production doesn't work and BABEL_ENV=development works.
Everything works fine in development mode.
One error was resolved by downgrading react-native from 0.57 to 0.55 but the following error then appeared
I narrowed  down the error to the usage of Button from 'react-native-paper' or Input with shake=true from react-native-elements. (ie any animation)
On development mode animations work fine
```
ypeError: Right-hand side of 'instanceof' is not an object
    at n.o.__attach (AnimatedProps.js:91)
    at new n (AnimatedProps.js:44)
    at s.l._attachProps (createAnimatedComponent.js:127)
    at s.l.UNSAFE_componentWillMount (createAnimatedComponent.js:73)
    at li (react-dom.production.min.js:2853)
    at Po (react-dom.production.min.js:3759)
    at jo (react-dom.production.min.js:3960)
    at Ga (react-dom.production.min.js:5514)
    at Ka (react-dom.production.min.js:5536)
    at Ts (react-dom.production.min.js:5958)
    at Cs (react-dom.production.min.js:5925)
    at ks (react-dom.production.min.js:5860)
    at Ja (react-dom.production.min.js:5787)
    at Object.enqueueSetState (react-dom.production.min.js:2789)
    at n._.setState (react.production.min.js:72)
    at Object.o._dispatch [as dispatch] (createBrowserApp.js:74)
    at Object.f.(:5000/anonymous function) [as navigate] (http://localhost:5000/static/js/1.5da2e1a3.chunk.js:1:4716357)
    at t.<anonymous> (AppSwitch.js:80)
    at _ (runtime.js:63)
    at Generator._invoke (runtime.js:282)
    at Generator.e.(:5000/anonymous function) [as next] (http://localhost:5000/static/js/1.5da2e1a3.chunk.js:1:1387461)
    at r (asyncToGenerator.js:3)
```

That's the line of code
```
_proto.__attach = function __attach() {
    for (var key in this._props) {
      var value = this._props[key];

      if (value instanceof AnimatedNode) {
        value.__addChild(this);
      }
    }
  };
```

**How to reproduce**
Use any animated component from react-native-paper/react-native-elements
Compile with webpack in production mode and BABEL_ENV=production

**Expected behavior**
behave like in development mode

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11
* React (version): 16.8.1
* Browser: chrome

**Comment by vadimb** [comment]
We are experiencing the same issue. Struggling to find the core of the problem. Any help is appreciated!

**Comment by antraub** [comment]
Same issue here, caused by animations in react-native-slider. Using react-native-web 0.11.2.

**Comment by sirpy** [comment]
@vadimb @antraub 
What boilerplate are you using? I was using create-react-native-web-app and I found out that with create-react-app it works just fine.
Perhaps its an issue with conflicting packages/dependencies/versions who knows.

**Comment by puneethreddy-3186** [comment]
I am using create-react-native-web-app for creating the boiler plate.

**Comment by geminiyellow** [comment]
same error. 
i use `react-native-web` 's `Animated.Image`.
when i put it in the top page (create by `create-react-app`), it work well.
but when i move it down to the sub page, which route by `react-router`,
the same error is here.
anybody can tell me why?

**Comment by sirpy** [comment]
> I am using create-react-native-web-app for creating the boiler plate.

@puneethreddy-3186 i've opened an issue on crnwa
can you post the code that causing this here:
https://github.com/orYoffe/create-react-native-web-app/issues/41

**Comment by puneethreddy-3186** [comment]
I got this to work by updating the react-native-web to 0.11.2 and react-native-slider to 0.11.0. I am using the crnwa 0.1.14 for creating the boiler plate. Also update the babel-loader in the webpack production config
 `// Process application JS with Babel.
          // The preset includes JSX, Flow, and some ESnext features.
          {
            test: /\.(js|mjs|jsx|ts|tsx)$/,
            include: paths.appSrc,
            loader: require.resolve('babel-loader'),`

**Comment by puneethreddy-3186** [comment]
include the appSrc for babel transformation

**Comment by iamraffe** [comment]
I am also seeing this when running in production with Animated components.

Any clues as to what may be causing this?

I'm not sure I understand @puneethreddy-3186's fix...

I'm running react-native-web to 0.11.2

**Comment by colmbrady** [comment]
I also had the exact same issue, I managed to resolve it by changing my babel react native web plugin to use commonJS.

`['react-native-web', { commonjs: true }],`

I have not had time to investigate the "why" - but this might fix other peoples issue for the time being.

**Comment by G2Jose** [comment]
Running into this same issue.
My setup:
- `react-native-web: 0.12.3`
- `react-native: 0.62`

**Comment by waqas19921** [comment]
@necolas Running into same issue

My setup is also same:

```
react-native-web: 0.12.3
react-native: 0.62
```
I'm using create-react-app's default react-scripts, i.e not the react-native-web babel plugin. Any ideas on how to fix this?

**Comment by waqas19921** [comment]
I am able to fix above issue by updating `create-react-app` `react-scripts` version to `3.4.4`
