### ISSUE TITLE
textShadow style propery triggers missleading warning message

### ISSUE THREAD

**Issue by JoseFMP** [necolas/react-native-web#1308]
**The problem**
According to https://github.com/necolas/react-native-web/issues/104 `react-native-web` should support using the style property `textShadow` as in CSS:
![image](https://user-images.githubusercontent.com/24405049/55061812-36c2b000-50a7-11e9-84c2-33af1237da7c.png)

Indeed, setting the property works fine. The result displayed in multiple web browsers is correct.
However, there is a verbose console error message complaining about this style property being incorrect. The message is specially annoying because it lists all the possible CSS properties if using previous versions of `react-native-web`.
![image](https://user-images.githubusercontent.com/24405049/55061774-227eb300-50a7-11e9-8d4a-46f264918637.png)
Although in `react-native-web` "0.11.x" is only one line fortunately. But still misleading: 
![image](https://user-images.githubusercontent.com/24405049/55061981-991bb080-50a7-11e9-8ee3-e2727070129d.png)
 
Extra information: using the text shadow properties split as in React Native Mobile, does NOT work for `react-native-web`. Which is totally fine as `textShadow` is working.

**How to reproduce**
https://codesandbox.io/s/ox60mm5716

Simplified test case: 
https://codesandbox.io/s/ox60mm5716

Steps to reproduce:
1. Create a stylesheet with property `shadowText` using `react-native-web`
2. Apply the style to a `View` element from `react-native-web`
3. Get a warning message telling the property name is wrong.

**Expected behavior**
There is no warning message.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): "0.11.x"
* React (version): "16.8.4"
* Browser: Chrome, Firefox, Opera.

**Comment by necolas** [comment]
Use the `textShadow*` styles as documented for Text on the web site (same as the react native docs)

**Comment by JoseFMP** [comment]
@necolas  Thank you for your answer. However, when using the ones `textShadow*` the shadow properties do not translate to CSS and they have no effect, i.e. cannot use the shadow effect.

**Comment by necolas** [comment]
You can see it working in the example app.  Only supported by text. Read the docs for more details
