### ISSUE TITLE
React Native external plugin

### ISSUE THREAD

**Issue by LucianHij** [necolas/react-native-web#1309]
Hi, 
I have an issue and I don't know if it is normal to happen this way or if it should work.
I want to use a plugin for using the camera only on RN, not on web.
I use this plugin https://github.com/react-native-community/react-native-camera. 
I created a file named `camera.native.js` so in this case i am sure that only when i am on mobile this will be imported. 
I just insert this line `import { RNCamera, FaceDetector } from 'react-native-camera';` in the file `camera.native.js` and after this it breaks. 
How should i use an external react-native specific plugin?

**Comment by necolas** [comment]
I don't know what "it breaks" means, but it sounds like your web bundler is not configured correctly. Without providing any more information - test case, stacktrace - I can't help further. Since this is not a problem with the library I will close the issue

**Comment by LucianHij** [comment]
Can you guide me to an example of how to config the web bundler in order to be able to use all the packages for react-native that are out there?

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md#web-packaging-for-existing-react-native-apps

being able to use a react-native package depends on whether that package supports web

**Comment by LucianHij** [comment]
So we are not able to use any react native package that doesn't support react native web. Practically we are not able to use almost any react native package, just a very small number that are created especially for react native web. Am I correct?

**Comment by acro5piano** [comment]
I don't know what is going on your environment, but you can create two files: `camera.native.js` and `camera.web.ts`. Then if you set webpack config correctly it will works.
