### ISSUE TITLE
Not possible to use emotion or styled-components when using react-native-web@0.11.X

### ISSUE THREAD

**Issue by Josema** [necolas/react-native-web#1310]
**The problem**

Using emotion or styled-components and the version 0.11.X it throw this error:
```
Failed to compile.
                                                                            ported as 'react
./node_modules/@emotion/native/dist/native.browser.esm.js
Attempted import error: 'react-native' does not contain a default export (imported as 'reactNative').
```
The problem is solved when using 0.9.9

**How to reproduce**
```
import styled from '@emotion/native'

const View = styled.View`
    padding: 32px;
    background-color: hotpink;
    font-size: 24px;
    border-radius: 4px;
    width: ${props => props.width};
    &:hover {
        color: ${'red'};
    }
`
```

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.X
* React (version): 16.X.X
* Browser: *

**Comment by necolas** [comment]
As mentioned n the release notes, the default export has been removed. Emotion and styled-components shouldn't be relying on React Native's default export to build their `styled` object

**Comment by Josema** [comment]
I see. This is another aproach that works in my case:

```js
// from
import styled from '@emotion/native'

const View = styled.View`
    ...
`
```

```js
// to
import styled from '@emotion/styled'
import { View } from 'react-native'

const ViewStyled = styled(View)`
    ...
`
```

**Comment by Josema** [comment]
The solution offered above is not valid because it uses className and is deprecated.

The best solution ATM:
```js
import { createStyled } from '@emotion/primitives-core'
import { StyleSheet } from 'react-native'
import { View } from 'react-native'

const styled = createStyled(StyleSheet)
const ViewStyled = styled(View)`
    ...
`
```

Waiting for: https://github.com/emotion-js/emotion/pull/1289

**Comment by MrLoh** [comment]
@necolas I am trying to provide a [fix to styled-components]( https://github.com/styled-components/styled-components/pull/2453), but I cannot figure out what syntax works for react-native and react-native-web. Styled-components depends on the [lazy-loading that react-native uses](https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-implementation.js) and react-native web would now require concrete imports, is there any way to lazy-load from react-native-web?

**Comment by MrLoh** [comment]
@necolas do you have any hints how a library like styled-components should handle this, I want to fix it for styled-components but I don't know what the right way to handle this is

**Comment by gablabelle** [comment]
For those who came here because they got the same described error using styled-components with react-native-web, check this PR https://github.com/styled-components/styled-components/pull/2453

**Comment by firestarter31497** [comment]
Hi! Good evening!😇 Do y'all know that you are coding a real live person??
I may be small, but I'm real!! I bite my fingernails and I got stung by a
jellyfish when I was a kid. I laugh and cry, I feel embarrassed at times
and jubiliant other times. I hope you consider this as you go about your
days of brilliant coding. I think developers and coders are some of the
sharpest, most talented group of professionals out there and I thank you
for your ingenuity, creativity, and attention to detail. Just please don't
forget you cannot code a spirit-for the soul is permanent, constantly
growing and moving but permanent and specific to it's individual owner.
This will not change. Thanks!
