### ISSUE TITLE
Warning: Failed prop type: Invalid props.style key `pointerEvents` supplied to `View`.

### ISSUE THREAD

**Issue by Josema** [necolas/react-native-web#1314]
Getting this error when applying that property.
```
Warning: Failed prop type: Invalid props.style key `pointerEvents` supplied to `View`.
```

But is a valid property for View component.
https://facebook.github.io/react-native/docs/view

**Comment by necolas** [comment]
Duplicate of https://github.com/necolas/react-native-web/issues/1293
