### ISSUE TITLE
accessibilityRole - heading or header?

### ISSUE THREAD

**Issue by airandfingers** [necolas/react-native-web#1320]
**The problem**
I want to set the `accessibilityRole` property so that it works on iOS, Android, and web. "header" looks like the accepted value on native, and [`accessibilityRoleToWebRole`](https://github.com/necolas/react-native-web/blob/36dacb2052efdab2a28655773dc76934157d9134/packages/react-native-web/src/modules/AccessibilityUtil/propsToAriaRole.js) converts "header" to "heading" on web, but when I pass in "header", I get a warning due to the [TextPropTypes](https://github.com/necolas/react-native-web/blob/36dacb2052efdab2a28655773dc76934157d9134/packages/react-native-web/src/exports/Text/TextPropTypes.js#L15), which specify "heading" instead of "header".

Meanwhile, "heading" is prescribed by the [docs](https://github.com/necolas/react-native-web/blob/master/docs/guides/accessibility.md#accessibilityrole) and `TextPropTypes`, but passing in this value results in "invalid accessibilityRole value" errors on both iOS and Android.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/5x7noz8qll

Steps to reproduce:
1. Create a component with `<Text accessibilityRole="header" />`
2. Notice the console PropType warning

**Expected behavior**
`Text` should accept an `accessibilityRole` value of "header", converting it to `role="heading"`.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.0
* React (version): 16.8.4
* Browser: OSX Chrome

**Additional context**
We have common React Native components that are being used on Android, iOS, and web, and I've noticed other times where we can't set roles on native and web without warnings/errors:

* "text" is prescribed on native, but also not included in `TextPropTypes`, so it triggers a console warning.
* "label" creates a `<label>` on web, but triggers an error on native (`react-native-web` can't do much about this, but I'd like to know how to get around this).

Is the way we're using `react-native-web` not a common use case for it, or is accessibility not handled widely enough to expose these issues sooner?

**Comment by necolas** [comment]
> I'd like to know how to get around this

`Platform.select({ 'web' : {…}, 'default': {…} })`

**Comment by airandfingers** [comment]
Okay, we can use `Platform.select` to set `accessibilityRole="label"` on web only, and we can put that logic into our custom component to avoid repetition.

However, it doesn't help the issues with the `accessibilityRole` values of "heading" versus "header" (echoed by #1330) and "text".

These require at least adding "header" and "text" to `TextPropTypes`. If you like, I'll submit a PR with these simple changes, but I figured you might want to solve this some other way.

**Comment by necolas** [comment]
Look at the diff that closed this issue

**Comment by airandfingers** [comment]
Oh, I missed that, my bad.. Thanks!

**Comment by paulwongx** [comment]
> `Platform.select({ 'web' : {…}, 'default': {…} })`

@necolas For a prop like accessibilityLevel which is not accepted by react native, do you mean we should use `Platform.select` to return a whole different component or is there some way to add an unaccepted prop using `Platform.select()`?
