### ISSUE TITLE
Add backdrop-filter style prop

### ISSUE THREAD

**Issue by EvanBacon** [necolas/react-native-web#1321]
**Is your feature request related to a problem? Please describe.**

Adding support for the [`backdrop-filter`][bkdrop] and `-webkit-backdrop-filter` will enable safari/chrome users to use [`expo-blur`](https://github.com/expo/expo/tree/master/packages/expo-blur).

Related: [Expo web Blur View](https://github.com/expo/expo/compare/@evanbacon/expo-web/blur-view-updates?expand=1)

[bkdrop]: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

**Describe a solution you'd like**

```tsx
style={{
  backdropFilter: 'blur(10px)'
}}
```
Creates the following styles:

```css
backdrop-filter: blur(10px);  
-webkit-backdrop-filter: blur(10px);
```

**Comment by EvanBacon** [comment]
@necolas I'll open a PR as well

**Comment by EvanBacon** [comment]
Duplicate #1070

**Comment by sravan1000** [comment]
any update?

**Comment by necolas** [comment]
Did you look at #1070? It's been added
