### ISSUE TITLE
Image onLoadEnd

### ISSUE THREAD

**Issue by oxyii** [necolas/react-native-web#1322]
**The problem**

On **RN** `Image` component `onLoadEnd` event triggered everytime after `source` prop changing on mounted `Image` component... On RNWeb - after source loaded (not changed)...

**How to reproduce**

RN: https://snack.expo.io/@oxyii/image-onloadend-test

RNWeb: https://codesandbox.io/s/7w32oql5zx

**Expected behavior**

same as RN )))

OPTIONAL:

Real world example: `react-native-elements` lib have `Avatar` component that use `Image` component. So RNE fade in animation not fired on source changed because [this](https://github.com/react-native-training/react-native-elements/blob/master/src/image/Image.js#L80)

**Comment by mschipperheyn** [comment]
In the meantime, something like this?
```
constructor(props) {
		super(props);
		this.handleLoad = () => {
			this.setState({ loaded: true });
			this.props.onLoad();
		};
	}

	state = {
		loaded: false,
	};

	componentWillUnmount() {
		delete this.handleLoad;
	}

	render() {
		const {
			loadNow,
			photoDir,
			photo,
			displayName,
			gender,
			type,
			showBorder,
		} = this.props;
		const { loaded } = this.state;
		let image = null;

		if (photo) {
			image = (
				<Image
					onLoad={() => {
						if (this.handleLoad) this.handleLoad();
					}}
					style={[
						localStyle.image,
						localStyle[type],
					]}
					uri={utils.photoUrl(photoDir, photo, type)}
				/>
			);
		}
```

**Comment by dmsvlks** [comment]
Just to add, none of the events fire after source is changed to something that was loaded previously.
