### ISSUE TITLE
StyleSheet vs ReactNative.StyleSheet

### ISSUE THREAD

**Issue by nickwebha** [necolas/react-native-web#1324]
If I do
```
import { StyleSheet } from "react-native";
const Style = StyleSheet.create( { } );
```
everything works as expected.

If I do
```
import ReactNative from "react-native";
const Style = ReactNative.StyleSheet.create( { } );
```
I get errors like _StyleSheet_ can not be found when used in a View. The same happens with _View_/_ReactNative.View_ and I imagine other members of the object.

I would think this would work the same way that React Native works (since this works in React Native).

react-native v0.59.2
react-native-web v0.11.2
All browsers as it is a missing object in JavaScript.

**Comment by ValGeorgiev** [comment]
@nickwebha react-native-web is not compatible with react-native 0.59.2.
**Compatibility: React Native 0.55.**
Reference: https://github.com/necolas/react-native-web#react-native-for-web

**Comment by necolas** [comment]
Using a default es6 export is not supported and there is on going work to remove the default export from RN too
