### ISSUE TITLE
Title prop only works for Text components

### ISSUE THREAD

**Issue by brunolemos** [necolas/react-native-web#1326]
**The problem**
Title prop only works for Text components

**How to reproduce**

Simplified test case: https://codesandbox.io/s/qkxon07lzq

```jsx
import React from "react";
import { Image, Text, TouchableOpacity, View } from "react-native";

class App extends React.Component {
  render() {
    return (
      <View>
        <Text title="It works">Text with label (it works)</Text>
        <TouchableOpacity
          accessible
          accessibilityLabel="test"
          title="It doesn't work"
        >
          <Text> TouchableOpacity with label (doesn't work)</Text>
        </TouchableOpacity>
        <Image
          source={{
            uri:
              "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          }}
          title="Image with title (doesn't work)"
          style={{ width: 120, height: 40 }}
        />
      </View>
    );
  }
}

export default App;
```

**Expected behavior**
Support some declarative way to set the web title popover on any component, without using setNativeProps. It's something I'd like to have on the web project, on mobile I did using onLongPress.

**Environment**

* React Native for Web (version): 0.11.x
* React (version): 16.8.x
* Browser: Chrome

![image](https://user-images.githubusercontent.com/619186/56087056-bbe4ed80-5e39-11e9-9fb8-718564c0ff96.png)

**Comment by paularmstrong** [comment]
You're looking looking for [`accessibilityLabel`](https://facebook.github.io/react-native/docs/view#accessibilitylabel). RNW will set it properly from there.

**Comment by brunolemos** [comment]
It seems `accessibilityLabel` adds an `aria-label` property to any element, but I don't see anything related to `title`.

Is the recommend approach to use that instead of title and maybe use a javascript to create a popover instead of using the built-in `title`?

**Comment by brunolemos** [comment]
`setNativeProps` is good enough for me for now.

**Comment by 0x24a537r9** [comment]
Should this be reopened given this comment from necolas? https://github.com/facebook/react-native/issues/33520#issuecomment-1171762317

> setNativeProps will not be supported in the new "Fabric" architecture, and should be considered deprecated
> 
> https://reactnative.dev/docs/new-architecture-library-intro#migrating-off-setnativeprops
