### ISSUE TITLE
No `borderStyle` set to `<Text />` component

### ISSUE THREAD

**Issue by yairopro** [necolas/react-native-web#1327]
**The problem**
`<Text />` have no `borderStyle` set by default.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/ry0ok78owp

Steps to reproduce:
1. Add a border to a text
2. No border will appear unless you clearly set the `borderStyle`.

**Expected behavior**
A solid border should appear like in react-native: https://snack.expo.io/By-F-zbc4 

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.2
* React (version): 16.8.5
* Browser: Chrome 73

**Comment by necolas** [comment]
Fixed in master
