### ISSUE TITLE
So is this project dead…

### ISSUE THREAD

**Issue by nathggns** [necolas/react-native-web#1329]
You've immediately closed an issue asking about ongoing support for this project https://github.com/necolas/react-native-web/issues/1328 without answering.

As you will know, many projects are depending on the ongoing future of this project and need to understand your intentions to support it or not in order to plan for the future.

Are we to take your closing of this issue as you confirming that this project is dead?

**Comment by necolas** [comment]
You can see from the activity that it is not. I find it toxic for people to repeatedly ask this question if I don't push commits for a few weeks.
