### ISSUE TITLE
Invalid UIAccessibilityTraits 'heading'. shoud be one of ...

### ISSUE THREAD

**Issue by EvanBacon** [necolas/react-native-web#1330]
**The problem**

A popular `accessibilityRole` **'heading'** is not supported on native. Possibly could upstream this to react native. `header` is supported however. Not sure if this is a common issue, but here is an [example of usage](https://github.com/necolas/react-native-web/blob/801937748b2f3c96284bee1881164ac0c62a9c6d/packages/website/storybook/ui-explorer/Section.js#L12).

**How to reproduce**

In native:
```jsx
<AppText accessibilityRole="heading">
```

**Expected behavior**

Should work everywhere.

**Environment (include versions). Did this work in previous versions?**

* react-native: 0.57.1
* React Native for Web (version): 0.11.0
* React (version): 16.5.0
* Browser: TBC

Related: #1320

**Comment by necolas** [comment]
I don't understand. Are you asking to disallow the value in RNW?

**Comment by EvanBacon** [comment]
It might make sense to transform the value `header` to `heading` on web, or vise-versa. Not too sure which is better. 

**References:**
* web: aria [uses `heading`](https://www.w3.org/TR/wai-aria/#heading)
* native: [uses `header`](https://facebook.github.io/react-native/docs/accessibility)

**Comment by EvanBacon** [comment]
I seem to have this more researched issue #1320. Closing
