### ISSUE TITLE
Module parse failed: Unexpected token... when I use webpack

### ISSUE THREAD

**Issue by alex83130** [necolas/react-native-web#1331]
**The problem**

I am currently doing a multi-platform application  (web/android/ios), I need to make a specific development between web and native. So I followed this documentation : [Multi-platform applications](https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md).
But I have a "Failed to compile" with a  "Module parse failed: Unexpected token"

![error](https://user-images.githubusercontent.com/15250423/56661276-b42b1180-66a1-11e9-903f-39927339a785.JPG)

I am looking for a long time but I can't find a solution to my problem ...

I specify also that before to using the solution by webpack, I used the RN command "react-scripts start" and it works perfectly. But "file.web.js" was not supported ..

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.2
* React (version): 0.59.5

**Comment by derekblank** [comment]
Likely an issue with your webpack config. Take a look at [this example config](https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md#web-packaging-for-existing-react-native-apps) and check that you have `web.js` in your extensions to resolve:

```
  resolve: {
    // This will only alias the exact import "react-native"
    alias: {
      'react-native$': 'react-native-web'
    },
    // If you're working on a multi-platform React Native app, web-specific
    // module implementations should be written in files using the extension
    // `.web.js`.
    extensions: [ '.web.js', '.js' ]
  }
```

**Comment by iulo** [comment]
read this: https://github.com/necolas/react-native-web/issues/794

just put  `App.js` in you `${projectRootDir}/src`

**Comment by necolas** [comment]
Yes this is a bundler configuration issue
