### ISSUE TITLE
PreventDefault does not work on textinput

### ISSUE THREAD

**Issue by mbouxin** [necolas/react-native-web#1332]
**The problem**
It is impossible to perform a preventDefault on a TextInput.

**How to reproduce**
A simple component can be found here:
https://gist.github.com/mbouxin/37634081917ae50b8c68b04f4d34493d

1. type AAA in the text input
2. type arrow up
3. the cursor has moved to the beginning of the text input

**Expected behavior**
It is not supported by react native (RN does not fire onKeyPress on arrow) but it would be great if the cursor did not change position. 

For this, the nativeEvent should not be overriden as it is done in _handleKeyPress (l. 367 in https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TextInput/index.js).

I tried a little hack which does the trick: replacing the native event by:
```
          if (e.nativeEvent.altKey === undefined) e.nativeEvent.altKey = e.altKey;
          if (e.nativeEvent.ctrlKey === undefined) e.nativeEvent.ctrlKey = e.ctrlKey;
          if (e.nativeEvent.key === undefined) e.nativeEvent.key = e.keyValue;
          if (e.nativeEvent.metaKey === undefined) e.nativeEvent.metaKey = e.metaKey;
          if (e.nativeEvent.shiftKey === undefined) e.nativeEvent.shiftKey = e.shiftKey;
          if (e.nativeEvent.target === undefined) e.nativeEvent.target = e.target; 
```

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.2
* React (version): 16.8.4
* Browser: Chrome

**Comment by z0al** [comment]
@mbouxin were you able to work around this?

**Comment by mbouxin** [comment]
@z0al I just patched my node_modules

**Comment by ngburke** [comment]
I am seeing problems where `preventDefault` is not being honored in TextInput components for regular keys. I see `isDefaultPrevented` and `isPropagationStopped` come back true when calling `e.preventDefault()` and `e.stopPropagation()`, but still keys go through. I'm ultimately trying to use this for Tab, however my initial test with simple keys was failing as described. Anyone else seeing this behavior?

- React Native for Web (version): 0.12.2
- React (version): 16.9.0
- Browser: Chrome (Electron)

**Comment by Devshail** [comment]
Can you Please answer this question @necolas as I am facing this issue for preventing tab press event

**Comment by necolas** [comment]
This was fixed several versions ago by the linked commit
