### ISSUE TITLE
IE 11 Object.values problem

### ISSUE THREAD

**Issue by RooQI** [necolas/react-native-web#1334]
Hello.

**The problem**

In the file createStyleResolver.js and `Object.values` are not supported in IE11. You need to replace them with a supported combination `Object.keys(obj).map(function(e)`. 

**How to reproduce**

Open any example in IE11

**Expected behavior**

Instead of a blank page, the content should appear at startup.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.2
* React (version): 16.8.4
* Browser: IE11

**Comment by canaanites** [comment]
@RooQI @necolas any updates on this? We have the same problem..
