### ISSUE TITLE
Support for react-navigation

### ISSUE THREAD

**Issue by Ajar-Ajar** [necolas/react-native-web#1338]
Any app has more than a single screen and needs navigation.
The standard library for react-native seems to converge to react-navigation.
When I tried a simple react-navigation test with the starting [codesanbox template](https://codesandbox.io/s/q4qymyp2l6) it crashed.
Is it supposed to be supported? Is it a priority known issue on the roadmap?
I don't see how RNW can go any further without it, what do people use at the moment to navigate between screens?
Thank you for reading this.
Ajar

**Comment by paularmstrong** [comment]
This is a problem with the react-navigation library: they don't have any web support. This is specified in their [readme here](https://github.com/react-navigation/react-navigation/blob/a7265155bdb390f11391effdbb3f0fc9ab9e413e/README.md#can-i-use-this-library-for-web)

**Comment by SimenB** [comment]
Might be a bit dated (it talks about v1 while current major is v3) - their website says there's "experimental support": https://reactnavigation.org/docs/en/web-support.html

**Comment by sfcgeorge** [comment]
> Note: starting in v3, React Navigation has built-in support for use in web sites, including server rendering. This has not yet been widely used in production and we consider this feature to be experimental.

https://reactnavigation.org/docs/en/web-support.html

react-navigation works perfectly with RNW and does have web support as above. The readme is misleading; it doesn't support _pure_ web, AKA ReactDOM alone, but it supports web via RNW. If you're having problems it's almost certainly just the usual JS config issues, fiddle with it.

The easiest way to get started now is via [Expo](https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375). Expo Web support is still Alpha so [documentation](https://github.com/expo/web-examples/tree/master/expo-managed-workflow) is scarce and not everything works yet, but I didn't have much trouble getting RNW + react-navigation working.

If not using Expo you need to add RN modules to the list of modules Babel will compile, that's probably your issue.
[Instructions](https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md) (scroll down do babelLoaderConfiguration `include:`). Expo's default webpack config already has react-navigation in there so you don't need to do anything, but for other RN modules there's an [open issue](https://github.com/expo/expo-cli/issues/556).

**Comment by EvanBacon** [comment]
This should probably be tracked here: https://github.com/react-navigation/react-navigation/issues/5674 I'm working on parts of this for Expo web support.

**Comment by Ajar-Ajar** [comment]
@sfcgeorge - That's great news!
Do you think it may be possible to get it to work on codesandbox too?
since they use create-react-app for react projects with no babel configuration file...
They getting started RNW template on codesandbox is SO apealling. it would be amazing to be able to have it support react-navigation out of the box...
