### ISSUE TITLE
onContentSizeChange on TextInput does not trigger in some cases

### ISSUE THREAD

**Issue by d4rky-pl** [necolas/react-native-web#1339]
**The problem**

When `<TextInput />` has an explicitly set `height` (for example because we're implementing an auto-growing textarea) then `onContentSizeChange` is not being triggered if the content height is smaller than that container height.

**How to reproduce**
https://codesandbox.io/s/ll3j9pwrx7
https://snack.expo.io/Bkkv7CRi4

**Expected behavior**
`onContentSizeChange` is called again with the correct values

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.2
* React (version): 16.8.6
* Browser: tested on Chrome

**Additional context**
The workaround I've used in my particular implementation:

```
  if (Platform.OS === 'web') {
    const node = this.input._node
    node.style.height = 'inherit'
    const height = node.scrollHeight
    node.style.height = `${height}px`
    this.setState({ height })
  }
```

**Comment by eseQ** [comment]
Check it on latest (0.17.5) version.
Issue has not yet been solved.

**Comment by d4rky-pl** [comment]
Updated snack: https://snack.expo.dev/@helpling/graceful-crackers

**Comment by eseQ** [comment]
@d4rky-pl can you confirm the issue still exist? Am I right?

**Comment by eseQ** [comment]
@necolas sorry for ping but we still have problem

**Comment by d4rky-pl** [comment]
@eseQ seems that Snack is now stripping the RNW version from the dependencies automatically. I wanted to showcase that the problem is back with the latest version of the library.

This is updated codesandbox: https://codesandbox.io/s/issue-react-native-for-web-forked-5rp84

It seems that there's an interesting behaviour in play here - the `onContentSizeChange` does in fact trigger but the internal height is incorrect. @eseQ I believe you need to report this as a new issue since it's not related to this one.

**Comment by d4rky-pl** [comment]
FYI: the behaviour changed in version 0.14.4. If you change the version to 0.14.3 in my codesandbox, it seems to work like before and the reported content size is indeed the size of the content

**Comment by eseQ** [comment]
@d4rky-pl, you'rе totally right. I'm going to create new issue report.
Thank you.
