### ISSUE TITLE
[Docs] What about CSS units? 

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#134]
react-native seems to only accept unitless values. And [current doc about styling](https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md) show examples with _rem_. Percentage won't work neither ([for now](https://github.com/facebook/css-layout/issues/147)).

[I am seeing tricks for this](https://stackoverflow.com/questions/34952984/react-native-flexbox-how-to-do-percentages-columns-responsive-grid-et) and [library](https://github.com/vitalets/react-native-extended-stylesheet) to make it more automatic, but current documentation does not mention anything about that.

Maybe we should add something about those points, and at least mention `Dimensions` API into the Style documentation?

**Comment by necolas** [comment]
People can use `Platform` to guard units that RN doesn't currently support on native platforms

**Comment by MoOx** [comment]
I know (now that I read some docs) how to handle the issue, but new users might not found the information quickly.
What about mentionning this in the doc? I can do a PR if you are open for this.

**Comment by necolas** [comment]
That sounds good. I'm wondering how RN community can best deal with this kind of issue in the medium term. I want to be able to use something like the following, which might also provide a surface for cross-platform fallbacks without people littering their code with `Platform` conditions:

```js
const rem = (value)  => `${value}rem`
const percent = (value) => `${value}%`

const style = {
  marginLeft: rem(theme.horizontalSpace * 2)
}
```
