### ISSUE TITLE
Expo deprecating support for RN 0.55

### ISSUE THREAD

**Issue by bcpugh** [necolas/react-native-web#1340]
We use expo SDK for our RN app (SDK 30, RN 0.55, and RNW 0.11, used a CRNA starter and never ejected)

Just received an email about deprecating old versions of expo. Upgrading to the recommended v32 requires RN 0.57 (“September 2018” release) which is more recent than what RNW supports (0.55 according to the docs)

Does anybody have any experience upgrading? I imagine I can’t be the only person in this boat— I’m wondering if upgrading but not using any of the “newer” features in my codebase is an option.

**Comment by SimenB** [comment]
SDK33 will support rnw out of the box, so I'd assume it works fine

https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375

**Comment by jasonuwbadger** [comment]
Looking the general APIs surface of react-native-web and the changes in react from 0.55.4 to 0.59.8, there doesn't seem to be much missing in react-native-web (or has been removed in react-native).  It looks like it should be mostly compatible.

Some things that need to be add:
FlatList.ListFooterComponentStyle
FlatList.ListHeaderComponentStyle

Some things that need to be removed:
SwipeableFlatList

At one point it looks like https://github.com/necolas/react-native-web/tree/0.11-wip was for making react-native-web compatible with react-native 0.57.  Though it hasn't been touched in 6 months.

Does anyone know how to determine the API differences between 0.55.4 and 0.59.8, so a concrete list of differences can be gathered and react-native-web can be updated with the changes?

**Comment by EvanBacon** [comment]
Like @SimenB said, Expo now supports this library out of the box, if you upgrade your version of Expo you will have guaranteed support with web (which is still in beta for Expo libs).
