### ISSUE TITLE
Picker fontFamily

### ISSUE THREAD

**Issue by PeterKottas** [necolas/react-native-web#1342]
**The problem**
How should one set the font-family (or anything font related) on Picker without getting the console warning? I know the api (https://necolas.github.io/react-native-web/storybook/) doesn't support it. But in the real world, a website with default system font for select looks pretty crappy. 

**How to reproduce**
Simplified test case: https://codesandbox.io/s/zk6oop43o4

Steps to reproduce:
1. Observe the styles and notice the console error

**Expected behavior**
There should be a way of changing the default font-family of picker. Default is "System" which was set by this PR https://github.com/necolas/react-native-web/pull/860

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.10.1
* React (version): 16.8.6
* Browser: ALL

**Comment by PeterKottas** [comment]
Ok, I think I slightly misunderstood and it's all making more sense now. As we are in the browser, I can obviously inject styles and override the default for select globally. While that wouldn't work on react-native, that's sort of a given as their api just doesn't support that.

The way of thinking here is probably because RN doesn't support it, RNW won't either. Even with some convenience api. Cause it could be misleading. 

I think this can pretty much be closed, I'd appreciate if somebody could verify my logic though.

**Comment by paularmstrong** [comment]
@PeterKottas agree that this is expected. RN won't allow anything other than the system font for this component, so RNW isn't going to add separate support for something you can't do natively.

**Comment by PeterKottas** [comment]
Perfect. I got confused cause I've pretty much set the fontFamily for all component via default props, and this was the only one causing problems. The reasons for that are obviously valid, thanks for your input @paularmstrong

**Comment by zivchen** [comment]
Hi Guys
This issue shouldn't be closed.
I fully understand the logic behind what you wrote but in the end of the day my web app doesn't look good as expected and it prevent from a RNW to be perfect as it should.
Do you know any way to bypass that? (global CSS doesn't work)
