### ISSUE TITLE
Compatibility with React Native @0.59

### ISSUE THREAD

**Issue by Sofianne8** [necolas/react-native-web#1349]
Are we able to work with the latest version of React Native? 
The official documentation says that it is compatible with version 0.55.

Thanks

**Comment by steida** [comment]
@Sofianne8 You should always read issues before bothering people with the already answered question. Please, be polite.

**Comment by Sofianne8** [comment]
@steida I don't know why you are questioning my politeness, but I guess this is not how you are supposed to answer people. 

I already checked other issues and unfortunately I did not find an answer, maybe I should look more. 

I am thankful for any help I get usually but I prefer to not get any answer if you are answering in that way. 

Thank you.

**Comment by steida** [comment]
As you wish.

**Comment by necolas** [comment]
It basically works but there are some changes to make to account for additions to the React Native component APIs.
