### ISSUE TITLE
NOTICE: API removals

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1352]
The next major release still remove all the APIs that have been deprecated or removed from React Native. *There will be no deprecation period in RNW.* Several of those APIs were never implemented and most of the rest of them involve unnecessary overhead. A notable exception is `CheckBox` which I think belongs in the core and I will continue to maintain

**Comment by piranna** [comment]
Would this help to update `react-native-web` to be compatible with React Native latest v0.59 (maybe 0.60 when the deprecations take effect)? I'm willing to update [re-start](https://github.com/react-everywhere/re-start) and my work project to latest available versions...

**Comment by necolas** [comment]
Additional RN exports I'm hoping to get moved out of core (https://github.com/facebook/react-native/issues/23313)

- Button (kind of useless)
- DrawerLayoutAndroid (android-only atm)
- FlatList (doesn't work well on web, no dependencies on RN internals)
- VirtualizedList (as above)

**Comment by piranna** [comment]
> * Button (kind of useless)
> * FlatList (doesn't work well on web, no dependencies on RN internals)
> * VirtualizedList (as above)

Well, call me a freerunner, but so far in the project I've been involved, we use extensively both `Button` and `FlatList` to be considered useless, also on web...

**Comment by necolas** [comment]
You can trivially build your own, better button - https://github.com/necolas/react-native-web/blob/b732cec/packages/react-native-web/src/exports/Button/index.js

And if FlatList were an external package you could still use it on web if you want.

**Comment by cltsang** [comment]
> Additional RN exports I'm hoping to get moved out of core ([facebook/react-native#23313](https://github.com/facebook/react-native/issues/23313))
> 
>     * Button (kind of useless)
> 
>     * DrawerLayoutAndroid (android-only atm)
> 
>     * FlatList (doesn't work well on web, no dependencies on RN internals)
> 
>     * VirtualizedList (as above)
> 
>     * TabBarIOS
> 
>     * TimePickerAndroid
> 
>     * ToastAndroid

For VirtualizedList and FlatList, what are the altematives? The react-native core ones encapsulate a lot of optimizations.

**Comment by EyMaddis** [comment]
@cltsang Here is an alternative with web support:
https://github.com/Flipkart/recyclerlistview

**Comment by necolas** [comment]
All the removed APIs are visible in the commits referenced above
