### ISSUE TITLE
is shadowSpread unimplemented?

### ISSUE THREAD

**Issue by EvanBacon** [necolas/react-native-web#1357]
https://github.com/necolas/react-native-web/blob/33dc3cb01869cde556387e1cbc4e43323015b5b7/packages/react-native-web/src/modules/ShadowPropTypes/index.js#L23
I can't find any uses of it. Would you accept a PR to have it implemented or removed?

**Comment by necolas** [comment]
I'll remove it. I proposed internally that we replace the RN shadow props with these:

```
// boxShadow
type BoxShadowStyle = BoxShadow | Array<BoxShadow>;
// textShadow
type TextShadowStyle = BoxShadow | Array<BoxShadow>;

type BoxShadow = {
  color?: ?Color;
  spreadRadius?: ?number|string;
  blurRadius?: ?number|string;
  x?: ?number|string;
  y?: ?number|string
  inset?: ?boolean
};

type TextShadow = {
  color?: ?Color;
  blurRadius?: ?number|string;
  x?: ?number|string;
  y?: ?number|string
  inset?: ?boolean
};
```

That would support multiple shadows and additional features that make them as powerful as those on the web.

**Comment by necolas** [comment]
This is fixed in the `next` branch

**Comment by necolas** [comment]
https://github.com/facebook/react-native/issues/26110
