### ISSUE TITLE
Image Not Working In Live Demo

### ISSUE THREAD

**Issue by oxbits** [necolas/react-native-web#1360]
**The problem**
Image Not Working In Live Demo:
https://necolas.github.io/react-native-web/examples/

**How to reproduce**
Steps to reproduce:
1. https://necolas.github.io/react-native-web/examples/
2. Click on "\<Image\>"
3. See a white page

**Expected behavior**
I imagine there should be an image displayed visibly.

**Environment (include versions). Did this work in previous versions?**
I do not know.

* React Native for Web (version): ?
* React (version): ?
* Browser: macos chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by tuantvk** [comment]
same issues
