### ISSUE TITLE
ClassName deprecation work-around

### ISSUE THREAD

**Issue by CareLuLu-Gabriel** [necolas/react-native-web#1362]
**Is your feature request related to a problem? Please describe.**

This issue is linked to the issue #1146 that has been closed. It seems that className will be completely removed and that will break my app.

1. We use the same code to render server-side web pages (including AMP pages), client-side web pages, iOS app and android app.
2. We mostly use StyleSheet but we also use className for media queries to adapt the HTML generated by the server. It is important that this is done via CSS (not script like https://github.com/ReactTraining/react-media) so Google and other search engines can index and render the page correctly independent of the screen size.

Example of our use case:
```
// components/Helmet/index.js
const noop = () => null;

export const Helmet = noop;
export const meta = noop;
export const title = noop;
export const style = noop;
export const script = noop;
export const link = noop;

// components/Helmet/index.web.js
import React from 'react';

export { Helmet } from 'react-helmet';

export const link = props => <link {...props} />;
export const meta = props => <meta {...props} />;
export const title = props => <title {...props} />;
export const style = props => <style amp-custom="javascript:undefined" {...props} />;
export const script = props => <script {...props} />;

// components/AdjustableText/index.js
import React from 'react';
import { Text, StyleSheet } from 'react-native';
import { Helmet, style } from '../Helmet';

const styles = StyleSheet.create({
  text: {
    fontSize: 20,
  },
});

const AdjustableText = props => (
  <React.Fragment>
    <Helmet>
      <style>
        {`
           @media (min-width: 768px) {
              .AdjustableText { font-size: 25px; }
           }
        `}
       </style>
    </Helmet>
    <Text {...props} className="AdjustableText__text" style={styles.text} />
  </React.Fragment>
);

export default AdjustableText;
```

**Describe a solution you'd like**
It'd be great if className could be enabled in the future (maybe with a flag).

**Describe alternatives you've considered**
I've considered a few options but they don't seem to solve the problem.

1. Libraries like https://github.com/contra/react-responsive and https://github.com/ReactTraining/react-media depend on react (javascript) to hide/show elements that match the query. This doesn't work for AMP and certain server-side rendered pages.
2. Wrapping components with DIV isn't ideal because it changes the component properties. For example, if I wrap `AdjustableText` with a `<div>`, it no longer can be nested in `<Text>`.

Is there a work around for that?

**Comment by necolas** [comment]
You can apply styles using data-* attribute selectors but it's not safe as your custom css can collide with the library's

https://github.com/necolas/react-native-web/issues/1146#issuecomment-481940724
