### ISSUE TITLE
Does it work with react-native-maps ?

### ISSUE THREAD

**Issue by brunohkbx** [necolas/react-native-web#1363]
**The problem**
I'm trying to run web an expo-project which uses MapView and I've got this error:
```
TypeError: Object(...) is not a function
nativeComponent
node_modules/react-native-maps/lib/components/MapView.js:945
  942 | 
  943 | MapView.MAP_TYPES = MAP_TYPES;
  944 | 
> 945 | const nativeComponent = Component => requireNativeComponent(Component, MapView, {
  946 |   nativeOnly: {
  947 |     onChange: true,
  948 |     onMapReady: true,
```

```
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.
```

**How to reproduce**
Execute this piece of code
```
<MapView
  style={{ flex: 1 }}
  initialRegion={{
    latitude: 37.78825,
    longitude: -122.4324,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }}
/>
```

**Expected behavior**
It should open a google-maps.

**Comment by pinturic** [comment]
Did you try this:  ?
https://github.com/react-native-web-community/react-native-web-maps

**Comment by necolas** [comment]
cc @EvanBacon

**Comment by EvanBacon** [comment]
Could you move this issue to https://github.com/expo/expo/issues/. I added the Map shim to prevent crashing but unfortunately that left a lot of things unimplemented. The Google Maps web SDK is also pretty expensive so I haven't been in a rush to add support yet. You can look at the current implementation here: https://github.com/expo/expo/blob/master/packages/expo/src/Maps/MapView.web.tsx

**Comment by thiemo--bleeken** [comment]
ran into the same issue. where can i find the latest status? thanks!

**Comment by MOwais** [comment]
Is there a fix for this? I am getting the same error

**Comment by YajJackson** [comment]
I am dealing with this same issue.

**Comment by EvanBacon** [comment]
I've been very slowly adding web support here: https://github.com/expo/react-native-maps/pull/2

**Comment by Daniel-Georgiev** [comment]
Hey @EvanBacon, you are doing a sublime job!
Bad thing is I am still running into the same issue as the OP. I am getting the error on MapView import. 
I'm using expo with the implementation that you've made.

**Comment by davidbaussart** [comment]
Hi @EvanBacon, thanks for working on this! I've tried to use a MapView with expo web, and also get an import error, similar to Bruno's:

`/node_modules/react-native-maps/lib/components/MapView.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.`

I've been following the [web setup documentation](https://docs.expo.io/versions/latest/sdk/map-view/), unfortunately I did not manage to make it work. Do you know where can I find a working example? Thanks!

**Comment by pologonzalo** [comment]
Yeah, same issue that @davidbaussart is having, any solution?

**Comment by WickedBrat** [comment]
funny thing is that I'm not using react-native-maps in the project and am still getting the same project. The root of the problem appears to be something else.

**Comment by edi** [comment]
I'm having the same issue. Running a "bare-minimum" expo template, to which I've added the expo maps. Not sure what else I should do here.

Works just fine on iOS / Android, but the web part crashes.

**Comment by diegoboston** [comment]
The snack linked from here:
https://docs.expo.io/versions/latest/sdk/map-view/
also fails on Web.

(0 , g.requireNativeComponent) is not a function
  Evaluating module://react-native-maps.js
  Evaluating module://App.js.js
  Loading module://App.js

**Comment by jebjiayoub** [comment]
Is there any solution to make web map work in web browser ?  i'm still getting the following error  :    
 " `TypeError: Object(...) is not a function` "

**Comment by diegoboston** [comment]
I have made some progress by changing the import to:
import {MapView} from 'expo';

Also, important:
Location.setApiKey(<YOUR API KEY FROM GOOGLE>);

You'll have to set up a billing account at Google to make it work.

**Comment by brymurod** [comment]
Hello @diegoboston Have you been able to make it work ?

**Comment by diegoboston** [comment]
@brymurod not yet. I thought my issue was with the Google API keys, but when I fixed that, nothing would render anyway. I believe the library is not fully implemented yet. @EvanBacon do you have a working example of maps for a web app?

BTW, react-native-web-community/react-native-web-maps doesn't seem to work either.

**Comment by arjun-bhatt** [comment]
also interested

**Comment by lcsalt** [comment]
I'm having the same issue, is there a solution for this yet?

**Comment by augustosamame** [comment]
+1

**Comment by vrinch** [comment]
any progress on this issue please?

**Comment by shubhamdeol** [comment]
@vrinch  use https://github.com/expo/react-native-maps/blob/master/docs/examples-setup.md
yarn add https://github.com/expo/react-native-maps/blob/master/docs/examples-setup.md

**Comment by vrinch** [comment]
Does it work on expo web @shubhamdeol?

**Comment by shubhamdeol** [comment]
> Does it work on expo web @shubhamdeol?

@vrinch  yes, It does work

**Comment by vrinch** [comment]
@shubhamdeol there’s no project in the link you shared earlier

**Comment by vrinch** [comment]
@shubhamdeol it’s not working for expo web

**Comment by shubhamdeol** [comment]
I am using bare work flow, and it works for me.

**Comment by vrinch** [comment]
> I am using bare work flow, and it works for me.

I guess there’s an issue with managed app

**Comment by YahyaBagia** [comment]
> I am using bare work flow, and it works for me.

@shubhamdeol Could you please share with us how do you import `MapView`, `Markers`, `PROVIDER_GOOGLE`, `MAP_TYPES` ?

**Comment by fuelkoy** [comment]
Have someone gotten this to work somehow? It works fine in android, but Im facing following import error if i try to use MapView in web: Module not found: Can't resolve 'react-native-web/dist/exports/ColorPropType' in 'C:\PATH\node_modules\react-native-maps\lib\components'

**Comment by vrinch** [comment]
> @vrinch use https://github.com/expo/react-native-maps.git
> `yarn add https://github.com/expo/react-native-maps.git`

it works on web, however when I try to load it in my mobile phone browser, I am getting a blank screen. No errors a all

**Comment by vrinch** [comment]
the maker works on system browsers, however, when I try to use markers on mobile browsers, it keeps showing a blank screen without any error whatsoever

**Comment by brymurod** [comment]
@vrinch Make sure you have added the code for location permission.

Similar to this:
Import:
import * as Permissions from 'expo-permissions';

Code:
_getLocationAsync = async () => {
        let { status } = await Permissions.askAsync(Permissions.LOCATION);
        if (status !== 'granted') {
          this.setState({
            errorMessage: 'Permission to access location was denied',
          });
        }
}

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by vrinch** [comment]
@brymurod it should work without location permission if I’m inputting the location myself
What I’m trying to say is it currently works when I load up in the laptop browser, but doesn’t on mobile browser and it’s being caused by the marker

**Comment by flyskywhy** [comment]
npm install --save-dev react-app-rewired

Create a `config-overrides.js` in your project root

```
// used by react-app-rewired

const webpack = require('webpack');
const path = require('path');

module.exports = {
  webpack: function (config, env) {
    config.module.rules[1].use[0].options.baseConfig.extends = [
      path.resolve('.eslintrc.js'),
    ];

    const webAliases = {
      'react-native': path.resolve('web/aliases/react-native'),
    };
    Object.assign(config.resolve.alias, webAliases);

    config.plugins.push(
      new webpack.DefinePlugin({
        __DEV__: process.env.NODE_ENV !== 'production',
      }),
    );

    return config;
  },
  paths: function (paths, env) {
    paths.appIndexJs = path.resolve('index.web.js');
    paths.appSrc = path.resolve('.');
    paths.moduleFileExtensions.push('ios.js');
    return paths;
  },
};
```

Also create a `web/aliases/react-native/index.js`
```
// ref to https://levelup.gitconnected.com/react-native-typescript-and-react-native-web-an-arduous-but-rewarding-journey-8f46090ca56b

import {Text as RNText, Image as RNImage} from 'react-native-web';
// Let's export everything from react-native-web
export * from 'react-native-web';

// And let's stub out everything that's missing!
export const ViewPropTypes = {
  style: () => {},
};
RNText.propTypes = {
  style: () => {},
};
RNImage.propTypes = {
  style: () => {},
  source: () => {},
};

export const Text = RNText;
export const Image = RNImage;
// export const ToolbarAndroid = {};
export const requireNativeComponent = () => {};
```

Now you can just run `react-app-rewired start` instead of `react-scripts start`

**Comment by iman2420** [comment]
> `import MapView, { Marker, PROVIDER_GOOGLE, MAP_TYPES } from "react-native-maps";`

> Web Bundling complete 22575ms
./node_modules/react-native-maps/lib/components/MapView.js:204:26
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  202 |    *
  203 |    */
> 204 |   loadingBackgroundColor: ColorPropType,
      |                          ^
  205 | 
  206 |   /**
  207 |    * Loading indicator color while generating map cache image or loading the map
./node_modules/react-native-maps/lib/components/MapView.js:211:25
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  209 |    *
  210 |    */
> 211 |   loadingIndicatorColor: ColorPropType,
      |                         ^
  212 | 
  213 |   /**
  214 |    * If `false` the user won't be able to change the map region being displayed.
./node_modules/react-native-maps/lib/components/MapCircle.js:44:15
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  42 |    * The stroke color to use for the path.
  43 |    */
> 44 |   strokeColor: ColorPropType,
     |               ^
  45 | 
  46 |   /**
  47 |    * The fill color to use for the path.
./node_modules/react-native-maps/lib/components/MapCircle.js:49:13
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  47 |    * The fill color to use for the path.
  48 |    */
> 49 |   fillColor: ColorPropType,
     |             ^
  50 | 
  51 |   /**
  52 |    * The order in which this tile overlay is drawn with respect to other overlays. An overlay
./node_modules/react-native-maps/lib/components/MapPolygon.js:62:15
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  60 |    * The stroke color to use for the path.
  61 |    */
> 62 |   strokeColor: ColorPropType,
     |               ^
  63 | 
  64 |   /**
  65 |    * The fill color to use for the path.
./node_modules/react-native-maps/lib/components/MapPolygon.js:67:13
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  65 |    * The fill color to use for the path.
  66 |    */
> 67 |   fillColor: ColorPropType,
     |             ^
  68 | 
  69 |   /**
  70 |    * The order in which this tile overlay is drawn with respect to other overlays. An overlay
./node_modules/react-native-maps/lib/components/MapPolyline.js:41:13
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  39 |    * The fill color to use for the path.
  40 |    */
> 41 |   fillColor: ColorPropType,
     |             ^
  42 | 
  43 |   /**
  44 |    * The stroke width to use for the path.
./node_modules/react-native-maps/lib/components/MapPolyline.js:51:15
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  49 |    * The stroke color to use for the path.
  50 |    */
> 51 |   strokeColor: ColorPropType,
     |               ^
  52 | 
  53 |   /**
  54 |    * The stroke colors to use for the path.
./node_modules/react-native-maps/lib/components/MapPolyline.js:56:34
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  54 |    * The stroke colors to use for the path.
  55 |    */
> 56 |   strokeColors: PropTypes.arrayOf(ColorPropType),
     |                                  ^
  57 | 
  58 |   /**
  59 |    * The order in which this tile overlay is drawn with respect to other overlays. An overlay
./node_modules/react-native-maps/lib/components/MapMarker.js:79:12
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  77 |    * which can be customized by this color. Ignored if a custom marker is being used.
  78 |    */
> 79 |   pinColor: ColorPropType,
     |            ^
  80 | 
  81 |   /**
  82 |    * The coordinate for the marker.
./node_modules/react-native-maps/lib/components/MapView.js:370:14
"export 'EdgeInsetsPropType' was not found in 'react-native-web/dist/index'
  368 |    *
  369 |    */
> 370 |   mapPadding: EdgeInsetsPropType,
      |              ^
  371 | 
  372 |   /**
  373 |    * (Google Maps only, iOS)
./node_modules/react-native-maps/lib/components/MapView.js:399:20
"export 'EdgeInsetsPropType' was not found in 'react-native-web/dist/index'
  397 |    * See `EdgeInsetsPropType.js` for more information.
  398 |    */
> 399 |   legalLabelInsets: EdgeInsetsPropType,
      |                    ^
  400 | 
  401 |   /**
  402 |    * Callback that is called once the map is fully loaded.
./node_modules/react-native-maps/lib/components/MapView.js:519:17
"export 'PointPropType' was not found in 'react-native-web/dist/index'
  517 |    * @platform ios
  518 |    */
> 519 |   compassOffset: PointPropType,
      |                 ^
  520 | 
  521 |   /**
  522 |    * Callback that is called when a level is activated on a indoor building.
./node_modules/react-native-maps/lib/components/MapView.js:70:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  68 | 
  69 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 70 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  71 | 
  72 | const propTypes = {
  73 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapWMSTile.js:12:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  10 | 
  11 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 12 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  13 | 
  14 | const propTypes = {
  15 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapUrlTile.js:12:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  10 | 
  11 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 12 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  13 | 
  14 | const propTypes = {
  15 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapCalloutSubview.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapCallout.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapLocalTile.js:12:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  10 | 
  11 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 12 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  13 | 
  14 | const propTypes = {
  15 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapCircle.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapPolygon.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapHeatmap.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapPolyline.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapMarker.js:28:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  26 | 
  27 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 28 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  29 | 
  30 | const propTypes = {
  31 |   ...viewPropTypes,
Web Bundling complete 1674ms
./node_modules/react-native-maps/lib/components/MapView.js:204:26
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  202 |    *
  203 |    */
> 204 |   loadingBackgroundColor: ColorPropType,
      |                          ^
  205 | 
  206 |   /**
  207 |    * Loading indicator color while generating map cache image or loading the map
./node_modules/react-native-maps/lib/components/MapView.js:211:25
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  209 |    *
  210 |    */
> 211 |   loadingIndicatorColor: ColorPropType,
      |                         ^
  212 | 
  213 |   /**
  214 |    * If `false` the user won't be able to change the map region being displayed.
./node_modules/react-native-maps/lib/components/MapMarker.js:79:12
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  77 |    * which can be customized by this color. Ignored if a custom marker is being used.
  78 |    */
> 79 |   pinColor: ColorPropType,
     |            ^
  80 | 
  81 |   /**
  82 |    * The coordinate for the marker.
./node_modules/react-native-maps/lib/components/MapPolyline.js:41:13
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  39 |    * The fill color to use for the path.
  40 |    */
> 41 |   fillColor: ColorPropType,
     |             ^
  42 | 
  43 |   /**
  44 |    * The stroke width to use for the path.
./node_modules/react-native-maps/lib/components/MapPolyline.js:51:15
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  49 |    * The stroke color to use for the path.
  50 |    */
> 51 |   strokeColor: ColorPropType,
     |               ^
  52 | 
  53 |   /**
  54 |    * The stroke colors to use for the path.
./node_modules/react-native-maps/lib/components/MapPolyline.js:56:34
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  54 |    * The stroke colors to use for the path.
  55 |    */
> 56 |   strokeColors: PropTypes.arrayOf(ColorPropType),
     |                                  ^
  57 | 
  58 |   /**
  59 |    * The order in which this tile overlay is drawn with respect to other overlays. An overlay
./node_modules/react-native-maps/lib/components/MapPolygon.js:62:15
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  60 |    * The stroke color to use for the path.
  61 |    */
> 62 |   strokeColor: ColorPropType,
     |               ^
  63 | 
  64 |   /**
  65 |    * The fill color to use for the path.
./node_modules/react-native-maps/lib/components/MapPolygon.js:67:13
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  65 |    * The fill color to use for the path.
  66 |    */
> 67 |   fillColor: ColorPropType,
     |             ^
  68 | 
  69 |   /**
  70 |    * The order in which this tile overlay is drawn with respect to other overlays. An overlay
./node_modules/react-native-maps/lib/components/MapCircle.js:44:15
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  42 |    * The stroke color to use for the path.
  43 |    */
> 44 |   strokeColor: ColorPropType,
     |               ^
  45 | 
  46 |   /**
  47 |    * The fill color to use for the path.
./node_modules/react-native-maps/lib/components/MapCircle.js:49:13
"export 'ColorPropType' was not found in 'react-native-web/dist/index'
  47 |    * The fill color to use for the path.
  48 |    */
> 49 |   fillColor: ColorPropType,
     |             ^
  50 | 
  51 |   /**
  52 |    * The order in which this tile overlay is drawn with respect to other overlays. An overlay
./node_modules/react-native-maps/lib/components/MapView.js:370:14
"export 'EdgeInsetsPropType' was not found in 'react-native-web/dist/index'
  368 |    *
  369 |    */
> 370 |   mapPadding: EdgeInsetsPropType,
      |              ^
  371 | 
  372 |   /**
  373 |    * (Google Maps only, iOS)
./node_modules/react-native-maps/lib/components/MapView.js:399:20
"export 'EdgeInsetsPropType' was not found in 'react-native-web/dist/index'
  397 |    * See `EdgeInsetsPropType.js` for more information.
  398 |    */
> 399 |   legalLabelInsets: EdgeInsetsPropType,
      |                    ^
  400 | 
  401 |   /**
  402 |    * Callback that is called once the map is fully loaded.
./node_modules/react-native-maps/lib/components/MapView.js:519:17
"export 'PointPropType' was not found in 'react-native-web/dist/index'
  517 |    * @platform ios
  518 |    */
> 519 |   compassOffset: PointPropType,
      |                 ^
  520 | 
  521 |   /**
  522 |    * Callback that is called when a level is activated on a indoor building.
./node_modules/react-native-maps/lib/components/MapView.js:70:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  68 | 
  69 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 70 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  71 | 
  72 | const propTypes = {
  73 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapMarker.js:28:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  26 | 
  27 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 28 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  29 | 
  30 | const propTypes = {
  31 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapPolyline.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapHeatmap.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapPolygon.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapCircle.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapUrlTile.js:12:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  10 | 
  11 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 12 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  13 | 
  14 | const propTypes = {
  15 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapWMSTile.js:12:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  10 | 
  11 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 12 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  13 | 
  14 | const propTypes = {
  15 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapLocalTile.js:12:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
  10 | 
  11 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 12 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  13 | 
  14 | const propTypes = {
  15 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapCallout.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
./node_modules/react-native-maps/lib/components/MapCalloutSubview.js:10:22
"export 'ViewPropTypes' was not found in 'react-native-web/dist/index'
   8 | 
   9 | // if ViewPropTypes is not defined fall back to View.propType (to support RN < 0.44)
> 10 | const viewPropTypes = ViewPropTypes || View.propTypes;
     |                      ^
  11 | 
  12 | const propTypes = {
  13 |   ...viewPropTypes,
