### ISSUE TITLE
Responsive SSR and Media Queries

### ISSUE THREAD

**Issue by jupl** [necolas/react-native-web#1368]
I see there is information on [media queries](https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md#what-about-media-queries) and [SSR](https://github.com/necolas/react-native-web/blob/master/docs/guides/server-side-rendering.md) but I was wondering if react-native-web can support responsive components that work with SSR, such as it generates media queries in case someone has JavaScript disabled but responsiveness still works while it's a no-op in native?

**Comment by necolas** [comment]
There's no built-in support for media queries
