### ISSUE TITLE
Redundant inline styles added as part of the React Native Web Library ? 

### ISSUE THREAD

**Issue by rahulrsingh09** [necolas/react-native-web#1370]
I am trying to use React Native components in the web by making use of React Native web Library.

But when doing that my DOM elements has lots of inline styles which makes it look cluttered  , how can we get rid of the redundant styles as part of the transpilation .

Some thing like this 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/XUllP.png

And can we even get rid of this transplied inline css.

This is how my React Native component used here looks like 

    import React from "react";
    import { View, Text, Platform, StyleSheet } from "react-native";

    const instructions = Platform.select({
      ios: "Press Cmd+R to reload,\n" + "Cmd+D or shake for dev menu",
      android:
        "Double tap R on your keyboard to reload,\n" +
        "Shake or press menu button for dev menu",
      web: "Your browser will automatically refresh as soon as you save the file."
    });

    const HomeScreen = () => {
      return (
        <View >
          <Text>
            Welcome to React Native Web universal app!
          </Text>
          <Text>
            This component is shared between web and react environment. To see how
            it works, just edit the HomeScreen.js
          </Text>
          <Text>{instructions}</Text>
        </View>

      );
    };

    /*const styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#F5FCFF"
      },
      welcome: {
        fontSize: 20,
        textAlign: "center",
        margin: 10
      },
      instructions: {
        textAlign: "center",
        color: "#333333",
        marginBottom: 5
      }
    });*/

    export default HomeScreen;

**Comment by necolas** [comment]
Those aren't inline styles and you should update to the latest version

**Comment by rahulrsingh09** [comment]
Sorry to bug you again @necolas  but you mean to say in the latest version of rnw these inline code will be eliminated. Will be glad if you gave a heads up. I didnt get any context in stackoverflow.. and can i remove them..
