### ISSUE TITLE
What are these statements added as css classes in the DOM for a RN component used in RNW

### ISSUE THREAD

**Issue by rahulrsingh09** [necolas/react-native-web#1371]
![image](https://user-images.githubusercontent.com/17721520/59706345-eb3f1e80-921d-11e9-9fb3-6969c9b527ed.png)

In case of Embedding a RN component and using it in web the RNW generates some css classes that are attached to the DOM for the respective component . 

But what are these and why are they even there and what is the use case for these classes and can we remove them to make sure the DOM appears more clean it has been modified a lot from the prev versions but can we eliminate them..

Post on Stackoverflow for these do-not gather much attention so writing over her can some one please give 5 mins of their time and explain this which may help us use this Framework and even contribute to this

**Comment by necolas** [comment]
That's how stuff gets styled in a way that matches the RN algorithm! No, it's not going to be removed because this is how the library works and it has nothing to do with "clean code".
