### ISSUE TITLE
Native Router with web+android react-native-web

### ISSUE THREAD

**Issue by Fen0l** [necolas/react-native-web#1372]
Hello !

I am starting a react native cross-platform using react-native-web . I would like to use the react-router-native as default routing for all platforms  but I cannot get ride of it.

Does this issue https://github.com/necolas/react-native-web/issues/878 still explain the problem  or does we have to use both react-router-native and react-router-dom in order to have a proper routing on all of our platform ?

Currently, we are using codesandbox.io in order to test our application using react-router-native and it works well, but when we want to build it locally, it failed. 

```
./node+modules/react-router-native/NativeRouter.js
Module parse failed: Unexpected token (11:9)
You may need an appropriate loader to handle this file type>
*/
function NativeRouter(props) {
   return <MemoryRouter {...props} />
}
```
Our versions:
```
"react": "16.8.6",
"react-native-web": "0.11.2",
"react-dom": "16.8.6",
"react-native": "0.59.5",
"react-router-native": "5.0.0",
```

Thank for any hint :)

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/docs/guides/multi-platform-apps.md#web-packaging-for-existing-react-native-apps

**Comment by tombh** [comment]
Previous link is broken, I think this is the new link: https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page
