### ISSUE TITLE
Add mobile web as a different platform

### ISSUE THREAD

**Issue by reinhardholl** [necolas/react-native-web#1373]
**Is your feature request related to a problem? Please describe.**
Sometimes the need arises to create styles or components specifically for Mobile Web. Currently, we check width, etc in conjunction with Platform to determine if the browser is a mobile browser and change styles/components on the fly.

**Describe a solution you'd like**
It could be good to have `Platform.OS === 'mobile-web'` as an option to easily switch between styles and components.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by necolas** [comment]
I don't think that makes sense and it goes against the whole ethos of the project. Apps should respond to changes in layout, pointer type, etc., not unreliable inference of what is "desktop web" or "mobile web". This is along the lines of preferring "feature detection" and "progressive enhancement" over UA sniffing.
