### ISSUE TITLE
AppRegistry.runApplication replaces DOM node in dev but appends in prod

### ISSUE THREAD

**Issue by rickysullivan** [necolas/react-native-web#1374]
**The problem**
In dev mode, `AppRegistry.runApplication` replaces the children of the target DOM node as expected. In prod mode, however, the react app is appended to a nested DOM element.

**How to reproduce**

Simplified test case: 
Dev: https://codesandbox.io/s/issue-react-native-for-web-g512l
Prod: https://csb-g512l.netlify.com/

Steps to reproduce:
1. Add child nodes to the targeted DOM element.
2. Deploy app.
3. See app appended to child node.

**Expected behavior**
I expect the DOM element's children to be replaced, not appended. As it does in dev.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.x
* React (version): 16.8.4
* Browser: Chrome 75.0.3770.100

I'm trying to create a loading screen using DOM elements in the index.html file.

**Comment by necolas** [comment]
That's probably down to this line and ReactDOM leaving existing HTML alone when hydrating

**Comment by necolas** [comment]
What I think I'll do is add a field `hydrate` to the application params, and that can be used on the client to opt into hydrating the app if you know you server rendered.

```
ApplicationRegistry.runApplication('App', {
  initialProps: {},
  rootTag: document.getElementById('root'),
  hydrate: true
});
```

**Comment by zamponotiropita** [comment]
Any progress with this issue?

**Comment by necolas** [comment]
This change is in master if you want to try it out before I cut a pre-release version that includes it
