### ISSUE TITLE
StyleSheet.create issue

### ISSUE THREAD

**Issue by artyorsh** [necolas/react-native-web#1377]
**The problem**

Unexpected behavior when spreading `StyleSheet.create` styles into another style object. `StyleSheet` styles are missing in a final object in this case.

**How to reproduce**

Simplified test case: [Sample project on Github](https://github.com/artyorsh/react-native-web-demo/blob/master/src/sample.component.tsx#L12)

Steps to reproduce:
1. Create some styles object using `StyleSheet.create`
2. Spread it into another object
3. Apply to component

**Expected behavior**

Both mobile and web components look the same. 

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.4
* React (version): 16.8.3
* Browser: Google Chrome 74.0.3729.169

**Additional context**

Added some possible workarounds [in comments](https://github.com/artyorsh/react-native-web-demo/blob/master/src/sample.component.tsx#L13) inside a demo project.

**Comment by necolas** [comment]
As mentioned in the docs, that is not supported and creating new objects is bad for perf anyway. Arrays are used to compose styles
