### ISSUE TITLE
Build in Production mode not working

### ISSUE THREAD

**Issue by VasilUrda** [necolas/react-native-web#1381]
Please check this
<img width="780" alt="Screen Shot 2019-06-26 at 11 57 54 PM" src="https://user-images.githubusercontent.com/33361100/60195749-3d132480-986e-11e9-8c6b-0081f06d9d8e.png">

**Comment by VasilUrda** [comment]
Please tell me why you closed this issue

**Comment by steida** [comment]
@VasilUrda 1) Because it looks like a bug in your code. 2) There are clear instructions on how to write issues. 3) Open source maintainer is not your slave.
