### ISSUE TITLE
createElement -> unstable_createElement

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1385]
Rename this export to communicate that it is unstable and not part of the public API (i.e., may experience breaking changes at any time)

**Comment by JandersonConstantino** [comment]
I would like to make these changes as my first issue in this repository.
Do I only need to change the folder name and imports?

**Comment by aaronmgdr** [comment]
Now that this api is officially unstable what the alternative? It seems to be serving a unique purpose of being able to use RN `Stylesheet` styles on what were regular dom elements. 

Is the solution to style them in some other way and not have the RNW unique features available?
