### ISSUE TITLE
Presence of Icon component breaks numberOfLines in Text

### ISSUE THREAD

**Issue by zamponotiropita** [necolas/react-native-web#1386]
**The problem**

Using `react-native-vector-icons` component breaks `numberOfLines` in Text component. I originally encountered this problem while placing an Icon component at a random place in my render function. So the position doesn't seem to make a difference.

**How to reproduce**

```jsx
import React from "react";
import { Text } from "react-native";
import Icon from "react-native-vector-icons/MaterialCommunityIcons";

export default Test = props => (
  <React.Fragment>
    <Text numberOfLines={1}>{"multimulti\nlinenline\ntestnt"}</Text>
    <Icon name="send" />
  </React.Fragment>
);

```

**Expected behavior**

I expect that the `numberOfLines` prop will work independent of other components added aside.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.4
* React (version): 16.7.0
* Browser: Chrome
* react-native-vector-icons (version): 6.6.0

**Comment by necolas** [comment]
Please add a reduced test case, as required in the issue template, or I will close this issue

**Comment by zamponotiropita** [comment]
numberOfLines started working out of the blue again everywhere in my project. Didn't change anything. That's really odd.

**Comment by HailongZeng** [comment]
> **The problem**
> 
> Using `react-native-vector-icons` component breaks `numberOfLines` in Text component. I originally encountered this problem while placing an Icon component at a random place in my render function. So the position doesn't seem to make a difference.
> 
> **How to reproduce**
> 
> ```js-jsx
> import React from "react";
> import { Text } from "react-native";
> import Icon from "react-native-vector-icons/MaterialCommunityIcons";
> 
> export default Test = props => (
>   <React.Fragment>
>     <Text numberOfLines={1}>{"multimulti\nlinenline\ntestnt"}</Text>
>     <Icon name="send" />
>   </React.Fragment>
> );
> ```
> 
> **Expected behavior**
> 
> I expect that the `numberOfLines` prop will work independent of other components added aside.
> 
> **Environment (include versions). Did this work in previous versions?**
> 
> * React Native for Web (version): 0.11.4
> * React (version): 16.7.0
> * Browser: Chrome
> * react-native-vector-icons (version): 6.6.0

Same issue for me now, have you figured out how to implement it today?
