### ISSUE TITLE
Examples down

### ISSUE THREAD

**Issue by mhrisse** [necolas/react-native-web#1388]
**The problem**
Example website down.

**How to reproduce**
Visit https://necolas.github.io/react-native-web/examples/ in Chrome

Steps to reproduce:
1. Open Chrome
2. Visit https://necolas.github.io/react-native-web/examples/
:)

**Expected behavior**
Show Website

**Environment (include versions). Did this work in previous versions?**
Yes, always had a great example website experience. :)

<img width="1611" alt="Screen Shot 2019-07-01 at 2 18 02 PM" src="https://user-images.githubusercontent.com/1583014/60406686-4b18ca80-9c0b-11e9-83c3-a16bf1aa0ef5.png">

**Comment by centrodph** [comment]
<img width="1113" alt="Screen Shot 2019-07-01 at 08 18 49" src="https://user-images.githubusercontent.com/2073951/60432621-168c1b00-9bd9-11e9-8279-5381f0b3f3e8.png">

It's working for me

**Comment by mhrisse** [comment]
Hi! Yep, back up for me as well. I am in New Zealand, so maybe temp edge location issue. 

Awesome job on the project! We love it, especially with Expo and soon React Navigation.
