### ISSUE TITLE
React Native Web needs to support RN 0.59+ in order to support 64 bit mobile apps

### ISSUE THREAD

**Issue by SnakeHead** [necolas/react-native-web#1389]
React Native Web needs to support React Native 0.59+ in order to support 64 bit mobile apps for iOS and Android app stores otherwise the apps will be rejected after Aug 1.

https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

https://stackoverflow.com/questions/48732351/64-bit-version-issue-in-react-native-android-app-by-google-play-store/54406295#54406295

**Comment by necolas** [comment]
It supports 0.59

**Comment by SnakeHead** [comment]
Ok, thanks @necolas!  I thought it didn't since it says "Compatibility: React Native 0.55."  I'll give it a try...

**Comment by tomlobato** [comment]
> It supports 0.59

How to know? Readme says .55 only. Is there any more secure info than the readme?

**Comment by RichardLindhout** [comment]
It's baked in react-native-web natures since it uses a different implementation of everything react-native does. So react-native-web will probably always work with newer react-native versions, but it could be missing some new features or options.
