### ISSUE TITLE
checkType method very slow

### ISSUE THREAD

**Issue by bkniffler** [necolas/react-native-web#1390]
In my next.js / typescript project on dev mode, checkType method eats up a lot of time. Production is fine. I've been wondering lately why my project is so much slower while development, I guess a huge part is due to checkType.

<img width="751" alt="Bildschirmfoto 2019-07-02 um 16 50 40" src="https://user-images.githubusercontent.com/4349324/60527375-585cb480-9cf2-11e9-8548-a5e45a0061f9.png">

Is there any way to deactivate the strict type checking? Its becoming more and more of a problem with my growing amount of components.

**Comment by necolas** [comment]
See #1383

React is just slower in dev.

**Comment by brunolemos** [comment]
@bkniffler can you make a pull request replacing prop-types with flow types?

**Comment by bkniffler** [comment]
Hey there, if it was typescript I'd gladly help, but I'm not familiar with flow types :(

**Comment by bkniffler** [comment]
I've created a PR over here: https://github.com/necolas/react-native-web/pull/1477
