### ISSUE TITLE
Update vendored `Animated` to support `React.forwardRef`

### ISSUE THREAD

**Issue by janicduplessis** [necolas/react-native-web#1392]
**Is your feature request related to a problem? Please describe.**
RN added support for components using `React.forwardRef` in [this commit](https://github.com/facebook/react-native/commit/3e534b9aab5156adac67762877b2457408fe8934#diff-eef3f0bea8a82e16bf6e4ee901e83fbf). Seems like vendor sync was done using a script so I'm opening this issue instead of a PR.

**Describe a solution you'd like**
Sync Animated with lastest RN

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by necolas** [comment]
Duplicates #1325
