### ISSUE TITLE
Why we have to do this.

### ISSUE THREAD

**Issue by torabian** [necolas/react-native-web#1394]
Your library is great - it has given you 14K stars which I struggled to collect 200 at best. But I want to raise a question:

What is wrong with bootstrap that we have to use this?

"This is a new way or modern tool" I hear that a lot. No - We don't need this. Normal web, even without React and SPA is good enough. At least, React itself is enough. These shiny tools just make daily work harder. 

With respect, really you should focus on doing something useful for the world - start from collecting plastics in the ocean.

**Comment by necolas** [comment]
Did you post this while on a plastic connecting expedition?
