### ISSUE TITLE
Multiline TextInput ignores textAlignVertical

### ISSUE THREAD

**Issue by NiciusB** [necolas/react-native-web#1397]
**The problem**
Multiline TextInput components will always align the text at the top, since they use textarea.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/issue-react-native-for-web-em39u?fontsize=14

Steps to reproduce:
1. Create a multiline TextInput component
2. Try to change the text vertical alignment setting textAlignVertical to 'center' or 'bottom'

**Expected behavior**
Using a contenteditable div would allow to vertically align the text textAlignVertical, but it might have negative implications.

**Environment**

* React Native for Web (version): 0.11.2
* React (version): 0.59

**Comment by NiciusB** [comment]
While Android does use textAlignVertical, it seems like iOS doesn't. (https://facebook.github.io/react-native/docs/textinput.html#multiline)

That is a good reason to mark this issue as Won't fix, but on the other side, it would be great to already have support if iOS does eventually get support for textAlignVertical

**Comment by necolas** [comment]
Yeah this isn't possible with the native `textarea` and I don't plan to implement this component with `contenteditable` at this time.
