### ISSUE TITLE
TextInput's onContentSizeChange is not consistent with other platforms

### ISSUE THREAD

**Issue by NiciusB** [necolas/react-native-web#1399]
**The problem**
TextInput's onContentSizeChange is never fired when the size is reduced, only when it's increased

**How to reproduce**
Simplified test case: https://codesandbox.io/s/issue-react-native-for-web-hsjev?fontsize=14

**Expected behavior**
onContentSizeChange should also be fired when the size decreased, as it happens in other platforms

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.5
* React (version): 0.59
* Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by NiciusB** [comment]
Just realized that the height stays the same because the textarea element will keep the max height once set, even if it has less text.

However, in other platforms the height is actually reduced. I wonder if it's possible to achieve the same behavior on the web

**Comment by kennethlynne** [comment]
Duplicate of #1339 ?

**Comment by NiciusB** [comment]
You're right, don't know how did I miss that one
