### ISSUE TITLE
Unable to use flexShrink on a View

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#140]
It seems this lines https://github.com/necolas/react-native-web/blob/6a73d77030a8b48afb5f3db780409e451145d2a9/src/components/View/index.js#L78-L79 make it impossible to provide a flexShrink value.
I am sure this has been made to avoid the [flexbug # 1](https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored) but don't you think that providing a flexShrink value by hand should be honored?

**Comment by necolas** [comment]
Yeah it should be

**Comment by MoOx** [comment]
Thank you!
