### ISSUE TITLE
mapDispatchToProps doesn't update mapStateToProps

### ISSUE THREAD

**Issue by joan-saum** [necolas/react-native-web#1403]
**The problem**
Hello there,
Currently trying to be able to access to my react native app through the web, I can't figure out about a problem :

I'm using `react-redux` in my app.
The normal behaviour about `mapDispatchToProps`and `mapStateToProps`is that, when an action defined in `mapDispatchToProps` is dispatch, the props coming from `mapStateToProps`are update with the new state.

This is working fine in my react-native app

However, using react-native-web make that the `mapStateToProps` is not update. I have to reload the page to see the updated props.

I really dont know if the problem is coming from RNW or react-redux but I'm really stuck and don't know where to look to find a solution :/

**Comment by necolas** [comment]
This is just a view library so I don't see from this information how it can be responsible for your issue
