### ISSUE TITLE
ScrollView shows(Horizontal/Vertical)ScrollIndicator=false doesn't work on Firefox 68.

### ISSUE THREAD

**Issue by yungkittty** [necolas/react-native-web#1405]
**The problem**
The problem is that the props `shows(Horizontal/Vertical)ScrollIndicator={false}` doesn't hide the scrollbar on Firefox 68 (64-bit) in the `ScrollView`. This also means that it doesn't work with `FlatList` and `SectionList` as long as they're based upon `ScrollView`.

**How to reproduce**
To reproduce just render a `FlatList` with enough items to make it scrollable on Firefox 68 using the props `shows(Horizontal/Vertical)ScrollIndicator={false}`. You'll see that the scrollbar is still visible on Firefow 68 (64-bit) while on Chrome 75 (64-bit) it does work.

Here is few screenshoots of our project.

**Firefox 68 (64-bit)**
![Screenshot from 2019-07-29 12-51-16](https://user-images.githubusercontent.com/20394860/62043408-915c4c00-b200-11e9-9720-a1d6131167b2.png)

**Chrome 75 (64-bit)**
![Screenshot from 2019-07-29 12-51-52](https://user-images.githubusercontent.com/20394860/62043409-915c4c00-b200-11e9-9b12-8afcc63838b8.png)

**Versions**
* React Native for Web (version): 0.11.5
* React (version): 16.8.6
* Browser: Firefox 68 (64-bit), Chrome 75 (64-bit)

I looked the source code to figure out a solution and I found what seems to cause this issue. 

https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/compile.js#L153

Here you guys are polyfilling the css rule `scrollbar-width: none` with `${selector}{overflow:-moz-scrollbars-none;-ms-overflow-style:none;}` but actually Firefox 68 doesn't recognize `overflow:-moz-scrollbars-none;`. It seems like it's deprecated https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#Deprecated. However, when I'm adding `scrollbar-width: none` to the selector it does hide the scrollbar on Firefox 68.

![Screenshot from 2019-07-29 13 16 02](https://user-images.githubusercontent.com/20394860/62044390-219b9080-b203-11e9-8ee9-679e7cb0792b.png)
![Screenshot from 2019-07-29 13-16-43](https://user-images.githubusercontent.com/20394860/62044394-23fdea80-b203-11e9-9118-54ea100a0c9e.png)

I don't know if it's good solution but it fixs my issue. (Sorry about my English :fr:)

**Comment by necolas** [comment]
See https://github.com/necolas/react-native-web/pull/1395
