### ISSUE TITLE
numeric keyboards allow dot and "e" characters

### ISSUE THREAD

**Issue by sirpy** [necolas/react-native-web#1406]
**The problem**
when using keyboardtype=number-pad you can enter "." and "e" expected is only numbers
when using keyboardtype=numeric you can enter "e" expected only dot and numbers

**How to reproduce**
go to react-native-web  examples pages of TextInput and test the numeric keyboard type by typing "e"

**Expected behavior**
only numbers allowed in numeric-pad

**Comment by necolas** [comment]
`e` is allowed as a way to express numbers in scientific notation, meaning "10 to the power of…"
