### ISSUE TITLE
[FlatList] Endless re-rendering.

### ISSUE THREAD

**Issue by Ermolaev-Nikolay** [necolas/react-native-web#1409]
**The problem**
Tested many options. But always begins an endless call to the `loadMore ()`function. How to configure `FlatList`?

Simplified test case: 
```
  constructor(props) {
      super(props);
      this.state = {
        items: ["1", "2"]
      }  
    }
  loadMore = () => {
    this.setState((state) => {
      return { items: [ ...state.items, ...state.items] }
    });
  }
  
  render() {
      return(

          <FlatList
          onEndReachedThreshold={0.5}
          onEndReached={this.loadMore}
          data={this.state.items}
          renderItem={({item}) =>
            <Text>{item}</Text>}
          />

      );
  }
```

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.5
* React (version): 16.8.6
* Browser: Chromium 76.0.3809.87

**Comment by d4rky-pl** [comment]
Make sure that every parent of this component has `flex: 1` set and is constrained to at most the height of the window. Took me a longer while to figure that one out.

**Comment by Ermolaev-Nikolay** [comment]
@d4rky-pl, thanks it works!
