### ISSUE TITLE
borderBottomWidth only works when all 4 sides are explicitly defined

### ISSUE THREAD

**Issue by respectTheCode** [necolas/react-native-web#141]
When defining border widths the bottom width is ignored if the other 3 sides are not explicitly defined

```javascript
	works: {
		borderBottomColor: "#F00",
		borderTopWidth: 0,
		borderLeftWidth: 0,
		borderBottomWidth: 1,
		borderRightWidth: 0
	},
	doesNotWork1: {
		borderBottomColor: "#F00",
		borderBottomWidth: 1
	},
	doesNotWork2: {
		borderBottomColor: "#F00",
		borderWidth: 0,
		borderBottomWidth: 1
	},
	doesNotWork3: {
		borderBottomColor: "#F00",
		borderTopWidth: 0,
		borderLeftWidth: 0,
		borderBottomWidth: 1
	}
```

**Comment by MoOx** [comment]
I recently got the same issue (I was thinking I was doing something wrong as I don't use react-native **yet**).

**Comment by giuseppeg** [comment]
`border[top|right|bottom|left]-style` is `none` by default. Can that be the reason why you don't see any border?

**Comment by miketheanimal** [comment]
I hit this problem, or at least similar, where I wanted a border at the bottom only. The following worked for me:

      borderBottomWidth: 1,
      borderBottomStyle: 'solid',
      borderBottomColor: 'black',

If i remove the borderBottomStyle then it doesn't work, so I think giuseppeg is likely right.

**Comment by necolas** [comment]
I'm looking into this now
