### ISSUE TITLE
Error using async storage for react native web - unexpected token ;

### ISSUE THREAD

**Issue by bhaskar8088** [necolas/react-native-web#1410]
Hi,

I have a react native project which I am trying to port to web.

And I got below error:

Failed to compile.

./node_modules/@react-native-community/async-storage/lib/AsyncStorage.js
SyntaxError: /home/bhaskar/myproject/node_modules/@react-native-community/async-storage/lib/AsyncStorage.js: Unexpected token, expected ";" (40:5)

  38 | }
  39 | 
> 40 | type ReadOnlyArrayString = $ReadOnlyArray<string>;
     |      ^
  41 | 
  42 | type MultiGetCallbackFunction = (
  43 |   errors: ?$ReadOnlyArray<Error>,

Any idea how to fix this?

**Comment by necolas** [comment]
This is a different project
