### ISSUE TITLE
AsyncStorage is null 

### ISSUE THREAD

**Issue by bhaskar8088** [necolas/react-native-web#1412]
I installed asyncstorage using

    yarn add @react-native-community/async-storage

then linked it using:

    react-native link @react-native-community/async-storage

And I imported in of the files then getting below error:

```
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

To fix this issue try these steps:

  • Run `react-native link @react-native-community/async-storage` in the project root.

  • Rebuild and restart the app.

  • Run the packager with `--clearCache` flag.
```

Any idea how to fix this? Is this happening only when mixed with react native web or is it a general one? I didnt get this error when using with pure react native.

**Comment by necolas** [comment]
Please stop opening issues here that are about different repositories

**Comment by bhaskar8088** [comment]
@necolas Sorry.  But the question I am trying to ask is, do we have to use asyncstorage or local storage when using with  react native web. Because asyncstorage works well with react native, but having issues only with web. Since you must have already used async storage, thought of asking you. For now, using local storage for web and asyncstorage for mobile.

**Comment by dherault** [comment]
I think this issue should be reopened, I'm having the same issue

**Comment by mrKorg** [comment]
I have the same problem. Issue must be opened.

My setup

`  
"dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.1.1",
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.0.2",
    "axios": "^0.19.2",
    "babel-plugin-inline-import": "^3.0.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint-plugin-import": "^2.22.1",
    "formik": "^2.1.4",
    "immer": "^7.0.9",
    "jetifier": "^1.6.6",
    "lodash": "^4.17.20",
    "react": "16.13.1",
    "react-dom": "^16.13.1",
    "react-native": "0.63.2",
    "react-native-config": "^1.3.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-web": "^0.13.14",
    "react-navigation": "^4.4.1",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-observable": "^1.2.0",
    "redux-persist": "^6.0.0",
    "rxjs": "^6.6.3",
    "yup": "^0.28.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.14",
    "@types/react": "^16.9.49",
    "@types/react-native": "^0.63.22",
    "@types/react-test-renderer": "^16.9.3",
    "babel-jest": "^26.3.0",
    "eslint": "^7.10.0",
    "jest": "^26.4.2",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "16.13.1",
    "redux-logger": "^3.0.6",
    "typescript": "^4.0.3"
  },
`
