### ISSUE TITLE
How to make Jest test cases work for a React component using React Native library?

### ISSUE THREAD

**Issue by rahulrsingh09** [necolas/react-native-web#1416]
I have a widget library that is created using React Native 0.55.3 and i am using the library in the web using React Native Web transpiler.

Currently my setup is React + TS + React Native Widgets (using RNW transpiler)

The library works fine in the web , but when i run the jest test case it starts complaining

```
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
```

I tried adding the following setup in the config file but with no avail .

```
  "transformIgnorePatterns": [
  "node_modules/(?!react-native-my-lib)"
  ],
```
Still it throws the same error , even tried adding transform and then pairing it to a mock file.
The jest version i am using is 24.8.0.

How do we ingest this setup to run jest test.. and can we even test this..

I had raised this in multiple forums but i couldn't get any response , will be glad is some one here has encountered this or help me on this.

**Comment by rahulrsingh09** [comment]
Right now what i have done in order to mitigate this issue is I have mocked the RN components as the RN components will be tested in their own Library and we will test the layout in React end   mocking these components with string.

My solution [Please let me know if this is feasible]

create a mock file 

```
module.exports = {
  RN1COMP : '',
  RN2COMP : ''
}
```
using module name mapper in jest

```
  moduleNameMapper: {
    "react-native-widgets": "<rootDir>/mocks/react-native-widgets.js"
  },

```

The components comes in the DOM as blank . what do you think about this as a solution to the problem of Testing RN components in React ?

**Comment by edwinwong90** [comment]
I have the same issue like you, if you use Babel (I believe so), you need to read this https://jestjs.io/docs/en/getting-started#using-babel

**Comment by necolas** [comment]
Yes jest needs babel to transform any uncompiled dependencies
