### ISSUE TITLE
ScrollView shows(Horizontal/Vertical)ScrollIndicator=false doesn't work on Firefox +64.

### ISSUE THREAD

**Issue by yungkittty** [necolas/react-native-web#1417]
This issue https://github.com/necolas/react-native-web/issues/1405 haven't been fixed with 0.11.6.

This pull-request https://github.com/necolas/react-native-web/pull/1395 was supposed to fix it.

However on Firefox 68:

![Screenshot from 2019-08-10 14-01-49](https://user-images.githubusercontent.com/20394860/62821579-6d412900-bb77-11e9-8e52-e64901d03107.png)

![Screenshot from 2019-08-10 14 03 12](https://user-images.githubusercontent.com/20394860/62821594-9feb2180-bb77-11e9-8fb9-72bb71722515.png)

I think there's a clash between the selectors because they have the same name. The third one (which is suppose to hide the scrollbar on firefox +64) is ignored because the selector (the second line) is already defined.  

![Screenshot from 2019-08-10 14 06 38](https://user-images.githubusercontent.com/20394860/62821624-1d169680-bb78-11e9-8df2-eba16f4faccf.png)

EDIT:

When I remove the line which is suppose to clash with the selector for firefox +64 it works.

![Screenshot from 2019-08-10 14-13-17](https://user-images.githubusercontent.com/20394860/62821684-0b81be80-bb79-11e9-9304-227b89f4969b.png)

**Comment by necolas** [comment]
Fixed as above
