### ISSUE TITLE
Build as Web Library, onPress does not register as click

### ISSUE THREAD

**Issue by Kikketer** [necolas/react-native-web#1419]
**The problem**

I'm attempting to build a library that exports both Web and React-Native consumable components.  And I'd like to export them without any additional libraries needed by the consumers.  So I'm targeting Create-React-App and `react-native init` without having to bring in any specifics.

When I export a `<TouchableHighlight onPress=...` the resulting web version that's being consumed by Create-React-App (web) does not register a click event.  It renders properly and handles the focus + spacebar event, but any clicks on it do nothing.

**How to reproduce**

Not entirely helpful since codesandbox can't seem to add a dependency from a git repo.  Also the issue is more visible on a Create-React-App where React-Native-Web is not imported (my goal).

https://codesandbox.io/embed/issue-react-native-for-web-hcjns

The actual library is here: https://github.com/Kikketer/RNWSharedComponents

Simplified test case: 

Steps to reproduce:
1. Create a react app: `npx create-react-app test-app --typescript`
2. In that app do `yarn add git+https://github.com/Kikketer/RNWSharedComponents.git`
3. Modify the App.tsx file:

```
// Add
import { RNWButton } from '@kikketer/womponents'

// Then render it:
const App: React.FC = () => {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <RNWButton/>
...
```

_Bonus_

Notice that if you use a `react-native init` style project and `import { RNWButton } from '@kikketer/womponents/dist/mobile' (after doing the same yarn install) the library works properly.  It responds to the `onPress` properly which is expected.

**Expected behavior**

I expect the button that's produced to respond to a click event.  The library is incredibly simple right now where it'll console.log a clicked event when clicked.  If you focus the button and hit spacebar, it'll work properly.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): react-native-web@0.11.5
* React (version): react@16.9.0
* Browser: Chrome (probably others)

**Additional context**

Again my goal is to provide a library that does not require the consumers to import React-Native-Web.  Ideally the end result would be ES5 that Create-React-App could directly consume.

Also i found that if I bring React-Native-Web into the consumer project (CRA) and then create another element with that, the library version of the button would actually work.  So this seems to only affect the situation where I do not want to force consumers to import React-Native-Web.

**Comment by jrm2k6** [comment]
I ran into the same situation.
I have a component that I bundle with Webpack, aliasing react-native to react-native-web.
When importing that component in a separate package (lerna mono-repo), I have to import react-native-web (`import "react-native-web"`) in my index.js file to have the onPress handler working.

@Kikketer Did you find a solution to work around having to bring in react-native-web in the consumer project?

**Comment by Kikketer** [comment]
@jrm2k6 I have not found a solution, I've abandoned the attempt and moved on to other alternatives like ditching react-native altogether.

**Comment by mariaines** [comment]
Hi @jrm2k6, your solution works for me in development, but in a production build, it seems that the import is getting tree-shaken. Have you gotten this to work in production?

**Comment by elie222** [comment]
Any downsides to this approach?
Also looking to use it in a lerna project that is consumed separately be React and React Native packages.

**Comment by necolas** [comment]
Please try version `0.0.0-33f8505d6` (a canary release) and let me know if the problem is resolved. See  #1538

**Comment by SmartArray** [comment]
Is this still an issue?

In my production build, everything gets rendered perfectly. BUT, the UI does not respond to any clicks at all.
> Hi @jrm2k6, your solution works for me in development, but in a production build, it seems that the import is getting tree-shaken. Have you gotten this to work in production?
> 
> Update: Got it to work by switching to `require('react-native-web')`

This approach did not work in our app.

Is there any other solution for this? How could I help with debugging this issue?
