### ISSUE TITLE
Update NetInfo to conform to the signatures of @react-native-community/netinfo

### ISSUE THREAD

**Issue by RyanThomas73** [necolas/react-native-web#1420]
The `@react-native-community/netinfo` dependency has deprecated many of the api signatures and added new ones.

For my browser environment I currently use a webpack alias to map the netinfo dependency to the module within `react-native-web`. This currently causes runtime issues because the `react-native-web` NetInfo module does not contain the same signatures as the 3rd party module.

I've seen the communication in their repo at:  https://github.com/react-native-community/react-native-netinfo/pull/47

Since it is uncertain if or when the `@react-native-community/netinfo` module will support web environments, it would be useful if we could update `react-native-web` to have the same api signatures. 

I can currently work around this issue by having a platform check that uses different net info calls and event handler functions based on whether not the code is running in the browser environment. This is less than ideal, and will stop working with typescript if the `react-native-community/netinfo` module removes the deprecated api calls.

**Comment by necolas** [comment]
That repo is responsible for adding web support. I created an issue and you could help get them to prioritize it.

https://github.com/react-native-community/react-native-netinfo/issues/174
