### ISSUE TITLE
Generate all static pages of a React Native Web application

### ISSUE THREAD

**Issue by 5ervant** [necolas/react-native-web#1421]
I created a GitHub organization to deploy a React Native Web application as the organization site using Expo for Web: https://github.com/expo-gh-pages/expo-gh-pages.github.io

Check this deployed Expo web application on GitHub Pages hosting: **https://expo-gh-pages.github.io**

If you visit it, the navigation menus contain links to these:

- https://expo-gh-pages.github.io/Home
- https://expo-gh-pages.github.io/Links
- https://expo-gh-pages.github.io/Settings

If you click any of those links directly, it’ll show *“404 File not found”* because they’re not existing.

**Is it possible to generate all static pages of a React Native Web application and use `react-native-web` as a static site generator?**

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/docs/guides/server-side-rendering.md

https://github.com/necolas/react-native-web/blob/master/README.md#integrations

**Comment by 5ervant** [comment]
@necolas I'm having trouble figuring out how would `react-navigation` work with those integrations, they have a different process of page/screen creation.

Is there any straight guide how would we build static web pages of a React Native Web application, to be deployed on GitHub Pages hosting?
