### ISSUE TITLE
react-native camera possibility?

### ISSUE THREAD

**Issue by shreyaspadhye3011** [necolas/react-native-web#1423]
Hello,

Please pardon me if this is a silly question as the README states that CameraRoll is not available as there are "No equivalent web APIs." available. I was wondering if there is scope of integrating this in the future or if there is a hacky way to do it.

I understand that browser side uses `getUserMedia()`. I'm basically looking for an implementation that could give me native control to the device camera over a browser becasue I want "on tap" capture functionality over a camera opened in browser.

Please advise.

**Comment by necolas** [comment]
Expo probably has something. cc @EvanBacon
