### ISSUE TITLE
Images are not draggable by default

### ISSUE THREAD

**Issue by evcohen** [necolas/react-native-web#1425]
**The problem**
The `Image` component should match native behavior by setting draggable to `true` by default.

**How to reproduce**
Render an `<Image />` component without explicitly setting the draggable prop. Note in the browser how `draggable` is set to false. Also, note [the code](https://github.com/necolas/react-native-web/blob/37ca236d095d039b48899720ff39a630f4f0dff2/packages/react-native-web/src/exports/Image/index.js#L277)

**Expected behavior**
Draggable is true by default.

**Comment by necolas** [comment]
Thanks but the current default is as intended

**Comment by evcohen** [comment]
Yes but it's incorrect

**Comment by evcohen** [comment]
For any reason in particular? Its at odds with how browsers natively set the property and is a web-only prop.

**Comment by necolas** [comment]
This is the web part a cross-platform React framework, and images on all the other platforms do not currently hand-off to a native drag behavior when a pointer becomes actives and moves on their surface. If you need an image to rely on native drag behavior on the web, I've already made that available via the custom `draggable` prop.
