### ISSUE TITLE
Layout and style differences between web and mobile

### ISSUE THREAD

**Issue by Antonhansel** [necolas/react-native-web#1431]
Hello 👋

My question is a bit broad but I couldn't find any answer out there, even after reading https://github.com/necolas/react-native-web/issues/646 and https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md
I'm working with react-native-web and our mobile app is nearing completion.
For obvious reasons, while having the same features and user flow, our web and mobile apps won't have the exact same layout.

I have failed to find a concrete example of a pattern to apply to properly differentiate the layout and styles between web and mobile. Using the `Platform` API seems obvious, but I would love to see real life example.

Thank you for your time 🙏

**Comment by necolas** [comment]
You can use the `Dimensions` API and `onLayout` props to adjust layouts

**Comment by Sharcoux** [comment]
@Antonhansel maybe you can try `rn-css`. This might help you get a common css code for both web and mobile.
