### ISSUE TITLE
improve Getting Started documentation

### ISSUE THREAD

**Issue by littlehome-eugene** [necolas/react-native-web#1442]
**Is your feature request related to a problem? Please describe.**

> create-react-app includes built-in support for aliasing react-native-web to react-native

It sounds like if you do `create-react-app` you get `react-native-web` for free. but after doing `create-react-app` I'm perplexed how to continue

**Describe a solution you'd like**

Give a bit more what to do to use `react-native-web` .. Should do `yarn add react-native-web` ?

**Describe alternatives you've considered**

**Additional context**

**Comment by necolas** [comment]
The install command is literally right above that line. And "support for aliasing" means only aliasing. You still need to install the package.
