### ISSUE TITLE
[Proposal] Refactoring import and export in index

### ISSUE THREAD

**Issue by ecreeth** [necolas/react-native-web#1445]
**Is your feature request related to a problem? Please describe.**
This is a code refactoring for [index](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/index.js)

**Describe a solution you'd like**
I think we can clean this file a bit using [export default from](https://github.com/tc39/proposal-export-default-from#common-concerns)

**From this**
```
import createElement from './exports/createElement';
import findNodeHandle from './exports/findNodeHandle';
import processColor from './exports/processColor';
```
**To this**
```
export {default as createElement} from './exports/createElement';
export {default as findNodeHandle} from './exports/findNodeHandle';
export {default as render} from './exports/render';
export {default as unmountComponentAtNode} from './exports/unmountComponentAtNode';
```

**Additional context**
You can find the final result [here](https://gist.github.com/ecreeth/614f308e909f93a86b2758e7932ea85f#file-export-default-index-from-react-native-website-js)

If this is approved i can send a pull request immediately :smile:

**Comment by necolas** [comment]
Sounds good. I merged a few branches into master that made changes to this file, but you should be good to go now.

**Comment by necolas** [comment]
0b31a8b09659c002e4499c1b71cae471fe5d6b20
