### ISSUE TITLE
[Proposal] Migrate from createReactClass to ES6 classes

### ISSUE THREAD

**Issue by ecreeth** [necolas/react-native-web#1446]
**Is your feature request related to a problem? Please describe.**
I would like to know if there is any reason why **createReactClass** is still used

**Describe a solution you'd like**
I want to help migrate from **createReactClass** to ES6 classes

**Comment by necolas** [comment]
createReactClass is still used because parts of RN are still using mixins. it will go away once RN migrates away from it
