### ISSUE TITLE
TouchableOpacity with onPress causes an error to the whole page

### ISSUE THREAD

**Issue by gie3d** [necolas/react-native-web#1448]
**The problem**
Use TouchableOpacity with onPress causes an error to the whole page. I added 
```js
<TouchableOpacity onPress={()=> console.log('test')}>
  <Text>Test</Text>
</TouachableOpacity>
```
Once I press on anywhere on the page, it shows the following errors:
```
Uncaught TypeError: Cannot read property 'type' of null at Object.push../node_modules/react-native-web/dist/modules/ResponderEventPlugin/index.js.ResponderEventPlugin.extractEvents 
```

**How to reproduce**
https://codesandbox.io/s/cranky-fire-r34s2?fontsize=14

Simplified test case: 

Steps to reproduce:
1. Open sandbox from this link: https://codesandbox.io/s/cranky-fire-r34s2?fontsize=14
2. Open chrome dev tool
3. Press on the text "Touch me!" and you will see errors on console

**Expected behavior**

It should alert with text "test"

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.7
* React (version): 16.10.1
* React Dom (version): 16.10.1
* Browser: Test with Chrome (77.0.3865.90 (Official Build) (64-bit) Mac

I cannot reproduce this in React & React Dom 16.8.6

**Comment by gie3d** [comment]
This seems to work fine with React & React Dom 16.8.6

**Comment by necolas** [comment]
Duplicates https://github.com/necolas/react-native-web/issues/1443
