### ISSUE TITLE
ResponderEventPlugin.extractEvents nativeEvent is null on React 16.10.1

### ISSUE THREAD

**Issue by AndrewMorsillo** [necolas/react-native-web#1450]
**The problem**
RNWeb doesn't work with latest react due to `nativeEvent` being null in `ResponderEventPlugin.extractEvents`

**How to reproduce**

Simplified test case: https://codesandbox.io/embed/issue-react-native-for-web-xebmh

Steps to reproduce:
1. Run example. Observe crash.

**Expected behavior**
RNWeb works with latest react.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.x
* React (version): 16.10.1
* Browser: any

**Comment by necolas** [comment]
Duplicates #1443
