### ISSUE TITLE
ScrollView pagingEnabled: Content is stylable

### ISSUE THREAD

**Issue by mikeaustin** [necolas/react-native-web#1454]
When the ScrollView pagingEnabled prop is supplied, a View is wrapped around each child in the scrollbar content, but is not stylable. I can't set "flex: 1" for example to make it fill.

On 11/15/2018, @jaulz  changed React.cloneElement() to a nested View, preventing any flexbox styling from being passed. Later, it was updated by @krister to support pagingEnabled.

The check-in was "[fix] ScrollView dependency on 'style' forwarding for sticky headers".
Does anyone know why using cloneElement() didn't work? Did it clobber styles?

What would be a good solution to this problem? adding a ScrollView prop "innterContainerStyle" or similar?

Specifically, I'm using a horizontal ScrollView with paging to create a type of SwipableFlatList that support MacBook swiping from the touchpad.

**Comment by tamagokun** [comment]
ran into the same problem, using the `CellRendererComponent` prop, I was able to override the default `View` and add styles.

Docs: https://facebook.github.io/react-native/docs/virtualizedlist#cellrenderercomponent
