### ISSUE TITLE
Question: Difference between rendering via AppRegistry and ReactDOM

### ISSUE THREAD

**Issue by mohsinulhaq** [necolas/react-native-web#1455]
```jsx
AppRegistry.registerComponent('App', () => App);
AppRegistry.runApplication('App', { rootTag: document.getElementById('react-root') });
```
vs
```jsx
ReactDOM.render(<App />, document.getElementById('react-root'));
```
Now I know the first one is platform-agnostic code.
But is there any difference between the two rendering methods for **web**?

**Comment by necolas** [comment]
Yes there are differences https://github.com/necolas/react-native-web/tree/master/packages/react-native-web/src/exports/AppRegistry

**Comment by Mohmed-Refaay** [comment]
@necolas What would I lose from using ReactDom Rendering over App Registry?
