### ISSUE TITLE
Window.open and two tabs breaks app

### ISSUE THREAD

**Issue by vjsingh** [necolas/react-native-web#1459]
**The problem**
I included a window.open in my app. A few seconds after opening the new tab, both apps become buggy and then eventually freeze. I see that the tabs are grouped together in the chrome task manager, and CPU usage spikes to 100%.

**How to reproduce**

Include `window.open('/aRouteName')` in your app.
I notice that doing `window.open('http://www.url.com/aRouteName')` doesn't group the tabs in the chrome task manager, and doesn't result in the bug.

**Expected behavior**

No freezing / bugginess.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.4
* Expo: 35 (react-native)
* Browser: Chrome 77.0.3865.120

**Comment by necolas** [comment]
Closing as this doesn't have enough actionable info or a reduced test case. Doesn't seem related to RNW
