### ISSUE TITLE
[Documentation] Adding a reference to React Native for Web Starter

### ISSUE THREAD

**Issue by grabcode** [necolas/react-native-web#146]
Hi everyone,

As I was trying out React Native for Web, I figure it would be useful to create and maintain a Starter kit, as lean as possible.

React Native for Web Starter aims at:
- Providing the leanest code base to bootstrap a React Native for Web project.
- Following the standard React Native project structure close so someone becoming familiar with React Native may quickly find its way in a RN4Web project, and vice-versa.

Feel free to check it out [here](https://github.com/grabcode/react-native-web)

Cheers

**Comment by necolas** [comment]
See https://github.com/necolas/react-native-web/pull/147
