### ISSUE TITLE
How to use web variables when running in mobile

### ISSUE THREAD

**Issue by bhaskar8088** [necolas/react-native-web#1461]
Hello,

In my project, I had to use both web only variables like document and mobile only variables like async storage(atleast for me, asyncstorage doesnt work in web so I am using local storage in web. But thats a different issue).

I am writing code like below:

if (Platform.OS == "web") {
    document.getElementById("abc")......
} else {
 //something else.
}

Above code raising complaint that document variable not found in mobile.

How to solve this issue.

Current solution I am following is:
I am maintaining a single file where I am using methods like

mydocument: function() {

if(Platform.OS == "web") {
return document
//in mobile, I will comment above line because even though control wont go to above line in mobile, it is still raising error. So my only option is to comment out above line. But use mydocument rather than document every where in the project.
}
return {}
}

**Comment by necolas** [comment]
> Above code raising complaint that document variable not found in mobile.

That code should never be reached when the platform isn't web
