### ISSUE TITLE
SectionList does not scroll

### ISSUE THREAD

**Issue by izzyreal** [necolas/react-native-web#1462]
**The problem**
SectionList does not scroll.

**How to reproduce**

Steps to reproduce:
1. Open https://codesandbox.io/s/issue-react-native-for-web-pp69b
2. Try to scroll

Here's the react-native version that does scroll using the same example: https://snack.expo.io/HyVw0f9KH

**Environment (include versions). Did this work in previous versions?**

I haven't tried other versions.

* React Native for Web (version): 0.11.7
* React (version): 16.8.4
* Browser: Chrome

**Comment by manjunathgk22** [comment]
A workaround is to add <View> with height 100%
https://codesandbox.io/s/issue-react-native-for-web-9986v

**Comment by necolas** [comment]
You need to set `flex:1` on the `SafeAreaView`

**Comment by alessandrocapra** [comment]
> You need to set `flex:1` on the `SafeAreaView`

This was exactly the problem, thank you so much!
