### ISSUE TITLE
`autoComplete="off"` is not working in browsers.

### ISSUE THREAD

**Issue by alimyhamed** [necolas/react-native-web#1464]
**The problem**
`autoComplete="off"` is not working in browsers.

**How to reproduce**
Set `autoComplete` prop to "off".

Steps to reproduce:
1. Set `autoComplete` prop to "off";
2. Watch in browser to input `autocomplete` prop;

**Expected behavior**
Input `autocomplete` in browser same as `autoComplete` inside code. But insted if setted to "off", inside browser equals "noop".
Because of code inside 'TextField/index.js':
```
// Browser's treat autocomplete "off" as "on"
      // https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164
      autoComplete: autoComplete === 'off' ? 'off' : autoComplete,
```

* React Native for Web (version): 0.11.7
* React (version): 16.9.0
* Browser: Chrome

**Comment by paularmstrong** [comment]
@alimyhamed  Please read the Chrome Bug page from the code comments in your original message: https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164

It was closed as "wont-fix". Chrome knows that this doesn't work and they won't fix it. It's not a react-native-web issue.

**Comment by necolas** [comment]
b10711bddd1fdf6e01e82c0d49840dce9c2e04d2
