### ISSUE TITLE
Module not found: Error: Can't resolve 'EmitterSubscription' (Expo/Webpack?)

### ISSUE THREAD

**Issue by Ivanca** [necolas/react-native-web#1469]
**The problem**

If I try to import "expo" (the library create-react-app uses) from App.js the following error starts happening:

> ERROR in ./node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js
> Module not found: Error: Can't resolve 'EmitterSubscription' in 'C:\Users\User\test\mobile-frontend\node_modules\react-native\Libraries\vendor\emitter'

**How to reproduce**

Bug cannot be reproduced on codesandbox due a bug in that platform when trying to install expo@33.0.7: [ENOSPC](https://github.com/codesandbox/codesandbox-client/issues/1892)

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.59.10
* React (version): 16.9.0
* Expo: 33.0.7

One workaround is to modify EventEmitter.js, RCTDeviceEventEmitter.js, CTDeviceEventEmitter.js, EventEmitter.js to use relative imports, e.g. instead of 
```js
const EventSubscription = require('EventSubscription');
```
to
```js 
const EventSubscription = require('./EventSubscription');
```
but those files are internal of react-native so a proper solution is needed.

**Comment by necolas** [comment]
There is no `React Native for Web (version): 0.59.10`. Is this an expo issue?

**Comment by EvanBacon** [comment]
Could you please provide a repro some other way, maybe with https://snack.expo.io ? CRA isn't supported with Expo. When you start a project with the `expo-cli` the Webpack config that is used (`@expo/webpack-config`) adds the following Emitter aliases to polyfill a wider set of libraries that don't belong to Expo. 

```js
'react-native/Libraries/EventEmitter/RCTDeviceEventEmitter$':
    'react-native-web/dist/vendor/react-native/NativeEventEmitter/RCTDeviceEventEmitter',
'react-native/Libraries/vendor/emitter/EventEmitter$':
    'react-native-web/dist/vendor/react-native/emitter/EventEmitter',
'react-native/Libraries/vendor/emitter/EventSubscriptionVendor$':
    'react-native-web/dist/vendor/react-native/emitter/EventSubscriptionVendor',
'react-native/Libraries/EventEmitter/NativeEventEmitter$':
    'react-native-web/dist/vendor/react-native/NativeEventEmitter',
```

Note that I plan on deprecating these in time now that they can mostly be accessed through the `react-native` import.

**Comment by Ivanca** [comment]
I updated expo to the latest version and started using their way to start a web project (expo start --web) and that seems to have solved the issue.
