### ISSUE TITLE
FOUC with SSR

### ISSUE THREAD

**Issue by tamagokun** [necolas/react-native-web#1471]
**The problem**

When we render our page server-side, not all the styles are on the page. So we get a FOUC until the client renders and hydrates the css.

https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/createStyleResolver.js#L275

What would be great is if we could have more control over what we consider "critical" styles, or just turn this off.

**How to reproduce**

Simplified test case: 

Can't repro it in code sandbox because it needs to be SSR, but any custom styles should reproduce the issue.

e.g. https://codesandbox.io/s/issue-react-native-for-web-2s7bn

Steps to reproduce:
1. Create styles using StyleSheet.create
2. View source of SSR rendered page
3. The custom styles won't be in the style tag

**Expected behavior**

Have the option to determine if we want critical css or not when using `getStyleElement`

i.e.

```js
const { getStyleElement } = AppRegistry.getApplication('Main');
getStyleElement({ critical: false });
```

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.7
* React (version): 16.8.3
* Browser: Chrome
* Next.js (version): 9.1.1

**Comment by necolas** [comment]
I don't understand what the issue is. `getStyleElement` should always return the styles needed for the HTML produced by `getApplication`

**Comment by tamagokun** [comment]
perhaps a false alarm. I create an example to share and it's not happening. It might be entirely something on my end. Sorry for the trouble! 😓 i'll close this while I do some more testing and re-open if I can provide a sufficient test case.

Thanks!
