### ISSUE TITLE
onLayout relies on ResizeObserver which is not supported by your browser. Firefox and Safari

### ISSUE THREAD

**Issue by chayancbnits** [necolas/react-native-web#1473]
onLayout relies on ResizeObserver which is not supported by your browser. Please include a polyfill, e.g., https://github.com/que-etc/resize-observer-polyfill. Falling back to window.onresize.

How do I fix that in issue, I am using React Native Expo 35 SDK?

**Comment by necolas** [comment]
It is telling you to install the polyfill. You could open an issue against expo if you'd like them to include a fix by default
