### ISSUE TITLE
[Question & discuss] Disable atomic styles in development mode?

### ISSUE THREAD

**Issue by FrodoLuo** [necolas/react-native-web#1475]
### Background:

My team is working with React Native and React Web. We have a scene in which we want to develop only once by React Native, and then, by using react-natve-web, run the application on both native platform and web.

To ensure the consistency of app's behavior and vision styles, **we need debugging and tweaking on styles on web browser** after we finished the development for native platform.

### What's the problem:

And my team noticed that the react-native-web breaks style rule definition into atomic classes, as has been described in the [`style.md`](https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md).

From this document I learn that the atomic classes are for deduplicating the rules(Or any missing please figure it out). But atomic className do worsen the experience during debugging on Web Browser. 

### How I think:

I just changed the implement detail of react-native-web in our forked edition, avoiding the `atomic` method related parts. Then I got a class consists of should-be atomic styles. And styles are properly resolved. For example

I wrote in js like this:
```js
// my js code
const styles = StyleSheet.create({
    someClass: {
        marginLeft: 3,
        marginRight: 3,
        margin: 0
    }
})

<View style={styles.someClass>
...
</View>
```

And then I got css and html like this:

```html
<div class="css-view-[hash] someClass-[hash]">...</div>
```

```css
// I got the style class
.someClass-[hash] {
    margin-top: 0;
    margin-right: 3px;
    margin-bottom: 0;
    margin-left: 3px;
}
```
So I'm wondering whether **there is a reason that react-native-web must use atomic styles?** And **is there any possibility of disabling atomic styles during development mode**?

Best regards, you and your team has built a really great lib! :)

**Comment by necolas** [comment]
This has been asked before and isn't going to happen as what you're proposing isn't equivalent in terms of how styles are resolved.
