### ISSUE TITLE
Android app crash with error 'com.facebook.jni.CppException : Can't find variable: setTimeout' android 64 bit with React native 0.59.10

### ISSUE THREAD

**Issue by sunildate05** [necolas/react-native-web#1476]
**App crash with setTimeout error for react native 0.59.10 version**

**How to reproduce**

Simplified test case: 

I have upgraded React native 0.55 version to 0.59.10 using this helper 
[https://react-native-community.github.io/upgrade-helper/?from=0.55.3&to=0.59.10]()

Error in details -

 com.facebook.jni.CppException: Can't find variable: setTimeout
    
    index.android.bundle:206:7357
    h@index.android.bundle:2:1670
    index.android.bundle:205:53
    h@index.android.bundle:2:1670
    index.android.bundle:204:92
    h@index.android.bundle:2:1670
    index.android.bundle:13:2046
    h@index.android.bundle:2:1670
    index.android.bundle:11:46
    h@index.android.bundle:2:1670
    d@index.android.bundle:2:868
    global code@index.android.bundle:304:4
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version):0.10.x
* React (version): 16.8.3
* React native: 0.59.10

Can you please help us?

**Comment by sunildate05** [comment]
@necolas - I have used react-native-web 0.10.x version but after upgraded to RN- 0.59.10, App is crashing. Can you please reopen or May I know reason for closing this issue?.

Thanks.

**Comment by necolas** [comment]
Android bundle has nothing to do with web
