### ISSUE TITLE
React Storybook to demonstrate components

### ISSUE THREAD

**Issue by mnmtanish** [necolas/react-native-web#148]
Hi,
We can use [react-storybook](https://github.com/kadirahq/react-storybook/) to demonstrate some use cases for each component. I can work on this issue if you're interested.

**Comment by davidpelayo** [comment]
@mnmtanish I can help you with that if you need help 👍

**Comment by grabcode** [comment]
@mnmtanish @davidpelayo I'm happy to share with you my attempt to solving this react-native/web gap with my React Native for Web Starter

Simply install and `npm run storybook`
