### ISSUE TITLE
lists are not respecting their container

### ISSUE THREAD

**Issue by adamsythe** [necolas/react-native-web#1480]
**The problem**

Lists go out of their container over the the content below and above them

**How to reproduce**

Simplified test case: https://web-build.adam44.now.sh/?fbclid=IwAR0c25qPfg5iPZ7efxy5ehCjglWs3XZaTxyQGN0d6NCjh_BHfKviSRDEdRI

Steps to reproduce:
1. Create a View with flex one with three view children
2. first view and third view should have a fixed height, middle view should be flex 1
3. put a flatlist or scrollview inside the middle view

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: TBC

**Comment by necolas** [comment]
Please provide a proper repro case on codesandbox

**Comment by adamsythe** [comment]
@necolas thanks i built it in codesandbox now and it worked as one would expect.  I have the exact same code in an expo app where it doesnt work, would it be interesting for you to see the repo of the expo or is this a problem i should take to the expo team?

Here is the working codesandbox example
https://dh5sy.csb.app/

**Comment by necolas** [comment]
Yeah it looks like a bug in your app / expo where `body` is styled with `min-height:100%` when `height:100%` is what is needed to limit the growth of the body height. Will close this for now
