### ISSUE TITLE
Parse selectionColor on TextInput

### ISSUE THREAD

**Issue by robertLichtnow** [necolas/react-native-web#1490]
**Is your feature request related to a problem? Please describe.**

Yes, I have an issue with changing the color of a `TextInput` cursor.

**Describe a solution you'd like**

The feature is the parsing of the `TextInput` property `selectionColor` to `caret-color` in the css.

**Describe alternatives you've considered**

Didn't consider any alternatives.

**Additional context**

No additional context.

**Comment by necolas** [comment]
`selectionColor` is not the same thing as the `caretColor` style, which you can set on `TextInput` for web
