### ISSUE TITLE
Switch does not match React Native implementation

### ISSUE THREAD

**Issue by Arlen22** [necolas/react-native-web#1492]
In React Native the thumb is one color, and the track changes color when switched, and this is controlled by two properties. However, in React Native Web, there are 4 properties, at least according to https://github.com/necolas/react-native-web/issues/832. However, nothing is listed in the Readme about Switch being any different from React Native. Even though I like this idea, React Native Web should rather match React Native in order to avoid edge cases.

**Comment by Arlen22** [comment]
Update, after playing around with the colors a little, I decided that the React Native system of keeping the same thumb color and changing the track color between a neutral color and a tertiary color looked about the nicest.

**Comment by necolas** [comment]
aa8593ba9704d42f26c87303ac5a584856cbadaa
