### ISSUE TITLE
rn-web SectionList' stickySectionHeadersEnabled not work with version 0.8.9

### ISSUE THREAD

**Issue by jevonsofcode** [necolas/react-native-web#1494]
**The problem**
rn-web SectionList' stickySectionHeadersEnabled not work

**How to reproduce**

[codesandbox](https://codesandbox.io/embed/issue-react-native-for-web-sectionlist-sticky-header-uepdk?fontsize=14&hidenavigation=1&theme=dark)

- I tried [the method](https://github.com/necolas/react-native-web/pull/1122/files) 

```
    var style = this.props.style;
    var itemSeparator = ItemSeparatorComponent && _react.default.createElement(ItemSeparatorComponent, this.state.separatorProps);
    console.log("inversionStyle is :", inversionStyle) // inversionStyle is : null
    console.log("horizontal is :", horizontal) // horizontal is : null
    var cellStyle = inversionStyle ? 
    horizontal ? [styles.rowReverse, inversionStyle, style] : [styles.columnReverse, inversionStyle,style] 
    :
     horizontal ? [styles.row, inversionStyle,style] : [inversionStyle,style];

    if (!CellRendererComponent) {
      return _react.default.createElement(_View.default, {
        style: cellStyle,
        onLayout: onLayout
      }, element, itemSeparator);
    }
```

But it still doesn't work and those consoles is "null"

So, what this "style" does

And what should I do , please. T^T

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.8.9  
* React (version): 16.2  
* RN (version): 0.52  
* Browser: chrome  

Should I add something style in code

**Comment by necolas** [comment]
There is no version 7

**Comment by jevonsofcode** [comment]
> There is no version 7

sorry ! rnweb version 0.8.9

**Comment by necolas** [comment]
Try the latest version
