### ISSUE TITLE
createAnimatedComponent on styled-component works in react-native but not react-native-web

### ISSUE THREAD

**Issue by kennethlynne** [necolas/react-native-web#1495]
**The problem**
Error: 
`createAnimatedComponent` does not support stateless functional components; use a class component instead.

However this does not match react-natives API where this works just fine. 

**How to reproduce**
https://codesandbox.io/embed/issue-react-native-for-web-6o8rn

Simplified test case: 

Steps to reproduce:
1.Run above demo

**Expected behavior**

It should attach properly so one can animate styled-components like on mobile.

**Comment by necolas** [comment]
This is fixed in master

**Comment by kennethlynne** [comment]
That's great @necolas. It is not fixed in the latest release (11.7), and installing from git#master breaks things in my set-up. Any e.t.a. on when a new release will come out?

**Comment by kennethlynne** [comment]
Is there a specific commit or hint I can look into to patch the package temporarily until a new release is out?
