### ISSUE TITLE
how to integrate react-native-web in already existing react native project? Older issue is closed and not helping much

### ISSUE THREAD

**Issue by josprachi** [necolas/react-native-web#1496]
**Trouble in integrating react native web in already existing react native project**
Hello, I have written a piece of project in react native which is working fine for me on Android as well as ios. Now I want to integrate react native web in the project. I do not want to start over by creating whole new project. I looked for help. An issue with same name was present in this repo but the links provided in that issue but the links provided in that issue give page not found error and the issue is now closed even for commenting. Please help me to make my project runnable on web as well. Thanks !  

**Expected behavior**
I should be able to run on web browser

**Environment (include versions).**
This is my first time on react native. I could work really nice with mobile versions but not getting much help for browser

**this is what my dependencies look like**
 "react": "16.9.0",
    "react-art": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-native": "0.61.2",
    "react-native-calendar-picker": "^6.0.1",
    "react-native-elements": "^1.2.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-paper": "^2.16.0",
    "react-native-phone-input": "^0.2.4",
    "react-native-simple-time-picker": "^0.2.0",
    "react-native-unimodules": "^0.7.0-rc.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.3",
    "react-router-dom": "^5.1.2",
    "react-router-native": "^5.1.2",
    "react-scripts": "^3.2.0"

**Comment by necolas** [comment]
There is a link in the readme to the documentation for this, or you could use expo

**Comment by wh1t3cAt1k** [comment]
@necolas would you please care to share a link here as well? I see a link to the documentation website, but I also have trouble finding the migration / upgrade guide for existing RN projects.

**Comment by wh1t3cAt1k** [comment]
For those who also encounter this issue, the guide (somewhat counter-intuitively in my opinion) resides here:

https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page

I would suggest to include this question as an FAQ in the readme, or in the docs website in the "Getting Started" section.

**Comment by gireeshjoshi2** [comment]
This helped: https://mmazzarolo.com/blog/2020-10-24-adding-react-native-web/

**Comment by arrygoo** [comment]
Here's a blogpost explaining the steps: 
https://arry.medium.com/how-to-add-react-native-web-to-an-existing-react-native-project-eb98c952c12f

**Comment by MohammadAzimi** [comment]
This one is also a good one
https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej

**Comment by adeperio** [comment]
> https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page

This has been updated to here https://necolas.github.io/react-native-web/docs/multi-platform/
