### ISSUE TITLE
React 15.1.0 : "Cannot read property '_debugID' of undefined"

### ISSUE THREAD

**Issue by agrcrobles** [necolas/react-native-web#150]
I have a TouchableOpacity that used to work well, but when migrated to v15 got exception above.

**Comment by amilajack** [comment]
Possible PR for tests which test against this?

**Comment by agrcrobles** [comment]
https://github.com/necolas/react-native-web/blob/master/src/apis/UIManager/index.js#L37

**Comment by agrcrobles** [comment]
necolas already fixed it in commit 
https://github.com/necolas/react-native-web/commit/a378d3cce2fa8f52c13d0b72207f351fd798c043#diff-71604b0feac1a36a92211d23d137bf27
I will wait for next release then.

**Comment by amilajack** [comment]
I you want it now, you can swap the npm dependency:

```json
dependencies: {
  react-native-web: 'github:necolas/react-native-web'
}
```

**Comment by necolas** [comment]
> I will wait for next release then.

Yep :)
