### ISSUE TITLE
ScrollView onContentSizeChange running without size change

### ISSUE THREAD

**Issue by ugurrdemirel** [necolas/react-native-web#1502]
**The problem**
If I add onContentSizeChange prop to my scrollView, it is running every millisecond without size change

**Here is my code**

```
<ScrollView onContentSizeChange={(width, height) => {
        this.setState({scrollHeight: height});
        console.log(width)
}} 
style={{height:this.state.height, width:this.state.width}}>
                

                {/* Another Components */}
                

</ScrollView>
```

**How to reproduce**
Fix listener to work only on content size change

**Environment**

* React Native for Web (version): 0.11.7
* React (version): 16.12.0
* Browser: Google Chrome v78.0.3904.108 (Mac OS)

**Comment by affandhia** [comment]
I face the problem as well but it is happening in Safari 12.1.1. The prop is not triggered once the content's size is changing. Weirdly enough, the prop is working after you resize the browser.

The prop is working as expected on chrome 79.0.3945.88 and firefox 72.0.1.

![weirdprops2](https://user-images.githubusercontent.com/17004848/72148499-91798e00-33d3-11ea-9d4f-e07d92ab26e3.gif)

related sandbox: https://codesandbox.io/s/sticky-scroll-wun6s

**Comment by affandhia** [comment]
> I face the problem as well but it is happening in Safari 12.1.1. The prop is not triggered once the content's size is changing. Weirdly enough, the prop is working after you resize the browser.
> 
> The prop is working as expected on chrome 79.0.3945.88 and firefox 72.0.1.
> 
> ![weirdprops2](https://user-images.githubusercontent.com/17004848/72148499-91798e00-33d3-11ea-9d4f-e07d92ab26e3.gif)
> 
> related sandbox: https://codesandbox.io/s/sticky-scroll-wun6s

A temporary solution to me by calling `window.dispatchEvent(new Event(‘resize’))` in safari at the end of the action which triggers the content size changing.

**Comment by gorhom** [comment]
to capture the content height on initial rendering, i use this workaround 

```
const isInitialContentHeightCaptured = useRef(false);

const handleOnLayout = useCallback(() => {
    if (!isInitialContentHeightCaptured.current) {
        window.requestAnimationFrame(() => {
            const contentHeight = event.nativeEvent.target.clientHeight;
            console.log({contentHeight})
        });
        isInitialContentHeightCaptured.current = true;
      }
}, []);

<ScrollView onLayout={handleOnLayout} />
```
