### ISSUE TITLE
AsyncStorage module not found. Can't resolve react-native-web/dist/exports/AsyncStorage

### ISSUE THREAD

**Issue by Sharathnasa** [necolas/react-native-web#1515]
Hi Team,

I'm getting the below mentioned error when i try run application in the web mode.

/node_modules/expo/build/Notifications/Notifications.js
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' in '/Users/i322865/node_modules/expo/build/Notifications'

I'm using the latest expo(0.36, same error i faced when i was using 0.35 version as well) and react native web 0.12.0-rc.1. Please help to solve this issue and let me know if you require any further details

Regards,
Sharath

**Comment by Naturalclar** [comment]
@Sharathnasa 
AsyncStorage will be removed in v0.12 of react-native-web
Seems like it will be supported in v2 of react-native-community/async-storage, which can be found [here](https://github.com/react-native-community/async-storage/tree/master)

**Comment by Sharathnasa** [comment]
@Naturalclar Thank yo so much for the reply. So how do i go about fixing my current issue? Could you please shed some light

**Comment by necolas** [comment]
Use 0.11 until the community packages add web support. They've known this was coming for 9 months https://github.com/react-native-community/async-storage/issues/52

**Comment by aguilared** [comment]
"react-native-web": "~0.13.7",
AsyncStorage not available in RNW 0.13.7 expo/expo#6654
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage

**Comment by EvanBacon** [comment]
`AsyncStorage` is still deprecated. In Expo SDK 39 we use `react-native-web@0.13` so you'll need to migrate to the react-native-community module. ymmv with web support in community packages.

**Comment by karan1611** [comment]
Firstly remove the node modules from your project, as per documentation add try to import import  AsyncStorage  from 'react-native';....
then again try npm install 
and your project will run

**Comment by DaveLomber** [comment]
I use 

-  "react-native-web": "^0.14.10",
- "@react-native-community/async-storage": "^1.6.3",

and still getting `Attempted import error: 'AsyncStorage' is not exported from 'react-native'.`

**Comment by aneena-thomas** [comment]
Any update regarding this error? I'm on "react-native-web": "0.17.1", and still got the same error.

"export 'AsyncStorage' was not found in 'react-native-web/dist/index'


any help

**Comment by QuibDev** [comment]
For anyone still facing this, I fixed this by changing the import of AsyncStorage 

**from:** import AsyncStorage from "react-native";
**to:** import AsyncStorage from "@react-native-async-storage/async-storage";
