### ISSUE TITLE
Cannot find module 'babel-preset-react-native'

### ISSUE THREAD

**Issue by arshidkv12** [necolas/react-native-web#1519]
``ERROR in ./index.web.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-react-native' from '/Users/arshid/Desktop/test/MyNewAApp'
- If you want to resolve "react-native", use "module:react-native"``

**Comment by necolas** [comment]
Looks like a misconfiguration or failure to install the module in your project

**Comment by GIAVINH2010** [comment]
> ``ERROR in ./index.web.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> Error: Cannot find module 'babel-preset-react-native' from '/Users/arshid/Desktop/test/MyNewAApp'
> 
> * If you want to resolve "react-native", use "module:react-native"``

I meet the same error when setting react-native-web for current react native

**Comment by Preethyp** [comment]
@GIAVINH2010  I'm facing the same issue. Have you found any solution?

**Comment by GIAVINH2010** [comment]
> @GIAVINH2010 I'm facing the same issue. Have you found any solution?

Not yet. I'm still looking for it.

**Comment by arshidkv12** [comment]
Same issue :(

**Comment by Queeniie** [comment]
Same issue, has any solution been found yet? D:

**Comment by alyatwa** [comment]
this solution might work!
[https://github.com/necolas/react-native-web/issues/1257#issuecomment-653957398](https://github.com/necolas/react-native-web/issues/1257#issuecomment-653957398)

**Comment by glennposadas** [comment]
Any updates? @GIAVINH2010  would you like to share your findings? I have yet to try @alyatwa 's suggestion.
