### ISSUE TITLE
onLayout won't trigger when sibling or relative nodes change

### ISSUE THREAD

**Issue by yuanfux** [necolas/react-native-web#1520]
description: the x, y values from event.nativeEvent.layout should change accordingly as relative nodes change their layouts. The behavior is confirmed in React Native.

reproduce link: 
https://codesandbox.io/s/react-native-l0u9u?fontsize=14

When click "test" button, the height of red block is changed, but onLayout on green block is not triggered.

**Comment by necolas** [comment]
Duplicated by #1525
