### ISSUE TITLE
Support for article tags (SEO)

### ISSUE THREAD

**Issue by jfrolich** [necolas/react-native-web#1521]
**Is your feature request related to a problem? Please describe.**
For SEO it's better to use semantic tags.

**Describe a solution you'd like**
accessibilityRole to accept "article"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

There might be other tags to tackle (we already have header etc.).

**Comment by MoOx** [comment]
It seems it's already supported https://github.com/necolas/react-native-web/search?q=article&unscoped_q=article

**Comment by necolas** [comment]
Yes it is

**Comment by jfrolich** [comment]
Sorry! Great it's already supported.
