### ISSUE TITLE
Compile Failed with issue Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by toanhosss** [necolas/react-native-web#1522]
**The problem**
Cannot compile react native project for web by 
"Support for the experimental syntax 'classProperties' isn't currently enabled"

Steps to reproduce:
1. Installation react-native-web
2. Installation react-navigation
3. Installation react-native-drawer
4. Implement UI with react-navigation-stack and react-navigation-drawer
5. NPM start react native web
screen shot
[https://prnt.sc/qq78vf](url)

**Expected behavior**
compile successfully and open the web

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): "0.11.x"
* React (version): 16.8.4
* Browser: Chrome for Mac version 79.0.3945.130

**Comment by necolas** [comment]
See instructions for compiling RN modules, or use expo https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page
