### ISSUE TITLE
How to add Firebase to react-native-web project ?

### ISSUE THREAD

**Issue by rajeshlousigam** [necolas/react-native-web#1526]
I am trying to use firebase api to use in react-native-web? How to do that?

**Comment by necolas** [comment]
I don't know, probably not different to a normal react web app, but this issue tracker isn't for support questions

**Comment by qadirhusainee** [comment]
> I am trying to use firebase api to use in react-native-web? How to do that?

Have you got any solution for using firebase with react-native-web?

**Comment by rajeshlousigam** [comment]
Use it like the same way firebase in use in create-react-app

**Comment by ishaan-puniani** [comment]
Since the screen and components are shared across the Web, Android and iOS how can we configure it to use different libs. I tried to encapsulate analytics class for example and it ends up with a complicated structure.

**Comment by MahmoudShaeer** [comment]
+1

**Comment by hungvu193** [comment]
Hi @ishaan-puniani
Can you please explain it more detail, may be with some example code? Thanks in advance ✋

**Comment by marksyzm** [comment]
I think he means that you use the module `firebase/*` for web instead of `@react-native-firebase/analytics` and flip between the two in order to go from native to web environments. It's a workaround that might be worth raising an issue with `@react-native-firebase` instead to see if they can cover adding the web environment (if they haven't already).

**Comment by hungvu193** [comment]
I sovled this problem with by creating 2 files:
- `firebaseAnalytics.js` for mobile use react-native-firebase
- `firebaseAnalytics.web.js` for web use firebase/analytics

**Comment by marksyzm** [comment]
@hungvu193  you okay to show the source of those?

**Comment by DivyatejaChe** [comment]
> I sovled this problem with by creating 2 files:
> 
> * `firebaseAnalytics.js` for mobile use react-native-firebase
> * `firebaseAnalytics.web.js` for web use firebase/analytics

Why is this discouraged? I face the same issue - has anyone been able to figure out how to support Firebase parallelly on Web & Mobile?

**Comment by hungvu193** [comment]
not sure why people disliked my comment but I actually resolved my issued with that solution.
Simple created 2 files:
- firebaseAnalytics.js for mobile use react-native-firebase
- firebaseAnalytics.web.js for web use firebase/analytics

Then import and use them:

```
import firebase from "./firebaseAnalytics "
```

**Comment by DivyatejaChe** [comment]
> 

Can you suggest how did you manage loading dependencies in your webpack - exclude react-native-firebase & load firebase/analytics?

**Comment by DivyatejaChe** [comment]
> not sure why people disliked my comment but I actually resolved my issued with that solution. Simple created 2 files:
> 
> * firebaseAnalytics.js for mobile use react-native-firebase
> * firebaseAnalytics.web.js for web use firebase/analytics
> 
> Then import and use them:
> 
> ```
> import firebase from "./firebaseAnalytics "
> ```

Can you suggest how did you manage loading dependencies in your webpack - exclude react-native-firebase & load firebase/analytics?

**Comment by hungvu193** [comment]
@DivyatejaChe let me search, I didn't maintain this project anymore

**Comment by hungvu193** [comment]
here it is,  hope it can help:
firebaseAnalytics.js:
```javascript
import analytics from '@react-native-firebase/analytics';


async function trackScreen(screenName) {

    await analytics().logScreenView({
      screen_class: screenName,
      screen_name: screenName,
    });
}

async function trackProperty(unitid, userid, property) {

  await analytics().setUserProperties({
    unitid,
    userid,
    property,
  });
}

const  analyticsWrapper = {
  trackScreen,
  trackProperty,
 };

export default analyticsWrapper;

```

firebaseAnalytics.web.js:
```javascript
import firebase from 'firebase/app';

async function trackScreen(screenName) {
    firebase.analytics().logEvent(
      screenName,
      {screen_name: screenName},
    );
}

async function trackProperty(unitid, userid, property) {
  firebase.analytics().setUserProperties({
    unitid,
    userid,
    property,
  });
}

const analyticsWrapper = {
    trackScreen,
    trackProperty,
};

export default analyticsWrapper;


```

**Comment by DivyatejaChe** [comment]
Hey @hungvu193 , thanks for sharing - I was wondering how you had `path.resolve('./node_modules/@react-native-firebase'),` in your **_babelInclude_** . Does building it not throw you any errors - like 'Module not found'?

To be more specific of my ask, how do I exclude selective RN packages from being loaded/ used on React-Native-Web?
