### ISSUE TITLE
Compatibility with createRoot for latest concurrent mode

### ISSUE THREAD

**Issue by SamyPesse** [necolas/react-native-web#1529]
Using `react-native-web` relies on `AppRegistry.runApplication` which doesn't use `ReactDOM.createRoot`. It means that using suspense with `react-native-web` is only possible using the previous Suspense API (`<React.unstable_ConcurrentMode>`), since then the React had released [great new concurrent APIs such as `useTransition`, or `useDeferredValue`](https://reactjs.org/docs/concurrent-mode-reference.html).

Supporting concurrent mode with `react-native-web` will require:
- Replace uses of deprecated React API (legacy context https://github.com/necolas/react-native-web/issues/1506, findDOMNode) 
- Use `ReactDOM.createRoot` in [`renderApplication`](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/AppRegistry/renderApplication.js)

I think a potential solution in the short term could be to use `ReactDOM.createRoot` when an option is passed to `AppRegistry.runApplication` so that it supports both latest and older react versions.

I'd be happy to open a PR for such changes if you agree with such implementation :)

**Comment by necolas** [comment]
I'll update the implementation once a stable release of concurrent mode is available

**Comment by hosseinmd** [comment]
This is possible if we change renderApplication like this
```js
function renderApplication<Props: Object>(
  RootComponent: ComponentType<Props>,
  WrapperComponent?: ?ComponentType<*>,
  callback?: () => void,
  options: {
    initialProps: Props,
    rootTag: any,
    mode: 'Concurrent' | 'Blocking' | 'Legacy',
  },
) {
  const {initialProps, rootTag, mode} = options;

  invariant(rootTag, 'Expect to have a valid rootTag, instead got ', rootTag);

  const App = (
    <AppContainer rootTag={rootTag} WrapperComponent={WrapperComponent}>
      <RootComponent {...initialProps} />
    </AppContainer>
  );

  if (mode === 'Concurrent') {
    ReactDOM.createRoot(rootTag).render(App, callback);
  } else if (mode === 'Blocking') {
    ReactDOM.createBlockingRoot(rootTag).render(App, callback);
  } else {
    ReactDOM.render(App, rootTag, callback);
  }
}
```

**Comment by hosseinmd** [comment]
I want to test react experimental on react-native-web this code help me.
could you release that in an experimental like react to test that by anyone who is curious.

**Comment by hosseinmd** [comment]
I have a temporary release for the next branch with concurrent mode support for testing, until the official version is released.
Available on NPM
```
yarn add react-native-web-experimental
```

**Comment by cdeszaq** [comment]
I see this was removed from the 0.16 milestone, but not added to any subsequent one. Any idea when this might be target for getting into a release? We'd love to be able to leverage these concurrent capabilities everywhere from our RN codebase.

**Comment by tpisto** [comment]
Hi! Any updates on this?
