### ISSUE TITLE
Packager is Failing on my Terminal

### ISSUE THREAD

**Issue by jesskrich** [necolas/react-native-web#153]
Ran the initial npm install command as specified in the Read Me and got this error:

npm ERR! Tell the author that this fails on your system:
npm ERR!     del ./dist && mkdir dist && babel src -d dist --ignore **/__tests__,src/modules/specHelpers
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native-web
npm ERR! There is likely additional logging output above.

**Comment by amilajack** [comment]
Try this:
```
rm -rf node_modules && npm cache clean && npm i

**Comment by jesskrich** [comment]
Thx! Turns out it was a human error on my part.

**Comment by amilajack** [comment]
What was the error?

**Comment by jesskrich** [comment]
I wrote 'react-native-for-web' instead of 'react-native-web'
