### ISSUE TITLE
custom attributes of Button are not rendered

### ISSUE THREAD

**Issue by chiru007** [necolas/react-native-web#1533]
customer attributes of Button are not rendered in the DOM, but its fine for View or Image. I added a data-id attribute to the Button, but I can't see in the inspect window.

Thanks

**Comment by necolas** [comment]
That component doesn't support passing data attributes

**Comment by chiru007** [comment]
are there any attributes can I use to pass an id?

**Comment by paularmstrong** [comment]
You can use `testID` on `Button`: https://facebook.github.io/react-native/docs/button#testid. On web, a `data-testid` attribute will be present

**Comment by chiru007** [comment]
great, thanks.. is this testID attribute available for all components
