### ISSUE TITLE
How to import two separate react-native packages to one web page?

### ISSUE THREAD

**Issue by BohdanHulchack** [necolas/react-native-web#1535]
**Is your feature request related to a problem? Please describe.**
I have and issue when importing two react-native modules to web page.
Looks like second package is not know anything about first and fails to load with error:

> Invariant Violation: EventPluginRegistry: Cannot inject two different event plugins using the same name, `ResponderEventPlugin`.

I couldn't find anything related to importing multiple RNW packages to one page in documentation or issues.
Mb it's not how this package suppose to be used.

But I want to ask if anybody have idea how this can be done.
How to tell second rect-native-web package not init if first is running.

Thank you.

**Comment by necolas** [comment]
You can't have more than one copy. This is true for React too.

**Comment by BohdanHulchack** [comment]
@necolas Thank you for answer.
