### ISSUE TITLE
Upgrade from 0.11.7 to 0.12.0 fail to import AsyncStorage

### ISSUE THREAD

**Issue by kopax** [necolas/react-native-web#1536]
**The problem**

I have tried to upgrade from `react-native-web@0.11.7` to `react-native-web@0.12.0`

This is the error I have when starting my application after the upgrade:

```
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' in '/home/dka/test-native/node_modules/expo/build/Notifications'
```

**How to reproduce**

Steps to reproduce:
1. Use `AsyncStorage` and try to upgrade from 0.11.7 to 0.12.0

**Expected behavior**

It should work

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version):  https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
* React (version): 16.12.0
* Browser: Google Chrome

**Comment by necolas** [comment]
It was removed intentionally

https://github.com/necolas/react-native-web/releases/tag/0.12.0

It's now a community module

https://github.com/react-native-community/async-storage/issues/52

**Comment by jackdewhurst** [comment]
So what's the fix for this? install `react-native-community/async-storage` directly?
