### ISSUE TITLE
Native image-picking for web?

### ISSUE THREAD

**Issue by benpetsch** [necolas/react-native-web#1540]
I just stumpled over this project and find my self confused about the power of react-native-web.

Will react-native-web add native image picking experience to my webapp (assuming the user uses the browser on a mobile device) or will it fallback to the usual web file picking?

Is there a better place to ask those questions?

**Comment by necolas** [comment]
RNW doesn't provide any APIs for image picking. You can use whatever is built into the browser, or the Expo APIs that wrap those browser APIs
