### ISSUE TITLE
define propTypes for compatibility

### ISSUE THREAD

**Issue by mo22** [necolas/react-native-web#1543]
Hi,

a lot of react-native libraries use ReactNative.Text.propTypes.style or ReactNative.ViewPropTypes to define their own propTypes.

I know that propTypes are deprecated, but right now this causes a lot of "cannot read property style of undefined" errors with third party libraries.

My workaround is to monkey patch the prop types:

```
import * as ReactNative from 'react-native-web';
{
  const PropTypes = require('prop-types');
  ReactNative.Text.propTypes = { style: PropTypes.any };
  ReactNative.View.propTypes = { style: PropTypes.any };
  ReactNative.Image.propTypes = { style: PropTypes.any };
  ReactNative.ViewPropTypes = { style: PropTypes.any };
}
```

I wonder if it makes sense to have the propTypes still defined by react-native-web for better user experience or just wait until propTypes are removed from the third party libraries.

Cheers
Mo

**Comment by LinusU** [comment]
Would you mind sharing which libraries this is? I think that the correct course is to send PRs to them ☺️

**Comment by mo22** [comment]
I recall that react-native-swipeout was affected, and others also.

It's gonna be quite hard to push the removal of propTypes to those libraries as long as the latest react-native still provides them.

**Comment by dested** [comment]
I am currently dealing with it with https://github.com/archriss/react-native-snap-carousel

**Comment by necolas** [comment]
React Native is going to stop exporting prop types so libraries should stop depending on them. I don't plan to add them back to RNfW

**Comment by lovebes** [comment]
Here's a fix for the time being until libraries are updated to not use propTypes:

1. in the root directory, add this as "fix-for-web.sh":
```
#!/bin/bash
# Monkey patch propTypes: https://github.com/necolas/react-native-web/issues/1543
MONKEY_PATCH_PROPTYPES=('Text')
echo "Monkey patching propTypes for $import ..."
if grep -q "const PropTypes = require('prop-types');" ./node_modules/react-native-web/dist/index.js; then
    echo "$import fixed already!"
else
    echo -e "\nconst PropTypes = require('prop-types');">> ./node_modules/react-native-web/dist/index.js
    for import in "${MONKEY_PATCH_PROPTYPES[@]}"
    do
        echo -e "\n$import.propTypes = { style: PropTypes.any };">> ./node_modules/react-native-web/dist/index.js
    done
fi
```
NOTE: depending on your OS - you might need to run: "chmod +x ./fix-for-web.sh"

2. In package.json:
`
  "scripts": {
    "start": "expo start",
    ...
    "postinstall": "bash ./fix-for-web.sh",
    "uninstall": "bash ./fix-for-web.sh"
  },
`

**Comment by phpepe** [comment]
Hey @mo22, I like your workaround. On which file are you adding this ?

> ```
import * as ReactNative from 'react-native-web';
{
  const PropTypes = require('prop-types');
  ReactNative.Text.propTypes = { style: PropTypes.any };
  ReactNative.View.propTypes = { style: PropTypes.any };
  ReactNative.Image.propTypes = { style: PropTypes.any };
  ReactNative.ViewPropTypes = { style: PropTypes.any };
}
```
