### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by jfrolich** [necolas/react-native-web#1544]
It would be great for `Linking` to provide an option to open in a new window/tab. (Or is there already a way to do this?)

**Comment by steida** [comment]
It's impossible to open a new tab without a link with the target.

**Comment by jfrolich** [comment]
Sure? I think it's possible with `window.open`?

https://stackoverflow.com/questions/14132122/open-url-in-new-window-with-javascript

**Comment by steida** [comment]
Window, not tab. Remember it's restricted because of popups.

**Comment by jfrolich** [comment]
> Window, not tab. Remember it's restricted because of popups.

You are right. I formulated it wrong, it should be open in new tab.

**Comment by steida** [comment]
It's impossible. The user has to click to a link. Browsers require that.

**Comment by jfrolich** [comment]
> It's impossible. The user has to click to a link. Browsers require that.

`window.open` second argument is target, if I use that with `"_blank"` it opens in a new tab (at least in Chrome)

**Comment by Sharcoux** [comment]
Could [this](https://github.com/necolas/react-native-web/pull/1743) solve this issue?

**Comment by JijoBose** [comment]
Can Linking open an External Browser when running **react-native-web** inside a **Mobile App** in its **WebView**?
For eg: A **react-native-web** PWA running inside a **React Native** App's **webview**

Code
```
  const openLink = async url => {
    const supported = await Linking.canOpenURL(url)
    if (supported) {
      await Linking.openURL(url)
    }
  }

```
The above code however redirects to a page within the WebView and not from an external Browser (eg, open with Chrome, etc)
Any workarounds for this issue?

**Comment by avanwinkle** [comment]
Resurrecting this thread to ask why the implementation hard-coded `_blank` as the target, instead of the other proposal https://github.com/necolas/react-native-web/pull/1743 which allowed a parameter?

I ask because there are scenarios where the desired behavior is *not* to open in a new tab, but that is currently impossible due to the hard-coded `_blank`.
