### ISSUE TITLE
Incorrect versions in package.json from npm

### ISSUE THREAD

**Issue by johanjordaan** [necolas/react-native-web#155]
Hi. I run : npm install react-native-web

I get the following warnings:

npm WARN react-native-web@0.0.25 requires a peer of react@^0.14.3 but none was installed.
npm WARN react-native-web@0.0.25 requires a peer of react-dom@^0.14.3 but none was installed.
npm WARN react-textarea-autosize@3.3.1 requires a peer of react@^0.14.0 but none was installed.

I then look at the package.json in node_modules/react-native-web and find the following lines:

 "react": "^0.14.3",
    "react-addons-test-utils": "^0.14.3",
    "react-dom": "^0.14.3",

I thought these should be 15 for tag 0.25?

Regards
Johan

**Comment by MoOx** [comment]
react-native-web@0.0.25 does not match react-native@0.25 and for now there is not release of react-native-web that supports react@^15.0.0. Just use react@0.14 until a release is made public.

**Comment by johanjordaan** [comment]
I see. I didn't go down the rabbit hole far enough :)

**Comment by MoOx** [comment]
You can probably close this issue then (I don't have any right here, just helping a little ^^).
