### ISSUE TITLE
How does Twitter or Uber manage the address bar in the web?

### ISSUE THREAD

**Issue by zeitamin** [necolas/react-native-web#1553]
I have few ideas to make it work by using browser history and location objects and using [path-to-regexp](https://github.com/pillarjs/path-to-regexp) to check for the `location.pathname` with the predefined paths and load the corresponding screen, but, I'm not sure how to implement this.  I wonder how does Twitter or Uber apps manage the address bar in the browser? is this the correct path I'm going to?

**Comment by koulmomo** [comment]
use a library like [react-router](https://reacttraining.com/react-router/) for routing and [react-helmet-async](https://github.com/staylor/react-helmet-async) to modify the document head using react components

**Comment by necolas** [comment]
You can use any existing approach to managing the address bar, this is just a UI component library
