### ISSUE TITLE
Implement InteractionManager createHandle/clearHandle to allow detecting ongoing interactions

### ISSUE THREAD

**Issue by Jarred-Sumner** [necolas/react-native-web#1554]
**Is your feature request related to a problem? Please describe.**

I have some code that needs to not trigger when an interaction handle is running (a click event listener).

The current implementation of InteractionManager stubs out `createInteractionHandle` and `clearInteractionHandle` so that they do nothing

This works great for `InteractionManager.runAfterInteractions`, but the `addEventListener` does effectively nothing right now.

**Describe a solution you'd like**

It'd be great if this was implemented. I'm currently polyfilling it. It doesn't handle multiple concurrent interactions and requires adding a listener to the window object, but that's probably fine for most cases.

polyfill:
```tsx
const original = InteractionManager.runAfterInteractions;

InteractionManager.createInteractionHandle = () => {
  window.dispatchEvent(new Event(InteractionManager.Events.interactionStart));
  return 1;
};

InteractionManager.clearInteractionHandle = () => {
  window.dispatchEvent(
    new Event(InteractionManager.Events.interactionComplete),
  );
  return 1;
};

InteractionManager.runAfterInteractions = task => {
  return original(task).done(orig => {
    window.dispatchEvent(
      new Event(InteractionManager.Events.interactionComplete),
    );
    return orig;
  });
};
```

**Describe alternatives you've considered**

**Additional context**

**Comment by necolas** [comment]
You can submit a PR for this

**Comment by necolas** [comment]
An implementation of InteractionManager was added in 0.19 by @ntdiary https://github.com/necolas/react-native-web/commit/47d77ac256cf1324e684362465a2b0001d2db574
