### ISSUE TITLE
Filtering props.style dedicated for other platforms in Text

### ISSUE THREAD

**Issue by Barteque** [necolas/react-native-web#1556]
**The problem**
`Warning: Failed prop type: Invalid props.style key `includeFontPadding` supplied to `Text`.`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.7
* React Native (version): 0.60.24
* React (version): 16.8.16
* Browser: Chromium

My question is: should i filter the props dedicated for native platforms or maybe it would be better if React-Native-Web filtered it?

**Comment by necolas** [comment]
Update to 0.12. That version doesn't use React PropTypes
