### ISSUE TITLE
Error with react-native-vector-icons

### ISSUE THREAD

**Issue by moonjava2005** [necolas/react-native-web#1558]
Attempted import error: 'ToolbarAndroid' is not exported from './react-native'.
But, when downgrade to 0.11.7, it works

* React Native for Web (version): 0.12.2
* React (version): 16.12.0
* Browser: Chrome

**Comment by pruthvip** [comment]
I think, since ToolbarAndroid is deprecated(removed) from react-native hence the same has been removed from the rnw new verision. It is mentioned in the release notes.

**Comment by bikashsahucbnits** [comment]
It seems to be an issue that React-native 0.61 removed the reference to ToolbarAndroid but gesture-handler is still referencing to it.

Seems to be fixed in version 1.5.5 version

**Comment by necolas** [comment]
Yeah that export is gone

**Comment by aviemet** [comment]
Sorry to bump this after it's closed, but I don't see a solution in this thread. I have a project with this exact issue. react-native: 0.61.5, react-native-vector-icons: 6.6.0, react-native-web: 0.12.2.

I had to downgrade to 0.11.7 to ditch the error, but would prefer to be on the latest version. react-native-gesture-handler doesn't seem to exist in my yarn.lock file, even as a secondary dependency. I installed the latest version to see if it would make a difference, but no dice. Can you please tell me what I'm missing?

Thanks

**Comment by littlehome-eugene** [comment]
same as @aviemet , what's the solution other than downgrading to 0.11.7?

**Comment by bikashsahucbnits** [comment]
To allow more customization, I do not use ToolbarAndroid, however, this library might be what you are looking for instead of ToolbarAndroid.
Here is an example that describes about the use of the library.
[https://reactnativeexample.com/an-android-like-action-bar-for-react-native/](url)

**Comment by adiffmike** [comment]
Just in case anyone lands here - this is not a react-native-web issue. Its an issue with react-native-vector-icons.

There's a workaround here:
https://github.com/oblador/react-native-vector-icons/issues/1104#issuecomment-599393489 

Unfortunately for some reason react-native-vector-icons has fixed this issue in the codebase but not yet published the fix to npm so you can also try installing from github instead.
