### ISSUE TITLE
Image: add support for srcsets

### ISSUE THREAD

**Issue by dustinsavery** [necolas/react-native-web#156]
With React Native, they can automatically pull @1x, @2x, and @3x images depending on the device, automatically. With web, that support comes in the form of having a default src and following that up with srcset, which contains additional sizes or pixel densities for the browser to use. That would be very helpful to have!

**Comment by necolas** [comment]
We might want a webpack plugin to deal with image imports, including support for this feature.

**Comment by necolas** [comment]
Closing in favour of #237
