### ISSUE TITLE
Storybook integration does not resolve .web extension files

### ISSUE THREAD

**Issue by BrendonSled** [necolas/react-native-web#1561]
**The problem**
Storybook integration does not resolve .web extension files.
When you have two files `Animating.js` and `Animating.web.js` the file resolved is `Animating.js`

**How to reproduce**

1. Using the storybook react-native-web docs package
https://github.com/necolas/react-native-web/tree/master/packages/docs/

2. Duplicate a file and add the .web extension.
3. Add some visible changes into that file
4. Start

**Expected behavior**
You should see the changes in the .web file but instead the regular file is resolved.

* React Native for Web (version): 0.12.2

**Comment by necolas** [comment]
The docs package is private to this repo. I don't need to use .web files

**Comment by patrickjm** [comment]
@BrendonSled I got around this by using [@expo/webpack-config](https://www.npmjs.com/package/@expo/webpack-config) and merging their unimodules webpack configuration with my own storybook configuration.

**storybook web's main.js**:

```
const { resolve } = require('path');
const { withUnimodules } = require('@expo/webpack-config/addons');

module.exports = {
    ...
    webpackFinal: async (config, { configType }) => {
        config = withUnimodules(config, {
            projectRoot: resolve(__dirname, '../../')
        });

        // ... other stuff, I used this area to add Typescript support

        // Add react-native-web support
        config.resolve.alias['$react-native$'] = 'react-native-web';
        return config;
    }
};
```
