### ISSUE TITLE
onPress of TouchableHighlight does not work.

### ISSUE THREAD

**Issue by YvetteLau** [necolas/react-native-web#1562]
Hi, My code like this:

```js
class Demos extends Component {
    render() {
        return (
            <TouchableHighlight
                onPress={() => alert('aaaa')}
            >
                <Text>点击</Text>
            </TouchableHighlight>
        );
    }
}
```

It doesn't work as excepted, I view react-native-web code, and I found  `react-native-web/src/exports/TouchableHighlight/index.js`,  code below is commented out. 

```js
onClick={this.touchableHandlePress}
```

`this.props.onPress` is called in `touchableHandlePress`. 

If I uncomment this code, it will work normally.

My version is:

- react-native-web: 0.12.2
- react-native: 0.59.9

**Comment by kievu** [comment]
I also get this issue. After testing a bit, it seems like the onPress function only trigger if you are clicking with no movement. When applying gesture on mouseClick, the callback won't trigger. A temporary solution i found is to use the `onPressIn()` function instead.

**Comment by YvetteLau** [comment]
> I also get this issue. After testing a bit, it seems like the onPress function only trigger if you are clicking with no movement. When applying gesture on mouseClick, the callback won't trigger. A temporary solution i found is to use the `onPressIn()` function instead.

maye you can try update version of react/react-dom
I have update  react-dom version to 16.8.3 , It does work now.

**Comment by P3dro-4rtur** [comment]
> I also get this issue. After testing a bit, it seems like the onPress function only trigger if you are clicking with no movement. When applying gesture on mouseClick, the callback won't trigger. A temporary solution i found is to use the `onPressIn()` function instead.

Nice!
