### ISSUE TITLE
why  View Component default set "flexShrink: 0" css style ?

### ISSUE THREAD

**Issue by relign** [necolas/react-native-web#1565]
**The problem**
View Component default set "flexShrink: 0" caused some style problems，In the standard, flexShrink default value is 1.
![image](https://user-images.githubusercontent.com/13749042/76953545-d7118480-6949-11ea-90a2-c59c9e696ea7.png)

**How to reproduce**
[codepen link](https://codepen.io/CodingLion/pen/dyoKZrx)

Text does not break lines

**Expected behavior**
![image](https://user-images.githubusercontent.com/13749042/76953702-1d66e380-694a-11ea-9ee8-63c14633fe67.png)

default, Text should break lines.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): latest v0.12.2
* React (version): 16.8.6
* Browser: Chrome

**Additional context**
I followed you on twitter and watched what you were up to. I feel you're nervous about coronavirus.
I hope you are healthy. Make sure you wear a mask when you go out and wash your hands frequently.

**Comment by necolas** [comment]
> why View Component default set "flexShrink: 0" css style ?

Because that's the default in React Native.

As you can see in this example, text wraps when using the RN exports: https://codesandbox.io/s/hopeful-darkness-cz41l

**Comment by relign** [comment]
"Because that's the default in React Native"
@necolas Where can you see this default setting？ ಥ_ಥ
"As you can see in this example, text wraps when using the RN exports:"
In the example, "flexShrink: 0" css style  is setting by react-native-web.
