### ISSUE TITLE
Is it possible to use a CSS library like TailwindCSS?

### ISSUE THREAD

**Issue by vasco3** [necolas/react-native-web#1567]
**Is your feature request related to a problem? Please describe.**

I would like to leverage the utility css from tailwind.

**Describe a solution you'd like**

be able to add CSS class names to the components

**Describe alternatives you've considered**

maybe a library that transforms tailwind into JS-CSS. Not sure if that exists

**Additional context**

https://tailwindcss.com/

**Comment by necolas** [comment]
No, it's not possible
