### ISSUE TITLE
Some leaflet elements cannot be displayed

### ISSUE THREAD

**Issue by Fabian815** [necolas/react-native-web#1569]
**The problem**

First of all, my English is not very good. I got all of this through Google Translate. Please understand. The following is my question.I want to use react-native-web to display a map page developed with leaflet. As a result, the map can be displayed, but the lines and areas drawn on the map cannot be displayed. In addition, I opened my map page with the browser of the mobile phone simulator, and the page was able to display the line following the normal.
This is my first time asking questions, please understand if the way of question is not correct.

**Comment by necolas** [comment]
Sorry I don't know what a leaflet element is. RNW is a component library for ReactDOM so it shouldn't cause any special problems when integrating 3rd party code
