### ISSUE TITLE
Errors with animated.js

### ISSUE THREAD

**Issue by agrcrobles** [necolas/react-native-web#157]
After changes in https://github.com/necolas/react-native-web/commit/f33312a4dd2679ddcc290a20dfdb6d20d23c660e I am getting the following errors when trying to run:
```
ERROR in ./~/animated/lib/index.js
Module build failed: Error: Couldn't find preset "react-native" relative to directory.
```
```
ERROR in ./~/animated/lib/Easing.js
Module build failed: Error: Couldn't find preset "react-native" relative to directory
```

**Comment by agrcrobles** [comment]
Fixed, babel issue, there is need to add `react-native` preset array in `.babelrc`

https://www.npmjs.com/package/babel-preset-react-native

**Comment by necolas** [comment]
How can this be reproduced? Animated is published as a built package so there shouldn't be any need to install its devDependencies

**Comment by agrcrobles** [comment]
that makes sense, I will try to re create it by an small example

**Comment by agrcrobles** [comment]
FYI, The issue is not fixed for me.

I am getting that `TouchableOpacity` does not have a `type`.

**Comment by necolas** [comment]
You haven't explained any steps to reproduce the issue, or even what you're trying to do

**Comment by agrcrobles** [comment]
I will have a test project to verify this issue soon, in the meantime I notice this:
https://github.com/animatedjs/animated/blob/master/.babelrc

I am not sure if it is something related to how are things building.

**Comment by necolas** [comment]
OK, we can reopen when there is a test case and details.

**Comment by agrcrobles** [comment]
Created a webpack babel starter to check it and figure that my issue is with flow

https://github.com/agrcrobles/react-native-web-webpack-starter
