### ISSUE TITLE
onPress of Touchable called twice

### ISSUE THREAD

**Issue by YvetteLau** [necolas/react-native-web#1570]
My code like this:

```js
<TouchableHighlight onPress={()=>{
    alert('You pressed me')
 }}>
     <View style={styles.touchStyle}>
         <Text >
            press me
        </Text>
     </View>
</TouchableHighlight>
```
when I click the alertDialog, onPress will trigger one more.

It's sees that when I click the alert dialog, touchableHandleResponderGrant of Touchable will trigger.

>My Version is :
- react-native:0.59.9
- react:16.10.2
- react-dom:16.10.2

**Comment by necolas** [comment]
Looks ok here: https://codesandbox.io/s/elastic-swirles-x8jn5

Make sure you update React too.
