### ISSUE TITLE
Add support for flow

### ISSUE THREAD

**Issue by agrcrobles** [necolas/react-native-web#158]
Will be very usefull to have an interface like the one below to make flowtypes work with react-native-web

https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-interface.js

**Comment by necolas** [comment]
I'll accept a PR for that.

**Comment by agrcrobles** [comment]
I was thinking that we could implement something like:

```
declare module 'react-native-web' {
  declare var exports: {
    Text: (callback: any) => any,
    View: (callback: any) => any,
    Image: (callback: any) => any,
    Platform: any,
  }
};
```

but I think it goes better in a starter kit.
