### ISSUE TITLE
__DEV__ support

### ISSUE THREAD

**Issue by littlehome-eugene** [necolas/react-native-web#1580]
**The problem**
If you want to share code between RN and RN-web, `__DEV__` should also be provided in the both platform.

However I can't add __DEV__ using `const __DEV__ = process.env.NODE_ENV !== 'production'; new webpack.DefinePlugin({__DEV__})`

I can set `window.__DEV__` fine, but RN code uses `__DEV__`

I've also tried adding `module:metro-react-native-babel-preset` 

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.12.2
* React (version): 16.12.0
* Browser: chrome

**Comment by necolas** [comment]
That's something a bundler like webpack has to do for you

**Comment by KingAmo** [comment]
could anyone anyone help me with how we could get `__DEV__` in `react-native-web` with `webpack` ?
i really do not familiar with `webpack`

**Comment by KingAmo** [comment]
see https://stackoverflow.com/questions/61115645/react-native-web-dev-not-defined/62297869#62297869

**Comment by LuoTuxiu** [comment]
```
  plugins: [
    new webpack.ProvidePlugin({
      __DEV__: process.env.NODE_ENV === 'production' || true,
    }),
  ],
```

when I add __DEV__ to webpack plugins, it goes other error: 

```
ERROR in specifier.charCodeAt is not a function

ERROR in specifier.charCodeAt is not a function

ERROR in specifier.charCodeAt is not a function
```

anybody could help?
