### ISSUE TITLE
Touchable onPress not working for react-dom 16.13.1

### ISSUE THREAD

**Issue by gregoryBernard** [necolas/react-native-web#1582]
**The problem**
onPress event is not fired

**How to reproduce**

```javascript
export const Link = () => {
  return (
    <TouchableOpacity onPress={() => console.log('Bonjour')}>
      <View testID="PinPad Digit">
        <Text>Text</Text>
      </View>
    </TouchableOpacity>
  );
};
```

Browser: Chrome
react-native-web: 0.12.2
babel-plugin-react-native-web: 0.12.2
react-dom: 16.13.1

It does work with react-dom: 16.8.0 and 16.9.0

**Comment by necolas** [comment]
Provide a link to a test case as asked for in the issue template and I'll reopen this.
