### ISSUE TITLE
<Text> with numberOfLines prop clips text when lineHeight and fontSize are the same

### ISSUE THREAD

**Issue by javascripter** [necolas/react-native-web#1585]
**The problem**

When the `<Text>` component has `numbeOfLines` prop and the `lineHeight` and `fontSize` are set to the same number, some characters of the last line gets clipped and part of the characters are hidden.

<img width="257" alt="Screen Shot 2020-04-10 at 23 54 17" src="https://user-images.githubusercontent.com/13040/79000048-dfdf2a00-7b86-11ea-9847-7f5092cfc585.png">

This seems to be caused by the `overflow: 'hidden'` style applied to `<Text>` with `numberOfLines` props.

Even when the lineHeight and fontSize are the same, the actual height of text can be bigger than the set fontSize or lineHeight. Therefore `<Text>` cannot have `overflow: hidden` set.
https://stackoverflow.com/questions/33185205/text-input-on-chrome-line-height-seems-to-have-a-minimum

https://github.com/necolas/react-native-web/blob/5287044f403d881a13e17f140c5575ce0661587f/packages/react-native-web/src/exports/Text/index.js#L115

**How to reproduce**

Simplified test case: https://codesandbox.io/s/unruffled-germain-1ebsg?file=/src/App.js

Steps to reproduce:
1. Place <Text> with any numberOfLines (1, 2 or more)
2. Set the fontSize and lineHeight the same
3. the bottom of some characters like `g` gets clipped

**Expected behavior**

All characters are visible

**Environment (include versions). Did this work in previous versions?**

React Native for Web (version): 0.12.2
React (version): 16.12.0
Browser:
Google Chrome: Version 80.0.3987.163 (Official Build) (64-bit)
Safari: Version 13.0.5 (15608.5.11)

**Comment by necolas** [comment]
Yes this is just how things work on the web. You need to hide overflow to truncate the text
