### ISSUE TITLE
Keyboard.dismiss prevents textinput on web

### ISSUE THREAD

**Issue by Tobbe** [necolas/react-native-web#1589]
**The problem**

Wrapping a TextInput in `<TouchableWithoutFeedback onPress={Keyboard.dismiss}>` prevents text input in web browsers. It works in the Android emulator.

**How to reproduce**

Simplified test case: https://snack.expo.io/zZnI!80Pv
Even more minimal: https://snack.expo.io/wGzixvj1e

Steps to reproduce:
1. Choose the web view
2. Click on the TextInput field
3. Try to type any text using the computer keyboard

**Expected behavior**

I expect the text I enter to show up in the TextInput field.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): Whatever Snack uses
* React (version): Whatever Snack uses
* Browser: Chrome

**Comment by Tobbe** [comment]
Just realized this is a side effect of this issue: https://github.com/necolas/react-native-web/issues/1583
Here's a snack to verify my assumption: https://snack.expo.io/6Dn1gdys0

**Comment by necolas** [comment]
This is also fixed in `react-native-web@canary`

**Comment by necolas** [comment]
We'll keep this open until the patches land in master

**Comment by shokoofa-ghods** [comment]
I solved the issue just with putting children components of TouchableWithoutFeedback, inside <> {children} </> .

**Comment by danieloi** [comment]
Still seeing the issue in version 0.15.0

**Comment by danieloi** [comment]
It doesn't work with reanimated 1. 
https://docs.swmansion.com/react-native-reanimated/docs/web-support/

**Comment by jmarcosmruk** [comment]
I adeed a check before `Keyboard.dismiss()`

`function dismissKeyboard() {
        if (Platform.OS != "web"){
        Keyboard.dismiss();
    }
    }`

`<TouchableWithoutFeedback style={{ alignContent: "center" }} onPress={() => dismissKeyboard()}>`

it worked for me

**Comment by xpsdeset** [comment]
> I adeed a check before `Keyboard.dismiss()`
> 
> `function dismissKeyboard() { if (Platform.OS != "web"){ Keyboard.dismiss(); } }`
> 
> `<TouchableWithoutFeedback style={{ alignContent: "center" }} onPress={() => dismissKeyboard()}>`
> 
> it worked for me

You sir are a lifesaver.

**Comment by taeyongkim95** [comment]
> I adeed a check before `Keyboard.dismiss()`
> 
> `function dismissKeyboard() { if (Platform.OS != "web"){ Keyboard.dismiss(); } }`
> 
> `<TouchableWithoutFeedback style={{ alignContent: "center" }} onPress={() => dismissKeyboard()}>`
> 
> it worked for me

Thank you for this!

**Comment by shreyashc** [comment]
> I adeed a check before `Keyboard.dismiss()`
> 
> `function dismissKeyboard() { if (Platform.OS != "web"){ Keyboard.dismiss(); } }`
> 
> `<TouchableWithoutFeedback style={{ alignContent: "center" }} onPress={() => dismissKeyboard()}>`
> 
> it worked for me

Thank You!!
