### ISSUE TITLE
Make text selectable on web

### ISSUE THREAD

**Issue by RWOverdijk** [necolas/react-native-web#1594]
**Is your feature request related to a problem? Please describe.**

My test group informed me that not being able to select text on web is very frustrating. Even cmd+a (ctrl+a) doesn't select anything. I get it for apps, but on web users want to be able to select text.

**Describe a solution you'd like**

Text to be selectable in the browser.

**Describe alternatives you've considered**

- The `selectable` prop. Which doesn't seem to work. Even if it did, I'd have to apply this everywhere which is not ideal imo.
- Disabling gestures (scrollview, list, react navigation etc) didn't change this behaviour.

**Comment by necolas** [comment]
The issue template asks for steps to reproduce a problem and a codesandbox example. I'll reopen if you can do that. But you can see from this repos docs and the Twitter PWA that text is selectable by default.

**Comment by RWOverdijk** [comment]
@necolas I clicked on feature request. Maybe you were a bit hasty there

**Comment by necolas** [comment]
This feature is the already the default

**Comment by RWOverdijk** [comment]
Sure man, but your reply accused me of removing the issue template. I get that you're busy but come on, that's not cool 😄

Anyway, if you say it's the default then I'll have to find out why it's not behaving that way. I opened this thinking it was just a missing feature. Thanks for the info :)

**Comment by RWOverdijk** [comment]
FYI confirmed. Looks like it's react navigation somehow. Sorry for creating an issue.
