### ISSUE TITLE
I have this warning  `Using the "className" prop on <View> is deprecated. ` after hooking a css in RNW

### ISSUE THREAD

**Issue by kopax** [necolas/react-native-web#1596]
**Is your feature request related to a problem? Please describe.**

I would like to hook some css for hovering effect

**Describe a solution you'd like**

Restore `className`

**Describe alternatives you've considered**

Maybe allow `name` or anything that can be rendered in dom and targeted

**Additional context**

Currently, using `className` cause the following warning:

    Using the "className" prop on <View> is deprecated

Following https://github.com/necolas/react-native-web/issues/1146

**Comment by necolas** [comment]
It's not supported
