### ISSUE TITLE
Documentation to use react-native libraries

### ISSUE THREAD

**Issue by albertcito** [necolas/react-native-web#1598]
**Is your feature request related to a problem? Please describe.**
- step 1: `npx create-react-app my-app`
- step 2: `npm i react-native-web`
- step 3: `npm i react-native-animatable`
- step 4: Add `import * as Animatable from 'react-native-animatable'` in `App.js`
- step 5: `npm start` result: 

> Support for the experimental syntax 'classProperties' isn't currently enabled...
> Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

I tried to fix it, but it doesn't works because (someone posted) the issue is that the library must to be precompiled. Also I found that someone was able to make it works in the react-native-animatable's [ticket 92](https://github.com/oblador/react-native-animatable/issues/92#issuecomment-297638991) and says: _"That covers all react-native-* libraries, so you don't need to configure each library separately."_

**Describe a solution you'd like**

- I would like if is possible to have some guide to know how configure the webpack in my create-react-app project to make all the react-native libraries works with react-native-web.

**Comment by necolas** [comment]
This is already documented https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page

I also strongly recommend not using create-react-app and using Expo instead
