### ISSUE TITLE
SEO for react-native and react-native-web application, can it work?

### ISSUE THREAD

**Issue by kopax** [necolas/react-native-web#1599]
I am looking at the generated HTML in my `react-native-web` web application and the volume of HTML is hudge.

The whole application is build with `<div />` and there are some `role` attribute such as  `role="navigation"` in many places.

- This is what makes me ask, can SEO today solve the problem to have good indexation in Google for `react-native` web application?
- If not, how can I improve the components of a native application in order to have a normal SEO potential? 

I was not able to find any resource about that matter, resources that talk about it would be much appreciated.

**Describe a solution you'd like**

A part in the `README.md` or in the documnation

**Describe alternatives you've considered**

Wrapping the react-native components in `<nav/>`, `<header />` and increasing the `Platform.OS === 'web'` and `.web.js` custom code

**Comment by steida** [comment]
Nav, Header, etc. are SEO irrelevant abstractions RNW is trying to remove. Btw, do HTML5 community already know when to use Article and when Section? I am so glad I don't have to think about it anymore.

**Comment by necolas** [comment]
RNW already produces <nav> etc elements. Look at the output again. Those elements don't have an impact on SEO anyway

**Comment by kopax** [comment]
@necolas thanks for the feedback, but I am still trying to understand, is it equivalent as a react website for SEO?
