### ISSUE TITLE
Switch: invisible in Windows High-Contrast mode

### ISSUE THREAD

**Issue by kennethkufluk** [necolas/react-native-web#1606]
**The problem**
The Switch component only uses background colour to distinguish itself. When a website is rendered in High-Contrast mode, the background colour is removed and the Switch is invisible.

**How to reproduce**
Use Windows High Contrast mode. View a Switch in Firefox (the user reporting the issue uses Firefox).

Simplified test case:
I made a test page here:
https://2jibd.csb.app/
The page shows 4 Switches. The first is plain, and the last three have various border styles added. See that the first one is invisible:
![image (10)](https://user-images.githubusercontent.com/156496/80993453-ee200f00-8def-11ea-9d4b-8d6702099d2c.png)

**Expected behavior**
While background colours are hidden, borders are enhanced. If we add a transparent border to the Switch views for Thumb and Track, the Switch will become visible.
I have done this on twitter.com.

**Environment (include versions). Did this work in previous versions?**
Windows.

* React Native for Web (version): 0.11.7
* React (version): 16.8.6
* Browser: Firefox

An alternative option would be to allow any styles to be passed in for Thumb and Track, so sites can override as needed.

Happy to make a PR for this if helpful.

**Comment by necolas** [comment]
I wonder if we could use SVG to retain color in high contrast mode

**Comment by necolas** [comment]
Looks like colors in SVGs aren't touched https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/
