### ISSUE TITLE
getNativeScrollRef is not a function

### ISSUE THREAD

**Issue by whereiscode** [necolas/react-native-web#1607]
**The problem**

Steps to reproduce:

The flatList is nested inside the flatList, and when the list is large, it loads more dynamically, which prompts me for the error I described.

After the error occurs, there is a large blank area, and when you continue to pull down, the previous data comes out, but there is another large blank area.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.12.2
* React (version): 16.13.1
* Browser: google

**Comment by whereiscode** [comment]
windowSize
initialNumToRender
maxToRenderPerBatch

If these three parameters are not set to be large, in the case of a large list, only a few will be displayed, and no more will be loaded.

Suppose you set
WindowSize = 1000000
InitialNumToRender = 1000000
MaxToRenderPerBatch = 1000000

I can load more

**Comment by whereiscode** [comment]
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/55313887/81054327-2e1ee900-8ef9-11ea-9c92-e8cf7c2f45d6.png">
If you remove this height, everything will work properly

**Comment by necolas** [comment]
Duplicates #1560
