### ISSUE TITLE
better mouse support for Touchable

### ISSUE THREAD

**Issue by chrisdrackett** [necolas/react-native-web#1609]
**Is your feature request related to a problem? Please describe.**

Currently when using a mouse with Touchable components there are some behaviors that are undesirable. For example when the mouse presses down in an element and moves outside the element bounds the active state stays and the press event will still fire when the cursor is within the `PressRect` area. While this is what is probably wanted with a touch interaction it isn't standard with a mouse interaction.

*Note* I know this code is currently being refactored, so maybe this has been considered.

**Describe a solution you'd like**

I think ideally `Touchable` should be able to determine if the press is via a mouse or touch. When the press is via a mouse the strict bounds of the element are respected for hover, active and when it comes to firing the event. If the press is via a touch then things like `hitslop` or `pressRectOffset` can come into play.

**Describe alternatives you've considered**

I've considered not using `Touchable` at all on web, but as the lines here get more and more blurred (iOS supporting mice, windows supporting touch) there are positives to attempting handle both paradigms.

**Comment by necolas** [comment]
> Note I know this code is currently being refactored, so maybe this has been considered.

Yeah it's changed

**Comment by necolas** [comment]
See 0.13
