### ISSUE TITLE
Webview not supported?

### ISSUE THREAD

**Issue by twiz911** [necolas/react-native-web#161]
Hi

I'm trying to use the webview component but I'm getting an error in the render() method.

Is webview supported? If not, any idea when it will be?

Many thanks

**Comment by miketheanimal** [comment]
I have a very primitive version, works in Chrome, if this is any use:

    export class WebView extends React.Component {

        loadIFrame = () => {
            this.refs.iframe.srcdoc = this.props.source.html ;
            }

        render () {
            setTimeout(this.loadIFrame) ;
            return (
                <iframe ref="iframe" style={{ height: '100%', width: '100%', border: 0, seamless
                </iframe>
                ) ;
            }
        }

It does what I need, no more.

**Comment by necolas** [comment]
`WebView` is not currently supported (see the README for the list of supported components). I have no plans to look into implementing it yet – other parts of the framework are higher priority for us.

**Comment by piranna** [comment]
Any update on this? I'm needing it too. Would you accept a pull-request?

**Comment by damiaozi** [comment]
I want it too

**Comment by mikeaustin** [comment]
Just curious if there would be an issue with X-Frame-Options: SAMEORIGIN? For example, you can't use iframes for some sites. Or would it be used strictly for self-hosted content?

I'm simply raising the question, and am just a react-native-web lurker :)

**Comment by piranna** [comment]
> Just curious if there would be an issue with X-Frame-Options: SAMEORIGIN? For example, you can't use iframes for some sites.

There would be problems, but it's possible to disable the header on Electron or on regular browsers by adding an extension to whitelist the site, it's just a matter of showing a note to the users to install it.

**Comment by mikeaustin** [comment]
Then it seems pretty straightforward, either to fork and add it, or maybe add a "contrib" section and pull request so it's available, but not supported. i.e. everything in contrib would be experimental/at-your-own-risk. I understand the maintainers' philosophy, but at the same time it would be nice to have WebView available and for others to be able to contribute to it.

I originally looked at react-native-web to prototype react native apps without the hassle of setting up native. I'm busy with other things, but I've been lurking.

**Comment by Minishlink** [comment]
Hello, you can find an experimental implementation of `WebView` at [react-native-web-community/react-native-web-webview](https://github.com/react-native-web-community/react-native-web-webview).
It currently supports sources of `html` (without `baseUrl`), and `uri` (simple, or with POST method and `application/x-www-form-urlencoded` content-type). I plan on adding a prop that opens a new window instead of using an iframe, in order to circumvent CORS issues.
Note that WebView seems like a good candidate to never use on the web, since it leads to bad UX most of the time. Nevertheless, it's good to have an implementation ready in order to move on.

**Comment by piranna** [comment]
> Hello, you can find an experimental implementation of WebView at react-native-web-community/react-native-web-webview.

I was planning to do my own implementation with the same repo name, lol :-P I'll review it and see if I can help :-)

**Comment by Minishlink** [comment]
Cool, thanks! :)

**Comment by miketheanimal** [comment]
> Note that WebView seems like a good candidate to never use on the web, since it leads to bad UX most of the time. Nevertheless, it's good to have an implementation ready in order to move on.

I have been using react-native-web quite extensively in the development of a react-native app, because even with RN's development speed compared to native, development in a browser is still a lot faster (for me, anyway). So having a WebView implementation is really useful.

**Comment by yarra2296** [comment]
Is there any Possibility to use the WebView for the React-native-web Component. I tried using react-native-web-webview but I didn't get it working in the Web. So, suggest me a component which is helpful for Displaying the HTML content in the Web page.

**Comment by cyberpine** [comment]
Any chance for this? Really interested.

**Comment by lanman2000** [comment]
Just use an iframe if the platform is web. It works.

**Comment by sisoalbert** [comment]
Does any anyone have a functional components example code with iframe? I get the error failed to connect.
