### ISSUE TITLE
Additional Extensions

### ISSUE THREAD

**Issue by asleepingpanda** [necolas/react-native-web#1610]
This is more of a question than a feature request. I LOVE that you've enabled `.web.js` as a file extension for this.

In my React Dom project, I would like to enable this kind of feature, but specifically for that project. (in my case, .sandbox.js for my beta environments)

I'm trying to read through your babel plugin and extensions to figure out how you accomplished this, but I'm having a hard time tracking.

In my project, I'll have an environment variable called `ENABLE_SANDBOX=true` to indicate if you should use the sandbox specific file.

Any suggestions on how to approach this? It it possible to accomplish this using your babel plugin?

**Comment by necolas** [comment]
That's just webpack https://webpack.js.org/configuration/resolve/#resolveextensions
