### ISSUE TITLE
NativeModules undefined

### ISSUE THREAD

**Issue by csalgo70** [necolas/react-native-web#1612]
**The problem**

 I am new to react-native-web. Have created a simple app with expo init auth. I have added  
   "react-native-app-auth": "^5.1.2" so I can do oAuth login across ios, android and web.

**How to reproduce**

Try the test case below. Just click on the button and it would fail with (see console )

TypeError: Cannot read property 'authorize' of undefined
    at authorize (index.js:74)

Simplified test case:  https://gri6x.csb.app/ 

Steps to reproduce:

1. Click on the "Sign in with MSA" on the above testcase app.

**Expected behavior**

NativeModules shouldn't be undefined in index.js

**Environment (include versions).**

* React Native for Web (version): **"react-native-web": "~0.11.7"**
* React (version): **"react-native": "~0.61.5",**
* Browser: **Chrome**

OPTIONAL:

**Additional context**
 I did do react-native link react-native-app-auth as suggested by some for android ( plus modifying the MainApplication.java to add new RNAppAuthPackage() to the packages list in getPackages) / ios. But not sure how to fix this for web

**Comment by necolas** [comment]
NativeModules is exported but it's just a stub as native modules can't really be loaded on the web

**Comment by csalgo70** [comment]
So what is the option for oAuth when you want to share code across web and native apps in react-native.

**Comment by oottoohh** [comment]
up
