### ISSUE TITLE
Status of the LayoutAnimation Translate Property

### ISSUE THREAD

**Issue by sgehly** [necolas/react-native-web#1613]
**Is your feature request related to a problem? Please describe.**

I'm curious about the status of LayoutAnimation's translate property, and what the technical challenges are that block it from being a part of the current implementation.

**Describe a solution you'd like**

It'd be awesome to put this back on the radar, and I'd certainly be interested in taking a look at implementing it if I have the capability once I have an understanding of why it's not as straightforward as the other properties (if it isn't).

**Describe alternatives you've considered**

I'm not clear if other libraries solve this problem when used with react-native-web, or if I can abstract LayoutAnimation to use a different dedicated React library on the web. If there are alternatives I'd love some pointers.

**Additional context**

**Comment by necolas** [comment]
Feel free to take a look, I haven't worked on `LayoutAnimation` at all and don't plan to

**Comment by danielstern** [comment]
Should this feature maybe be removed from React Native if no one can get it to work and no one wants to work on it?

**Comment by sgehly** [comment]
@danielstern I've been able to get it work (with very sloppy code and probably not the best design decisions, I was solely focused on getting it to work) with react-native-web. If there's interest I can push it to the fork I have, but I don't have the bandwidth currently to get the implementation to match the React Native API.
