### ISSUE TITLE
Touchable child must either be native or forward setNativeProps to a native component

### ISSUE THREAD

**Issue by Chahat-23** [necolas/react-native-web#1615]
Touchable child must either be native or forward setNativeProps to a native component
![image](https://user-images.githubusercontent.com/49164800/81954669-c23e2e00-9626-11ea-91a2-0386645664e9.png)

in this file the above problem marked is occuring..
How will it be resolved..please help...

**Comment by necolas** [comment]
This is how the components were designed in React Native initially. Shouldn't be a problem for the latest versions
