### ISSUE TITLE
Upgrading from 0.11.6 to 12 breaks styled-components

### ISSUE THREAD

**Issue by tettoffensive** [necolas/react-native-web#1618]
**The problem**
Using `styled-components` with `react-native-web` `0.11.7` I can clearly see that the style is being applied.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/react-native-web-styled-components-dxkbg?file=/src/App.js

Steps to reproduce:
1. Run the test case with `react-native-web v0.12.2`
2. Note that the text labeled `Title` is not styled
3. Change the version of `react-native-web to v0.11.7`
4. See the correct style

**Expected behavior**

You should see this:
<img width="679" alt="Screen Shot 2020-05-15 at 11 46 37 AM" src="https://user-images.githubusercontent.com/5884119/82085350-bf345380-96a1-11ea-992d-88b9f3ae692b.png">

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.7
* React (version): 16.12.0
* Browser: Chrome

**Additional context**

Note that even older versions didn't work as expected, though the syntax that I used in the example did work with v0.11.7: https://github.com/styled-components/styled-components/issues/3142

**Comment by necolas** [comment]
```js
import styled from "styled-components/native";
```

But I strongly recommend not using styled-components. You're adding another layer of bundle and runtime cost with no benefits.

**Comment by tettoffensive** [comment]
For anyone finding this: 
- 11.7.0 works with: `import styled from "styled-components";`
- 12 works with: `import styled from "styled-components/native";`

**no benefits** is subjective. I much prefer the syntax over having `style={styles.text}` everywhere. However, I understand your concern about runtime costs and even more concerning to me is how it could potentially break in the future.

**Comment by steida** [comment]
I would not favorite familiarity over functionality.
