### ISSUE TITLE
Failed prop type: Invalid props.style key 'fontFamily' supplied to 'Picker'

### ISSUE THREAD

**Issue by gunnartorfis** [necolas/react-native-web#1619]
When using the Picker component, passing `fontFamily` to `props.style` leads to the following warning: 
`Failed prop type: Invalid props.style key 'fontFamily' supplied to 'Picker'.`

**How to reproduce**
Simplified test case: https://codesandbox.io/s/flamboyant-breeze-z5ryz?file=/src/App.js

**Expected behavior**
The warning should not be logged since the style key **does apply desired effects** 

* React Native for Web (version): 0.11.7
* React (version): 16.12
* Browser: Brave (Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit))
                  Google Chrome (Version 81.0.4044.138 (Official Build) (64-bit))

**Comment by necolas** [comment]
Can't reproduce in 0.12

**Comment by gunnartorfis** [comment]
Can I update the bug report template's Codesandbox link? Or do you have to do it? It defaults to v11.x.
