### ISSUE TITLE
Nesting styles behave differently on iOS、Android and Web

### ISSUE THREAD

**Issue by relign** [necolas/react-native-web#1620]
**The problem**
Nesting styles behave differently on iOS、Android and Web.

**How to reproduce**
```
<View style={{ flexDirection: 'row', alignItems: 'center' }}>
  <View style={{ flexDirection: 'row', alignItems: 'center' }}>
    <View style={{ height: 100, backgroundColor: 'red', flex: 1 }}>
      <View style={{ height: 100 }}></View>
      <Text>张三李四王五</Text>
    </View>
    <View style={{
      marginTop: 16,
      marginRight: 20,
      backgroundColor: '#EBEBEB'
    }}>
    </View>
  </View>
</View>
```
In Android and iOS:
![image](https://user-images.githubusercontent.com/13749042/82190287-670c8400-9923-11ea-8d8b-07c374de8392.png)
But in Web:
![image](https://user-images.githubusercontent.com/13749042/82190322-725faf80-9923-11ea-8c1d-80bbd19beeed.png)

**Expected behavior**
Their UI is consistent

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: TBC

**Additional context**
I guess it cause because of the Yoga doesn't behave the same as the Web?
emmm...

**Comment by necolas** [comment]
This issue needs a link to a test case on codesandbox and the library version numbers

**Comment by relign** [comment]
@necolas 
codesandbox Link: [Demo](https://codesandbox.io/s/cranky-wiles-rh3us)
Environment (include versions):
React Native for Web (version): 0.12.2
React (version): 16.8.6
Browser: Chrome 81.0.4044.138
React Native: 0.60.5

**Comment by necolas** [comment]
Yeah it's React Native that's getting the layout wrong. Yoga doesn't implement flexbox correctly, and in this case the 2nd view also needs `flex:1` to fill its parent.

**Comment by relign** [comment]
Thanks~~~
