### ISSUE TITLE
ErrorUtils is undefined in React Native for Web

### ISSUE THREAD

**Issue by daxfrost** [necolas/react-native-web#1621]
**The problem**

ErrorUtils is undefined and therefore unusable for globally capturing uncaught JS exceptions.

I am not sure how else to proceed, but any advice on how to approach this would be wonderful, I have scoured the internet for answers before coming here looking for guidance.

**How to reproduce**

Simplified test case: 

![image](https://user-images.githubusercontent.com/1788177/82236054-8eeaf000-9901-11ea-9882-de9a6519bb93.png)

Steps to reproduce:
1. Reference the global ErrorUtils object from React Native in any RN4W project
2. See that it's always `undefined`

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): `0.12.2`
* React (version): `16.11.0`
* Browser: `Chrome  80.0.3987.163 (Official Build) (64-bit)`

**Comment by necolas** [comment]
There is no ErrorUtils global in the browser so you should check it exists before calling it

**Comment by daxfrost** [comment]
@necolas thank you for your response - I was hoping you had a preferred way / suggestion for handling all uncaught JS exceptions with `React Native for Web`? I assume `window.onError()` or using some SDK wrapping this would be the best option.

**Comment by necolas** [comment]
I don't know. Maybe @EvanBacon has done something for this in Expo. I don't know why RN added this is a global but Expo is the library that polyfills all the weird RN environment stuff, while RNW is focused on the APIs exported from `react-native`

**Comment by altany** [comment]
@daxfrost Did you ever get around this?

**Comment by daxfrost** [comment]
@altany I haven't spent time on this in a little while, but the reality is that the ErrorUtils is bound to the React Native embedded usage of JavaScriptCore engine - not the browser's Javascript engine, so technically you should simply avoid using ErrorUtils altogether, by abstracting away from it and using standard `window.onError` methods, which is utilized by many web SDKs (e.g: https://github.com/rollbar/rollbar.js/blob/0ffa71592d4b6a312f832134121d745c672811f0/src/browser/globalSetup.js#L1-L25)

**Comment by CannibalKush** [comment]
This is sort of a weird and wild one, but in trying to use [@sentry/react-native](https://github.com/getsentry/sentry-react-native) with React Native Web, I run into this, and can't seem to find a way around it without doing patches to Sentry's SDK, which would be less than ideal. Would love a more workable alternative.

**Comment by Tjax33** [comment]
Why on earth is this closed this is still an issue. 

I need to be able to use @sentry/react-native with React Native Web as well. This should not be closed until it is fixed
