### ISSUE TITLE
Using RNW with out-of-tree platforms

### ISSUE THREAD

**Issue by endquote** [necolas/react-native-web#1623]
I have a React Native implementation for an [out-of-tree platform](https://reactnative.dev/docs/out-of-tree-platforms). I would like to use RNW to render it to the web. I'm not really sure how to get started, or if it's even possible.

My first naive attempt was to add `react-native-web` and `react-scripts` to my project, and run `react-scripts start`, but of course it complained about not being able to find an index.js entrypoint.

A document describing how to add RNW to another platform (maybe `react-native-windows` would be a good example) would be pretty helpful. Maybe someone has written a blog post or similar already?

**Comment by necolas** [comment]
There's an example in the docs https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page
