### ISSUE TITLE
CSS is generated differently for the same code, but on different components

### ISSUE THREAD

**Issue by tstankevicius** [necolas/react-native-web#1625]
**The problem**
Different styles are generated for the exactly same code added to two components with just different name of component. 
If I add the same component twice - it renders ok. the style generated is also the same.

**How to reproduce**
Write advanced component with several complex elements. Duplicate component and modify the name of 2nd. Add both components on the RN screen inline. The generated styles will be different.

**Problem screeshot:**
<img width="1463" alt="Screenshot 2020-05-21 at 16 01 39" src="https://user-images.githubusercontent.com/9268579/82567243-65d69380-9b7d-11ea-8134-3d9f780b6e06.png">

**Expected behavior**
The generated styles should be exactly the same as they are if you place same component twice.

Environment (include versions). Did this work in previous versions?
Mac.

React Native for Web (version): 0.11.7
"react": "16.12.0",
"react-native": "0.60.5",
Browser: Chrome, Firefox, Safari

**Comment by necolas** [comment]
I can't tell anything from the screenshot. Please create a test case on codesandbox using the latest version of RNW

**Comment by necolas** [comment]
Closing this issue as there has been no reproduction steps or test case provided

**Comment by tstankevicius** [comment]
Hello,
Sorry it took long time to find the root cause. So I created a sandbox example - https://codesandbox.io/s/react-native-web-epdh3

In there the attention point is PxSpinner component. I placed it into two places:

1. The components folder in source code
2. In separate npm module '@devopro/react-native-common-components

In Subscriptions.js file you will find two imports of it: 
1. It works fine when you import it from components folder.
2. It stops working when you import it from another npm module.

The generated html code with css classes are exactly the same in both cases. But style interpretation is different. As a sudden in case of import from node modules the css-view-1dbjc4n takes precedences over other important and more specific styles.

Thank you.

**Comment by necolas** [comment]
Seems to work fine with either import if you use version 0.12.2

**Comment by tstankevicius** [comment]
In sandbox yes - but the real project is blocked due to ViewProps being removed in latest version. I saw the ticket for that already - https://github.com/necolas/react-native-web/issues/1537 but just wanted to ask for a favour and add it back as deprecated until RN removes it completely. You are basically blocking 90% of your audience for no good reason.
Thank you.

**Comment by necolas** [comment]
The prop types are gone in react native too. You can use 'yarn patch' to add them back locally until you take the time to update your project to stop using them. Prop types don't do anything except some runtime type checks in development, so they are unnecessary

**Comment by tstankevicius** [comment]
Hello,
I wanted to comment on https://github.com/necolas/react-native-web/issues/205 but don't have access to do it.

The issue is that onMouseEnter and onMouseLeave only works in Responsive Desktop mode. Same sandbox as before:
https://codesandbox.io/s/react-native-web-p6e9q?file=/src/components/Subscriptions.js

You can see console logs when you hover on the box. But if you do Inspect on Chrome and switch to responsive mobile view the hovering stops working. 

On my own project it is again different. Dekstop mode works fine. Mobile mode works when I click in and click out of the element instead of hover.

The hovering also does not work if you open sandbox link directly even on desktop mode, but I blame the codesandbox tool for this :) https://epdh3.csb.app/

Would you take a quick look please? Or should I raise another ticket?

Thank you.

**Comment by tstankevicius** [comment]
Hello,
not sure if you had time to look into previous one, but I suggest to ignore it. I was not very smart requesting hovering effect on mobile mode when on mobile hovering is not relevant...

Thank you.

**Comment by riteshoyo** [comment]
@tstankevicius @necolas I am also facing the same issue that is mentioned [here](https://github.com/necolas/react-native-web/issues/1625#issuecomment-635934591)? Can you please let me know how did you fix the issue? I am using the RNW version 0.14.13.

**Comment by tstankevicius** [comment]
Applying latest version at that moment 0.12.2 fixed the issue for me.
