### ISSUE TITLE
Accessibilityrole: none is generated to role="presentation" for web

### ISSUE THREAD

**Issue by caner-karaman** [necolas/react-native-web#1626]
When I gave 'none' to Text component's accesibilityRole, it generates role="empty presentation" 

Steps to reproduce:
1. Create a View element
2. Add accesibilityRole="none" prop to this View

**Expected behavior**
Element role attribute will be empty if I give accessibilityRole="none"

* React Native for Web (version): 0.10.0
* React (version): 16.12.0
* Browser: safari, google

**Comment by necolas** [comment]
'none' is a synonym for 'presentation', the latter has better backwards compatibility
