### ISSUE TITLE
Accessibilityrole: text is generated to role="empty group" for web

### ISSUE THREAD

**Issue by caner-karaman** [necolas/react-native-web#1627]
When I gave 'none' to Text component's accesibilityRole, it generates role="empty presentation"

Steps to reproduce:
- Create a Text element
- Add accesibilityRole="none" prop to this Text

Expected behavior
Element role attribute will be empty if I give accessibilityRole="none"

React Native for Web (version): 0.11.7
React (version): 16.12.0
Browser: safari, google

**Comment by necolas** [comment]
The expected behavior is to render `role="presentation"`
