### ISSUE TITLE
autocomplete="noop" is wrong since latest chrome update, we should switch back to off

### ISSUE THREAD

**Issue by kopax** [necolas/react-native-web#1628]
## Environment

Web RNW 11

> We do not use RNW12 due to the removed features that haven't been replaced yet.

## Description

I am trying to disable the `autocomplete` on the web using [`TextInput`](https://callstack.github.io/react-native-paper/text-input.html) from [react-native-paper](https://github.com/callstack/react-native-paper) 3.10.1

```jsx
<TextInput
  name="city"
  textContentType="addressCity"
  autoComplete="off"
  mode="outlined"
/>
```

The `autoComplete="off"` is replaced with `autocomplete="noop"` in the rendered HTML, which cause the auto complete not to be disabled.

![image](https://user-images.githubusercontent.com/1866564/82732345-fa233080-9d0c-11ea-906e-0335097d7feb.png)

The `noop` create an error when disabling autocomplete here

https://github.com/necolas/react-native-web/blob/e810f1fd2b41293cb1efe04e332fb6f8d4bcca65/packages/react-native-web/src/exports/TextInput/index.js#L261

## Reproducible Demo

https://snack.expo.io/@kopax/curious-pizza

## Possible solution

Release a fix that removes that line, more generally, we should have been able to solve that userland and not in that lib.

Because RNW 12 is not a valid solution for us, is it possible to fix a v11+ version?

## Related issues

- https://github.com/callstack/react-native-paper/issues/1946

**Comment by necolas** [comment]
I'm not going to back port patches. 0.12 has been out for a long time and 0.13 is nearing release. 0.12 didn't remove features, it removed deprecated APIs, many of which is now also gone in React Native. If you explain you problems upgrading maybe I can make suggestions for you

**Comment by kopax** [comment]
Thanks for offering to help with the upgrade. One reason that come to my mind is AsyncStorage being removed. I already tried twice to upgrade but I failed. I think the replacement library wasn't ready or needed a significant rewrite and I ran out of time. 

RNP team also use an older version of RNW for similar reasons

**Comment by necolas** [comment]
You can copy paste the old modules out of 0.11 but React Native's exported API has also changed a lot over the last year. RNP will need to migrate off the deprecated / removed APIs too. For now you can follow the build config that @EvanBacon made for expo web for these old modules

It is unfortunate that RN's "lean core" moved a few modules to poorly maintained community packages that dramatically changed the APIs. That boat has sailed though

**Comment by necolas** [comment]
You can also use yarn to patch packages locally https://yarnpkg.com/cli/patch
