### ISSUE TITLE
'ActionSheetIOS' is not exported from 'react-native'

### ISSUE THREAD

**Issue by devbihari** [necolas/react-native-web#1630]
RNW does not support ActionSheets using `react-native-actionsheet`. I get the following error when I try to run the project in the firefox browser. 
```shell
'ActionSheetIOS' is not exported from 'react-native'
```
Is it a missing feature or I fail to make it work?

Any help is appreciated.

A.

**Comment by necolas** [comment]
ActionSheetIOS is not supported on web. And that package you're using hasn't been updated in 2 years and doesn't support multiple platforms by using platform specific extensions

**Comment by walidvb** [comment]
Agreed that the sheet doesn't exist on web.
However, I would sure hope that building a react-native code would not break on compilation when building for web, but I see this opinion is consistent with the one last posted on #1651 .
Maybe a secondary package, react-native-web-bridges or smth could provide API mappings between the platforms? 🤔
