### ISSUE TITLE
when <image> component  resizeMode is center or repeat, backgroundSize is not right

### ISSUE THREAD

**Issue by laszhiai** [necolas/react-native-web#1632]
**Image style backgroundSize is wrong**
should be background-size: xxPX,xxPX，but it's auto

**How to reproduce**

Simplified test case: 
```
<View style={StyleSheet.absoluteFillObject}>
         <Image
                style={{flex: 1, opacity: 1}}
                resizeMode={'center'}
                source={{uri:'http://secure.finedevelop.com:65081/webroot/jacky.png'}}/>
</View>
```
just use this as AppContainer

**need to disable cache in chrome**

**Environment (include versions). Did this work in previous versions?**
always

* React Native for Web (version):0.11.4
* React (version): 16.6.3
* Browser: chrome && safari
two browser have different behavior

**Comment by necolas** [comment]
The issue template is there for a reason, so please fill it out or I will close this. Thanks
