### ISSUE TITLE
Sample of adding react-native-web to an existing react-native app

### ISSUE THREAD

**Issue by csalgo70** [necolas/react-native-web#1633]
It would be very useful for a newbie like me to see an example of all the steps, to add react-native-web to an existing react-native-app which doesn't use expo. With the repro steps below, I am hoping, it should be easy for someone who has worked on this for a while to spot the issue quickly.

I did read the [documentation](https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page). But there are still issues.

**Repro Steps:**

Creating the barebones app using react-native cli

react-native inti ilabsweb

cd myapp

Copied the webpack.config.js from above documentation site to ilabsweb/web/ folder

yarn add react react-dom react-native-web

yarn add babel-plugin-module-resolver

yarn add --dev babel-loader url-loader webpack webpack-cli webpack-dev-server

yarn add --dev babel-plugin-react-native-web

---Ran into Errors / to Fix added  

yarn add babel-preset-react-native

yarn

./node_modules/.bin/webpack-dev-server -d --config ./web/webpack.config.js --inline --hot --colors 

gives the following error using the same webpack.config.js at the documentation site above.

ERROR in ./App.js 24:12

Module parse failed: Unexpected token (24:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   return (
|
>             <View style={styles.sectionContainer}>
|               <Text style={styles.sectionTitle}>Learn More</Text>
|               <Text style={styles.sectionDescription}>
 @ ./index.web.js 1:340-356
 @ multi ./index.web.js

![packages json](https://user-images.githubusercontent.com/2498081/83561846-63553180-a4cd-11ea-8535-6c520358cc9e.jpeg)

**Comment by necolas** [comment]
As mentioned in the docs on that page

> If you depend on uncompiled packages they may cause webpack build errors. To fix this webpack can be configured to compile to the necessary `node_module`

But I strongly recommend using Expo who have all this built-in.

**Comment by KingAmo** [comment]
> To fix this webpack can be configured to compile to the necessary node_module
@necolas   how to configure `webpack` to solve this problem ? could you please help ?

**Comment by KingAmo** [comment]
in my case, i have a webpack config like this
```
 module: {
        rules: [{
            test: /\.js$/,
            exclude: /(node_modules|bower_components)/,
            use: {loader: 'babel-loader',}
        }]
    },
```
so i removed  ` exclude: /(node_modules|bower_components)/` and everything works fine !

**Comment by KingAmo** [comment]
https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page#web-packaging-for-existing-react-native-apps

as the doc says:
>// This is needed for webpack to compile JavaScript.
// Many OSS React Native packages are not compiled to ES5 before being
// published. If you depend on uncompiled packages they may cause webpack build
// errors. To fix this webpack can be configured to compile to the necessary
// `node_module`.

```
    path.resolve(appDirectory, 'node_modules/react-native-uncompiled')
```

just replace `react-native-uncompiled`  with the package name which throw the error  `You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.`
