### ISSUE TITLE
Redux looking for `unstable_batchedUpdates` from `react-native`

### ISSUE THREAD

**Issue by samuelneff** [necolas/react-native-web#1639]
**The problem**
When running a redux application with react-native-web I get this error as soon as the first action is dispatched.
```
error in mw dispatch or next call, probably in middlware/reducer/render fn: TypeError: batch is not a function
```
I was able to track it to this code in Redux:

https://github.com/reduxjs/react-redux/blob/5e6205a2f9bb18e1f8b0163382bc29230ea7d3d3/src/utils/reactBatchedUpdates.native.js
```
import { unstable_batchedUpdates } from 'react-native'

export { unstable_batchedUpdates }
```

Where it's looking for a function called `unstable_batchedUpdates` from `react-native` that eventually gets assigned to a variable called `batch`. There's a corresponding file for web-world where it imports this same function from `react-dom`. 

I believe `react-native-web` would need to import this function from ReactDOM and re-export it to make Redux happy.

Simplified test case: Sorry, Corp proxy does not allow access to codesandbox.io

Steps to reproduce:
1. Create React Native app
2. Add React Native Web support
3. Use Redux
4. Dispatch an action

**Expected behavior**
Should run without error. ;)

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.12.3
* React (version): 16.11.0
* Browser: Chrome 83.0.4103.97

**Additional context**
This is my first time trying to use React Native Web. I bundled the app with metro bundler using instructions found here:

https://github.com/necolas/react-native-web/issues/1257#issuecomment-541443684

**Comment by necolas** [comment]
They already have this file: https://github.com/reduxjs/react-redux/blob/5e6205a2f9bb18e1f8b0163382bc29230ea7d3d3/src/utils/reactBatchedUpdates.js

You shouldn't need to use the react native version of redux

**Comment by samuelneff** [comment]
I'm not using any specific version of Redux for React Native. It seems it's detecting React Native and trying to use that one. I don't see how else to explain this value being undefined.

**Comment by necolas** [comment]
Then the problem is metro bundling files with .native extensions instead of .web for the web build

**Comment by samuelneff** [comment]
@necolas yes, the issue is related to Metro bundler pulling in the `.native` module instead. `react-native-web` can address this though. I was able to resolve this by adding this code:

```js
// In node_modules/react-native-web/dist/cjs/index.js
exports.unstable_batchedUpdates = _interopRequireDefault(require("react-dom")).default.unstable_batchedUpdates;
```

**Comment by samuelneff** [comment]
I added this code to my web bundle script and it's working now.
```bash
grep unstable_batchedUpdates node_modules/react-native-web/dist/cjs/index.js > /dev/null 2> /dev/null
if [ $? ]; then
  echo '' >> node_modules/react-native-web/dist/cjs/index.js
  echo 'exports.unstable_batchedUpdates = _interopRequireDefault(require("react-dom")).default.unstable_batchedUpdates;' >> node_modules/react-native-web/dist/cjs/index.js
fi
```

**Comment by necolas** [comment]
It's going to pull in the native files for everything else too, so this is a probably with how the bundler is configured

**Comment by samuelneff** [comment]
So far everything else works. Should I report anything else that doesn't or are you not concerned with supporting the metro bundler?

**Comment by MonchiLin** [comment]
1. open node_modules/react-native-web/dist/index.js

2. add the line
```
export { unstable_batchedUpdates } from 'react-dom'
```

3. npx patch-package react-native-web 

Works for me!
