### ISSUE TITLE
 Unexpected token 

### ISSUE THREAD

**Issue by salman15** [necolas/react-native-web#1641]
**The problem**
I've updated my react, expo and expo-cli version recently and am trying to get expo web running on this updated project, but whenever I run expo start --web I get the following error:

```
web  Failed to compile.
/App/App.js
SyntaxError: /App/App.js: Unexpected token (6:9)

  4 | 
  5 | const App = () => {
> 6 |   return <Text>Hii</Text>;
    |          ^
  7 | };
  8 | 
  9 | export default App;
```
The app works fine on IOS and android, but I keep getting this error for web.

Not sure what's causing the error.

I've added "web" to platform in my app.json

My app file is

```
import React from "react";

import { Text } from "react-native";

const App = () => {
  return <Text>Hii</Text>;
};

export default App;
```
**How to reproduce**
Install expo SDK 37
Install the latest version of the Expo CLI: npm i -g expo-cli
Add web dependencies: yarn add react-native-web react-dom
Ensure your project has at least expo@^33.0.0 installed.
Start your project with expo start then press w

**Expected behavior**
Web app to start with either specified error or working

**Environment (include versions). Did this work in previous versions?**

```
"@expo/vector-icons": "^10.0.0",
    "@react-native-community/netinfo": "5.5.1",
    "axios": "^0.18.0",
    "expo": "^37.0.0",
    "expo-barcode-scanner": "~8.1.0",
    "expo-constants": "~9.0.0",
    "expo-font": "~8.1.0",
    "expo-updates": "~0.2.1",
    "intl": "^1.2.5",
    "laravel-echo": "^1.6.1",
    "navigation": "^5.2.0",
    "pusher-js": "^6.0.2",
    "react": "16.9.0",
    "react-dom": "^16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-background-timer": "^2.1.1",
    "react-native-elements": "^1.2.7",
    "react-native-fbsdk": "^0.8.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-maps": "0.26.1",
    "react-native-payment-gateway": "^0.4.3",
    "react-native-reanimated": "~1.7.0",
    "react-native-redash": "^3.3.2",
    "react-native-screens": "^2.2.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-svg": "11.0.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.12.3",
    "react-navigation": "^3.13.0",
    "react-redux": "^5.1.2",
    "redux": "^4.0.4",
    "styled-components": "^4.4.1"
```

**Comment by necolas** [comment]
This is a compiler issue. If it's happening with expo and you've followed their instructions, you should open a bug against expo.
