### ISSUE TITLE
[Text] fontSize not work when lower than 12 on web

### ISSUE THREAD

**Issue by KingAmo** [necolas/react-native-web#1642]
**The problem**
on web, when fontSize is above 12, it works ;  but when font is lower than 12, it does not work ,  however, on iOS or Android, everything is fine
```
<Text style={{fontSize: 10}}>hello</Text>
```
**How to reproduce**

Simplified test case: 
https://codesandbox.io/s/little-browser-w5jy7?file=/src/App.js
Steps to reproduce:
1.
2.
3.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: TBC

**Comment by KingAmo** [comment]
@necolas could you please help?

**Comment by necolas** [comment]
It renders as expected in the codesandbox.

You also don't need to demand help from me moments after opening an issue.

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/84735390-fc0fa500-afd5-11ea-883a-ed55e5dc0dce.png)
did i miss something ?  it do not work as expected when fontSize is below 12

**Comment by KingAmo** [comment]
you can see that when below 12,  font size are the same

**Comment by necolas** [comment]
![Screenshot_20200615-223653_Chrome](https://user-images.githubusercontent.com/239676/84735602-c4164c80-af58-11ea-8653-314308253fcc.jpg)

This is what I see. If you don't provide enough information about how to reproduce an issue, I can't help you. It could be that the browser just ignores font sizes below a certain level

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/84735806-f49ccb80-afd6-11ea-9d21-6079d6d64f1e.png)
change to Safari everything is fine, maybe it is Chrome's fault

**Comment by KingAmo** [comment]
much thanks!
