### ISSUE TITLE
TouchHistory‘s processing logic caused the Crash in Safari

### ISSUE THREAD

**Issue by relign** [necolas/react-native-web#1644]
**The problem**

In "react-native-web/dist/hooks/useResponderEvents/ResponderTouchHistoryStore.js" ,  use `touchBank` tracks the position.
But `touchBank`'s type is `Array` and `touch identifier`’s not a number between 0 and 20, It can be very big sometimes，examples: `863683572`.  It can cause Crash in Safari.

**How to reproduce**

Simplified test case: 
Examples Code: 
```javascript
var arr =[]; arr[863683572]=109; console.log(arr.length);console.log(arr);
```
You can run it multiple times in Safari to reproduce this problem.
![image](https://user-images.githubusercontent.com/13749042/85110115-fa97e400-b244-11ea-8347-aaa219c15a28.png)

**Expected behavior**

I think you can change `touchBank`'s type to `Object` store history of touch position in `ResponderTouchHistoryStore.js`.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): The latest next branch in the code repository
* React (version): 16.8.6
* Browser: Safari

**Comment by relign** [comment]
@necolas 
The same code doesn't cause crash in Chrome,  I guess V8 has a few tweaks to the `Array`.

**Comment by necolas** [comment]
I don't understand what you're trying to explain

**Comment by relign** [comment]
@necolas 
Demo Code:
```javascript
// app.tsx
import React from 'react'
import { View } from 'react-native'

// Fork this sandbox and add example code
// to reproduce the issue.
//
// Please check the versions of dependencies
// in package.json

class App extends React.Component {
    render() {
        return <View style={{ backgroundColor: 'blue', height: 500 }} />
    }
}

export default App
```

**Then, I'll simulate the gesture of double refers to zoom on the mobile Page of React-Native and Web, respectively, to trigger the logic of the `touchBank` collecting position information.**

**Use React Native**, insert debug log:
```
// node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js
function getTouchIdentifier(_ref) {
  var identifier = _ref.identifier;
  console.warn('[Demo] identifier', identifier);
  ...
  return identifier;
}
```

In iOS React Native App:
<img src="https://user-images.githubusercontent.com/13749042/85247221-a3318800-b47f-11ea-82e6-70521ac10776.png" width="300">
In Android React Native App:
<img src="https://user-images.githubusercontent.com/13749042/85247171-839a5f80-b47f-11ea-9bd3-4bafb4e7e04e.png" width="300">

**Use React Native Web**, debug log:
```
// node_modules/react-native-web/dist/hooks/useResponderEvents/ResponderTouchHistoryStore.js
function getTouchIdentifier(_ref) {
  var identifier = _ref.identifier;
  console.warn('[Demo] identifier', identifier);
  ...
  return identifier;
}
```
In Android Web Page:
<img src="https://user-images.githubusercontent.com/13749042/85273640-6f228b00-b4b0-11ea-87fe-a4afb33096b1.png">
But In iOS Web Page:
![image](https://user-images.githubusercontent.com/13749042/85273935-d80a0300-b4b0-11ea-9a3a-f1767860ca34.png)

**The `identifier` value here will be very large In iOS Web Page,  If sometimes more touches are triggered,  the code about `TouchBank`  will run very slowly or even Crash**

ಥ_ಥ...  I think `touckBank` should be stored as `Object` in Web environment.

**Comment by necolas** [comment]
I see what you're saying, thanks.

It's unfortunate that the touchBank array is part of the RN responder event API, because adding touches to an array like that is a bad code pattern that can create enormous arrays. A Map would be better in this case.

And it's bizarre that safari is still using huge identifiers too. If this bug is not occurring in 0.12 it may be because of this line of code https://github.com/necolas/react-native-web/blob/36dacb2052efdab2a28655773dc76934157d9134/packages/react-native-web/src/modules/normalizeNativeEvent/index.js#L22

**Comment by relign** [comment]
@necolas 
Will we be compatible with this issue in latest next branch?

**Comment by necolas** [comment]
This is patched in master

**Comment by necolas** [comment]
> This is patched in master

I actually don't see where this patch went 😬 Is anyone still experiencing this issue with 0.13.x?

**Comment by relign** [comment]
> > This is patched in master
> 
> I actually don't see where this patch went 😬 Is anyone still experiencing this issue with 0.13.x?

Thanks, it's work perfectly in 0.13.x.

**Comment by necolas** [comment]
Oh here it is https://github.com/necolas/react-native-web/blob/cfe36d780e981885ce73862a9effcea29e7ea1c9/packages/react-native-web/src/hooks/useResponderEvents/ResponderTouchHistoryStore.js#L89
