### ISSUE TITLE
Native animated module is not available

### ISSUE THREAD

**Issue by Uysim** [necolas/react-native-web#1647]
I use [fastlist](https://gist.github.com/vishnevskiy/f4ba74adf5cf1d269b860fab86e8feef) as suggest in document but I got **Native animated module is not available**

* React Native for Web: 0.11.7

**Comment by necolas** [comment]
That module is only available on native platforms. You'll have to make edits to run it on the web. Maybe discord will publish their original web implementation too. You can ask them
