### ISSUE TITLE
Typescript type for TextInput "onKeyPress" event do not have "key" attribute

### ISSUE THREAD

**Issue by danawoodman** [necolas/react-native-web#1649]
**The problem**

According to the [docs](https://necolas.github.io/react-native-web/docs/?path=/docs/components-textinput--auto-capitalize#onkeypress), the `onKeyPress` event of the `TextInput` component should have a `key` attribute but the Typescript types (`TextInputProps.onKeyPress?: (e: NativeSyntheticEvent<TextInputKeyPressEventData>) => void`), do not support a `key` attribute so doing `e.key` fails TS validation.

**How to reproduce**

1. Setup react-native-web with Typescript
2. Try and pass a `onKeyPress` callback to a `TextInput` component while use `key`
3. See TS complain

```tsx
  function handleKeyPress(
    e: NativeSyntheticEvent<TextInputKeyPressEventData>
  ): void {
    console.log(e.key)
  }

  return (
    <div>
      <Input
        onKeyPress={handleKeyPress}
        value={val}
      />
    </div>
  )
```

**Expected behavior**

Types should have `key` attribute for `NativeSyntheticEvent<TextInputKeyPressEventData>`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): `0.12.3`
* React (version): `16.13.1`
* Browser: Brave

**Comment by necolas** [comment]
Probably expects you to use `e.nativeEvent.key`

**Comment by danawoodman** [comment]
@necolas you're correct, that fixed it. Is this documented somewhere and I missed it? Would this be obvious to other new users?

For posterity, here is how to use the key events:

```
import { NativeSyntheticEvent, TextInputKeyPressEventData } from "react-native"

  // in your component...
  function handleKeyPress(
    e: NativeSyntheticEvent<TextInputKeyPressEventData>
  ): void {
    console.log(e.nativeEvent.key)
  }
```
