### ISSUE TITLE
How to get parameter value from query string of url in react-native-web?

### ISSUE THREAD

**Issue by KingAmo** [necolas/react-native-web#1653]
**The problem**
How to get parameter value from query string in react-native-web? 

i have see a solution:
https://stackoverflow.com/questions/55592321/accessing-url-with-params-from-a-react-native-web-app

but what if I do not use `react-navigation`?

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1.
2.
3.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: TBC

**Comment by KingAmo** [comment]
or just use `document.URL` ?

**Comment by KingAmo** [comment]
simply use like this:
```
const urlParams = new URLSearchParams(window.location.search);
const myParam = urlParams.get('myParam');
```
see https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript

**Comment by conor909** [comment]
This will break on iOS and Android

**Comment by Stevemoretz** [comment]
> Wont this break on iOS and Android?

It would
