### ISSUE TITLE
Horizontal Scrolling by touch actions isn't working on Safari

### ISSUE THREAD

**Issue by mafiusu** [necolas/react-native-web#1658]
**The problem**
I'm using a ScrollView / FlatList to render some items horizontal. On the Safari, there is the problem that I can't scroll to right or left based on my (mouse) touch actions. In the Chrome Browser this works. I also set touchAction: "pan-x" to the styles of my ScrollView/FlatList but it doesn't have any effect. When I set touchActions to none, this has an effect to Chrome (scrolling disabled)

**Steps to reproduce:**
1. Create a Scrollview with horizontal prop
2. Place some more items with (<View style={{width: 150, height: 150, backgroundColor: 'blue'}/> in a row (view>
3. run on safari - scrolling by touch input isn't working

**Expected behavior**
Scrolling Horizontal like on the smartphones.

**Environment**

* React Native for Web (version): "^0.11.7" (Expo)
* React (version): 16.9.0
* Browser: Safari Version 13.1 (15609.1.20.111.8)

For UX purpose I would solve it when showing scroll indicators are always showing. But that's not the case either on the web. Scrolling Indicators are only showing up, when starting scrolling. Users could scrolled based on the indicator in the web.

**Comment by necolas** [comment]
Update to 0.13. If the issue still exists I will reopen

**Comment by mafiusu** [comment]
@necolas I ask you to open this issue again since I've encountered this problem with the recent version of React Native Web. My package.json lists RNWEB as follows:

react-native-web”: “~0.13.7"
