### ISSUE TITLE
[Q] Why TabBarIOS deprecated ?

### ISSUE THREAD

**Issue by fortezhuo** [necolas/react-native-web#1659]
TabBar IOS https://reactnative.dev/docs/tabbarios-item still exist on React Native documentation. And please inform what alternative package for TabBar IOS ?

Package  : RNW 0.13.1

**Comment by necolas** [comment]
It was removed a long time ago and only ever worked for the iOS platform. https://github.com/facebook/react-native/commit/02697291ff41ddfac5b85d886e9cafa0261c8b98
