### ISSUE TITLE
Is it possible to add onLayout to unstable_createElement elements?

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#1660]
**Is your feature request related to a problem? Please describe.**

There is a component that I have to treat differently for web and native. I need a div on web, that I create with `require('react-native-web').unstable_createElement('div', props)` and populate with some svg string. My issue is that I need it to accept onLayout, and right now, I get `Unknown event handler property `onLayout`. It will be ignored.`

**Describe a solution you'd like**

I think that adding the hook useElementLayout in createElement file would do the trick, but I'm not 100% sure on how to do it correctly.

**Describe alternatives you've considered**

It could be cool to have a web support for SvgXml component from react-native-svg project.

**Additional context**

"react-native-web": "^0.12.2",
"react-native": "^0.62.2",

**Comment by necolas** [comment]
No I'm not going to add it to createElement, which isn't a React component and cannot internalize the use of a hook either. You can put svg string inside `View`

**Comment by Sharcoux** [comment]
Ok, then I have another proposal to handle svg in a common way for RN and RNWeb (which I think is a problem that I'm not the only one to try to solve).

Here is my draft PR on react-native-svg: https://github.com/react-native-community/react-native-svg/pull/1414/files

I took more or less the code of your View to try to create an SVG component, but I'm not sure if this is an acceptable approach.

I don't want to put the svg string within a View because I don't know how I should separate the style received as props between the View wrapper and the svg string, nor that I can easily apply a RN style to an html svg tag.

**Comment by drpiou** [comment]
Why is this closed? Just by using a FlatList on web produce this error on my end.
