### ISSUE TITLE
TouchableOpacity: opacity related bugs

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#167]
There are a few opacity-related bugs in the RN repo. Disabled opacity styles in a composite component don't seem to get applied to TouchableOpacity. Upstream some of Twitter's button examples to the RN for Web storybook.

**Comment by giuseppeg** [comment]
I noticed that disabled TouchableOpacity elements are also focusable and don't have `aria-disabled="true"`. In general they are only visually disabled I think but the cbs will still fire right?

**Comment by necolas** [comment]
I can't reproduce either of these issues (original report is not that clear though)
