### ISSUE TITLE
Image component useEffect bug

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#1672]
I just got:

```
react-dom.development.js:88 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Image (at TopBar.tsx:61)
````

There must be some not canceled async action in `useEffect`. Looking at the source code, it's probably `ImageLoader.load` callbacks. 

There are two solutions. Cancel ImageLoader in useEffect return functions, or add ref to bypass setState.

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by necolas** [comment]
Will be closing this unless you fill out the issue template as required. Please take the time to do so

**Comment by steida** [comment]
Simple use case works, so maybe it was related to Fast Refresh... Closing for now.

https://codesandbox.io/s/bold-feather-10moq?file=/src/App.js

**Comment by markymc** [comment]
Just a note that I was also seeing this when running a dev build, but it's not showing on my production builds.

**Comment by steida** [comment]
It still happens but not always so it seems it's some race condition probably related to Next.js Fast Refresh, but I am not sure because it's not possible to disable it.

@markymc That warning is never shown on production.
