### ISSUE TITLE
Focus on TextInput when is focused

### ISSUE THREAD

**Issue by hosseinmd** [necolas/react-native-web#1673]
**The problem**
On react-native when calling the focus of a textInput which is focused onFocus doesn't invoke. But in react-native-web onFocus invoked

**Expected behavior**
Expected when textInput is focused onFocus doesn't invoke

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.12
* React (version): 16.13
* Browser: chrome

**Comment by necolas** [comment]
Cannot reproduce in a sandbox with 0.13. Next time please include a codesandbox test case

**Comment by hosseinmd** [comment]
I have an example, please look at that.
https://codesandbox.io/s/strange-cache-jpjz0?file=/src/App.js

**Comment by necolas** [comment]
Pressing the button first blurs the text input before you imperatively shift focus back to the text input. This is expected behavior

**Comment by hosseinmd** [comment]
Excuse me, I forgot keyboardShouldPersistTaps="handled" property of ScrollView. I updated example that work on native, but on the web that do not behave like native and exactly what you said happening.

**Comment by necolas** [comment]
That behavior doesn't exist on the web platform
