### ISSUE TITLE
How to handle mouse events

### ISSUE THREAD

**Issue by chrisdrackett** [necolas/react-native-web#1674]
pre 0.13 I had button components that used `onMouseEnter` and `onMouseLeave` on a `TouchableWithoutFeedback` to handle hover styles. This no longer seems to work and I'm curious the best way to handle these mouse events

**Comment by chrisdrackett** [comment]
I was able to fix this by using a `TouchableOpacity` and setting `activeOpacity` to `1`. I am curious why `TouchableOpacity` passes props down to the DOM while `TouchableWithoutFeedback` does not

**Comment by necolas** [comment]
TouchableWithoutFeedback doesn't render its own DOM node so you can just set your mouse event handlers on its child
