### ISSUE TITLE
Animated.Value setValue not updating bound components styles when called inside panResponder

### ISSUE THREAD

**Issue by IgorCRD** [necolas/react-native-web#1677]
Hey, @necolas
Thanks for the all the work you have dedicated to this project. I really appreciate it.

**The problem**
When using panResponder to set new values to an Animated.Value the value seems to be updated, but components styles bound to this Animated.Value are not updated.

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1. Try the code of this snack with react-native-web 0.13 version: 
https://snack.expo.io/@igorcrd/76c2ee?session_id=snack-session-t9deY9FRl&preview=true&platform=web&iframeId=wzqk84dhs6&supportedPlatforms=ios,android,web&name=PanResponder&description=Example%20usage&waitForData=true

**Expected behavior**
It should work the same as on the linked snack.

**Environment (include versions). Did this work in previous versions?**
Sorry, I didn't test on previous versions, but I think it used to work because it works on the linked snack and it probably uses a version older than the 0.13 version.

* React Native for Web (version): 0.13
* React (version): 16.11.0
* Browser: Chrome 83

**Comment by necolas** [comment]
Looks the same to me: https://codesandbox.io/s/jovial-dubinsky-pkelj

**Comment by IgorCRD** [comment]
@necolas,
Sorry, I guess I might have done something wrong in my tests.

I isolated the actual use case where I am facing this problem on a codesandbox and created a gif of how the same component is running on native.

Here is the Codesandbox. Relevant files are ./App.js and ./Tabs/index.tsx
https://codesandbox.io/s/zealous-mclaren-rpx6e

I am using panResponder to implement tabs switching based on gestures. That's how I intended it to work:
- fast swipe go to next tab;
- slow swipe go to next tab if the panel was dragged past the half of the container width;
- any horizontal swipe should animate the panel to give feedback.

It is working as intended on native, but not on web.

Tabs component running on chrome (on the left) and iOS simulator (on the right).
![tabs](https://user-images.githubusercontent.com/32890840/87961540-34e6e200-ca8c-11ea-9f3e-3801c45461b7.gif)

Please consider reopenning the issue.

**Comment by necolas** [comment]
The behavior seems to be the same as in 0.12. I noticed that your demo fills the console full of React Dev Tools error messages. If you can revisit your demo to avoid the errors and remove the unrelated code, that would help as I don't have much time to investigate for you

**Comment by IgorCRD** [comment]
After reducing the demo I think I have found the cause of the problem.

On iOS the AnimatedValue.setOffset API accepts not only a primitive number, it can also be used with an AnimatedValue as the argument, but doing so breaks android and fails to animate on web. That was causing the difference in behavior between native iOS and web. So react-native-web is working as expected and you can keep this issue closed.

Thanks again and I am sorry for the confusion.

**Comment by necolas** [comment]
No worries. Thank you for continuing to investigate and finding the source of the problem. It might be worth raising this difference between ios and android/web as an issue in the react native repo
