### ISSUE TITLE
Conditionally rendering apps based on Screen Sizes 

### ISSUE THREAD

**Issue by rhaegar453** [necolas/react-native-web#1678]
**Is your feature request related to a problem? Please describe.**
Hello, I'm planning to use React Native web for my next project. I have an application that needs to render a mobile version of the application when using mobile devices and the web version (Written in React ) when using Tablets and Desktops. How do I achieve this with React-Native-Web?

**Describe a solution you'd like**
I'm Hosting the application on Netlify and using Lambda as the backend. How do I conditionally render the Mobile Version (React-Native-Web) and the Web Version (React) based on the device the user is using?
Thank you in advance

**Describe alternatives you've considered**
I've considered Media Queries in the past for creating responsive web apps, but with React Native web I think I can achieve a lot more than that. 

**Additional context**

**Comment by necolas** [comment]
Hi. You can ask development questions about user agent detection on stackoverflow or perhaps the React community forums listed on the react site

**Comment by steida** [comment]
@rhaegar453 Try https://github.com/artsy/fresnel

**Comment by rhaegar453** [comment]
Excellent @steida , but will this setup work if i'm hosting the application on a serverless platform like Netlify? Or will I have to host it on a server?

**Comment by steida** [comment]
Should work.
