### ISSUE TITLE
Storybook: make examples look nice

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#168]
I'm sure we can prevent the functionality of the framework in a more visually pleasant form than the initial RN examples :)

**Comment by necolas** [comment]
Hey @arunoda, any advice on how to customize things like the "React Storybook" text and hiding the action logger by default? Should I really be using storybook-ui rather than react-storybook?

**Comment by arunoda** [comment]
@necolas check this: https://github.com/storybooks/storybook-addon-options

**Comment by necolas** [comment]
Thanks. What about changing the layout? For example: I want to get rid of all the chrome around the stories, create a header, and toggle the visibility of the left panel (i.e., make it a toggle-menu on mobile and always display it on wider screens)

**Comment by arunoda** [comment]
We don't have direct way to deal with that.
But I assume, you could do some webpack alias to hijack our UI. But I didn't tried that.

**Comment by necolas** [comment]
Oh, is there a plan to support theming/white-labelling? In particular the default UI isn't mobile friendly

**Comment by arunoda** [comment]
Yep. We have.
Need to prioritise it.

**Comment by LinuCC** [comment]
Hey @necolas your [Storybook](https://necolas.github.io/react-native-web/storybook/) page does not use the code thats in the `master` (or any branch of that matter?) of this repo.
Would be nice if you would update it since your Storybook-setup is quite awesome now :)

**Comment by necolas** [comment]
Still working on it. Currently planning to remove storybook and build my own app that works on mobile

**Comment by necolas** [comment]
Moving into #491
