### ISSUE TITLE
Function to create React Native elements that rely on HTML tag

### ISSUE THREAD

**Issue by MatheusrdSantos** [necolas/react-native-web#1681]
**Is your feature request related to a problem? Please describe.**

I need to add support for the SvgXml component (from react-native-svg) for web.
**Describe a solution you'd like**

I would like to have a function like createElement that creates a ReactNative element that relies on any HTML tag. The created element must support methods like onLayout, onClick, onMouseEnter... and props like ref, style, width, height...
The methods and props the element supports may be customizable.
**Describe alternatives you've considered**

I considered implementing the SvgXml component the same way you implement the View component, but instead of relying on div, it relies on svg tag.
I might need to handle more components, so it would be good to make this process easier by creating a function like createElement that allows this kind of behavior.
**Additional context**

I wrote an initial code here: e87dda8e6d236770b0e56d1791808e3befd70684
This issue is related to #1660

**Comment by necolas** [comment]
I've already answered this request before and won't be adding another API. You can build your own thing on top of createElement already but I don't think it's necessary for the svg use case anyway
