### ISSUE TITLE
[Feature Request] add support for onTextLayout props of Text component

### ISSUE THREAD

**Issue by KingAmo** [necolas/react-native-web#1685]
**Is your feature request related to a problem? Please describe.**

see https://reactnative.dev/docs/text.html#ontextlayout
related issue  #889

**Describe a solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by necolas** [comment]
I don't think this information can be practically provided on web. I don't plan to add this prop

**Comment by Bbbtt04** [comment]
> I don't think this information can be practically provided on web. I don't plan to add this prop
why you think that？I think this prop is useful because I have encountered this situation in my business。
