### ISSUE TITLE
Text metrics do not match React Native at smaller line heights

### ISSUE THREAD

**Issue by andymatuschak** [necolas/react-native-web#1687]
**The problem**
react-native-web's implementation of `<Text>` positions text differently within the element's bounding box than react-native's implementation of `<Text>` (either iOS or Android). This issue reproduces across a variety of fonts.

Interestingly, the two implementations appear to render the same when the `lineHeight` is large enough—e.g. above around a `lineHeight` of 45px for 40px Helvetica. Perhaps this is the ascender height? The font's bounding box height? I'm not sure.  The issue also does not appear to manifest when `lineHeight` is unset—i.e. with the default `lineHeight`.

This issue makes it impossible to create a shared web/native implementation which aligns to the same grid.

**How to reproduce**

This test case displays the issue: https://codesandbox.io/s/affectionate-ishizaka-ylnhx?file=/src/App.js
Here's an Expo Snack link to easily view the same test case on device: https://snack.expo.io/W51F2OAqD

This image compares the renderings:
![image](https://user-images.githubusercontent.com/2771/88594928-f9fa2680-d016-11ea-8c1d-83558c92edb1.png)
**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.3
* React (version): 16.13.1
* Browser: Safari 13.1.1, Chrome 84.0.4147.89

The react-native Expo snack is using Expo 37, which corresponds to react-native 0.61.

---

Arguably, the r-n-w behavior is more reasonable than the r-n behavior, since it distributes the lost line height evenly above and below the cap height, while r-n appears to take it from the top only. I don't really care which behavior is chosen (I'll need to add manual offsets specific to each font's metric)—I just care that they're the same! :)

I worry that fixing this issue will create subtle and surprising source compatibility issues for existing r-n-w clients.

**Comment by necolas** [comment]
> Arguably, the r-n-w behavior is more reasonable than the r-n behavior

Yep. This is the native behavior on web. I don't plan to add hacks to get it looking like RN when RN's rendering is worse. Maybe something to bring up in the RN repo as they might be able to adjust the algorithm.

**Comment by andymatuschak** [comment]
Got it. I'll file an issue there and reference this one for interested viewers.

I'd be happy to write a documentation PR in the meantime. Is there a place where you're collecting rendering gotchas between r-n-w and r-n? Looking through the docs, I'm not seeing a spot that looks quite right to mention this—perhaps http://necolas.github.io/react-native-web/docs/?path=/docs/guides-style--page?

**Comment by necolas** [comment]
>  Is there a place where you're collecting rendering gotchas

There isn't. And I don't think RN has one for differences between iOS/Android/Window/macOS either
