### ISSUE TITLE
TouchableWithoutFeedback does not work in combination with href

### ISSUE THREAD

**Issue by RichardLindhout** [necolas/react-native-web#1692]
**The problem**
React Native Paper uses the TouchableWithoutFeedback for their buttons. I want this button te be a link because I render the app also on the server side with Next.js.

To optimize SEO I want my buttons to be links on the web but the TouchableWithoutFeedback does not support the href prop

**How to reproduce**
https://codesandbox.io/s/serene-bose-1nkon?file=/src/App.js

**Expected behavior**
I expect the 'href' prop to work on all button types in react native

* React Native for Web (version): 0.13.5
* React (version): 16.13.1
* Browser: Google Chrome

**Comment by RichardLindhout** [comment]
I think this is broader like I think it should be supported to make buttons links in background. Maybe also accessibility things need to focusable e.g. when a href is provided.

**Comment by necolas** [comment]
`TouchableWithoutFeedback` is only a component wrapper that applies press behavior to the child. The rest of the props should be set on the child itself.
