### ISSUE TITLE
Horizontal ScrollViews don't animate on ScrollTo calls in Safari + mobile 

### ISSUE THREAD

**Issue by rcmarron** [necolas/react-native-web#1696]
**The problem**
Horizontal ScrollViews don't animate when the `scrollTo` method is called with `animated` set to `true`. I can consistently reproduce this on Safari and iPhone and have heard reports of it happening on Android, but I don't have one to test with.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/nervous-jennings-5uc12

Steps to reproduce:
1. Open the link above in Safari
2. Click the "ScrollTo" button
3. Notice the list jumps instead of animating to its new position

**Expected behavior**
The expected behavior is that the list would animate to its new position instead of jumping.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.5
* React (version): 16.13.1
* Browser: Safari Version 13.1.1 (15609.2.9.1.2)

This hasn't worked in previous versions (at least since 0.11.7)

**Comment by necolas** [comment]
That's because Safari doesn't natively support smooth scrolling yet - https://caniuse.com/#search=scroll%20behavior

**Comment by nandorojo** [comment]
I fixed it with this [polyfill](https://github.com/iamdustan/smoothscroll).

```sh
yarn add smoothscroll-polyfill
```

```js
// App.js
if (typeof window !== 'undefined') {
  require('smoothscroll-polyfill').polyfill()
}
```
