### ISSUE TITLE
Adjacent panResponders intercept gesture on overlap

### ISSUE THREAD

**Issue by r-bman** [necolas/react-native-web#1697]
**The problem**
When dragging an element with a panResponder over another adjacent panResponder element, the gesture is intercepted by the other panResponder.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/affectionate-antonelli-gwgec

Steps to reproduce:
1. Click and drag one box over another
2. Repeat
3. Change `react-native-web` version to < 0.13 and retry - you will see that this was not an issue previously

**Expected behavior**
The box you started the gesture on should continue to move uninterrupted until you release.

Works as expected on iOS & Android: https://snack.expo.io/SGEXmrVyL

**Environment**

* React Native for Web (version):0.13.5 (worked in versions < 0.13)
* React (version): 16.13.1
* Browser: Firefox 79.0, Chrome 84.0.4147.125 (64-bit), Safari 12.1.1

**Comment by necolas** [comment]
This was fixed in master an hour ago :) https://github.com/necolas/react-native-web/commit/3233d0ffe99a568de3b76272926c7083e083f83e

Try 0.13.6 - https://codesandbox.io/s/quizzical-bassi-m7gbf

**Comment by r-bman** [comment]
Great, thanks a lot!
