### ISSUE TITLE
React Native Web: After ejecting web doesn’t work

### ISSUE THREAD

**Issue by fullhdpixel** [necolas/react-native-web#1700]
I’ve just tried to eject my RN expo app, because I want to add in app payments for android and iOS. However, the app crashes on web giving the following error:

> funcError: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of ExpoRootComponent. “registerRootComponent.web”

SDK version: 38
Platforms: All

So, in the managed workflow the web version works fine, but not in the bare workflow. Steps to reproduce:

Create new app
Add react-native-web
Eject to bare workflow
Try to start app

**Comment by necolas** [comment]
Open an issue against expo
