### ISSUE TITLE
Dead keys are not handled correctly on onKeyPress event on TextInput.

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#1701]
**The problem**

Pressing a Dead key in a TextInput doesn't trigger the event normally triggered by event listeners on web. It shows 'Unidentified' instead.
Worst, after a dead key, the next event fired is still 'Unidentified' instead of being the character to be printed. For instance, ^e will give 'Unidentified' 'Unidentified'.
This prevents me to treat the event correctly and to handle this kind of keys.

**How to reproduce**

Simplified test case: 

[Sandbox](https://codesandbox.io/s/react-native-web-onkeypress-events-2d3xp?file=/src/App.js)

Steps to reproduce:
1.Create a TextInput with an event listener on onKeyPress
2.Give it the focus
3.Press a dead key (^, `, ~)

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.4
* React (version): 16.13.1
* Browser: 81.0.4044.138

**Comment by necolas** [comment]
I can't reproduce the issue

![image](https://user-images.githubusercontent.com/239676/90061203-aafcf400-dc9a-11ea-8bdd-e7de6fe114b9.png)

![image](https://user-images.githubusercontent.com/239676/90061475-08914080-dc9b-11ea-8fb3-640eeebed1c7.png)

**Comment by Sharcoux** [comment]
![image](https://user-images.githubusercontent.com/797545/90062423-f4bffb80-dce7-11ea-8d96-feed3597413e.png)

:/

**Comment by Sharcoux** [comment]
Might be an issue with keyboard layouts. I'm using Azerty keyboard...

**Comment by necolas** [comment]
It's just using the ReactDOM `onKeyDown` event. Maybe see if the problem exists for you with the ReactDOM `input`

**Comment by Sharcoux** [comment]
Indeed... Then that becomes evn worst for my case :/

Thanks.

**Comment by necolas** [comment]
Definitely open an issue against ReactDOM if that is the source of the problem. And good news is a future version of RNWeb will probably use native events instead of ReactDOM

**Comment by Sharcoux** [comment]
That's really good news. Any timeframe for the upgrade?

**Comment by necolas** [comment]
Probably not for a while but if ReactDOM can't fix this promptly maybe just TextInput can switch to native events first

**Comment by Sharcoux** [comment]
We are making a complex app in full RN + RNWeb and trying to fill the gap between mobile and web.
We brought CSS units with https://github.com/Sharcoux/rn-css
A slider (as react-native-slider was mobile only. I did the web implementation for them, but the current project is shitty) : https://github.com/Sharcoux/slider
A range slider
And, as you saw, we are trying to find a solution to have a bridge for svg (and some other html elements)

**Comment by Sharcoux** [comment]
So, thanks for your work ;)

**Comment by Sharcoux** [comment]
I could fix my use case with a combination of onKeyDown and onChange. Thanks for your help.
