### ISSUE TITLE
 Abnormal scrolling experience when use Touchable in ScrollView

### ISSUE THREAD

**Issue by farawaaay** [necolas/react-native-web#1702]
**The problem**

Abnormal scrolling experience when use Touchable in ScrollView.

**How to reproduce**

Simplified test case: 

https://snack.expo.io/yKMUhXT!4

```jsx

import React, { Component } from 'react';
import { View, ScrollView, Button } from 'react-native';

class App extends Component {

  render() {
    const style = { color: 'white', height: 100, width: 200 }
    return (
      <View style={{ backgroundColor: "black" }}>
        <ScrollView horizontal={true}>
          {
            new Array(10).fill(0).map((_, i) => {
              if (i%2===0) {
                return <Button style={style} title={`TestButton${i}`} />
              } else {
                return <button>TestButton{i}</button>
              }
            })
          }
        </ScrollView>
      </View>
    );
  }
}

export default App;


```

Steps to reproduce:
1. Open this snack on any mobile iPhone device: https://snack.expo.io/yKMUhXT!4
2. Use web as target
3. Scroll the scrollview with your finger on a `<Button/>`

**Expected behavior**

scrolling experience while my finger is on `<Button />` should be as same as when my finger is on html standard `<button />`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): maybe latest, using Expo snack
* React (version):  maybe latest, using Expo snack
* Browser: Safari on iPhone iOS 13.6.0

**Comment by necolas** [comment]
You should actually explain the bug and expected behavior in issues. But whatever this is, is probably fixed in the latest version, which is not yet used by expo
