### ISSUE TITLE
Hover support in Pressable

### ISSUE THREAD

**Issue by RichardLindhout** [necolas/react-native-web#1708]
**Is your feature request related to a problem? Please describe.**

I would like it to make the hover status part of react-native-web since it's an important interaction of the web UX.

e.g.

```jsx
<Pressable
        onPress={() => {
          setTimesPressed((current) => current + 1);
        }}
        style={({ pressed, hovered, focused }) => [
          {
            backgroundColor: pressed
              ? 'rgb(210, 230, 255)'
              : 'white'
          },
          styles.wrapperCustom
        ]}>
        {({ pressed, hovered, focused }) => (
          <Text style={styles.text}>
            {pressed ? 'Pressed!' : 'Press Me'}
          </Text>
        )}
      </Pressable>
```

**Describe a solution you'd like**

> To address these problems, we are shipping a new core component called Pressable. This component can be used to detect various types of interactions. The API was designed to provide direct access to the current state of interaction without having to maintain state manually in a parent component. **It was also designed to enable platforms to extend it's capabilities to include hover**, blur, focus, and more. We expect that most people will build and share components utilizing Pressable under the hood instead of relying on the default experience of something like TouchableOpacity.

https://reactnative.dev/blog/2020/07/06/version-0.63

**Additional context**

**Comment by hosseinmd** [comment]
Awesome feature.  We enable Managing to hover easily if this is available.

**Comment by necolas** [comment]
Yeah I worked on this API at FB, but the hover implementation I originally wrote for `Pressable` isn't as good as the one I've subsequently written for another framework. So I need to take a bit of time to port it over here and reorganize this project to accommodate it first.

**Comment by RichardLindhout** [comment]
Would you accept a PR in the meantime which creates the hovered state with the onMouseIn onMouseOut the same way the focus is handled at the moment?


https://github.com/necolas/react-native-web/blob/cfe36d780e981885ce73862a9effcea29e7ea1c9/packages/react-native-web/src/exports/Pressable/index.js#L139

E.g. createHoverHandler

```
   onMouseIn={createHoverHandler(onMouseIn, true)}
   onMouseOut={createHoverHandler(onMouseOut, false)}
```

**Comment by necolas** [comment]
No, because the behavior would be incorrect

**Comment by RichardLindhout** [comment]
Ah, when would this incorrect behaviour trigger?

**Comment by necolas** [comment]
Any time a touch interaction occurs or a pressable is nested

**Comment by RichardLindhout** [comment]
Ah indeed maybe we could add some kind of tag to the event that it is being handled by the hover but that would be much more complicated that I would have imagined 😅.

**Comment by nandorojo** [comment]
> the hover implementation I originally wrote for Pressable isn't as good as the one I've subsequently written for another framework. 

@necolas is the implementation you made for another framework open source by chance? I know it'll take a while to organize and add it to this library, so I figured I'd ask in the meantime. Thanks for the great work.

**Comment by RichardLindhout** [comment]
Maybe we can create a small library in the meantime which wraps react-native-web Pressable and scrollviews with hover support 

E.g.

import { ScrollView, Pressable } from 'react-native-web-with-hover'

**Comment by RichardLindhout** [comment]
Here is a small demo
https://codesandbox.io/s/young-surf-bbmzz?file=/src/App.tsx

```jsx
import { Pressable, ScrollView } from "./react-native-web-with-hover";
.....

    <Pressable
      style={({ hovered, focused, pressed }) => [
        styles.buttonRoot,
        hovered && styles.buttonHovered,
        focused && styles.buttonFocused,
        pressed && styles.buttonPressed
      ]}
    >
      {({ hovered, focused, pressed }) => (
        <View style={styles.buttonInner}>
          <Text style={styles.buttonLabel} pointerEvents="none">
            {label}
          </Text>
        </View>
      )}
    </Pressable>
```

**Comment by RichardLindhout** [comment]
Update: I've created a library to support hovering with react-native-web

**Comment by necolas** [comment]
I already pointed out the problems with that implementation. And I'd rather people didn't use this project's issue tracker to promote their packages. Thanks

**Comment by RichardLindhout** [comment]
The issues you pointed out are fixed with in the library.

```javascript
document.ontouchstart = unhover;
document.ontouchend = unhover;
document.ontouchcancel = unhover;
document.ontouchmove = unhover;
```

I would rather not have this package too, but it is a temporary workaround for some people who need this feature. I'm sorry if you feel that way. I just wanted to help you and I like this package very much!

**Comment by necolas** [comment]
Hover will be added in 0.14 which can be tested by installing the `@canary` version

**Comment by RichardLindhout** [comment]
Amazing work <3! I will deprecate the library

**Comment by Seanmclem** [comment]
> Hover will be added in 0.14 which can be tested by installing the `@canary` version

How can I achieve the same thing in non-web? I'd like to replicate the same behavior in both places, but I'm clearly missing some key words in my Google searches.

**Comment by RichardLindhout** [comment]
What platforms are you referring to? React Native still needs to implement this on iOS.
https://react-native.canny.io/feature-requests/p/ios-pointer-support

The macOS, Windows needs to add this too to the Pressable component. I think you need to make an issue on those platforms.
I think react-native-web is the only wants to support this at the moment.

**Comment by Seanmclem** [comment]
> What platforms are you referring to? React Native still needs to implement this on iOS.
> https://react-native.canny.io/feature-requests/p/ios-pointer-support
> 
> The macOS, Windows needs to add this too to the Pressable component. I think you need to make an issue on those platforms.
> I think react-native-web is the only wants to support this at the moment.

It just seems iOS/Android at least, don't have any kind of hover. I'm using pan responder for dragging but there seems to be no way to detect what you're dropping on to without comparing the positions of every component

**Comment by rodrigojcmello** [comment]
TypeScript typing still doesn't recognize "hovered", would it be necessary to open an issue in the @type/react-native project?

**Comment by hosseinmd** [comment]
> TypeScript typing still doesn't recognize "hovered", would it be necessary to open an issue in the @type/react-native project?

I think that would be great.
If they are not ok with this, we can create another type definitions module which expands @type/react-native for the web too.

**Comment by nandorojo** [comment]
@rodrigojcmello There's discussion about this on #1684, you can see [my comment](https://github.com/necolas/react-native-web/issues/1684#issuecomment-712297248) there.

**Comment by Smtih** [comment]
This is a pretty lightweight setup to make Typescript happy

`
export type PressableState = Readonly<{
  pressed: boolean;
  hovered?: boolean;
  focused?: boolean;
}>;


<Pressable>
      {({ pressed, hovered, focused }: PressableState): ReactElement => {
            return <Button color={pressed ? "black" : focused ? "gray" : hovered ? "light gray" : "white" />
      }
</Pressable>
`
By explicitly defining the input type of the function this way, it still makes sense to pass it to Pressable which expects a function with an input of `Readonly<{ pressed: boolean }>` and inside the function you can just treat the values as truthy or falsy.
Also if you're building tri-platform, these values actually will be undefined on mobile so the type is robust to this.

**Comment by haveamission** [comment]
One thing I am noticing is that when I have an <Image /> component inside of a <Pressable /> component, hovering doesn't seem to affect the color.

I can get a hover overlay to work, but that's about it
