### ISSUE TITLE
The Component Image request resource three times  

### ISSUE THREAD

**Issue by wkeylin** [necolas/react-native-web#1711]
**The problem**  

The Component Image request resource three times  

**How to reproduce**  

Disable cache  

```
const WrapImage = () => {
  return (
    <Image
      accessibilityLabel="React logo"
      source={{ uri: logoUri }}
      resizeMode="contain"
      style={styles.logo}
    />
  );
};

class App extends Component {
  render() {
    return (
      <View style={styles.app}>
        <View style={styles.header}>
          <WrapImage />
          <Text style={styles.title}>React Native for Web</Text>
        </View>
        <Text style={styles.text}>
          This is an example of an app built with{" "}
          <Link href="https://github.com/facebook/create-react-app">
            Create React App
          </Link>{" "}
          and{" "}
          <Link href="https://github.com/necolas/react-native-web">
            React Native for Web
          </Link>
        </Text>
        <Text style={styles.text}>
          To get started, edit{" "}
          <Link href="https://codesandbox.io/s/q4qymyp2l6/" style={styles.code}>
            src/App.js
          </Link>
          .
        </Text>
        <Button onPress={() => {}} title="Example button" />
      </View>
    );
  }
}
```
Simplified test case: https://codesandbox.io/s/suspicious-smoke-4ozpy?file=/src/App.js

**Expected behavior**  

The Component Image request resource once  

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.8
* React (version): 16.13.1
* Browser: Safari 13.1.2 (15609.3.5.1.3)

**Comment by wkeylin** [comment]
> Disable which cache? Please make a bit more effort to describe the issue and produce a useful test case
@necolas  Disable the safari cache
Steps to reproduce:  
1. download <https://codesandbox.io/s/suspicious-smoke-4ozpy?file=/src/App.js>
2. start and open on safari which is disabled cache
3. show develop web inspector, you can see this problem on Network

**Comment by necolas** [comment]
Cannot reproduce / not enough info to reproduce
