### ISSUE TITLE
Characters in nested Text seem to behave differently between native and web

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#1714]
**The problem**

If you split a word into letters like that: `word.split().map(letter => <Text>{letter}</Text>)` you will get a different behavior between native and web when you reach the end of the line. On web, the words will wrap anywhere. On mobile, the wrap will occur only on beginning or end of words.

**How to reproduce**

[Simplified test case](https://snack.expo.io/@sharcoux/f6feef) 

```javascript
import React from 'react';
import { Text } from 'react-native';

export default function App() {
  const text = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?";
  const words = text.split(/\b/);
  const children = words.map((word) => <Text>{word}</Text>);
  return <Text>{children}</Text>;
}
```

Steps to reproduce:
1. Create nested Text with a text long enough to wrap
2. See that the text wraps anywhere

**Expected behavior**

The web version should behave the same as mobile version as much as possible

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.4
* React (version): 16.13.1
* Browser: Chrome Version 81.0.4044.138 (Build officiel) (64 bits)

I could solve my use case by wrapping the words in a Text and adding `whitespace: 'nowrap'` to it. I'm just referencing the issue as it might be symptomatic of something that could bring more issues.

**Comment by necolas** [comment]
Pictures please

**Comment by Sharcoux** [comment]
Web:

![image](https://user-images.githubusercontent.com/797545/91031872-7295d800-e601-11ea-904f-e11ddf255970.png)

Android:

![image](https://user-images.githubusercontent.com/797545/91032246-f8b21e80-e601-11ea-9377-077d514c8876.png)

iOS:

![image](https://user-images.githubusercontent.com/797545/91032604-76762a00-e602-11ea-9dae-553f6d988bd5.png)

Check the word "voluptatem" for both mobile and web for instance (first line)

**Comment by necolas** [comment]
Looks like this is caused by the `dir="auto"` attribute. I think what I could do is only set that to `auto` by default on the root text element, and all the nested ones will not have `dir` set unless it is explicitly set by the developer.
