### ISSUE TITLE
iOS Safari issue with touch event

### ISSUE THREAD

**Issue by jeromeheissler** [necolas/react-native-web#1716]
**The problem**
I would like to use the library https://github.com/mohebifar/react-native-easy-dnd/ but with safari on ios i can't drag element because the event cause an error.

**How to reproduce**
Here a sample code that not work on safari
https://codesandbox.io/s/muddy-browser-4l2gg

Steps to reproduce:
1. Drag the red square

**Expected behavior**
This error will print to the console : 
```
TypeError: undefined is not an object (evaluating 'oneTouchData.touchActive')
centroidDimension — index.js:12
onResponderGrant — index.js:90
attemptTransfer — ResponderSystem.js:221
eventListener — ResponderSystem.js:106
19centroidDimension — index.js:12
```

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.3
* React (version): 16.13.1
* Browser: safari iOS 13.6

**Comment by necolas** [comment]
Please give version `0.0.0-da3429ed3` a try. I tried it out in the simulator and the error is resolved, but you should test it in your environment.

**Comment by jeromeheissler** [comment]
It works with version `0.0.0-da3429ed3`

**Comment by benceg** [comment]
Thank you @necolas!
