### ISSUE TITLE
Is it possible for react-native-web to import *.web.js if one exists (to allow use alongside native modules)

### ISSUE THREAD

**Issue by mmmurf** [necolas/react-native-web#172]
I'd like to do the following and wondering if it's possible:

// create files
Foo.ios.js
Foo.android.js
Foo.web.js

import Foo from 'foo';

**Comment by RangerMauve** [comment]
That might be more of a question for the React-Native folks since they're the ones that make the tools

**Comment by RangerMauve** [comment]
The current packager code is here: https://github.com/facebook/react-native/tree/master/packager
You might be able to just add the change and submit a PR

**Comment by necolas** [comment]
Yeah, webpack should load `*.web.js` files by default. So if you're using that you build your web entry, it should work.

**Comment by sportfort** [comment]
@necolas should it work for Typescript (*.web.ts and *.web.tsx)?
Where I can find a way to configure this? Thank you!

**Comment by priya-unacademy** [comment]
But this doesn't seem to work with server side code. Everything is taken to the default .js files. Any help ??
