### ISSUE TITLE
Outline prop on input is complained about on RN

### ISSUE THREAD

**Issue by vongohren** [necolas/react-native-web#1720]
**The problem**

Using TextInput with styled.native emotion is a great thing.  We have transpiled react native web through emotion so we get the features provided here.
But when we add outline: none to our component to avoid web outline, RN complains.
https://github.com/necolas/react-native-web/issues/48 I see here that it has been dicussed before, but removed again?

What is suggested approach.

**How to reproduce**
Transpile react-native through react-native-web
```
 rollup(config, options) {
    config.plugins = [
      alias({
        entries: [
          { find: 'react-native', replacement: 'react-native-web' },
        ],
      }),

```

Add emotion/native to the app.
Render this component
```
const Input = styled.TextInput`
  font-family: '${mainTheme.defaultFont}';
  color: ${globalColors.black};
  font-size: 16px;
  flex: 1;
  outline: none;
`
```

**Expected behavior**
No warning like this
<img width="314" alt="Screenshot 2020-08-28 at 16 08 24" src="https://user-images.githubusercontent.com/1012055/91577937-c1b57300-e949-11ea-8202-8ccb58f5ceb9.png">

**Environment (include versions). Did this work in previous versions?**
Never tested if worked before

* React Native for Web (version): 0.12.2
* React (version): 16.12.0

**Comment by necolas** [comment]
That style property is not supported in React Native. You can avoid setting on native it using a `Platform.OS` check on the style. I'd also recommend against using another styling library like emotion, as you are essentially paying the cost of a CSS-in-JS lib twice.

**Comment by vongohren** [comment]
@necolas thanks for the heads up, and will bring it along.
But yeah what is the biggest downers, because using it has given us a very nice structure and development flow.
Some strangeness but not very often. I guess the strangeness comes from the cost you are talking about

**Comment by lmxcraft** [comment]
@vongohren this works for me, nevertheless React Native Web should have a real solution for these kind of exceptions. I recommend you to put this code in a component that renders only once.
``      <SafeAreaProvider>
        {Platform.OS === "web" && (
          <style>
            {`
              input {
                  outline: none;
              }`}
          </style>
        )}
        <Navigation colorScheme={colorScheme} />
        <StatusBar />
      </SafeAreaProvider>``

**Comment by vongohren** [comment]
Thanks @lmxcraft !
