### ISSUE TITLE
Custom image to have backgroundSize, backgroundRepeat and backgroundPosition 

### ISSUE THREAD

**Issue by Uysim** [necolas/react-native-web#1721]
**The problem**
I need view image to have css
```
  background-size: contain;
  background-repeat: repeat-x;
  background-position: 0px 0px;
```

I look at the source code. It seem to be impossible.

**Comment by necolas** [comment]
I don't know what you're asking. I'm going to close this as it doesn't follow the issue template

**Comment by JeSuisAlrick** [comment]
What he is trying to say is that there is no way to apply custom styles to the nested View you use for Image and BackgroundImage.

![image](https://user-images.githubusercontent.com/177066/107139348-5942c880-68cf-11eb-893a-258a51d7d0a4.png)

The only styles applied to the nested View are `styles.image` and some other styles, but there is no way to apply custom styles.
