### ISSUE TITLE
Question: RNW use-case?

### ISSUE THREAD

**Issue by Sleepful** [necolas/react-native-web#1727]
Hello, I was looking through react-native-web and it's a bit difficult for me to understand when to pick ReactJS, React Native, and React Native Web. To me it seems like RNW was built with the idea of sharing code with React Native code bases, that much makes sense. So my question is as follows, is there a use-case for RNW when there is no RN app?
I was wondering if there are more advantages to RNW than code-sharing, because perhaps it offers better support for the mobile experience of web apps. Usually making a web app "responsive" or "adaptive" is enough to have the mobile experience, but with "progressive" web apps there seems to be a bigger focus on making the experience like a native app, and this is where I was wondering if RNW would help. But to my understanding, RNW is going to have the same API in available in mobile devices as standard web apps. Thank you for your time n_n

**Comment by necolas** [comment]
Yes it can be used for web only apps too, like Twitter

**Comment by Sleepful** [comment]
yeah, but what advantages does it offer over using just reactjs?
