### ISSUE TITLE
Style Prop not being mapped properly

### ISSUE THREAD

**Issue by dustinsavery** [necolas/react-native-web#173]
Getting the following error when running `0.0.39`:

`Uncaught (in promise) Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX. This DOM node was rendered by <MODULE>`

Was there an update to the way that modules are being output? I can downgrade to `0.0.30` and it works just fine.

UPDATE: Have confirmed the breaking change started in `0.0.33`, which was a large stylesheet update. Still trying to trace it down.

**Comment by necolas** [comment]
What is the code in your app that produces the error? Sounds like you might be passing an invalid object to `StyleSheet.create`

**Comment by dustinsavery** [comment]
Unknown. Not enough debug information to trace it down. But again, all current code works in `0.0.32`. Only throws an error in `0.0.33` and above. Was there something that changed/updated with how you are exporting the styles?

**Comment by necolas** [comment]
Yes, it now mirrors React Native's API. You'll need to find the module that is referenced in the error and look at how you're adding styles. Without the code I can't really say much else. I don't think the issue in with this package so I'm going to close the issue until we know otherwise.

**Comment by dustinsavery** [comment]
Finally pinned down the problem node. It was a `div` using styles being output from a Stylesheet. This had been working previously and, at the time, we needed to use a div because we needed an `onClick` event, which RNW did not allow to be added to a `View`. It appears the onClick issue has been fixed at least, but not being able to attach styles to a div is a problem for us. Any ideas?

**Comment by dustinsavery** [comment]
Looks like we _might_ have a solution. If we bypass the `Stylesheet.create()` and just use a standard object, React and RNW are both satisfied and the styles are applied. Not sure this is the _best_ way, but it would appear that not using RNW Stylesheets still works, with no loss of functionality or features.

**Comment by necolas** [comment]
`View` includes support for `onClick` now. If you need to use a native element like `div` you can still use `StyleSheet` like this:

```js
const { className, style } = StyleSheet.resolve(this.props)
<div {...props} className={className} style={style} />
```

I've thought about exporting a dedicated web-specific function to do this without leaking the implementation details like `StyleSheet.resolve`. But at the moment, it is also currently designed as an internal implementation detail. Might look something like this

```js
createReactDOMElement('span', props)
```
