### ISSUE TITLE
This package is a mess to maintain

### ISSUE THREAD

**Issue by chadhobson** [necolas/react-native-web#1733]
**Is your feature request related to a problem? Please describe.**
I get the intention of following RN core religiously for purity sake but here in the real world, we're using hundreds of packages from thousands of maintainers who can't keep up at the same pace this project is currently moving. That puts the onus on the individual developer to go through patch-package hell to undo all the changes being made in this package while still picking up the new RN features.

**Describe a solution you'd like**
Deprecate for a few subversions? Back port new functionality to previous versions?  I'm stuck on a monkey patched 0.12.3 just to keep the web part of my app running. The last two versions of this package had MAJOR breaking changes. 0.12 was manageable to monkey patch but 0.13 is a bridge too far.

No offense - **_because I definitely appreciate the amount of work invested in this package_** - but are all the decisions being made by a single person? That's the only logical explanation because here in the real world there's no way I could convince a plurality of team members to introduce changes like these into our project and tell them to deal with it.

**Describe alternatives you've considered**
Jumping head first out my office window, may even leave the window down when I do it.

**Additional context**
PropTypes aren't removed from RN yet so why did whoever's maintaining this package say "Well they're going to be removed eventually, so let's just remove them now before Facebook even bothers with it (because FB knows its a HUGE deal, maybe?) and force everyone else that uses RNW to deal with it right now rather than maintain it for awhile and deprecate"... that's insane. 

The latest version doesn't forward component props anymore and instead takes the heavy handed approach of whitelisting props that get forwarded which - guess what - breaks other packages. Was this even up for discussion? If so, what kool aid was everyone drinking to think THAT was a good idea?

I can go through my patch files and add more but this is the gist. End rant. 

Thanks again for the contribution, RNW is great and, like I said, I respect and appreciate the contribution.

If at least 75% of the people who read this don't agree with me then I'll take that header out the window. I've amended my will to direct my estate to login and delete this upon my untimely demise.

**Comment by necolas** [comment]
This kind of comment is unhelpful and the tone is unacceptable. If there's any relevant information here it's lost in the rant and assumptions.

**Comment by chadhobson** [comment]
Seriously? Detailed feedback from someone who uses your package and finds faults with the direction is considered "unhelpful" and "unacceptable"? At least tell me what "assumptions" I'm making for dismissing it wholesale. I guess your reply has answered most of the questions I posed. Thanks for that, I guess.

**Comment by necolas** [comment]
Chad, your post is 95% rant and you expect me to take my time to parse what is relevant from it?

Each minor release has come with a lengthy period of canary testing that dozens of people and organization have contributed to. Their feedback was helpful and detailed. Your feedback is late, rude, and entitled. It's been well over a year since the major consumers of this package – e.g., Twitter, Facebook – migrated off PropTypes and the APIs that were deprecated in 0.11. There really aren't many "breaking changes" in 0.13, and most of them were made to unstable APIs.

And since you don't provide any information on what props you were relying on being forwarded but aren't in 0.13, why would you expect a helpful response? If you actually want help, or to provide constructive feedback, please reassess how you're going about doing it.

**Comment by chadhobson** [comment]
95% is a bit dramatic, no? In fact, I doubt you'll ever get more effusive constructive criticism and input in your career, so please spare me the theatrics and grow a sense of humor.

For the record, I've seen your responses to the feedback that you claim was "helpful and detailed" from others with the same concerns as mine, so I find it a little more than ironic that you think mine is "rude" and "entitled".

But that having been said, I don't have Twitter or Facebook's budget, ergo I don't have the staff to ingest breaking changes at the rate they do either and I highly doubt I'm alone in this respect. So who specifically is this project for? If your only concern is for them, then I get it. Say no more. Otherwise, try to grow some thicker skin and listen to legitimate, constructive criticism. You'll be a better all-around person for it, I promise.

To your last question, the very nature of React components allow for N number of unknowable props so why would you take this approach? I'm genuinely asking. Can you provide a link to the PR's where all of this helpful and detailed feedback exists so I can review it and educate myself? No one is more open to new ideas than yours truly, I swear. I tried searching for this earlier this afternoon in the Issues and came up empty which is actually what prompted this entire exchange.

I will say again, as I said twice in my original "rant"... RNW is great and _I respect and appreciate the contribution_.
