### ISSUE TITLE
I18Manager change direction not work well

### ISSUE THREAD

**Issue by hosseinmd** [necolas/react-native-web#1735]
**The problem**
i18Manager works well if you change direction before the components are rendered. But if change after components are rendered that has a problem with start end margins.
When changing i18Manager to RTL,  marginStart and marginEnd for some elements  won't change. But it works when defined before rendering components.

I provided an example that shows the issue.
In this example, after changing direction margin between buttons isn't right.
Simplified test case: https://codesandbox.io/s/muddy-sky-tjz8x?file=/src/App.js

**Expected behavior**
The expected margin between buttons to be equal in both directions.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.7
* React (version): 16.13.1
* Browser: Chrome 85.0.4183.102

**Comment by necolas** [comment]
You still have to trigger a react update, e.g., https://github.com/necolas/react-native-web/blob/master/packages/docs/src/apis/I18nManager/examples/LayoutRTL.js#L477

**Comment by hosseinmd** [comment]
In an App, how can I update all layouts which are memorized? This is not about a page, this is about a few pages where users can go back to those.
