### ISSUE TITLE
Deprecated RN Components

### ISSUE THREAD

**Issue by radihuq** [necolas/react-native-web#1737]
Are there plans to remove deprecated React Native components from this library?

For example: The RN team deprecated the [Checkbox component](https://reactnative.dev/docs/checkbox.html) and recommends using `@react-native-community/checkbox` as [it wasn't being used internally at FB](https://github.com/react-native-community/react-native-checkbox/issues/67#issuecomment-683940155). The other core deprecated component is the [Picker component](https://reactnative.dev/docs/picker).

I know @necolas made the [conscious decision to keep these components](https://github.com/react-native-community/react-native-checkbox/issues/67#issuecomment-674616111), however will that change in the future?

**Comment by necolas** [comment]
Unlikely to change. The community packages are really bad at adding and maintaining acceptable web support. And a UI framework should have core form elements included, so I think we will eventually revisit some of the decisions made by the lean core initiative. Things like checkbox should be part of core, whereas flatlist should not

**Comment by radihuq** [comment]
Cool, good news for me and my projects
