### ISSUE TITLE
Support for BackHandler

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#1739]
I don't know if this can be helpful, but I worked on a RN + RNWeb app where I needed to handle the "previous" key from the browser, as well as the hardware back key from other devices.

I found a little trick to handle it correctly for my use case and it gave me an idea for a web implementation of BackHandler.

You can find the draft PR [here](https://github.com/necolas/react-native-web/pull/1738)

@necolas if you can give it a look and tell me if it is interesting. If it is, I can test it more thoroughly to make it a real PR.

**Comment by necolas** [comment]
Closing this issue as we have the PR. If anyone else is interested in attempting to support this, please head over to the PR and leave feedback or suggestions. Thanks
