### ISSUE TITLE
useElementLayout for DOM elements

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#1740]
I need a span that supports measureLayout provided by useElementLayout.

The issue is that those hooks aren't exported and [this PR](https://github.com/necolas/react-native-web/pull/1686) that would fix this was not accepted.

How am I supposed to solve this?

**Comment by necolas** [comment]
Those hooks are implementation details and not part of the public API at this time

**Comment by Sharcoux** [comment]
Ok, but what are the options. If the hooks are not accessible, why can't we have at least a public API that make us benefit from them.
