### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#1744]
Opening link in a new tab is something quite common on web nowadays. This use case should be handled by react-native-web.

Currently, the only solution is [described here](https://github.com/necolas/react-native-web/issues/162).

Can I propose [this solution](https://github.com/necolas/react-native-web/pull/1743) as an improvement to react-native-web?

**Comment by imnotjames** [comment]
Duplicate of https://github.com/necolas/react-native-web/issues/1544 ?
