### ISSUE TITLE
Exposing the native View, commands & dispatchViewManagerCommand in UIManager

### ISSUE THREAD

**Issue by nimishsinghal** [necolas/react-native-web#1745]
**Is your feature request related to a problem? Please describe.**

We are using dispatchViewManagerCommand to dispatch the events to native, while extending the functionality to the web the method was missing in RNW.

**Describe a solution you'd like**

Can we expose nativeView, commands & dispatchViewManagerCommand in UIManager?

**Describe alternatives you've considered**

**Additional context**

**Comment by necolas** [comment]
This is not something I'm going to spend time on, but you're welcome to investigate

**Comment by necolas** [comment]
Closing due to lack of follow-up. I don't know if these APIs make sense for web, but it would be great if you share what you come up with in a PR. Thanks
