### ISSUE TITLE
Change in ref handling from 0.13.12 to 0.13.13 causing issues.

### ISSUE THREAD

**Issue by cj** [necolas/react-native-web#1749]
Hi,

It looks like the commit https://github.com/necolas/react-native-web/commit/376ccc31b1b1a11de1cab6bd7df4385be1a6a28c is causing issue with libraries like https://github.com/callstack/react-native-paper.

Here is an example https://snack.expo.io/ENlokUg6Y

You will notice the label fields are hidden when they should be showing in web.  If you switch to IOS you will see the label fields are displayed correctly.

react-native-web@0.13.13

**Comment by necolas** [comment]
I don't see an  issue in that snack, but it's using Expo 38. Please fill out the issue template with a link to a codesandbox?

**Comment by necolas** [comment]
What's going on in all that react-native-paper code? Where is the problem occurring?

**Comment by necolas** [comment]
The package is depending on an old version of `react-native-safe-area-view`, so it doesn't even run on web without bundler configuration.

**Comment by necolas** [comment]
The issue seems to be related to that package using Animated and setNativeProps, not with refs.

**Comment by jaulz** [comment]
I face the same issues and found out that if I remove `useMemo` from `useMergeRefs` it is working as expected.

**Comment by necolas** [comment]
`0.0.0-583e16fa8` is a patch release candidate that should avoid this issue while also memoizing refs. Twitter is going to dogfood it, but if anyone else does too, lmk how it goes
