### ISSUE TITLE
Is it possible to build the web app into a static bundle?

### ISSUE THREAD

**Issue by johnnynanjiang** [necolas/react-native-web#1752]
Instead of using `npm run web` to get it up and running, is it possible to build the web app into a static bundle?

**Comment by johnnynanjiang** [comment]
@necolas why you closed the ticket without any comment or explanation?

**Comment by necolas** [comment]
You haven't reported an issue with this library. This is just JS modules so it can be bundled like any JS.

**Comment by johnnynanjiang** [comment]
Because this is the only channel I know of for communicating with you around `react-native-web`, and I raised this issue as a feature inquiry instead of a bug.

**Comment by johnnynanjiang** [comment]
Another question, how to change the default web app port from 3000 to 80?

**Comment by necolas** [comment]
Your questions are not about RNW but about bundlers like webpack or sdks like expo. Please refer to their docs
