### ISSUE TITLE
Bring back className prop

### ISSUE THREAD

**Issue by natew** [necolas/react-native-web#1756]
**Is your feature request related to a problem? Please describe.**

So until now I've been working around not having className with a custom hook `useAttachClassName`, but it's very hacky. It uses ref + mutationObserver, and during a recent profile of a slow part of the app, I noticed the mutation observers were causing significant slowdowns.

Simply put, classNames are useful for a ton of things. In fact, our biggest use case is optimizing styles. We have a compiler that takes `StyleSheet` and converts them to.. classNames. This is the biggest performance win you can get on rnw, and to be honest, you can't really build any significant app without doing it.

So, essentially, rnw is held back for all but the most trivial apps without className support.

For now, we are just patching to add it back in.

**Describe a solution you'd like**

Bring back className support, you can leave it untyped.

**Describe alternatives you've considered**

Tried mutation observers and ref but its far too slow.

**Comment by necolas** [comment]
I'm not surprised you had issues using MutationObserver. You can use a data-* attribute instead of class

**Comment by natew** [comment]
Data attributes are far slower, that’s not a good solution.

**Comment by necolas** [comment]
Nonsense. There's no significant performance difference and of course you can do atomic CSS with them. What I'm not going to do is open up the API to intentionally support arbitrary styling solutions that conflict with the one provided. If you're that far down the rabbit hole you can fork the library or apply a patch to passthrough that prop.

**Comment by natew** [comment]
So you apply a data attribute for every atomic style and accept overhead in bytes download and parse time when className is designed for this purpose?

[It seems className is faster](https://stackoverflow.com/questions/12496884/are-data-attribute-css-selectors-faster-than-class-selectors), which makes sense given className is the de-facto way to style on the web and has been around to optimize longer.

Suddenly using className is an "arbitrary styling solution"?

> that far down the rabbit hole

There are tons of styling solutions that extract to stylesheets, not only is Facebook itself doing this but Pete Hunt and his team released jsxstyle years ago.

I am a big fan of this library and am just trying to improve it. To expect the entire ecosystem to bend around data-attributes and trade performance, readability, bundle size, inspector friendliness, and DX seems really short-sighted.

**Comment by necolas** [comment]
No, Twitter is using the StyleSheet provided here. That was introduced under experimentation without negative usage consequences, including for people using 3G on low end phones. Facebook extracts their CSS, but that has its own tradeoffs, like requiring users to download all 90Kb of gzipped CSS most deploys. Facebook doesn't even ship a PWA or provide offline support. Their entire architecture, product goals, and requirements are different from Twitter and extremely idiosyncratic. And yes, making className part of View's public API opens the door to arbitrary use of CSS styling that can conflict with the built-in styles and the guarantees of RN's styling model (no descendent selectors etc). At Facebook, on the new front-end we don't use className directly and ban anything except the JS syntax for styles - just like here. At some point this library may include a compiler to provide the option of static style extraction, or hybrid approaches, but it's not an approach that is better in absolute terms for all apps. Since you've written your own compiler somewhere (which presumably you'd share if you were trying to make this library better), you'll have fork the library to integrate it. But you can do that by modifying what createElement expects from `style` too

**Comment by natew** [comment]
> like requiring users to download all 90Kb of gzipped CSS most deploys

Ok, but that’s not relevant, it’s easy to extract it per-file so webpack knows to lazy load styles. 

> Their entire architecture, product goals, and requirements are different from Twitter and extremely idiosyncratic

This is the part that feels weird about your arguments. There are more companies using rnw than Facebook and Twitter. And literally the biggest company using it and the creator of the library does extraction. Isn’t that alone reason to allow an escape hatch at least? I feel like I’ve proved my point already here. 

> making className part of View's public API opens the door to arbitrary use of CSS styling that can conflict with the built-in styles and the guarantees of RN's styling model

So technically no need to make it public, have it under a scary flag like dangerouslySetInner, or leave it untyped but still have it accept. 

But... second point. You say this like it’s a good thing, but why *wouldn’t* you want an escape hatch. This is react-native-*web* after all. And it’s software. It feels very authoritarian to decide for others that className is too dangerous without even listening to us. I mean literally I’m a user coming here to explain some use cases, and you closed the ticket before even hearing one person out. Do you know my company’s requirements before I even say my word? It’s weird to be honest how hostile you are. You do realize when I said “beyond non-trivial” I wasn’t attacking you, I mean we have a big example in Facebook. It’s weird that you work for Facebook who extracts to className and yet the rest of us developers aren’t capable enough of handling that power? Or even making a case for it? It’s a simple lint rule away to disable it.

There don’t exist great cross platform libraries for animation for example. The native ones all run very slow on web. Why not let people sprinkle in animation related classNames? That’s a great escape hatch to have.

Are you afraid your future upcoming libraries from Facebooks that aren’t released yet will have competitors and are trying to prevent those competitors from coming along? I only ask because it’s a bit odd with the “what’s for me not for thee” thing going on here.

> but it's not an approach that is better in absolute terms for all apps.

It is better in absolute terms to be honest, unless adding a plug-in to webpack isn’t worth time. There’s no downside: you write your styles as normal and then you get optimization for free. 

> which presumably you'd share if you were trying to make this library better

Of course I plan to, I open sourced a static extraction library a few weeks ago. I open sourced Reapp, Pundle, tons of libraries over the years.

That’s why I opened this ticket. But I guess you don’t want people to compete with Facebook and you’re not really open to listening to your community. You’d rather cast doubt on us and close issues before even the slightest discussion.

**Comment by natew** [comment]
I do think the discussion has gone off rails do to you perceiving my “non-trivial” comment as a personal attack. Since then I can tell you’ve taken this as some sort of attack, so I want to cool it down. Let’s talk collaboratively and not adversarially. I hope you see my point of view when I say the Facebook competition stuff: I earnestly mean it. As a low level library, an escape hatch here is necessary and having it available for Facebook but not outsiders seems odd. Plus, they are planning on releasing Stylex at some point, no? Wont it need an escape hatch?

But more importantly, let me explain something I think was missed that should clear it up how important this is. It’s not the extraction to CSS/className that really speeds things up. It’s actually the fact that in many cases you can compile from View to div.  In fact in our codebase close to 60% of the views we use are actually compiled to a plain div. Further, since the library supports Text, about 60% of our text views are turned into spans. I can totally show your the profile results. It’s a *massive* speed up. Twitter is a fairly “flat” app, they don’t render extremely detailed views. But if you build an app that has deeper trees, I’m telling you, avoiding 60% of View and Text renders is huge. I can share profile results, absolutely.

I’m also happy to even just open source the library ASAP. It’s not ready, I’d have liked to finish media query and theme support, both of which can use the static analysis for big wins in performance (extract to real media queries in many cases). It has a couple bugs. But that’s fine, if it would prove the need to you.

I mean it’s exciting stuff, seeing huge jumps in performance for the whole community. As you know flattening the tree depth is a huge win. Our app renders very detailed views with lots of elements on screen, so you know the use case.

**Comment by necolas** [comment]
You're not really listening and have started creating straw man arguments and conspiracy theories. Facebook isn't using RNW or open sourcing stylex. As I've said several times, fork the library to integrate your compiler or share what you've created when it's ready. Thanks

**Comment by natew** [comment]
Would love to hear your thoughts on flattening view depth, seriously. I think you missing that context set this out on the wrong foot as you thought it was a simple optimization and not a large one. 

Same with animations, until Web Animations is widely supported I don’t believe we have a good answer as a community. 

Wish you the best and a good weekend. I will release it and come up with a PR I think addresses your worries and my own.

Thank you for all your hard work on this. You’ve been a tremendous contributor to the world of software. I appreciate it. 

Hope we can find a constructive solution here. I only work to help. If you want some honest feedback, two lines you wrote came across as very unnecessarily adversarial:

“*presumably* you'd share *if* you were trying to make this library better” and “That far down the rabbit hole”. The first suggests I’m acting in bad faith, the second suggests I’m doing something so eccentric, when in fact prior art in jsxstyle had already been around for ages and proves this is helpful.

I’ll also apologize for suggesting you have bad intentions at Facebook, I was only doing so because of your above statements and trying to show you that assuming the worst looks ugly. As you can see, it is. I don’t actually believe you have those intentions, as I hope you don’t actually believe I opened this without the intention of delivering real benefit. 

Cheers, talk to you next time.

**Comment by natew** [comment]
@necolas haven't tested it outside our app yet and it won't build from a clone as I need to adjust it for running outside the monorepo, but it's here:

https://github.com/natew/snackui/
