### ISSUE TITLE
Button component shouldn't propagate click event when disabled

### ISSUE THREAD

**Issue by krosenberg** [necolas/react-native-web#1757]
**Is your feature request related to a problem? Please describe.**
The Button component (and components with button-like roles) propagates click events when disabled. This means that a component that wraps a disabled Button will receive a bubbled click event if the Button is clicked. This behavior is different from a native HTML button, in which click events are not propagated if the button has a `disabled` attribute.

https://codesandbox.io/s/confident-ardinghelli-v632m shows a disabled RNW Button and a disabled native HTML button, each wrapped by a View with a click handler. Notice that clicking on the RNW Button causes a message to log in the console from the wrapper click handler, but clicking the native button does not.

**Describe a solution you'd like**
The RNW Button component should behave like the HTML button element, in that if it's disabled, it should prevent click events on the button itself from propagating.

I believe [this line](https://github.com/necolas/react-native-web/blob/9ed9231b04ae495718e76749036ca3cd2a81eb80/packages/react-native-web/src/modules/createDOMProps/index.js#L232) could be replaced with `domProps.onClick = e => { e.stopPropagation() }` instead of setting `onClick` to `undefined`. I'm happy to submit a PR if you have no reservations.

**Comment by necolas** [comment]
Thanks. The proposed fix sounds good to me

**Comment by necolas** [comment]
This line probably needs to be moved too https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/hooks/usePressEvents/PressResponder.js#L391
