### ISSUE TITLE
Switch disabled track and thumb color

### ISSUE THREAD

**Issue by reck753** [necolas/react-native-web#1758]
**Is your feature request related to a problem? Please describe.**
No.

**Describe a solution you'd like**
I saw that the disabled colors are hard-coded so I would only change them with variables passed from props. Eg. I would add two more props disabledTrackColor and disabledThumbColor. I feel like that styling should be adjustable, because not everyone is happy with those colors.

**Describe alternatives you've considered**

**Additional context**
Eg. I have a switch with red track and white thumb and I would like it to have some light red color for track and some light grey color for thumb when disabled, instead of those that are hard-coded.

**Comment by bouaoud** [comment]
same here

**Comment by Moe-kanan** [comment]
+1

**Comment by makkarMeenu** [comment]
@reck753 [This](https://github.com/necolas/react-native-web/pull/2164) PR resolves the above issue in a different way.
You can change trackColor and thumbColor  conditionally according to disabled condition. 
I think, we can't introduce new props as react-native also doesn't provide `disabledTrackColor` and `disabledThumbColor`.

**Comment by reck753** [comment]
> @reck753 [This](https://github.com/necolas/react-native-web/pull/2164) PR resolves the above issue in a different way. You can change trackColor and thumbColor conditionally according to disabled condition. I think, we can't introduce new props as react-native also doesn't provide `disabledTrackColor` and `disabledThumbColor`.

Hi, @makkarMeenu!
Thanks for the PR! This would be a good enough solution for me.
