### ISSUE TITLE
Touchable opacity provides react error on Web render

### ISSUE THREAD

**Issue by vongohren** [necolas/react-native-web#1759]
**The problem**
Using a touchable opacity in a component and rendering it on web, provides this error. It is a default create react typescript project, that is using a compiled component including touchable opacity from a library, following this standard: https://github.com/formium/tsdx
<img width="1051" alt="Screenshot 2020-10-02 at 09 40 40" src="https://user-images.githubusercontent.com/1012055/94899357-71bf5400-0493-11eb-9e81-3707d3f00b66.png">

**How to reproduce**
Just build a component with touchable opacity and render it in web.
Not sure what forces the error, if it is that im on TypeScript, have some strict mode set or something.
Because my compiled stories dont complain, and production dont complain.

Simplified test case: Dont have that now

Steps to reproduce:
1. Use touchable opacity inside a default create react typescript project
2. See the error render

**Expected behavior**
Dont produce any error on rendering

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.12.2
* React (version): 16.12.0,
* Browser: Chrome

**Comment by necolas** [comment]
You're using StrictMode so you been to be on RNW v0.13
