### ISSUE TITLE
Rendering looses spaces

### ISSUE THREAD

**Issue by miketheanimal** [necolas/react-native-web#176]
This might not be a bug, and might be OK with some work-around ...

If I have something like

    let text = 'One two' ;
    ....
    <Text>{text}</Text>

then visually it renders correctly and I see the space. However if I have:

    let left = 'One ' ;
    let right = 'Two ' ;
    ....
    <Text>{left}</Text><Text>{right}</Text>

then visually the space disappears, although it is actually there in the DOM:

    <span>One </span><span>Two</span>

This is a problem for me, as I actually want to render the string with a cursor marker in the middle which can be animated to blink, ie., (ignoring the actual animation stuff) something like:

    <Text>{left}</Text><Text>|</Text><Text>{right}</Text>

I guess that converting all spaces in strings within <Text>...</Text> to &nbsp; within react-native-web would fix my problem, but then:

    <Text>
        Spaces and newlines at each end!
    </Text>

would break?

**Comment by necolas** [comment]
This looks like default React behaviour. Not sure what result you're trying to get. Something like this?

```js
<Text>
  <Text>One </Text><Text>|</Text><Text> Two</Text>
</Text>
```

**Comment by miketheanimal** [comment]
If that's the default behaviour when I'll have to live with it:) The effect I'm trying to get is a blinking cursor in the middle of some text without loosing visibility of spaces immediately before or after the cursor.
