### ISSUE TITLE
Firefox showsHorizontalScrollIndicator doesn't work (because old prefix deprecated)

### ISSUE THREAD

**Issue by burakgormek** [necolas/react-native-web#1760]
**The problem**

scrollbarWidth style prop doesn't work for firefox because it's deprecated with version 63 and later. ([source](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#Deprecated)) (latest version: 81.0.1)

StyleSheet source: https://github.com/necolas/react-native-web/blob/7cbe1609b8f7506dc3c0903cfd7eeb8cf4f7e8c8/packages/react-native-web/src/exports/StyleSheet/compile.js#L176

We need to change this line with new property "scrollbar-width: none". (or do we need to keep old version support?)
It works when I apply it in firefox developer tools.

I can make a pull request if you want.

**How to reproduce**

Simplified test case: https://snack.expo.io/yHiO2YlIX 

Steps to reproduce:
1. Try horizontal scroll on white background content in the test case link (Firefox).

**Expected behavior**

Scroll bar needs to hide with "showsHorizontalScrollIndicator={false}" prop.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.15 (tried on 0.14 pre-release too)
* React (version): 16.10.2
* Browser: Firefox 81.0.1

**Comment by necolas** [comment]
Thanks. Should be fixed in 0.13.16
