### ISSUE TITLE
Custom DOM Attributes haven't been working since 0.11.7

### ISSUE THREAD

**Issue by kimthompson** [necolas/react-native-web#1768]
**The problem**

I bootstrapped a React Native/Next.js project with Expo last month, and development has been going well. However, when I upgraded to SDK 0.39.3, I lost the ability to use custom [DOM Attributes](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html). We are sparingly relying on them to apply a few extra web-only styles to site, like removing `text-decoration` on links.

Further experimentation revealed that these attributes appear again if I roll back my version of `react-native-web` to `0.11.7`, but fail on all subsequent versions I tried.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/sleepy-booth-kils4?file=/package.json

Steps to reproduce:
1. Load up this page and see that the text is quite ugly (black background with magenta text). If you feel like it, also inspect that element to see that the `<div>` has a `data-class` property of "webstyles".
2. Go to package.json and update `react-native-web` to any valid subsequent version, like `0.14.1`
3. Reload the page and see that the ugly styles are gone. You can confirm that this is because the `data-class="webstyles"` attribute was never rendered to the DOM by inspecting that element.

**Expected behavior**

I expected the `data-class="webstyles"` attribute to show up on the div so that my styles.css file in the public folder could find it and attach a few styles to it.

**Environment (include versions). Did this work in previous versions?**

Yes, this worked in 0.11.7, but no later.

* React Native for Web (version): 0.11.7
* React (version): 16.13.1
* Browser: Chrome 85.0.4183.12

**Comment by necolas** [comment]
You shouldn't need custom styles to remove link underlines as that is done automatically. As for the data attributes, this is documented in the release notes

> Forwarding of data-* props is no longer supported. Use dataSet instead. For example, dataSet={{ someName: 1 }}

https://github.com/necolas/react-native-web/releases/tag/0.13.0
