### ISSUE TITLE
Seems that ListView is not checking whether sections/rows are necessary to render

### ISSUE THREAD

**Issue by genxium** [necolas/react-native-web#177]
There're currently some differences between the [ListView of react-native-web](https://github.com/necolas/react-native-web/blob/master/src/components/ListView/index.js) and [that of react-native](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js). It seems that ListView is not checking whether sections/rows are necessary to render.

**Comment by necolas** [comment]
If you want to contribute improvements that would be appreciated. We aren't using list view internally so this is not currently a priority for me.

**Comment by gethinwebster** [comment]
FYI have got a few use-cases for ListView in a project I'm working on, so am going to aim to put some time aside over the next few weeks to look at this and try to get a bit closer to the react-native implementation.

**Comment by necolas** [comment]
Moving all ListView issues to #260
