### ISSUE TITLE
Support "matrix" in transform style

### ISSUE THREAD

**Issue by Naturalclar** [necolas/react-native-web#1771]
**Is your feature request related to a problem? Please describe.**

Currently, when I try to use `transform` in StyleSheet with matrix, it has no effect on react-native-web. 

e.g. 
```jsx
const MatrixComponent = () => {
  return(
	<View style={{transform:[{matrix:[1,2,3,4,5,6]}]}/>
  )
}

```

react-native-web allows `transformMatrix` style, which is currently deprecated in the react-native core.

ref: https://reactnative.dev/docs/transforms#decomposedmatrix-rotation-scalex-scaley-transformmatrix-translatex-translatey

**Describe a solution you'd like**

Add `matrix` option to Transform styles https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/types/styles.js#L258

Change mapTransform so that when `matrix` type is used, call `convertTransformMatrix` to get its css-equivalent for web https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/createReactDOMStyle.js#L40

**Describe alternatives you've considered**

**Additional context**

**Comment by necolas** [comment]
Thanks. Fixed in 0.14.3
