### ISSUE TITLE
onBlur prevents trigger of onPress

### ISSUE THREAD

**Issue by Nestoro** [necolas/react-native-web#1773]
**The problem**

with react-native-web 0.14.2 i experience different behaviour regarding the execution of a onPress trigger in a component that is getting removed by a onBlur trigger. Previously the execution went through in 100% of the cases. now the execution of the onPress trigger gets terminated before executing.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/quirky-tu-vdh69

Steps to reproduce:
1. focus TextInput
2. klick on TouchableOpacity
3. witness closing

**Expected behaviour**

1. focus TextInput
2. klick on TouchableOpacity
3. witness text changing and closing

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.2
* React (version): 16.9.0
* Browser: Chrome

**Workaround**

if i wrap the closing handler (L14) in a timeout i can reproduce the old behaviour, but i fear that this method lacks consistency as it requires a timeout of 50ish to work.

`        onBlur={() => setTimeout(() => onChangeOpen(false), 50)}
`

**Comment by necolas** [comment]
The pattern you're using is the problem. The text input is blurred before the press event occurs, so by the time the click is dispatched the pressable is no longer in the tree. You can see this with native DOM components too:

https://codesandbox.io/s/infallible-jones-owfkk
