### ISSUE TITLE
Pressable pressed should be true with macbook trackpad clicking

### ISSUE THREAD

**Issue by hosseinmd** [necolas/react-native-web#1774]
**The problem**

When I click with the trackpad Pressable pressed don't change 
It changes just with a hard click.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/staging-frog-kj2o3?file=/src/App.js:296-395

Steps to reproduce:
1.
2.
3.

**Expected behavior**

Expected pressed to be true when clicking with trackpad

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.1
* React (version): 16.13.1
* Browser: chrome

**Comment by necolas** [comment]
I don't understand the problem

**Comment by hosseinmd** [comment]
I am touching on pressable onPress calling but pressed of style don't change to true.

**Comment by hosseinmd** [comment]
I am touching on pressable onPress calling but pressed of style doesn't change to be true.

**Comment by necolas** [comment]
That's because you have a long transition delay: https://codesandbox.io/s/inspiring-diffie-hj7lk

**Comment by hosseinmd** [comment]
I found what is the problem, when I'm tapping that it is so fast and that can't create any change in you, such as changing background or opacity.
How can we solve that?

TouchableOpacity has this problem too.

**Comment by hosseinmd** [comment]
> That's because you have a long transition delay: https://codesandbox.io/s/inspiring-diffie-hj7lk

No, that is nothing, I'm just testing

**Comment by hosseinmd** [comment]
Pressable needs to have a min duration to show changed style based on pressed
That seems bad, because I change the style because pressed changed But it is useless

**Comment by hosseinmd** [comment]
I don't have enough time to show my specific style when user taping.

**Comment by necolas** [comment]
Use `delayPressOut` then

**Comment by hosseinmd** [comment]
Thanks so much.
