### ISSUE TITLE
React-native-web / nextjs - You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by chas13** [necolas/react-native-web#1776]
Hi there,

I installed react-native-web in my NextJS project so that I could use rn-sliding-up-panel. However, I am getting the below error:

`error - ./node_modules/rn-sliding-up-panel/SlidingUpPanel.js 37:19
Module parse failed: Unexpected token (37:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class SlidingUpPanel extends React.PureComponent {

static propTypes = {
| height: PropTypes.number,
| animatedValue: PropTypes.instanceOf(Animated.Value),
wait - compiling...`

I followed the with-react-native-web example
https://github.com/vercel/next.js/tree/master/examples/with-react-native-web

Any help would be appreciated.

**Comment by chas13** [comment]
I was able to resolve that by adding this in my next.conf.js

config.module.rules.push({
  test: /@?(rn-sliding-up-panel|SlidingUpPanel).*\.(ts|js)x?$/,
  use: defaultLoaders.babel,
  include: [path.resolve(__dirname, "node_modules")],
})

**Comment by chas13** [comment]
I am left with this error:

SyntaxError: Cannot use import statement outside a module

Would anyone be able to assist me in how I should setup next.config.js and babel.config.js to be able to use rn-sliding-up-panel, maybe, please?

**Comment by necolas** [comment]
Try asking for help using the next.js support channels. Closing this as it's not an issue related to this repo

**Comment by gunjankothari** [comment]
`const withTM = require('next-transpile-modules')(['react-native-web']);
module.exports = withTM({
  reactStrictMode: false,
  webpack: (config, { defaultLoaders }) => {
    config.resolve = {
      ...config.resolve,
      alias: {
        ...config.resolve.alias,
        'react-native$': 'react-native-web',
      }
    };
    return config;
  }
})`

This helped me fix the issue
