### ISSUE TITLE
Warning: Invalid DOM property `enterkeyhint`

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#1778]
**The problem**
React 17 changed valid DOM property dev warning logic. 
`react-dom.development.js?61bb:67 Warning: Invalid DOM property `enterkeyhint`. Did you mean `enterKeyHint`?`

**How to reproduce**
Just use TextInput.
https://codesandbox.io/s/zen-knuth-zn4ux

**Expected behavior**
Change this line `supportedProps.enterkeyhint = returnKeyType;` in TextInput. However, it would break React < 17 so I am not really sure how it should be fixed.

**Comment by necolas** [comment]
Duplicates #1707
