### ISSUE TITLE
Disabled Touchable inside (enabled) Touchable prevents onPress event to bubble

### ISSUE THREAD

**Issue by yairopro** [necolas/react-native-web#1781]
**The problem**

A disabled touchable prevent the `onPress` event to bubble to the next touchable ancestor.

**How to reproduce**

Place a disabled `TouchableOpacity` inside an enabled `TouchableOpacity`.

Simplified test case web: https://codesandbox.io/s/disabled-touchable-inside-enabled-touchable-2us02
Simplified test mobile case (working): https://snack.expo.io/@yairopro/disabled-touchable-inside-enabled-touchable

Steps to reproduce:
1. Create a `TouchableOpacity` with a log set as its `onPress` event.
2. Place another `TouchableOpacity` inside. Disable it.

**Expected behavior**
The parent `TouchableOpacity` 's `onPress` event should be triggered when user click on the disabled child `TouchableOpacity`.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): ^0.14.4
* React (version): ^17.0.1
* Browser: Chrome 86.0.4240.111

**Comment by necolas** [comment]
I think this might be an issue with RN and this should not be happening. On the web a disabled button will not propagate clicks etc, so nested pressables that are disabled should not trigger their parents press callback

**Comment by yairopro** [comment]
I really **really** don't think it's a bug in RN. Native on iOS / Android  buttons act like that.
Disabled _touchables / buttons / clickables_ should act just like a view. Even on the web, the way to disable a clickable div is to remove its `onClick` method, which makes it a simple view.
Cases when the event should stop to propagates are edge cases, and the developer should stop the event propagation explicitly.

But well anyway, if you think so, can we at least let the developper have a fallback to force the disabled button to bubble its event by setting a prop (or something else) ?
Replacing the `TouchableOpacity` by a `View` component will unmount/re-mount all descendants and so reseting all their states. It's not a possible solution.

**Comment by necolas** [comment]
> Cases when the event should stop to propagate are edge cases, and the developer should stop the event propagation explicitly.

How can a developer stop the propagation of the press event when it doesn't get fired if the element is disabled?

**Comment by yairopro** [comment]
No lol, it's the other way around.
If he wishes to prevent propagation, **he should not disable it** and set an `onPress` to prevent the propagation.
Like we do on web as well: to prevent an event to bubble, one has to set an `on-click` handler which will call `event.stopPropagation()` explicitly.

**Comment by necolas** [comment]
That doesn't really make sense because the start/end etc events need to be prevented too. What I can do is make the existing default case a special case only for `button` roles, as a native button isn't current used (which would provide the expected behavior by default)

**Comment by yairopro** [comment]
> the accessibility state needs to be disabled.

You've got a point.

> make **the existing default case** a special case only for button roles

By _the existing default case_ you mean to bubble like RN, or to not bubble like web-native-button. ?

**Comment by yairopro** [comment]
ok

**Comment by yairopro** [comment]
Thanks @necolas
