### ISSUE TITLE
Disabled `Pressable` should have `cursor: default`

### ISSUE THREAD

**Issue by jtomaszewski** [necolas/react-native-web#1784]
After changes from https://github.com/necolas/react-native-web/commit/c2019a9881ecec4cdb5d4b2ab355ed7e578b8752 (I'm testing on 0.14.4), `Pressable` now always has `cursor: pointer`, even when it's disabled.

I think when button/link is disabled it should have `cursor: default` like on most websites, including github.com .

@necolas do you agree? I can submit a PR for this.

**Comment by necolas** [comment]
Duplicates #1782
