### ISSUE TITLE
Discrepancy for onPress event in child of a PanResponder

### ISSUE THREAD

**Issue by flip-it** [necolas/react-native-web#1788]
**The problem**

After upgrading to RNW 0.13 the `onPress` of a Pressable can be triggered after dragging a parent with a mouse (but not touch).

**How to reproduce**

Simplified test case: https://codesandbox.io/s/angry-wave-g3rys
The outer blue rectangle represents a swipeable row. The inner red rectangle represents a row which you can press.

Steps to reproduce:
1. Drag the red rectangle with a mouse
2. The "Pressed" number increments

**Expected behavior**
There should be no `onPress` event on the red rectangle after dragging.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.0–0.14.15
* React (version): 16.13.1
* Browser: tested in Safari and Chrome

**Comment by necolas** [comment]
Is this basically how you expect it to work? https://codesandbox.io/s/unruffled-thompson-4t408

That's a user-space implementation of a change we can make to the `PanResponder` code so that it doesn't activate a `PressResponder` in the subtree, when a pan gesture ends.

**Comment by flip-it** [comment]
Yes this is what I expect! Does it mean that this can be the default behaviour of PanResponder and the user-space implementation not necessary?

**Comment by dylan-chong** [comment]
hey guys we're getting the exact same bug as this using react 18 and rnw 0.19.13
