### ISSUE TITLE
_reactNativeWeb.requireNativeComponent is not a function (on iOS)

### ISSUE THREAD

**Issue by Fawxy** [necolas/react-native-web#1791]
When running my react native first app on iOS (not an expo app) with react-native-web, I get an error `_reactNativeWeb.requireNativeComponent) is not a function.` in react-native-safe-area-context.

**How to reproduce**

Simplified test case: 
[RequireNativeComponentRepro.zip](https://github.com/necolas/react-native-web/files/5461218/RequireNativeComponentRepro.zip)

Steps to reproduce:
1. In the project run `yarn && npx pod-install ios && npx react-native run-ios`
2. See crash on app start.

**Expected behavior**

`requireNativeComponent` should be available on iOS, this project actually would work no problem on the web. Should react-native only be aliased to react-native-web in webpack or something so that it's only aliased for web?

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.5
* React (version): 16.3.1
* React Native: 0.63.3

**Comment by necolas** [comment]
> Should react-native only be aliased to react-native-web in webpack or something so that it's only aliased for web?

Yes. You shouldn't be using the web renderer on the iOS platform.
