### ISSUE TITLE
New flex-basis behaviour gives unexpected results compared to both RN and web

### ISSUE THREAD

**Issue by jamesisaac** [necolas/react-native-web#1792]
**The problem**

From what I can see, commit 108366a72421e1b7ef8800a05584b507e948f8bf changed the resolved styles when `flex` is set, removing `flex-basis`, so now e.g. `flex: 1` resolves to the CSS `flex-grow: 1; flex-shrink: 1`.

I understand the motivation for not wanting to replicate quirks of Yoga (having `flex-basis` always set to `0%`).  But I don't think this behaviour is consistent with the web either.  My understanding is that setting `flex: 1` on the web translates down to `flex: 1 1 0`, i.e. it changes the value of `flex-basis` from `auto` to `0` ([reference](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#%3C'flex-basis'%3E)), which RNWeb doesn't do.

**How to reproduce**

The result is seemingly simple flexbox examples failing, e.g. using `flex: 1` to split two Views to be equal width regardless of content size:

https://codesandbox.io/s/react-native-web-root-element-styles-forked-4nuyg?file=/src/App.js

![Screenshot_2020-10-30 CodeSandbox](https://user-images.githubusercontent.com/1068177/97715524-6b37f280-1aba-11eb-9053-34834b8fcaf1.png)

**Expected behavior**

Top example is setting `flex:1` on each div with RNWeb, bottom is doing the same with React DOM.  React Native mobile produces results similar to the 2nd case, so it's only in RNWeb where it's necessary to set `flexBasis: 0` to get 2 divs split 50/50 regardless of content size.

IMO if someone writes `flex: 1` in RNWeb, that should either be resolved down to `flex: 1` in CSS, or expanded out to the expected values for web of all 3 attributes (`flex-grow`, `flex-shrink` *and* `flex-basis`), so that it's consistent with using `flex: 1` on the web.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14 (issue is resolved by downgrading to 0.13)
* Browser: Chrome or Firefox

**Comment by martinandert** [comment]
I've got the same issue with react-navigation, where, after upgrading react-native-web, the tab content view is now collapsed (rendering the bottom tabbar at the top).

**Comment by jamesisaac** [comment]
@necolas Thanks for such a quick fix!  Works great in latest release.
