### ISSUE TITLE
locationX and locationY are missing from onPress event

### ISSUE THREAD

**Issue by ElForastero** [necolas/react-native-web#1795]
**The problem**
`locationX` and `locationY` are missing from onPress event

I'm using https://github.com/n4kz/react-native-material-ripple to create a ripple effect on buttons.
It stopped working on Web after v12 due to these props missing on the onPress event.

All it does is accessing these props in the `onPress` handler of `<TouchanbleWithoutFeedback />` to get where to draw the circles.

```js
let { locationX, locationY } = rippleCentered?
   { locationX: w2, locationY: h2 }:
   event.nativeEvent;
```

Was the removal intentional? Sorry, I've spent a few hours trying to debug this behavior and understand the Responder system but honestly saying without any success.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/friendly-surf-5p1jh?file=/src/App.js

Steps to reproduce:
1. Click on the button to see the broken ripple effect
2. Switch RNW to v12
3. Click to see it works

**Expected behavior**
Properties are present on the `event.native.Event`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): ^0.14.7
* React (version): 16.13.1
* Browser: Chrome 86.0.4240.111

**Comment by necolas** [comment]
This is documented in the [0.13 release notes](https://github.com/necolas/react-native-web/releases/tag/0.13.0):

> The onPress callback on Touchables is now backed by native click events and will be called in almost every situation a native click event is called. The onPress prop of Touchable* components now receives a SyntheticMouseEvent not a SyntheticResponderEvent. It may be fired without a preceding onPressIn.

The package you're using hasn't been updated for over a year. I don't think it follows the material design spec, where the ripples would be rendered on press-in.

**Comment by ElForastero** [comment]
@necolas Thank you for the clarifications.
