### ISSUE TITLE
Can't resolve 'core-js/modules/es6.typed.float32-array'

### ISSUE THREAD

**Issue by mcaple** [necolas/react-native-web#1796]
**I am trying to use react-native-web within a Gatsby site and when running gatsby develop I see

 **ERROR #98124  WEBPACK**

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es6.typed.float32-array' in '/Users/xxxxx/code/Gatsby/xxxx/node_modules/react-native-web/dist/vendor/react-native/Animated'

If you're trying to use a package make sure that 'core-js/modules/es6.typed.float32-array' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/react-native-web/dist/vendor/react-native/Animated/bezier.js

**

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1. Run gastby develop

**Expected behavior**

es6.typed.float32-array gets resolved

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.7
* React (version): 17.01
* Browser: Build stage

**Comment by necolas** [comment]
Maybe a Gatsby problem?

[Float32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array) has been supported in browsers for a long time and there is a feature test [here](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/vendor/react-native/Animated/bezier.js#L26)

**Comment by mcaple** [comment]
Thanks necolas, I think it is a typescript setup issue as I have just created a hello, world app to post here to show the problem including react-native-web with no issue. I will relook at my config
