### ISSUE TITLE
Babel's configration file is not loading in

### ISSUE THREAD

**Issue by mikkpokk** [necolas/react-native-web#1799]
**The problem**

Unable to add a Babel's plugin. On this case plugin is called `@babel/plugin-proposal-class-properties`.

**How to reproduce**

Steps to reproduce:
1. Create a React class component
2. Add property inside to class. For example `test = () => {}`
3. Install Babel's proposal class properties plugin `npm install @babel/plugin-proposal-class-properties --save`
4. Open babel.config.js and add following line below a presets array `plugins: [ '@babel/plugin-proposal-class-properties']`
5. Run `npm run web` and see that babel's config is not working _(SyntaxError: ./node_modules/react-native-shadow/lib/BorderShadow.js: Support for the experimental syntax 'classProperties' isn't currently enabled (6:9):)_

**Expected behavior**

After installing and enabling Babel's plugin `@babel/plugin-proposal-class-properties` error should be dissapear and code should be compiled successfully.

**Environment (include versions). Did this work in previous versions?**

Don't know if it did work in previous versions. Problem exists only on web side.

* React Native for Web (version): 0.14.7
* React (version): 0.63.3
* Browser: Any

**Additional context**

![image](https://user-images.githubusercontent.com/14272312/98547264-94b60280-22a0-11eb-86ef-c38e75131d60.png)

**Comment by necolas** [comment]
See https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page#web-packaging-for-existing-react-native-apps
