### ISSUE TITLE
`hovered` render and style prop doesn't reset on a disabled Pressable until mouseOut

### ISSUE THREAD

**Issue by jamesisaac** [necolas/react-native-web#1803]
**The problem**

If you click a Pressable which leads to that Pressable becoming disabled, it's still passing `hovered: true` down to its children in the render props, and to the function in the `style` prop, until you mouseOut then mouseIn again.

Every other aspect of the button becoming disabled as soon as it's clicked seems to work correctly (cursor changing and stopping responding to clicks).

**How to reproduce**

Simplified test case: https://codesandbox.io/s/compassionate-mountain-oq2ze?file=/src/App.js

Steps to reproduce:

1. Move mouse over the main button and watch it go darker blue.
2. Click the button to set `disabled:true`.

**Expected behavior**

As soon as the button is clicked, hover state should disappear, as the Pressable is no longer interactive.  However, the state only disappears if you first move the mouse outside of the button.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version):  0.14 (hover wasn't supported in earlier versions)
* React (version): 16.13
* Browser: tested on Firefox and Chrome

**Example use-case**

A "Next page" button which becomes disabled once you click it enough times to reach the final page.

**Workaround**

You can create a style which cancels out the hover effects, applying it if the Pressable is disabled.  But this adds complexity so would be nice if this wasn't necessary.

**Comment by necolas** [comment]
You know you can use a conditional like `hovered && !disabled && styles.hover`?

**Comment by jamesisaac** [comment]
Whoops, good point!  Got so sidetracked trying to simplify this behaviour to minimal repro that I missed the obvious
