### ISSUE TITLE
expose hover callback props from `Pressable`

### ISSUE THREAD

**Issue by minheq** [necolas/react-native-web#1804]
**Is your feature request related to a problem? Please describe.**
Pressable does not expose `onHover*` callback props. Those are useful to enable richer web experience.

For example `<select>` allows you to highlight an option with either **hover** or keyboard arrow up/down. In order to replicate that behavior with a custom component, one would maintain an `activeIndex` of the highlight item. In pseudocode:
```
Component {
  activeIndex = 0

  onKeyboardUp = () => activeIndex  -= 1
  onKeyboardDown = () => activeIndex  += 1
  onHoverItem = (index) => activeIndex = index

  return options.map(option => <Pressable onHover={onHoverItem} />)
}
```
See the desired behavior in `react-select` where both mouse and keyboard can highlight the items. (cursor disappears when the highlighted items are changed with keyboard arrow keys)
![Screen Recording 2020-11-10 at 21 07 26](https://user-images.githubusercontent.com/9356633/98684661-05404a80-2399-11eb-8819-7a00c6d190f5.gif)

**Describe a solution you'd like**
Expose [onHoverChange](https://github.com/necolas/react-native-web/blob/6928fab9e0ef1e5bd0c10713b3b18b1b178d0bfb/packages/react-native-web/src/exports/Pressable/index.js#L135) or all [onHover*](https://github.com/necolas/react-native-web/blob/78174d7b487bb37d2f15c21e38a5beb2ad196da4/packages/react-native-web/src/modules/useHover/index.js#L21-L24) callbacks from `Pressable`.

**I would like to submit a PR for this feature, if you greenlight it.**  

This feature adds more props, and thus weight to `Pressable` API, so I will understand if you reject this feature.

**Describe alternatives you've considered**
In the example above, have the children call `onHoverItem` when they receive `hovered` prop. This is a little bit awkward. In pseudocode:

```
<Pressable>
 {({ hovered }) => {
   useEffect(() => {
      onHoverItem(index)
   }, [hovered])
   
   return <Item />
 }}
</Pressable>
```

Alternatively, wrap Pressable with `<Hoverable>` component from [Web Recipes](https://codesandbox.io/s/o9q8vy70l5)

**Additional context**
N/A

**Comment by minheq** [comment]
Having thought through this, i no longer believe this would be right idea.

Exposing hover callbacks is only a nice-to-have API. The use case described in the issue, can already be achieved in user land code. Straying off further from react-native's API unnecessarily adds more maintenance burden to this library.

**Comment by necolas** [comment]
> The use case described in the issue, can already be achieved in user land code.

Not without reimplementing the entire hover behavior. These callbacks probably will be added to Pressable as RN Windows needs the same functionality.

I have what I think is a better API for behaviors but it deviates significantly from the RN API and there would need to be work on the RN side to implement native equivalents. That's not going to happen for some time yet

**Comment by Freddy03h** [comment]
There is other use cases where the RN api has some limits with keyboard+mouse scenarios.

But ss you say, I hope it will be discuss because of RN Windows, but those scenarios affect more directly the RN project considering iPadOS with the magic keyboard (that include a trackpad) and all hoverable buttons.
