### ISSUE TITLE
adding component from NPM package  

### ISSUE THREAD

**Issue by satz4ios** [necolas/react-native-web#1806]
**The problem**

I am unable to import componets from the npm packages developed in react native and use it with a project created with react native web. Is there any specific thing to be done in the package which i have published in react native? 

<img width="1116" alt="Screenshot 2020-11-11 at 5 31 47 PM" src="https://user-images.githubusercontent.com/11567122/98816014-0b443300-244e-11eb-973f-6381de400d50.png">

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1.Create a new React JS project and follow steps provided here. 
2.install custom npm package (packed used by me https://www.npmjs.com/package/pkgtestmm ) 
3.npm start 

**Expected behavior**
Need to render the component 

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.7
* React (version): 17.0.1
* Browser: Firefox

**Comment by necolas** [comment]
https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page#web-packaging-for-existing-react-native-apps
