### ISSUE TITLE
[Question] Can I know my web app is running on mobile browser or desktop browser?

### ISSUE THREAD

**Issue by Insullone** [necolas/react-native-web#1813]
I am writing a chat web app, and find that its behavior is different on mobile browser and desktop browser when <TextInput> is clicked and keyboard pops up. When typing something and send in Input bar at the bottom, the positions of messages and the Input bar are not the same between mobile and desktop browsers. So I want to write separate code for mobile and desktop web, and the question is that, can/how I know the web is running on mobile or desktop browser? Thanks.

**Comment by necolas** [comment]
I can't help you because I don't understand how things are different between mobile and desktop web. If you want to try to detect mobile vs desktop you should Google for strategies to do that
