### ISSUE TITLE
[Bug]The valid props list of `View` should not have `borderXXStyle` like `borderLeftStyle`

### ISSUE THREAD

**Issue by NE-SmallTown** [necolas/react-native-web#1814]
**The problem**

The valid props list of `View` should not have `borderXXStyle` like `borderLeftStyle` because React Native only support set `borderStyle`

**How to reproduce**

Simplified test case: https://codesandbox.io/s/valid-prop-bug-ekvzp?file=/src/App.js

Steps to reproduce:
1. Open the codesandbox above, and then check the console.

![image](https://user-images.githubusercontent.com/18418010/99477159-e4758780-298c-11eb-8f8a-2bdd4a330b76.png)

**Expected behavior**

Remove the wrong valid props items. And remove them from the [doc](https://github.com/necolas/react-native-web/blob/cfe36d780e981885ce73862a9effcea29e7ea1c9/packages/docs/src/components/View/View.stories.mdx#style)

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version):  0.11.7
* React (version): 16.13.0
* Browser: TBC

**Comment by necolas** [comment]
React Native supports those style props. And even if it didn't I would support them on web. And the latest versions of RNW don't print that warning

**Comment by NE-SmallTown** [comment]
> React Native supports those style props. 

AFAIK, it doesn't. You can see the doc: https://reactnative.dev/docs/view-style-props#borderstyle

> And even if it didn't I would support them on web. 

Sure, but the (warning/error)message should be consistent with the behavior. I.e If react-native-web supports that, then it **should not** show "it doesn't support". Or, if react-native-web doesn't support that, then it **should show** "it doesn't support"

> The latest versions of RNW don't print that warning either

Yea, I notice that too. But I cant upgrade to latest for now, so I file this issue to confirm this question
