### ISSUE TITLE
FlatList Momentum and onScroll props alternative

### ISSUE THREAD

**Issue by HadiModarres** [necolas/react-native-web#1816]
As I understand none of onScrollBeginDrag, onScrollEndDrag or momentum props are supported on ScrollView and as a result on FlatList.

I would like to know if there's any way to detect long presses on the ScrollView or FlatList to try to implement above manually? 

Thanks

**Comment by necolas** [comment]
Duplicates #1021

**Comment by HadiModarres** [comment]
you didnt really answer my question though, I read that issue before. my question was if there's any way to detect presses on flatlist or scrollview
