### ISSUE TITLE
Modal styles

### ISSUE THREAD

**Issue by gesposito** [necolas/react-native-web#1818]
**Is your feature request related to a problem? Please describe.**

I need to make it so Modal has an higher `z-index`

**Describe a solution you'd like**

[getAnimationStyle](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Modal/ModalAnimation.js#L17) in [ModalAnimation](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Modal/ModalAnimation.js) might parse the `style` property and append styles.

**Describe alternatives you've considered**

I might patch it with `patch-package`

**Additional context**

**Comment by necolas** [comment]
Please describe the actual problem that leads you to believe you need to control the zindex

**Comment by gesposito** [comment]
It is common for mobile apps to have absolute positioned elements, be the top header, search bar, or buttons on the bottom

![Screenshot 2020-11-24 at 09 44 29](https://user-images.githubusercontent.com/735227/100070050-c222b480-2e39-11eb-8d0a-9a4cdb9398bd.png)

when a Modal is being shown we want to make sure all elements are covered "full screen"

using portals with no `z-index` we give all elements the same "stacking context", meaning we loose control of what is prioritized

**Comment by necolas** [comment]
Modals are appended to the document with a zindex. Please provide a test case for the problem, then I'll reopen https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Modal/ModalContent.js#L59

**Comment by gesposito** [comment]
Following up in #1820
