### ISSUE TITLE
Open External Browser from App

### ISSUE THREAD

**Issue by JijoBose** [necolas/react-native-web#1819]
How can I open an External Browser when running react-native-web inside a Mobile App in its WebView?

Code
```
  const openLink = async url => {
    const supported = await Linking.canOpenURL(url)
    if (supported) {
      await Linking.openURL(url)
    }
  }

```
The above code however redirects to a page within the WebView and not from an external Browser (eg, open with Chrome, etc)

**Comment by necolas** [comment]
Duplicates #1544
