### ISSUE TITLE
FlatList onScroll never triggers

### ISSUE THREAD

**Issue by NickHackman** [necolas/react-native-web#1827]
**The problem**

When using FlatList's onScroll property it never triggers on Web, but triggers on Android and iOS. Even when setting `scrollEventThrottle` to 16 still never causes it to trigger.

**How to reproduce**

Simplified test case: https://snack.expo.io/GWLY9XaUD

Steps to reproduce:
1. use FlatList
2. Fill screen with elements
3. set onScroll
   a. set scrollEventThrottle to 16 (iOS only)
   b. log something or do something
4. Scroll
5. Don't see the thing you wanted to occur happen

**Expected behavior**

When scrolling the onScroll callback for FlatList should be invoked.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.7
* React (version): 16.13.1
* Browser: Chrome

Using Expo for both Android/iOS and Web

**Comment by necolas** [comment]
It's working fine https://codesandbox.io/s/peaceful-hamilton-s2k1i

**Comment by NickHackman** [comment]
Thanks, sorry about that I assumed the expo snack would display the same behavior. This leads me to believe the issue is with Expo then :+1:

**Comment by necolas** [comment]
Probably works fine there too. The value you're using to update state probably isn't changing on scroll

**Comment by NickHackman** [comment]
I don't believe so, comparing https://codesandbox.io/s/funny-ptolemy-9mi1n versus https://snack.expo.io/@nickhackman/flatlist-simple same code different host provider when scrolling yields a different result, at least on Linux Chrome 87. The value does change when scrolling as expected, but not on Expo web.

**Comment by emac3** [comment]
I've got the same issue with an expo bare project apparently and if I copy-paste the working [example](https://codesandbox.io/s/peaceful-hamilton-s2k1i) above from codesandbox to expo [snack](https://snack.expo.io/LPSSWnRAr), it doesn't log on scroll on web (it logs correctly on native devices though).
I tried different expo, react, react-native and react-native-web versions, but I couldn't pinpoint the issue.
I keep investigating...

**Comment by vishalnarkhede** [comment]
Did anyone manage to resolve this issue? 

@necolas I have setup an app using `create-react-app` and only copied the code from codesandbox
https://github.com/vishalnarkhede/rnw-flatlist-example

**Comment by necolas** [comment]
You haven't looked at the index.html root elements styles. This is documented and has been covered many times

**Comment by vishalnarkhede** [comment]
@necolas Thanks a ton for quick response!! Indeed I missed that part. Cheers ;)

**Comment by mcrombie** [comment]
I am seeing this same issue for ScrollView.
