### ISSUE TITLE
TextInput with multiline=true not autogrowing

### ISSUE THREAD

**Issue by amberv0** [necolas/react-native-web#1829]
I think we need to reopen #287
Current RN Web behavior of `TextInput` with `multiline` set to `true` doesn't match the RN behavior (where the field will autoresize depending on the content height).

For this reason I mark it as a bug, and not as a feature request.

**Comment by amberv0** [comment]
Ok, I discovered that there are several open issues regarding this topic. So i will close this one i think

**Comment by Sharcoux** [comment]
The follow up is in #795
