### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by dustinsavery** [necolas/react-native-web#183]
Can you provide release notes for your releases? (Or if I'm blind and they already exist, can you point me to them please?)

**Comment by MoOx** [comment]
Notes can be find via the commit logs https://github.com/necolas/react-native-web/commits/master :)
I guess since it's still 0.0.x, @necolas don't want to bother with notes.
Btw @necolas why don't you want at least to release 0.x.y so people can have fix when relevant?

**Comment by necolas** [comment]
Yeah I'll probably publish a `0.1.0` release once we've cleared up a few things.

**Comment by dustinsavery** [comment]
@MoOx while the commit log does help to start with, a bulleted list of changes/additions/deprecations/fixes/etc. would help in narrowing down issues, rather than digging through commits in hoping to find something relevant.

**Comment by necolas** [comment]
The project is `0.0.x` so basically every release could break things
