### ISSUE TITLE
[Question] Is it possible to navigate to another screen by event?

### ISSUE THREAD

**Issue by Insullone** [necolas/react-native-web#1830]
I am using react-native-web and react navigation 5 for web app. I read documentation in react navigate for web support, it says I can use <[Link](https://reactnavigation.org/docs/link)> to navigate to new screen/page. But it seems that <Link> can only be triggered by clicking or touching, not by an event. In my case, I want to trigger screen navigation by an event, e.g. Websocket message, etc. Is it possible?

**Comment by necolas** [comment]
You'll have to refer to the react navigation docs
