### ISSUE TITLE
Can we use CSS in react-native-web for a CSS feature that is not supported by React Native?

### ISSUE THREAD

**Issue by yolpsoftware** [necolas/react-native-web#1831]
Our RN app has some screens that run on mobile and web. One screen however is only used on web. In this screen, we would like to use CSS Grids, which [unfortunately are not supported by React Native](https://react-native.canny.io/feature-requests/p/css-grid-layout-supporting).

Is there a way to use CSS when working with `react-native-web`? Of course this is a bad idea if the components are also used on platforms that don't support CSS. But if the screen is exclusively used in web scenarios, I don't see why we should not use CSS.

I could add the CSS directly to the `index.html`, but then I would have to know the CSS classes of the HTML elements generated by RNW. Can I know these at design-time?

**Comment by necolas** [comment]
CSS Grid is supported by React Native for Web

**Comment by yolpsoftware** [comment]
@necolas Thanks, but I can't find anything on it when searching for "grid" in the [docs](http://necolas.github.io/react-native-web/docs/?path=/docs/overview-getting-started--page).

[StackOverflow](https://stackoverflow.com/questions/54254256/does-react-native-support-css-grid) [does not](https://stackoverflow.com/questions/30550098/responsive-grid-in-react-native-flex) [know](https://stackoverflow.com/questions/47743472/how-to-use-grid-template-areas-in-react-inline-style) about it either.

Searching this repo for "grid" yields some results, but these are just valid props lists. There is no documentation, and I cannot find any code which translates the grid props to CSS.

On Google, the only thing I found is [this page](https://github.com/EvanBacon/AWESOME-REACT-NATIVE-WEB/blob/master/styling/grids.md) by Evan Bacon. Not sure if that is supposed to be documentation, but it does not really answer my questions:

* How can I declare `display: flex` on the container?
* The props `gridRowStart`, `gridRowEnd`, `gridColumnStart` and `gridColumnEnd` do not have any effect (Expo 39, react-native-web 0.14.8). There is no CSS generated for them.

Is there an example for CSS grids with react-native-web?

**Comment by necolas** [comment]
> I can't find anything on it when searching for "grid" in the doc

https://necolas.github.io/react-native-web/docs/?path=/docs/components-view--on-layout#style

> The props gridRowStart, gridRowEnd, gridColumnStart and gridColumnEnd do not have any effect

Set the value as a string

**Comment by yolpsoftware** [comment]
@necolas Thanks, this really works.

However, I now get the following error when running this code on iOS:

```
"gridTemplateColumns" is not a valid style property.
```

I know that React Native on iOS does not support CSS Grids. But this screen is not used on iOS. It just lives in the same app.

How can get around this error?

Also, please note that in the docs, when using the search function for the word "grid", there are no results.

**Comment by necolas** [comment]
Use `Platform` e.g. `Platform.select` to conditionally supply the style

**Comment by yairopro** [comment]
For people who pass by, looking for an answer to the title question:

###  Can we use CSS in react-native-web for a CSS feature that is not supported by React Native?

### Yes

You can pass an object to the prop `dataSet` like
```javascript
<View dataSet={{a: 1}} />
```

It will result a `div` with the following attributes:
```html
<div data-a="1" ></div>
```

And now you can add in your CSS a selection for this precise element:
```css
*[data-a=1] {
  /* ... */
}
```

**Comment by raarts** [comment]
For me this results in a TS error:

```
 Property 'dataSet' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps> & Readonly<{ children?: ReactNode; }>'.
```
