### ISSUE TITLE
Conflicting react native versions for Compatibility in documentation.

### ISSUE THREAD

**Issue by prachi-myntra** [necolas/react-native-web#1832]
Can you please clarify the Compatibility of react-native-web with react-native version ?
Found **conflicting react native versions in documentation**.

<img width="998" alt="Screenshot 2020-12-01 at 5 13 55 PM" src="https://user-images.githubusercontent.com/74350128/100736402-ad758c00-33f8-11eb-95f6-b5c27fe35a72.png">

<img width="1085" alt="Screenshot 2020-12-01 at 5 14 10 PM" src="https://user-images.githubusercontent.com/74350128/100736411-b2d2d680-33f8-11eb-8a15-efc1fb9505d5.png">

We are using react-native version : **0.61**.
Wanted to know if we can use **0.14.0** react-native-web.

**Comment by necolas** [comment]
Refer to the release notes for deprecations in each release. 0.14 is best used with 0.63 and above
