### ISSUE TITLE
Setting opacity on an Image wrapped in Text has no effect on Android

### ISSUE THREAD

**Issue by balasan** [necolas/react-native-web#1834]
**The problem**
Setting opacity on an Image wrapped in Text has no effect on Android

**How to reproduce**

```
      <Text>
        <Image
          resizeMode={'contain'}
          style={{
            width: 10,
            height: 10,
            opacity: 0.5,
          }}
          source={require(<imgUrl>)}
        />
      </Text>
```

**Expected behavior**
on Web and iOS the image renders at .5 opacity, on Android image renders at full opacity

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.4
* React (version): 16.13.1
* Browser: Android
* React Native: 0.61.5

**Workaround**

tintColor can be used as a temporary workaround on Android

**Comment by necolas** [comment]
If you're reporting a bug in react native, this is the wrong repo
