### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by findjassi** [necolas/react-native-web#1840]
Hi There,

I am struggling with the issue below when i trying to have my project running on a web version. The blank project works like a charm, but as soon as I include the outside modules, it starting breaking. Steps to recreate is to have   react-native-app-intro-slider in the dependencies and just import in the App.js. 
import AppIntroSlider from 'react-native-app-intro-slider';

I am getting the below error with the outside module installed i.e. react-native-app-intro-slider

<img width="1075" alt="Screenshot 2020-12-09 at 12 00 05" src="https://user-images.githubusercontent.com/10572588/101627319-16bb5780-3a16-11eb-9123-b8aeada242bf.png">

I tried changing the configuration of babel, like below but didn't find any luck. 
(babel.config.js)
module.exports = {
  plugins: [
    'module:@babel/plugin-syntax-jsx',
    'module:@babel/plugin-transform-react-jsx',
  ],
  presets: [
    'module:metro-react-native-babel-preset',
    'module:@babel/preset-react',
  ],
};

Tried changing this too :
module.exports = {
  plugins: [
    '@babel/plugin-syntax-jsx',
    '@babel/plugin-transform-react-jsx',
  ],
  presets: [
    'module:metro-react-native-babel-preset',
    '@babel/preset-react',
  ],
};

Nothing worked :( 

Any help will be much appreciated. Thanks

**Comment by necolas** [comment]
> // Many OSS React Native packages are not compiled to ES5 before being
> // published. If you depend on uncompiled packages they may cause webpack build
> // errors. To fix this webpack can be configured to compile to the necessary
> // `node_module`.

https://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page
