### ISSUE TITLE
[Bug]Need remove CJS export to keep all files use ESM

### ISSUE THREAD

**Issue by NE-SmallTown** [necolas/react-native-web#1842]
**The problem**

Currently there are still 4 files using CJS syntax to export, this will break our build and optimization sometimes.

https://github.com/necolas/react-native-web/blob/e03ac45173fc542f8de9063d3482dd3e4ce1ff42/packages/react-native-web/src/vendor/react-native/Animated/polyfills/flattenStyle.js#L8

https://github.com/necolas/react-native-web/blob/e03ac45173fc542f8de9063d3482dd3e4ce1ff42/packages/react-native-web/src/vendor/react-native/Animated/polyfills/Set.js#L24

https://github.com/necolas/react-native-web/blob/e03ac45173fc542f8de9063d3482dd3e4ce1ff42/packages/react-native-web/src/vendor/react-native/Animated/polyfills/InteractionManager.js#L10

https://github.com/necolas/react-native-web/blob/e03ac45173fc542f8de9063d3482dd3e4ce1ff42/packages/react-native-web/src/vendor/react-native/Animated/bezier.js#L82

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1. Check the link above.

**Expected behavior**

All files use ESM.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.0
* React (version): 16.13.0
* Browser: no need

**Comment by necolas** [comment]
Make a PR please

**Comment by NE-SmallTown** [comment]
No problem, I will do it later(this evening or tomorrow)

**Comment by NE-SmallTown** [comment]
closed for #1846
