### ISSUE TITLE
TouchableWithoutFeedback cursor style is set to default

### ISSUE THREAD

**Issue by wabisabit** [necolas/react-native-web#1847]
**The problem**
TouchableWithoutFeedback doesn't have the cursor style set to pointer.

**Expected behavior**
TouchableWithoutFeedback has the cursor style set to pointer like it had prior to 0.12

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.9
* React (version): 16.10.2
* Browser: All

**Additional context**
I'm working on a project that uses only TouchableWithoutFeedback so it would be nice to keep this style. I can create a PR if this is not a design decision.

**Comment by necolas** [comment]
Default cursor is the intended style. You can set your own cursor depending on how you're using the component

**Comment by jchook** [comment]
@necolas, what is the recommended way to add these styles?

TypeScript complains that `cursor` is not a member of `ViewStyle`.
