### ISSUE TITLE
Switch thumb is green and I can't change it

### ISSUE THREAD

**Issue by baptisteArno** [necolas/react-native-web#1848]
I implemented a simple Switch:

```tsx
        <View style={{ flexDirection: "row", alignItems: "center" }}>
          <Text style={{ ...grotesk, marginRight: 5 }}>cm</Text>
          <Switch
            trackColor={{ false: blue, true: blue }}
            onValueChange={() =>
              setMeasurementUnits(
                measurementUnits === "inches" ? "centimeters" : "inches"
              )
            }
            value={measurementUnits === "inches"}
          />
          <Text style={{ ...grotesk, marginLeft: 5 }}>inches</Text>
        </View>
```

And the thumb color is green when the switch is enabled? I can't figure out how to change this.

![CleanShot 2020-12-17 at 17 46 24](https://user-images.githubusercontent.com/16015833/102517199-0cd9ca00-4090-11eb-80c2-ce40911effc3.gif)

**Comment by necolas** [comment]
See the docs https://necolas.github.io/react-native-web/docs/?path=/docs/components-switch--active-thumb-color

**Comment by paulwongx** [comment]
New link as of Nov 5, 2011: https://necolas.github.io/react-native-web/docs/switch/

What you're looking for is `activeThumbColor` probably implemented in such a way like
```js
        <Switch
            {...Platform.select({web: {
                activeThumbColor: tw.white
            }})}
        />
```
