### ISSUE TITLE
Using Third-Party Web Libraries

### ISSUE THREAD

**Issue by aghasemi** [necolas/react-native-web#1850]
Hi,
I am quite new to the React area, so I may have gotten lost here. May I kindly ask, what is the procedure, if any, to run third-party, or custom Javascript libraries in an RNW, the same way we do with `<script>` tags in a "normal" web application?

I have created a bare project with `expo-cli`, but cannot find any `index.html`, or `src` or `public` folder. Is it possible at all to use javascript libraries in RNW?

Thanks

**Comment by necolas** [comment]
Yes, this is just a UI library sitting on top of React DOM.

You should direct questions about integrating 3rd party JS with Expo to the Expo project.

Thanks
