### ISSUE TITLE
Linear easing for loop animation?

### ISSUE THREAD

**Issue by kg-currenxie** [necolas/react-native-web#1851]
Is this a bug or limitation of rn-web?

**The problem**

![Kapture 2020-12-19 at 22 45 55](https://user-images.githubusercontent.com/48229166/102692087-03955c80-424c-11eb-8121-0f66f5bc3468.gif)

**How to reproduce**

https://codesandbox.io/s/sharp-https-30x52?file=/src/App.js

```

export const Spinner = () => {
  const animationValue = useRef(new Animated.Value(0)).current

  const startAnimation = useCallback(() => {
    Animated.timing(animationValue, {
      toValue: 1,
      duration: 800,
      useNativeDriver: true,
    }).start(() => {
      animationValue.setValue(0)
      startAnimation()
    })
  }, [animationValue])

  useEffect(() => {
    startAnimation()
  }, [startAnimation])

  const interpolatedRotation = animationValue.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '360deg'],
    easing: Easing.linear,
  })

  const animatedRotationStyle = {
    width: 32,
    height: 32,
    transform: [{ rotate: interpolatedRotation }],
  }

  return (
    <Animated.View style={animatedRotationStyle}>
```

**Expected behavior**

The animation should be completely linear and not slow down.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.3
* React (version): 16.13.1
* Browser: Chrome

**Comment by necolas** [comment]
Easing goes in the timing config not the interpolation one

**Comment by Frexuz** [comment]
#embarassed
