### ISSUE TITLE
PanResponder incorrectly cancels click (0.14.6)

### ISSUE THREAD

**Issue by raineorshine** [necolas/react-native-web#1852]
**The problem**

As of `v0.14.6`, click events on PanResponder children are cancelled, [per this addition](https://github.com/necolas/react-native-web/commit/d2e6c29e259856b81d0466217754c1107a44f014#diff-896ba59b7007443d7bfe11ef7dfc2963ed4f6584f3d6071e3e53f2ffa3b5ff79R528-R537). However, this breaks existing code that expects click events to work.

Is this intended? If so, is there a way to restore the `0.14.5` functionality?

```jsx
class MyPanComponent extends React.Component {
  constructor(props) {
    super(props);

    this.panResponder = PanResponder.create({
      onStartShouldSetPanResponder: () => true
    });
  }

  render() {
    return (
	  // click events on children are cancelled (see test case below)
      <View {...this.panResponder.panHandlers}>{this.props.children}</View>
    );
  }
}
```

**How to reproduce**

Simplified test case: https://codesandbox.io/s/silent-rain-gq0xo

Steps to reproduce:
1. Click the pink box

**Expected behavior**

The click event should fire and you should see an alert.

**Environment (include versions). Did this work in previous versions?**

This worked in `v0.14.5` and stopped working in `v0.14.6`.

* React Native for Web (version): `0.14.10`
* React (version): `16.14.0`
* Browser: Tested in Chrome and Safari

**Comment by necolas** [comment]
Do you have a specific example in mind? It's important not to fire click events when a pointer is released at the end of a pan gesture.

**Comment by raineorshine** [comment]
I have a global gesture system in which the whole app is included within a PanResponder. When the user swipes, it activates the PanResponder and dispatches the appropriate action. When a user clicks on a link, the click handler should work as usual. The PanResponder and click handlers worked together without any issues in my case. 

I had assumed the PanResponder would only be activated on swipe rather than on click.

**Comment by necolas** [comment]
If you only want to activate it on move, you should use `onMoveShouldSetPanResponder` instead: https://codesandbox.io/s/mutable-sky-lrvds

**Comment by raineorshine** [comment]
Thanks, I'll try thatt.

**Comment by raineorshine** [comment]
Thank you, removing `onStartShouldSetPanResponder` and only using `onMoveShouldSetPanResponder` worked.
