### ISSUE TITLE
Add role="switch" in Switch component's checkbox

### ISSUE THREAD

**Issue by intergalacticspacehighway** [necolas/react-native-web#1856]
**Is your feature request related to a problem? Please describe.**
Switch component is read as a "checkbox" by a ScreenReader (I've tested using VoiceOver)

**Describe a solution you'd like**
Add a role="switch" attribute in checkbox being used to implement Switch

**Describe alternatives you've considered**
Not sure.

**Additional context**
https://www.w3.org/TR/wai-aria-1.1/#switch

**Comment by necolas** [comment]
Fixed by #1855
