### ISSUE TITLE
Only show Tab Bar when using react-native-web with @react-navigation/bottom-tabs

### ISSUE THREAD

**Issue by dinhquan** [necolas/react-native-web#1859]
**Current Behavior**

The screen content doesn't appear on the web, it only shows the Tab Bar. It works fine on iOS and Android.

```
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {NavigationContainer} from '@react-navigation/native';
import React from 'react';
import {Text, View} from 'react-native';

const HomeScreen = () => {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>This is the home screen</Text>
    </View>
  );
};

const RootView = () => {
  const Tab = createBottomTabNavigator();
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
};

export default React.memo(RootView);

```
On web:

<img width="821" alt="Screen Shot 2020-12-31 at 10 33 56 AM" src="https://user-images.githubusercontent.com/1617852/103393158-ecac0f80-4b53-11eb-96ac-bf586106aae1.png">

On iOS:

<img width="377" alt="Screen Shot 2020-12-31 at 10 43 16 AM" src="https://user-images.githubusercontent.com/1617852/103393266-66dc9400-4b54-11eb-952f-531b6cdf1b58.png">

There's the same issue on stackoverflow but no answer yet:
https://stackoverflow.com/questions/64264743/react-navigation-bottom-tabs-occupying-the-whole-screen-in-react-native-web

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |^5.8.10
| @react-navigation/bottom-tabs |^5.11.2"
| react-native-screens          |^2.16.1
| react-native                  |0.63.3
| react-native-web|^0.14.10

**Comment by necolas** [comment]
See https://necolas.github.io/react-native-web/docs/?path=/docs/guides-web-recipes--page#html-and-body-styles

**Comment by dinhquan** [comment]
Thanks @necolas. Set style for html & body works perfectly.
