### ISSUE TITLE
ScrollView: showsHorizontalScrollIndicator/showsVerticalScrollIndicator

### ISSUE THREAD

**Issue by miketheanimal** [necolas/react-native-web#186]
ScrollView does not honour:

showsHorizontalScrollIndicator
showsVerticalScrollIndicator

The scoll bar still appear, and generates a warning in the console:

Warning: Unknown prop `showsHorizontalScrollIndicator` on <div> tag.

OS: Linux
Device: Desktop
Browser: Chrome
React Native for Web (version): 0.0.41
React (version): 15.3.0

Regards
Mike

**Comment by necolas** [comment]
Not really sure this is something web needs or could support

**Comment by miketheanimal** [comment]
I guess you are right; in which case, in this sort of case, could the code output a "this is not supported by react native web" message?

**Comment by necolas** [comment]
Yes something like that sounds sensible. I'll take proper look within the next few days. Thanks

**Comment by MoOx** [comment]
I just got

```
Warning: Unknown prop `showsHorizontalScrollIndicator` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (at index.js:35)
    in View (at ScrollViewBase.js:94)
    in ScrollViewBase (at index.js:208)
    in ScrollView (at index.js:50)
    ...
```

It's because I added props when working on RN app :)

One thing we could do is just remove this prop before building the div so React don't warn on unknown props. Docs can just say "not supported", I am not sure it make sense to "pollute" the console.

**Comment by MoOx** [comment]
Btw, same issue with `bounces`.

**Comment by necolas** [comment]
Fixed by abd1227a948e4680b69e937493c17d12653a6362

You'll have to filter iOS-specific props yourself for now.

**Comment by Elijen** [comment]
@necolas Is this really something that cannot be supported? It's not uncommon thing to use a scrollable div without displaying the actual scrollbar.

**Comment by yadirhb** [comment]
Is there any solution on this issue? Or did anyone manage to hide the scrollbar in a FlatList?

**Comment by shrikantr-iprogrammer** [comment]
Is there any solution on this issue? Or did anyone manage to hide the scrollbar in a FlatList?
