### ISSUE TITLE
Support for onKeyDown in Pressable.

### ISSUE THREAD

**Issue by intergalacticspacehighway** [necolas/react-native-web#1862]
**Is your feature request related to a problem? Please describe.**
I am trying to create a Typeahead component that works on RN and RN-Web. 
I am using Pressable as a Trigger element. I need to open the Typeahead using Arrow keys (Up/Down).
Currently, Pressable prevents passing onKeyDown into the underlying View component. Line 154 (pressEventHandler overrides it). 
<img width="856" alt="Screenshot 2021-01-03 at 9 28 05 PM" src="https://user-images.githubusercontent.com/23293248/103483045-961c2b00-4e0a-11eb-8fcf-7ed645470dc0.png">

**Describe a solution you'd like**
I am not sure if this is overridden for some purpose but chaining the onKeyDown instead of overriding is one option.

**Describe alternatives you've considered**
I'll have to conditionally use a button/div for the web platform and attach onKeyDown.

**Additional context**
I can raise a PR that chains onKeyDown. 
Pressable lets you pass onKeyUp and other events. I just feel onKeyDown should also be passed. Please let me know if I am missing something. Thanks for your time and efforts on the project 😄

**Comment by necolas** [comment]
You can use `onPressIn` which receives the keydown event when it occurs

**Comment by intergalacticspacehighway** [comment]
@necolas thanks for responding, but I need keyDown events to detect key type (In my case, arrow key up and down).
pressIn only triggers on spacebar/enter. Correct me if I am wrong. 😅 
Again, thanks for your efforts!

**Comment by necolas** [comment]
Yeah a Pressable doesn't expose that. You should use a native event handler with a hook. That's actually how I think we'll do all events in future interested of React restrictive props API. Let me know if the ref prop isn't available.

**Comment by intergalacticspacehighway** [comment]
Thanks, @necolas. Makes sense. I will also be needing onPointer events that currently are not whitelisted here [forwardPropsList](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/View/index.js#L25).
Should I raise a PR to add this to documentation in web recipes? 
A simple note that if you need to attach such event handlers, use the ref.

**Comment by intergalacticspacehighway** [comment]
@necolas New documentation mentions that Pressable [inherits ViewProps](https://necolas.github.io/react-native-web/docs/pressable/#props) which indirectly indicates that it supports onKeyDown. 
Let me know If you still think we should add this. It's a few lines of changes 😅. I'll generate a PR.

**Comment by arthurpankiewicz** [comment]
Support for `onKeyDown` for `TextInput`s would be great as well

@intergalacticspacehighway do you know of any workaround to capture `onKeyDown` for the time being?

**Comment by intergalacticspacehighway** [comment]
@arthurpankiewicz TextInput supports onKeyPress which is same as onKeyDown.

For Pressable, I am just attaching onkeydown on it's ref. It would be great if it supports onKeyDown.

**Comment by arthurpankiewicz** [comment]
@intergalacticspacehighway `TextInput` and `onKeyPress` are slightly different. It triggers after the full cycle (`onKeyDown->onKeyUp`) from my understanding. I need the event to fire off when a key is being held down, so I explicitly require `onKeyDown`

**Comment by intergalacticspacehighway** [comment]
@arthurpankiewicz For the time being, instead of using onKeyDown I am using onKeyDownCapture in Pressable. onKeyDownCapture can be used with Pressable.

**Comment by paulwongx** [comment]
I can't seem to escape the typescript issue saying no overload matches this call. @intergalacticspacehighway Do you mind sharing how you wrote it? Using both onKeyDown and onKeyDownCapture still results in a typescript error.

```tsx
<Pressable 
     onPress={handlePress}
     {...Platform.select({web: {onKeyDownCapture: (e) => handleKeyDown(e)} })}
/>
```
