### ISSUE TITLE
accessibilityRole='Link' Views are not included in tabbing order

### ISSUE THREAD

**Issue by tj-mc** [necolas/react-native-web#1865]
**The problem**
[This docs page](https://github.com/necolas/react-native-web/blob/master/packages/docs/src/guides/accessibility.stories.mdx) states that Touchables with roles of `link` and `button` are accessible and given a tab index. This works as expected with `accessibilityRole={'button'}`, but when using `accessibilityRole={'link'}`, Touchables are not given a `tabindex`.

**How to reproduce**
Simplified test case: [Sandbox](https://codesandbox.io/s/priceless-dawn-ekh4y?file=/src/App.js)

Steps to reproduce:
1. Open app in fullscreen browser
2. Press tab to reach 'Link'
3. Note that it is skipped

**Expected behavior**
Link is included in tabbing order, like with button

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.10
* React (version): 16.13.1
* Browser: Chrome 87.0.4280.88

**Additional context**
If this is not the intended behavior, we should clarify this in the docs. Happy to make a PR for any of this too. Thanks for your work @necolas!

**Comment by necolas** [comment]
I can fix this, but the use cases for using a touchable without an `href` are very limited. Using a href will put it in the tab flow

**Comment by tj-mc** [comment]
Thanks for the reply. In my own use case extra logic is needed in the onPress, so I can't use a simple href. I can revert this to a button, but it would be great to have a way of semantically identifying this as a link for accessibility purposes, without being forced to use href, as I don't think this has a meaning to native platforms. 

Do you have any thoughts on how to tackle this?

**Comment by necolas** [comment]
If you're targeting the web you must include `href` attributes and follow standard web patterns for navigation

**Comment by tj-mc** [comment]
That makes sense. I guess if logic is required on press, it's more of a button.

**Comment by necolas** [comment]
You can still perform logic in a press handler for a link. That is typical for web apps, which may also prevent the default native navigation behavior of the link
