### ISSUE TITLE
Setting selectable={false} should prevent mouse cursor to change when hovering text / icons

### ISSUE THREAD

**Issue by sreuter** [necolas/react-native-web#1866]
**The problem**

When using `selectable={false}` the mouse cursor still changes to a text selector one when hovering text, even tho it's not selectable.

**How to reproduce**

Add `selectable={false}` to a `<Text>` component

**Expected behaviour**

Mouse cursor should stay being a pointer.

**Comment by tj-mc** [comment]
`selectable` is[ False by default in RN](https://reactnative.dev/docs/next/text#selectable). However, we need text to be selectable on the web as this is important for accessibility and general usability. The only case where it make sense to disable this is for Touchables, Pressables, etc where these are button and part of the a11y tabbing order.

Pretty much all text content on the web is selectable, what is your use case to disable it?

**Comment by sreuter** [comment]
@tj-mc Thanks for your reply. I agree with your argument in general, but IconSet's are using Text as well. I don't think there's a value in having those selectable, as they use special fonts/characters. My main problem tho is with the mouse cursor changing from cursor to text select, even if selectable is set to false.

**Comment by sreuter** [comment]
I just realized this was already fixed for `<Pressable>` in the latest version: https://github.com/necolas/react-native-web/issues/1764 .. Do think it makes sense to apply the same for `<TouchableWithoutFeedback>`?

**Comment by necolas** [comment]
This issue is not clearly explained and is missing a reproducible test case. As far as I understand, you are expecting the cursor for `TouchableWithoutFeedback` to be a pointer, but it is left as a default cursor because this component provides no feedback and it is up to the developer to style in response to state change.

https://codesandbox.io/s/strange-grass-yrjhd

**Comment by soot-joshua** [comment]
@sreuter https://latency-harsh.github.io/google-api-nodejs-client/
