### ISSUE TITLE
code split for react native web

### ISSUE THREAD

**Issue by MillionStrengthKnowledge** [necolas/react-native-web#1872]
I am using react native web to develop my web application.

I want to create code-split for my web application.

From my research on the web, I found that react web application has some code-split methods, which is shown in https://reactjs.org/docs/code-splitting.html

Does react native web supports these code-split techniques: import(), react.lazy, and other techniques shown in the code-splitting.html?

Can the code split works for web application and also mobile application with the same code base?

**Comment by necolas** [comment]
Yeah, this package is made of javascript modules which can be part of code-splitting strategies
