### ISSUE TITLE
Responsive Resize

### ISSUE THREAD

**Issue by haveamission** [necolas/react-native-web#1877]
**Is your feature request related to a problem? Please describe.**
I see no clear and easy way to resize responsively, like in a normal web browser

**Describe a solution you'd like**
Some way that resizes based on browser updates

There seems to be no easy way to resize everything - I've tried re-renders and all sorts of other ideas and libraries based on this, and nothing seems to update in real time as you resize the window.

**Comment by necolas** [comment]
Dimensions API and onLayout prop. See the docs for more info

**Comment by haveamission** [comment]
So I essentially have to put style resize into each component, rather than a stylesheet? Ok then...
