### ISSUE TITLE
Header issue on iOS devices

### ISSUE THREAD

**Issue by brar07** [necolas/react-native-web#1879]
When using react-native-web library and using the Stack Navigator, along with header, there is an issue, in which header doesn't stick up top, the issue may be regarding scrollview, but, this issue is only in iOS devices and not on Android devices. I ended up embedding a header in all the screens and if any of you guyz know a better solution or workaround, please, do comment below.

Here's link to the video: https://imgur.com/P3Ji5Tz

**Comment by necolas** [comment]
Closing this issue as it ignores the required issue template format, and seems to be about react-navigation, which is developed in a different repo

**Comment by brar07** [comment]
Ok, but, the issue isn't regarding react-navigation as it works when used in react-native app on both iOS and Android version of apps. But, it just doesn't work when used in react-native-web and opened in Safari on iOS devices.
The issue, I think, is with how ScrollView/FlatList is rendered using react-native-web, as when I removed ScrollView, it worked. So, it is something to do with content size, maybe.
Here's some code, that I am using.
`const Stack = createStackNavigator();

const AuthNavigator = () => (
  <Stack.Navigator
    screenOptions={{
      cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
      headerShown: true,
      headerTitle: (navigation) => (
        <Header navigation={navigation} title="BLUE CARD VISA" />
      ),
      headerStyle: {
        backgroundColor: colors.white,
      },
      headerTitleAlign: "center",
      headerTintColor: colors.primary,
    }}
  >
    <Stack.Screen
      name="Login"
      component={LoginScreen}
    />
    <Stack.Screen
      name="Signup"
      component={SignupScreen}
    />
  </Stack.Navigator>
);

export default AuthNavigator;`

And, here is the SignupScreen:
`return (
    <Screen style={styles.container}>
      <ScrollView
        style={{
          flex: 1,
          flexDirection: "column",
          marginBottom: 60,
        }}
        keyboardShouldPersistTaps="handled"
      >
      ....
      </ScrollView>
       <View style={{ position: "absolute", bottom: 0 }}>
        <CommonFooter navigation={navigation} />
      </View>
      </Screen>
      );
`
