### ISSUE TITLE
How about mock appdelete config other than write configuration to js file?

### ISSUE THREAD

**Issue by Obooman** [necolas/react-native-web#188]
As a react-native developer, I think write `AppRegistry.runApplication` within index.ios.js or other business code is weird.How about move configs like this to another indepedent js file as a react-native-web app config? It will make the two parts split both of them will be more pure.

for example
```js
// AppDelegate.js

var ReactNativeWebInit = require('react-native-web').init // or something like this

var jsCodeLocation = "http://localhost:8082/index.ios.bundle?dev=true"
var RootView = {
  DOM:document.getElementById('react-root'),
  jsCodeLocation:jsCodeLocation,
  moduleName:'MyApp',
  initialProperties:{
    init:true
  }
}

ReactNativeWebInit(RootView);
```

**Comment by necolas** [comment]
Thanks. You might want to post API suggestions to the react-native repo
