### ISSUE TITLE
Pressable and touchables should maybe fire onClick too

### ISSUE THREAD

**Issue by yairopro** [necolas/react-native-web#1883]
### The problem

Touchables (and the `Pressable` component) don't fire `onClick` callback.

**Why do you need it ? Just use onPress**
`react-navigation` asks to [set the `onClick` callback in order to create links](https://reactnavigation.org/docs/use-link-props) that won't reload the entire page.

**Well just use a `View`**
I guess I can do so, that's what makes this issue not really important, maybe not even an issue at all for some, but I currently still use `Pressable`, because I need the effects when pressing. And my current workaround is to redirect the `event.nativeEvent` to the `onClick`.

### How to reproduce

Just set a `onClick` on a touchable.
In the demo below, just click on the pink background, there won't be no log.
Simplified test case: https://codesandbox.io/s/touchable-onclick-not-triggered-dmyq7

Steps to reproduce:
1. Place a `TouchableOpacity`
2. Set its `onClick={console.log}`
3. Press it, and you won't see any log

### Expected behavior
`onClick` to be called with the nativeEvent as parameter.

Environment (include versions). Did this work in previous versions?
Maybe.

* React Native for Web (version): 0.14.10
* React (version): 17.0.1
* Browser: Chrome 87

**Comment by necolas** [comment]
The react-navigation advice is incorrect. onPress is equivalent to onClick and should be used instead

**Comment by yairopro** [comment]
Ok 👍🏻
