### ISSUE TITLE
Intersection observer type error

### ISSUE THREAD

**Issue by ericlifs** [necolas/react-native-web#1884]
**The problem**
I've been trying to create a `useIsInViewport` hook which uses `Intersection Observer` in order to detect when an specific element of the DOM enters (or leaves) the viewport but I've been having the following error:

![image](https://user-images.githubusercontent.com/7376892/105859568-6e645100-5fcb-11eb-98fc-180e850434a1.png)

I have console logged the ref within the hook (when I call the observer.observe) and the element itself is a View. IDK if there is a way of getting the transformed DOM Element after react-native-web does it magic.

**How to reproduce**
This is the hook I've created:

```
import { RefObject, useEffect, useState } from 'react';

const useIsInViewport = (blockRef: RefObject<any>): boolean => {
  const [isInViewport, setIsInViewport] = useState(false);

  const observer = new IntersectionObserver(([entry]) => {
    setIsInViewport(entry.isIntersecting);
  }, {});

  useEffect(() => {
    if (blockRef.current) {
      observer.observe(blockRef.current);
    }
  }, [blockRef.current]);

  return isInViewport;
};

export default useIsInViewport;
```

Steps to reproduce:
1. Create any component that you want using react-native
2. Add a ref to a View (or any element) from that component
3. Import the hook and call it by doing `const isInViewport = useIsInViewport(myElementRef)`

**Expected behavior**
The type error shouldn't happen and the hook should work fine.

**Comment by necolas** [comment]
I'll reopen this issue if you provide the required reduced test case asked for in the issue template, and can demonstrate that your problem is rooted in RNW
