### ISSUE TITLE
Use with Next.js routing?

### ISSUE THREAD

**Issue by baptisteArno** [necolas/react-native-web#1885]
**The problem**

I'm using Next.js routing tools to handle navigation in my react-native-web app and it has strange behaviors that doesn't correspond to Next.js documentation.

When I use Link like this:
```
<Link href={path}>
    <a>...</a>
</Link>
```

 It loads the new page. I think this is the correct behavior. But if I need to navigate to the new page without the browser loading it (like in a SPA):

```
<Link href={path} shallow={true}>
    <a>...</a>
</Link>
```

it doesn't change anything.

Also when using the `Router.push` method with default properties, the browser is supposed to load the new page but instead it navigates straight to the new route without a browser loading.

**How to reproduce**
Steps to reproduce:
1. Clone the [with-react-native-web Next.js example](https://github.com/vercel/next.js/tree/canary/examples/with-react-native-web)
2. Play with `Link` and `push`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.14.10
* React (version): 17.0.1
* Browser: Chrome

**Comment by necolas** [comment]
There's nothing in RNW that should be causing problems. If Next is behaving as you expect you should open an issue against that repo. Closing this as there is no link to a test case and not enough info to point to this being a RNW issue (since you're not even using the RNW components it seems).

**Comment by baptisteArno** [comment]
Thank you for your reply @necolas. Sorry for the missing details.

After more test I found out that the problem is only appearing whenever there is a `TouchableOpacity` in the `<Link>` component :

This
```
<Link href={path}>
  <Text>Link</Text>
</Link>
```
works as expected

This:
```
<Link href={path}>
  <TouchableOpacity>
     <Text>Link</Text>
  </TouchableOpacity>
</Link>
```
doesn't

Do you know have an idea why this is happening?

**Comment by steida** [comment]
@baptisteArno I remember there were some issues with TouchableOpacity but I am using Pressable instead and it works.

![Screenshot 2021-01-28 at 21 53 23](https://user-images.githubusercontent.com/66249/106197665-42a3bf80-61b3-11eb-8f50-5b37b4b29510.png)

**Comment by steida** [comment]
So I tried to integrate Next.js Link with Pressable on the same element to get hover state again, and learned it's not possible.

Pressable has to be separated from Next.js Link.
Next.js Link works properly only with RNfW Text because only Text supports onClick.
Pressable does not support onClick and we can't manually handle it via onPress, because we would have to clone Next.js behavior.
