### ISSUE TITLE
View component does not support `focusable` prop.

### ISSUE THREAD

**Issue by roryabraham** [necolas/react-native-web#1886]
**Is your feature request related to a problem? Please describe.**
There are some times where I would like a view or button to _not_ be focusable via keyboard events. React Native supports a `focusable` prop for `View` on Android. It would be awesome to see that feature on web too.

**Describe a solution you'd like**
An optional prop `focusable` for the react-native-web `View` component, which, if `false`, would prevent the div from being focusable. It would probably be `true` by default.

**Describe alternatives you've considered**
I haven't considered any alternatives. This is not mission-critical for me and has pretty easy workaround, but would be nice-to-have nonetheless.

**Additional context**
I ran into this while setting up keyboard event listeners, and found that if a `TouchableOpacity` has focus, then the `Enter` key will trigger the `onPress` event. I can suppress the behavior by just checking for the presence of a `key` field on the event, but it might be better if the `TouchableOpacity` wasn't focusable at all. It would also prevent my having to deal with unwanted default styles like this blue border:

![image](https://user-images.githubusercontent.com/47436092/106189993-de0a4580-615d-11eb-8071-381a95576187.png)

**Comment by necolas** [comment]
Agreed. The prop should make an appearance in 0.15 and I will follow React Native for Windows in eventually removing the `accessible` prop too
