### ISSUE TITLE
No platform.web.js in Utilities on react-native 

### ISSUE THREAD

**Issue by Kiran0791** [necolas/react-native-web#1887]
**ERROR in ./node_modules/react-native/Libraries/Image/AssetSourceResolver.js 1:341-373
Module not found: Error: Can't resolve '../Utilities/Platform' in 'node_modules/react-native/Libraries/Image'**

**Comment by andy-clapham** [comment]
Seems to still be affecting some rn libraries.
Adding an alias in webpack.config to '../Utilities/Platform' to the react-native-web version fixes it for me, would be interesting if there is a systemic fix for the library.

**Comment by wassimAJ** [comment]
@andy-clapham can you show me how you added the alias in webpack.config please?

**Comment by TheEhsanSarshar** [comment]
I still get this error @andy-clapham

**Comment by andy-clapham** [comment]
Are you getting the exact same error for Platform?
I'm no longer using RN so I don't think I can help much ... sorry.

**Comment by 17Amir17** [comment]
Hey guys, incase anyone is still seeing this here is how I was able to fix
In my case this was caused because my library exports a native component
I was able to fix this by shimming the import
`metro.config.js`
```js
const webAliases = {
  "react-native/Libraries/Utilities/codegenNativeComponent": // <-- shimming /codegenNativeComponent
    "@10play/react-native-web-webview/shim",
};

config.resolver.resolveRequest = (
  context,
  realModuleName,
  platform,
  moduleName
) => {
  if (platform === "web") {
    const alias = webAliases[realModuleName];
    if (alias) {
      return {
        filePath: require.resolve(alias),
        type: "sourceFile",
      };
    }
  }
  return context.resolveRequest(context, realModuleName, platform, moduleName);
};
```

`shim.js`
```js
export default function () {
  return null;
}
```

If you are using webpack to bundle you can 

```js
  config.resolve.fallback = {
    ...config.resolve.fallback,
    "react-native/Libraries/Utilities/codegenNativeComponent":
      "@10play/react-native-web-webview/shim",
  };
```

Again this was broken for me because my library exported a native component, but there may also be some other cases, so you should figure out which import breaks you app and simply shim it.

**Comment by acrabb** [comment]
@Priyanshu2117 
Here was my error:

```
Unable to resolve "../../Utilities/Platform" from "node_modules/react-native/Libraries/NewAppScreen/components/DebugInstructions.js"
```

My code was using an import for `react-native/Libraries/NewAppScreen` in a couple places. Removing this import fixed it.
```
import { Colors } from "react-native/Libraries/NewAppScreen"
```

**Comment by ShayanRezvanii** [comment]
thank a lot @acrabb

**Comment by KamadoSama** [comment]
> [@Priyanshu2117](https://github.com/Priyanshu2117) Here was my error:
> 
> ```
> Unable to resolve "../../Utilities/Platform" from "node_modules/react-native/Libraries/NewAppScreen/components/DebugInstructions.js"
> ```
> 
> My code was using an import for `react-native/Libraries/NewAppScreen` in a couple places. Removing this import fixed it.
> 
> ```
> import { Colors } from "react-native/Libraries/NewAppScreen"
> ```

Thanks so much it's work for me
