### ISSUE TITLE
Support rollup bundling

### ISSUE THREAD

**Issue by gluck** [necolas/react-native-web#1894]
**The problem**
react-native-web can't be bundled using rollup.

**How to reproduce**
bundling with rollup with NODE_ENV=development results in remaining `require` calls in output.

**Expected behavior**
Mixing CJS require calls in ESM files seems to be a bad practice (although supported by webpack).
See https://github.com/rollup/plugins/issues/441

**Environment**

* React Native for Web (version): 0.14.11
* React (version): *
* Browser: *

**Workaround**
Bundling in production mode works because the 2 require calls are for optional debugging helpers.

**Fix**
Replace dynamic require calls by top-level ESM imports, output size & behavior shouldn't change because of tree-shaking:
[mixInEventEmitter.js](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/vendor/react-native/emitter/mixInEventEmitter.js#L123-L126)
[StyleSheet.js](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/StyleSheet.js#L49-L53)

Let me know if you agree, and I can do the PR.

**Comment by necolas** [comment]
> Let me know if you agree, and I can do the PR.

Yep. That would be good. Thanks

**Comment by necolas** [comment]
Fix by #1895
