### ISSUE TITLE
0.15 canary release

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1897]
The **0.15** canary release is now available for testing and feedback. PR: #1898

```
npm i react-native-web@canary
```

# Release notes

This release introduces improved accessibility features and new documentation. It includes relatively minor breaking changes.

## Breaking changes

* React 17 is a peer dependency.
* The `I18nManager` API has removed the `isRTL` and `doLeftAndRightSwapInRTL` properties. They must now be accessed using the `getConstants()` method, which returns an object with the same properties. This was an undocumented breaking change in a previous version of React Native.
* The `focusable` prop now determines whether an element appears in the keyboard tab flow.
* The `hrefAttrs` prop has been added to `Text` and `View`. The value is an object with `rel`, `target`, and `download` properties. This replaces the undocumented `rel` and `target` props.
* The automatic addition of `rel="noopener"` to anchors has been removed.
* The `Linking.openURL(url)` API now opens the url in new tab.
* The `Linking` API now includes the `addEventListener` methods.
* The deprecated `importantForAccessibility` prop has been removed. Use `accessibilityHidden` instead.
* The undocumented `data-focusable` attribute has also been removed from rendered DOM nodes.

## New features

* Pressable has added `onHoverIn` and `onHoverOut` props.
* All ARIA properties are now supported via equivalent `accessibility*` props. The undocumented support for `aria-*` prop forwarding remains and will be removed in a future version.
* Additional `accessibilityRole` values are mapped to HTML element equivalents.
* CSS `aspectRatio` property is now available in browsers with support.

## Deprecations

* The `accessible` prop is deprecated and will be removed in the next minor release. React Native for Web will follow React Native for Windows/macOS in removing this prop. Use `focusable` instead.

# Documentation

This release will include a rewrite of the documentation site and interactive examples. A preview of the documentation can be found below:

### https://necolas.github.io/react-native-web/canary/

![image](https://user-images.githubusercontent.com/239676/107107413-9af74480-67e5-11eb-8fcd-49cffced46fe.png)

The examples will be embedded in relevant pages via a Next.js-powered codesandbox, making it easy for people to fork the example app from their browsers. At the moment the examples are copy-paste from the previous docs but will get a bit of a visual makeover later.

**Comment by necolas** [comment]
Documentation fixes required:

- [ ] Typos in "Multiplatform", "Accessibility", and "Localization" pages.
- [ ] Styling: Add shadow props to non-standard props list
- [ ] Pressable: document hover props

**Comment by necolas** [comment]
Note that I've reverted the removal of `accessible` and it will instead be deprecated before being removed in the next minor.

Also fixed a bug in the canary release to get the new accessibility props working as described.

**Comment by blackbing** [comment]
Will include this? https://github.com/necolas/react-native-web/issues/1786

**Comment by necolas** [comment]
> Will include this? #1786

![image](https://user-images.githubusercontent.com/239676/107721773-53affe80-6c92-11eb-8af6-49d7d887415c.png)

**Comment by necolas** [comment]
This release is now public

**Comment by ally0426** [comment]
Please remove me from thus list. Thank you.
