### ISSUE TITLE
Components become unresponsive on mobile safari when adding third party React DOM components (Material-UI).

### ISSUE THREAD

**Issue by chsrlnd** [necolas/react-native-web#191]
I'm trying to implement a simple app using React Native for Web and Material-UI for
extra components. I noticed that when adding certain Material-UI components, such a radio button, other components (not limited to just Material-UI components) became unresponsive on mobile safari only.

The JSX code works under React DOM, so I think the issue lies in React Native for Web. I realize that React Native for Web is new and this is a very specific issue which might not even be related to React Native for Web but I was wondering if this is something that should be possible or not. If so, please let me know if I can help dig further into it.

Here is the code I am trying to use. In this case, the TextInput becomes unresponsive due
to the radio button group.

```

export class App extends Component {
  render() {
    return (
      <View>

        <TextInput
          accessibilityLabel='Write a status update'
          maxNumberOfLines={5}
          multiline
          numberOfLines={2}
          placeholder={`What's happening?`}
        />


        <MuiThemeProvider>
          <RadioButtonGroup name="productClass" defaultSelected="not_light">
              <RadioButton value="light" label="Option1"  value="1" />
              <RadioButton value="light" label="Option2"  value="2"   />
              <RadioButton value="light" label="Option3"  value="3"  />
          </RadioButtonGroup>
        </MuiThemeProvider>



      </View>

    );
  }
}

```

OS: OS X 10.11.6 for development, simulator version 9.3
Device: Simulator
Browser: Mobile safari
React Native for Web (version): 0.0.39
React (version): 15.1.0

**Comment by necolas** [comment]
Thanks. Please can you try a couple of things to help me get to the bottom of this:

1. Update to react@15.3 and react-native-web@0.0.43
2. Create a reduced test case in codepen

**Comment by chsrlnd** [comment]
Wow, I feel silly, didn't even realize react-native-web was outdated. Updated it fixed this issue, thanks!

**Comment by necolas** [comment]
Hah, I wonder what the problem was though :)

**Comment by MoOx** [comment]
My 2 cents: I don't want to beat up on the back of material-ui project, but I tried it on a project for 2 months, and got a tons of issues and inconsistencies... Don't waste too much time on this ;) react-toolbox seems a better project to have "google material design" components.

**Comment by chsrlnd** [comment]
Thanks again guys. Might be worth pointing out - I noticed the reason why I had an outdated version was because react-native-web-starter requires only 0.0.39, not sure if this is something that should be addressed or not.
