### ISSUE TITLE
After upgrading to 0.15.0 from 0.13.1 I am getting React Warning's

### ISSUE THREAD

**Issue by dirindon** [necolas/react-native-web#1911]
**The problem**

This warning appear's after launching the web page : 

'index.js:1 Warning: React does not recognize the `enterKeyHint` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `enterkeyhint` instead. If you accidentally passed it from a parent component, remove it from the DOM element.'

Steps to reproduce:
1. Add TextInput
2. Make sure you have same versions as I do (react native web etc)
3. Launch page via.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.63.2
* React (version): 16.13.1
* Browser: Chrome

**Comment by dirindon** [comment]
marked for deletion.

**Comment by fortezhuo** [comment]
@dirindon I get same warning.. How do you solve the problem?

**Comment by dirindon** [comment]
I updated both both : "react" and "react-native"

**Comment by foureyedraven** [comment]
> I updated both : "react" and "react-native"

Which versions are you using for each of these? I updated to 17.0.1 and 0.63.4, and react-native-web 0.15.0, the warning persists

**Comment by pslyman** [comment]
I got the same error. I had to go through and start upgrading all of my packages. Eventually the error went away. Wish I could say which package is was, but I have no idea.
