### ISSUE TITLE
Missing from react-native-web : LayoutChangeEvent, KeyboardEventListener, ScreenRect, NativeSyntheticEvent, TextInputKeyPressEventData

### ISSUE THREAD

**Issue by kopax** [necolas/react-native-web#1920]
**Is your feature request related to a problem? Please describe.**

In the process of using `react-native-web` for porting for the web our **iOS and Android application**, we have listed the missing component from `react-native-web`: 

- LayoutChangeEvent
- KeyboardEventListener
- ScreenRect
- NativeSyntheticEvent
- TextInputKeyPressEventData

**Describe a solution you'd like**

Since those are not exported from this package, and our import looks like `import { Layout } from 'react-native'`, I am worried about webpack replacing `react-native` with `react-native-web`.

**Describe alternatives you've considered**

How can we solve the missing dependencies issues?

**Additional context**

Using `react-native@0.63.3`, and I believe the latest version of `react-native-web`

**Comment by necolas** [comment]
None of those are exported from RN. If you're looking for types, there's an existing issue open. If you're using typescript there is a 3rd party effort to maintain types for RN

**Comment by kopax** [comment]
Thanks @necolas for your reply. What are the 3rd party package you are referring too please? Also is there a guide we can follow to add react-native-web to our bare native application that currently run only on iOS and Android?  (Source code is [here](https://github.com/pass-culture/pass-culture-app-native))

**Comment by necolas** [comment]
There is a guide on the documentation website. I don't remember the packages but you can try googling for it or searching through the repo issues
