### ISSUE TITLE
Memory leak in StyleSheet.create

### ISSUE THREAD

**Issue by JetA2** [necolas/react-native-web#1925]
**The problem**
When creating a style sheet, the object gets registered in [ReactNativePropRegistry](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/ReactNativePropRegistry.js). The registry is a module-scoped map where the object is added with a unique key. This object will never be removed from the map. This is a problem for style sheets that contain dynamic properties and need to be recreated.

In React Native, the same code does not cause an issue since the ReactNativePropRegistry does not exist anymore and StyleSheet.create just returns the object passed in.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/boring-lumiere-c2pw4

Steps to reproduce:
1. Start performance profiling in Chrome DevTools.
2. Force garbage collection
3. Press the button a number of times
4. Force garbage collection
5. End performance profiling
6. Observe the rise in allocated memory

**Expected behavior**
The memory should be reclaimed on garbage collection, or there should be a way of "deleting" a created style sheet.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.15.0
* React (version): 17.0.1
* Browser: Chrome Version 88.0.4324.192 (Official Build) (x86_64)

Perhaps ReactNativePropRegistry could be dropped from react-native-web, to align with react-native?

**Comment by necolas** [comment]
You shouldn't use StyleSheet for dynamic properties or within the body of a component

**Comment by steida** [comment]
@necolas How would you implement light/dark themes with RNfW? Thank you.

**Comment by JetA2** [comment]
I suppose it's easy to just create a normal map with the style properties for dynamic styles. With TypeScript there's a bit of casting you have to do but it works.

It's just that it's a bit of a trap when working RN code suddenly creates memory leaks when built with RNW. I can't recall seeing any warnings from the RN team about using StyleSheet for dynamic properties or within the body of a component so others may make the same mistake.

**Comment by necolas** [comment]
> How would you implement light/dark themes with RNfW?

https://github.com/necolas/react-native-web/discussions/1801

> I can't recall seeing any warnings in the RN docs about using StyleSheet for dynamic properties or within the body of a component

This has been the case since the framework's inception. The fact that RN later made StyleSheet.create a passthrough function means you shouldn't need to use it for dynamic styles at all

**Comment by JetA2** [comment]
Cool, now I know. Works fine without StyleSheet.

Anyway it's incredibly cool to be able to reuse around 95% of code between iOS, Android and Web in quite a decently sized app. Excellent work on this package! 😃
