### ISSUE TITLE
Reducing TextInput value length onChange shifts cursor to end of string

### ISSUE THREAD

**Issue by rozele** [necolas/react-native-web#1926]
Simplified test case: https://codesandbox.io/s/dawn-hooks-jmtxo?file=/src/App.js

Steps to reproduce:
1. Enter a string into the text box (e.g., "foobar")
2. Change the cursor to anywhere except the end of the string (e.g., "foo|bar)
3. Type a space character
4. The whitespace character is deleted, but the cursor shifts to the end of the string (e.g., "foo |bar" -> "foobar|")

**Expected behavior**
The space character will be deleted and the cursor remains in the same position (e.g., "foo |bar" -> "foo|bar")

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.15.0
* React (version): 17.0.1
* Browser: Chrome

**Comment by necolas** [comment]
Same behavior is observed when using a ReactDOM `input` element

**Comment by necolas** [comment]
I think you're going to have to abstract your string replacement code and reset the selection each time you change the text, or do something like this for the web target: https://stackoverflow.com/questions/40196467/restore-cursor-position-after-replace

I don't think there's much I can do if you're mutating the text and replacing the value. The browser is going to move the selection when the node is re-rendered with a new string.

**Comment by rozele** [comment]
Thanks I was actually about to close this myself. All React Native platforms are a bit different, so the cursor positioning always needs to be handled by app code.

**Comment by necolas** [comment]
As far as I could tell, iOS and Android behave as you wanted. It's a shame the web doesn't seem to natively support that when setting the value. But it is straightforward to implement. It may be that ideally React Native should have an API that papers over the platform differences in this case
