### ISSUE TITLE
Breaking out of iframe??

### ISSUE THREAD

**Issue by lanman2000** [necolas/react-native-web#1927]
Here is the scenario... My app is written in react native and I am deploying to web. The screen can sometimes be served up in a partner's website within an iframe. I want to break out of the iframe in certain circumstances.

Normally this is as easy as writing code like:

if (top.location!= self.location) {
   top.location = self.location.href;
}

With react native web though how can this be done?

**Comment by necolas** [comment]
The same way. It's just the web
