### ISSUE TITLE
.babelrc文件会对react－native干扰 导致报错

### ISSUE THREAD

**Issue by wollld** [necolas/react-native-web#193]
.babelrc文件会对react－native干扰 导致报错 将此文件放在node_modules同一目录会干扰

**Comment by wollld** [comment]
{
  "presets": [
    "es2015",
    "stage-1",
    "react"
  ],
  "plugins": [
    "transform-decorators-legacy"
  ]
}

**Comment by MoOx** [comment]
Can you try to explain this in english? That will be more easy for us to understand your error :)

**Comment by necolas** [comment]
This repo currently uses the same Babel preset as react native. It's also transpiled and shouldn't cause any issues when installed locally. Going to close this until there is enough information to know if there's a problem in master

**Comment by wollld** [comment]
react native ，react－native－web，have the same .bablerc file and it disturb   cause err. tip babel type err

**Comment by MoOx** [comment]
I am currently doing the react-native + react-native-web thing and now I think I understand the problem.

RN requires a specific config but does not rely on any "env" (BABE_ENV/NODE_ENV assumed to be "development").

My workaround is to split my config into 2 parts, one relying on babel env.development and the other on BABEL_ENV set by hand in webpack config, so I end up with this:

```json
{
  "env": {
    "#test": "for jest",
    "test": {
      "presets": [
        "babel-preset-latest",
        "babel-preset-stage-2",
        "babel-preset-react"
      ]
    },
    "#development": "for react-native",
    "development": {
      "presets": [
        "babel-preset-react-native",
      ]
    },
    "#webpack-*": "for webpack(@2)",
    "webpack-development": {
      "presets": [
        [
          "babel-preset-latest",
          {
            "babel-preset-es2015": {
              "modules": false
            }
          }
        ],
        "babel-preset-stage-2",
        "babel-preset-react"
      ],
      "plugins": [
        "react-hot-loader/babel"
      ]
    },
    "webpack-production": {
      "presets": [
        [
          "babel-preset-latest",
          {
            "babel-preset-es2015": {
              "modules": false
            }
          }
        ],
        "babel-preset-stage-2",
        "babel-preset-react"
      ]
    }
  }
}
```

Then in my webpack config I do this:

```js
process.env.BABEL_ENV = "webpack-" + (process.env.NODE_ENV || "development")
```

This helps me to have all config in a single place.
