### ISSUE TITLE
Support Image from Images.xcassets folder ios

### ISSUE THREAD

**Issue by hungvu193** [necolas/react-native-web#1931]
Hi there, I have a little problem with image, on my react-native app I have few images from `Images.xcassets` folder and I can display them by using Image component like this:
```
 <Image
        fadeDuration={0}
        transition={false}
        source={{ uri: 'Notification_Bg' }}
        style={styles.backgroundImage}
        resizeMode="cover"
        PlaceholderContent={<ActivityIndicator />}
      />
```
`Notification_Bg` 's image from `Images.xcassets` folder.
<img width="640" alt="Screen Shot 2021-03-07 at 13 02 46" src="https://user-images.githubusercontent.com/16502320/110230723-6b9f3900-7f45-11eb-825c-d045c8b0a81d.png">
But on the web, they don't display, How can I use those images from  Images.xcassets?

**Comment by necolas** [comment]
You can configure your bundler to map the strings like `Notification_Bg` to the URL they will be hosted at

**Comment by hungvu193** [comment]
I have hundreds of image like that, is that the best way ? @necolas
