### ISSUE TITLE
Picker component with multiple selection

### ISSUE THREAD

**Issue by aghasemi** [necolas/react-native-web#1946]
Hi,

Is there a Picker/Select element that is compatible with RNW and also allows multiple selections?

I am currently using react-select, which is obviously exclusive to web. The original Picker of React Native does not allow multiple selections (does it?), plus it is apparently deprecated now. 

Many thanks

**Comment by necolas** [comment]
See https://reactnative.directory/?search=picker and open an issue if necessary against the project you choose to use
