### ISSUE TITLE
Picker component

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#195]
As I mentioned in #184 I implemented a simple Picker but it's a partial implementation of the react-native one.

I am just pasting a link to a gist if anyone want to finish this and make a clean PR for react-native-web (or just use it like I do)

https://gist.github.com/MoOx/96169e8af11894d3e74a2aa29b2ccac5

**Comment by MoOx** [comment]
Note that my component is "just" a select, with the same API as the Picker. The UI is not exactly the same as the RN Picker is kind of the moment (on mobile) when you open the `<select>` (on the web).
So I guess in real work, RN dev use a button to spawn a Picker.

**Comment by necolas** [comment]
Thanks! This looks like a good starting point and using native select/option is the way I think we should go. Will track in #91

**Comment by srt0422** [comment]
when will this be integrated into the node package?

**Comment by remon-georgy** [comment]
@MoOx that picker is neat! Are you creating a PR with that code?
