### ISSUE TITLE
Add support for onKeyDown for Pressable

### ISSUE THREAD

**Issue by tolfino** [necolas/react-native-web#1950]
**Is your feature request related to a problem? Please describe.**
Currently, the only element that supports keypress events is TextInput: this makes it difficult to implement custom accessible `<select>`-esque dropdowns, because it's not possible bind handlers to the items to use the arrow keys through the dropdown items.

**Describe a solution you'd like**
Expose `onKeyPress` on `Pressable` and call it in `PressResponder.onKeyDown`. I've proposed a PR for it, please take a look!

**Describe alternatives you've considered**
The other alternative is to write a separate component that supports `onKeyPress`, but this loses all the benefits that `Pressable` has.

**Additional context**
It looks like twitter.com's "More" menu supports keyboard navigation without using TextInput.

**Comment by intergalacticspacehighway** [comment]
@tolfino I think we should have onKeyDown instead of onKeyPress. The documentation states that Pressable inherits View props which inherits KeyboardProps. (onKeyDown, onKeyUp etc...). https://necolas.github.io/react-native-web/docs/pressable/
We had this discussion here but it was before 0.15 release.
https://github.com/necolas/react-native-web/issues/1862

**Comment by tolfino** [comment]
Ah, I missed that! Should I forward all the `onKey*` properties props down to Pressable instead?

**Comment by intergalacticspacehighway** [comment]
@tolfino Pressable supports most of the onKey* handlers, the issue with onKeyDown is that it gets overridden by pressEventHandlers prop spread. This line
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Pressable/index.js#L155

A simple fix would be to chain the onKeyDown event from the outer prop and from pressEventHandlers.

**Comment by tolfino** [comment]
Ah, thanks! I've fixed the PR to just forward onKeyDown to PressResponder.
