### ISSUE TITLE
When used in conjunction with react-native-svg image tags get transformed incorrectly

### ISSUE THREAD

**Issue by denissb** [necolas/react-native-web#1958]
**The problem**

When using the `Image` component from `react-native-svg` with `react-native-web: 0.15.0` the tag gets transformed incorrectly.
This happens because it also uses a `href` attribute, but in this case it is referring to : https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href, so the framework still decides to polyfill it with `<a href="..">`, but this off-course breaks the svg structure.

Don't know if it is a sensible bug because `react-native-svg` is not officially supported by this project.
For now I am using a workaround where I specifically use the `image` tag when running on the web platform.

Example:
<img width="1100" alt="Screenshot 2021-03-23 at 15 36 33" src="https://user-images.githubusercontent.com/2261330/112164119-eb87fd00-8bed-11eb-9d9c-cc27061126b4.png">

**How to reproduce**
Simplified test case: https://codesandbox.io/s/practical-faraday-ypb4w

1. Use an `Image` element from ` react-native-svg` with the `href` attribute set to an image URL.
2. Check the result and see that instead of `<image href="..." />`, `a <a href="..." />` is rendered in the dom.

**Expected behavior**
`Image` from `react-native-svg` is transformed to an SVG `image` element by `react-native-web`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.15.0
* React (version): 17.0.1
* Browser: Google Chrome 89.0.4389.90 (Official Build) (x86_64)

**Comment by necolas** [comment]
Please include a reduced test case.

IIRC `react-native-svg` is not properly maintained right now and uses unstable APIs from RNWeb.

**Comment by denissb** [comment]
> Please include a reduced test case.
> 
> IIRC `react-native-svg` is not properly maintained right now and uses unstable APIs from RNWeb.

I added a code example on snack, but I assume they use an older version of `react-native-web` so it renders fine in the preview.

**Comment by necolas** [comment]
test case https://codesandbox.io/s/twilight-river-4336g

**Comment by denissb** [comment]
Updated test case: https://codesandbox.io/s/practical-faraday-ypb4w, but I suppose it does not work without a proper webpack/babel setup.
