### ISSUE TITLE
Add `onKeyPressDown` support for `TextInput`

### ISSUE THREAD

**Issue by arthurpankiewicz** [necolas/react-native-web#1961]
**Is your feature request related to a problem? Please describe.**
I have an input that is shared between web/native, and I'd like the web input to handle certain keyboard shortcuts using `onKeyPressDown` rather than `onKeyPress`.

**Describe a solution you'd like**
`TextInput` exposes an `onKeyPressDown` prop

**Describe alternatives you've considered**
None

**Comment by necolas** [comment]
onKeyPress is equivalent to onKeyDown
