### ISSUE TITLE
0.15.0 Release Notes are missing undocumented `disabled` prop change 

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#1964]
**The problem**
There was a breaking change that's not mentioned in the 0.15.0 release notes which may cause unexpected behavior when upgrading. The following line should be added:

Removed undocumented "disabled" prop; use "accessibilityDisabled" instead.

This comes from the change here, who's other changes made the notes:
https://github.com/necolas/react-native-web/commit/abf00ef9b37b67fb88156fc32548ef96a7f05a60

**Comment by necolas** [comment]
Sure. But no one should have been using that prop on View. What was the context?

**Comment by comp615** [comment]
It was getting passed through from our `Button` and Interactive components (we use View to underpin Button). So it was handling some of the click ignoring. Much like you did internally in RNW re-mapping disabled to accessibilityDisabled in various components, we just had to to do the same thing.

**Comment by necolas** [comment]
Updated, thanks! https://github.com/necolas/react-native-web/releases/tag/0.15.0
