### ISSUE TITLE
accessibilityLevel doesn't create correct heading

### ISSUE THREAD

**Issue by atomicpages** [necolas/react-native-web#1965]
According to the [docs](https://necolas.github.io/react-native-web/docs/accessibility/#semantic-html):

> If the "heading" role is combined with an accessibilityLevel, the equivalent HTML heading element is rendered. Otherwise, it is rendered as `<h2>`.

So this code:

```js
<Text accessibilityRole="heading" accessibilityLevel={3} />
```

should create a `h3` element; however `h1` is created.

https://github.com/necolas/react-native-web/blob/66d01734ce3ffcfea61e05aa1b45015658b3f2af/packages/react-native-web/src/modules/AccessibilityUtil/propsToAccessibilityComponent.js#L49

Simple issue that I'm happy to make a PR for :). Thanks for the awesome lib!

**Comment by necolas** [comment]
Thanks!
