### ISSUE TITLE
No momentum scrolling on iOS

### ISSUE THREAD

**Issue by nthtran** [necolas/react-native-web#197]
**What is the current behavior?**

There's no momentum scrolling on iOS using ScrollView. Test [the official example](http://necolas.github.io/react-native-web/storybook/?selectedKind=component%3A%20ScrollView&selectedStory=vertical&full=0&down=1&left=1) in any iOS browser.

Should `WebkitOverflowScrolling: 'touch'` be added to View to enable momentum scrolling?

**Environment (include versions)**

OS: iOS 10
Device: iPad Pro
Browser: Safari
React Native for Web (version): 0.0.44
React (version): 15

**Comment by necolas** [comment]
Thanks. Give 0.0.45 a try.
