### ISSUE TITLE
Pull-to-Refresh doesn't exist

### ISSUE THREAD

**Issue by aghasemi** [necolas/react-native-web#1973]
Hi,
I just noticed that the pull-to-refresh gesture on Chrome for Android doesn't work for an RNW app. Is there a way to "enable" it?

**The problem**
 The pull-to-refresh gesture on Chrome for Android doesn't work for an RNW app

**How to reproduce**

Steps to reproduce:
1. Build any app and deploy it
2. Try pull to refresh on Chrome browser on an Android phone
3. Example: https://goods2give.ch/

**Expected behavior**
Page is refreshed after the pulling gesture

**Environment (include versions). Did this work in previous versions?**
Don't know

* React Native for Web (version): ~0.13.12
* React (version): 16.13.1
* Browser: Chrome for Android

**Comment by MohammadAzimi** [comment]
@aghasemi I think it's because `RefreshControl` is not implemented yet. see https://github.com/necolas/react-native-web/issues/1027

**Comment by necolas** [comment]
The native pull to refresh only works if the body is the root scroller. You can try adjusting the root elements styles in your app

**Comment by aghasemi** [comment]
> The native pull to refresh only works if the body is the root scroller. You can try adjusting the root elements styles in your app

Thanks. Any more hints, examples, ..?
