### ISSUE TITLE
Provide a concise DevOps starter example 

### ISSUE THREAD

**Issue by synergiator** [necolas/react-native-web#1979]
**The challenge**
Imagine somebody tries to understand how to run a web app based on `react-native-web` in a container.
There is a whole series of [nice examples](https://codesandbox.io/examples/package/react-native-web), but it's not clear how to build and run them.

**Describe a solution you'd like**
Typically, a DevOps example can ship with a Dockerfile featuring a multi-stage build, which documents effectively the environments to assemble and execute the project.

**Describe alternatives you've considered**
Available tutorials do not feature this; it's not clear whether to use yarn either npm to download dependencies.

**Comment by necolas** [comment]
There's no difference to working with any other React DOM package.
