### ISSUE TITLE
Linking: does this make sense on web?

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#198]
See https://github.com/grigio/HAgnostic-News/blob/099f6b65e2f7873889913d7d4ae5c09827a46c3a/src/AppContainer.js#L45-L50

We could also include security precautions like `noopener` and `noreferer`.

**Comment by MoOx** [comment]
Can you be more clear about what you have in mind? I am not sure if you are asking to force _blank (but I guess you don't).

**Comment by grigio** [comment]
I think Linking is useful to have portable RN/RNW external links format, for internal links it dipends how you do client-side routing or you manage the app state and it's related to #135 
Linking on the Web could also support web specific options ,

**Comment by RangerMauve** [comment]
@MoOx Using `_black` is actually a security issue. `noopener` and `noreferer` are the [safer alternatives](https://mathiasbynens.github.io/rel-noopener/).

**Comment by mattferrin** [comment]
I think it would be ideal, insofar as humanly possible, for `react-native` code to be entirely portable to `react-native-web` without refactoring. This includes assuming support for the`Linking` API for everything `web` platform analogous and logging warnings to the console if anything is `web` platform irrelevant. The inverse is true, it would be nice for every non-DOM `react-native-web` component to be portable to `react-native`, this would mean creating a separate cross-platform component if needed to avoid adding non-`react-native` props to `react-native` APIs.
