### ISSUE TITLE
Viewing transpiled react-native code in react js

### ISSUE THREAD

**Issue by srameshr** [necolas/react-native-web#1990]
**Is your feature request related to a problem? Please describe.**

How do I see the output of the react-native code, that react-native-web transpiles. Something like a Babel REPL that shows the ES6 syntax that's transpiled into ES5 syntax. If not, is there any way to achieve this?

https://babeljs.io/repl/

**Describe a solution you'd like**
I'm using a library that's built for react-native and I am using react-native-web to transpile that code in my react-js app. I want to remove react-native-web from my app by converting the package that's written in react-native to react-js.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by necolas** [comment]
There is no "transpiling". I suggest you look at the source code
