### ISSUE TITLE
How to configure tests unit when distributing a module for iOS/Android and Web with react native web ?

### ISSUE THREAD

**Issue by kopax-polyconseil** [necolas/react-native-web#1994]
**Is your feature request related to a problem? Please describe.**

This may be or not the right place to find such advice, we would like to distribute package for iOS, Android and Web.

So far, we are not able to found those informations on RNW website.

**Describe a solution you'd like**

Add a documentation on how to develop and test third-party module for iOS Android and Web.

We know expo worked on a similar solution for testing the 3 environments, we do not use expo sdk.

**Additional context**

We have a Lerna monorepository with a Web application and a module:

```bash
.
├── apps
│   └── id-check-app            <# Web application (create-react-app)
├── lerna.json
├── package.json
├── packages
│   └── id-check                <# Module made with react-native-web
├── tsconfig.json                # and compatible with react-native
└── yarn.lock
```

The `id-check` module within `packages` is made with `react-native-web`, aliased on `react-native` imports.

So far, we are able to test for the Web but if we use customs version of our components for **iOS or Android, then we are not able to test their `react-native` versions**.

I may try to bootstrap a fresh react native application in the `apps` directory for being able to test them. (Note: we do not use expo)

How can I configure React Native and Jest to be able to test components for iOS and Android our components using the real `react-native` package?

**Comment by necolas** [comment]
> How can I configure React Native and Jest to be able to test components for iOS and Android our components using the real react-native package?

Please refer to the RN docs on testing.

https://reactnative.dev/docs/testing-overview

If you're still having trouble after that, you can ask the community for advice.

https://reactnative.dev/help
