### ISSUE TITLE
Missing removeSubscription function from event emitter

### ISSUE THREAD

**Issue by Federkun** [necolas/react-native-web#1998]
After moving from 0.15.7 to 0.16.0, expo's unimodules complains that the `removeSubscription` function doesn't exist anymore from the event emitter.

https://github.com/expo/expo/blob/master/packages/%40unimodules/react-native-adapter/src/EventEmitter.ts#L67

Indeed, it has been removed in https://github.com/necolas/react-native-web/commit/f60d435e9b10b5d5023e3d0c411593d712f6c58a#diff-1ab56059c54295a2cfafab6bc42791ba7939f5e635e43b7d428f3d7f352a702cL57

**Expected behavior**

Avoid breaking changes if possible

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.16.0
* React (version): 17.0.1
* Browser: Chrome

**Comment by necolas** [comment]
It doesn't exist in React Native anymore: https://github.com/facebook/react-native/commit/d39643b9de11c6b44984166ede34a7f44de76fe5#diff-9f250e6d8a5ec553d894b660a762e5975e048fcb822ece9d1af7a72d93b3cb71

Expo will need to update that module.

I can add this change as a breaking change to the 0.16 notes.

**Comment by Federkun** [comment]
Thanks, understood. Is it expected for 0.16 to target the master version of react-native? As I don't see RN as a peer dependency defined in the package, do we have a table that define which RNW version to use for each RN version?
