### ISSUE TITLE
Caret going back to the beginning of TextInput

### ISSUE THREAD

**Issue by deerflow** [necolas/react-native-web#2003]
**The problem**
Caret going back to the beginning of TextInput on press event with react-native-paper

**How to reproduce**

Simplified test case: https://snack.expo.io/_hfgvyG0v

Steps to reproduce:
1. Create a TextInput with react-native-paper
2. Add a TextInput.Icon to the "right" property of the TextInput
3. Add an "onPress" callback to the TextInput.Icon that will toggle the "secureTextEntry" prop of the TextInput
4. Everytime you click on the icon, the caret will go back to the beginning of the TextInput

**Expected behavior**
The caret should stay at the end of the TextInput

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.13.18
* React (version): 16.13.1
* Browser: Google Chrome 90.0.4430.85

**Comment by necolas** [comment]
I don't have time to look into what React Native Paper is doing; you should open an issue against their library for now.

I would need a test case on codesandbox using the latest version of react-native-web. You're 3 minor versions behind

**Comment by necolas** [comment]
I'll be closing this soon if there is no follow up.

**Comment by dhairyasenjaliya** [comment]
@deerflow have you figured out any solution seems still a problem
