### ISSUE TITLE
Shorthand style properties overwriting the more specific properties

### ISSUE THREAD

**Issue by chrisgreen1993** [necolas/react-native-web#2007]
First i'd like to say I really appreciate this project, thanks everyone ❤️ 

**The problem**

Less specific shorthand style properties are being applied instead of the more specific styles if there is another element also with one of the more specific styles.

This is due to the common styles being pulled out as class names for de-duplication.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/dazzling-gould-ihiig

Steps to reproduce:
1. Open the link
2. The second View has horizontal paddings of 8px instead of 40px

Note that moving the first View below the second causes the issue to go away.

**Expected behavior**

I expect the horizontal padding to be 40px as this matches the behaviour in React Native.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.16.1
* React (version): 17.0.1
* Browser: Chrome

This appears to be an issue in previous versions as well

**Additional context**

I did some digging and this appears to be caused by the way that styles are de-duplicated. The first View get a class name applied with a `padding-left` & `padding-right` of `40px`. 

The second View then applies the same class and removes the horizontal padding in order to de-duplicate the styles. However this just leaves the `padding: 8px` in the style prop which then takes precedence over our de-duplicated padding class name. See here:

<img width="337" alt="Screenshot 2021-05-01 at 15 36 15" src="https://user-images.githubusercontent.com/1177794/116785728-0b36fe80-aa93-11eb-8290-20a85b34b67c.png">

I believe this is caused by `_resolveStyle` here https://github.com/necolas/react-native-web/blob/8fdbbc8d021ba3cb6a75f8b523a36da3c1be7007/packages/react-native-web/src/exports/StyleSheet/createStyleResolver.js#L147

I'm also willing to help out with a PR if someone can give me some pointers on the expected behaviour for how these styles should be applied.

Thanks 🙏

**Comment by zoontek** [comment]
@chrisgreen1993 This is wrong, it currently behaves correctly.
In React Native, the least specific style always win (padding > paddingVertical > paddingLeft)

I made a Snack using Expo, so you can try your example on native: https://snack.expo.io/@zoontek/biased-hummus
As you can see on this screenshot, padding is not 8px (native, iOS):

![IMG_2229](https://user-images.githubusercontent.com/1902323/116790474-9d9bca00-aab4-11eb-8bf5-816aa8359d42.PNG)

**Comment by necolas** [comment]
Thanks, this is a good catch! I can handle the fix but if you could submit a PR with a failing test case, that would be great.

**Comment by necolas** [comment]
See #2208 for a build that should fix this
