### ISSUE TITLE
Getting issue /node_modules/react-native-table-component/components/rows.js Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web/dist/index'. 

### ISSUE THREAD

**Issue by avs30390** [necolas/react-native-web#2009]
Is anyone can help to resolve this problem.
**The problem**
<!--
 I am using 'react-native-table-component' module that is working for android and ios , But in case of web , code is breaking.Please find the below  error details.
Compiled with warnings.
/node_modules/react-native-table-component/components/rows.js
Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web/dist/index'.
![Screenshot 2021-05-03 at 11 01 29 AM](https://user-images.githubusercontent.com/11497020/116843553-ef03a080-abfd-11eb-90ea-c414389b539c.png)
@necolas can you please help to resolve  this issue .

**Comment by necolas** [comment]
It's not exported

**Comment by avs30390** [comment]
Why you close that issue it is not resolved yet .How to export because there is no ViewPropTypes folder in react-native web.
 @necolas
