### ISSUE TITLE
Support passing dom-only html attributes into View

### ISSUE THREAD

**Issue by chrisdevereux** [necolas/react-native-web#2013]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate react-flip-tookit with RN web.

It requires the ability for a parent element to pass inline styles into a child element (via react-dom's style prop), which are interpreted by rn-web as react native's style prop.

**Describe a solution you'd like**
One straightforward solution that would allow adaptors like this to be developed would be adding a (discouraged from general use) `__htmlProps` prop on `<View />`.

A downside to this, naturally, is that it isn't compatible with react-native's api, so its use should be limited to web implementations and this should be clearly documented. Happy to open a PR to implement.

**Describe alternatives you've considered**
Perhaps if there are reasons for wanting to not make a general-purpose escape into the html attributes, a subset of props could be added to view.

**Comment by necolas** [comment]
This is not something that will be supported
