### ISSUE TITLE
Serverside Rendering is not working.

### ISSUE THREAD

**Issue by miteshtagadiya** [necolas/react-native-web#2014]
**The problem**
We have created a web app using react native web. We want to add a server-side rendering to our app. We have added a code to render the page server-side, but it's not working, I can see the blank white page in the network preview tab and the server only sends my index.html file as a response.

**How to reproduce**
I tried react-native-web server API for server-side rendering but it returns empty div tags
like this:
```
<div><div><div><div></div></div></div></div>
```
I used the same code as react-native webserver API(https://necolas.github.io/react-native-web/docs/rendering/#server-api)

Steps to reproduce:
1. https://necolas.github.io/react-native-web/docs/rendering/#server-api

**Expected behavior**
The app should be server-side rendered, I should see the snapshot of the page in the network preview, the server should return a snapshot of the page in the response.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): ^0.11.4
* React (version): 16.8.4
* Browser: chrome 89.0.4389.90

I found some articles that are suggesting to use prerendering of the app.
To add prerendering to our app I tried react-snap (https://www.npmjs.com/package/react-snap), a snapshot is created but when I started the app it's only loading the first page(landing page) of the app, No events are working on this page(click events) and styles are also missing, there is no way to navigate in the app. 

Then I tried react-snapshot (https://www.npmjs.com/package/react-snapshot), but it's throwing build error every time and not generating a snapshot of our app.

**Comment by necolas** [comment]
Try updating to 0.16 as 0.11 is very old and the API might not even be the same.

I'm closing this because the functionality is [unit tested](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/AppRegistry/__tests__/index-test.js) and there's no provided test case to indicate otherwise.

**Comment by miteshtagadiya** [comment]
@necolas Upgrading react-native-web is causing errors within react-native-htmlview and react-native-paper modules. react-native-paper errors are resolved on upgrading it. But react-native-htmlview module is throwing Module not found error. Do you have any idea, how can I fix this?
