### ISSUE TITLE
Rendering with React Portal

### ISSUE THREAD

**Issue by gax97** [necolas/react-native-web#2018]
**Is your feature request related to a problem? Please describe.**
Sometimes when you want to render multiple react trees on the same page it can be usefull to render them with portals in order to share context between them.

**Describe a solution you'd like**
I would like to extend AppRegistry to include method for creating the React Portal which you can use.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by necolas** [comment]
You can use ReactDOM Portal or a 3rd package that provides portals for RN and web

**Comment by gax97** [comment]
@necolas That is what I meant actually, but I don't see the package providing an option of rendering through portals right?
