### ISSUE TITLE
Image: layout bug in Safari caused by maxHeight

### ISSUE THREAD

**Issue by lprhodes** [necolas/react-native-web#202]
**What is the current behavior?**
Image height is a % of the browser height (even though it's inside a ScrollView) when no height is known for an image.

Minimal test case: https://codepen.io/anon/pen/KgVjxA?editors=0110

**What is the expected behaviour?**
The height of the image container would maintain the aspect ratio for the image when the image is a specific (or %) width.

I can "fix" this by removing the maxHeight: 100% on the `<img />` but I imagine that would break a lot of other things.

Any thoughts around this? I'm happy to dive in but some pointers would be a great help.

Thanks!

**Steps to reproduce**
1. See minimal test case above

**Environment (include versions)**

OS: macOS Sierra
Device: MacBook 12"
Browser: Safari
React Native for Web (version): 0.0.45
React (version): 15.3.1

**Comment by necolas** [comment]
Sound be fixed in 0.0.50
