### ISSUE TITLE
FlatList: initialScrollIndex broken in v0.16

### ISSUE THREAD

**Issue by hizo** [necolas/react-native-web#2030]
**The problem**
`initialScrollIndex` prop on `FlatList` stopped working from v0.16

**How to reproduce**
Simplified test case: https://codesandbox.io/s/nifty-hopper-44ntf

Steps to reproduce:
1. open the above test case link
2. observe an empty list with a scrollbar on the right (no signs of attempted scroll - the scrollbar is at the top of the list)
3. scroll
4. observe all items render at this point, with the scroll starting at the top of the list, instead of the provided index in `initialScrollIndex` prop

**Expected behavior**
FlatList renders items starting from the correct index provided in `initialScrollIndex` prop and the scrollbar shows correct position.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.16.3
* React (version): 17.0.2
* Browser: Google Chrome Version 90.0.4430.212 

This worked in 0.15.x versions and below
Test case showcasing correct behaviour with rn-web v0.15.7: https://codesandbox.io/s/elegant-leaf-8yt3c

**Comment by sirpy** [comment]
not working
i've tested and also _getItemCount() returns 0.
