### ISSUE TITLE
Destructuring Inline Styles doesn't work 

### ISSUE THREAD

**Issue by gyanadeep** [necolas/react-native-web#2031]
Destructuring Inline Styles doesn't apply and for a conditional styles we need to pass them as array instead using destructuring.

**How to reproduce**

`<Text style={styles.text}>` ---- Works
`<Text style={{ ...styles.text}}>`  ---- Doesn't work
`<Text style={[styles.text, {color: stayRed? 'red': 'green'}]}> `---- Works
`<Text style={{ ...styles.text, color: stayRed? 'red': 'green'}}> ` ---- Doesn't work

Simplified test case: https://codesandbox.io/s/destructuring-styles-issue-o792s
Refer to the codesandbox snippet
**Expected behavior**
Both {styles.text} and {{ ...styles.text}} should work similarly.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.16.2
* React (version): 17.0.1
* Browser: Chrome

**Comment by necolas** [comment]
You can't (and don't need to) destructure the return values from StyleSheet because they are not objects.

**Comment by aaronnewtonplaytravel** [comment]
It will work if you cast the object it to the right type, e.g. `{} as React.CSSProperties`.

```
const standardStyles = {
  all: 'unset',
  margin: 0,
  padding: 0,
  // Whatever.
};

// etc.

<div
    style={
      {
        ...standardStyles,
        display: 'flex',
        alignItems: 'center',
      } as React.CSSProperties
    }
  >Content here :)</div>
```
