### ISSUE TITLE
How to identify if website is made using react-native-web or not? Example of some top websites using react-native-web?

### ISSUE THREAD

**Issue by ShivamS136** [necolas/react-native-web#2037]
Is there any method by which I can identify that a website is created using `react-native-web`? 

I tried using "React Developers Tools" but it tells that the page is using `React` not `React-Native`. `Wappalyzer` also doesn't seem to detect even `React`.

Also, what are the examples of some top websites currently using `react-native-web` on production, the Twitter-lite example seems too old to trust as I am not able to detect that it's using `react-native-web` or not.

**Comment by ShivamS136** [comment]
Hi @necolas 
I am a very new user, is there anything wrong with the question? As you closed without any comment.

Thanks

**Comment by necolas** [comment]
You didn't read the issue template, a question isn't an issue, examples are listed in the docs, and Twitter is not too old to trust.

**Comment by ShivamS136** [comment]
Ok, I'll take care...
And by "too old" I meant that Twitter was using this as per 2017 video but is it still using or changed tech, that was confusing me. As I am not able to detect how to identify if a web app is using this pkg. Thanks for the clarification, if the community could build something to identify if the website is using this pkg then it would be great.

Thanks
