### ISSUE TITLE
Allow to set tabIndex -1 on all elements

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#2042]
Maybe I'm overlooking something, but I don't see any reason why tabIndex -1 is limited to native elements that are focusable by default.

For the proper roving tabIndex implementation, we need tabIndex -1 on all elements.
`UIManager.focus` sets it, but too lazy. We need elements rendered with tabIndex -1 to be able to listen onFocus event.

```
Use onfocus to track the current focus
Don't assume that all focus changes will come via key and mouse events: assistive technologies such as screen readers can set the focus to any focusable element. Track focus using onfocus and onblur instead.
```

https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets#managing_focus_inside_groups

I think it would not harm anything and would be very helpful to propagate tabIndex -1 to all elements with explicit focusable={false} since it already sets tabIndex -1 on native focusable elements. 

This code from `createDOMProps/index.js`

```js
// FOCUS
  // "focusable" indicates that an element may be a keyboard tab-stop.
  const _focusable = focusable != null ? focusable : accessible;
  if (
    // These native elements are focusable by default
    elementType === 'a' ||
    elementType === 'button' ||
    elementType === 'input' ||
    elementType === 'select' ||
    elementType === 'textarea'
  ) {
    if (_focusable === false || accessibilityDisabled === true) {
      domProps.tabIndex = '-1';
    }
  } else if (
    // These roles are made focusable by default
    role === 'button' ||
    role === 'checkbox' ||
    role === 'link' ||
    role === 'menuitem' ||
    role === 'radio' ||
    role === 'textbox' ||
    role === 'switch'
  ) {
    if (_focusable !== false) {
      domProps.tabIndex = '0';
    }
  } else {
    // Everything else must explicitly set the prop
    if (_focusable === true) {
      domProps.tabIndex = '0';
    }
  }
```

Am I correct? Or the recommended way is to set it manually via native props? Either way, it should be documented at least.

And again, thank you for the wonderful project.

**Comment by necolas** [comment]
as far as I understand you don't need to set -1 on every element, but you do if the element is interactive (i.e., set `focusable = false), as the key is to remove it from the tab flow.

you've been opening issues long enough to know that I ask that *all issues should follow the issue template*. please don't open issues just to think out loud.

**Comment by steida** [comment]
I do not think out loud. I am trying to explain higher-level issues to you. 

> as far as I understand you don't need to set -1 on every element

And that's why I tried to explain the issue. 
We need tabIndex -1 to properly implement the roving tabindex pattern. 

But OK, I will make an example of why we need it.
