### ISSUE TITLE
Allow to set tabIndex -1 to implement Roving tabindex pattern

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#2046]
**Is your feature request related to a problem? Please describe.**
Roving tabindex is the basic accessiblity pattern for grouped focusable items.

**Describe a solution you'd like**
RNfW should provide API for that so users don't have to hack it with setNativeProps in useEffect which can be too late.

**Describe alternatives you've considered**
There is no alternative for that.

**Additional context**
Here is an example https://codesandbox.io/s/gallant-germain-ujqnm?file=/src/App.js

**Comment by necolas** [comment]
Show me how you can't already do this.

**Comment by necolas** [comment]
This still works https://codesandbox.io/s/snowy-morning-fwke7

You only need tabIndex `-1` if the element would otherwise natively receive focus.

**Comment by steida** [comment]
1) Try to click on any item. Nothing will happen because there is no tabIndex.
2) We have to track the current focus via onFocus which requires tabIndex -1

No, we can not set tabIndex 0 on all items. Then it would not be grouped.

![Screenshot 2021-06-07 at 23 24 24](https://user-images.githubusercontent.com/66249/121089487-83f24e80-c7e7-11eb-8ffd-125a296fd5c9.png)

![Screenshot 2021-06-07 at 23 27 25](https://user-images.githubusercontent.com/66249/121089820-fcf1a600-c7e7-11eb-97bd-0215c618eb93.png)

**Comment by necolas** [comment]
> Try to click on any item

Add a press handler: https://codesandbox.io/s/snowy-morning-fwke7?file=/src/App.js

**Comment by necolas** [comment]
We can make `focusable=false` explicitly set `tabIndex=-1` though. I don't see the harm in that

**Comment by steida** [comment]
"Don't assume that all focus changes will come via key and mouse events."

From this document "https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets"

Do you think they are wrong? 

![121089820-fcf1a600-c7e7-11eb-97bd-0215c618eb93](https://user-images.githubusercontent.com/66249/121142008-dbbaa500-c83b-11eb-83d7-46bd07c64437.png)

**Comment by steida** [comment]
> We can make focusable=false explicitly set tabIndex=-1 though. I don't see the harm in that

I agree. No focusable, no tabindex. Focusable true, tabindex 0. Focusable false, tabindex -1. 
And for all elements, because everything can be focusable.
