### ISSUE TITLE
what's the idiomatic way to apply an onHover handler?

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#205]
It seems to me that *React Native Web* should have an `onHover` prop just as `<View>` and `<Text>` support `onPress`. Perhaps I'm missing something.

**Comment by MoOx** [comment]
The thing is you need 2 callbacks to know on and off. But yeah, onMouseEnter & onMouseLeave are related to mouse...

**Comment by faceyspacey** [comment]
excellent that solves my problem--didn't know those callbacks were available.

**Comment by dsernst** [comment]
I created a utility component to make it easy to add a hover style:

### HoverableOpacity.js

```js
import React, { Component } from 'react'
import { TouchableOpacity } from 'react-native'

export default class HoverableOpacity extends Component {
  constructor(props) {
    super(props)
    this.state = {}
  }

  render() {
    const { outerStyle, hoverStyle } = this.props

    return (
      <TouchableOpacity
        activeOpacity={1}
        style={[{ cursor: 'inherit' }, outerStyle, this.state.hover ? hoverStyle : {}]}
        onMouseEnter={() => this.setState({ hover: true })}
        onMouseLeave={() => this.setState({ hover: false })}
      >
        <TouchableOpacity {...this.props} />
      </TouchableOpacity>
    )
  }
}

HoverableOpacity.propTypes = {
  hoverStyle: React.PropTypes.shape({}),
  outerStyle: React.PropTypes.shape({}),
}
```

## Usage
Use `HoverableOpacity` in place of `TouchableOpacity`. 

It can take two new props:

### hoverStyle
Style to apply while component is hovered.

##### E.g.:
```jsx
hoverStyle={{ backgroundColor: 'hsla(0,0%,100%,0.1)' }}
```


### outerStyle
Style applied to the Hoverable container. 

Useful for adding margins outside the hover.
##### E.g.:
```jsx
outerStyle={{ margin: 30 }}
```

**Comment by necolas** [comment]
You should use setNativeProps (like the touchables do) to update the style without triggering a render of the sub tree.

**Comment by lotap** [comment]
I wrote a component that uses setNativeProps to set styles on hover in case anyone wants to see what that looks like:

```
import React from 'react'
import { View } from 'react-native'

class HoverableView extends React.Component {
  setStyles = (styles) => {
    this.root.setNativeProps({
      style: styles,
    })
  }

  render() {
    return (
      <View
        ref={(component) => { this.root = component }}
        onMouseEnter={() => this.setStyles(this.props.onHover)}
        onMouseLeave={() => this.setStyles(this.props.style)}
        {...this.props}
      />
    )
  }
}

export default HoverableView
```

Called like this:
```
<HoverableView
  style={{ backgroundColor: 'transparent', flex: 1 }}
  onHover={{ backgroundColor: '#ff0000' }}
>
  <Text>Foo</Text>
</HoverableView>
```

One thing to be aware of is that if a style attribute is passed through onHover but is not in the style prop, it will not be overwritten onMouseLeave. (That's why backgroundColor: 'transparent' is set in the style prop of the example)

**Comment by Shagamii** [comment]
I created an example that also implements pseudo class other than hover.
As an example, please try it.
https://github.com/Shagamii/pseudo-class-example/blob/master/src/AccessibleComponent.js
