### ISSUE TITLE
Step by Step Guide to integrate react-native-web in basic app created by react-native init (with and without typescript)

### ISSUE THREAD

**Issue by ShivamS136** [necolas/react-native-web#2050]
**Is your feature request related to a problem? Please describe.**
I am new to `node/npm`, `react` and `react-native` so very new to `react-native-web` as well. It's been 3 days for me to integrate `react-native-web` in a *Hello World App* generated using `npx react-native init` [as per the doc](https://reactnative.dev/docs/environment-setup). I tried using both templates: with and without typescript, but no success so far. The farthest I got is to run the app code written in `index.web.js` but if I add any component from `./src/components/` then I get errors, mostly of **webpack**. If I list the articles I used to debug then this page will be short of space. I am literally frustrated and seems like convincing my organization to use `react-native` and `react-native-web` was not a good idea.

**Describe a solution you'd like**
It would be very helpful if we get a detailed doc mentioning the step-by-step guide to add `react-native-web` in a *Hello Word* app created by `react-native init`. Preferably with and without Typescript. The [current doc](https://necolas.github.io/react-native-web/docs/setup/) is not that much helpful and descriptive. The steps are not that clear especially for a beginner like me.

**Describe alternatives you've considered**
I tried StackOverflow, logrocket, webpack doc, typescript doc, react-scripts, medium articles, current official doc of this project, babel doc, flow doc. But most of them are outdated or working till home file only, when I include components from `src/components`, it does not work.

**Comment by necolas** [comment]
You should use Expo as recommended, instead of trying to set up manually yourself. Manual setup requires basic knowledge of the relevant tools, and if you're a beginner it is too complicated to start there.

If you're having trouble you should also open a discussion or stackoverflow with specific errors and details so people can help. Just saying "it's not working" doesn't allow anyone to help you.
