### ISSUE TITLE
Guide to using in a web only CRA project

### ISSUE THREAD

**Issue by conor909** [necolas/react-native-web#2054]
I've built a few UI components in React Native Web, and from them created a standalone UI library package.  My Expo project consumes the package and compiles to Web and Mobile, which is great because I can see my library components working in the browser when Expo compiles to web.  I can also see them working in a browser with Storybook, which I setup inside the library package.

But setting up a web only project with create-react-app, that consumes the library package is difficult, with not much documentation on approaches to compiling or importing.

The documentation mentions that create react app has built in support for react native web, but I get the following error:

Can the documentation on web only projects be expanded upon?  It says we only have to install react-native-web as a package but nothing more.

`````
./node_modules/@expo/vector-icons/build/createIconSet.js
SyntaxError: /Users/conor/dev/renx-app/node_modules/@expo/vector-icons/build/createIconSet.js: Support for the experimental syntax 'jsx' isn't currently enabled (39:28):

  37 |                 }
  38 |                 if (!this.state.fontIsLoaded) {
> 39 |                     return <Text />;
     |                            ^
  40 |                 }
  41 |                 return (<RNVIconComponent ref={(view) => {
  42 |                     this._icon = view;

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
`````

**Comment by necolas** [comment]
The error is telling you that the package expo/vector-icons contains uncompiled jsx. CRA is not compiling code in node_modules. You should open an issue against the uncompiled expo package.

I think the docs are clear:

> Create React App is a basic way to setup a simple, web-only React app with built-in support for *aliasing react-native-web to react-native*. However, it’s generally recommended that you use Expo.

**Comment by Alexorz** [comment]
@necolas But the same code works well with metro bundler. I think it will be better to make uncompiled node_modules to be compiled when runtime by default (same result with metro).

I’m recently diving in RN-Web but I’ve worked on this issue for all day long, and saw several same issues like this one (some on other RN-UI repos), I think it will be worthy to make this easy, better for RN-Web newcomers.

**Comment by necolas** [comment]
This project works with any bundler. The docs explain that you need to configure bundlers
