### ISSUE TITLE
Text component with accessibilityRole heading will only render an h1 element

### ISSUE THREAD

**Issue by jffr** [necolas/react-native-web#2057]
**The problem**
The `Text` component will always rendering the `h1` element. Using the `accessibilityRole="heading"` and `accessibilityLevel={otherLevel}` will not result in the corresponding heading element.

Link to documentation: https://necolas.github.io/react-native-web/docs/accessibility/#semantic-html

**How to reproduce**
The following code snippet will not render an h2 element:
```javascript
import { Text } from 'react-native'

const Heading = ({ text, level }) => {
  return (
    <Text
      accessibilityRole="heading"
      accessibilityLevel={level}
    >
      {text}
    </Text>
  )
}

<Heading text="Heading 2" level={2} />
```
**Expected behavior**
On web: `<h2>Heading 2</h2>`

**Environment**
* React Native for Web (version): 0.13.8
* React (version):  16.13.1
* Browser: Chrome version 91.0.4472.101 (Official Build) (arm64)

**Comment by necolas** [comment]
You should update to the latest version

**Comment by jffr** [comment]
I want to confirm that after the update it works as expected! Thank you. 😊
