### ISSUE TITLE
warnings thrown when using background style property

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#206]
I've noticed that some style properties such as `background` behave as they should within a browser context, even though the corresponding components throw warnings for these properties that otherwise don't exist in React Native. 

The thing is sometimes you need a property like `background` because you can't achieve what you want stylistically through the combination of `backgroundImage` and `backgroundColor`. For example, if you combine a gradient with a repeating url() image you can only do so using a `background` property. I'm not sure if it's recommended to do such things, so what is the prescribed way to handle it? Should RNW accept background properties or turn off the warnings for it??

**Comment by necolas** [comment]
Is there a reduced test case to demonstrate what you can't achieve? The aim isn't to support everything that is possible in CSS, and the `background` shorthand isn't supported
