### ISSUE TITLE
Unhandled JS Exception: Can't find variable: require

### ISSUE THREAD

**Issue by skashyapsri** [necolas/react-native-web#2060]
I am trying to run my react-native-web app which is running fine on the web. I have run into this issue after setting up the react-native project structure from ```create-react-native-app``` (as the project was initially configured to run on the web using react-native-web). 

The metro bundler generates a ```index.bundle``` file which runs on metro dev server ```http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.name.app```

This is the error I'm getting while trying to run the app using ```react-native run-ios``` 

Here is the screenshot of the runtime error: 
<img width="400" alt="y7Qtn" src="https://user-images.githubusercontent.com/22166697/122645467-576bfa00-d138-11eb-9e74-4decc1b7ebcf.png">

The complete error log is as follows:
```
Unhandled JS Exception: Can't find variable: require

http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.name.app:5:24
global code@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.name.app:720:3

global code
    index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.name.app:720:3
```

The ```index.bundle``` on line 5 and line 720 as mentioned in the error logs has

```  var _typeof = require("@babel/runtime/helpers/typeof");```

I tried everything mentioned here https://github.com/facebook/react-native/issues/21048, nothing worked.

I am posting my package.json and babel.config.js here.

**package.json**

      "engines": {
        "node": "12.x"
      },
      "dependencies": {
        "@expo/metro-config": "^0.1.73",
        "@loadable/component": "^5.10.2",
        "@loadable/server": "^5.10.2",
        "@sentry/node": "^5.29.2",
        "@sentry/react": "^5.29.2",
        "@stripe/react-stripe-js": "^1.0.3",
        "@stripe/stripe-js": "^1.0.3",
        "actioncable": "5.1.4",
        "axios": "^0.21.1",
        "body-scroll-lock": "^2.6.3",
        "bowser": "1.9.1",
        "color": "^3.1.1",
        "comma-separated-values": "^3.6.4",
        "core-js": "^3.1.3",
        "draft-js": "^0.11.6",
        "draft-js-export-html": "^1.4.1",
        "draft-js-link-detection-plugin": "^0.0.4",
        "draft-js-plugins-editor": "^3.0.0",
        "enzyme-adapter-react-16": "^1.10.0",
        "expo-splash-screen": "^0.10.2",
        "expo-updates": "^0.5.5",
        "express": "4.16.2",
        "express-static-gzip": "0.3.1",
        "fabric": "github:languageinmotion/fabric.js",
        "file-saver": "^2.0.2",
        "fontsource-montserrat": "^3.0.9",
        "fontsource-poppins": "^3.0.9",
        "fontsource-roboto": "^3.0.3",
        "global": "^4.4.0",
        "html2canvas": "^1.0.0-rc.5",
        "i18n-js": "^3.5.0",
        "i18nliner": "github:languageinmotion/i18nliner-js",
        "json-api-normalizer": "0.4.1",
        "lodash": "4.17.4",
        "mammoth": "^1.4.9",
        "matchmedia-polyfill": "0.3.0",
        "moment-timezone": "^0.5.31",
        "newrelic": "^7.0.2",
        "node-fetch": "^2.3.0",
        "opentok-react": "github:languageinmotion/opentok-react",
        "prerender-node": "2.7.4",
        "qs": "6.5.1",
        "query-string": "5",
        "ramda": "^0.26.1",
        "rc-tooltip": "^4.0.0-alpha.3",
        "react": "16.8.4",
        "react-autosuggest": "^9.4.3",
        "react-awesome-lightbox": "^1.7.3",
        "react-color": "^2.19.3",
        "react-copy-to-clipboard": "^5.0.3",
        "react-datasheet": "^1.4.8",
        "react-dom": "16.8.4",
        "react-draggable": "^4.4.3",
        "react-dropzone": "^10.1.10",
        "react-ga": "2.4.1",
        "react-google-maps": "^9.4.5",
        "react-guard": "0.5.0",
        "react-hammerjs": "^1.0.1",
        "react-helmet": "^6.1.0",
        "react-hook-form": "^5.7.2",
        "react-i18nliner": "^0.2.3",
        "react-lazy-load": "^3.0.13",
        "react-lazyload": "^2.6.5",
        "react-loadable": "^5.5.0",
        "react-native": "0.64.1",
        "react-native-animatable": "^1.3.2",
        "react-native-htmlview": "^0.14.0",
        "react-native-paper": "^2.15.2",
        "react-native-unimodules": "^0.13.3",
        "react-native-vector-icons": "^6.4.2",
        "react-native-web": "^0.11.4",
        "react-native-web-linear-gradient": "^1.0.5",
        "react-onclickoutside": "^6.9.0",
        "react-pdf": "^5.0.0",
        "react-places-autocomplete": "^7.2.1",
        "react-player": "^1.11.1",
        "react-redux": "^7.1.0",
        "react-responsive": "1.3.0",
        "react-router-dom": "^5.1.2",
        "react-router-native": "^5.2.0",
        "react-share": "^3.0.1",
        "react-sidebar": "^3.0.2",
        "react-slick": "^0.23.1",
        "react-webcam": "^5.2.0",
        "react-zoom-pan-pinch": "^1.6.1",
        "redux": "3.7.0",
        "redux-actions": "2.0.3",
        "redux-api-middleware": "1.0.3",
        "redux-form": "^8.2.4",
        "redux-object": "0.4.5",
        "redux-persist": "^5.10.0",
        "redux-reset": "0.3.0",
        "redux-thunk": "2.2.0",
        "reselect": "^3.0.1",
        "seamless-immutable": "^7.1.4",
        "semantic-ui-css": "2.2.12",
        "semantic-ui-react": "^0.88.1",
        "slick-carousel": "^1.8.1",
        "styled-components": "3.4.10",
        "svgs": "^4.1.0",
        "throttle-debounce": "^2.2.1",
        "validate.js": "0.11.1",
        "victory-area": "^35.2.0",
        "victory-axis": "^35.2.0",
        "victory-chart": "^35.2.0",
        "victory-scatter": "^35.2.0",
        "victory-voronoi-container": "^35.2.0",
        "viewport-units-buggyfill": "0.6.2",
        "webfontloader": "1.6.28",
        "xdate": "^0.8.2",
        "yup": "^0.28.0"
      },
      "devDependencies": {
        "@babel/cli": "^7.5.5",
        "@babel/core": "^7.5.5",
        "@babel/plugin-proposal-class-properties": "^7.5.5",
        "@babel/plugin-proposal-decorators": "^7.4.4",
        "@babel/plugin-proposal-object-rest-spread": "^7.4.4",
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@babel/plugin-transform-flow-strip-types": "^7.4.4",
        "@babel/plugin-transform-runtime": "^7.5.5",
        "@babel/preset-env": "^7.4.5",
        "@babel/preset-flow": "^7.0.0",
        "@babel/preset-react": "^7.0.0",
        "@babel/register": "^7.4.4",
        "@babel/runtime-corejs2": "^7.0.0",
        "@loadable/babel-plugin": "^5.10.0",
        "@loadable/webpack-plugin": "^5.7.1",
        "@storybook/addon-centered": "^5.0.11",
        "@storybook/addon-options": "^5.0.11",
        "@storybook/react": "^5.0.11",
        "autoprefixer": "7.1.0",
        "babel-core": "7.0.0-bridge.0",
        "babel-eslint": "^9.0.0",
        "babel-loader": "^8.0.6",
        "babel-plugin-dynamic-import-node": "^2.2.0",
        "babel-plugin-file-loader": "2.0.0",
        "babel-plugin-import": "^1.13.0",
        "babel-plugin-inline-json-import": "^0.3.2",
        "babel-plugin-lodash": "^3.3.2",
        "babel-plugin-module-resolver": "^3.2.0",
        "babel-plugin-ramda": "^2.0.0",
        "babel-plugin-react-native-web": "^0.11.6",
        "babel-plugin-styled-components": "^1.10.0",
        "babel-plugin-transform-imports": "^2.0.0",
        "babel-plugin-webpack-alias": "2.1.2",
        "babel-preset-env": "^1.7.0",
        "babel-preset-react-app": "9.0.1",
        "babel-runtime": "6.26.0",
        "case-sensitive-paths-webpack-plugin": "2.2.0",
        "chai": "4.0.2",
        "chalk": "1.1.3",
        "clean-webpack-plugin": "^3.0.0",
        "compression-webpack-plugin": "^3.0.0",
        "copy-webpack-plugin": "^5.1.1",
        "cross-env": "^5.2.0",
        "css-loader": "^3.2.0",
        "dotenv": "6.2.0",
        "dotenv-expand": "4.2.0",
        "enzyme": "3.9.0",
        "eslint": "^4.12.0",
        "eslint-config-airbnb": "^17.1.0",
        "eslint-config-prettier": "^4.3.0",
        "eslint-config-react-app": "1.0.4",
        "eslint-loader": "^2.2.1",
        "eslint-plugin-babel": "^5.3.0",
        "eslint-plugin-flowtype": "^3.9.1",
        "eslint-plugin-import": "^2.17.3",
        "eslint-plugin-jsx-a11y": "^6.2.1",
        "eslint-plugin-react": "^7.13.0",
        "eslint-plugin-react-hooks": "^4.2.0",
        "extract-text-webpack-plugin": "^4.0.0-beta.0",
        "file-loader": "3.0.1",
        "flow-bin": "^0.99.1",
        "fs-extra": "3.0.1",
        "html-webpack-plugin": "4.0.0-beta.5",
        "husky": "^4.2.5",
        "image-webpack-loader": "^5.0.0",
        "imagemin-mozjpeg": "8.0.0",
        "is-wsl": "^2.1.0",
        "istanbul": "0.4.5",
        "jsdom": "11.0.0",
        "lint-staged": "4.0.0",
        "lodash-webpack-plugin": "^0.11.5",
        "metro-react-native-babel-preset": "^0.56.0",
        "mini-css-extract-plugin": "^0.7.0",
        "mocha": "^6.1.4",
        "nock": "9.1.4",
        "node-sass": "^4.12.0",
        "nyc": "11.0.3",
        "object-assign": "4.1.1",
        "optimize-css-assets-webpack-plugin": "^5.0.3",
        "path": "^0.12.7",
        "pnp-webpack-plugin": "^1.6.4",
        "postcss-flexbugs-fixes": "3.2.0",
        "postcss-loader": "3.0.0",
        "postcss-normalize": "7.0.1",
        "postcss-preset-env": "6.6.0",
        "postcss-safe-parser": "^4.0.1",
        "prettier": "^1.17.1",
        "promise": "7.1.1",
        "react-addons-test-utils": "15.6.2",
        "react-dev-utils": "^9.0.1",
        "react-error-overlay": "1.0.7",
        "react-test-renderer": "15.6.1",
        "redux-mock-store": "1.3.0",
        "sass-loader": "7.1.0",
        "script-ext-html-webpack-plugin": "^2.1.4",
        "sinon": "2.3.5",
        "sinon-promise": "0.1.3",
        "source-map-explorer": "^2.0.1",
        "style-ext-html-webpack-plugin": "3.4.5",
        "style-loader": "0.19.0",
        "sw-precache-webpack-plugin": "0.11.4",
        "terser-webpack-plugin": "^1.3.0",
        "uglify-js": "2.8.29",
        "url-loader": "1.1.2",
        "webpack": "4.29.6",
        "webpack-bundle-analyzer": "^3.9.0",
        "webpack-cli": "^3.3.12",
        "webpack-dev-server": "3.2.1",
        "webpack-manifest-plugin": "2.0.4",
        "whatwg-fetch": "2.0.3",
        "workbox-webpack-plugin": "^4.3.1"
      }

**babel.config.js**

    module.exports = function(api) {
      api.cache(false);
      return {
        presets: [
          "@babel/preset-env",
          "@babel/preset-react",
          "@babel/preset-flow",
          "module:metro-react-native-babel-preset",
        ],
        plugins: [
          ["lodash", { id: ["lodash", "semantic-ui-react"] }],
          "ramda",
          "@babel/plugin-syntax-dynamic-import",
          "@babel/plugin-proposal-class-properties",
          "@babel/plugin-proposal-object-rest-spread",
          "@babel/plugin-transform-flow-strip-types",
          ["react-native-web", { commonjs: true }],
          [
            "@babel/plugin-proposal-decorators",
            {
              legacy: true,
            },
          ],
          "@loadable/babel-plugin",
          [
            "module-resolver",
            {
              alias: {
                "react-native": "react-native-web",
                "react-native-svg": "svgs",
                "react-native-linear-gradient": "react-native-web-linear-gradient",
              },
            },
          ],
          [
            "@babel/plugin-transform-runtime",
            {
              regenerator: true,
            },
          ],
          "react-native-paper/babel",
        ],
        env: {
          production: {
            plugins: [
              [
                "file-loader",
                {
                  name: "[hash].[ext]",
                  extensions: ["png", "jpg", "jpeg", "gif", "svg", "webm"],
                  publicPath: "/static/media",
                  outputPath: "./build/static/media",
                  context: "",
                  limit: 0,
                },
              ],
            ],
          },
        },
      };
    };

React native Version: 0.64.1

Android: Google Pixel 3 API - 30

iOS: iPhone 12 - 14.5

react-native-web: 0.11.4

**Comment by necolas** [comment]
You're probably running the RNW Babel plugin for the native builds. Not related, but you're also using a very old version of RNW. Closing this because it's not an issue with this project but with your build setup

**Comment by caner-karaman** [comment]
I am also getting the same error. I create project with "npx react-native init AwesomeTSProject --template react-native-template-typescript"

react-native: 0.65.1
react-native-web: 0.17.1
