### ISSUE TITLE
TypeError: params.rootTag is null runApplication node_modules/react-native-web/dist/exports/AppRegistry/index.js:90

### ISSUE THREAD

**Issue by marcioseno** [necolas/react-native-web#2066]
Sorry my english. I am a noobie from Brazil.
I created a simple expo bare app and I am trying to connect with firebase. I use firebase init and I have this:
TypeError: params.rootTag is null 
runApplication
node_modules/react-native-web/dist/exports/AppRegistry/index.js:90

The problem appear when I create firebase init firestore.

Simplified test case: 

Steps to reproduce:
1. create-react-native-app my-app
2. npm install --save firebase
3. npm install firebase-tools
4. firebase init

I am trying to show a simple <View><Text>Hello World</Text></View>

I am using: 

* React Native for Web (version): 0.17.1
* React (version): 17.0.2
* Browser: firefox 89.0

**Comment by necolas** [comment]
Please try opening an issue with expo
