### ISSUE TITLE
Stylesheet.create incompatible return type

### ISSUE THREAD

**Issue by badsyntax** [necolas/react-native-web#2068]
**The problem**

The return type of RNW `StyleSheet.create` is incompatible with RN `StyleSheet.create`. This causes problems in css libraries where RN is aliased to RNW via https://www.npmjs.com/package/babel-plugin-react-native-web.

RNW implementation: 

https://github.com/necolas/react-native-web/blob/13f7b9e2f45af2761bfdccd763c511992c0be030/packages/react-native-web/src/exports/StyleSheet/StyleSheet.js#L47-L57

RN implementation:

https://github.com/facebook/react-native/blob/36318b6776507ba31070f6c8a3493609238a1a98/Libraries/StyleSheet/StyleSheet.js#L359-L371

**How to reproduce**

```js
// RNW
StyleSheet.create({
  foo: {
    color: 'blue'
  }
})
// results in: { foo: 89 }


// RN
StyleSheet.create({
  foo: {
    color: 'blue'
  }
})
// results in: { foo: { color: 'blue' } }
```

Simplified test case: Not sure if this is useful: https://codesandbox.io/s/async-bush-kfpgo?file=/src/App.js

**Expected behavior**

I expect the return type to match RN.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.0
* React (version): 16.14.0
* Browser: n/a

**Additional context**

- I believe this was changed in RN with this commit: https://github.com/facebook/react-native/commit/a8e3c7f5780516eb0297830632862484ad032c10
- https://github.com/emotion-js/emotion/issues/1543#issuecomment-867583957

**Comment by necolas** [comment]
This has been discussed before and for now we keep the original RN return type as web optimisations are built around it

**Comment by badsyntax** [comment]
Okie doke. I took a quick look at the required changes and I agree it seems like high effort to refactor things to align with react-native, which is unfortunate. 

Here's some related issues where this change was previously discussed:

- https://github.com/necolas/react-native-web/issues/1593
- https://github.com/necolas/react-native-web/pull/1466
- https://github.com/necolas/react-native-web/issues/1259 (Possibly related, not sure)
