### ISSUE TITLE
Does'nt Navigator work?

### ISSUE THREAD

**Issue by 6pm** [necolas/react-native-web#207]
Default component Navigator not work? I not see this component in list your section "Exported modules". Thank you for answer.

**Comment by necolas** [comment]
That's right, Navigator is not supported. You should use one of the web routers.

**Comment by RangerMauve** [comment]
Just to confirm, @necolas, _will_ it be supported in the future? Or is there some reason against trying to support it?

**Comment by necolas** [comment]
I don't think it will ever be supported. `NavigatorExperimental` aims to work on web and you could use that once it's complete. Until then, there are dozens of web routing libraries including react-router (which can work on native platforms too).

**Comment by RangerMauve** [comment]
Awesome. Thanks for clarifying.

**Comment by KalKhera** [comment]
Hi necolas, can you point me to a react router example for native which does not need navigator?

**Comment by MoOx** [comment]
react-router 4 can handle native apparently, using memory history instead of browser history, otherwise, you have things like https://github.com/jmurzy/react-router-native

**Comment by KalKhera** [comment]
Merci Monsieur,
thanks for quick response

**Comment by sospedra** [comment]
Note also that `react-native-router` is gonna mimic `react-router@next` (v4) also. As stated:

> Please note that React Router v4 was just released. Over the next few weeks,
> React Router Native will be refactored to make it fully compatible with v4.

**Comment by zargold** [comment]
Unfortunately, that was written in October or so 6 months since react-router-native has been updated. Still very grateful for that work, but wondering what if any draw backs are there to using react-router@next (a) in web (b) in iOS/Android if anybody knows?
