### ISSUE TITLE
Href links stopped working in 0.17

### ISSUE THREAD

**Issue by robertherber** [necolas/react-native-web#2076]
**The problem**
I've used this approach to create links:
```TypeScript
ref.current?.setNativeProps({
  href: url,
  target: new URL(url).host, // prevent swamping the user with multiple tabs, try opening one per service
  draggable: false,
});
```

on views like this
```JSX
<View
  {...props}
  accessibilityRole='link'
  ref={ref as React.ForwardedRef<View>}
>
  { children }
</View>
```

wrapping the buttons etc with it to provide a web-native experience.

**How to reproduce**
https://codesandbox.io/s/loving-breeze-fn8ec

**Expected behavior**
Be able to wrap buttons etc with an element with accessibilityRole='link' and set a href to create web links.

**Environment (include versions). Did this work in previous versions?**
This worked before 0.17.x (as you can verify in the CodeSandbox above). Is there a new approach to links that I missed?

* React Native for Web (version): 17.x
* React (version): 17.x
* Browser: Tested Chrome and Safari

**Comment by necolas** [comment]
I don't know why you're using effects and setNativeProps to set the href when you can simply set that prop directly. See the release notes for more details on what changed in 0.17 https://github.com/necolas/react-native-web/releases/tag/0.17.0

**Comment by robertherber** [comment]
@necolas I'm not sure I follow? I get the feeling you mean there is very obvious better way to do this?

From what I can see using an `a` tag instead of a `View` changes the layout, setting href/target on a `View` results in type errors? If we should use `a` tags resetting its CSS (so it behaves like a View) would probably be a good idea. If it's supposed be set as a prop directly on a View the type definitions doesn't seem to reflect this (going down this route would mean ignoring type checking)?

Please elaborate :)

**Comment by necolas** [comment]
`<View href={url} />`.

The types for web are not the same as the types for native https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/View/types.js#L185

**Comment by robertherber** [comment]
Is there any way to get a hold of those types for TypeScript? And would it be considered safe to set those properties for native Views as well?

**Comment by robertherber** [comment]
It seems I still need to use `setNativeProps` since I need to set draggable=false. 

Is there a general principle for how RNW maps to DOM properties? Just in this example I see three levels of handling stuff:
- Some props - like `href` - maps directly to it's equivalent DOM attribute
- `hrefAttrs` which is the way to set the `download`, `rel`, `target` DOM attributes
- Most other DOM attributes I suppose are not supported and requires `setNativeProps`?

Wouldn't it be nice to allow all DOM props in a generic and predictable way? Something like prefixing DOMhref, DOMdownload, DOMrel, DOMtarget, DOMdraggable (there is probably a better naming convention, but you get the idea :). This would allow easily setting any web attribute - still keeping it clearly separated from react-native constructs.

**Comment by natew** [comment]
@robertherber this is something that's been asked on this project about a hundred times, for some reason the maintainer has an ideological stance that escape hatches are not allowed and therefore accessibility, DX, and usability aren't a priority for the project.

If you're interested in helping at all, I've been working on [a project](https://github.com/snackui/snackui) that builds off this one so you can still use anything from rnw, but forks the core components from View + Text into Stack + Text and allows for escape hatches on web.

**Comment by robertherber** [comment]
Thanks @natew, will definitely check it out!
