### ISSUE TITLE
StyleSheet: add support for all 'transform' and 'perspective' properties

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#208]
Support for various css properties is missing (you can use such properties and they will work, but then the very long red warnings in the console practically render the console unusable). Obviously you can fallback to standard web techniques of using a `className` and specifying such properties in standard CSS, but that comes with further complications when you need to dynamically change them in  javascript where the best practices approach would be to do it declaratively in your react components, rather than an old fashioned imperative "hack" to apply the style properties. 

I'm not fully sure what the goals of RNW are, but more and more it's seeming like RNW should be a superset of standard React Native by supporting a few web-specific things that native code can't make use of, especially in regards to css.

**Comment by faceyspacey** [comment]
oh, I see, you can use perspective in a `transform` style prop, but the other origin props are missing. I see React Native doesn't support them either: https://facebook.github.io/react-native/docs/transforms.html ...Perhaps RNW supports them as transforms so the API is more consistent with RN.

**Comment by necolas** [comment]
Yeah RN doesn't support all those yet. I can look at adding web support though. `perspective` isn't currently handled correctly as it needs to be mapped to its own css property rather than a transform function

**Comment by necolas** [comment]
`perspective` is now fixed in master. I do think RN should have all the transform and perspective properties, and that it should move `perspective` out of `transform` into its own property. There doesn't seem to be any benefit to deviating from the CSS spec here. Would you mind opening an issue against RN?

**Comment by MiLeung** [comment]
Is transform-origin supported on RNW? Or is RNW supposed to be an exact replica of RN for the web?

**Comment by necolas** [comment]
It's supported, as mentioned in the docs
