### ISSUE TITLE
FlatList: Can't scroll horizontally by dragging the mouse 

### ISSUE THREAD

**Issue by hitman249** [necolas/react-native-web#2089]
**The problem**
```
<FlatList
  horizontal={true}
  showsVerticalScrollIndicator={false}
  showsHorizontalScrollIndicator={false}
  ...
/>
```
Can't scroll horizontally by dragging the mouse.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.16.3
* React (version): 0.64.0
* Browser: Chrome

**Comment by bisho1995** [comment]
@hitman249 I think this feature is not implemented by default in the browsers. If you need this, you have to implement it yourself.

Check this [https://youtu.be/C9EWifQ5xqA](https://youtu.be/C9EWifQ5xqA)

**Comment by nandorojo** [comment]
I have a solution for this here: https://gist.github.com/nandorojo/92e7301a49a8b9575bb24b3b1ddc19bf

**Comment by necolas** [comment]
You can't scroll with mouse drag on web scroll views. No plan to add this

**Comment by testermumatstudio** [comment]
hi, thanks for sharing, how can i implement this in a flatlist
