### ISSUE TITLE
ScrollView onScroll handler triggers on completion triggers this warning: "Warning: This synthetic event is reused for performance reasons"

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#209]
Here's the full warning:

_Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information._

Based on what the link says, it appears RNW is still working with the event after scrolling has stopped. 

If you're providing a callback directly you can simply not access `nativeEvent` if it's null. However, if you're doing the extremely useful and nice pattern of using `Animated.event` mappings, there doesn't appear to be anything you can do to stop error. So it seems to be something that needs to be fixed within the framework, i.e. so it checks the value of `nativeEvent`. Here's what I'm referring to:

```
<ScrollView
  onScroll={Animated.event(
      [{nativeEvent: {target: {scrollTop: this.animationValue}}}], //map to AnimatedValue 
  )}
>
```

On a side note, my first attempted was to map to `{nativeEvent: {contentOffset: {y:` as would normally work in React Native, but the same API is not kept at this level of granularity unfortunately. 

ps. so happy to see features like mapping to  `AnimatedValue.setValue()` and animation interpolation in RNW! opens up a lot of possibilities.

**Comment by faceyspacey** [comment]
I see how the `animated` library is being used which already has the goal of bringing RN's Animated lib to the web. So unless we are to touch that, it seems maybe we should test if `nativeEvent` is null and not call `onScroll` here:

https://github.com/necolas/react-native-web/blob/master/src/components/ScrollView/ScrollViewBase.js#L73

As well as most likely in `_handleScrollEnd`. The thing is it's getting called multiple times at the end once it's `null`. So that says to me it's being called both at the end and in the last few ticks of the scroll. This solution may be a hack though and the right solution might lie in the `animated` library, I'm not sure.

**Comment by necolas** [comment]
Please can you provide a reduced test case and some of the other information asked for in the issue template

**Comment by necolas** [comment]
I was looking over `animated` and part of the problem appears to be there. It doesn't seem to be maintained anymore either, so I might have to switch back to copy-pasting `Animated` from RN and avoiding the calls into native code.

RN also has different events to React. Not easy to build a cross-platform API on different synthetic events :/.

**Comment by bigbee** [comment]
I have the same warning on every scrollend.

It looks like it is happening because scrollEnd is throttled. Since react reuses event objects, you cannot access the event after the onScroll has finished executing - which the debounced scrollEnd tries to do.

Happens here: https://github.com/necolas/react-native-web/blob/master/src/components/ScrollView/ScrollViewBase.js#L36
