### ISSUE TITLE
Can't install react-native-web unless running --legacy-peer-deps

### ISSUE THREAD

**Issue by ceres-dev-team** [necolas/react-native-web#2090]
**The problem**
when I run `npm install` I get an error that it's `unable to resolve dependency tree` but if I remove `react-native-web` everything install just fine and I no longer get this error but one of my packages requires RNW to work. 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.6" from react-native-youtube-iframe@2.1.0
npm ERR!   node_modules/react-native-youtube-iframe
npm ERR!     react-native-youtube-iframe@"^2.1.0" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=17.0.1" from react-native-web@0.17.1
npm ERR! node_modules/react-native-web
npm ERR!   peer react-native-web@"*" from react-native-web-webview@1.0.2
npm ERR!   node_modules/react-native-web-webview
npm ERR!     peer react-native-web-webview@">=1.0.2" from react-native-youtube-iframe@2.1.0
npm ERR!     node_modules/react-native-youtube-iframe
npm ERR!       react-native-youtube-iframe@"^2.1.0" from the root project
```

**How to reproduce**

Running expo v42, and using ` "react-native-youtube-iframe": "^2.1.0",` which requires `react-native-web`
Simplified test case: 

Steps to reproduce:
1. latest version of expo (42)
2. install    "react-native-youtube-iframe": "^2.1.0",
3. try to install and run react native web

**Expected behavior**
`npm install` should install everything without a problem and I should be able to play youtube videos inside of the app using 
`"react-native-youtube-iframe"`. I have posted this issue on their github but it seems like the issue is happening because of react-native-web.

**Environment (include versions). Did this work in previous versions?**
* React Native for Web (version):   
` "node_modules/babel-plugin-react-native-web": {
      "version": "0.13.18",` 
      Doing `npm i react-native-web@latest` throws the same dependency error: 
      
<img width="494" alt="CleanShot 2021-07-18 at 12 40 55@2x" src="https://user-images.githubusercontent.com/87544598/126076999-e1989486-8a46-469b-81b1-c5a0958918e5.png">

* React (version): "react": "16.13.1",
* "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
*    "react-native-youtube-iframe": "^2.1.0",
* Browser: using for react native only. 
ios version 14 and android v11

**Comment by necolas** [comment]
> react@"16.13.1" from the root project

This is telling you that your project depends on a version of React not compatible with the version of React Native for Web. It needs >=17, you are using 16
