### ISSUE TITLE
Style overrides don't work in specific case.

### ISSUE THREAD

**Issue by owenjeon** [necolas/react-native-web#2093]
**The problem**

After style is created as a hashed class through `StyleSheet.create`, even if the same style is declared as `StyleSheet.flatten`, it is not created inline style, and it seems to use the previously created class name.

This causes the style priority to be twisted.
Please refer to the example below for details.

**How to reproduce**

I made sample code for reproducing on sandbox.
In this case, the innermost View `marginLeft` should be overridden by 5. But the result is 30.
- https://codesandbox.io/s/rnw-style-override-wc5n0

Codes
```javascript
export default function App() {
  const dynamicStyle = { marginLeft: 5 };
  return (
    <div className="App">
      <View style={style.wrap}>
        <View style={StyleSheet.flatten([style.inner, dynamicStyle])} />
      </View>
    </div>
  );
}

const style = StyleSheet.create({
  wrap: {
    backgroundColor: "yellow",
    marginLeft: 5
  },
  inner: {
    backgroundColor: "green",
    height: 100,
    margin: 30
  }
});
```
Result (Computed Style)
![image](https://user-images.githubusercontent.com/14075436/126641625-95c2cad9-9f6b-46e2-845c-13b48572560a.png)

**Expected behavior**

Style priorities working correctly.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.1
* React (version): 17.0.1
* Browser: chrome

**Comment by necolas** [comment]
Duplicate #2007
