### ISSUE TITLE
Module react-native-web/jest/serializer in the snapshotSerializers option was not found

### ISSUE THREAD

**Issue by kiranlanke** [necolas/react-native-web#2105]
**Note:** Also asked the same question in [SO](https://stackoverflow.com/q/68766620/3142611) but didn't get the reply yet

**Question**
Trying to commit React code to GitHub, when i pushed the code, got this problem

`TypeError: Cannot read property 'injection' of undefined`

![image](https://user-images.githubusercontent.com/15002093/129317668-41b47ae9-4e3e-4ae9-b436-72826becf2c5.png)

To solve this problem, updated react-native-web package to 0.17.0. Then this problem solved but ended up with below error

`Module react-native-web/jest/serializer in the snapshotSerializers option was not found`

![image](https://user-images.githubusercontent.com/15002093/129329370-9abd57cb-30e0-447c-9aec-7ecfca6c882c.png)

Tried to solve this problem but didn't get much discussions in online except [this](https://github.com/necolas/react-native-web/issues/1012#issuecomment-414444951) (i didn't get what is he telling exactly)

How to resolve this error

**Comment by necolas** [comment]
There is no `react-native-web/jest/serializer` anymore. You should remove it from your jest setup

**Comment by KiranTem** [comment]
Thank you for your reply. Apologies for delay

After removing `react-native-web/jest/serializer`  from `snapshotSerializers` getting this issue

`TypeError: Cannot read property 'twoArgumentPooler' of undefined`

![image](https://user-images.githubusercontent.com/65328506/129489372-d992c4df-002d-44bb-af52-2ccca0bea7e8.png)

unfortunately didn't have much search results in Google/SO/Git

**Comment by kiranlanke** [comment]
Thank you for your reply. Apologies for delay

After removing react-native-web/jest/serializer from snapshotSerializers getting this issue

`TypeError: Cannot read property 'twoArgumentPooler' of undefined`

![image](https://user-images.githubusercontent.com/15002093/129514261-4763d3fd-9953-4331-aaef-bb436c7c46a4.png)


unfortunately didn't have related search results in Google/SO/Git
