### ISSUE TITLE
image resizeMode cause err

### ISSUE THREAD

**Issue by wollld** [necolas/react-native-web#211]
**What is the current behavior?**

Link to minimal test case: (template: [codepen](https://codepen.io/necolas/pen/PZzwBR?editors=0010))

**What is the expected behaviour?**

**Steps to reproduce**
error:-------------
income.js?version=1474525325576:272 Warning: Failed prop type: Invalid props.style key `resizeMode` supplied to `View`.
Bad object: {
  "alignSelf": "flex-start",
  "backgroundColor": "transparent",
  "backgroundPosition": "center",
  "backgroundRepeat": "no-repeat",
  "backgroundSize": "contain",
  "width": 10,
  "alignItems": "center",
  "resizeMode": "contain",

**Environment (include versions)**

OS: mac
Device:
Browser:
React Native for Web (version):
React (version):

**Comment by corymsmith** [comment]
@wollld `resizeMode` should be a prop on the Image itself and shouldn't be contained in the styles. 

```jsx
<Image resizeMode='contain' />
```

**Comment by necolas** [comment]
Please can you include a test case and fill in the template information (e.g., which version of the library are you using?). I quickly tried to reproduce this with the latest version of RNW and couldn't, so I'll close this issue in the mean time.

@corymsmith `resizeMode` is also supported as a `style`.

**Comment by corymsmith** [comment]
@necolas Ahh yes, you're correct. The error message says `Invalid props.style key resizeMode supplied to View.` so the issue may be that the style is being using on a View component vs. an Image

**Comment by wollld** [comment]
function resizeMode(type){
    if(window.document){
        return {}
    }else{
        return {
            resizeMode: type
        }
    }
}
export default resizeMode;
-----------------------------
import React from "react";
import {StyleSheet,View,Text,Image} from "react-native";
import resizeMode from "../../commonKit/resizeMode";

var headerSty= StyleSheet.create({
    wrap: {
        height: 45,
        flexDirection: "row",
        backgroundColor: "#d75143"
    },
    left: {
        width:80,
        justifyContent: "center",
        paddingLeft: 10,

    },
    leftImg:{
        width: 22,
        //resizeMode: "contain",
    },
    topic: {
        top: 10,
        flex:1,
        fontSize: 18,
        textAlign: "center",
        color: "#fff",
    },
    right: {
        top: 12,
        width: 80,
        fontSize: 14,
        color: "#fff",
        textAlign: "center",

    }
})
var Header =(props)=>{
    return (
        <View style={headerSty.wrap}>
            <View style={headerSty.left}>
                <Image source={require("./icon_back.png")} style={[headerSty.leftImg,resizeMode("contain")]} onPress={props.press}/>
            </View>

            <Text style={headerSty.topic}>{props.topicText}</Text>
            <Text style={headerSty.right}>{props.rightText}</Text>
        </View>
    )
}

exports.Header= Header;
------------------------
i write a function to prevent error, can you provide a better way
我写了一个函数 阻止报错 能够提供更好的方法吗

**Comment by necolas** [comment]
Please can you include a test case and fill in the template information (e.g., which version of the library are you using?).
