### ISSUE TITLE
numberOfLines=1 does not work on Safari

### ISSUE THREAD

**Issue by janicduplessis** [necolas/react-native-web#2111]
**The problem**

`numberOfLines={1}` has no effect on Safari. This seems to be caused by this commit https://github.com/necolas/react-native-web/commit/ab98851881d10bfe11aee2eb8e3320474174fc8e#diff-fe65c584905c7546103177805c46541e3c38992b188e97600cd1fec4bce5307f. Safari requires having `nowrap` for it to work.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/stupefied-pike-hyhjn?file=/src/App.js

Steps to reproduce:
1. Open test case in Safari

Safari:

![image](https://user-images.githubusercontent.com/2677334/130509950-89f58360-60b8-447e-8577-94848af45d49.png)

Chrome:

![image](https://user-images.githubusercontent.com/2677334/130509987-fce2e9c6-6f88-4420-9fb8-35f8560f0c43.png)

**Expected behavior**

Text has an ellipsis and a single line

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.1
* React (version): N/A
* Browser: Safari 14.1.1

I made a patch in my fork to use the multiline implementation in all cases, can PR it if it looks good. I think the main issue with using it is slighly lower browser support (no IE). https://github.com/janicduplessis/react-native-web/commit/26fca0136557db4cdbc694ee1c27afe41e5e4886

**Comment by tomLadder** [comment]
not merged?
