### ISSUE TITLE
Should `Button`, `Pressable`, etc fire a `click` event?

### ISSUE THREAD

**Issue by kirbyfu** [necolas/react-native-web#2115]
**The problem**
Should `Button`, `Pressable`, etc fire a `click` event? Is there a reason why it doesn't?

**How to reproduce**
Simplified test case: [sandbox](https://codesandbox.io/s/compassionate-field-nb83k?file=/src/App.js)

Steps to reproduce:
1. Clicking anywhere outside the button emits a click event
2. Clicking the button doesn't emit a click event

**Comment by necolas** [comment]
They prevent click bubbling. You can listen to the capture phase if needed
