### ISSUE TITLE
<ScrollView /> horizontal cannot be scroll using drag on desktop browsers

### ISSUE THREAD

**Issue by kopax-polyconseil** [necolas/react-native-web#2122]
**The problem**

We use react-native-web to port our react-native application into a Web application.

I am using a `horizontal` `<ScrollView />`.

- it can't be drag on mobile browsers
- it is not draggable on desktop browser

We rather not have to use the `showsHorizontalScrollIndicator` on desktop.

Without it there's no way to scroll unless user hold `shift` and use the scroll when hovering.

This is not user friendly at all.

**How to reproduce**

```jsx
      <ScrollView
        horizontal={true}
        showsHorizontalScrollIndicator={false}
        scrollEventThrottle={200}
        onScroll={onScroll}>
        {items.map(renderItem)}
      </ScrollView>
```

**Expected behavior**

I expect the `<ScrollView horizontal />` to be scrollable on the web with the `onDrag`

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): `0.17.1`
* React (version): `17.0.2`
* React Native: `0.64.2`
* Browser: `google-chrome-stable@94.0.4606.20-1`

**Comment by necolas** [comment]
> it can't be drag on mobile browsers

Can't reproduce: https://codesandbox.io/s/angry-field-twi3l

> it is not draggable on desktop browser

That is normal behavior when using a mouse to interact with a scroll view on web.
