### ISSUE TITLE
Support for PlatformColor?

### ISSUE THREAD

**Issue by JCMartell** [necolas/react-native-web#2128]
In React Native, there's an API called [PlatformColor](https://reactnative.dev/docs/platformcolor) to get native colors. Is there any plan to support this API in RNWeb in the near future?

**Comment by necolas** [comment]
Since this API is only for accessing native color names, I don't see how it relates to web

**Comment by marklawlor** [comment]
@necolas Currently [this example](https://reactnative.dev/docs/platformcolor#example) on the React Native docs crashes in React Native Web. I think that example shows a valid use-case where `PlatformColor` is needed in RNW, even if its an empty function with no implementation.

**Comment by sem4phor** [comment]
Would be cool if this maps to system colors on web :) https://developer.mozilla.org/en-US/docs/Web/CSS/system-color

**Comment by vendramini** [comment]
Is there a way to bypass this issue? It's weird because this problem doesn't happen when using Expo and exports for web. But when we create a vite project with RNW, it does happen. Any ideas?
