### ISSUE TITLE
Import some other js modules

### ISSUE THREAD

**Issue by vvinichuk** [necolas/react-native-web#213]
Is there any way to connect some other js modules e.g. **react-bootstrap-date-picker**
I've imported into my react-native application and it doesn't raise any errors, but after I build with **react-native-web** it says **'input-card.web.js:1 Uncaught Error: Cannot find module "react-bootstrap-date-picker'**

How can I build successfully with some other js modules?

**Comment by necolas** [comment]
Hi, when opening an issue please fill out the default template so I have some information to go on. This doesn't seem to be a bug in the library but in your build step, so I'm going to close this issue.
