### ISSUE TITLE
'Animated' is not smooth when there're many animations

### ISSUE THREAD

**Issue by ChrisOHu** [necolas/react-native-web#214]
Hi guys,

First really awesome library to bring react-native to the web front end 👍 

Currently I'm using this to write an HTML-5 page which uses a lot of ```Animated``` animations, which doesn't seem very smooth, so I would guess the animations are being run in the main thread which would be blocked let's say, when there're lots of animations ?

If so wondering if this could be improved ? E.g. put the animations work in another worker maybe ?

**Comment by necolas** [comment]
Hi, I'd open this issue against React Native or the separate Animated package: https://github.com/animatedjs/animated

**Comment by faceyspacey** [comment]
@ChrisOHu any discoveries regarding how to optimize multiple animations? Perhaps tweaks that need to be made to the `animated` library?

**Comment by necolas** [comment]
I don't think `animated` is maintained. I'd be open to a PR that reintroduces the RN Animated library.

**Comment by faceyspacey** [comment]
Have you looked into samsara: http://samsarajs.org

It's interface shares a lot in common with Animated. I feel like it could be a powerful way to power a future `Animated` for both and RN and react on the web. Just last week I shared my thoughts about it with its creator (ex-Famous employee) here:

https://github.com/dmvaldman/samsara/issues/9

It's probably a lot of work to get a full samsara interface in RN, but what in fact may in fact be surprisingly easy is a mirror of the Animated api, just using Samsara to power it. And obviously the *hope* would be that its performance is many times better.

**Comment by ChrisOHu** [comment]
Perhaps react-motion (https://github.com/chenglou/react-motion) ?
