### ISSUE TITLE
Add image-rendering support?

### ISSUE THREAD

**Issue by Estevete** [necolas/react-native-web#2145]
**Is your feature request related to a problem? Please describe.**

Having small images, if you want to display them with a bigger size, with this property it will look so much better. Otherwise, we see the image blurred. Currently, we are able to use it, but if you're using typescript, you get a type check error.

![image](https://user-images.githubusercontent.com/19273351/137284865-f9a9a2dc-f7a5-41a1-bbc6-78376c476292.png)

![image](https://user-images.githubusercontent.com/19273351/137284982-cdace777-a6c3-4d5b-8623-a69497b21334.png)

(In this example, I'm using `Image` component from `react-native-elements`)

**Describe a solution you'd like**

Add type support for imageRendering.

**Comment by necolas** [comment]
The typescript definitions are not maintained here. And `containerStyle` is not a valid prop on `Image`
