### ISSUE TITLE
TextInput: Can't capture 'enter' key with onChange or onChangeText events

### ISSUE THREAD

**Issue by jeffgorder** [necolas/react-native-web#215]
Pressing 'enter' when in a TextInput doesn't fire the onChangeText or onChange events. If a TextInput is used to capture text to be submitted, it doesn't seem like there is a way to determine that the 'enter' key was pressed.

**Comment by necolas** [comment]
Thanks. `TextInput` should support all `View` propTypes, which on web will include the keyboard event handlers. I'll get a patch for this in the next release and would appreciate your help confirming all is good

**Comment by jeffgorder** [comment]
I'm happy to help confirm a fix.

**Comment by jeffgorder** [comment]
I've confirmed that this is working.

**Comment by necolas** [comment]
Great, thanks!
