### ISSUE TITLE
KeyboardAvoidingView does not work like native

### ISSUE THREAD

**Issue by rissois** [necolas/react-native-web#2152]
Apologies as I do not fully understand what "Mock. No equivalent web APIs." means for its development.

**The problem**
No behavior props enable KeyboardAvoidingView to work correctly. It shifts vertically slightly, but hides other crucial components in the top and bottom portions of the screen.

**How to reproduce**
https://codesandbox.io/embed/react-native-web-root-element-styles-forked-2px85?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Depending on implementation and ability to detect keyboard height, KAV should implement a view that adjusts its height or padding.

**Comment by necolas** [comment]
It means importing the component won't crash on web, but the functionality can't be reproduced on that platform

**Comment by rissois** [comment]
> It means importing the component won't crash on web, but the functionality can't be reproduced on that platform

Thanks @necolas , really appreciate the package. It's interesting that there is some TextInput recognition and component shift, but justifying center to compensate.

**Comment by Gregoor** [comment]
Would you be open for a PR that makes a stab at a stub that tries to emulate the original behavior? I've gotten pretty far with RN's `useKeyboard().keyboardHeight` in my web-supporting app.
