### ISSUE TITLE
[question] AccessibilityRoles which is particular to RNW dose not work in Android

### ISSUE THREAD

**Issue by pokuwagata** [necolas/react-native-web#2154]
I need roles (`contentinfo`, `article` ...) in order to build semantic HTML for web app in RNW
but  Android builds does not work because these roles are not supported in Android.
These roles are used only for web ?  How can I build semantic HTML and Android code at the same time ?

**Comment by intergalacticspacehighway** [comment]
React Native (Android/iOS) only supports [these roles](https://reactnative.dev/docs/accessibility#accessibilityrole). 
You can use Platform.OS check to add the role you need on web and pass undefined on Android/iOS or take a look at this library from expo that handles it for you. https://github.com/expo/expo/tree/master/packages/html-elements

**Comment by necolas** [comment]
Closing because the question has been answered above

**Comment by pokuwagata** [comment]
Thanks @intergalacticspacehighway
