### ISSUE TITLE
Is Animated broken ?

### ISSUE THREAD

**Issue by agenthunt** [necolas/react-native-web#216]
**What is the current behavior?**
Animated API seems to be broken. It fails with following stacktrace

<pre>
react-native-web@latest:6 Uncaught TypeError: Cannot read property 'stopTracking' of undefinedstart @ react-native-web@latest:6
startAnimation @ pen.js:40
onPress @ pen.js:78
touchableHandlePress @ react-native-web@latest:3
_performSideEffectsForTransition @ react-native-web@latest:3
_receiveSignal @ react-native-web@latest:3
touchableHandleResponderRelease @ react-native-web@latest:3
(anonymous function) @ react-native-web@latest:4
r.invokeGuardedCallback @ react-native-web@latest:13
a @ react-native-web@latest:10
s @ react-native-web@latest:10
d @ react-native-web@latest:10
h @ react-native-web@latest:10
o @ react-native-web@latest:16
processEventQueue @ react-native-web@latest:10
o @ react-native-web@latest:13
handleTopLevel @ react-native-web@latest:13
i @ react-native-web@latest:13
perform @ react-native-web@latest:16
batchedUpdates @ react-native-web@latest:13
i @ react-native-web@latest:14
dispatchEvent @ react-native-web@latest:13
</pre>

Link to minimal test case: (template: [codepen](http://codepen.io/agenthunt/pen/WGjVYG))

**What is the expected behaviour?**
Animation should start when start button is pressed

**Steps to reproduce**

See codepen link
**Environment (include versions)**

OS: mac
Device: 
Browser: Chrome
React Native for Web (version): 0.0.45
React (version): 15.3.2

**Comment by necolas** [comment]
Animated is an external dependency: https://github.com/animatedjs/animated. I'd open issues against that repo. Looks like it is falling behind RN `Animated`.
