### ISSUE TITLE
View onLayout is not called in Safari Mobile iOS <= 12

### ISSUE THREAD

**Issue by kopax-polyconseil** [necolas/react-native-web#2161]
**The problem**
`onLayout` props from `<View />` is broken on Safari Mobile <= 12 :
```
<View onLayout={onLayout} />
```

**How to reproduce**

https://github.com/reactrondev/react-native-web-swiper/blob/master/src/Swiper.js#L242

Steps to reproduce:
1. Create a swiper or use an example provided by the documentation, add a `console.log` in the `onLayout`
2. Run it in the web, it will log
3. Run it on Safari Mobile <= 12 , it will not log

**Expected behavior**

I expected `onLayout` to be called

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.1
* React (version): 0.64.2
* Browser: iPhone 6, Safari Mobile <= 12

OPTIONAL:

**Additional context**

Related to https://github.com/pass-culture/pass-culture-app-native/pull/1894 and https://github.com/reactrondev/react-native-web-swiper/issues/73

**Comment by necolas** [comment]
Requires a ResizeObserver polyfill, as should be printed to the console https://necolas.github.io/react-native-web/docs/browser-compatibility/#javascript

**Comment by kopax-polyconseil** [comment]
Hi @necolas , may I ask how do you use it ?

After doing `yarn add -D resize-observer-polyfill` in our project, I. can read [this](https://www.npmjs.com/package/resize-observer-polyfill#usage-example), but it is unclear where this should be used to fix the Safari Mobile on iOS

## Usage Example
It's recommended to use this library in the form of a ponyfill, which doesn't inflict modifications of the global object.

```jsx
import ResizeObserver from 'resize-observer-polyfill';
 
const ro = new ResizeObserver((entries, observer) => {
    for (const entry of entries) {
        const {left, top, width, height} = entry.contentRect;
 
        console.log('Element:', entry.target);
        console.log(`Element's size: ${ width }px x ${ height }px`);
        console.log(`Element's paddings: ${ top }px ; ${ left }px`);
    }
});
 
ro.observe(document.body);
```

Package's main file is a ES5 UMD bundle that will be swapped with the ES6 modules version for those bundlers that are aware of the module field, e.g. for Rollup or webpack 2+.

Note: global version of the polyfill (dist/ResizeObserver.global) is deprecated and will be removed in the next major release.

**Comment by necolas** [comment]
You have to assign it to `window.ResizeObserver` if the native class isn't available. Google about polyfilling web APIs
