### ISSUE TITLE
removeListener deprecated

### ISSUE THREAD

**Issue by jer-sen** [necolas/react-native-web#2166]
In `react-native@0.65.0` they deprecated the old api in favour of a more terse name, so `removeListener()` becomes `remove()`.

This line
https://github.com/necolas/react-native-web/blob/081a128db325f9ee10c359e304e9f6cc7f4f9c56/packages/react-native-web/src/exports/AppState/index.js#L81
raise the `console.error` message
`EventEmitter.removeListener('function(e){a(e)}', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.`

**Comment by MarioRover** [comment]
In react-native@0.66.4 when return addEventListener to a subscription at useEffect, then use remove method to remove subscription, web app CRASH...!!!!!!
`useEffect(() => {
    const subscription = Linking.addEventListener('url', handler);
    return () => subscription.remove();
} ,[])`
