### ISSUE TITLE
a webpack set

### ISSUE THREAD

**Issue by wollld** [necolas/react-native-web#217]
now,i use react-native-web, in native,web platform .i want to write 3 file  name is  dialog.web.js and dialog.ios.js  dialog.android.js   i want use webpack  to compile web  and if there is no dialog.js i require dialog.web.js  what should i do ?

**Comment by necolas** [comment]
Webpack resolves files with web.js extension by default. See https://webpack.github.io/docs/configuration.html→resolve.extensions
