### ISSUE TITLE
flatlist triggers onEndReached event easily trigger item click event

### ISSUE THREAD

**Issue by yexianli** [necolas/react-native-web#2174]
**The problem**
When I slide the FlatList up and down to load the next page of data, it is easy to trigger the item's click event

**How to reproduce**

When I slide the FlatList to trigger the onEndReached event

Simplified test case:  http://shopdev.gf.com.cn/new/#/VideoList

Steps to reproduce:
1.Slide the list to load the next page of data

**Expected behavior**

Does not trigger the click event of the Item when sliding the list

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version):"^0.11.7",
* React (version): react (version) 16.5.1
* Browser: google

**Comment by rissois** [comment]
Hi @yexianli ,

I am not a contributor on this project, but you should really follow the posting guidelines and fork the appropriate [CodeSandbox.io](https://codesandbox.io/s/6lx6ql1w5r) template. Otherwise, people cannot see your code and understand where you might be having issues.

**Comment by yexianli** [comment]
> Hi @yexianli ,
> 
> I am not a contributor on this project, but you should really follow the posting guidelines and fork the appropriate [CodeSandbox.io](https://codesandbox.io/s/6lx6ql1w5r) template. Otherwise, people cannot see your code and understand where you might be having issues.

Similar to this question, https://github.com/facebook/react-native/issues/27355, maybe I got it wrong and it’s not your problem
