### ISSUE TITLE
absolute style will cause untouchable in some situation

### ISSUE THREAD

**Issue by flyskywhy** [necolas/react-native-web#2179]
**The problem**
As below link shows, the `TouchableOpacity` `Text` 'foobar' can not be touchable on react-native-web, but be touchable on react-native.

**How to reproduce**
Simplified test case: https://codesandbox.io/s/blissful-blackwell-ffyfp?file=/src/App.js:444-448

Steps to reproduce:
1. move your mouse on 'foobar' in the `Browser` of above link, you will find it.

**Expected behavior**
The mouse pointer should be a hand icon, and can click the 'foobar'.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.0, 0.17.5, 0.12.3
* React (version): 17.0.2, 16.13.1
* Browser: Chrome

workaroud:
1. remove the 1st  `style={{flex: 1}}`;
2. or, remove the 2nd `style={{flex: 1}}`;
3. or, switch the position of the two nested `View`, in other words, let the `View` which contains the `TouchableOpacity` to be the final component of the APP.

**Comment by necolas** [comment]
Add `zIndex:1` to the positioned view. Looks like RN gets this wrong compared to web. The RN layout model isn't very well defined, and views act as position relative in many ways but not in terms of layout stacking here.
