### ISSUE TITLE
How to avoid typescript showing error for <Pressable> props

### ISSUE THREAD

**Issue by Saikedo** [necolas/react-native-web#2180]
**The problem**
React Native Web adds some additional props to <Pressable> component.
For example `onHoverIn` does not exist in react-native but does exist in react-native-web. Is there any way to make typescript recognize the added props?

You can look at this snack. As you can see, The functionality of `onHoverIn` and `onHoverOut` works as expected but typeScript still shows an error
Simplified test case: (https://snack.expo.dev/KXvr3_XMQ)

**Expected behavior**
Expecting TypeScript to recognize the additional props added by React-Native-Web

**Comment by necolas** [comment]
Probably need to get those types included wherever the RN TypeScript definitions are maintained. The hover stuff is coming to RN in 2022 as part of the feature set needed by Desktop and VR.

**Comment by tgreco** [comment]
@necolas any idea when we will get a version of react-native-web on the newest RN version ?
