### ISSUE TITLE
TextInput API docs is misleading on autoComplete

### ISSUE THREAD

**Issue by conor909** [necolas/react-native-web#2183]
The [TextInput API](https://necolas.github.io/react-native-web/docs/text-input/) mentions that the `autoComplete` prop follows [HTMLElement.autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) (although at the time of writing, this is link is broken)

I believe it is intended to follow the [aria-autocomplete API](https://developer.mozilla.org/en-US/docs/web/Accessibility/ARIA/Attributes/aria-autocomplete) instead?

Since adding `autoComplete="off"` does nothing to turn off autocomplete, yet adding `autoComplete="none"` works.

**How to reproduce**
```
<TextInput autoComplete='off' /> // --> does not turn off autocomplete on web
<TextInput autoComplete='none' /> // --> turns off autocomplete on web
<TextInput autoComplete={ Platform.OS !== 'web' ? 'off' : 'none' }  /> // --> turns off autocomplete on web and Android
```

**Environment (include versions). Did this work in previous versions?**
* Expo: 42.0.4
* React Native: 0.63.2 (https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz)
* React Native for Web (version): 0.13.18
* React (version): 16.13.1
* Browser: Chrome 96.0.4664.110 (Official Build) (x86_64)

**Comment by necolas** [comment]
Update to version 0.17

**Comment by conor909** [comment]
@necolas so does this mean the API follows the HTML Attribute AutoComplete in 0.17, and follows the aria-autocomplete in <0.17?

Because I can’t upgrade yet since I’m locked into whatever my expo version supports
