### ISSUE TITLE
Incorrect behaviour of numberOfLines={1} in Text 

### ISSUE THREAD

**Issue by masiacra** [necolas/react-native-web#2186]
`**The` problem**
After patch 0.17.5 <Text numberOfLines={1}>some text</Text> doesn't work similar with same tag with same property in react-native-web ver. 0.17.1
**How to reproduce**

Simplified test case: https://codesandbox.io/s/sharp-resonance-0mdje

Steps to reproduce:
For react-native-web: 0.17.1 if we have <View style={{maxHeight: 252}}><Text numberOfLine={1}>goal aaaaaaaaaaaaaaaaaaaaa</Text></View>
Text fit all available space in div

In patch 0.17.5 when we use same tags with same props we see only "goal ...."
**Expected behavior**
text fit all available space and truncates with ...

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.5
* React (version): 17.0.*
* Browser: firefox, google chrome latest versions

OPTIONAL:
To fix this problem we can use for numberOfLines === 1 next style={{ whiteSpace: 'nowrap', display: 'initial' }}

**Comment by parasharrajat** [comment]
I am facing the same issue. Here is Repro https://codesandbox.io/s/nostalgic-golick-6hc4i.

if we use `numberOfLines={1}`. Multi lines styles are applied which I can confirm by looking at the CSS class name `.css-textMultiLine-cens5h`.

**Comment by necolas** [comment]
Read through https://github.com/necolas/react-native-web/issues/2111 and let me know what the patch is it cover both these issues

**Comment by parasharrajat** [comment]
I can see that https://github.com/necolas/react-native-web/pull/2113 for #2111 caused this issue.

**Comment by parasharrajat** [comment]
@necolas I have created a PR https://github.com/necolas/react-native-web/pull/2193. Thanks.

**Comment by parasharrajat** [comment]
PR Updated and failing tests fixed. What do you think? @necolas
