### ISSUE TITLE
TypeScript support for accessibilityRole

### ISSUE THREAD

**Issue by kopax-polyconseil** [necolas/react-native-web#2194]
**Is your feature request related to a problem? Please describe.**

Currently, using `accessibilityRole` in a TypeScript `react-native-web` project generate ts errors.

**Describe a solution you'd like**

Support TypeScript for `accessibilityRole`.

**Describe alternatives you've considered**

Using `@ts-ignore` where we use `accessibilityRole`.

**Additional context**

https://github.com/necolas/react-native-web/issues/2189#issuecomment-1008886405

**Comment by necolas** [comment]
I don't maintain ts types for this library. Maybe ask about this in the repo that has the RN types you are depending on

**Comment by orlando** [comment]
Using the same approach described here https://github.com/necolas/react-native-web/issues/1684#issuecomment-772735882 you can extend the react-native `TextProps` interface to accept the react-native-web values via declaration merging.

```ts
declare module 'react-native' {
  interface TextProps {
    // https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/AccessibilityUtil/propsToAccessibilityComponent.js#L12
    accessibilityLevel?: number;
    accessibilityRole?:
      | 'heading'
      | 'label'
      | 'list'
      | 'listitem'
      | 'main'
      | 'region'
      | 'strong';
  }
}
```

This should work correctly to use [Semantic HTML](https://necolas.github.io/react-native-web/docs/accessibility/#semantic-html) with TypeScript.
