### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by gut4** [necolas/react-native-web#2196]
Any plans/roadmap to support react 18 concurrent features?

Looks like style system need changes
https://github.com/reactwg/react-18/discussions/110

**Comment by billouboq** [comment]
I think they are working on stylex at the moment with other people from facebook so we don't have to worry about react 18 support.

But yeah I'm really excited to know when those changes are going to be included in react-native-web 😄

**Comment by necolas** [comment]
See #2208 for a build that should support React 18 constraints

**Comment by ulantiger** [comment]
Hi there,

Got following error during installation:
Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^18.1.0" from the root project
npm ERR!   peer react-dom@"^17.0.2 || ^18.0.0" from react-native-web@0.18.10
npm ERR!   node_modules/react-native-web
npm ERR!     react-native-web@"*" from the root project

Thanks
