### ISSUE TITLE
Compiles with warnings: Import error ActionSheetIOS 

### ISSUE THREAD

**Issue by claudiaTonak** [necolas/react-native-web#2202]
I get an compilation warning:
./node_modules/react-navigation-header-buttons/src/overflowMenuPressHandlers.js:93:2        
Attempted import error: 'ActionSheetIOS' is not exported from 'react-native-web/dist/index'.
  91 |   })();
  92 | 
> 93 |   ActionSheetIOS.showActionSheetWithOptions(
     |  ^
  94 |     // $FlowFixMe - typings are old
  95 |     {
  96 |       options: actionTitles,

every time you use the latest react-navigation-header-uttons in your project

Simplified test case: 

Steps to reproduce:
1.
2.
3.

**Expected behavior**

no warning

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.5
* React (version): 0.64.3
* Browser: compiler warning

please just put an empty export in your project to avoid this warning:

class ActionSheetIOS {
  static showActionSheetWithOptions() {}
}

export default ActionSheetIOS;

**Comment by necolas** [comment]
AlertIOS hasn't been part of the RN API for 2 years
https://github.com/necolas/react-native-web/commit/920211b99852fc3717fc6f7e050ba273f1e2d26d

**Comment by claudiaTonak** [comment]
ActionSheetIOS not AlertIOS 
please just an empty definition to avoid the compiler warning
