### ISSUE TITLE
 Flatlist does not scroll on web, works fine on mobile (the second)

### ISSUE THREAD

**Issue by bohrsty** [necolas/react-native-web#2204]
The problem is the same as in #1436, the FlatList component doesn't scroll in correctly web, but does in android. I don't know why the issue was closed, I face the same... I also use react navigation in my app and expo as system to develop mobile and web...

Every parent has flex set to 1, as suggested in the comments, it doesn't change anything...

If the FlatList is filled, it seems that something is scrollable, but if I scroll down the whole page scrolls, but the next elements weren't shown, only one big white part of the page...

I'm not sure what might be the problem, is here something buggy or is there something I can change...

**Comment by necolas** [comment]
You can see it scrolls in the example embedded in the docs https://necolas.github.io/react-native-web/docs/lists/

**Comment by bohrsty** [comment]
yes, that list scrolls... the switches above weren't shown, but that's not the issue here...
