### ISSUE TITLE
Support optgroup for Picker

### ISSUE THREAD

**Issue by briankwlin** [necolas/react-native-web#2214]
The current [picker](https://necolas.github.io/react-native-web/docs/picker/) doesn't support categories/groups of options as part of its props. It would be great to have support for the native [optgroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) element as part of react-native-web, or if that's not possible, any alternative solution anyone can suggest. Thanks (:

![image](https://user-images.githubusercontent.com/12367435/151912716-c0b706b9-b404-47f3-9f62-d88d8a44c00d.png)

**Comment by necolas** [comment]
Yeah migrate away from Picker and use platform-file forking if needed. We have some plans to make web a first-class API in React Native, which will make a lot of these things easier to do https://github.com/react-native-community/discussions-and-proposals/pull/496
