### ISSUE TITLE
Notice about "Deprecate AppState remove method" that new api does not support for 0.16.4 react-native

### ISSUE THREAD

**Issue by siarheipashkevich** [necolas/react-native-web#2230]
**The problem**

Could you please add a notice that the version of you library above 0.17.2 does not support react-native 0.16.4.

**How to reproduce**

Steps to reproduce:
1. install react-native of the version 0.16.4
2. install react-native-web of the latest version or above 0.17.2
3. see deprecation warning

**Expected behavior**

Maybe add a notice to the documentation that the version 0.17.3 and above does not support old version of the react native 0.64.3 and below.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.3-0.17.6
* React Native (version): 0.64.3
* Browser: any

**Comment by necolas** [comment]
It's just a warning
