### ISSUE TITLE
NextJS without Babel produces this error - "Expected 'from', got 'typeof'"

### ISSUE THREAD

**Issue by dittmarconsulting** [necolas/react-native-web#2232]
**The problem**

I'm using RNW together with NextJS and Typescript. The app builds fine when I use Babel, which is obviously very slow. 

I would rather use the Next Compiler **SWC** but as soon I turn off Babel I get the following error

```
../../node_modules/react-native/index.js
Error: error: Expected 'from', got 'typeof'
  
   |
14 | import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
   |        ^^^^^^

Caused by:
    0: failed to process js file
    1: Syntax Error
```

**How to reproduce**
Here my simple dependencies
```json
"dependencies": {
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^9.0.0",
    "next": "12.1.0",
    "react-dom": "^17.0.2",
    "react-native-web": "^0.17.6",
    "react": "^17.0.2"
  },
  "devDependencies": {
    "@types/react": "^17.0.39",
    "babel-plugin-react-native-web": "^0.17.6",
    "typescript": "^4.5.5"
  }
```

**.babelrc**
```json
{
  "presets": ["next/babel", "@babel/preset-typescript"],
  "plugins": [
    ["react-native-web", { "commonjs": true }],
    [
      "module-resolver",
      {
        "root": ["./"],
        "extensions": [".tsx", ".ts", ".js", ".json"]
      }
    ]
  ]
}
```
pages/index.tsx
```js
import { View, Text } from 'react-native'

export default function App() {
  return (
    <View >
      <Text accessibilityRole="header">
        React Native for Web & Next.js
      </Text>
    </View>
  )
}
```

1. Run it with Babel - it works
2. Run without Babel - it shows the error above

**Expected behavior**

I expect that the app would run with the Next Compiler only.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.6
* React (version): 17.0.2
* Browser: Brave (Chrome)

**Comment by necolas** [comment]
Please read the setup docs about aliasing so you're not trying to build the react-native package on web https://necolas.github.io/react-native-web/docs/setup/

**Comment by dittmarconsulting** [comment]
I don't know why you closed this ticket @necolas 

`NextJS` has its own `webpack` file called `next.config.js` and I already HAVE defined the alias in there

```js
// @ts-check

/**
 * @type {import('next').NextConfig}
 **/

const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')(['@types/react-native'])

module.exports = withPlugins([withTM()], {
  webpack: (config) => {
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      'react-native': 'react-native-web',
    }
    config.resolve.extensions = ['.web.js', '.web.jsx', '.web.ts', '.web.tsx', ...config.resolve.extensions]
    return config
  }
})
```

As I mentioned it works WITH Babel (so the webpack setup works) but it doesn't compile without Babel. This was exactly the issue I reported but instead, you assumed I forgot to set up the project properly can closed the ticket 🤷‍♂️

**Comment by necolas** [comment]
Your error message only shows that the compiler is trying to consume the react-native package. You didn't include the next config. Either way, the issue is with your compiler consuming the wrong package, maybe from a dependency you didn't list

**Comment by dittmarconsulting** [comment]
Thank you for your reply @necolas 

I have a yarn workspace mono-repo and I define my top dependencies in the root.

As you can see at the error, it looks for the `react-native` package in the root

```
../../node_modules/react-native/index.js
```

Hence, I only have one `"react-native": "^0.66.3"` package installed.
