### ISSUE TITLE
VirtualizedList: incorrect direction when inverted and keyboard scrolling

### ISSUE THREAD

**Issue by staltz** [necolas/react-native-web#2233]
All the same symptoms as issue #995, except this time **keyboard** buttons such as :arrow_up: would scroll *down*, :arrow_down: would scroll *up*, as well as PageUp would scroll one page *down*, and PageDown would scroll one page *up*.

**Comment by necolas** [comment]
Yeah. The `scale:-1` inversion hack used by VirtualizedList just isn't the way to go

**Comment by necolas** [comment]
This PR by @azimgd removes the transform and fixes another issue: copy-paste text order https://github.com/necolas/react-native-web/pull/2151

**Comment by necolas** [comment]
@davidrieman is also working on fixing visualization https://github.com/necolas/react-native-web/discussions/2236.

Perhaps the 3 of you can work together to get VirtualizedList working for your needs? And if there are examples and unit tests to include in this repo that would also be a great help to limit regressions

**Comment by DavidRieman** [comment]
Ok I've added commentary to #2236.  I don't know if the scroll direction issues you are talking about are react-native-web only, or if they reproduce in react-native with a device with keyboard (like iPad with Magic Keyboard or a Samsung DeX device) - but if it's RNW-only issue it would be good to test out whether it continues to be a problem from my code.  I'll report back when things are committed and pushed, so you would be able to test that against `DavidRieman/react-native-web` main branch at that time.

**Comment by DavidRieman** [comment]
Ok the https://github.com/davidrieman/react-native-web/ `main` branch now has testable upgraded `VirtualizedList` including `SectionList` and `FlatList` too.

**Comment by staltz** [comment]
> if they reproduce in react-native with a device with keyboard (like iPad with Magic Keyboard or a Samsung DeX device or _whatever_ with a keyboard paired)

I tested on an iPad, and it seems like iOS doesn't support scrolling with the keyboard arrows.

**Comment by shrehatiwari** [comment]
May I solve this VirtualizedList issue stating incorrect direction when inverted and keyboard scrolling ?

**Comment by necolas** [comment]
Closing this as there's an issue in RN to move Animated, VirtualizedList, and FlatList to packages that get published to npm https://github.com/facebook/react-native/issues/35263.

This is the issue that is implicitly tracking problems with using transforms for inversion https://github.com/facebook/react-native/issues/30383
