### ISSUE TITLE
`numberOfLines={1}` does not work as expected when `<Text/>` contains `\n`s.

### ISSUE THREAD

**Issue by drtangible** [necolas/react-native-web#2243]
**The problem**

`numberOfLines={1}` does not work as expected when `<Text/>` contains `\n`s.

_____

**How to reproduce**

Simplified test case: https://codesandbox.io/s/magical-phoebe-xx2qmy?file=/src/App.js

Steps to reproduce:
1. Render `<Text numberOfLines={1} />` with text containing `\n`s.
2. Observe that text is not limited to 1 line:

<img width="423" alt="Screen Shot 2022-02-25 at 11 28 03 AM" src="https://user-images.githubusercontent.com/169912/155760158-7f15baa2-974b-462a-821b-7a0066a61003.png">

_____

**Expected behavior**

1. Render `<Text numberOfLines={1} />` with text containing `\n`s.
2. Observe that text *is* limited to 1 line:

<img width="324" alt="Screen Shot 2022-02-25 at 11 30 13 AM" src="https://user-images.githubusercontent.com/169912/155760445-f386f9bd-75db-4fd1-93b3-49addaa80a1c.png">

(https://snack.expo.dev/@drtangible/ashamed-croissant)

_____

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.6
* React (version): 17.0.*
* Browser: Chrome (98.0.4758.102), Safari (15.2), Firefox (97.0.1) all impacted on macOS Monterey.

**Comment by necolas** [comment]
Unfortunately fixing this is in conflict with fixing another issue https://github.com/necolas/react-native-web/pull/2058. Which makes me wonder if RN's text rendering needs to be revisited to better align with browsers

**Comment by necolas** [comment]
Here is a more complete set of test cases: https://codesandbox.io/s/bold-sea-nrd02d?file=/src/App.js

I'm tempted to say that the issue in #2058 is less important than this one, as using several truncated and adjacent text elements should be less common and sensical.

**Comment by drtangible** [comment]
@necolas -- interesting! 

> I'm tempted to say that the issue in https://github.com/necolas/react-native-web/pull/2058 is less important than this one, as using several truncated and adjacent text elements should be less common and sensical.

I'd tend to agree with that. In practice, I wonder if it would be more common for the `numberOfLines` prop to be applied to a parent `<Text/>` element (as shown in the two new test cases here: https://codesandbox.io/s/loving-brook-xul608?file=/src/App.js
