### ISSUE TITLE
ScrollView onMomentumScrollBegin does not work

### ISSUE THREAD

**Issue by wkeylin** [necolas/react-native-web#2247]
**The problem**
The `ScrollView` `onMomentumScrollBegin` prop does not work

**How to reproduce**
Simplified test case: https://codesandbox.io/s/white-sky-7ztkge

**Expected behavior**
`onMomentumScrollBegin` called correctly
**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.6
* React (version): 17.0.*
* Browser: Edge

**Comment by necolas** [comment]
Duplicate by #2249
