### ISSUE TITLE
Installing RNW kills RN runnings

### ISSUE THREAD

**Issue by sospedra** [necolas/react-native-web#225]
**What is the current behavior?**

Not even starting
![image](https://cloud.githubusercontent.com/assets/3116899/19356848/78f3fece-916f-11e6-9aab-02e722168790.png)

**Steps to reproduce**

1. `react-native init whatever`
2. `npm install react-native-web`
3. `react-native run-ios`
4. Cry

**Environment (include versions)**

OS: Sierra
Device: iOS 6 emu
React Native for Web (version): 0.0.46
React (version): 15.3.2

**Comment by necolas** [comment]
Hard to see how this could be happening when the 2 packages are independent

**Comment by sospedra** [comment]
Maybe is my machine? Did you try to repro?

**Comment by MoOx** [comment]
`react-native run-ios` is just not using react-native-web as RNW require an alias to be used like `from "react-native"`.
I am successfully using RN & RNW (RNW is aliased as RN  via webpack alias option)

**Comment by sospedra** [comment]
Therefore shall be my computer. I'll try tonight with another mac that I have. I'll report as soon as is done.

**Comment by necolas** [comment]
Ok thanks. I'll close for now.

**Comment by sospedra** [comment]
It works. I just restarted the computer and then works. I'll move the issue to RN just so they know about. Sorry for the false flag.
