### ISSUE TITLE
TouchableOpacity stops click events from propagating

### ISSUE THREAD

**Issue by marian-c** [necolas/react-native-web#2255]
**The problem**

`TouchableOpacity` prevents event propagation

**How to reproduce**

Simplified test case: https://codesandbox.io/s/great-rain-f39fdn?file=/src/App.js

Steps to reproduce:
1.  Have a parent component with an `onClick` handler
2. Have a child `TouchableOpacity` component inside the "parent" component
3. Click the element rendered by `TouchableOpacity` (click on "Does not propagate" text in the demo)

**Expected behavior**

Handler (`onClick`) of the parent component should run

**Environment (include versions). Did this work in previous versions?**

It did work in previous versions (I know of 0.11.7)

* React Native for Web (version): 0.17.1, 0.17.7 (could be others)
* React (version): 17.0.2
* Browser: Chrome

**Comment by marian-c** [comment]
Demo of inconsistent behaviour on expo snack
- web: value is incremented by 10
- ios: value is incremented by 110

https://snack.expo.dev/zB3qmenKM

**Comment by necolas** [comment]
The `onPress` being called on the parent looks like is a bug in React Native. You'll notice that on native none of the other press handler functions get called on the parent, and neither does the keyboard handler. `onPress` is not even a real "event" on native (it's inferred from the pressable state machine) so `stopPropagation` doesn't work on the object passed to `onPress` either.

**Comment by marian-c** [comment]
Hello necolas

Thank you for the reply,

Just because my example in snack uses 2 TouchableOpacities, let me clarify what I called inconsistent behaviour between native and web.

On web, TouchableOpacity prevents the `onTouchStart` and `onTouchEnd` from being triggered on the parent `View`.
This is not the case on native, where these callback are being triggered.

Just thought I'd clarify as I'm not familiar with the proper semantics of these events, also because you started with the `onPress` on the parent, which is less of an issue (and not happening anyway).

Please see a better example
https://snack.expo.dev/EdCHY5GSZ


side note: the example with 2 TouchableOpacities: on _native_, the inner one will prevent the `onPress` from triggering the `onPress` on the outer one, which incidentally is consistent with what happens on web, only that on web nothing escapes the touchable opacity while on native some bits propagate.

**Comment by necolas** [comment]
Oh, your example is very unclear. Better to log from callbacks. Looks to me like everything is behaving as expected and consistent between platforms.

> On web, TouchableOpacity prevents the onTouchStart and onTouchEnd from being triggered on the parent View.

This is not correct. You need to be using a touch device/emulator for those callbacks to fire on web.

**Comment by marian-c** [comment]
Thanks for clarifying

Indeed, the behaviour is not inconsistent as native does not have mouse events.

Touch events do escape the TouchableOpacity.

> click events will not propagate outside pressables/touchables on web.

Could you elaborate on the reasoning of this?

Personally, given this behaviour is not "specified" (n/a on native), I wouldn't have expected mouse events to be stopped from propagating.

Cheers
