### ISSUE TITLE
Adding horizontal margin to drawer navigation

### ISSUE THREAD

**Issue by aghasemi** [necolas/react-native-web#2256]
**The problem**
I am trying to get the expo example for drawer navigation (https://github.com/expo/examples/tree/master/with-drawer-navigation) working with RNW. The only change I made is adding a CSS styling to have horizontal margins on a desktop screen, similar to the Twitter timeline for example. However, the drawer itself "exceeds" the container and goes into the margin:

![a102dc04-7099-486b-8ab7-3d226a84031a](https://user-images.githubusercontent.com/7351535/158120641-ad067a3a-e860-49b7-8170-24e664efb7e7.jpeg)

Here is the part of the code I changed:

```
export default function App() {
  const style = {  flex: 1, padding: '20%', justifyContent:'center' };

  return (
    <View style={style}>
      <NavigationContainer style={{ paddingHorizontal: '20%' }}>
        <Drawer.Navigator initialRouteName="Home" >
          <Drawer.Screen name="Home" component={HomeScreen} />
          <Drawer.Screen name="Notifications" component={NotificationsScreen} />
        </Drawer.Navigator>
      </NavigationContainer>
    </View>
  );
}

```

Any idea how to solve this?

**Comment by aghasemi** [comment]
I opened an issue also on React navigation repo: https://github.com/react-navigation/react-navigation/issues/10428

I am not sure where the "fix" should come from.

**Comment by necolas** [comment]
I don't understand what the problem is, and there's no information here that surfaces that there might be an issue with RNW.  Feel free to open a new issue if you and the RN Navigation maintainers can identify the root cause as a bug in RNW
