### ISSUE TITLE
When open TextInput on IOS the keyboard not open but on android this part works nice

### ISSUE THREAD

**Issue by zoro1378** [necolas/react-native-web#2263]
When open TextInput on iOS the keyboard not open
but on android this part works nice

more definition : this problem only accrue on iOS devices changing browser has NO benefit for this problem ;
when want to focus on TextInput the keyboard NOT open , but on Android devices this problem is not seen yet  

Packages  :

"react-native-web": "~0.13.12"
"expo": "~41.0.1"
"react": "16.13.1",
"react-dom": "16.13.1",

thanks KFOX team

**Comment by necolas** [comment]
0.13 does not receive support patches. Please first upgrade to the latest version. **Bug reports must also include reduced test cases and complete the issue template as required**
