### ISSUE TITLE
Element created with unstable_createElement don't receive measurement methods

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#2265]
**The problem**

If I create a component by using `unstable_createElement`, `ref.current.measureLayout` will throw `ref.current.measureLayout is not a function`

**How to reproduce**

Simplified test case: [Link](https://codesandbox.io/s/pedantic-paper-xdx0sh?file=/src/App.js)

Steps to reproduce:
1. Create a ref
2. Add the ref to a component created with `unstable_createElement`
3. Try to access methods like measure or measureLayout

**Expected behavior**

Should call the callback provided to the method.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.6
* React (version): 17.0.2
* Browser: Firefox 98.0.2 (64 bits)

I need to locate some components relative to the parent canvas. The issue is that some components must be handled differently for web and native. I need to use a contentEditable div for web, and a TextInput for native.

Solving this would be just adding `usePlatformMethods` in unstable_createElement method.

**Comment by necolas** [comment]
Those methods are not available and createElement is not a component and so cannot contain hooks. Since you are creating different web/native implementations you can just use DOM APIs instead

**Comment by Sharcoux** [comment]
Why can't we just add custom tags on the View component to solve all the missing features in unstable_createElement?

Right now, I have to re-implement the View component by importing stuff from dist, like:

```js
import useElementLayout from 'react-native-web/dist/modules/useElementLayout'
import usePlatformMethods from 'react-native-web/dist/modules/usePlatformMethods'
```

This will probably break over time.

Why aren't those method publicly exported, at least?
