### ISSUE TITLE
rgb colors not working

### ISSUE THREAD

**Issue by johhansantana** [necolas/react-native-web#2267]
Just wanted to know if this is happening to others as it seems to not work with regular [react-native](https://github.com/facebook/react-native/issues/33536) as well.

https://codesandbox.io/s/musing-easley-34qlgi?file=/src/App.js

**Comment by jamesallain** [comment]
You're missing commas ``<Text style={{ color: "rgb(255 0 0)" }}>hey</Text>``

**Comment by necolas** [comment]
> react-native doesn't seem to work with this newer syntax though

And so it's a "wontfix" until it is fixed upstream in RN's color parser.

Next time, please follow the template in the issue instead of deleting it.
