### ISSUE TITLE
Pressable with accessibilityRole="link" doesn't respond to enter/space

### ISSUE THREAD

**Issue by askay** [necolas/react-native-web#2270]
**The problem**

When rendering a Pressable with accessibilityRole="link", the element will receive keyboard focus and respond to states produced by enter/space, but not call onPress. 

**How to reproduce**

Simplified test case:  https://codesandbox.io/s/priceless-dream-59g8vj?file=/src/App.js:687-958

Steps to reproduce:
0. Open console.
1. Set keyboard focus on "Press as a button". Press enter.
2. Press tab to "Press as a link". Press enter.

**Expected behavior**

Both turn red on Enter, but only "Press as a button" emits "pressed".

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17
* React (version): 17.*
* Browser: Safari/Chrome

This appears to have been true for the past five years across different code moves, but I haven't been able to find any documentation as to why. My understanding from reading [the code](https://github.com/necolas/react-native-web/blob/dc9ecfbc84c7e6cbf0c36c537ac1b0a86b7e43c1/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L312) is that if the role is `link` then it is a native element that would automatically support the keyboard behaviors; but in this case, it's rendered as a `div`. Seems like the fix here would be to exempt divs.

We use react-navigation to move between pages, which is why we don't use the href prop.

**Comment by necolas** [comment]
Add `href` for links: https://codesandbox.io/s/xenodochial-greider-5y8s7c

Links don't respond to spacebar interactions on web.

**Comment by askay** [comment]
Thank you for your help; I specified href and got the desired behavior
