### ISSUE TITLE
Property 'textContentType' does not exist on TextInput

### ISSUE THREAD

**Issue by hardikoyo** [necolas/react-native-web#2281]
**The problem**

Property 'textContentType' does not exist on TextInput

**How to reproduce**

Simplified test case: 

Steps to reproduce:
1.Create a TextInput with a textContentType prop.
2. send a message with correct format having otp (https://web.dev/sms-otp-form/#format)
3. keyBoard should look like this after receiving otp
![Screenshot 2022-04-28 at 3 43 30 PM](https://user-images.githubusercontent.com/88826246/166641635-3b9bd631-802f-4103-b7fc-1e1c2c244244.png)

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.15.0
* React (version): 16.9.0
* Browser: Safari

**Comment by necolas** [comment]
textContentType is the iOS-only equivalent of autoComplete, which is supported by Android and Web. But web requires a different value compared to Android for one time codes: https://web.dev/sms-otp-form/#:~:text=autocomplete%3D%22one%2Dtime%2Dcode%22%20%23&text=With%20autocomplete%3D%22one%2Dtime,for%20the%20user%20to%20enter.
