### ISSUE TITLE
Getting error while integrating ReactNative Web 

### ISSUE THREAD

**Issue by davinderkumar** [necolas/react-native-web#2287]
I am integrating ReactNativeWeb in an existing app. I am getting the following error 

[Error] TypeError: undefined is not an object (evaluating 'transition._updatedFibers')
	__webpack_require__ (bundle.web.js:44371)
	(anonymous function) (bundle.web.js:45441)
	Global Code (bundle.web.js:45443)
[Error] TypeError: undefined is not an object (evaluating 'ReactCurrentActQueue$1.isBatchingLegacy')
	batchedUpdates$1 (bundle.web.js:28933)
	batchedUpdates (bundle.web.js:6824)
	dispatchEventForPluginEventSystem (bundle.web.js:12120)
	dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (bundle.web.js:9298)
	dispatchEvent (bundle.web.js:9290:85)
	dispatchDiscreteEvent (bundle.web.js:9263)
	dispatchDiscreteEvent

Does anyone know how to resolve this?

**Comment by davinderkumar** [comment]
**The problem**

Adding RNW into an existing ReactNative app working fine on Android.
Installed following npm packages
react-native-web
react-dom

Add index.html, index.web.js, and webpack.config.js

**Simplified test case:**

npm run web

Following error showing in browser console

```
Error] TypeError: undefined is not an object (evaluating 'transition._updatedFibers')
webpack_require (bundle.web.js:44371)
(anonymous function) (bundle.web.js:45441)
Global Code (bundle.web.js:45443)
[Error] TypeError: undefined is not an object (evaluating 'ReactCurrentActQueue$1.isBatchingLegacy')
batchedUpdates$1 (bundle.web.js:28933)
batchedUpdates (bundle.web.js:6824)
dispatchEventForPluginEventSystem (bundle.web.js:12120)
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (bundle.web.js:9298)
dispatchEvent (bundle.web.js:9290:85)
dispatchDiscreteEvent (bundle.web.js:9263)
dispatchDiscreteEvent
```

**Expected behavior**

There should not be any error in console. 

Environment (include versions). Did this work in previous versions?

React Native for Web (version):  0.17.7
React (version): 16.11.0
Browser: Any

**Comment by necolas** [comment]
React 17 is the required version. No other actionable info. If that doesn't fix it, likely an issue with your setup

**Comment by gregogalante** [comment]
@davinderkumar How did you solve the error?
