### ISSUE TITLE
Ability to benchmark react-native-web vs react-native

### ISSUE THREAD

**Issue by LifeIsStrange** [necolas/react-native-web#2288]
Hi @necolas , I'm curious about how react-native-web and react-native performance compare in practice.
I'm seeing you have made online benchmarks here https://necolas.github.io/react-native-web/benchmarks/ The only missing piece is to build a equivalent react native app. The result would be compared with the react-native web score on the phone's google chrome.
A bonus would be to benchmark a Ionic react app clone to a ionic react-native-web clone.

**Comment by necolas** [comment]
I don't care about performance relative to RN, only relative to other React web experiences built with CSS modules

**Comment by LifeIsStrange** [comment]
Well you could be surprised to observe e.g. that Ionic react apps are faster than their react native equivalent, and would consume less energy. That kind of information would make the whole point of react native moot and it's actually, likely to be true.
