### ISSUE TITLE
TextInput: clearing input programmatically does not show placeholder again

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#229]
If you call `clear()` or `setState({value: ''})` along with `<TextInput value={this.state.value} />` the placeholder never returns. You can try blurring it or focusing it programmatically, but the placeholder doesn't return _unless_ you manually backspace the last character in the field. 

You should be able to clear a field by one of the above 2 _programatic_ techniques and see the placeholder again, which is what you would do if successfully submitting a form without taking the user to a thankyou page (i.e. if the form still is visible to the user, but cleared).

**Comment by RangerMauve** [comment]
Is this on all browsers?

**Comment by necolas** [comment]
Please can you include reduced test cases and the other info asked for in the issue template

**Comment by faceyspacey** [comment]
@necolas here's the thing, I have a lot more issues I haven't reported simply because of the amount of time fully completing the issue template would take. My point of view is this: RNW does have lots of issues (a lot of inconsistencies compared to RN), yet this repository isn't so overloaded with issues that such lengthy issue template is required imho; it's preventing RNW from progressing. I'm sure I'm not the only one that just said f it and didn't supply an issue, as I've done like 10 times now cuz I knew I didn't have the time to do it. If the package had thousands of issues, it would be a different story, but it doesn't and hardly anyone is reporting anything. What I've experienced is that newer less used packages don't have as strict of an issue template, and that's basically where RNW is at. I'm surprised at how few issues it's receiving, and ultimately how few people are using it. I think more people *will* use it once it comes closer to paralleling RN in # of components, and if various inconsistencies with with RN proper didn't exist. 

Now that said, **RNW is so good**, I don't see any point in building React apps without it, since obviously we are all also building RN apps. I want to be the one to contribute many of these fixes, as I did yesterday. I just don't have the friggin time, as of course is the case with you guys and everyone. I'm the sole developer at my startup (pre-launch behind deadline by far), and when we hire more developers I plan to create a whole unit assigned to resolving inconsistencies between RNW and RN; my whole company is based on the RN component API. ...As I said above, RNW is motherfuckin awesome. Amazing job! It perhaps is a bigger game changer than RN--it brings everything full circle. I think a lot of developers are reserved about using it--maybe because they just can't believe this API would work as well on web as it does natively, and, again, because of the missing components. The latter probably is the biggest thing that could increase adoption--a complete or far-nearer complete component library that parallels RN. At which point, a lot of the inconsistencies will likely be fixed by the community because so many people will be using. The thing is this: your codebase is very understandable and the fixes are each very few lines of code to make, but there's so many of them. There's just a lot of them, a lot more than are being reported here. ANOTHER EXAMPLE OFF THE CUFF: Touchable doesn't position itself the same as on native where the children 100% of the time dictate it's positioning; in RNW, you often have to apply styles to the Touchable button, i.e. with fixed and absolute positioning. Touchable is `position: relative` therefore you can't absolutely or fix position the children inside it like you could on native. 

So bottom line my reality is this and the decision is yours: do you want me to report everything even if I can't provide a complete issue template every time or keep it to myself? Is there another venue for off the cuff bugs. I'm do all i can over here man for my own project, while trying to help this project out. I know reporting an issue is small compared to the work you have done, but on my side here's the reality: i find another fix/hack for the problem and move on; so just reporting it and providing detailed information as I did yesterday is additional time I basically don't have. I'm happy to keep a public google spreadsheet and write things in there and give you access to the sheet, and when I get around to it I'll escalate individual issues to fully completed issue template and github issue. Let me know how I can help.

**Comment by faceyspacey** [comment]
@RangerMauve haven't tested outside of Chrome yet. I'm doing my app all in Chrome and then moving to Firefox, etc. That said, I have checked my app from time to time in FF, and the situation is not good.

**Comment by necolas** [comment]
> I have a lot more issues I haven't reported simply because of the amount of time fully completing the issue template would take

The template is minimal: what's the issue (+test case), what did you expect, what was the environment. It would have been faster to fill it in than write that lengthy reply!

What takes a lot of time is me or someone else having to produce a test case (many issues can't be reproduced in isolation), guess which browsers and versions are effected, and then write a patch.

**Comment by faceyspacey** [comment]
I know it takes a lot of time, but I assume you rather be aware than not. Like I said, I can maintain a sheet with minor issues to help your package for the times I can't do a proper issue--I'm using RNW full time and have been for 2 months. 

Is there a live-codeable version of the storybook examples where we can generate a new link with every revision:

https://necolas.github.io/react-native-web/storybook/?selectedKind=component%3A%20TextInput&selectedStory=tbd&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel&

If we can get that, I can streamline this for you.

**Comment by faceyspacey** [comment]
here's the example with `setState({value: ''}`

http://codepen.io/necolas/pen/PZzwBR

**Comment by faceyspacey** [comment]
here's the `clear()` case:

http://codepen.io/anon/pen/ORANOY

the TextInput is properly used as "unmanaged," i.e. the value isn't set via `this.state.value`, and `clear()` does clear the field, but again, the placeholder does not appear. 

Both codepens are tested in both Firefox and Chrome.

**Comment by faceyspacey** [comment]
this should handle it: 

https://github.com/necolas/react-native-web/pull/231
