### ISSUE TITLE
Could not load react-native-web/Libraries/Utilities/codegenNativeComponent

### ISSUE THREAD

**Issue by belaziv** [necolas/react-native-web#2292]
**The problem**
I have a react native application that i'm trying to use on web as well
When I'm trying to build I get the following error:
```
Could not load react-native-web/Libraries/Utilities/codegenNativeComponent (imported by node_modules/react-native-safe-area-context/lib/module/specs/NativeSafeAreaView.js): ENOENT: no such file or directory, open 'react-native-web/Libraries/Utilities/codegenNativeComponent
error during build:
ENOENT: no such file or directory, open 'react-native-web/Libraries/Utilities/codegenNativeComponent'
```
The correct file path is:
`react-native/Libraries/Utilities/codegenNativeComponent.js`
It seems that the error comes from `react-native-safe-area-context`
And it occurs because of `react-native-web` alias in my `vite.config.ts`:
```
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      'react-native': 'react-native-web'
    }
  }
})
```
What does it mean?
Is `react-native-web/Libraries/Utilities/codegenNativeComponent` really missing in the implementation of `react-native-web` ?

**How to reproduce**
https://stackblitz.com/edit/vitejs-vite-betvra

Simplified test case: 

Steps to reproduce:
1. go to the link above (How to reproduce section)
2. run `npm i`
3. run `npm run build`

**Expected behavior**
The web app will work fine with the native components

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.7
* React (version): 17.0.2
* Browser: chrome

**Comment by necolas** [comment]
Your bundler should be using the web implementation of react-native-safe-area-context instead of the native export. If you continue to have trouble loading the web implementation you should open an issue against their repository

**Comment by zico4reel** [comment]
Hi @necolas , so the issue I'm having with vite, is more of the Utilities/Platform, on webpack or CRA this issue is quite easy to resolve, but webpack is just too messy or too big.

I've been able to solve the issue on this thread, but for some reason I'm having issue with aliasing for Utilities/Platform

**Comment by codelocksdev** [comment]
@mmomtchev thank you for that! It worked for me.

**Comment by carlgieringer** [comment]
> Your bundler should be using the web implementation of react-native-safe-area-context instead of the native export. If you continue to have trouble loading the web implementation you should open an issue against their repository

I got this to work using `esbuild` by following [this comment](https://github.com/th3rdwave/react-native-safe-area-context/issues/202#issuecomment-1204474830) and prioritizing `.web.x` extensions in my config:

```
  resolveExtensions: [
    ".web.tsx",
    ".tsx",
    ".web.ts",
    ".ts",
    ".web.jsx",
    ".jsx",
    ".web.js",
    ".js",
    ".css",
    ".json",
  ],
```

**Comment by jeremyfrancis** [comment]
Personally, I removed react-native-web in the latest RN Expo setup with no issues.  And then in my app.config.ts I had to remove where it says "bundler": "metro"

And I also had to install everything webpack related and setup the webpack config.  It is odd to me how webpack and metro are used together still, but whatever it works now.

**Comment by Tech3Imperio** [comment]
> Your bundler should be using the web implementation of react-native-safe-area-context instead of the native export. If you continue to have trouble loading the web implementation you should open an issue against their repository

Where can I find the web implementation of react-native-safe-area-context, I am not able to find it or solve this issue either by using a mock for the codegenNativeComponent or by using @react-navigation/stack instead of @react-navigation/native-stack

The only way I was able to solve this issue is by installing expo-dev-tools as a developer dependency and adding the below line of code in my vite.config.js's alias, 

    alias: {
      'react-native': 'react-native-web',
      'react-native-safe-area-context': 'expo-dev-menu/vendored/react-native-safe-area-context/src'
    },

I am looking for a way to avoid using expo and create a cross-platform application with react-native-web support but this error is not being solved by me.

**Comment by dennyzain** [comment]
> [@necolas](https://github.com/necolas) I have a draft story on medium with my experience with bundling react-native for the web with webpack, feel free to comment on it as I went through all the problems that are posted in an issue here every few days:
> 
> https://medium.com/@mmomtchev/bundling-react-native-for-the-web-with-webpack-and-typescript-ba42db25584

thank you for that

**Comment by mmomtchev** [comment]
> have you tried using react-native-web with a vite application? I've followed your article (which is great by the way) but still no luck

I am not a vite power user, but I think that mostly everything should apply to vite too. As long as you can follow the trace of the failing dependency, you should be able to find a way to replace it.
