### ISSUE TITLE
Project use third node library react-native-code-push,run on browser promot error.

### ISSUE THREAD

**Issue by Leaf-WXC** [necolas/react-native-web#2293]
The problem
Project use third node library react-native-code-push,when run it  on browser ，Console promot error "Uncaught TypeError: Cannot read properties of undefined (reading 'Alert')" 

How to reproduce
Project package.json config script  with : "web": "webpack serve --mode=development --config webpack.config.js"
then I start run project with command 'npm run web',and it build successfully. Then I use the url 'http://localhost:8080/' on Chrome browser,the browser page was blank,and open dev tools,the Console promot : 'Uncaught TypeError: Cannot read properties of undefined (reading 'Alert')'  (P.S  'Alert' is difnied in AlertAdapter.js in react-native-code-push library)

Expected behavior
project can show the correct page in browser,but now I think its the packaged bundlejs  which cant be resolved by browser lead to this problem.I want to know the reason why it happend?  React-native-web didnt support RN project which used such as   react-native-code-push third library  to resolve and display on browser?

Environment (include versions). 
React Native for Web (version): ^0.17.7
React (version): 17.0.2
Browser: chrome

**Comment by necolas** [comment]
react-native-code-push can't be used on web https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

**Comment by Leaf-WXC** [comment]
> react-native-code-push can't be used on web https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

I got it .Thanks for your reply~
