### ISSUE TITLE
Error After New Project Creation - Duplicate Box Import

### ISSUE THREAD

**Issue by kunle-e** [necolas/react-native-web#2305]
**The problem**
Two Box components are being imported in App.tsx: 
``import {
  Box,
  Image,
  Text,
  Link,
  HStack,
  Heading,
  Switch,
  useColorMode,
  VStack,
  Box,
} from "native-base";``

Which causes the error below:

ERROR in src/App.tsx:12:3
TS2300: Duplicate identifier 'Box'.
    10 |   useColorMode,
    11 |   VStack,
  > 12 |   Box,
       |   ^^^
    13 | } from "native-base";
    14 |
    15 | function App() {

**How to reproduce**
- Copy installation instructions for Install in Create React App project from: https://docs.nativebase.io/install-cra
``yarn dlx  create-react-app my-app --template @native-base/typescript``

**Expected behavior**
No duplicate Box Identifier

**Environment  (never tested in previous versions)**
Node: v16.10.0

Dependencies installed:
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.2",
    "@types/node": "^16.10.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-native": "^0.65.5",
    "native-base": "3.4.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-svg": "^12.1.1",
    "react-native-web": "^0.17.5",
    "react-scripts": "5.0.1",
    "typescript": "^4.1.2",
    "web-vitals": "^2.1.1"
  },

**Comment by necolas** [comment]
This is not the native-base repo
