### ISSUE TITLE
Trying to install react-native libraries will fail on peer dependencies react@17.0.2

### ISSUE THREAD

**Issue by oliviercperrier** [necolas/react-native-web#2306]
**The problem**

React would need to be updated to react@18.2.0

**How to reproduce**

Steps to reproduce:
1. Create a react-native-web project with a base project react 18.2.0
2. Try installing a lib such as `npm i react-native-scroll-bottom-sheet`
3. See the error

````
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.68.2
````

**Expected behavior**
Should be able to install the library, but get an error because react is not up to date in react-native-web

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.18.0
* React (version): 18.2.0

**Comment by necolas** [comment]
Either use React 17 or npm install with `--legacy-peer-deps`

**Comment by oliviercperrier** [comment]
> Either use React 17 or npm install with `--legacy-peer-deps`

Why not upgrade to react 18?
