### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by chkmls** [necolas/react-native-web#2307]
**The problem**
I cant install it on react native project.
creating new react native project with `npx react-native init myapp`
and then `npm install react-dom react-native-web` raise errors of conflicts.
**The error**
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: appp5@0.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^18.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
running with force i manged to install but the web app wont run, and any ther npm install raise above error.

**How to reproduce**
My os :windows 10
nodejs: lts
 `npx react-native init myapp`
`npm install react-dom react-native-web`

There's a way to install it?
Thanks and sorry for my English.

**Comment by taZik616** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/94304770/175286844-74c539a2-0bdd-4688-9ebe-78f7a811fd8f.png">

**Comment by chkmls** [comment]
I tried that but than i got many errors when installing other modules like navigation.
Maybe there is a tutorial or ready to use template? I very much like to use it

**Comment by necolas** [comment]
You can't use React 18 with RNW 0.18 or RN 0.68

**Comment by rdinizz** [comment]
@necolas what is the newest RN version supported?
