### ISSUE TITLE
CSS missing in SSR

### ISSUE THREAD

**Issue by code-artisan** [necolas/react-native-web#2320]
**The problem**
CSS is missing in SSR when first visit. But after that, the styles is normally.

**How to reproduce**
https://codesandbox.io/s/upbeat-grothendieck-ojcns0

Fork this repo and restart server.

Simplified test case: 

**Expected behavior**
No styles missing. include first visit.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.18
* React (version): 17.0.0
* Browser: any

**Comment by necolas** [comment]
As @yuxizhe said. This is mentioned in the documentation: https://necolas.github.io/react-native-web/docs/rendering/#server-api

**Comment by code-artisan** [comment]
Oops... It is my fault and it is works.  Thanks.
