### ISSUE TITLE
`dataSet` is giving a type error

### ISSUE THREAD

**Issue by jnrepo** [necolas/react-native-web#2322]
**The problem**
Trying to use `dataSet` to pass in custom data props. ie. `dataSet={{ test: '123' }}`. Doing so returns an error
```Property 'dataSet' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TouchableOpacity> & Readonly<TouchableOpacityProps> & Readonly<...>'.```

**How to reproduce**
Simplified test case: https://codesandbox.io/s/dataset-type-error-f5yzef?file=/src/App.tsx

Steps to reproduce:
1. Add `dataSet` to a `react-native` component. ie. TouchableOpacity, View, etc.

**Expected behavior**
No type error. According to release [changes](https://github.com/necolas/react-native-web/releases/tag/0.13.0) this is how we should be passing in custom `data-` props.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.17.5
* React (version): 17.0.2
* Browser: Chrome
* Did this work in previous versions? not sure

**Comment by necolas** [comment]
I don't maintain the TypeScript types for this library.

https://github.com/necolas/react-native-web/issues/832
