### ISSUE TITLE
Image: in production, only resizeMode always falls through to `cover`

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#233]
**What is the current behavior?**

If you set `resizeMode: contain` in production, `cover` is always what you get. 

```
const styles = StyleSheet.create({
  imageStyle: {
    resizeMode: 'contain',
  },
})
```
***output:*** `<div class=" __style_df" role="img" style="background-size: cover">...`

**What is the expected behaviour?**

a div with `background-size: contain`

**Steps to reproduce**

Build your app with webpack, setting NODE_ENV to production: `NODE_ENV=production webpack -p --config web/webpack.config.js`

visit your site. Can't easily put into a codepen or I would. 

The issue is obviously in this area:

https://github.com/necolas/react-native-web/blob/master/src/components/Image/index.js#L97

However, I stepped through the production code. I'm talkin stuff that looks like this: https://www.dropbox.com/s/s3b54f83h2u9gui/Screenshot%202016-10-21%2001.56.45.png?dl=0

and it produced the correct results. At first I thought it was because `StyleSheet.flatten()` couldn't ultimately reproduce the original styles out of numbered styles. But it did. That wasn't it. Next, the line where you check if we're in production, that didn't seem to be it either. So it must be happening somewhere prior, and conditionally, not for all times you use a resizeMode other than cover--because at least when I stepped through the code, I actually saw `resizeMode: contain` come out. That boggled my mind--because when I inspected 10 contained images in the Elements tab, they all were incorrectly set to `cover`. 

here's my exact code:

```
import React, { Component } from 'react';
import {
  StyleSheet,
  View,
  Image,
} from 'react-native';

export default function Footer() {
  return (
    <View style={styles.container}>
       <Image source={require('../../images/logo.png')} style={styles.logo} />
       <Text>&copy;{(new Date).getUTCFullYear()}. All Rights Reserved.</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  logo: {
    width: 200,
    height: 40,
    resizeMode: 'contain',
    marginTop: 8,
    marginBottom: 20,
    marginLeft: 25,
  },
});
```

**Environment**
OS: X
Device: Macbook
Browser: Chrome
React Native for Web (version): 0.0.45
React (version): 15.3.2

**Comment by faceyspacey** [comment]
explicitly providing the component property `<Image resizeMode='contain` />` works as I suspected/hoped. But not as a style property.

**Comment by necolas** [comment]
Thanks, good spot. The issue was that this code could mutate the source `style`.

```js
let style = StyleSheet.flatten(this.props.style);
style = process.env.NODE_ENV !== 'production' ? { ...style } : style;
delete style.resizeMode;
```

In the fix I flatten the new style before passing it to the view.
