### ISSUE TITLE
ListView issue with many items

### ISSUE THREAD

**Issue by mkdotcom** [necolas/react-native-web#234]
Hello
It seems there is an issue when a ListView has a lot of items.
I attach a sample code file showing the issue 
(change "count=10" to "count=100" to see the differences)

[TestListViewWeb.zip](https://github.com/necolas/react-native-web/files/544572/TestListViewWeb.zip)

If there is enough items in the listview, it overlaps completely the top view
The same code works fine on android/ios/windows

**Comment by mkdotcom** [comment]
if there is enough items in the listview, it overlaps completely the top view

**Comment by necolas** [comment]
Moving all ListView issues to #260

**Comment by mkdotcom** [comment]
the issue is still here (parent layout issue when the listview is big)
