### ISSUE TITLE
FlatList act differently in RNW than RN

### ISSUE THREAD

**Issue by yuxizhe** [necolas/react-native-web#2340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

FlatList act differently in RNW than RN. 
In RN, FlatList have a height by default which fit the screen view,  so it can scroll and all methods workout fine. 
But in RNW, FlatList 's height by default is the height of the children list , not fit the screen view, so it cannot scroll and many methods broken. For example the onEndReached method fires infinitely. 

Expo demo:  https://snack.expo.dev/@yuxz/flatlist-h5 
web (with RNW 0.18.6): https://codesandbox.io/s/flat-list-h5-hnk1el?file=/src/App.js

We have to manually set FlatList height or FlatList`s parent height.  for example: height: '100vh'. 
eg: https://codesandbox.io/s/flat-list-h5-forked-tde962?file=/src/App.js

### Expected behavior

FlatList should have a default height to fit the view.

### Steps to reproduce

https://codesandbox.io/s/flat-list-h5-hnk1el?file=/src/App.js

FlatList cannot scroll and the onEndReached method fires infinitely

### Test case

https://codesandbox.io/s/flat-list-h5-hnk1el?file=/src/App.js

**Comment by yuxizhe** [comment]
> You have to set `flex:1` on the root view to have it fill the screen https://codesandbox.io/s/flat-list-h5-forked-hj7hbo

Yes, not only the root view,  we have to set `flex:1` on every parent view to make it work in RNW. which is very inconvenient, and its different with RN.  We dont need to set those in RN. What about make it behave the same as RN?

https://codesandbox.io/s/flat-list-h5-forked-lti8qj?file=/src/App.js

<img width="800" alt="image" src="https://user-images.githubusercontent.com/14990734/178411489-ae2ab23b-291f-4106-b1bc-8d914119bdbf.png">

We dont need to set those in RN: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/14990734/178411631-8a8bca26-f37b-48dd-82f8-23ef3e8ad5f0.PNG">

**Comment by necolas** [comment]
That's how CSS flexbox works. Whatever React Native is doing is non-standard.
