### ISSUE TITLE
TextInput: padding is applied to wrapper View, not input

### ISSUE THREAD

**Issue by TannerAtVenu** [necolas/react-native-web#235]
**What is the current behaviour?**
When you specify padding in the style of a TextInput, the padding is placed on the parent View element and not the TextInput itself.

Link to minimal test case: https://codepen.io/anon/pen/mAaXXQ

**What is the expected behaviour?**
Padding should be placed on the TextInput itself, instead of the parent element.

This issue seems to have been fixed here: https://github.com/necolas/react-native-web/issues/48, but it doesn't currently work with the newest version of react-native-web.

**Comment by necolas** [comment]
What are the problematic consequences of the current behaviour?

**Comment by TannerAtVenu** [comment]
Hi Necolas,

The problem lies in trying to style the focused field or trying to add a border to the field especially with autofill fields where browsers also tend to add their own styling.

This is a crude example but this is the result you get when you add a red border and some padding to an autofill field that utilizes Chrome UI styling:

<img width="259" alt="screen shot 2016-11-21 at 11 10 28 am" src="https://cloud.githubusercontent.com/assets/12898162/20494740/98248ba8-afdb-11e6-9c2a-0678c4877386.png">

The padding should be on the text field itself so that the yellow background color gets a full-bleed effect and reaches the edges of the red border.
