### ISSUE TITLE
I18nManager.isRTL returns undefined instead of boolean?

### ISSUE THREAD

**Issue by SrBrahma** [necolas/react-native-web#2350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Looks like that console.log(I18nManager.isRTL) on web logs `undefined`.

"react-native-web": "0.17.1"

### Expected behavior

It should be a boolean, and should reflect the `I18nManager.forceRTL(bool)` value.

### Steps to reproduce

Just `console.log(I18nManager.isRTL)` on web. It will log `undefined`.

Even if you change the RTL with `I18nManager.forceRTL`, it will still print `undefined`.

https://snack.expo.dev/@srbrahma/32420e

### Test case

https://snack.expo.dev/@srbrahma/32420e

**Comment by SrBrahma** [comment]
I just found that in rn-web .18 there is a new API to get the RTL value. But, for .17 I would like to know if it's possible to get it.

**Comment by necolas** [comment]
See the 0.15 release notes about this API

**Comment by SrBrahma** [comment]
Many thanks for the quick reply!
