### ISSUE TITLE
Is there a way to disable modal's focus trap?

### ISSUE THREAD

**Issue by Natumsol** [necolas/react-native-web#2351]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

```
version: react-native-web@0.15.7
```

When displayed, Modal automatically focuses on the content area, which may be disruptive to some business scenarios. Is it possible to disable this default behaviour by adding a configuration property?

**Comment by necolas** [comment]
> react-native-web@0.15.7

This version is no longer maintained.

> Modal automatically focuses on the content area

This is a standard accessibility practice.

> which may be disruptive to some business scenarios

Such as?

**Comment by necolas** [comment]
Closing due to lack of follow up
