### ISSUE TITLE
CheckBox does not apply readonly when using accessibilityReadOnly

### ISSUE THREAD

**Issue by paularmstrong** [necolas/react-native-web#2359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

`aria-readonly` / `readonly` attributes for checkboxes

### Expected behavior

using `<CheckBox accessibilityReadOnly />` should apply `readonly` attribute to the output `<input type="Checkbox" reaonly />` when using `, but it currently does not.

### Steps to reproduce

`<CheckBox accessibilityReadOnly />` 

See test case

### Test case

https://codesandbox.io/s/icy-fire-fr2ct4

### Additional comments

I'm uncertain if there are other accessible props that are also not translating through and/or if this is only related to `CheckBox`. It does appear to work correctly on `TextInput`, as shown in the test case link.

There may also be needs to have the colors either the same as a `disabled` checkbox, or muted in some other way.
<img width="210" alt="Screen Shot 2022-08-09 at 10 02 03" src="https://user-images.githubusercontent.com/33297/183712800-d9302591-5ff3-42d8-b801-351b60fe9797.png">

**Comment by devalpi** [comment]
There is no property to make the checkbox readonly. 
When I look at the test case, an aria read-only parent div appears as it should.

I opened a pull request the other day, but it doesn't seem to be a problem right now.

**Comment by necolas** [comment]
@paularmstrong see https://github.com/necolas/react-native-web/pull/2375. For different styling, that is something you can define in your component when setting the readonly prop. The native checkbox doesn't provide any different visual treatment for readonly states either.
