### ISSUE TITLE
require document or information to replace deleted files in version 0.18  

### ISSUE THREAD

**Issue by Viraj-10** [necolas/react-native-web#2363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We were internally using `createCompileableStyle`, `i18nStyle`, `atomic`, `styleResolver` from RNW but in version `0.18` This functions/files were depreciated. Do these functions still exist somewhere or renamed into something else?

Exact file paths before react-native-web@0.18

- react-native-web/dist/exports/StyleSheet/createCompileableStyle
- react-native-web/dist/exports/StyleSheet/i18nStyle
- react-native-web/dist/exports/StyleSheet/compile
- react-native-web/dist/exports/StyleSheet/styleResolver

### Expected behavior

None

### Steps to reproduce

None

### Test case

none

### Additional comments

Can see our implementation [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/utils/useResponsiveQuery/useResponsiveQuery.web.ts)

_No response_

**Comment by necolas** [comment]
Deprecated? These files were private internals of the library that you shouldn't be using. You can look at the source code to see how the StyleSheet is now implemented, but reaching into internals is not reliable or recommended. Eventually packages will use node package exports to prevent this altogether

**Comment by necolas** [comment]
Also worth mentioning that the canary for 0.18 was published months before release, with explicit mention of the StyleSheet rewrite. If your library depends on RNW and used StyleSheet internals, you should have been aware of this months ago and tried integrating the canary

**Comment by Viraj-10** [comment]
Hi @necolas, Thanks for the quick reply. We will see how we can use the current StyleSheet in our repo without using internal files.
