### ISSUE TITLE
Transitions not working on TouchableOpacity before a click

### ISSUE THREAD

**Issue by Minivera** [necolas/react-native-web#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When using the `TouchableOpacity` element, if we try to use `transitionDuration` or any other transition properties, the transition will not animate due to the component hardcoding the duration to 0s. This is then fixed by clicking on the element. This means that adding a transition on hover, for example, won't work until the user clicks on the element first.

This seems to be caused by this state default value here, which is set to 0s: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TouchableOpacity/index.js#L55. This is then added to the root div element, https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TouchableOpacity/index.js#L136, after the base style sets it to 0.15s, https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TouchableOpacity/index.js#L145. This makes me think this might be an intentional mistake and a bug.

### Expected behavior

Either the `transitionDuration` property should be overridable on `TouchableOpacity`, or the transitions work without needing to click on the element first (I can reproduce a fix locally by changing the default value to `0.15s`).

### Steps to reproduce

1. Create a `TouchableOpacity` component like this:

```typescript
<TouchableOpacity style={[{ transitionDuration: '1s' }]}>
 Hi
</TouchableOpacity
```

2. Notice the transition duration on the created element is still `0s`.

### Test case

https://codesandbox.io/s/dawn-microservice-p9herz?file=/src/App.js

**Comment by necolas** [comment]
Use Pressable. The touchables should be considered deprecated in RN

**Comment by rahulsurve000** [comment]
May I solve the transition issue?

**Comment by necolas** [comment]
Closing this as the Touchables are deprecated in 0.19 and will be removed in 0.20
