### ISSUE TITLE
[webpack-cli] Error: @expo/webpack-config requires a valid `mode` string which should be one of: development, production, none

### ISSUE THREAD

**Issue by alexkendall** [necolas/react-native-web#2367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

[webpack-cli] Error: @expo/webpack-config requires a valid `mode` string which should be one of: development, production, none
    at validateEnvironment 

### Expected behavior

App should produce website build output.

### Steps to reproduce

./node_modules/.bin/webpack-dev-server --config ./webpack.config.js --hot --mode development

### Test case

https://stackoverflow.com/questions/49242756/how-to-set-mode-to-development-or-production-in-the-config-file

### Additional comments

webpack.config.json looks like the following:

```
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Customize the config before returning it.
  config.resolve = {
    ...config.resolve,
    alias: {
      "react-native": "react-native-web",
      "react-native-maps": "react-native-web-maps",
    },
    extensions: [".web.ts", ".web.tsx", ".web.js", ".js", ".ts", ".tsx"],
  };
  return config;
};

```

**Comment by necolas** [comment]
Add a `mode` then? Don't see how this has anything to do with this library

**Comment by alexkendall** [comment]
Even with a mode hardcoded into the config file. Same error.
Multiplatform setup with webpack is stated here: https://necolas.github.io/react-native-web/docs/multi-platform/
By the way, even with the webpack configuration from the website here generates an error.
