### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scales' of undefined? The above error occurred in the <Image> component:?

### ISSUE THREAD

**Issue by camnpr** [necolas/react-native-web#2370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

use `react-native-web` version is 0.17.7, it is worked.

but now use version is 0.18.7, it is not worked.

### Env
web

### Error
> Uncaught TypeError: Cannot read property 'scales' of undefined

    MyApp\node_modules\react-native-web\dist\exports\Image\index.js:126
    at resolveAssetUri (MyApp\node_modules\react-native-web\dist\exports\Image\index.js:126)
    at MyApp\node_modules\react-native-web\dist\exports\Image\index.js:178

>The above error occurred in the <Image> component:

    at Image (http://localhost:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false:52020:36)
    at div
    at View (http://localhost:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false:40813:27)
    at Pressable (http://localhost:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false:68173:26)
    ...
    at div
    at View (http://localhost:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false:40813:27)
    at DevAppContainer (http://localhost:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false:44817:36)
    at div
    at View (http://localhost:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false:40813:27)
    at AppContainer (http://localhost:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=web&dev=true&hot=false:37523:26)

### Guess
`Image` component on react.

### Expected behavior

I hope give detail error.

### Steps to reproduce

```jsx
<Stack.Navigator initialRouteName="CustomBottomTabNav" screenOptions={{
        headerStyle: {
          backgroundColor: "#f70f0f",
        },
        headerTintColor: "#fff",
        // https://reactnavigation.org/docs/native-stack-navigator/#headerbacktitlevisible
        headerBackTitleVisible: false,
        headerBackImage: () => {
          return <Image
            style={{width: 21, height: 21, marginLeft: Platform.OS === "ios" ? 10 : 0}}
            source={require("./assets/nav-back.png")}
          />
        },
      }} />
```

- run `npx expo start`
- w

### Test case

https://snack.expo.dev/@camnpr/b5dcfc

**Comment by necolas** [comment]
Please add a reduced test case on codesandbox as asked for. I'm not debugging expo or react-navigation

**Comment by camnpr** [comment]
Hi there, I found the problem.

during my code this use:
```js
() => {
    return <Image
        style={{width: 21, height: 21, marginLeft: Platform.OS === "ios" ? 10 : 0}}
        source={require("./assets/nav-back.png")}
    />
}
```

Output Source:
```json
{
    "source": 11,
    "style": {
        "height": 21,
        "marginLeft": 0,
        "width": 21
    }
}
```

I debug to this [code line](https://github.com/necolas/react-native-web/blob/3fc40bdf810901146b8a240a2d0399dee708cfff/packages/react-native-web/src/exports/Image/index.js#L115) is null.

so this line[`let scale = asset.scales[0];`](https://github.com/necolas/react-native-web/blob/3fc40bdf810901146b8a240a2d0399dee708cfff/packages/react-native-web/src/exports/Image/index.js#L116) is report errors.

I suggest give detail error when `var asset = getAssetByID(source)` is null.

That's about it:

```js
function resolveAssetUri(source): ?string {
  let uri = null;
  if (typeof source === 'number') {
    // get the URI from the packager
    const asset = getAssetByID(source);
    /**
     * when use ..() => { return <Image source={require('..')} /> }..
     * happend error: 
     *    Uncaught TypeError: Cannot read property 'scales' of undefined..
     *    The above error occurred in the <Image> component:..
     */
    if (!asset) {
      // give detail error when asset is null.
      throw new Error(
        `source uri is not supported or miss, please check image source. 
        recommend declare before use.
        eg: const icon1 = require('./xx.jpg') or import icon1 from './xx.jpg'`,
      );
    }
    let scale = asset.scales[0];
...
```

**Comment by necolas** [comment]
Maybe the expo packager is not registering the asset?

**Comment by camnpr** [comment]
I think this. 
because of expo 45 is OK, during to version 46, a lot of not able run.
I still to solve question other.
