### ISSUE TITLE
[0.18] accessibilityState and accessibilityValue deprecation?

### ISSUE THREAD

**Issue by marklawlor** [necolas/react-native-web#2373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

0.18 removed [accessibilityState](https://reactnative.dev/docs/accessibility#accessibilitystate) and [accessibilityValue](https://reactnative.dev/docs/accessibility#accessibilityvalue) due to deprecation in this commit https://github.com/necolas/react-native-web/commit/174ebb3c5d68bd396943a949d5e0098840505c1e, but I don't believe they were deprecated? 

There's no mention on the React Native docs of the deprecation and are they part of the [[w3c] Web Props umbrella issue](https://github.com/facebook/react-native/issues/34424) as target attributes. Maybe I've missed something but I don't believe they should have been removed.

### Expected behavior

-

### Steps to reproduce

-

### Test case

-

**Comment by necolas** [comment]
They were deprecated in React Native Web for a while, and that RFC is aimed at replacing them in React Native

**Comment by marklawlor** [comment]
Are you able to point in the direction on what API's to use instead?

I'm currently trying to migrate some RN components which use these props and I'm struggling to find information on it.

**Comment by intergalacticspacehighway** [comment]
there are [accessibility*](https://necolas.github.io/react-native-web/docs/accessibility/) mapping that still works. e.g. `accessibilityValueMax`, `accessibilityValueMin`, `accessibilityChecked`. Would need a platform check though 😅
