### ISSUE TITLE
Support more web props and styles

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#2379]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Support the features of this RFC that React Native will eventually adopt https://github.com/necolas/discussions-and-proposals/blob/reduce-fragmentation/proposals/0000-reduce-fragmentation.md

**Comment by Sharcoux** [comment]
This is an awesome project.

I worked on reducing the css fragmentation with [rn-css](https://www.npmjs.com/package/rn-css)

It brings hover, media queries and units support, and some other web features, to React-Native. It uses style-components syntax, but maybe we could adapt it?
