### ISSUE TITLE
Scroll is blocked when the gesture starts on a Touchable* component

### ISSUE THREAD

**Issue by bloodyowl** [necolas/react-native-web#238]
## issue

the scroll doesn't start at all when gestures starts on a `Touchable*` component

## repro

try to scroll with a gesture starting on "Highlight", blocked on iOS & Chrome responsive mode (not sure about android)

https://jsfiddle.net/2zcv64v0/

is there a workaround?

**Comment by necolas** [comment]
Hmm, pretty sure this is a regression. Will try to track down what caused this.

**Comment by bloodyowl** [comment]
Looks like the culprit is here: https://github.com/necolas/react-native-web/blob/master/src/components/View/index.js#L136

**Comment by necolas** [comment]
Agreed. I wonder how to best fix this without regressing touchables

**Comment by RangerMauve** [comment]
Would using [stopProagation](https://developer.mozilla.org/en/docs/Web/API/Event/stopPropagation) work?
