### ISSUE TITLE
Deprecate Touchables

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#2382]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

The Touchables are no longer recommended in React Native and have been replaced by Pressable. We should deprecate the Touchable components and mixin, and then remove them from React Native for Web. There has been the intent to deprecate them from React Native for a while, but the team hasn't had time to get around to it yet.

**Comment by agusvazquez** [comment]
Hello @necolas are there any docs where I can learn about this?

I looked for TouchableOpacity, the official docs doesn't say that is getting deprecated or no longer recommended to use.
https://reactnative.dev/docs/touchableopacity

Thanks!

**Comment by nabilfreeman** [comment]
@agusvazquez He seems to regularly deprecate things in RN Web ahead of core RN. I've encountered this twice now, pretty annoying.

**Comment by gentlee** [comment]
@necolas I think It is a mistake. Pressable doesn't have press feedback by default, while TouchableOpacity does, and it works most of the time like a charm.

Pressable requires additional programming of the feedback, so if we remove TouchableOpacity, everyone will actually have to implement it, which sounds like an excess work for no good reason.

Also, by being not so flexible, TouchableOpacity seems to be a bit faster alternative.

TouchableWithoutFeedback probably can be deprecated as it looks like a duplicate or Pressable, but other components, especially TouchableOpacity, IMO should not.

**Comment by necolas** [comment]
RN itself has long intended to deprecate those components but just hasn't gotten around to doing so. If you're targeting web, you'll have to move off old APIs faster, because the cost of RN bloat on web is far too high both for me to maintain and for apps on web to be vaguely acceptable from a perf perspective.

**Comment by agusvazquez** [comment]
Isn't the purpose of this library to provide compatibility with React Native, like, code in React Native and export for web.

If you deprecate / remove TouchableOpacity you are literally breaking the main purpose of this library. 

IMO, As a mobile developer, I just want to do React Native work and export to web. That means supporting TouchableOpacity.

**Comment by gentlee** [comment]
@necolas may be they had I don't know, but they didn't, and for a reason. As I said, `Pressable` is not a replace for `TouchableOpacity`, it is a more flexible component if you need more control, that's it. And I agree with @agusvazquez, lets keep RNW aa a library that supports web platform, which it is doing pretty well, without trying to predict the future.

**Comment by Josema** [comment]
`TouchableOpacity is deprecated. Please use Pressable.` 

What is the main motivation of this decision while react-native still support it?

**Comment by mickadoua** [comment]
> This set up of Pressable is a good alternative to TouchableOpacity:
> 
> ```js
>     <Pressable
>         style={({ pressed }) => [
>             { opacity: pressed ? 0.5 : 1.0, backgroundColor: '#2782fb', width: 210, padding: 10, borderRadius: 12 }
>         ]}
>         onPress={someFunction}
>         >
>         <View>
>             <Text className="font-semibold text-center text-[#fff]">Press Me</Text>
>         </View>
>     </Pressable>
> ```

yes, its a good start, but without animation 
i found this exemple very helpful  https://stackoverflow.com/a/77743947

**Comment by YuriiLutsykSPRO** [comment]
I think it was a wrong decision, but the library is awesome in general

**Comment by iamciro** [comment]
Hey there!

> RN itself has long intended to deprecate those components but just hasn't gotten around to doing so. If you're targeting web, you'll have to move off old APIs faster, because the cost of RN bloat on web is far too high both for me to maintain and for apps on web to be vaguely acceptable from a perf perspective.

@necolas, do you have any source where the RN team suggests TouchableOpacity will be deprecated? 

Regards
