### ISSUE TITLE
I18nManager

### ISSUE THREAD

**Issue by hosseinmd** [necolas/react-native-web#2386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I18nManager was removed, but it works in native, a lot of modules working with I18nManager. Remove whole of i18nMaanager is not good approach. This violates the theory of React-Native (Learn once, write anywhere).
Moving to start/end is good solution because has performance and can change direction in runtime. For swipe left to right, we could change body direction in I18nManager.

### Expected behavior

I think you should integrate I18nManager  and useLocaleContext

### Steps to reproduce

.

### Test case

.

**Comment by necolas** [comment]
In React Native, `I18nManager` is undocumented and produces highly limited localization that isn't good enough for web apps. We'll have to improve React Native to match React Native for Web. In the meantime on web all you have to do is set the `dir` prop on an element (eg the root) and use the logical CSS properties and values as covered in the documentation
