### ISSUE TITLE
Docs: Supported browsers list is not clear

### ISSUE THREAD

**Issue by DavidRieman** [necolas/react-native-web#2390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

At https://github.com/necolas/react-native-web/releases - we have the following line:
`Browser support has been reduced: Safari 10.1+, Edge (Chromium), no IE, no legacy Android browser.`

It is not clear from this document whether that (Safari and Edge only) is the full list of officially RNW supported browsers.  Surely it supports Chrome still, and Firefox?

### Expected behavior

Update to releases document's browser support list to be a clear, full list of supported browsers.

### Steps to reproduce

1. Navigate to https://github.com/necolas/react-native-web/releases
2. Try to infer whether RNW at v18+ is (still) expected to work well in Firefox and Chrome.

### Test case

https://github.com/necolas/react-native-web/releases

**Comment by necolas** [comment]
See https://necolas.github.io/react-native-web/docs/browser-compatibility/

**Comment by DavidRieman** [comment]
Thanks!  (If the /releases page is editable, can it point there on that line?)
