### ISSUE TITLE
Dimensions.get calls `change` listeners the first time

### ISSUE THREAD

**Issue by jonathanj** [necolas/react-native-web#2394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

All change listeners on `Dimensions` are called on the first call to `Dimensions.get`, even though there hasn't been any dimension-related change that might trigger layout events.

Some libraries, [notably react-native-popover-view](https://github.com/SteffeyDev/react-native-popover-view/issues/82#issuecomment-1255030671), assume that dimension changes will result in `onLayout` being called for views, but because no layout has actually changed this will not happen.

### Expected behavior

The [one-time initialisation](https://github.com/necolas/react-native-web/blob/dee258ae02188befca4192ea502d4fbebc478341/packages/react-native-web/src/exports/Dimensions/index.js#L50-L57) probably shouldn't be calling listeners when something is simply reading the dimensions.

This behaviour of RNW is inconsistent with RN, in my testing.

### Steps to reproduce

```typescript
let count = 0;
Dimensions.addEventListener('change', () => { ++count });
assert(count === 0);
Dimsensions.get('window');
assert(count === 1);
```

### Test case

https://codesandbox.io/s/nostalgic-microservice-du4zvs

### Additional comments

I'd be happy to do a PR for this, I just wanted to report it in case there was some context about the behaviour that I may have missed, or if there is some nuance to discuss that I'm unaware of.

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/commit/59af091fdb4dd91118b105596a28c093426978b0

**Comment by jonathanj** [comment]
Thanks for the context.

Would it be possible to preserve the improvement introduced by that commit, but  avoid notifying listeners when doing the one-time initialisation?

It’s not clear from the content on the commit/PR if notifying listeners is the key part or if it’s about doing the one-time initialisation sooner.

**Comment by necolas** [comment]
Yeah maybe. Not much context was provided by the PR author

**Comment by jonathanj** [comment]
@necolas Just want to say I appreciate you resolving this, and so thoroughly too, thank you!
