### ISSUE TITLE
How can I add a custom prefix to generated css classNames?

### ISSUE THREAD

**Issue by hoanght1995** [necolas/react-native-web#2395]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

I've added a bundled module to the current project and it seems some classNames in the module are overridden onto the current project because that has the same name. So I need to add a prefix to the classNames in the current project

**Comment by necolas** [comment]
I don't understand the request

**Comment by hoanght1995** [comment]
> I don't understand the request

Thank you. I have fixed the issue

**Comment by sadi304** [comment]
@hoanght1995 how did you solve it?
