### ISSUE TITLE
refactor: add the taskQueue in InteractionManager like react-native

### ISSUE THREAD

**Issue by ntdiary** [necolas/react-native-web#2399]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

In the react-native [documentation](https://reactnative.dev/docs/interactionmanager#methods) :
> InteractionManager.runAfterInteractions() is not working properly on web. It triggers immediately without waiting until the interaction is finished.

example:
In react-navigation,
we want a task to be deferred until the navigation animation ends. (after `clearInteractionHandle` is called)
Actually since the browser may be idle, it will be executed before `clearInteractionHandle` is called. (`requestIdleCallback`)

Can we submit a PR to migrate this feature? 🙂

**Comment by necolas** [comment]
> Can we submit a PR to migrate this feature?

Yes
