### ISSUE TITLE
Using WebkitFontSmoothing: "antialiased" / MozOsxFontSmoothing: "grayscale"

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#240]
I am trying to use the following styles

``` js
const styles = StyleSheet.create({
  icon: {
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
  },
})
```

(I am using https://github.com/oblador/react-native-vector-icons which works like a charm).
Only one thing is missing to have correct icons: this famous font-smoothing css thing.
Currently I am getting warnings (not a big deal) AND a fatal error

```
TypeError: allStylePropTypes[prop] is not a function
```

I guess it's an issue with `inline-style-prefixer`, will try to track that down.

From here we can probably handle the warning maybe?

**Comment by MoOx** [comment]
It seems allStylePropTypes cames from RNW. This snippet do not cause any issue

```js
const prefixAll = require('inline-style-prefixer/static')

const styles = {
  WebkitFontSmoothing: "antialiased",
  MozOsxFontSmoothing: "grayscale",
}

const prefixedStyles = prefixAll(styles)

console.log(prefixedStyles) // output the same styles
```

**Comment by necolas** [comment]
How do the font-smoothing properties relate to SVG icons?

**Comment by MoOx** [comment]
Sadly, react-native does not support SVG because iOS and Android does not support SVG themselves (yeah you read correctly, I was really surprised by this).
So react-native-vector-icons use the old web trick: a font

Without this font-smoothing thing, icons can look really ugly:

With font-smoothing:

![image](https://cloud.githubusercontent.com/assets/157534/20240871/f3adecda-a923-11e6-8a5b-5a00d59936d1.png)


Without

![image](https://cloud.githubusercontent.com/assets/157534/20240867/e8bccb8e-a923-11e6-9a2f-5bacdfbe7464.png)

Obviously this will depend of the platform+browser but I think we should add support for this property, icons or not icons :)

font-smoothing is also handy for light text on dark background.
