### ISSUE TITLE
deployment on netlify is not working

### ISSUE THREAD

**Issue by jsbaguette** [necolas/react-native-web#2402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Using `expo export:web`. When i deploy to netlify and follow the simple deployment. It's not working when navigate manually to a page. But working when using Link component

### Expected behavior

I should be able to manually navigate to `/login` page

### Steps to reproduce

- Create 3 dum component
- app.js
```import { StatusBar } from 'expo-status-bar';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { Text } from "react-native"

import HomeScreen from './src/screens/HomeScreen.js';
import LoginScreen from './src/screens/LoginScreen.js';
import NotFoundScreen from './src/screens/NotFoundScreen.js';

const Stack = createNativeStackNavigator();

const linking = {
  config: {
    screens: {
      Login: {
        path: "login"
      },
      Home: {
        path: ""
      },
      NotFound: {
        path: "*"
      },
    }
  }
}

function App() {


  return (
    <NavigationContainer linking={linking} fallback={<Text>Loading...</Text>}>
      <Stack.Navigator initialRouteName="Login" screenOptions={{ headerShown: false }}>
        <Stack.Screen name="Login" component={LoginScreen} options={{ 
          title: "Login Page",
          gestureEnabled: false
        }} />
        <Stack.Screen name="Home" component={HomeScreen} options={{ 
          title: "Home",
          gestureEnabled: false
        }}  />
        <Stack.Screen name="NotFound" component={NotFoundScreen} />
      </Stack.Navigator>
      <StatusBar style="auto" />
    </NavigationContainer>
  );
}

export default App;
```

- following https://docs.expo.dev/distribution/publishing-websites/#netlify

### Test case

https://codesandbox.io/p/github/jsbaguette/colib-mobile/main?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A19000%252C%2522key%2522%253A%2522cl8qsga4p004g3b6o4ez40kgf%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cl8qsg7zn001z3b6omhzh1g5f%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### Additional comments

my package json dependencies:

```
"dependencies": {
    "@expo/webpack-config": "^0.17.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "expo": "~46.0.9",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-heroicons": "^3.2.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "12.3.0",
    "react-native-web": "~0.18.7"
  },
```

**Comment by necolas** [comment]
This is not the expo / react-navigation repo

**Comment by jsbaguette** [comment]
You right necolas I opened the issue in expo directly. I have found a solution also for people who may come here.

```

Actually it worked after adding the `_redirects` file inside web-build with `/* /index.html 200`

and inside my package json 

"build:web": "expo export:web && cp _redirects web-build"

```
