### ISSUE TITLE
Accessibility - Pressable does not render with aria-checked

### ISSUE THREAD

**Issue by penx** [necolas/react-native-web#2403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The following code 

```tsx
    <Pressable
      accessibilityLabel="label"
      accessibilityRole="radio"
      accessibilityState={{ checked: true }}
    >
      Example
    </Pressable>
```

renders as

```html
<div aria-label="label" role="radio" tabindex="0">Example</div>
```

Which includes the label and role attributes but does not include `aria-checked`

### Expected behavior

Should render as

```html
<div aria-label="label" role="radio" tabindex="0" aria-checked="true">Example</div>
```

### Steps to reproduce

react-native-web@0.18.9

As per code code sandbox test case. 

### Test case

https://codesandbox.io/s/react-native-web-checked-1ej4me

**Comment by penx** [comment]
I see support for this was removed in https://github.com/necolas/react-native-web/commit/174ebb3c5d68bd396943a949d5e0098840505c1e with the comment" Remove deprecated accessibility APIs", but I don't see any reference to accessibilityState being deprecated at https://reactnative.dev/docs/accessibility

**Comment by penx** [comment]
I've also seen https://github.com/necolas/react-native-web/discussions/2372 and have left a comment there - I don't understand how to use accessibility props such as checked in a way that works on both native and web, without supporting the accessibilityState prop.

**Comment by necolas** [comment]
Use `accessibilityChecked`. See https://necolas.github.io/react-native-web/docs/accessibility/ and https://github.com/necolas/react-native-web/releases/tag/0.18.0

**Comment by penx** [comment]
Thanks!

I still need to figure out typing, but I think I can create a utility like this:

```ts
const getAccessibilityStateProps = (accessibilityState: {
  disabled?: boolean;
  selected?: boolean;
  checked?: boolean | "mixed";
  busy?: boolean;
  expanded?: boolean;
}) =>
  Platform.select({
    web: {
      accessibilityDisabled: accessibilityState.disabled,
      accessibilitySelected: accessibilityState.selected,
      accessibilityChecked: accessibilityState.checked,
      accessibilityBusy: accessibilityState.busy,
      accessibilityExpanded: accessibilityState.expanded
    },
    default: { accessibilityState }
  });
```

and have wrapped this in a little library called [react-native-accessibility-props](https://github.com/penx/react-native-accessibility-props) that can be used like this


```tsx
import { Pressable } from "react-native";
import { getAccessibilityStateProps } from "react-native-accessibility-props";

export default function App() {
  return (
    <Pressable
      accessibilityRole="radio"
      accessibilityLabel="label"
      {...getAccessibilityStateProps({ checked: true })}
    >
      Example
    </Pressable>
  );
}
```

Seems to work, other than the types, which I'll think about and hopefully publish an update.

https://codesandbox.io/s/react-native-accessibility-props-0vpn1r

I'll probably add another utility for all other accessibility& props too.
