### ISSUE TITLE
Autocorrect - Highlight not disappearing after submit (iOS Safari).

### ISSUE THREAD

**Issue by jeet-dhandha** [necolas/react-native-web#2405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Whenever you are typing something with autocorrect the text gets highlighted and when you submit it the highlight still remains and it disappears only when focusing out of textinput or on focusing back onto text input by pressing on it.

https://user-images.githubusercontent.com/78416198/193973626-5b4f5a2e-9633-405d-87ab-a4aad00ed6da.mov

### Expected behavior

The highlight should disappear automatically after submit.

### Steps to reproduce

Set `autoCorrect={true}` for TextInput and then try typing on an iPhone simulator Safari Browser. To access react-native-web app on simulator add `--host 0.0.0.0` to webpack command which will allow you to access `0.0.0.0:<HOST_NUMBER>` on simulator. Also replace HOST_NUMBER with your provided host number for e.g. `0.0.0.0:8080`.

### Test case

NA

**Comment by necolas** [comment]
Closing due to lack of reduced test case. It's possible Safari just behaves like this
