### ISSUE TITLE
remove role="list" on <ul> and role="listitem" on <li> when using API accessibilityRole

### ISSUE THREAD

**Issue by kopax-polyconseil** [necolas/react-native-web#2407]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

We have the two following component:

`Ul.tsx`:

```tsx
import { Platform, View } from 'react-native'
import styled from 'styled-components/native'

import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'

export const Ul: React.FC = styled(View).attrs({
  accessibilityRole: AccessibilityRole.LIST,
})({
  paddingLeft: 0,
  flexDirection: 'row',
  overflow: Platform.OS === 'web' ? 'auto' : undefined,
})

export const VerticalUl: React.FC = styled(Ul)({
  flexDirection: 'column',
})

```

`Li.tsx`:

```tsx
import { Platform } from 'react-native'
import styled from 'styled-components/native'

import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'

export const Li: React.FC = styled.View.attrs({
  accessibilityRole: 'list',
})({
  display: Platform.OS === 'web' ? 'list-item' : 'flex',
})

```

According to many site, it is not necessary nor recommended to use those role when rendering a list.

- Why did you add them at the beggining ?
- Can this be removed ?

Source: https://rocketvalidator.com/html-validation/the-listitem-role-is-unnecessary-for-element-li

**Comment by fershibli** [comment]
How did you get to make styled-components work with react-native-web? I'm researching this, so far it looks like only achievable by using Next.js, but I think this is overkill...

**Comment by kopax-polyconseil** [comment]
@fershibli you can check https://github.com/pass-culture/pass-culture-app-native
