### ISSUE TITLE
Touchable: fix cross-browser flex styling

### ISSUE THREAD

**Issue by lsps9150414** [necolas/react-native-web#241]
HTML's `<Button>` tag does not support flex styling in some browsers (e.g. safari), causing the flex styles on `<touchable>` to fail.

Suggest to wrap touchable's content with a `<div>` and assign the flex styles to it so that flex will work.

**Comment by necolas** [comment]
Good point. We use the same fix (with a `span`) on mobile.twitter.com

**Comment by lsps9150414** [comment]
Maybe it's better to solve this inside `react-native-web` so the exact same code could really cross platforms?

**Comment by necolas** [comment]
Yep

**Comment by necolas** [comment]
Please can you share a test case with me so I can validate the fix?

**Comment by necolas** [comment]
If anyone wants to test out a possible fix…038281d5d193dace6aff83fa71b4a25ccd915219

**Comment by necolas** [comment]
I don't think there's a good way to fix this at the framework level (while using `button`) that covers all possibilities without introducing unexpected layout issues. Perhaps the `button` role should not map to HTML `button` in order to fix this.

**Comment by mikeaustin** [comment]
Hi, I just started using react-native-web to prototype a react-native project. I just noticed that <Button /> doesn't flex horizontally, and it sounds like it's related to this ticket. If the ticket is closed, does that mean it's fixed?

I'm simply trying to display a row of horizontal evenly spaced buttons, like an iPhone tab-bar.
