### ISSUE TITLE
Why CSS in modules supported by react-native, but can't do the same thing with react-native-web?

### ISSUE THREAD

**Issue by sikaco** [necolas/react-native-web#2410]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

I have a new project with react-native, and let it support CSS in modules (such as sass,scss) success.
But I can't let RNW do the same thing.

The closest approach I founded is https://github.com/kristerkari/react-native-css-modules-with-typescript-example .
However, If I upgrade those dependencies such as webpack, everything will back to the beginning.

At the bottom, that's still a tricky & magic third-party way. So there are any more reliable method officially can resolve it?

Honestly, I think RNW which support CSS in modules is the COMPLETE RNW.
THX, that would be very helpful 🙏.

**Comment by necolas** [comment]
I don't understand the request. This project implements the RN API. If you're using another project, ask them to include web support

**Comment by sikaco** [comment]
> I don't understand the request. This project implements the RN API. If you're using another project, ask them to include web support

Oh, let me change the question please.
I just want to ask this question: is there a way to get RNW to support Sass? just like RN？

I want make RNW and RN coexist in an app.

**Comment by sikaco** [comment]
@necolas

**Comment by david-cahill** [comment]
+1
