### ISSUE TITLE
Allow passing className + style

### ISSUE THREAD

**Issue by natew** [necolas/react-native-web#2411]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Right now you can either do `$$css` = true or pass styles. For [Tamagui](https://tamagui.dev), we pass some styles inline and some as className. I could force convert all inline styles into classNames, at the expense of some extra logic.

Would this be amenable?

```tsx
<View style={[
  { $$css: true, background: 'bg-classname' },
  { margin: 10 }
]} />
```

Allowing for passing in mixed className/style. It would match the output of styleq as well.

**Comment by necolas** [comment]
Isn't this already supported?

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/releases/tag/0.18.0

**Comment by natew** [comment]
Worked on second try, must have made a mistake.

**Comment by necolas** [comment]
FYI in 0.20 I'm looking to add a mechanism to exclude the runtime style compiler

https://github.com/necolas/react-native-web/pull/2508
