### ISSUE TITLE
Styling ScrollBars

### ISSUE THREAD

**Issue by Saikedo** [necolas/react-native-web#2416]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Is there a way to style scrollBars on web? I searched around but was unable to find anything meaningful.

I found one way of doing it by assigning a nativeID to scrollView for example and then using CSS that looks something like this

```
    #scrollBarId::-webkit-scrollbar {
      width: 6px;
    }

    #scrollBarId::-webkit-scrollbar-track {
      box-shadow: inset 0 0 5px grey;
      border-radius: 10px;
    }

    #scrollBarId::-webkit-scrollbar-thumb {
      background: #5D3E65;
      border-radius: 10px;
    }

    #scrollBarId::-webkit-scrollbar-thumb:hover {
      background: #5D3E65;
    }
```

But I don`t really like this because I will either need to create the same CSS for each element that needs styling for scroll bar or end up assigning the same `scrollBarId` which seems to work but from what I understand each HTML element must have a unique ID so this is not perfect.

**Comment by ayushrathore111** [comment]
i want to do this can you please assign to me...

**Comment by Saikedo** [comment]
Hi,

I was wondering if there are any plans set to implement this functionality.

**Comment by bmbmjmdm** [comment]
Also having this issue! @Saikedo , I believe I implemented what you have and don't see it styling the scrollbar unfortunately? 

```
/* Track */
#scroll::-webkit-scrollbar-track {
  background: #000000;
}

/* Handle */
#scroll::-webkit-scrollbar-thumb {
  background: #444444;
}

/* Handle on hover */
#scroll::-webkit-scrollbar-thumb:hover {
  background: #555555;
}
```


```
  <ScrollView style={{height: 1}} nativeID="scroll"></>
```

The scrollbar shows, but is still the original grey

**Comment by necolas** [comment]
Closing this as I won't be adding support for this to the existing StyleSheet implementation. In the future a style compiler can be used instead of StyleSheet, and it might provide support for this selector and avoid crashing RN

**Comment by Abdul-Mustafa-Developer** [comment]
anyone here!
