### ISSUE TITLE
Custom fonts not loading for web

### ISSUE THREAD

**Issue by terragady** [necolas/react-native-web#2419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I have to use custom font but it does not work with web. I do link them for android and ios and they work fine with the emulator there but web is showing standard font.

### Expected behavior

Rendered custom font

### Steps to reproduce

![image](https://user-images.githubusercontent.com/19210041/199728514-bc39cc87-73e7-46fc-aecf-163c83190bca.png)
I do have them locally stored and importing them with @font-face like this in index.css:

```
@font-face {
  font-family: CircularStd-Book;
  font-style: normal;
  font-weight: 400;
  src: url('./src/assets/fonts/CircularStd-Book.otf') format('opentype'),
    url('./src/assets/fonts/CircularStd-Book.ttf') format('truetype');
}
```

and then importing it in index.web.js
`import './index.css';`

tried also inline in index.html: 
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link rel="stylesheet" href="./index.css">
  <title>RN Web</title>
  <style>
    @font-face {
      font-family: CircularStd-Book;
      font-style: normal;
      font-weight: 400;
      src: url('./src/assets/fonts/CircularStd-Book.otf') format('opentype'),
        url('./src/assets/fonts/CircularStd-Book.ttf') format('truetype');
    }
    #app-root {
      display: flex;
      flex: 1 1 100%;
      height: 100vh;
      font-family: CircularStd-Book;
    }
  </style>
</head>

<body>
  <div id="app-root"></div>
</body>
</html>
```

and the webpack configuration:
```
  module: {
    rules: [
      {
        test: /\.(otf|ttf)$/,
        use: {
          loader: 'url-loader',
        },
      },
      {
        test: /\.css$/i,
        use: ['css-loader'],
      },
      babelLoaderConfiguration,
      imageLoaderConfiguration,
      svgLoaderConfiguration,
    ],
  },
```

None of the above works.

Testing also on small scope:
```
export const Text = styled.Text`
  font-family: CircularStd-Book;
`;
```

### Test case

no

**Comment by necolas** [comment]
Closing as this isn't a react-native-web issue. This library is just a component library for React DOM and doesn't control your build system

**Comment by HannahCarney** [comment]
This still isn't working in RN-web, can you please reopen?

**Comment by luongminh2410-fabbi** [comment]
face the same issue, pls reopen

**Comment by leo-1228** [comment]
Same here
