### ISSUE TITLE
Production Build: eliminate unused components/apis

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#242]
So as opposed to [aliasing core.js](https://github.com/necolas/react-native-web/blob/0c76cc5d80bb188a48d3b0970d715be4f33552da/docs/guides/rendering.md#client-and-server-rendering), what is the recommended way to import something in between something so minimal as that and everything?

Clone RNW and do it myself? Or is there a way to go about it without having to maintain one's own package?

**Comment by necolas** [comment]
Once webpack@2 is out I'll export an ES6 package to take advantage of tree-shaking.

In the meantime, one option I'm playing around with at Twitter is aliasing `react-native` to a local module in our app and exporting what we need from there. Something like this.

```
// this file is aliased to 'react-native'
import ReactNative, { Text, View } from 'react-native-web/core';
import ProgressBar from 'react-native-web/lib/components/ProgressBar';
import Switch from 'react-native-web/lib/components/Switch';

export default ReactNative;
export Switch;
export Text;
export ProgressBar;
export View;
```

**Comment by faceyspacey** [comment]
excellent, that's what I'll do. I just wasn't sure if importing components individually by path like that would break things. 

...out of curiosity, if ur using webpack 2 now, what would the "ES6 package" you mentioned do differently to take advantage of tree-shaking?

**Comment by faceyspacey** [comment]
in case you're interested here are the errors you get:

```
ERROR in ./~/animated/lib/index.js
Module build failed: Error: Couldn't find preset "react-native" relative to directory "/Users/jamesgillmore/React/celebvidy-web/node_modules/animated"
```

```
ERROR in ./~/animated/lib/Easing.js
Module build failed: Error: Couldn't find preset "react-native" relative to directory "/Users/jamesgillmore/React/celebvidy-web/node_modules/animated"
```

**Comment by faceyspacey** [comment]
Also note for anyone else interested, the paths start with `/dist`. Here's what I ended up with:

```
import { 
  Image,
  Text,
  TextInput,
  View,
  StyleSheet
} from 'react-native-web/dist/core';


import Animated from 'react-native-web/dist/apis/Animated';
import AsyncStorage from 'react-native-web/dist/apis/AsyncStorage';
import Dimensions from 'react-native-web/dist/apis/Dimensions';
import Easing from 'animated/lib/Easing';

import Touchable from 'react-native-web/dist/components/Touchable/Touchable';
import TouchableOpacity from 'react-native-web/dist/components/Touchable/TouchableOpacity';
import TouchableWithoutFeedback from 'react-native-web/dist/components/Touchable/TouchableWithoutFeedback';


export {
  Image,
  Text,
  TextInput,
  View,
  StyleSheet,

  Animated,
  AsyncStorage,
  Dimensions,
  Easing,

  Touchable,
  TouchableOpacity,
  TouchableWithoutFeedback,
}
```

**Comment by necolas** [comment]
> Animated seems to have some circular reference issue.

I wonder if webpack is trying to import all the files in that package. At first glance I can't see any files imported that themselves import `react-native`.

> I ran it through webpack-bundle-size-analyzer and animated was like 25% bigger.

The webpack@2 beta was increasing the bundle size of our app, so it could be a webpack issue.

> I'm dealing with the distribution that is already passed the stage of still having imports in the code, which webpack can use to tree shake.

That's true. However, if you use `babel-preset-react-native` and don't exclude all `node_modules`, you may be able to import the `src` modules directly in the meantime.

**Comment by sjmueller** [comment]
@necolas probably dumb question, but can you talk a little more about the method you're using for path aliasing? Is there a clever trick here to get `import { Text, View } from 'react-native` statement automatically pointing to your local [lean] export? Or are you changing every file in your project to `./react-native`?

I'm trying to slim down our bundle as much as possible, and I think there might be a couple hundred k here in savings...

**Comment by RangerMauve** [comment]
@sjmueller Check out [aliasing in Webpack](https://webpack.github.io/docs/configuration.html#resolve-alias)

**Comment by sjmueller** [comment]
Thanks @rangermauve. I was hoping there was a way without `eject`ing create-react-app :(
