### ISSUE TITLE
RN parity: showSoftInputOnFocus property of <TextInput /> is not supported

### ISSUE THREAD

**Issue by christianwen** [necolas/react-native-web#2421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In https://reactnative.dev/docs/textinput, there's the `showSoftInputOnFocus` property that `will prevent the soft keyboard from showing when the field is focused`, but react-native-web does not support this yet.

### Expected behavior

`showSoftInputOnFocus` property of `<TextInput />` works correctly

### Steps to reproduce

1. Create a `TextInput` with `showSoftInputOnFocus=false`
2. Open mobile browser, click on the TextInput
3. We still see the keyboard open, the keyboard should **not** open

### Test case

https://codesandbox.io/s/runtime-paper-lgmxb3

### Additional comments

Since `react-native-web` does not support `showSoftInputOnFocus` yet, we need to make an update to support it
In `https://github.com/Expensify/react-native-web` -> `packages/react-native-web/src/exports/TextInput/index.js`

```diff
const {
+    showSoftInputOnFocus = true
  } = props;
...
  switch (keyboardType) {
    case 'email-address':
      type = 'email';
      break;
    case 'number-pad':
    case 'numeric':
      inputMode = 'numeric';
      break;
    case 'decimal-pad':
      inputMode = 'decimal';
      break;
    case 'phone-pad':
      type = 'tel';
      break;
    case 'search':
    case 'web-search':
      type = 'search';
      break;
    case 'url':
      type = 'url';
      break;
    default:
      type = 'text';
  }

+  if (!showSoftInputOnFocus) {
+    inputMode = 'none';
+  }
```

I can open a PR for this once this issue proposal is accepted.
Thanks!
cc @necolas

**Comment by necolas** [comment]
I think what we should do instead is do the mapping to inputMode in React Native. See https://github.com/facebook/react-native/pull/34460

**Comment by necolas** [comment]
Support for `inputMode='none'` is now merged into `react-native@main`. Not sure if it will make it into the `react-native@0.71.0` release. But `inputMode` will be supported in `react-native-web@0.19`.

**Comment by christianwen** [comment]
@necolas do we have an estimated date for the `react-native-web@0.19` release that will support the `inputMode`?

**Comment by christianwen** [comment]
> @necolas do we have an estimated date for the `react-native-web@0.19` release that will support the `inputMode`?

@necolas can you take a look at this comment, thanks!

**Comment by christianwen** [comment]
> @necolas can you take a look at this comment, thanks!

@necolas can you help check this?
thanks!

**Comment by necolas** [comment]
No estimate

**Comment by necolas** [comment]
Using `inputMode` is now possible in 0.19 and with RN 0.71+. Thanks
