### ISSUE TITLE
ScrollView full of TouchableHighlights does not scroll

### ISSUE THREAD

**Issue by lauri-lehtovaara** [necolas/react-native-web#243]
**What is the current behavior?**
ScrollView full of TouchableHighlights does not scroll.

Link to minimal test case: 
http://mindcraft.fi/test.html
"Show touchable" link

**What is the expected behaviour?**
ScrollView full of TouchableHighlights should scroll, like in native app or react-native-web with ScrollView full of Texts.

Link to minimal working test case with Texts: 
http://mindcraft.fi/test.html
"Show text" link

**Environment (include versions)**

OS: Android 4.4.2
Device: Samsung Galaxy S4 mini
Browser: Firefox Mobile
React Native for Web (version): 0.0.47
React (version): 0.34.1

**Comment by necolas** [comment]
Fixed in 0.0.48
