### ISSUE TITLE
Dimensions change event is not fired on iOS (Safari)

### ISSUE THREAD

**Issue by rawalyogendra** [necolas/react-native-web#2430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Dimensions `change` event is not fired when keyboard is triggered on Safari.

It's similar to this issue #1369 which we have fixed in the past.

### Expected behavior

The event should be fired when keyboard state changes, like it does on Chrome.

CSB Preview: https://scdqh6.sse.codesandbox.io/dimensions

### Steps to reproduce

1. Go to above CSB Preview URL
2. Interact with the text input.
3. See the `window.height` does not change

### Test case

https://codesandbox.io/s/stupefied-brook-scdqh6?file=/pages/dimensions/index.js

**Comment by rawalyogendra** [comment]
@necolas it turns out this issue is not related to our project, rather it is a Safari related issue. Safari does not fire a resize event on keyboard open/close. 

Are we looking to fix this on our side?

One solution would be using [window.visualViewport](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport) which does have a resize event and is fired by all browsers including Safari when keyboard open/close.

It has pretty good [support](https://caniuse.com/mdn-api_window_visualviewport).

 We can listen to `resize` event on `window.visualViewport` and update the `Dimensions` returned by `window.visualViewport`

**Comment by rawalyogendra** [comment]
@necolas I can fix this if you can give the green signal

**Comment by necolas** [comment]
Yeah, go for it. Thanks
