### ISSUE TITLE
Unable to resolve "inline-style-prefixer/lib/plugins/backgroundClip"

### ISSUE THREAD

**Issue by nephix** [necolas/react-native-web#2431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In an existing expo project I tried to add web support, but when running `expo start --web` I get:

```
Web Bundling failed 290ms
Unable to resolve "inline-style-prefixer/lib/plugins/backgroundClip" from "../../node_modules/react-native-web/dist/modules/prefixStyles/static.js"
```

### Expected behavior

Compiles successfully

### Steps to reproduce

It uses `react-native-web@~0.18.7` and in my package-lock.json I see `inline-style-prefixer@^6.0.1` gets installed (it has version `6.0.3` in `node_modules`), but

> node_modules/inline-style-prefixer/lib/plugins/backgroundClip

does not exist.

I can see in 

> node_modules/react-native-web/dist/modules/prefixStyles/static.js 

or https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/prefixStyles/static.js#L1 that it get's imported:

```
import backgroundClip from 'inline-style-prefixer/lib/plugins/backgroundClip';
```

### Test case

I don't have one

**Comment by nephix** [comment]
Seems to be related to https://github.com/robinweser/inline-style-prefixer/issues/227 and there is already a PR for RNW https://github.com/necolas/react-native-web/pull/2427 so I think the issue can be closed

**Comment by dannyhw** [comment]
I'm getting this error in react-native-web ~0.19.10, seems like the PR was closed. Has this been fixed?

**Comment by jimjam88** [comment]
I don't think it has - I'm still seeing the issue.

```
web:dev: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/foo/node_modules/inline-style-prefixer/lib/plugins/backgroundClip' imported from /Users/foo/apps/web/build/index.js
web:dev: Did you mean to import inline-style-prefixer/lib/plugins/backgroundClip.js?
web:dev:     at finalizeResolution (node:internal/modules/esm/resolve:263:11)
web:dev:     at moduleResolve (node:internal/modules/esm/resolve:908:10)
web:dev:     at defaultResolve (node:internal/modules/esm/resolve:1121:11)
web:dev:     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
web:dev:     at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
web:dev:     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
web:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
web:dev:     at link (node:internal/modules/esm/module_job:84:36) {
web:dev:   code: 'ERR_MODULE_NOT_FOUND',
web:dev:   url: 'file:///Users/foo/node_modules/inline-style-prefixer/lib/plugins/backgroundClip'
web:dev: }
```

I'm using a pnpm workspace with Remix (esbuild)

**Comment by jimjam88** [comment]
Downgrading to 6 didn't work for me. I did find a solution although it's not ideal. I set `serverModuleFormat` to cjs in my remix.config.js, rebuilt and all is well. Really strange issue... It's as if esm react-native-web is pulling in cjs inline-style-prefixer

**Comment by yjb94** [comment]
+1 for this
