### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by sparshmartireshk** [necolas/react-native-web#2437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Error while compiling code 

### Expected behavior

should run without any compile error this happens only for out of box react-native components

### Steps to reproduce

 "react-native": "^0.62.3",
"react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-native-web": "^0.18.10",

### Test case

no link

### Additional comments

<img width="951" alt="image" src="https://user-images.githubusercontent.com/117884066/203540231-01b5cbcb-fdb3-4ad1-bdde-882e75ace7fb.png">

**Comment by necolas** [comment]
Search the closed issues as there are dozens of examples of this that are solved if you read the docs on compiling the uncompiled RN packages
