### ISSUE TITLE
ScrollView full of TouchableHighlights scrolls, but fires onPress twice.

### ISSUE THREAD

**Issue by lauri-lehtovaara** [necolas/react-native-web#244]
What is the current behavior?
Original issue with 0.0.47: ScrollView full of TouchableHighlights did not scroll.
New issue with 0.0.48: ScrollView full of TouchableHighlights scrolls, but fires onPress twice.

Link to minimal test case:
http://mindcraft.fi/react-debug/

What is the expected behaviour?
ScrollView full of TouchableHighlights scrolls and fires onPress ONCE.

Environment (include versions)

OS: Android 4.4.2
Device: Samsung Galaxy S4 mini
Browser: Firefox Mobile
React Native for Web (version): 0.0.48
React (version): 0.34.1

**Comment by lauri-lehtovaara** [comment]
Code:

import React,{ Component, } from 'react';
import {AppRegistry,StyleSheet,Text,View,ScrollView,TouchableHighlight,Platform,} from 'react-native';

class App extends Component {
    constructor(props) {
        super(props);
        this.state = { clickcount: [] };
        this.clickcount = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,];
    }
    render() {
        var parent = this;
        return (<View style={styles.container}><ScrollView>{
                parent.clickcount.map(function(item,index) {
                        return (
                                <TouchableHighlight key={'btn'+index} style={{padding:10}}
                                onPress={function(event){parent.clickcount[index] = parent.clickcount[index] + 1; paren\
t.setState({clickcount: parent.clickcount})}}>
                                <Text>--- Test touchable {index} : {parent.clickcount[index]}---</Text>
                                </TouchableHighlight>)})}
            </ScrollView></View>);}}

const styles = StyleSheet.create({container: {flex: 1, alignItems: 'stretch',},});

AppRegistry.registerComponent('App', () => App);
AppRegistry.runApplication('App', { rootTag: document.getElementById('react-root') });

**Comment by necolas** [comment]
I just tried the test case in FF 49 on Android 6 and couldn't reproduce the issue.

You listed "React 0.34.1". Is that correct?

**Comment by lauri-lehtovaara** [comment]
Updating FF fixed the issue. Sorry for not checking this before posting. And thank you. This library is awesome.

Oops, should have been
react: 15.3.2
react-native 0.34.1

**Comment by necolas** [comment]
No worries, glad it's fixed :)
