### ISSUE TITLE
Different styling for SSR & CSR for development environment

### ISSUE THREAD

**Issue by uyend** [necolas/react-native-web#2445]
### The problem: 
There is difference in class names generated by SSR & CSR (for non production environment). This causes issues when the initial server side rendering is showing a different styles due to logic in `createIdentifier` in `Stylesheet/compile.js` whereby CSR is using production env, and SSR is using development env. 

Classname in CSR: css-1dbjc4n
Classname in SSR: css-view-1dbjc4n

Is there a reason we do this? 
What's the workaround for this or an upcoming feature addressing this issue?

**Comment by necolas** [comment]
Why are you running one environment in dev mode and the other in prod mode?
