### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by xiongemi** [necolas/react-native-web#2446]
### Is there an existing request?

- [x] I have searched for this request

### Describe the feature request

Vite support instead of webpack?
react-native-web uses the webpack. webpack is still very popular, but it is slow.
How about using vite instead?

**Comment by Dovakeidy** [comment]
Why couldn't you use Vite? React native web is not specific to Webpack. Here is an example of a Vite setup you can use to get started.

`
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  define: {
    global: "window",
  },
  optimizeDeps: {
    include: ["@react-navigation/native"],
    esbuildOptions: {
      mainFields: ["module", "main"],
      resolveExtensions: [".web.js", ".js", ".ts"],
    },
  },
  resolve: {
    extensions: [".web.tsx", ".web.jsx", ".web.js", ".tsx", ".ts", ".js"],
    alias: {
      "react-native": "react-native-web",
    },
  },
  plugins: [
    react()
  ],
  build: {
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
})`

**Comment by yuxizhe** [comment]
vite.config

```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      'react-native': 'react-native-web',
    },
  },
  plugins: [react()],
});

```

**Comment by xiongemi** [comment]
is there an out of box support?

**Comment by necolas** [comment]
react-native-web doesn't use any bundler. you can use whichever bundler you want

**Comment by stephenkillingsworth** [comment]
@Dovakeidy your suggestion worked for me, but I also needed `.jsx` for non-TS components.
`resolve: {
    extensions: [".web.tsx", ".web.jsx", ".web.js", ".tsx", ".jsx", ".ts", ".js"],
    alias: {
      "react-native": "react-native-web",
    },
  },`

**Comment by stereobooster** [comment]
This may be useful https://stereobooster.com/posts/react-native-web-with-vite/#final-config
