### ISSUE TITLE
server-side renderings delivers lots of redundant inline styles

### ISSUE THREAD

**Issue by faceyspacey** [necolas/react-native-web#245]
Is there a recommended optimized approach to not delivering all the redundant inline styles over the wire??

**Comment by necolas** [comment]
The impact after gzip is negligible in my testing

**Comment by faceyspacey** [comment]
im at 26kb after gzipping and what seems like 90% of the page are those styles. Are there any options available? Anything worth exploring?

**Comment by RangerMauve** [comment]
I doubt there's anything that will save you space when it comes to inline styles given that it's the only way to style React-Native components. Maybe it would be possible to re-use definitions as their own files which get imported into multiple components.

**Comment by necolas** [comment]
How big is the page when you strip all styles?

**Comment by necolas** [comment]
FWIW, I ran the entirety of the client-rendered HTML for the mobile.twitter.com Home Timeline through an HTML compressor and got these results (**3.58 KB** difference):

**production**

```
Input: 108.86 KB
Output: 108.81 KB
Gzip: 20.06 KB
Delta: -88.80 KB (-81.57%)
```

**using react-native-web**

```
Input: 231.05 KB
Output: 230.79 KB
Gzip: 23.64 KB
Delta: -207.41 KB (-89.77%)
```

Whatever problems there are with using inline styles, I don't think over-the-wire size of SSR pages is one of them. I might still re-introduce a classname transform if the perf cost of doing that is less than the cost of using a lot of inline styles in the browser.

**Comment by faceyspacey** [comment]
How can I strip all styles? RNW internally adds the bulk of them. 

...but year, ur right, the compression probably does handle a lot of it, since the styles are all identical. SSR is good to go.

As far as performance, it's looking like 1.5-2x slower is the number to peg on rendering costs of using inline styles: https://ctheu.com/2015/08/17/react-inline-styles-vs-css-stupid-benchmark

Based on that, something like Aphrodite or JSS might work very well for us since, from the looks of it, we can provide the same `StyleSheet.create()` + `style={[style1, style2]}` interface and easily change the implementation. For example, if Aphrodite has you do `className={css(styles.marker, this.props.styles)}`, we obviously move *that* `className` assignment to be implemented within our RNW components based on styles it receives in their `style` prop; and of course those styles are styles returned from Aphrodite's `StyleSheet.create()`, rather than our current one. 

That said, JSS may in fact be the better more performant solution in terms of rendering:

https://medium.com/@oleg008/aphrodite-vs-jss-a15761b91ee3#.igfosqsnm

I'm personally not as interested in saving bytes by rendering during the component life-cycle as Aphrodite does (as you pointed out, the bytes is likely negligible when it comes to css). I'm fine with an entire stylesheet rendered per imported component like JSS does. That will definitely be a lot smaller than we are sending now, and of course more importantly it will mean faster rendering. 

Either way, both options inject the css into the `head` as a separate stylesheet, and--unless I'm missing something--based on the above performance report would almost double rendering speed. In addition, RNW users would have the option to use things like pseudo selectors (e.g. `:hover`), without tampering with typical `Stylesheet` API as the latter is just a subset of the former. Perhaps even RN users would as well, as RN support is either supported or on the roadmap for these css frameworks.

**Comment by faceyspacey** [comment]
That all said, the Khan Academy team behind Aphrodite seemed to be hellbent on not having to send those extra 3-4kb lol:

http://engineering.khanacademy.org/posts/aphrodite-inline-css.htm

> We must deliver the absolute minimum amount of CSS necessary by only sending down CSS in use by components in the server-side rendered body. This rules out extracting all the CSS used in all of our components at compilation time, as much of that CSS would not be needed for the initial page load.

I wonder how small they are getting their initial page loads, 5kb? They don't have a wall of tweets after all. I also wonder what the difference in perceived time is between a 5kb page load and a 20kb page load, when it's starting to tip on the side of rendering taking longer than network latency, not to mention additional rendering time the entire that application tab is open.

**Comment by faceyspacey** [comment]
Here's a gist with the basics of the JSS implementation:

https://gist.github.com/faceyspacey/453e6ee26d6dae319b48679ea56e9432


The relevant parts are:
```
create(styles) {
    const sheet = jss.createStyleSheet(styles).attach(); //goodies!
    return sheet.classes; 
  },
```
and
```
resolve(props) {
    let className = props.className || '';
    className += ' ' + resolveStyle();
    return { className }; //note: we'll deal with display and pointer events `styleAsClassName` if we go this route
  }
```
and
```
const resolveStyle = (style) => {
  if (typeof style === 'string') {
    return style; //className generated by `jss.createStyleSheet(styles).attach()` 
  }
  else if (Array.isArray(style)){
    return style.map(s => resolveStyle(s)+' '); 
  }
  else if (typeof style === 'object') {
    const className = `generated-class-${Math.floor((Math.random() * 100000) + 1)}`; 
    const styles = {
      [className]: style //inline style object NOT from `StyleSheet.create()`
    };
    
    jss.createStyleSheet(styles).attach(); //append generated selector+style to the DOM
 
    return className;
  }
}
```

I didn't implement `styleAsClassName` for `display` and `pointerEvents`. I'm sure we can solve that easily, but what what is likely to cause problems is how I handled inline style objects that don't come from `StyleSheet.create()`. Basically, on the fly, if an object style prop is encountered, i generate the class selector using JSS. At first, I thought it was as simple as that. But after a million re-renders, you will end up with many different class selectors on the page. Both JSS and Aphrodite seem to have solved this problem in various ways, so I'm sure we can learn from them, if not somehow offload the task completely on them.
