### ISSUE TITLE
React-native-paper TextInput show warning Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation. To resolve this, add `RCTAnimation` module to this app, or remove `useNativeDriver`.

### ISSUE THREAD

**Issue by threemak** [necolas/react-native-web#2455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

![React native web](https://user-images.githubusercontent.com/50118354/208622015-f832d5ae-946c-4d3e-9b4a-79c8d74956d5.png)

### Expected behavior

I check this file  https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/vendor/react-native/Animated/NativeAnimatedHelper.js
```
var _warnedMissingNativeAnimated = false;
export function shouldUseNativeDriver(config) {
  if (config.useNativeDriver == null) {
    console.warn('Animated: `useNativeDriver` was not specified. This is a required ' + 'option and must be explicitly set to `true` or `false`');
  }

  if (config.useNativeDriver === true && !NativeAnimatedModule) {
    if (!_warnedMissingNativeAnimated) {
      console.warn('Animated: `useNativeDriver` is not supported because the native ' + 'animated module is missing. Falling back to JS-based animation. To ' + 'resolve this, add `RCTAnimation` module to this app, or remove ' + '`useNativeDriver`. ' + 'Make sure to run `pod install` first. Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md');
      _warnedMissingNativeAnimated = true;
    }

    return false;
  }

  return config.useNativeDriver || false;
}
```
When I remove ! sign it disappear the warning 

### Steps to reproduce

 "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@expo/webpack-config": "^0.17.2",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.6",
    "D": "^1.0.0",
    "expo": "~47.0.8",
    "expo-font": "~11.0.1",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "jest": "^26.6.3",
    "jest-expo": "^47.0.1",
    "nativewind": "^2.0.0-next.65",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-fast-compare": "^3.2.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-paper": "^5.0.1",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-web": "~0.18.9",
    "resize-observer-polyfill": "^1.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@types/react": "~18.0.14",
    "@types/react-native": "~0.70.6",
    "autoprefixer": "^10.4.13",
    "babel-preset-expo": "^9.2.2",
    "cross-env": "^7.0.3",
    "postcss": "^8.4.20",
    "postcss-loader": "^4.2.0",
    "sharp-cli": "^2.1.0",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.6.3"
  },

### Test case

 https://codesandbox.io/s/6lx6ql1w5r

**Comment by necolas** [comment]
The warning let's you know that animations are using JS on web because there is no native driver. This isn't a bug. But a future version of Animated could potentially use Web Animations API for better performance
