### ISSUE TITLE
 Why does exports is not define appear after compiling react redux？What should I do？

### ISSUE THREAD

**Issue by Coder-hrl** [necolas/react-native-web#2457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

![企业微信截图_16716140578530](https://user-images.githubusercontent.com/80744835/208867807-23aaac40-9bb3-4a17-a67e-9c2df411ff13.png)
![企业微信截图_16716141061133](https://user-images.githubusercontent.com/80744835/208868389-657e63ed-61c1-4c86-9b83-56c9b1138376.png)
![企业微信截图_16716141465864](https://user-images.githubusercontent.com/80744835/208868405-754d2706-fcd7-4c5f-ba55-6de8ea0dfc5c.png)
I wrote this for some reason because of the plugin，It is mentioned in the react redux issue that this is the reason for the compiler

### Expected behavior

it should be able to display normally

### Steps to reproduce

11

### Test case

11

**Comment by Coder-hrl** [comment]
I searched the Internet for solutions, but I couldn't find them

**Comment by necolas** [comment]
The repo is not react-redux. Closing as unrelated and for failing to provide an acceptable issue test case etc
