### ISSUE TITLE
memoizedProps are not accessible within panResponder event handlers

### ISSUE THREAD

**Issue by eemebarbe** [necolas/react-native-web#2462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm currently using `event._targetInst.memoizedProps` to access the props passed to a component from within it's panResponder's event handlers. The _targetInst field isn't present on web, and although there is a field labeled `memoizedProps` nested under `event.target.__reactFiber[long hash id].memoizedProps`, the props passed to the component were not present.

### Expected behavior

memoizedProps should be accessible via panResponder's event object

### Steps to reproduce

1. Trigger a panResponder
2. Within onPanResponderGrant, access event._targetInst.memoizedProps
3. _targetInst will not be a valid field, and passed props will not be available elsewhere on the event object.

### Test case

https://codesandbox.io/s/pan-responder-forked-c0dwvl?file=/src/App.js

**Comment by necolas** [comment]
That is not a public or supported API, it's part of React internals. You shouldn't need to use the memoized props. Closing as "won't fix"
