### ISSUE TITLE
RTL not working 

### ISSUE THREAD

**Issue by NahumG10** [necolas/react-native-web#2466]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

The i18nmanager library do not working properly in react native web and i can't figure out how to work it out, any help how to make it work like in react native library? I tried adding styles like direction : RTL but no luck :(

Thanks

**Comment by necolas** [comment]
See https://necolas.github.io/react-native-web/docs/localization/

**Comment by NahumG10** [comment]
Hi, that doest seem to help..
I use React Native Paper library for all ui elements and even when I use dir="RTL" that doesn't seem to do anything.
When I assign transfom scaleX -1 style it flips the text direction but still not what I need.
I need the label text to be in the right side of the textInput, in the attached image it's located on the left.

Thanks

![image](https://user-images.githubusercontent.com/72704101/212535851-828eec66-b256-4086-842d-989b1088e898.png)

**Comment by joaoguilhermee** [comment]
> Hi, that doest seem to help.. I use React Native Paper library for all ui elements and even when I use dir="RTL" that doesn't seem to do anything. When I assign transfom scaleX -1 style it flips the text direction but still not what I need. I need the label text to be in the right side of the textInput, in the attached image it's located on the left.
> 
> Thanks
> 
> ![image](https://user-images.githubusercontent.com/72704101/212535851-828eec66-b256-4086-842d-989b1088e898.png)

@NahumG10 I have the same issue that you, have you fixed that?
