### ISSUE TITLE
Image onLoad event (ImageLoadEvent) object is empty in Chrome version 109.0.5414.87 on M1 Mac

### ISSUE THREAD

**Issue by musnit** [necolas/react-native-web#2469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In the latest version of Chrome on an M1 Mac (Version 109.0.5414.87 (Official Build) (arm64)), the Image onLoad event no longer contains all expected fields - for example, path and target are not available fields as expected in https://reactnative.dev/docs/image#imageloadevent.

https://codesandbox.io/s/priceless-feather-jk2mm7?file=/src/App.js:0-596

### Expected behavior

When logging the event, as in the example above, I expect the path and target fields to be on the nativeEvent object

### Steps to reproduce

See above sandbox

### Test case

https://codesandbox.io/s/priceless-feather-jk2mm7?file=/src/App.js:0-596

**Comment by kidroca** [comment]
AFAIK onload never matched the RN Image Load event 

And it shouldn't contain path or target, but `source` with uri, width and height

**Comment by kidroca** [comment]
I'm trying to make onload match the react-native Image interface here: https://github.com/necolas/react-native-web/commit/80ee858e743e1fa6e9ba2e62efbbc5e71fc29229

**Comment by musnit** [comment]
> AFAIK onload never matched the RN Image Load event
> 
> And it shouldn't contain path or target, but `source` with uri, width and height

I believe it did include a path/target or some reference the DOM node that caused the event

**Comment by kidroca** [comment]
> I believe it did include a path/target or some reference the DOM node that caused the event

Yes a `path` did exist at some point, and it was an array like `[img]` where `img` was the html element
It seems it was recently deprecated: https://chromestatus.com/feature/5726124632965120
This is not a bug in react-native-web or related to M1 / arm64

If you load an image the way react-native-web does, `target` would be `null`
```js
var img = new Image();
img.onload = e => {
    console.log(e)
    window.myEvent = e;
};

img.src = 'https://images.unsplash.com/photo-1481595357459-84468f6eeaac?dpr=1&auto=format&fit=crop&w=376&h=251&q=60&cs=tinysrgb';

myEvent.target // null
'path' in myEvent // false
'path' in Event.prototype // false
```

---

A `target` exposing the html element can be exposed from `onLoad`, but I think most people that need it would just pass a `ref` as it is the most common way to work with underlying elements

```jsx
const img = useRef();
return <Image ref={img} />
```

**Comment by musnit** [comment]
Ah thanks for digging in and finding the Chrome change! and yeah, ref fix seems more appropriate, thanks!

**Comment by xilin** [comment]
Hi @kidroca @musnit , img ref will be the parent view, it seems quite hacky to find img element inside the view then get the img properties. Can we consider to use the patch https://github.com/necolas/react-native-web/commit/80ee858e743e1fa6e9ba2e62efbbc5e71fc29229? Or is there any better way to get img's width/height ?

<img width="371" height="113" alt="Image" src="https://github.com/user-attachments/assets/0cdc08df-11cf-40bb-9726-fb527fc5d119" />

**Comment by kidroca** [comment]
Hi, @xilin 
> Hi [@kidroca](https://github.com/kidroca) [@musnit](https://github.com/musnit) , img ref will be the parent view, it seems quite hacky to find img element inside the view then get the img properties. Can we consider to use the patch [80ee858](https://github.com/necolas/react-native-web/commit/80ee858e743e1fa6e9ba2e62efbbc5e71fc29229)? Or is there any better way to get img's width/height ?

You can borrow this patch  https://github.com/Expensify/App/blob/b7436524af53a84f5471bc3af14390632500882e/patches/react-native-web%2B0.20.0%2B003%2Bimage-header-support.patch

and apply it using `npx patch-package`

It's based on this Pull Request: https://github.com/necolas/react-native-web/pull/2442

Then the `onLoad` prop would be called with image dimensions

---

The hacky solution with the ref might be less taxing overall, especially if you're not managing other patches with `patch-package`
