### ISSUE TITLE
Remove deprecated usage

### ISSUE THREAD

**Issue by jorbuedo** [necolas/react-native-web#2471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

AppState logs a deprecation notice on unmount:
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/AppState/index.js#L92

should be `.remove()` as indicated by the notice here:
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/vendor/react-native/emitter/_EventEmitter.js#L170

### Expected behavior

AppState shouldn't trigger a deprecation console.log

### Steps to reproduce

Linked on the description

### Test case

no

**Comment by necolas** [comment]
If you don't use the deprecated ` AppState.removeEventListener` API, you won't get the warning. Use the return value of the `add...` method.
