### ISSUE TITLE
can't select text when user open modal again

### ISSUE THREAD

**Issue by ntdiary** [necolas/react-native-web#2473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

when we close the modal and then open modal again, we can't select text.

https://user-images.githubusercontent.com/8579651/214192685-311fdd76-0140-45e8-817c-5c4c0cc15065.mp4

### Expected behavior

Text can always be selected

### Steps to reproduce

RNW (0.18.*):
1. try to select the text, it works well.
2. close the modal.
3. open the modal again.
4. try to select the text and text can't be selected.

### Test case

https://codesandbox.io/s/select-text-bp333o

### Additional comments

<img src="https://user-images.githubusercontent.com/8579651/213914277-3bef1b06-8d15-40fe-ab8b-3df3bd7318d9.png" width="500px" />

#### Above is a sketch of the dom structure of this case.
When we press the left mouse button on an `Element` (or `Text`) to start selecting text, the browser receives a mouse event and iterates through its ancestor elements to find **a focusable element**. If it finds one, it will try to focus on that element and **dispatch a focus event**. And if this **focus shift is blocked**, browser will eat the mouse event and prevent us from selecting text.

https://github.com/necolas/react-native-web/blob/ca152037bf5d268a5235fe6b500424a51c4a1b90/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L86-L88
https://github.com/necolas/react-native-web/blob/ca152037bf5d268a5235fe6b500424a51c4a1b90/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L144-L156

#### There are two hooks in the ModalFocusTrap component.
The first hook aims to refocus on an element inside the modal if a focus event occurs outside the modal.
The second hook aims to refocus element that triggered opening modal after closing it.

1. After the page is loaded, `document.activeElement` is `body`.
2. When we close the modal, the second hook adds the `tabindex="-1"` to the `body` element by `UIManager.focus`. And this attribute makes body **a focusable element**.
3. When we open the modal again and start selecting text, browser will **dispatch a focus event** on the `body` element. And the first hook will catch this `focus` event and then refocus on an element inside the modal. 
4. This refocusing behavior will cause browser to eat the mouse event and prevent us from selecting text.

### proposed solutions:
Although we can temporarily add a `focusable` to `View`.
In my humble opinion, maybe `lastFocusedElementOutsideTrap.focus()` or `attemptFocus(lastFocusedElementOutsideTrap)` are enough to the second hook.

https://github.com/necolas/react-native-web/pull/2468 also wants to resolve this issue.
But the `body` element actually is not a focusable element. So I don't think it's appropriate to add it into the `focusableElements`.
And if possible, it would be better to remind the developers of this risk in the doc or somewhere if they try to use `UIManager.focus(body)`.

Looking forward to your ideas. : )

**Comment by s77rt** [comment]
I would say fixing the `body` having the unnecessary `tabIndex` have to be done on `UIManager` as this will fix the issue in the entire repo and not having to check every `UIManager` call and replace it with a direct `element.focus`.

Also this means there won't be the need of "remind the developers of this risk in the doc or somewhere if they try to use UIManager.focus(body)"
