### ISSUE TITLE
RTL support with react native paper

### ISSUE THREAD

**Issue by NahumG10** [necolas/react-native-web#2475]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Hi there, I use React Native Paper library for all UI elements and even when I use dir="RTL" the elements are in opposite direction or misbehave.
When I assign transfom scaleX -1 style it mirrors the text but still not what I need.
I'm attaching images:
1+2) Switch goes bananas when turned on
3)The text label of text input should be on the right side of the top line.

Thanks

![image](https://user-images.githubusercontent.com/72704101/214328989-1df2bfd7-0316-4b5d-bf7d-6f1535c13c61.png)

![image](https://user-images.githubusercontent.com/72704101/214328917-ffec9cba-d08d-4781-b451-d96a39db7f4f.png)

![image](https://user-images.githubusercontent.com/72704101/214329092-f7c11db5-32a8-4a00-b83b-f4ef6c005e1a.png)

**Comment by necolas** [comment]
If there's a bug in RNWeb components you should open a bug with test case as required. If there's a bug in Paper you should use their issue tracker. Thanks
