### ISSUE TITLE
Voiceover reads out unwanted number '50' when accessibilityRole='adjustable'

### ISSUE THREAD

**Issue by ajit-wm** [necolas/react-native-web#2485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

**Problem**

Voiceover reads out the unwanted number '50' before the actual accessibility label when `accessibilityRole='adjustable'`. I've tried three different components(Pressable, View and Touchable components) with adjustable role and I could see the issue.

### Expected behavior

Voiceover should not read the unwanted number '50' before the provided accessibility label.

### Steps to reproduce

1. Turn VoiceOver on
2. Focus on the component which has 'adjustable' role, ex. Pressable

**Environment**

React Native Web(Version): 0.18
React(Version): 0.17
Browser: Safari/Chrome

### Test case

https://codesandbox.io/s/hungry-hoover-ufq3k1?file=/src/App.js

**Comment by necolas** [comment]
That's because the default range is 0-100 and the default starting position is 50. Adjustable/slider should be used with min/max/now values so a person knows where they are in the range https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role
