### ISSUE TITLE
jest-preset.js was removed in version 18

### ISSUE THREAD

**Issue by mahcloud** [necolas/react-native-web#2494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

As of version 18.0, jest-preset.js was removed from react-native-web.
Please advise. Was this intentional?
If not, can we please add it back?

### Expected behavior

Jest expects a jest-preset.js file if the node_module is defined as a jest preset.
My understanding, is we are supposed to use react-native-web as the preset.

### Steps to reproduce

Install 18.0 or above and set jest preset to react-native-web.

### Test case

NA

**Comment by necolas** [comment]
It was intentional and mentioned in the release notes. The preset is no longer needed. https://necolas.github.io/react-native-web/docs/setup/#jest
