### ISSUE TITLE
Ui behaves inconsistently across platforms. Some are against RN spec.

### ISSUE THREAD

**Issue by aliveornot** [necolas/react-native-web#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hi, thanks a lot for this great project! I found some inconsistency across platforms. It would be so much better if the basic UI components behave exactly the same across platforms.

1. **`<Text/>` element default prop issue**: The `<Text/>` element has `position: 'static'` as a default prop, which is against React Native specification.

2. **`flexDirection` and position properties inconsistency**: If a parent element has `flexDirection: 'row-reverse'` or `flexDirection: 'column-reverse'`, the `left`, `right`, `top`, `bottom`, `start`, and `end` properties behave differently(opposite way) on Android/iOS compared to web.

3. **`<Text/>` component style inheritance**: The `<Text/>` component should not inherit styles from its parent elements, but it does on web platform.

### Expected behavior

1. `<Text />` should have `position: 'relative'` as default
2. If  a component is a child component of a component with `flexDirection: 'something-reverse'`, then `'left'`,  `'right'`,  `'top'`,  `'bottom'`,  `'start'`,  `'end'` should behave the opposit way.
3. An outermost `<Text />` should not inherit styles from its parents 

### Steps to reproduce

I created a github repo to demonstrate these: 
https://github.com/aliveornot/rn-ui-consistency

### Test case

https://codesandbox.io/s/quizzical-hill-x6hgi7?file=/src/App.js

**Comment by necolas** [comment]
2 is a bug in React Native not web.

3 is only true for text-align, not all text style inheritance.

And 1 is easy to change. But you're incorrect in saying static is not supported in RN because it is.

**Comment by aliveornot** [comment]
Thanks for your fast response.

But I'm afraid your response to 1 is not true, the official doc says position is enum('absolute', 'relative')
https://reactnative.dev/docs/layout-props#position

And about 2, yeah it kinda sounds right. I expected the RNW behaviour and got surprised when I realized ios/aos behaved the other way.

**Comment by necolas** [comment]
The docs are out of date / missing info https://snack.expo.dev/5Lpci2KAd

**Comment by necolas** [comment]
Thanks for the clear issue and your attention to detail in finding these issues.

1 & 3 should be fixed by the [latest canary release](https://github.com/necolas/react-native-web/pull/2377): https://codesandbox.io/s/muddy-frog-o4pkid

Please let me know if you encounter any more issues

**Comment by aliveornot** [comment]
Wow that was fast, THANKS A LOT!!!

Yes I surely will, and have been always admiring your work. Thanks again!
