### ISSUE TITLE
Ideas for web version of `StyleSheet`

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#25]
### Problems

1. The current strategy of using a hand-rolled CSS library means that inline styles are used for any app-specific values (e.g., `borderColor: 'orange'`).
2. The hand-rolled library adds ~8KB to the gzipped size of the module. About 5KB is the CSS string, with the rest coming from the strings in the precomputed dictionary (using to map inline styles to class names)
3. There are cases where specificity bugs can result with shorthands, because some styles exist as classes but others end up as inline styles. For example: `{ border: 4, borderBottom: 0 }` => `<div class="borderBottom-0" style="border: 4px">` – the bottom border remains `4px`.
4. There's no `StyleSheet.create` shim.

### Possible solution 1

This describes a solution I hacked together this afternoon, minus the CSS vendor prefixing.

Make `StyleSheet.create` return the object of styles untouched:

```js
const StylesSheet = {
  create: (style: Object): Object => {
    // do things
    return style
  }
}
```

The React Component code remains the same, styles are plain objects that can be used as if they were inline styles. Rules can be nested. React's `style` prop is not overloaded to accept arrays.

```js
import React, { StyleSheet, View } from 'react-native-web'

const styles = StyleSheet.create({
  resizeMode: {
    contain: { backgroundSize: 'contain' },
    cover: { backgroundSize: 'cover' }
  },
  rounded: {
    borderRadius: 50
  }
})

export default const Example = ({ resizeMode, rounded }) => (
  <View style={
    ...styles.resizeMode[resizeMode],
    (rounded && styles.rounded)
  } />
)
```

`create` keeps track of every unique style declaration it sees, and generates a dictionary of declarations to unique class names.

```js
{
  'border: 1px 2px 3px 4px': '_rn02',
  'margin: 0 auto': '_rn01',
}
```

`StyleSheet` converts these unique declarations to vendor prefixed CSS code. When the app initializes in the browser, this is inserted into the `head` as a tracked `style` element. For server-side rendering something like `StyleSheet.renderToString` can be used to prerender the styles into the head.

`CoreComponent` replaces the current style dictionary with the one dynamically created by, and retrieved from `StyleSheet`.

**Result**

* Minimal inline style use in the browser.
* The vast majority of unique declarations are now backed by class names, only the _unique_ declarations created outside of `StyleSheet.create` end up as inline styles.
* Produces pretty much the least amount of CSS possible for the application UI. No specificity issues due to declaration-based selectors.
* No build step (maybe also a downside). There is no CSS to extract, it's generated at run time from the imported modules.
* You are still working with JS objects (divergence from React Native).
* Works with 0.14 stateless function components.
* Should support code-splitting by updating the injected `<style>` when new bundles are downloaded.
* Unlike css-loader strategies, the mapping is dynamic so we can produce any declarations from a fixed amount of code (rather than adding static lookup dictionaries for each new component).

**Drawbacks**

* All CSS prefixing must be done in react-native-web (must include all browser prefixed for server-side rendering case)
* Need to add units to some number values
* ?

cc @vjeux is this stupid? also, this project is fun, but am I wasting my time if you're making a web backend at Facebook?

**Comment by vjeux** [comment]
> this project is fun, but am I wasting my time if you're making a web backend at Facebook?

This is something I want us to tackle but no one is working on it. If we are to, I'm pretty sure that we're going to start from what you have already, no need to reinvent the wheel :)
