### ISSUE TITLE
Does it support the latest 'React Native'?

### ISSUE THREAD

**Issue by TrustTheBoy** [necolas/react-native-web#250]
MobileCampus@0.0.1 E:\MobileCampus
+-- UNMET DEPENDENCY react-native@0.33.0
+-- react-native-scrollable-tab-view@0.6.0
+-- react-native-sortable-listview@0.1.1
+-- react-native-tab-navigator@0.3.3
+-- react-native-viewpager@0.2.12
+-- react-native-web@0.0.49
| +-- animated@0.1.3
| | +-- es6-set@0.1.4
| | | +-- d@0.1.1
| | | +-- es5-ext@0.10.12
| | | +-- es6-iterator@2.0.0
| | | +-- es6-symbol@3.1.0
| | | `-- event-emitter@0.3.4
| | `-- tinycolor@0.0.1
| +-- inline-style-prefixer@2.0.4
| | +-- bowser@1.5.0
| | `-- hyphenate-style-name@1.0.2
| +-- lodash@4.16.6
| +-- UNMET PEER DEPENDENCY react@^15.3.2
| +-- react-dom@15.3.2
| `-- react-textarea-autosize@4.0.5
`-- react-timer-mixin@0.13.3

npm WARN react-dom@15.3.2 requires a peer of react@^15.3.2 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react" "react-native-web"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path E:\MobileCampus\node_modules\react-native
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'E:\MobileCampus\node_modules\react-native' -> 'E:\MobileCampus\node_modules\.react-native.DELETE'
npm ERR!     at moveAway (D:\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (D:\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'E:\MobileCampus\node_modules\react-native' -> 'E:\MobileCampus\node_modules\.react-native.DELETE'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'E:\MobileCampus\node_modules\react-native' -> 'E:\MobileCampus\node_modules\.react-native.DELETE'
npm ERR!     at moveAway (D:\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (D:\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'E:\MobileCampus\node_modules\react-native' -> 'E:\MobileCampus\node_modules\.react-native.DELETE'
npm ERR!     at Error (native) parent: 'MobileCampus' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\MobileCampus\npm-debug.log

**Comment by MoOx** [comment]
Your stack trace does not help at all. Clearly you need to read documentation yourself and check what is supported and what is not. In short it probably does not support all of RN out of the box.

**Comment by TrustTheBoy** [comment]
@MoOx Thank you very much for your reply

**Comment by necolas** [comment]
This looks a bit like a windows node/npm error tbh
