### ISSUE TITLE
Linking api is not compatible with RN

### ISSUE THREAD

**Issue by burakgormek** [necolas/react-native-web#2507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Linking api not compatible with RN latest version(or before).

React Native v0.65 release note has:
- Deprecate Linking.removeEventListener. Instead, call remove() on the subscription returned by Linking.addEventListener.

We should add `remove()` subscription method. Otherwise it will throw error on RNW.
I'm not sure if we still need to deprecate or remove `removeEventListener` after v0.19 publish.

### Expected behavior

Compatible Linking api with RN.

### Steps to reproduce

Open sandbox:
Click button.

### Test case

https://codesandbox.io/s/priceless-darwin-3p033u

**Comment by necolas** [comment]
A PR for this can use the same approach as was used in AppState: https://github.com/necolas/react-native-web/blob/0.18.0/packages/react-native-web/src/exports/AppState/index.js
