### ISSUE TITLE
Invalid props.style warnings on Text component

### ISSUE THREAD

**Issue by abdulrahuman5196** [necolas/react-native-web#2514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We are getting warnings of "invalid props supplied to Text component" on mobile platform(iOS and android) when passing 'cursor' or 'WebkitUserSelect' to Text component. 
For example, if we create a Text component with the following style
```
<Text
      style={{cursor: 'pointer'}}
>
{"Testing"}
</Text>
```
we get the below warning when running the same on mobile. And its working without warnings in web platform

<img width="150" alt="229727736-cd405658-cdac-4842-be0f-800fc0c41f2a" src="https://user-images.githubusercontent.com/46707890/234092886-7c180dfb-3eeb-4c58-a84c-12312dfbdde4.png">

### Expected behavior

Shouldn't provide any warnings and handle the exceptions gracefully

### Steps to reproduce

react-native-web - 0.18.15
env - mobile platform

Steps:
1. Add Text component to app and use specific styles like 'cursor' and 'WebkitUserSelect'
2. Run the application in mobile and notice warnings

### Test case

N/A

**Comment by necolas** [comment]
Those warnings are coming from React Native. If you're using the latest version of RN, you can pass `userSelect` styles to Text. I don't think `cursor` is supported, and you can use `Platform.select` to pass specific props or styles to the element only for certain platforms.

**Comment by abdulrahuman5196** [comment]
Thank you for quick response and closure @necolas
