### ISSUE TITLE
A template for react-native-web using libraries

### ISSUE THREAD

**Issue by MehmetKaplan** [necolas/react-native-web#2516]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

I am trying to implement a library that aims to be used both by native applications and we builds.

For this purpose I searched for any existing libraries but had no chance.

And I am currently clueless about how to generate such a library.

Is it possible to have a template (or a boilerplate code) s.t. using it, libraries, that can integrate with react-native and react-native-web together, can be generated easily?

**Comment by necolas** [comment]
Check out https://expo.dev/
