### ISSUE TITLE
Excessive Virtual DOM nesting

### ISSUE THREAD

**Issue by louisWebTv** [necolas/react-native-web#2522]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

I was exploring using this library for a TV app  to share across other platforms but I noticed some pretty severe performance problems between reactjs and react native for web. There was consistently a 50% performance penalty when using React Native components and I believe the culprit is the virtual dom that's generated. Investigating I found that there were much more "components" being generated as compared to using plain react. See example below:
<img width="436" alt="Screenshot 2023-05-16 at 11 15 53 AM" src="https://github.com/necolas/react-native-web/assets/134091893/df5fdd51-cbc9-4768-8d58-96f78f03c726">

The only way to resolve this was to use plain html which then prevents me from sharing components with other devices. I also notice even when i do this there's an extra "APP" component that is generated:
<img width="320" alt="Screenshot 2023-05-16 at 11 29 35 AM" src="https://github.com/necolas/react-native-web/assets/134091893/cb5d3ef0-421e-4681-9436-5ee4b4edc159">

I compared this with a react.js app i made nearly identical (note i dropped the Page and Tile list component doing it all in App level except for the Tile component, this was also done with react-native but there were still extra `view` components.)

<img width="287" alt="Screenshot 2023-05-16 at 11 16 00 AM" src="https://github.com/necolas/react-native-web/assets/134091893/3ec26368-afb6-466b-8ec2-4c5d328e7a31">

As for testing this I created identical apps in both react.js and react-native for web, Both using a spatial-navigation library (norigin). I tested on various devices by creating a list of 500 or 1200 tiles each handling focus for navigation in the same way and updating their background when focused. I saw a difference of 30% CPU utilization 6x throttled on an M1 in react js vs 50% cpu utilization in react-native throttled 6x on an M1.

Even my tests on various hardware continue this trend of 50+% cpu utilization, making it unusable. There was also an added expense  of 40% if i attempted to use things like ScrollView or FlatList. 

I understand that this library is being used by large companies, and this performance penalty is almost negligible on a typical web desktop/laptop. But im curious if this is an existing problem that is hard/impossible to solve or im missing a crucial step when making components in this library

**Comment by necolas** [comment]
No way to know more without example component trees. But it looks like you're using different tree structures. And you're using FlatList it's going to have a bunch of wrapper elements around each of the rendered items. So I suggest not using FlatList

**Comment by louisWebTv** [comment]
Sure @necolas , here is the example  TILE component:

```
        <View ref={ref} style={tileStyles.container}>
            <View style={[tileStyles.tile, ...(focused ? [{backgroundColor: 'red'}]: [])]}>
                <Text>
                    {number}
                </Text>
            </View>
        </View>
```

The resulting Component rendered:

![image](https://github.com/necolas/react-native-web/assets/134091893/1d169b6b-e404-45ff-b9b0-20726e0947c3)


vs Reactjs equivalent Tile component:

```
        <div ref={ref} className="tileWrapper">
            <div className="tile" style={{backgroundColor: focused ? 'red' : 'grey'}}>
                <div>
                    {number}
                </div>
            </div>
        </div>
```

The generated component tree:
<img width="173" alt="image" src="https://github.com/necolas/react-native-web/assets/134091893/db077188-1293-4c33-bf8f-5193e120f501">

**Comment by louisWebTv** [comment]
Note that both have identical js logic regarding spatial navigation, state, and focus
