### ISSUE TITLE
HSL color type is not supported

### ISSUE THREAD

**Issue by MorningLit** [necolas/react-native-web#2525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

HSL color is supported in react-native, but not in react-native-web

### Expected behavior

I expected HSL to be supported in react-native-web

### Steps to reproduce

1. Create a expo project and set up for react-native-web,
2. Launch the app on the web and realise that HSL is not supported.

### Test case

https://codesandbox.io/s/recursing-brattain-eyxjm3?file=/src/App.js

**Comment by necolas** [comment]
If you add commas between the values, it will work.

I'll need to update normalizeColor to support no-comma syntax: https://github.com/facebook/react-native/commit/ac1fe3b7eb8e16f5feddeeac846ff70080dc119e

**Comment by makkarMeenu** [comment]
@necolas Can I work on this?

**Comment by makkarMeenu** [comment]
> If you add commas between the values, it will work.
> 
> I'll need to update normalizeColor to support no-comma syntax: [facebook/react-native@ac1fe3b](https://github.com/facebook/react-native/commit/ac1fe3b7eb8e16f5feddeeac846ff70080dc119e)

@necolas Can I work on this?
