### ISSUE TITLE
Cursor moves with each character clicked after max character limit reached

### ISSUE THREAD

**Issue by payal-lathidadiya** [necolas/react-native-web#2526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Cursor moves for every character clicked (but no characters are added to the name string)

https://github.com/necolas/react-native-web/assets/130229379/de556321-ff6c-4a7c-949a-cbb2f9c62604

### Expected behavior

Nothing should happen when clicking any key after max length limit is reached.

### Steps to reproduce

1. Navigate to TextInput Example code sandbox demo
1. Go to Input with max length 
1. Type text until max length 
1. Go to the last character and make sure you can't add any more characters
1. Click on the middle of the long string to put the cursor at the middle of text
1. Click on any character on your keyboard

### Test case

https://42y1lw.sse.codesandbox.io/text-input

**Comment by necolas** [comment]
This is standard browser behaviour and I see the same thing with native input and maxlength

**Comment by payal-lathidadiya** [comment]
> This is standard browser behaviour and I see the same thing with native input and maxlength

is it specific to platform?

doesn't happen on chrome desktop?

is there a way we could keep behavior consistent across device and platform? I mean nothing should happen when more keys pressed after max length reached

**Comment by necolas** [comment]
I'm not going to modify the browser default behavior. You can open an issue against Chromium for Android platform if you feel strongly about it.
