### ISSUE TITLE
Image array of styles where one contains `$css` and another is just a plain style makes the plain style work like css

### ISSUE THREAD

**Issue by natew** [necolas/react-native-web#2527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Passing this style object:

```
[
    {
        "transition": "all ease-in 500ms"
    },
    {
        "$$css": true,
        "t_will-mount": "t_will-mount",
        "is_Image": "is_Image",
        "_o-0": "_o-0",
        "_zi-1": "_zi-1",
        "_pos-relative": "_pos-relative",
        "_transform-231611629": "_transform-231611629"
    }
]
```

Will result in a className:

```
css-view-175oi2r r-flexBasis-1mlwlqe r-overflow-1udh08x r-zIndex-417010 all ease-in 500ms  is_Image _o-1 _zi-1 _pos-relative _transform-164621819
```

Where you can see `all ease-in 500ms` is put into the actual className, whereas I'd expect the `$css` to only apply to the second style object.

### Expected behavior

Only `$css` turns into CSS.

### Steps to reproduce

```
<Image style={[
    {
        "transition": "all ease-in 500ms"
    },
    {
        "$$css": true,
        "t_will-mount": "t_will-mount",
        "is_Image": "is_Image",
        "_o-0": "_o-0",
        "_zi-1": "_zi-1",
        "_pos-relative": "_pos-relative",
        "_transform-231611629": "_transform-231611629"
    }
]} />
```

### Test case

https://codesandbox.io/s/sweet-lamarr-bsf0gr?file=/src/App.js

**Comment by necolas** [comment]
This should be fixed by https://github.com/necolas/react-native-web/pull/2531 which removes the internal `StyleSheet.flatten` call. One potential regression from this patch is that `boxShadow` can't be passed to `Image`.
