### ISSUE TITLE
[Animated] Cannot animate string transform properties (v0.19)

### ISSUE THREAD

**Issue by Aashu-Dubey** [necolas/react-native-web#2528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

It seems that after rn-web v0.19, it is recommended to use space-separated string functions on web instead of array, as we get these deprecation warnings

<img width="370" alt="image" src="https://github.com/necolas/react-native-web/assets/46301285/ccf3116d-c7db-48de-8c98-58aa6e974ff0">

though they work fine on web, but we can't apply animations using them as of now, as I'm getting this error even when using the styles without animation on any `Animated` component
<img width="909" alt="image" src="https://github.com/necolas/react-native-web/assets/46301285/e006a7bf-85fc-4184-a450-2c4e275feaac">

### Expected behavior

animation on these new string functions should work fine, as it is working in case of array transform right now.

### Steps to reproduce

You can clearly see the issue in the attached sandbox.

For a bigger example, I had the issue when I was recently trying to fix these warning on [this sample app](https://gitlab.com/ashud/rn_travel_app) ([Web Demo](https://ngefly.vercel.app/)), there are few places where I'm using these styles and they are working fine, but can't use them where animations are needed.

### Test case

https://codesandbox.io/s/rn-web-string-transform-bug-g1eqvy

### Additional comments

Currently I'm using `...Platform.select({ web : { transform: 'rotate(45deg)' } })` approach to apply these styles, as they don't yet seems to be cross compatible with native platforms.

Do let me know if there's any particular approach to apply animations here or if this is something to be fix in future version of the package.

Thanks!

**Comment by chrispader** [comment]
Having the same issue in `>=0.19`

**Comment by necolas** [comment]
This is a bug in React Native too [34425](https://github.com/facebook/react-native/issues/34425#issuecomment-1608512159)

**Comment by dan-doyon-endear** [comment]
Here is patch that works for us in interim

```
diff --git a/node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedTransform.js b/node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedTransform.js
index 66072d9..b92ada1 100644
--- a/node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedTransform.js
+++ b/node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedTransform.js
@@ -16,7 +16,7 @@ import NativeAnimatedHelper from '../NativeAnimatedHelper';
 class AnimatedTransform extends AnimatedWithChildren {
   constructor(transforms) {
     super();
-    this._transforms = transforms;
+    this._transforms = transforms || [];
   }
   __makeNative() {
     this._transforms.forEach(transform => {

```

**Comment by necolas** [comment]
That doesn't "work", it just skips over the issue

**Comment by dan-doyon-endear** [comment]
> That doesn't "work", it just skips over the issue

Fair enough, we're not doing a lot with tranforms and it enabled us to migrate to latest version.

**Comment by dan-doyon-endear** [comment]
I obviously didn't make a great attempt to debug the react-native-animated code, but one thing I just noticed is that in the `useAnimatedStyle` hook its `transform` not `transforms`. Not sure if that is by design but just pointing it out. This is from react-native-animated 2.14.4.

```  // Animated style
  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateY: offset.value }],
    };
  });
  ```

**Comment by necolas** [comment]
In the test case, you're trying to stringify an animated object:

```
web: { transform: `rotate(${rotate})` }
```

That will never work.

What you can do is interpolate the whole string value (which will work in RN), or animate only the`rotate` property (which will work only on web for now)

```
   const rotate = anim.current.interpolate({
     inputRange: [0, 1],
     outputRange: ["rotate(0deg)", "rotate(45deg)"]
   });
```

Or

```
web: { rotate: rotate }
```

**Comment by dan-doyon-endear** [comment]
> const animatedStyles = useAnimatedStyle

Sorry, I should've been more clear. The provided example is only used on native (we are literally all in one repo for now), the point was the use of `transform` instead of `transforms`. But thanks for the tips.

**Comment by getusha** [comment]
>What you can do is interpolate the whole string value (which will work in RN)

@necolas it is not working on `Animated.View` 

![Screenshot 2023-08-26 at 1 28 34 PM](https://github.com/necolas/react-native-web/assets/75031127/835332fd-3068-4df8-be7a-d70c655d5de0)

It appears to be functioning correctly with the `View` component; however, it seems that it is not supported within the `Animation.View`

```js
<Animated.View style={ {transform: 'scale(2)'}} >
    ....
</Animated.View>
```

**Comment by Gregoirevda** [comment]
Is there a way to combine 2+ animated values into a single transform string?

```js
  const translateX = Animated.divide(Animated.multiply(progress, progressBarWidth), 2).interpolate({
    inputRange: [0, 1],
    outputRange: ['translateX(0)', 'translateX(1)'],
  });

  const scaleX = Animated.multiply(progress, progressBarWidth).interpolate({
    inputRange: [0, 1],
    outputRange: ['scaleX(0)', 'scaleX(1)'],
  });
```

**Comment by kevtronkrueger** [comment]
I'll second the question from @Gregoirevda 
I do not understand what the intended future-friendly implementation is for 2+ animated objects on a single Animated.View.
