### ISSUE TITLE
Add class name into "View" tag in react native web

### ISSUE THREAD

**Issue by PurpleMonkey729** [necolas/react-native-web#2535]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Hello, everyone.
I want to add class name into "View" tag in react native web.
What is the most important is to not use Stylesheet.
I typed the code like following:

`<Image className="img_item_active" source={img_icon} style={styles.img_icon]} />`

But it didn't work.
So I covered this part with "div" tag like following.

`<div className="img_item_active"><Image source={img_icon} style={styles.img_icon]} /></div>`

But as I see, it's not perfect coding.
I want to add class name in "View" absolutely.
Is there any other method?
Please help me.

**Comment by necolas** [comment]
This has been asked and answered before. Please search the closed issues
