### ISSUE TITLE
Cannot add type block to nginx.conf

### ISSUE THREAD

**Issue by bmbmjmdm** [necolas/react-native-web#2539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am trying to add a type config block to the `nginx.conf` file. Currently there does not seem to be any way to do that that gets picked up by nginx. I added the following block:

`
types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml rss;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/javascript                js mjs;
    text/plain                            txt;
    text/x-component                      htc;
    text/mathml                           mml;
    image/png                             png;
    image/x-icon                          ico;
    image/x-jng                           jng;
    image/vnd.wap.wbmp                    wbmp;
    application/java-archive              jar war ear;
    application/mac-binhex40              hqx;
    application/pdf                       pdf;
    application/x-cocoa                   cco;
    application/x-java-archive-diff       jardiff;
    application/x-java-jnlp-file          jnlp;
    application/x-makeself                run;
    application/x-perl                    pl pm;
    application/x-pilot                   prc pdb;
    application/x-rar-compressed          rar;
    application/x-redhat-package-manager  rpm;
    application/x-sea                     sea;
    application/x-shockwave-flash         swf;
    application/x-stuffit                 sit;
    application/x-tcl                     tcl tk;
    application/x-x509-ca-cert            der pem crt;
    application/x-xpinstall               xpi;
    application/zip                       zip;
    application/octet-stream              deb;
    application/octet-stream              bin exe dll;
    application/octet-stream              dmg;
    application/octet-stream              eot;
    application/octet-stream              iso img;
    application/octet-stream              msi msp msm;
    audio/mpeg                            mp3;
    audio/x-realaudio                     ra;
    video/mpeg                            mpeg mpg;
    video/quicktime                       mov;
    video/x-flv                           flv;
    video/x-msvideo                       avi;
    video/x-ms-wmv                        wmv;
    video/x-ms-asf                        asx asf;
    video/x-mng                           mng;
}
`

both inside and outside the `server` block inside `nginx.conf`, but it doesn't seem to take. My `index.mjs` is still being served as `text/html`

### Expected behavior

`type` is respected in `nginx.conf`

### Steps to reproduce

Start a new project
Add type block to nginx.conf
See that your `index.js` is still served as `index/html`

### Test case

NA

**Comment by bmbmjmdm** [comment]
@necolas Why is this marked as completed? React-native-web still does not respect nginx type configs

**Comment by necolas** [comment]
This library is just a React DOM UI library
