### ISSUE TITLE
Support virtualkeyboardpolicy

### ISSUE THREAD

**Issue by imaspen** [necolas/react-native-web#2548]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

For our electron app on Windows, we need access to the [VirtualKeyboard API](https://developer.mozilla.org/en-US/docs/Web/API/VirtualKeyboard_API). Namely, the [virtualkeyboardpolicy](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#virtualkeyboardpolicy) prop for text inputs that lets an app prevent the on screen keyboard from appearing when set to manual.
We have created a patch with [patch-package](https://www.npmjs.com/package/patch-package) that enables this in our code base, but it might be worth bringing into the library itself.

**Comment by necolas** [comment]
Create a PR and I'll take a look. Thanks
