### ISSUE TITLE
Pressable with button role does not fire onPress on space key press

### ISSUE THREAD

**Issue by zoontek** [necolas/react-native-web#2560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hi! 👋

We noticed something strange lately: when using keyboard navigation with `Pressable` using `role="button"`, using the space bar to press only trigger the visual focus (`pressed` is `true` in `style`), but doesn't fire `onPress`. When using the `enter` key, both are working.

### Expected behavior

`onPress` should be fire, in a similar way as pressing the enter key

### Steps to reproduce

- Focus on a `Pressable` with a button role using keyboard navigation
- Use the space key to press: visually it's `pressed`, but `onPress` is not fired

### Test case

https://codesandbox.io/p/sandbox/holy-darkness-pfk6m8?file=%2Fsrc%2Fmain.tsx%3A17%2C29

### Additional comments

I think it might happen since it's now using the HTML button element underneath.

**Comment by necolas** [comment]
This seems to be how Pressable has worked for a while. I tested 0.17 and 0.18 and it behaved the same. https://codesandbox.io/s/dazzling-greider-y38h47?file=/package.json

I couldn't change package versions in your non-standard test case.

**Comment by zoontek** [comment]
That's the new VM in codesandbox, to switch package versions you can update them in package.json and run yarn in the terminal, it truly works like locally.

### With RNW 0.17

Playground: https://codesandbox.io/s/admiring-elion-lgy9zw?file=/src/App.js

#### with accessibilityRole="button" (`role` wasn't supported at this time)

- On `space`: `pressed` style applied ✅ + `onPress` fired ✅
- On `enter`: `pressed` style applied ✅ + `onPress` fired ✅

#### without accessibilityRole="button"

- On `space`: `pressed` style not applied ❌ + `onPress` not fired ❌
- On `enter`: `pressed` style applied ✅ + `onPress` fired ✅

### With RNW 0.19

Playground: https://codesandbox.io/s/optimistic-hypatia-3mdyyq?file=/src/App.js

#### with role="button"

- On `space`: `pressed` style applied ✅ + `onPress` not fired ❌ _<- this is the broken case_
- On `enter`: `pressed` style applied ✅ + `onPress` fired ✅

#### without role="button"

- On `space`: `pressed` style not applied ❌ + `onPress` not fired ❌
- On `enter`: `pressed` style applied ✅ + `onPress` fired ✅

**Comment by necolas** [comment]
I think this will fix the issue: #2563
Let me know

**Comment by zoontek** [comment]
@necolas I confirm, it fixes it. Both space and enter fire `onPress` + apply `pressed` style now

https://github.com/necolas/react-native-web/assets/1902323/6302cca4-ffc9-4a71-91d4-c439ff8487fc
