### ISSUE TITLE
Unable to resolve "react-native-web/dist/exports/PermissionsAndroid"

### ISSUE THREAD

**Issue by htran844** [necolas/react-native-web#2577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I run web with expo.
I ran _expo prebuild_ to create native folder android and ios.
I have faced error when I use `import { PermissionsAndroid } from 'react-native';` 

I tried `if (Platform.OS != 'web')` but still not work
Thanks for support!

log: 
_Unable to resolve "react-native-web/dist/exports/PermissionsAndroid" from "services/notification/NotificationsHandler.ts"_

_Metro error: Unable to resolve module react-native-web/dist/exports/PermissionsAndroid from /Users/viethoang/Documents/dichhannom/hannomapp/services/notification/NotificationsHandler.ts: react-native-web/dist/exports/PermissionsAndroid could not be found within the project or in these directories:_

My code just:
```
import { PermissionsAndroid } from 'react-native';

const requestUserPermissionAndroid = () => {
    if (Platform.OS == 'android') {
        PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);
    }
}
```
and use that:
```
if (Platform.OS != 'web') {
      requestUserPermissionAndroid()
    }
```

### Expected behavior

I want web can run well

### Steps to reproduce

I have faced error when I use `import { PermissionsAndroid } from 'react-native';` 

### Test case

/

**Comment by comertcimen** [comment]
You can create a postInstall script, create PermissionsAndroid folder under node_modules/react-native-web/dist/exports and put index.js file with content module.exports = {}

**Comment by necolas** [comment]
This API was removed from web along with all other platform-specific exports. It should only be used in `.native.js` or `.android.js` files
