### ISSUE TITLE
upgrading to version 0.13.0 give me an error while running my test script by jest

### ISSUE THREAD

**Issue by Diaa-Ghonim** [necolas/react-native-web#2578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

after I upgraded the react-native-library to the release 0.13.0, I encounterd an issue whe I run my test cases.

this is the issue 

```
@nursery-story/nursery-app:  FAIL  __tests__/utils/registers-main/home-context-utils.test.ts
@nursery-story/nursery-app:   ● Test suite failed to run
@nursery-story/nursery-app:     Cannot find module '../dist/cjs/modules/StyleSheet/ReactNativePropRegistry' from 'node_modules/react-native-web/jest/setup.js'
@nursery-story/nursery-app:       at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
@nursery-story/nursery-app:       at Object.<anonymous> (node_modules/react-native-web/jest/setup.js:10:6)
```

### Expected behavior

it should be working fine after the upgrading

### Steps to reproduce

.

### Test case

.

**Comment by necolas** [comment]
We're on version 0.19. Older versions are not supported
