### ISSUE TITLE
getting error while using react navigation drawer

### ISSUE THREAD

**Issue by mubashiralisiddiqui** [necolas/react-native-web#2579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

when I tried to use a drawer in my react native project (react-native-cli) getting so many errors on web
here is my packag.json I am using latest version of react native and react native web
<img width="875" alt="image" src="https://github.com/necolas/react-native-web/assets/16689214/bb50dc03-eb0e-4150-9692-8b63d757dd61">
and these are the errors

<img width="1427" alt="image" src="https://github.com/necolas/react-native-web/assets/16689214/c39854fe-1f50-42e0-843c-6d9dc9991949">

when i remove drawer code from my app it starts working but when i tried to import drawer it gives error

here is my routing code
<img width="698" alt="image" src="https://github.com/necolas/react-native-web/assets/16689214/5d87b4f4-af15-4ee0-a7cb-57c9d2c78ee8">

### Expected behavior

it should work

### Steps to reproduce

create a new porject with react native cli install react nativ web and react navigation with drawer you will get the error

### Test case

no link

**Comment by necolas** [comment]
Sounds like you should first be reporting the issue to `@react-navigation`. AFAIK there is no issue using `Animated` from RNWeb.
