### ISSUE TITLE
could not load codegenNativeComponent

### ISSUE THREAD

**Issue by xiongemi** [necolas/react-native-web#2583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

when using react-native-svg library with react-native-web, i got this error with vite build:
```
[vite:load-fallback] Could not load react-native-web/Libraries/Utilities/codegenNativeComponent (imported by node_modules/react-native-svg/lib/module/fabric/RectNativeComponent.js): ENOENT: no such file or directory, open 'react-native-web/Libraries/Utilities/codegenNativeComponent'
```

i think in react-native-svg, it has code:
```
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent';
export default codegenNativeComponent('RNSVGRect');
//# sourceMappingURL=RectNativeComponent.js.map
```

when i change the resolve alias in vite, it replace the import to
```
react-native-web/Libraries/Utilities/codegenNativeComponent
```
which does not exist in react native web

### Expected behavior

the import `import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent';` should work after change the alias to react-native-web

there should be a file in react-native-web/Libraries/Utilities/codegenNativeComponent

### Steps to reproduce

- add vite.config in the react-native app
- in the vite.config, add the resolve.alias:
```
export default defineConfig({
  resolve: {
    alias: [
      {
        find: 'react-native',
        replacement: 'react-native-web'
      },
    ],
  },
```
- run vite build

### Test case

https://codesandbox.io/s/wizardly-frog-zn2rrw?file=/src/App.js

**Comment by necolas** [comment]
1. Importing from private paths of RN is not supported
2. You can't run code like `codegenNativeComponent` on web
