### ISSUE TITLE
TextInput Loses Focus on Each Keystroke

### ISSUE THREAD

**Issue by grant-13** [necolas/react-native-web#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am trying to use TextInput to create a text filter on an array of objects. The issue comes when I use a FlatList to try to show the newly filtered array. The issue is after every keystroke, the TextInput component loses focus. I tried testing on an iOS device with Expo Go, and the issue does not exist there. This issue is exclusive to Web development

`// PlayerSearch.tsx

import {
  FlatList,
  Pressable,
  StyleSheet,
  Switch,
  Text,
  View,
} from "react-native";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../../store";
import {
  setListOfPlayers,
  setSelectedPlayer,
} from "../../store/selected-players-slice";
import { Player } from "../../common/types";

export default function PlayerSearch() {
  const { textInput } = useSelector((state: RootState) => state.playerSearch);
  const filteredPlayers = PLAYERS.filter((player) =>
    player.name.toLowerCase().includes(textInput.toLocaleLowerCase())
  );

  return (
    <View style={{ backgroundColor: "red" }}>
      <FlatList
        data={filteredPlayers}
        renderItem={({ item }) => <Text>{item.name}</Text>}
        keyExtractor={(item) => item.id}
      />
    </View>
  );
}`

`// SearchFilters.tsx

import { StyleSheet, Text, TextInput, View } from "react-native";
import { useDispatch, useSelector } from "react-redux";
import { setTextInput } from "../../store/player-search-slice";
import { RootState } from "../../store";

export default function SearchFilters() {
  const { textInput } = useSelector((state: RootState) => state.playerSearch);
  const dispatch = useDispatch();

  const changeTextHandler = (text: string) => {
    dispatch(setTextInput(text));
  };

  return (
    <View style={styles.searchFilters}>
      <TextInput
        style={styles.input}
        onChangeText={changeTextHandler}
        value={textInput}
        placeholder="Search Player by Name"
      />
    </View>
  );
}`

### Expected behavior

When using TextInput and FlatList to display a filtered (based on the text input) array, the TextInput should remain in focus for each keystroke.

### Steps to reproduce

Using Google Chrome
Managed using expo:
 - Started development server with `expo start --web`
Dependancies:
 - "expo": "~49.0.13"
 - "react-native": "0.72.5"
 - "react-native-web": "~0.19.6"

### Test case

none

**Comment by grant-13** [comment]
There was a styling error that caused the text input to unfocus.

**Comment by Daavidaviid** [comment]
@grant-13 you minding sharing which style property ?
