### ISSUE TITLE
Pressable triggers onPress twice, when activated via Enter key and set to disabled

### ISSUE THREAD

**Issue by efoken** [necolas/react-native-web#2605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When using the `onPress` prop on the `Pressable` component and setting it to `disabled` inside the `onPress`-function, the function will be called a second time. But only when activating the button via the <kbd>Enter</kbd> key.

First time `onPress` is called when pressing the <kbd>Enter</kbd> key down and the second time it is called when releasing the <kbd>Enter</kbd> key. I created a test case which demonstrates this behaviour.

### Expected behavior

`onPress` is only called once, like it is when using <kbd>Space</kbd> key oder pressing the button with the mouse.

### Steps to reproduce

1. Use `<Pressable role="button">` and apply an `onPress` handler to it
2. Set a `disabled` state inside the `onPress` handler
3. Set the `disabled` prop using the state on your `Pressable`
4. Put some `console.log` inside the `onPress` handler
5. Activate your button using the keyboard, pressing the <kbd>Enter</kbd> key
6. See your `console.log` twice in the console

### Test case

https://codesandbox.io/s/react-native-web-on-press-disabled-77crwk

**Comment by seemX17** [comment]
Is there a workaround for this till the fix is provided?

**Comment by jkjustjoshing** [comment]
@necolas any idea when a new release will go out that includes this fix?

**Comment by necolas** [comment]
It's been out for a week already 54c14d64dabd175e8055e1dc92e9196c821f9b7d
