### ISSUE TITLE
Breaks with libraries that use NativeModules, like react-native-randombytes

### ISSUE THREAD

**Issue by Distance71** [necolas/react-native-web#2618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Every libraries using NativeModules breaks

### Expected behavior

It should export as least a mock, to be compatible with RN apps

### Steps to reproduce

I created a tiny sandbox to reproduce

### Test case

https://codesandbox.io/p/sandbox/gracious-mclean-kmynms

**Comment by necolas** [comment]
You can't use native code modules in web apps

**Comment by Distance71** [comment]
@necolas what alternative do you suggest for compatibility purposes?

**Comment by necolas** [comment]
https://necolas.github.io/react-native-web/docs/multi-platform/#web-specific-code
