### ISSUE TITLE
Button component: Add to web support

### ISSUE THREAD

**Issue by calvintychan** [necolas/react-native-web#262]
React Native introduced it's own Button component in [0.37.0](https://github.com/facebook/react-native/commit/2ae73ffa002221fde8011b012ea5e57e22979232)

The implementation is straight forward. Thought on implementing the same component in React Native Web?

**Comment by necolas** [comment]
Added to #91

**Comment by calvintychan** [comment]
Thanks @necolas, I will contribute to it.
