### ISSUE TITLE
No documentation about shadow* style props being deprecated

### ISSUE THREAD

**Issue by jkjustjoshing** [necolas/react-native-web#2620]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

I'm getting the following warning in my console

<img width="755" alt="image" src="https://github.com/necolas/react-native-web/assets/813192/d8e70b38-b668-4efa-a3dd-892055306e67">

However, when I search this repo and the React Native docs, I can't find anything giving me more information about this, or telling me which versions this impacts. Is this a React Native thing or a React Native Web thing?

It seems like this warning was introduced in [this commit](https://github.com/necolas/react-native-web/commit/bc6e02e9d07f65ced209c8bc54c6ea8946e684d1) as part of [this PR](https://github.com/necolas/react-native-web/pull/2377), but I don't see any additional discussion of these style properties there either.

**Comment by necolas** [comment]
The warning is coming from react-native-web. The `shadow*` props are iOS-only in React Native, and have very different results form web `boxShadow` - it's not safe to rely on `shadow*` props for any platform other than iOS. You should use `boxShadow` and generally assume you should only use web CSS properties in react-native-web, many of which have been polyfilled in React Native this year.

**Comment by stellarskye** [comment]
I dont understand, `boxShadow` is not recognized in React-Native?

**Comment by jkjustjoshing** [comment]
Thanks for the link, @stellarskye.

For anyone coming across this ticket looking for a way to stop Typescript errors, here is documentation that may help https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors
