### ISSUE TITLE
Confusion with `@react-native/normalize-colors` vs. `@react-native/normalize-color`

### ISSUE THREAD

**Issue by efoken** [necolas/react-native-web#2629]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

I think `@react-native/normalize-colors` (with S) should be used as a dependency, because `@react-native/normalize-color` seems to be the old package. Was probably renamed?!

**Comment by necolas** [comment]
Oh, yes probably. If anyone wants to fix that in a PR, would be great
