### ISSUE TITLE
react-native-web Server API Support

### ISSUE THREAD

**Issue by JegatheeshSelvam** [necolas/react-native-web#2631]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Please help me

How to configure my project:- 

Link:- https://necolas.github.io/react-native-web/docs/rendering/#server-api

=============================================================================
**Server API:-**

**Server-side rendering to HTML is supported using AppRegistry:**

import App from './src/App';
import ReactDOMServer from 'react-dom/server';
import { AppRegistry } from 'react-native-web';

// register the app
AppRegistry.registerComponent('App', () => App);

// prerender the app
const { element, getStyleElement } = AppRegistry.getApplication('App', { initialProps });
// first the element
const html = ReactDOMServer.renderToString(element);
// then the styles (optionally include a nonce if your CSP policy requires it)
const css = ReactDOMServer.renderToStaticMarkup(getStyleElement({ nonce }));

// example HTML document string
const document = `
<!DOCTYPE html>
<html style="height:100%">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
${css}
<body style="height:100%; overflow-y:hidden">
<div id="root" style="display:flex; height: 100%">
${html}
</div>
<script nonce="${nonce}" src="${bundlePath}"></script>

============================================================================

Example code or GitHub link is useful for me.

Eagerly waiting for your support.

**Comment by necolas** [comment]
The code example is in the docs. Sorry, I can't provide further support if you're not familiar with server development and debugging issues
