### ISSUE TITLE
Text component inline style overrides global style [color]

### ISSUE THREAD

**Issue by JinYuSha0** [necolas/react-native-web#2634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

![image](https://github.com/necolas/react-native-web/assets/20939091/e5df7b1d-36d1-4d29-9af9-4e014fb540dc)
![image](https://github.com/necolas/react-native-web/assets/20939091/054f4ebf-4d36-44d8-b000-b204313d28af)

### Expected behavior

Why text component's color defaults to black instead of inheriting
This is incompatible with browser specifications
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Text/index.js#L189

### Steps to reproduce

Add global styles and create text components

### Test case

https://codesandbox.io/p/sandbox/fervent-lichterman-jv4n25

### Additional comments

In fact, the performance of react-native on Android follows AppTheme, and iOS has Appearance, so it is more reasonable to set it as inheritance.

**Comment by JinYuSha0** [comment]
I submitted this PR [#2635]

**Comment by necolas** [comment]
This is how Text works in react native

**Comment by JinYuSha0** [comment]
Well, if anyone encounters this problem, say you want to modify the font color globally in react-native-web, or switch themes, you can try this solution:

```jsx
import {Platform, Text, View} from 'react-native';
import React from 'react';
import RootStack from './src/navigation/rootStack';

function App(): React.JSX.Element {
  const content = (
    <AppProvider>
      <RootStack />
    </AppProvider>
  );
  if (Platform.OS === 'web') {
    // Why wrapped by Text component?
    // Create a TextAncestorContext, make the color of the child Text component inherited
    // Related issues: https://github.com/necolas/react-native-web/issues/2634
    return (
      <Text style={{flex: 1, display: 'flex', color: 'your target color'}}>
        <View
          style={{
            flex: 1,
          }}>
          {content}
        </View>
      </Text>
    );
  }
  return content;
}

export default App;
```
