### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by gavrilikhin-d** [necolas/react-native-web#2641]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Add types to the library. 

There are several mismatches in API, that should be expressed in type system. For example, in web color schemes (get through `Appearance` module) are called `lightTheme` and `darkTheme` instead of `light` and `dark`

**Comment by necolas** [comment]
This repo has no plans to maintain separate TS types. For the `Appearance` example, the values are `light` and `dark` https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Appearance/index.js
