### ISSUE TITLE
react-native-web with server side rendering boilerplate

### ISSUE THREAD

**Issue by JegatheeshSelvam** [necolas/react-native-web#2644]
### Is there an existing request?

- [ ] I have searched for this request

### Describe the feature request

Amazing !!

I have implemented the web app (M-site & Desktop) working fine as expected, Positive scenario.

But I have faced some difficulties,  After I refresh/reload the page data will be lost (empty page).

You already mentioned Server-side(server API) rendering but not working.

If possible provide **boilerplate code with server-side rendering** more and more helpful for react-native-web based sites will developing web apps (M-site & Desktop).

**Comment by necolas** [comment]
Sorry no plans to add SSR boilerplate examples
