### ISSUE TITLE
role="switch" should map to element <button>

### ISSUE THREAD

**Issue by dukenv0307** [necolas/react-native-web#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

role="switch" should both map to HTML element `button` . 
Here's official web standard doc on the `switch` role: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role, it uses the `button` HTML element (also [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role#adding_the_switch_role_in_aria)). Another [doc of `button` HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), with `switch` in `Permitted ARIA roles`.

### Expected behavior

It should be <button role="switch"> on the web

### Steps to reproduce

1. Create a View component
2. Add role="switch" prop to this View

### Test case

https://codesandbox.io/p/sandbox/swtich-role-5qjrcy

### Solution

We should map the `switch` role to `button` html element in `react-native-web` [here](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/AccessibilityUtil/propsToAccessibilityComponent.js#L31) by this one line change:
```
switch: 'button'
```

**Comment by necolas** [comment]
switch can be used with non-button elements too, like `div` and `input[type=checkbox]`
