### ISSUE TITLE
React Server Side Rendering is not working

### ISSUE THREAD

**Issue by kapilgp** [necolas/react-native-web#266]
**Steps to reproduce**

1. clone react-native-web-starter repo
2. update index.web.js as mentioned in https://github.com/necolas/react-native-web/blob/master/docs/guides/rendering.md

But it throws error in console

Appregistery.getApplication is not a function.

**Environment (include versions)**

OS:
Device:
Browser:
React Native for Web (version): latest
React (version): latest

**Comment by MoOx** [comment]
Just in case you made a typo, Appregistery != AppRegistery.

**Comment by necolas** [comment]
Yeah looks like a typo

**Comment by kapilgp** [comment]
Sorry, that typo is written in that issue comment

Actually I tried the same thing that is mentioned in 

https://github.com/necolas/react-native-web/blob/master/docs/guides/rendering.md

const { element, stylesheet } = AppRegistry.getApplication('App', { initialProps });

And it throws error AppRegistery.getApplication is not a function.

**Comment by necolas** [comment]
Make sure you're using the latest version. And thehe error still contains a typo

**Comment by kapilgp** [comment]
Thanks necolas.

Yeah, that is react-native-web latest version issue. Actually I am using react-native-web-starter and in that repo old react-native-web  used in package.json.

I just updated it and it works fine :+1:
