### ISSUE TITLE
Image component is not clickable if it is a child of TouchableWithoutFeedback

### ISSUE THREAD

**Issue by adam-batwash** [necolas/react-native-web#267]
**What is the current behaviour?**
currently an **Image** component inside a **TouchableWithoutFeedback** is not clickable

**What is the expected behaviour?**
if an **Image** component is inside a **TouchableWithoutFeedback**, the image should be clickable. the way that it behaves in react-native. 

http://codepen.io/Batuash10/pen/pNWvNP

**Comment by adam-batwash** [comment]
I did some digging and found an interesting behaviour that might indicate why this is happening:

the **TouchableWithoutFeedback** renders the **child** component and passes the following props to it: **onStartShouldSetResponder,  onResponderTerminationRequest, onResponderGrant, onResponderMove, onResponderRelease, onResponderTerminate**.

```
    return (React: any).cloneElement(child, {
      accessible: this.props.accessible !== false,
      accessibilityLabel: this.props.accessibilityLabel,
      accessibilityRole: this.props.accessibilityRole,
      disabled: this.props.disabled,
      testID: this.props.testID,
      onLayout: this.props.onLayout,
      hitSlop: this.props.hitSlop,
      onStartShouldSetResponder: this.touchableHandleStartShouldSetResponder,
      onResponderTerminationRequest: this.touchableHandleResponderTerminationRequest,
      onResponderGrant: this.touchableHandleResponderGrant,
      onResponderMove: this.touchableHandleResponderMove,
      onResponderRelease: this.touchableHandleResponderRelease,
      onResponderTerminate: this.touchableHandleResponderTerminate,
      style,
      children,
      tabIndex: this.props.disabled ? null : '0'
    });
```

but in case of the **Image** component, when it renders it ignores these props:

```
    return (
      <View
        accessibilityLabel={accessibilityLabel}
        accessibilityRole='img'
        accessible={accessible}
        children={children}
        onLayout={onLayout}
        style={style}
        testID={testID}
      />
    ); 
```

**Comment by necolas** [comment]
Ah, I was following the RN docs, which is missing View's props for Image https://facebook.github.io/react-native/docs/image.html
