### ISSUE TITLE
Add "use client" directive for a proper usage with Next App Router

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#2672]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Would you be open to add [React `"use client"`](https://react.dev/reference/rsc/use-client) directive to all files that requires it so react-native-web can be easily used with Next.js without having to add this directive too early on pages ?

Problem when you add it yourself in your pages or in some component that use RNW primitives: this can conflict with some Server Components or server code that will try to be bundled in frontend bundle.

I can do a PR for this, if you are open to.

**Comment by necolas** [comment]
I think RSC needs to rethink `use client` if I have to add `use client` to every file

**Comment by necolas** [comment]
Maybe they should support configuring the directive for dependencies with no directive
