### ISSUE TITLE
`AppState.isAvailable` is a string instead of a boolean

### ISSUE THREAD

**Issue by mozzius** [necolas/react-native-web#2673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

`AppState.isAvailable` should just be a boolean, as documented here:

https://necolas.github.io/react-native-web/docs/app-state/#static-properties

However, since the check does not coerce `document[VISIBILITY_STATE_PROPERTY]` to a boolean, it ends up being a string such as `"visible"`

### Expected behavior

`AppState.isAvailable` should be a bool

### Steps to reproduce

1. Log `AppState.isAvailable` to console
2. It should be a string instead of a bool

### Test case

https://codesandbox.io/p/sandbox/interesting-dream-fq6q93

**Comment by necolas** [comment]
Fixed by #2674
