### ISSUE TITLE
When releasing a new version, create a new GitHub "release"

### ISSUE THREAD

**Issue by jkjustjoshing** [necolas/react-native-web#2677]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

My confusion in [this comment](https://github.com/necolas/react-native-web/issues/2605#issuecomment-2138267202) came from checking [the releases page](https://github.com/necolas/react-native-web/releases) and not seeing any new release after v0.19.0.

As new patch releases come out, it would be good to see them on the releases page, like [React Navigation](https://github.com/react-navigation/react-navigation/releases), [react-native-svg](https://github.com/software-mansion/react-native-svg/releases), [Zod](https://github.com/colinhacks/zod/releases), [swr](https://github.com/vercel/swr/releases), and many others.

Additionally/alternatively - if I'm on v0.19.6 and am considering upgrading to v0.19.12, how can I see what changes were introduced between those two versions to make sure I'm safely upgrading?

**Comment by necolas** [comment]
You can read the commit log. For the past nearly 10 years I've only published release notes for new minor versions.
