### ISSUE TITLE
[Feature Request] add support for onTextLayout props of Text component （Reiterating it once again）

### ISSUE THREAD

**Issue by Bbbtt04** [necolas/react-native-web#2679]
### Is there an existing request?

- [x] I have searched for this request

### Describe the feature request

[#1685](https://github.com/necolas/react-native-web/issues/1685)
I think this prop is useful because I have encountered this situation in my business。

Why do you think it's unnecessary？

**Comment by necolas** [comment]
I have no plan to try to implement this on web. If someone wants to put up a PR that doesn't tank performance, I'll take a look.
