### ISSUE TITLE
using create-react-app ReactDefaultInjection is not found (and doesn't exist)

### ISSUE THREAD

**Issue by mouneyrac** [necolas/react-native-web#268]
Hi,
I am using the last create-react-app and the file ReactDefaultInjection (and other files too) seems to not be here, causing:

```
Failed to compile.

Error in ./~/react-native-web/dist/index.js
Module not found: 'react/lib/ReactDefaultInjection' in /Users/jerome/Documents/my-react-native-web-app/node_modules/react-native-web/dist

 @ ./~/react-native-web/dist/index.js 2:27-69
```

I tested with react-native-web-starter it seems to me it is due to React 15.4.1 not containing the files anymore (react-native-web-starter works with React 15.3.2)

**Comment by necolas** [comment]
You need to be on react 15.3 until react 15.4 fixes a regression in the event plugins

**Comment by mouneyrac** [comment]
Thanks Nicolas for your quick answer.
