### ISSUE TITLE
FlexBasis of a number works as expected, but throws error that clogs up console feed when multiple elements use on page use it 

### ISSUE THREAD

**Issue by TannerAtVenu** [necolas/react-native-web#269]
**What is the current behavior?**

If I have 4 elements placed side by side on page and give them the following CSS:

elem1: {
  flex: 2,
  flexBasis: 2
},
elem2: {
  flex: 1,
  flexBasis: 1
},
elem3: {
  flex: 0.5,
  flexBasis: 0.5
},
elem4: {
  flex: 0.5,
  flexBasis: 0.5
}

The elements appear the show up as expected as per react-native's usage of flex and flexBasis. That is to say that element 1 is twice the width of element 2 which is then twice as wide as elements 3 and 4. I've included an image below to illustrate this:

<img width="1164" alt="screen shot 2016-11-29 at 2 49 07 pm" src="https://cloud.githubusercontent.com/assets/12898162/20730674/31dd5d2e-b644-11e6-9207-4771a2c801d9.png">

The problem lies in the console where an error is thrown for every element that uses flexBasis as a number, which clogs up the feed and makes it difficult to debug other errors in the app:

<img width="757" alt="screen shot 2016-11-29 at 3 01 36 pm" src="https://cloud.githubusercontent.com/assets/12898162/20730816/c3961684-b644-11e6-8617-f6c79d3a6cc7.png">

**What is the Expected Behavior?**

FlexBasis should allow a number (in the same manor that react native does natively) without throwing an error. 

**Environment (include versions)**

OS: macOS
Device: macBook Pro
Browser: Chrome, Safari, (Others potentially as well, this is all I tested)
React Native for Web (version): 0.35
React (version): 15.3.2

**Comment by MoOx** [comment]
Dup of #230 which is fixed in latest version.

**Comment by TannerAtVenu** [comment]
Oops, my bad. Thank you MoOx!
