### ISSUE TITLE
Image should support BorderPropTypes

### ISSUE THREAD

**Issue by adids1221** [necolas/react-native-web#2692]
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Currently react native Image does support `borderRadius` prop on mobile.
In web there is no support for `borderRadius` as individual prop but only passed via `style` ([link](https://github.com/necolas/react-native-web/blob/6a73d77030a8b48afb5f3db780409e451145d2a9/src/apis/StyleSheet/BorderPropTypes.js#L13)).
[react native image types](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Image/Image.d.ts#L162)

**Comment by necolas** [comment]
On Web we only support styles via the style prop
