### ISSUE TITLE
Crash if TouchableHighlight has a div as a child 

### ISSUE THREAD

**Issue by MykolaSauliak** [necolas/react-native-web#2699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

react div’s style prop couldn’t be an array, but react-native-web TouchableHighlight modifies styles and makes it as array (via cloneElement) - [github](https://github.com/necolas/react-native-web/blob/54c14d64dabd175e8055e1dc92e9196c821f9b7d/packages/react-native-web/src/exports/TouchableHighlight/index.js#L187C1-L190C1).
App crashes in such case.__

### Expected behavior

TouchableHighlight could be used with div and other elements as children

### Steps to reproduce

could be verified with simple example component - TouchableHighlight + div as a child
TouchableHighlight with react-native-web View component is ok.

### Test case

https://codesandbox.io/s/react-native-web-forked-3w4lg9?file=/src/App.js

**Comment by necolas** [comment]
You can't use div in React Native. Only nest other React Native elements in touchables.

**Comment by MykolaSauliak** [comment]
> You can't use div in React Native. Only nest other React Native elements in touchables.

what about other libraries. react-spinners, for example, it could be used on web
