### ISSUE TITLE
remove react dependency?

### ISSUE THREAD

**Issue by chandu0101** [necolas/react-native-web#27]
In my react 0.14 app when i install react-native-web, app is not working ..

>Uncaught Error: Invariant Violation: View.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object

**Comment by necolas** [comment]
looks like 2 versions of react are being installed. i think ultimately this is an `npm` bug that they have fixed in 3.0. but i can switch react to a peer-dependency for now.

**Comment by chandu0101** [comment]
> i think ultimately this is an npm bug that they have fixed in 3.0.

I just upgraded to npm 3.3.5 still same error 

>but i can switch react to a peer-dependency for now.

In my local i removed react as dependency/ bumped version to 0.14.0-rc1 but it's still fetching react 0.13.3 , may be sone of the other deps is culprit here!

**Comment by necolas** [comment]
oh yes, that sounds right. i'll either get them to relax their ranges or remove the external dependencies i used to hack the right API together (good idea longer term i think). sorry for the hassle with this righ tnow. i use react 0.14 while developing locally - npm reports errors but everything builds correctly.

**Comment by necolas** [comment]
Should be fixed in 1c444569ae8f12130197459ed0d34829826008a0.
