### ISSUE TITLE
Console warnings for shadow* props on View elements

### ISSUE THREAD

**Issue by thetable** [necolas/react-native-web#272]
**What is the current behavior?**

For a `View` element like this:

```
<View style={styles}>
  <Text>Text</Text>
</View>
```

where `styles` are:

```
const styles = StyleSheet.create({
  shadow: {
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: {
      height: 10,
      width: 0
    }
  }
});
```

react-native-web prints console warnings like this:

`"Warning: 'shadowColor' is not a valid style property.`

as demonstrated here: http://codepen.io/thetable/pen/bBaNaG?editors=1011

**What is the expected behaviour?**

As shadow props are supported properties on `View` elements (see https://facebook.github.io/react-native/docs/view.html) and react-native-web correctly translates these into CSS, no warnings should be shown.  

**Environment (include versions)**

OS: MacOS 
Device: Mac
Browser: Chrome
React Native for Web (version): latest
React (version): 15.3.1

**Comment by necolas** [comment]
These warnings are intentional because the RN shadow props aren't implemented and don't map cleanly to CSS's `box-shadow`.
