### ISSUE TITLE
how to deploy to server end

### ISSUE THREAD

**Issue by leoabacade** [necolas/react-native-web#277]
hello, I am pretty new to react-native-web, 

I just follow [https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/](url) and successfully build a dev version of web app

<img width="491" alt="screen shot 2016-12-06 at 4 06 08 pm" src="https://cloud.githubusercontent.com/assets/2664504/20917689/f664dd1e-bbcd-11e6-8fc3-ea9e1772aac0.png">

but I am not sure how to deploy these code onto my server, can anyone help me out?
asked at stackoverflow:[http://stackoverflow.com/questions/40990624/how-to-deploy-app-project-of-react-native-web-onto-server-end](url)

**Comment by necolas** [comment]
Stackoverflow is the right place to ask about how to deploy code to your server
