### ISSUE TITLE
ReactNativePropRegistry is undefined

### ISSUE THREAD

**Issue by ngduc** [necolas/react-native-web#280]
**What is the current behavior?**

"react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry" is undefined in react-native-web
https://github.com/GeekyAnts/NativeBase/blob/master/Utils/computeProps.js#L3

**What is the expected behaviour?**

ReactNativePropRegistry should be there in react-native-web

**Steps to reproduce**

1. import NativeBase lib
2. include a sample component from that lib & run the webapp
3. JS error will occur

**Environment (include versions)**

OS: MacOS
Device: Macbook pro
Browser: Chrome
React Native for Web (version): 0.0.55
React (version): ~15.3.2

**Comment by necolas** [comment]
You can use webpack to alias that path to `react-native-web/dist/modules/ReactNativePropRegistry`

**Comment by ngduc** [comment]
Hi @necolas , sorry for commenting on a closed issue but I also have the same undefined-issue with LayoutAnimation.
I tried webpack alias like this but it doesn't work:
```
alias: {
      'react-native/Libraries/LayoutAnimation/LayoutAnimation': path.join(__dirname, '../app/MyLayoutAnimationStub.js'),
      'react-native': 'react-native-web'
}
```
Do you have an example somewhere for mapping like that? Thanks.

**Comment by necolas** [comment]
`LayoutAnimation` isn't implemented and shouldn't be included in web builds. If a package is using it you could ask them to consider web in their implementations.

**Comment by ngduc** [comment]
I agree @necolas but in the mean time, could you help with alias? It's a bigger task to convince module authors to support web :)

**Comment by necolas** [comment]
I don't think aliasing is going to work. You might want to try defining `ReactNative.LayoutAnimation = ...` in your entry file.

**Comment by fabriciovergal** [comment]
You can use NormalModuleReplacementPlugin

`
// Native base compatibility
config.plugins.push(new webpack.NormalModuleReplacementPlugin(
  /react-native\/Libraries\/Renderer\/src\/renderers\/native\/ReactNativePropRegistry/,
  require.resolve('react-native-web/dist/modules/ReactNativePropRegistry')
));
`

**Comment by ChrisOHu** [comment]
Hi by the way you need to put  'react-native': 'react-native-web' to last line of 'resolve':

```
    alias: {
      'react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry': 'react-native-web/dist/modules/ReactNativePropRegistry',
      'react-native/Libraries/Components/StaticContainer': 'react-native-web/dist/components/StaticContainer',
      'react-native': 'react-native-web'
    },

```
