### ISSUE TITLE
Install procedure as documented does not work

### ISSUE THREAD

**Issue by aaroncraig10e** [necolas/react-native-web#285]
Running the install procedure as described in the README produces an error:
```
> npm install -g react react-native-web
/usr/local/lib
├── UNMET PEER DEPENDENCY react@15.4.1
└── react-native-web@0.0.57
```

However, installing the correct dependency seems to work:
```
> npm install -g react@15.3.2 react-native-web
/usr/local/lib
├── react@15.3.2
└── react-native-web@0.0.57
```

Maybe just needs a version bump for react in the package file?

OS: macOS Sierra
Node version: 7.2.1
npm version: 4.0.3

**Comment by remon-georgy** [comment]
That's correct. react@15.3.2 is required as a peer dependency. Compatibility with react 15.4 is on the way https://github.com/necolas/react-native-web/pull/255.
