### ISSUE TITLE
Navigator

### ISSUE THREAD

**Issue by chandu0101** [necolas/react-native-web#29]
web version of react-navigator - https://github.com/bh5-js/react-navigator

can we add this as dependency and expose via react-native-web ? 

or can we copy the source to navigator folder( ofc if author of  bh-react-navigator agree only) ? 

WDYT ..

**Comment by necolas** [comment]
I don't yet see how Navigator (no support for url state) makes sense on web, or would be preferable to react-router.

**Comment by chandu0101** [comment]
>I don't yet see how Navigator (no support for url state) makes sense on web

may be we don't need urls all the time!( because mobile app users are fine with it)

**Comment by necolas** [comment]
That's not the majority case for web

**Comment by necolas** [comment]
Going to close this for now, as react-router is a better choice:

* react-router intends to support React Native
* react-router can be used to control navigation of URL-less apps built with web technologies
* bh5-js/react-navigator doesn't support URLs
* bh5-js/react-navigator has no tests or active development

**Comment by grigio** [comment]
React Router is not going to support React Native https://github.com/reactjs/react-router/issues/743

**Comment by nunobbras** [comment]
What about adding the "new" NavigationExperimental?

**Comment by grigio** [comment]
The missing part is NavigationStateUtils which is similar to the history api but different

**Comment by jmurzy** [comment]
I agree with @necolas. Even though that's what the mobile app world looks like today, the URL is within the very fabric of our web and it shouldn't be taken away. Often people tend to take URLs for granted and advantages are not so pronounced. 

I admit the native app ecosystem is not web-like, and you can argue that URLs aren't necessary and most people don't care, or so I thought until I put the URL-centric design in my native development toolbox.

I've just open sourced [react-router-native](https://github.com/jmurzy/react-router-native) that brings native support for [react-router](https://github.com/reactjs/react-router). Not sure if this is useful to you guys at the moment as it's under active development, but it's worth a look—and feedback is greatly appreciated. 

🍺

**Comment by grigio** [comment]
@jmurzy cool, have you tried the Example you show with react-native-web? It should work on Native and on the Web.
Personally i think the urls are still important, because allow to restore an app state without user interaction

**Comment by jmurzy** [comment]
@grigio I haven't had a chance to try it with react-native-web. Let me know if you take a stab at it first. 

Something to keep in mind is that [react-router-native](https://github.com/jmurzy/react-router-native) introduces two new route configuration elements to [react-router](https://github.com/reactjs/react-router), namely, ```<Tabs />``` Route and ```<Stack />``` Route. We have to test the behavior of these in the browser before making any promises.

🍺

**Comment by bitdivine** [comment]
@jmurzy react-router-native sounds promising.  What is the current state of play?  Is it usable by a react newbie?

Best wishes, Max

**Comment by ngduc** [comment]
FYI. I tried Navigator but it didn't work for me.

So I created a SimpleNavigator below which works across platforms & will keep improving it:
https://github.com/rhinos-app/rhinos-app-dev/blob/master/App/View/App.js
