### ISSUE TITLE
Append to default reset styles

### ISSUE THREAD

**Issue by chandlervdw** [necolas/react-native-web#297]
Is there a way to inject additional "reset" styles?

**Comment by necolas** [comment]
No, you can add your own to your HTML page. What is your use case?

**Comment by chandlervdw** [comment]
Figured this out with `css-loader`. Sorry.

**Comment by necolas** [comment]
If you're building something that is cross-platform adding more global styles might not be the best idea, which is why I was curious what you're trying to accomplish.

**Comment by chandlervdw** [comment]
@necolas all I was trying to do was add a single reset style for web. `a { text-decoration: none }`

**Comment by necolas** [comment]
OK. You shouldn't need to do that if you're creating links with RNW
