### ISSUE TITLE
Is there any way to use sprite sheets?

### ISSUE THREAD

**Issue by user471** [necolas/react-native-web#300]
I guest it's web-specific feature. Maybe I could emulate it somehow?

**Comment by necolas** [comment]
Try using the standard `background-*` properties on `View`.

**Comment by user471** [comment]
@necolas I believe native react doesn't support these properties. 
I guess I can just use different components for web and mobile
```
Platform.OS == "web" ? <View id="css-sprite-sheet-image-id"/> : <Image source="image-id"/>
```
