### ISSUE TITLE
Support {'\n'} in Text

### ISSUE THREAD

**Issue by nthtran** [necolas/react-native-web#302]
**What is the current behavior?**

Unlike RN, RNW doesn't support creating newlines using `{'\n'}`.

Link to minimal test case: http://facebook.github.io/react-native/docs/text.html

This shows `{'\n'}` not working in official RN docs.

**What is the expected behaviour?**

`{'\n'}` within `Text` should create a newline, i.e. `{'\n'}` should be replaced with something like `<br />`.

**Comment by nthtran** [comment]
For a fix, perhaps you can do this in `Text`'s render:

```js
      const newChildren = React.Children.map(
        this.props.children,
        child => (child === '\n' ? <br /> : child), // replace '\n' with <br />
      );
```

If you're ok with it I'll create a PR.

**Comment by lelandrichardson** [comment]
An alternate solution to this problem might be to apply `white-space: pre-wrap;` to the `Text`'s base style

**Comment by necolas** [comment]
Yeah that sounds like a better idea. It's how we layout the Tweet text.

**Comment by nthtran** [comment]
Yep that would be the better solution.
