### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#306]
Add benchmarks to evaluate performance improvements and regressions. Main focus is StyleSheet. Can base it off those @lelandrichardson is using.

**Comment by lelandrichardson** [comment]
I'd also love ideas on better / different benchmarks that we can also use.  Dan abramov suggested using something like this: https://github.com/facebook/react/blob/master/scripts/bench/extract-component.js to extract mock components from real production code to get a more accurate test.  I was thinking I could try and figure out how to run this on an RN code base and try to grab some RN trees used in production. I'm more interested in what web would look like though. I think the trees will be much deeper/wider on web but i'm not sure.

**Comment by necolas** [comment]
That sounds good to me too. I'd been thinking about benchmarking a big tree from mobile.twitter.com once we've converted some components to RNW. Ideally it would be at the level of the `Tweet` but probably something easier to convert first.

For now, I was intending to build on the ones you started to include styles that are more challenging to resolve quickly, like `[ 1, [ 2, 3 ], { prop: value }, 4, 5 ]` and `[ 1, [ 2, [ 3 ], 4 ], 5, { prop: value } ]`.

**Comment by lelandrichardson** [comment]
@necolas yeah, I had planned on making the styles more involved as well. Not just with the arrays of styles etc, but also with more properties and overrides etc.
