### ISSUE TITLE
TouchableOpacity & TouchableWithoutFeedback with touch-screen displays

### ISSUE THREAD

**Issue by lastant** [necolas/react-native-web#313]
On a computer with a touch-screen (e.g. Lenovo Yoga), the TouchableOpacity and TouchableWithoutFeedback (but not TouchableHighlight!) don't work well. When touching using the touch-screen, it works fine; but when clicking using the touchpad or mouse, they only work when the scroll position of the whole page is at the top. 
I.e. on a computer with a touchscreen, if I scroll the page down a bit and then try clicking with a mouse on a TouchableOpacity or TouchableWithoutFeedback, the onPress event is not fired.

Browser: Chrome 55.0.2883.87
OS: Windows 10

**Comment by necolas** [comment]
Please can you try removing [this code](https://github.com/necolas/react-native-web/blob/8eaaf28a32f0d0aad820e977bda4764a23652ace/src/components/View/index.js#L140-L142) from `node_modules/react-native-web/dist/components/View/index.js` and let me know what changes.

**Comment by lastant** [comment]
Still the same.. Also tried removing the surrounding ScrollView..

**Comment by lastant** [comment]
It's strange that the TouchableHighlight does work. Maybe this can give you a hint.

**Comment by necolas** [comment]
Are you saying that `TouchableOpacity` and `TouchableWithoutFeedback` simply don't respond to the mouse? Is that the case for the storybook examples too? https://necolas.github.io/react-native-web/storybook/

**Comment by lastant** [comment]
I updated to the latest version and seems the bug is gone, will close it then.

**Comment by necolas** [comment]
Nice! Thanks
