### ISSUE TITLE
Firefox major issue: TypeError: CSS2Properties doesn't have an indexed property setter for '0'

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#315]
**What is the current behavior?**

Just open your [template codepen](https://codepen.io/necolas/pen/PZzwBR?editors=0010) and you will get a blank screen in Firefox (stable or nightly)

The error is: 

```
TypeError: CSS2Properties doesn't have an indexed property setter for '0'
```

I am getting this with 0.0.63 (I was upgrading from 0.49).
**This make latest version unusable in Firefox.** I guess it comes from the recent refactoring for injecting styles.

**What is the expected behaviour?**

Same result as you can get in Chrome or Safari

**Steps to reproduce**

1. Just use RN(web) in Firefox
2. boom

**Environment (include versions)**

OS: macOS
Device: MacBook Pro 2016
Browser: Firefox (stable or nightly)
React Native for Web (version): 0.063
React (version): 15.4.1

**Comment by user471** [comment]
Same here. 
Is someone know what version after 0.49 doesn't have this problem?

**Comment by user471** [comment]
It look like the last working version is 0.0.61

**Comment by MoOx** [comment]
Probably related to d87f71ebc11d4ac986ec39a039ec4f7c96916e7d or a related commit. I don't have time to investigate yet myself, maybe in the next few days - but I am guessing it's not a big deal to fix.

**Comment by necolas** [comment]
Thanks, this bug is evident in the `Text` snapshot and is caused by RN styles being passed to a DOM node. I'll have a fix up soon

**Comment by MoOx** [comment]
Thanks for the quick fix!

**Comment by necolas** [comment]
Try 0.0.64. The storybook worked in Firefox and the snapshots look fixed.

**Comment by MovingGifts** [comment]
@necolas I just encountered this error in Firefox on a mac (see screenshot), it works perfectly in Chrome though.
![screen shot 2017-02-28 at 12 21 20 pm](https://cloud.githubusercontent.com/assets/1202909/23416392/abfc2122-fdb0-11e6-8a07-95241afeed5f.png)

**Comment by necolas** [comment]
If you provide more context (e.g., version) and a working screenshot, I can take a look

**Comment by MovingGifts** [comment]
I'm using FireFox 51.0.1 on Mac and just opening [this url](http://necolas.github.io/react-native-web/storybook/?selectedKind=Components&selectedStory=ScrollView&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) leads to the above error. This is a url navigated to from this package's documentation's link.

**Comment by necolas** [comment]
OK thanks, that's probably because I haven't updated the documentation for a while

**Comment by duongtranpyco** [comment]
This issue is still happening with latest release **0.0.94**
