### ISSUE TITLE
Warning: prop type `style` is invalid

### ISSUE THREAD

**Issue by user471** [necolas/react-native-web#317]
There are 3 warnings if react dev version is used
```
Warning: ScrollView: prop type `contentContainerStyle` is invalid; it must be a function, usually from React.PropTypes. 
Warning: ScrollView: prop type `style` is invalid; it must be a function, usually from React.PropTypes. 
Warning: TouchableHighlight: prop type `style` is invalid; it must be a function, usually from React.PropTypes.
```

https://codepen.io/anon/pen/RKwmJR?editors=0010

react@15.4.1
react-native-web@0.0.65

**Comment by necolas** [comment]
Yeah you can't use the dev version of react with the production version of RNW, which has all the proptypes removed

**Comment by user471** [comment]
But isn't it weird there are only 3 warnings?
Why only `TouchableHighlight` and `ScrollView`?
