### ISSUE TITLE
ReactNative.js dev version

### ISSUE THREAD

**Issue by user471** [necolas/react-native-web#318]
I think there should be two versions similar to react
```
https://unpkg.com/react@15/dist/react.js
https://unpkg.com/react@15/dist/react.min.js
```
and current version
https://unpkg.com/react-native-web@0.0.65/dist/ReactNative.js
should be called ReactNative.min.js

**Comment by necolas** [comment]
There's no official support for UMD prebuilds right now. That bundle was only for codepen examples, and it looks like it's not being built correctly given the issues you're seeing

**Comment by user471** [comment]
>There's no official support for UMD prebuilds right now.

Is there any plans to support it? 
I use it with scala.js and it can only be used with umd.

**Comment by necolas** [comment]
You're welcome to have a go at fixing the UMD build

**Comment by user471** [comment]
>You're welcome to have a go at fixing the UMD build -> #320

Do you have any thoughts why simple re-export could break something in code?
