### ISSUE TITLE
TouchableHighlight error: addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by user471** [necolas/react-native-web#319]
There is an error when TouchableHighlight is used
```
Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

https://codepen.io/anon/pen/xgbXQN?editors=0010
react@15.4.1
react-native-web@0.0.65

It doesn't show error message because of reactnative.js production version.

Maybe it's related to https://github.com/necolas/react-native-web/issues/317

**Comment by necolas** [comment]
I can't reproduce this in the storybook - https://necolas.github.io/react-native-web/. Must be a UMD build error. I'll make a new issue to look into that. Thanks
