### ISSUE TITLE
Problems with UMD build

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#320]
**What is the current behavior?**

The unofficial UMD build for use in codepen et al has some issues.

1) `addComponentAsRefTo(...): Only a ReactOwner can have refs` when using TouchableHighlight (#319). [Example](https://codepen.io/anon/pen/xgbXQN?editors=0010)

2) Using `Image` can throw an error about accessing `source` of undefined.

**What is the expected behaviour?**

No issues!

**Environment (include versions)**

OS: Any
Device: Any
Browser: Any
React Native for Web (version): At least 0.0.60 upwards
React (version): 15.4.1

**Comment by user471** [comment]
I used `browserify` instead of `webpack` and the result doesn't have this error.

**Comment by necolas** [comment]
Cool, might be a misconfiguration in the webpack config. Are you bundling the whole of React in there? Also maybe try rollup since it produces smaller, faster bundles.

**Comment by user471** [comment]
>Are you bundling the whole of React in there? 

No. `browserify dist/index.js -o ReactNative.js`

**Comment by user471** [comment]
The file has similar size to webpack version and doesn't work without react.js

**Comment by necolas** [comment]
OK that sounds promising! Thanks :)

**Comment by necolas** [comment]
@user471 are you still looking into this?

**Comment by user471** [comment]
@necolas No, I have switched to module imports instead of globals. 
And everything works fine right now.

**Comment by necolas** [comment]
This is not officially supported but I hope to get it working properly after upgrading to React 16 (and no longer using paths to React's internal modules)

**Comment by JBradBarnes** [comment]
Are there any plans to include a UMD build in the future?  This would be awesome give the package size.

**Comment by NE-SmallTown** [comment]
Hi, do we still have a plan for supporting UMD build?

**Comment by NE-SmallTown** [comment]
@necolas Friendly ping~

**Comment by necolas** [comment]
No plans to publish UMD build

**Comment by NE-SmallTown** [comment]
Would you mind share the reasons? That would be helpful to me
