### ISSUE TITLE
Determine why inline styles are slow (React or the browser)

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#322]
`StyleSheet` must sometimes create a `style` object to correctly resolve RN styles.

However, a React render with a style object can be as much as 3-4x slower than one without (per benchmarks). This issue is to determine how much of that slowness is down to React vs the browser.

**Comment by o-t-w** [comment]
What was your conclusion? I was thinking of using inline styles to set the value of CSS custom properties.
