### ISSUE TITLE
Platform checks aren't defined

### ISSUE THREAD

**Issue by omrihq** [necolas/react-native-web#323]
I've been trying to work the Platform api for a bit, but it seems to not work to detect ios or android. In the Platform index file, the only thing present is

```
const Platform = {
 OS: 'web',
 select: (obj: Object) => obj.web
}

module.exports = Platform
```
so if I do
```import { Platform } from "react-native-web"```
```Platform.OS``` is always web

**Comment by RangerMauve** [comment]
@omrihq I think the point of the Platform API is to detect the "rendering platform" to be able to choose specific components. If you want your Web-specific components to also do platform detection, I would suggest using a module that will do user agent sniffing for you. For example [platform on npm](https://www.npmjs.com/package/platform)

**Comment by omrihq** [comment]
That makes more way more sense, thanks

**Comment by necolas** [comment]
I think the question has been answered, thanks
