### ISSUE TITLE
react-mobile-web

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#328]
Proposed redesign of the project:

**react-mobile-web** - The core React Native components and APIs optimized and adapted for mobile web development.

**react-mobile-web/addons** - Exports other components and APIs (e.g., "Switch", "Checkbox", "AsyncStorage")

**react-mobile-web/compat** - A compatibility layer for rendering React Native apps on web. Includes stubs`NativeModules`, `BackAndroid` stubs, etc. Alias for `react-native`(either way) and use a bundler with support for tree-shaking.

Why? React Native is not currently designed to extend beyond Android/iOS. It exports platform-specific modules, props, and styles in an increasing number of places. The React Web ecosystem is all over the place.

The idea would be to focus on developing a platform for mobile web apps (over RN API compatibility), enable faster development of the library, and explore a more platform-agnostic design (e.g., `react-mobile` and `createSwitch(renderer) => Switch`). Adopting a `compat` layer (a la Preact) may make it easier to improve RN compatibility (and document the differences).

**Comment by MoOx** [comment]
This make sense.
Just one question: what are the argument for something to be in core or in the index? Eg: Dimensions seems to be a core module to me - I guess I just miss something :)

**Comment by necolas** [comment]
If an API/component is a dependency of the basic building blocks in core, it could be added to core. At the moment `Dimensions` is not and isn't needed to build components in most cases, whereas `Image`, `View`, `Text` and `StyleSheet` are.

**Comment by drewwells** [comment]
Since Dimensions is very common in RN apps. How do we resolve it within react-native-web? `require('Dimensions')` fails.

**Comment by necolas** [comment]
I've been thinking more seriously about renaming this project to `react-mobile-web` after a conversation with @tomocchino and @sebmarkbage. I've updated the issue accordingly.

**Comment by RangerMauve** [comment]
What's the reasoning for the change if you don't mind me asking?

**Comment by necolas** [comment]
See above

**Comment by MoOx** [comment]
What about:

- react-web
- react-web/addons
- react-web/native-compat

I don't really see how it's specific to "mobile". This word don't really make sense to me as we are seeing more and more new kind of devices (smart*) with screen and browsing capabilities.

**Comment by necolas** [comment]
`react-web` is already taken

> I don't really see how it's specific to "mobile".

RN is literally a mobile app library

**Comment by RangerMauve** [comment]
`react-native-web` still seems more appropriate since it's obvious to people that it's "react-native, but on the web". `react-mobile-web` makes one think that it's another React component library for mobile web apps, which although it kind of is, it's still more strongly related to react-native

**Comment by t-benze** [comment]
react-native-mobile-web could be more appropriate but it may be too long :) Since usually the mobile-web version and app version of a product share most of the design and business logic, we'd like to have the same code being able to run on ios, android and mobile browsers with just a few tweaking (Desktop browser is another story). This library really fills the gap and we'd like to try it out in production.

**Comment by dorthwein** [comment]
I personally feel this is a terrible idea and the main reason I opted to use this project was with the understanding that it was seeking to make a web compatible version of RN.

While I understand your proposed direction on this would still have a section for that, why not just continue the current scope of this project and create another one to fill what ever need your seeing?

I've just been reading these in emails and need to review the proposed in more detail,  but wanted to voice my opposition to this.

**Comment by necolas** [comment]
> the main reason I opted to use this project was with the understanding that it was seeking to make a web compatible version of RN

Nothing mentioned here changes that

**Comment by MoOx** [comment]
What about a monorepo?

- react-mobile-web
- react-mobile-web-addons
- react-native-web

**Comment by MarkMurphy** [comment]
My vote is to keep it react-native-web. It's more intuitive imho. Adding mobile just makes it confusing and I agree with RangerMauve

On Feb 18, 2017, at 5:15 PM, Maxime Thirouin <notifications@github.com<mailto:notifications@github.com>> wrote:


What about a monorepo?

  *   react-mobile-web
  *   react-mobile-web-addons
  *   react-native-web

**Comment by gary-domain** [comment]
Agree adding mobile makes it confusing. Thought it would now work only as a mobile site or something strange like that.

**Comment by mouneyrac** [comment]
Personally when I was looking for this project I was looking for solution to make RN easily portable on web (so I dont spend too much time rewriting plenty of code). I find the current name of the project reflecting well on my "need". It is probably why it was originally called like that.

 I have to say mentioning mobile in the name is not reflecting my initial need. I mean I am developping a RN app, I know my app UX is designed for mobile. What I want is a solution to make RN works on web (and, I know it is bad, at the beginning, I dont care too much that the desktop version is too mobile oriented, would the project succeed then I will consider thinking more about inbesting in the web version).

Changing the name including "mobile" is designing the project for other people. I am not sure if they exists, sound like people working on the web who want to create a mobile app, could be hybrid or just web, and these people knows that RN is awesome and want to use RN syntax for their project... I doubt these people are a larger user base than the one for the current name. And they may prefer using something else like reactjs/router/boostrap. I think, if not already done, it may be worth to make a poll to understand who is using the project and who is not using it but want to use it. They probably the same but the idea is to understand why they want the project. Could prove my hypothesis on the people using this project is wrong :)

As for separating API in core and addons, I am just expecting a simple way to know what is supported and not supported (it seems a good idea to make separation if it helps you to manage the project more efficiently)


These are my 2 cents as a project user about the developer experience (or user experience if I should use the generic term).

**Comment by reggi** [comment]
Have you guys seen https://github.com/lelandrichardson/react-primitives? Similar project.

**Comment by reggi** [comment]
NVM! https://github.com/lelandrichardson/react-primitives/issues/31
