### ISSUE TITLE
react(-dom)/lib/* is going to be removed

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#329]
This thread is just a start following this tweet https://twitter.com/dan_abramov/status/820351000011751424

> Can’t wait to switch React to using flat bundles. Then server-side performance would be better out of the box! https://github.com/taobaofed/server-side-rendering-comparison/pull/5

> This means that if you (or libraries you depend on) rely on react/lib/* or react-dom/lib/*, time to raise issue. This WILL be removed.

**Comment by necolas** [comment]
Ok. I was starting to think about things like preact support (if only for bundle size savings for mobile) and pulling some of the react lib code into RNW. We had some problems building the production bundles for mobile Twitter with preact so I didn't look into it more. However the lack of event capturing, different event system, and work involved in porting the responder event plugin were also reasons I've put off looking into preact for RNW cc @developit

**Comment by necolas** [comment]
Closing. See #364 for umbrella issue
