### ISSUE TITLE
React alternatives / Preact support

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#330]
Support for React alternatives would be interesting. Preact could make for significantly smaller bundles. It would perhaps involve changes to `preact-compact` to support capture phase events and the `ResponderEventPlugin`, or alternative implementations of the plugin. Let me know if anyone else is interested in this and figuring out how to get there.
/cc @developit

**Comment by indexzero** [comment]
> Howdy. We've been using this a bunch for `react` (web) and `react-native` interop. Thanks for all your hard work!

A good place to start would be enumerating all of the explicit imports similar to `import Whatever from `react-dom/lib/Whatever.js`. Once all the explicit dependencies are known, it would be more straight-forward to outline the API surface area for such a compatibility layer. 

Thoughts? I'm relatively new to the project ... would be happy to help build / provide this if it seems like the right approach.

**Comment by developit** [comment]
Oi, long time no see @indexzero 😎
Are either of you two able to point me to where `ResponderEventPlugin` is implemented?  Regarding capturing/noncapturing events - that might actually get implemented in Preact core, so `preact-compat` would get it for free.  Right now Preact uses [a whitelist of event types](https://github.com/developit/preact/blob/master/src/constants.js#L20) for which it will always register capturing handlers, but since whitelists are a size penalty I think we might end up just allowing the `on*Capture` prop syntax and removing the whitelist entirely.

**Comment by necolas** [comment]
Closing this as I'm going to focus on the changes coming with Fiber #364

**Comment by jwickens** [comment]
Just chiming in to say that react-lite support would also help greatly in reducing bundle size (by more than 100kb in my current project after uglify). The biggest issue is the ResponderEventPlugin which does not exist in react-lite.

**Comment by necolas** [comment]
What is "react-lite"?

**Comment by jwickens** [comment]
@necolas This is react-lite https://github.com/Lucifier129/react-lite

The build size is enormously smaller considering it is a drop in replacement for both react and react-dom and minified is only 25 kb. Current versions of react and react-dom minified combined are about 140kb so you're looking at about saving 100kb of JS sent over the wire. 

See for http://elijahmanor.com/react-file-size/#linechart_material current react sizes

**Comment by necolas** [comment]
I don't think there is an easy way to not rely on the `ResponderEventPlugin`. Furthermore, React alternatives don't always have good runtime performance across the spectrum of use cases, which is another reason I stopped investigating ways to support them being used as replacements for `react` in RNW.

> you're looking at about saving 100kb of JS sent over the wire

You should be using compression formats over the wire though.

**Comment by jwickens** [comment]
> > you're looking at about saving 100kb of JS sent over the wire
> You should be using compression formats over the wire though.

Yeah you're right. In the react case its 45 kb gzipped and in the react-lite case its 10kb gzipped.

**Comment by SuhairZain** [comment]
@necolas I've looked at the linked issues, but it did not become clear to me. Apologies if this has been concluded somewhere else. In the end, was the decision that looking into ways to support React-like libraries(preact etc) was not worth it? Or is there a way to make something like Preact work with react-native-web?

**Comment by necolas** [comment]
Yes, not worth it and we're working on more fundamental integrations with React's new features

**Comment by duxiaofeng-github** [comment]
I wrote a plugin to implement the `Gesture Responder System`, feel free trying it. https://github.com/duxiaofeng-github/preact-responder-event-plugin

**Comment by austinjp** [comment]
> I wrote a plugin to implement the `Gesture Responder System` for preact and react-native-web, feel free trying it. https://github.com/duxiaofeng-github/preact-responder-event-plugin

Thanks for this. To assist people who are encountering errors while using Webpack to build react-native-web projects using Preact X, @duxiaofeng-github 's plugin fixes this error:

```
ERROR in ./node_modules/react-native-web/dist/exports/createElement/index.js
Module not found: Error: Can't resolve 'react-dom/unstable-native-dependencies' in '/home/austinjp/preact-native-test/node_modules/react-native-web/dist/exports/createElement'
 @ ./node_modules/react-native-web/dist/exports/createElement/index.js 12:0-82 18:2-26
 @ ./node_modules/react-native-web/dist/index.js
 @ ./src/index.js

ERROR in ./node_modules/react-native-web/dist/modules/ResponderEventPlugin/index.js
Module not found: Error: Can't resolve 'react-dom/unstable-native-dependencies' in '/home/austinjp/preact-native-test/node_modules/react-native-web/dist/modules/ResponderEventPlugin'
 @ ./node_modules/react-native-web/dist/modules/ResponderEventPlugin/index.js 11:0-88 12:27-61 13:33-67
 @ ./node_modules/react-native-web/dist/exports/createElement/index.js
 @ ./node_modules/react-native-web/dist/index.js
 @ ./src/index.js
```

Be sure to add the alias as described in the "Usage" section of the docs:

https://www.npmjs.com/package/preact-responder-event-plugin

Hopefully this will add a little Google-juice for people like me who are new to RNW and stumbling on this error.

**Comment by johnsonjo4531** [comment]
Just an update for anyone still looking at this thread: looks like React alternative and Preact support is now available in [0.13.0](https://github.com/necolas/react-native-web/releases/tag/0.13.0)

**Comment by cj** [comment]
@necolas  @johnsonjo4531 it mentions "However, it should be noted that benchmark rendering of 0.13 with React DOM is a lot faster than Preact." Do you know where I'd be able to see or run those benchmarks, I'd love to see the difference.  If it is that much slower, I wonder if it's something the Preact team and @developit would be willing to look into.

**Comment by necolas** [comment]
Fork the repo and alias `react` to `preact/compat` in the benchmarks package yourself

**Comment by developit** [comment]
We are looking into it.

**Comment by necolas** [comment]
Note the "benchmarks" are used more like "canary in the mine" early warning tests for CSS libraries. Didn't really expect much runtime difference between React/Preact. But they were running slower in each case so perhaps they will help surface something interesting
