### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by rafaelrinaldi** [necolas/react-native-web#333]
One of the best things about React Native is the ability to see errors (and warnings) displayed on screen when they happen, instead of crashing the application entirely.

I wonder what it would take to bring such thing to _React Native for Web_ and also if it does belong here?

Anyway, just wanted to share this and get some feedback from you.

Thanks.

**Comment by necolas** [comment]
This seems like something that create-react-app is tackling. It's not something I want to duplicate in this project right now.
