### ISSUE TITLE
Module import in webpack@2.x.x no longer considers files ending with *.web.js 

### ISSUE THREAD

**Issue by gisenberg** [necolas/react-native-web#334]
**What is the current behavior?**
There is a difference in module resolution behavior between `webpack@1.x.x` and `webpack@2.x.x`. The current guidance from `react-native-web` is [this](https://github.com/necolas/react-native-web/blob/master/docs/guides/react-native.md):

> More substantial Web-specific implementation code should be written in files with the extension .web.js, which webpack will automatically resolve.

It looks like this behavior has changed in `webpack@2.x.x`. 

The code for the page imports `./dependency`, which resolves to `dependency.web.js` in `webpack@1` but `dependency.js` in `webpack@2`. In webpack 2, the page emits 'Hello from dependency.js' but should be emitting 'Hello from dependency.web.js' instead.

The intent here is to understand whether or not this is now a documentation bug in `react-native-web`, a regression in `webpack` or some other change.

Link to minimal test case: [github](https://github.com/gisenberg/rnw-webpack2)

**What is the expected behaviour?**
The code for the page imports `./dependency`, which resolves to `dependency.web.js` in `webpack@1` but `dependency.js` in `webpack@2`. In webpack 2, the page emits 'Hello from dependency.js' but should be emitting 'Hello from dependency.web.js' instead.

**Steps to reproduce**
To reproduce, follow these steps:

1. `git clone https://github.com/gisenberg/rnw-webpack2.git`
2. `cd rnw-webpack2`
3. `yarn` or `npm install`
4. `yarn start` or `npm start`
5. Navigate to http://localhost:8080/

**Environment (include versions)**

OS: N/A
Device: N/A
Browser: N/A
React Native for Web (version): 0.0.68
React (version): 15.4.2

**Comment by necolas** [comment]
> The intent here is to understand whether or not this is now a documentation bug in react-native-web, a regression in webpack

Yes, this would be a breaking change in webpack@2 but may be intentional. /cc @TheLarkInn

**Comment by c-h-** [comment]
I'm using webpack 2, it's easy to enable `.web.js` support again using config.resolve.extensions.

For example, for `webpack.config.js`:
```javascript
{
  resolve: {
    extensions: ['.webpack.js', '.web.js', '.js', '.json'],
  }
}
```

**Comment by gisenberg** [comment]
@c-h- I have that configuration in my repository containing the repro (https://github.com/gisenberg/rnw-webpack2), and I still see the same behavior. Did I miss something?

**Comment by c-h-** [comment]
Hmmm @gisenberg are you sure you've got the right node_modules folder?? Not sure why that's happening.

When I `git clone` and `npm i` this is what I see: 
![image](https://cloud.githubusercontent.com/assets/5919164/23104896/6fcfd59e-f6a4-11e6-90d3-23a6bae69b42.png)

**Comment by gisenberg** [comment]
@c-h- I'm seeing the correct behavior now, it must have been a fluke with my local setup. Thanks!
