### ISSUE TITLE
TouchableOpacity can be slow to respond to touch while scrolling

### ISSUE THREAD

**Issue by Jxcook** [necolas/react-native-web#336]
This issue has more than one way to reproduce, but this is the way I was able to force the issue out.

**What is the current behavior?**

Rendering many views and elements with TouchableOpacity can cause a 250ms-500ms lag to the initial touch of a scroll.  This causes the scrolling experience to look detached from my finger and scroll a random distance.   This only happens for IPhone devices in the Safari mobile browser and it does not seem to reproduce in the simulator.

**What is the expected behaviour?**

Should be smooth and consistently responsive, similar to the feel of using TouchableWithoutFeedback in place of TouchableOpacity.  I use this to compare often when trying to reproduce the issue.

**Steps to reproduce**

I have spent time trying to simplify the reproduction of this issue, but the most reliable method of reproducing this is to embed views and TouchableOpacity elements something like the below example repeated 30-40 times.. The real cause I am still not certain because I have seen it happen under other types of conditions but this is the way I can force it to happen.

        <View>
          <Text>This is my first line of text for this repro</Text>
          <Text>This is my second line to repro this problem </Text>
        </View>
        <TouchableOpacity>
            <View>
              <Text>This text seems to make the issue slightly worse, but images don't seem as impactful</Text>
              <img src={logo} className="App-logo" alt="logo" />
            </View>
        </TouchableOpacity>

For comparison, you can replace TouchableOpacity with TouchableWithoutFeedback and see that there is definitely a difference in the scrolling experience.

**Environment (include versions)**

OS: IOS
Device: IPhone
Browser: Safari
React Native for Web (version): 0.0.51
React (version): 15.3.2

**Comment by necolas** [comment]
Please can you try updating to react@15.4 and react-native-web@0.0.68

**Comment by jameslive** [comment]
Thank you for the suggestion, I tried this and it did work better.  However, I need to perform some additional testing to make sure.  I will update as I get that done.

**Comment by jameslive** [comment]
Ok, this has been confirmed to fix the issue. Thanks!

**Comment by necolas** [comment]
Thanks for confirming

**Comment by gary-domain** [comment]
Wondering what cause this issue?

**Comment by nthtran** [comment]
@necolas This is still happening on `0.0.77`. To reproduce:

```js
<ScrollView>
  {Array.from(Array(100)).map((_, i) => (
    <TouchableOpacity>
      <View
        style={{
          backgroundColor: i % 2 ? 'red' : 'blue',
        }}
      >
        <Text>Random text</Text>
        <Text>Random text</Text>
        <Text>Random text</Text>
      </View>
    </TouchableOpacity>
  ))}
</ScrollView>
```

The lag is worst with `TouchableOpacity`, a bit better with `TouchableHighlight`, while `TouchableWithoutFeedback` works totally fine.

However, if you remove the Texts above and set a height on View like this:

```js
      <View
        style={{
          height: 100,
          backgroundColor: i % 2 ? 'red' : 'blue',
        }}
      />
```

Then all 3 Touchables work fine. So I'm guessing it's Text that's causing this issue.

Environment (include versions)

OS: iOS 10
Device: iPad Pro
Browser: Safari
React Native for Web (version): 0.0.77
React (version): 15.4.2

@jameslive @gary-domain Can you guys confirm this?

**Comment by necolas** [comment]
This happens in desktop Safari and probably related to a [major flexbox performance issue](https://bugs.webkit.org/show_bug.cgi?id=141845) that has affected Safari for over 2 years. Thankfully, WebKit has been patched and hopefully it will make it into the next version of Safari.

Adding the style `display: block` somewhere in the tree breaks the flexbox nesting and restores some of the lost performance. We used this work around to improve render performance in Safari for mobile.twitter.com:

```js
<ScrollView>
  {Array.from(Array(100)).map((_, i) => (
    <TouchableOpacity key={i}>
      <View style={{ display: 'block' }}>
        <View style={{ backgroundColor: i % 2 ? 'red' : 'blue' }}>
          <Text>Random text</Text>
          <Text>Random text</Text>
          <Text>Random text</Text>
        </View>
      </View>
    </TouchableOpacity>
  ))}
</ScrollView>
```

Environment:

OS: OS X 10.11
Device: MacBook Pro
Browser: Safari 10
React DOM (version): 15.4.2
React (version): 15.4.2

**Comment by nthtran** [comment]
Thank @necolas. That indeed fixes the issue.

**Comment by chinaxiaoyy** [comment]
change the TouchableOpacity to Text ,this.will flxed

**Comment by ShravanMeena** [comment]
> change the TouchableOpacity to Text ,this.will flxed

I know Bhosdike

**Comment by junaid5546** [comment]
Use Pressable.
