### ISSUE TITLE
Installing React Native UI Libraries.

### ISSUE THREAD

**Issue by veenedu** [necolas/react-native-web#340]
I am using `create-react-app` with `react-native-web`. I am successfully able to run a hello world app, where I import and `View` and `Text` and run toy App  in browser.

I want to use  UI Library (like below one). Right now I am getting error. 
https://github.com/GeekyAnts/NativeBase

My question is: Is there a way to install UI Libraries like we do in React_Native that runs on Mobile?

**Comment by RangerMauve** [comment]
NativeBase has a [native-base-web](https://github.com/Chion82/native-base-web) project for doing that. 

This was brought up in https://github.com/GeekyAnts/NativeBase/issues/120

You cannot, however, use any React-Native libraries that use native code. Only ones that use pure JS.

**Comment by necolas** [comment]
Thanks @RangerMauve
