### ISSUE TITLE
Regression with UIManager measurement methods

### ISSUE THREAD

**Issue by bloodyowl** [necolas/react-native-web#341]
**What is the current behavior?**

https://codepen.io/anon/pen/JEpbjg

The new calculation method of UIManager using `offset${ X }` properties doesn't return the expected values, because `offset${ X }` methods stop calculation at the closest positioned ancestor.

It breaks `measureLayout` behaviour by returning the wrong offsets.

**What is the expected behaviour?**

<img width="491" alt="screen shot 2017-01-31 at 15 03 59" src="https://cloud.githubusercontent.com/assets/1688645/22467876/a5d95d1e-e7c6-11e6-970d-b5f15e58aede.png">

**Comment by necolas** [comment]
Thanks, I suppose we could iterate up through the tree and accumulate offsets. I'm a little concerned about how that could impact performance vs a single call to get client rects (which unfortunately includes the effects of transforms).

**Comment by bloodyowl** [comment]
from what I can recall, most DOM libraries à-la-jQuery moved to `getBoundingClientRect` at some point both for performance and browser consistency issues. the only bug I can recall was with inline-block elements within inline ones, which shouldn't be an issue in RNW.

I think a loop iterating over `offsetParent` should do.

would you like a PR for this?

**Comment by necolas** [comment]
> would you like a PR for this?

sure, thanks!
