### ISSUE TITLE
Developer usability regarding styles

### ISSUE THREAD

**Issue by MarkMurphy** [necolas/react-native-web#342]
I've been working with react native web for a little bit now and I just wanted to voice my concern around how much of a pain it is to work with and debug styling in react native web. 

I find it very difficult to reason about the styles applied to components via the web inspector because it applies a class for every attribute. It makes my job a lot more difficult and time consuming. It's also really difficult to use the elements inspector because of this. 

I don't have any suggestions for alternative solutions I just wanted to put this out there as food for thought and maybe something to consider for the future of development on this.

![screenshot 2017-01-31 13 55 43](https://cloud.githubusercontent.com/assets/873474/22477567/02f245d8-e7bd-11e6-8795-1cdcf9b62110.png)

**Comment by necolas** [comment]
Try using the react dev tools extensions
