### ISSUE TITLE
JSS Support

### ISSUE THREAD

**Issue by jtag05** [necolas/react-native-web#344]
I would venture to say that I am not alone in wishing this project supported a JSS implementation. Debugging stylesheet issues when all elements are given a class for each CSS property is very tedious and difficult to read in the inspector. 

I've created a pull request #343 with a JSS implementation that does not replace the current `StyleSheet` api implementation but just creates an alternate approach that would be used in the same manner that the `/core` module is imported (ie `react-native-web/jss`)

Benchmark tests of my pull request show that there is virtually no difference between registered stylesheets and around a 30ms initial increase for unregistered styles from the initial creation of the style tag, but otherwise performs on par with the current StyleSheet api as well.

**Comment by necolas** [comment]
Hey,

I'd suggest debugging with the React dev tools to get a more accurate representation of the style props being applied to an element. If applying line-breaks between the classNames is a problem, I can remove that from development and retain it for clearer snapshots.

I don't think it's wise for this project to start maintaining multiple StyleSheet implementations. But I had a look at your PR and left a [comment](https://github.com/necolas/react-native-web/pull/343#issuecomment-279177085).

The current `StyleSheet` implementation in this repository was written in a couple of days, so I'm encouraged to see that it's already smaller and faster than an attempt using JSS. In my tests, it was also considerably faster than an attempt using glamor.

I will leave PR #343 open for now.
