### ISSUE TITLE
Make react-devtools work again

### ISSUE THREAD

**Issue by pillowsoft** [necolas/react-native-web#346]
**Current behavior**

[**react-devtools**](https://github.com/facebook/react-devtools) worked in older versions of react-native-web, but currently, do not work.

**Expected behaviour?**

**react-devtools** should work as they used to.

**Steps to reproduce**

Build a react-native-web app, open in Chrome which has **react-devtools** installed, and you will see that the **react-devtools** tab does not show up. If I add:

window.React = React;

at the app entry, I  can force the React tab to show up, but it will display a message saying:

*Waiting for roots to load...*

Another test case is to run [**react-native-web-starter**](https://github.com/grabcode/react-native-web-starter) and you will see **react-devtools** work. Then upgrade it to use the latest **react** and **react-native-web** and it no longer works.

**Environment (include versions)**

OS: Sierra 10.12.3
Device: Mac
Browser: Chrome
React Native for Web (version): 0.0.69
React (version): 15.4.2

**Comment by nthtran** [comment]
For now you can use `render` from `react-dom` to make your app work with devtools again.

**Comment by necolas** [comment]
Try 0.0.70

**Comment by pillowsoft** [comment]
That fixed it. Thanks!!
