### ISSUE TITLE
Native-only style props not being ignored

### ISSUE THREAD

**Issue by eriklharper** [necolas/react-native-web#347]
**What is the current behavior?**
setting an `elevation` style property on a View results in a console error:

![image](https://cloud.githubusercontent.com/assets/821864/22574101/9d782e74-e961-11e6-94e7-9afc74fdd809.png)

**What is the expected behaviour?**
Expect that the style be removed prior to bundling, or otherwise ignored so the error doesn't show up in the console.

**Steps to reproduce**

1. Add `elevation` prop to a style.
```
export default class App extends Component {
  render() {
    const styles = StyleSheet.create({
      default: {
        backgroundColor: 'gray',
        elevation: 4,
      }
    });
    return (
      <View style={styles.default}>
      </View>
    );
  }
}
```
2. Refresh page, looking at the console.

**Environment (include versions)**

OS: OSX Sierra
Device: MacBook Air early 2015
Browser: Chrome 56.0.2924.76 (64-bit)
React Native for Web (version): 0.0.69
React (version): 15.4.2

**Comment by necolas** [comment]
Are you adding `elevation` to your components or is it coming from a `react-native` dependency? You can use `Platform.select` to apply platform-specific styles to an element.

**Comment by eriklharper** [comment]
Its coming from a `react-native` dependency, unfortunately.  I tested adding `elevation` as a style prop to some of my code to verify that was the cause of the console error, but originally I saw the error from several of the `react-native` deps that are [specified here in `rhinos-app-dev`'s project](https://github.com/rhinos-app/rhinos-app-dev/blob/master/package.json#L32-L37) here that I'm using to learn more about how to build react native-like features for my web app.

In fact, if you [clone that repo](https://github.com/rhinos-app/rhinos-app-dev/blob/master/package.json#L32-L37), npm install and start the server, out of the gate you will see the litany of console error messages that result from those packages.

I certainly think this would be a very nice-to-have feature of `react-native-web` but I do understand the considerable complexity involved with developing a solution.  I would definitely be willing to collaborate with you on a solution, as this is a project I believe is the right for the type of thing I'm trying to build and I want to help improve it in any way I can!

What I might also do, since I'm really trying to build a fairly simple native "preview" app, is try to build RNW-specific components that don't have these console errors, or otherwise fork some of these projects as they see fit for my use case so that I can control the styles myself.  I'll update on the progress there, as it is likely a path I will pursue in light of this, and I can especially utilize `Platform.select` wherever needed as well.

**Comment by ndbroadbent** [comment]
I am seeing this error while using [react-native-experimental-navigation](https://github.com/aksonov/react-native-experimental-navigation), which is a dependency of [react-native-router-flux](https://github.com/aksonov/react-native-router-flux).

`elevation` is an android-only property, but it's just ignored on iOS, so it would be great if it could also be ignored on web. 

I saw that it is [already ignored in expandStyle.js](https://github.com/necolas/react-native-web/blob/master/src/apis/StyleSheet/expandStyle.js#L62), so I think the prop just needs to be added to `ViewStylePropTypes`

**Comment by eriklharper** [comment]
👍  thanks, look forward to testing this out!
