### ISSUE TITLE
__DEV__ is undefined

### ISSUE THREAD

**Issue by Gys** [necolas/react-native-web#349]
The global variable `__DEV__` is defined in React Native, but not in react-native-web. Therefore throwing errors in my cross platform backend code. Would be nice to have this var defined as part of this package.

**Comment by Gys** [comment]
I now realise `__DEV__` is a constant defined by React Native which distinguishes between test releases and live releases. As react-native-web probably has no such distinction it does not make sense to add such variable ? Although for compatibility it still would be nice.

**Comment by necolas** [comment]
You can set that variable using webpack's define plugin (similar to how process.env.NODE_ENV is set)
