### ISSUE TITLE
TextInput defaultValue is not changed at state change ?

### ISSUE THREAD

**Issue by Gys** [necolas/react-native-web#350]
The TextInput component does not update the defaultValue property when the state changes.

Current behaviour:

http://codepen.io/anon/pen/oByjmZ

Expected behaviour:

This codepen shows this.state.data in a Text and a TextInput component. I would expect in the output that both values are the same. Instead the values are different.

Using OSX (latest) and Chrome (latest).

**Comment by necolas** [comment]
That's how `defaultValue` works. You should use `value` if you want to control the component's value via state.

https://facebook.github.io/react/docs/uncontrolled-components.html#default-values

**Comment by Gys** [comment]
I am very sorry to come back to this.

It seems `value` cannot be changed by the user at all, only by state ? However, I want to set an initial value by using state and then the user can change that value: the page is constructed while 'getData' fetches data from the backend that subsequently can be edited.

As a more general thought: what benefit does `defaultValue` have if any initial state related initial value can also be set by this.state = {valueToEdit: initialValue} in the constructor ?

**Comment by Gys** [comment]
For anybody who ends up here with the same problem, the solution is to update the state with every change in the field value:
`onChangeText={(text) => this.setState({data: text})}`
