### ISSUE TITLE
Is it possible to append custom className ?

### ISSUE THREAD

**Issue by achtan** [necolas/react-native-web#355]
hi, Is it possible to append custom className ?

for example:
`````
<Text appendClassName="hoverable">Foo</Text>
`````
so in my web-specific-css i can now implement `:hover` efects

**Comment by necolas** [comment]
Use 'className'

**Comment by achtan** [comment]
but its not working on `TouchableOpacity` component

**Comment by kkamperschroer** [comment]
I'm seeing this issue as well with specifically `TouchableOpacity` and `TouchableHighlight`. Seems to me like it's components that render out as `button` elements. Should this issue be potentially re-opened and re-named to reflect the actual issue?

**Comment by achtan** [comment]
@necolas can you please reopen this issue?

**Comment by necolas** [comment]
It's more a duplicate of #65
