### ISSUE TITLE
end2end example

### ISSUE THREAD

**Issue by drewwells** [necolas/react-native-web#359]
**What is the current behavior?**
Attempting a basic ReactNative app with webpack config

https://gist.github.com/drewwells/27411bd34c270a37e5274184742c7c2e

The app builds, but throws require is not defined errors: `module.exports = require("url");`

**What is the expected behaviour?**
App loads as expected within react-native environment

**Steps to reproduce**

1. webpack-dev-server webpack.config.js
2. open localhost:8080

**Environment (include versions)**

OS: Sierra
Device: Mac
Browser: Chrome
React Native for Web (version): 0.0.70
React (version): 15.4.2

**Comment by drewwells** [comment]
It would be helpful to include a complete example with webpack config that can be run locally.

**Comment by necolas** [comment]
Hi. There are multiple community-created examples you could look through. If you're trying to run that build in a browser while all the node_modules are `externals`, then that will probably blow up in the browser.

**Comment by drewwells** [comment]
There are plenty of blog posts on this, but most are out of date and no longer work. Is there a defacto example to start from.

Without adding node_modules as externals, it blows up trying to import node code for use by the browser. Doing a npm install with the recommended packages adds node dependencies ie. fsevents. How do these work without those packages being available via react-native-web?

**Comment by necolas** [comment]
> it blows up trying to import node code

What is "it"? There must be a module in your app that is pulling in node-only dependencies that won't work in a browser.

**Comment by drewwells** [comment]
it is: https://gist.github.com/drewwells/27411bd34c270a37e5274184742c7c2ej

The only dependencies are 'React' and 'React-Native' which is mapped to react-native-web

**Comment by necolas** [comment]
You've got `target: 'node'` which isn't going to produce a binary that runs in a browser
