### ISSUE TITLE
Suggestion: Image tintColor

### ISSUE THREAD

**Issue by c-h-** [necolas/react-native-web#362]
Now that `tintColor` is a [standard prop](https://facebook.github.io/react-native/docs/image.html#style) instead of iOS only, it'd be cool to have some support on Web. There's not a super easy way to do this on web that I'm aware of, but for SVG images at least there's [fill](https://css-tricks.com/almanac/properties/f/fill/). My understanding is that CSS filters won't work since they only modify the existing image's colors (you can't simply fill the image). Perhaps a CSS mask could be used to achieve image fill regardless of image type?

@necolas if you're open to supporting `tintColor` and can point me to where I could implement it I'd be happy to give it a go.

**Comment by necolas** [comment]
Supporting `tintColor` is not a priority right now (I suspect that it would be tricky for mobile web too). But feel free to explore your ideas and what's possible
