### ISSUE TITLE
TouchableOpacity/Highlight Glows?

### ISSUE THREAD

**Issue by KjellConnelly** [necolas/react-native-web#369]
I'm not sure why, but TouchableOpacity/Highlight glows with a bluish tint around it and I'm not really sure how to get rid of it. Not sure if this is mimicing the Android functionality, but iOS apps don't continue to glow after being touched. Is this on purpose? And if so, is there a work around? Tried changing shadowRadius and boxShadow styles, which don't seem to work.

**Comment by necolas** [comment]
I'll be fixing this soon in #310
