### ISSUE TITLE
Responsively embed react native application and render in web via container?

### ISSUE THREAD

**Issue by MovingGifts** [necolas/react-native-web#372]
Hello,

Instead of having to create a react website version, is it possible to write once the react native app, and use that (responsively) as the website too. So when you visit from a web url, using react navigation for example, it would show the app full screen, just like you would a responsive website.

This is a useful idea because of the inconsistencies in components between react native and react, and if we can somehow render the react native app as the responsive website, that would remedy the inconsistencies and having to have a separate react web version. I figured the routing solution would be react navigate since I read it can work for both react and react native.

So essentially some sort of wrapper/container to wrap/contain the react native app and serve it as the website version too, so it's really universal if you know what I mean.

Is this possible with `react-native-web` or any other known way?

**Comment by necolas** [comment]
Yep, `react-native-web` can help you do that
