### ISSUE TITLE
Question: How to apply StyleSheet to DOM elements?

### ISSUE THREAD

**Issue by reggi** [necolas/react-native-web#380]
I was under the assumption that I'd be able to apply `styles` to any dom element as well. I realize now that's not the case. I have an `<a>` tag and I'm trying to pass in styles from `StyleSheet` and it's not working. Is there any way to do this? When I log the styles, they render as a integer, and not as a object.

> The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.

```js
<a style={adminSidebarItemStyles.anchor} href='https://google.com'>
Hello
</a>
```

**Comment by necolas** [comment]
Use the `createDOMElement` export
