### ISSUE TITLE
SSR window is not defined

### ISSUE THREAD

**Issue by LeoLeBras** [necolas/react-native-web#387]
**What is the current behavior?**
SSR doesn't work. I get the following error message when trying to render elements with ```node.js```:
```
/Users/.../node_modules/react-native-web/dist/modules/modality/index.js:22
var proto=window.Element.prototype;
          ^

ReferenceError: window is not defined
```
Rolling back to ```react-native-web@0.0.71``` resolved the issue.

**Steps to reproduce**
```shel
$ git clone https://github.com/LeoLeBras/react-native-web-ssr.git
$ cd react-native-web
$ yarn
$ yarn start
```

**Environment (include versions)**

OS: macOS Sierra
~~Browser:~~ Node: ```7.5.0```
React Native for Web (version): ```0.0.76```
React (version): ```15.4.2```

P.S: Thank you. This library is *awesome* :rocket:.

**Comment by necolas** [comment]
Thanks. This should be fixed in 0.0.77
