### ISSUE TITLE
which react-native version is this compliant to?

### ISSUE THREAD

**Issue by talarari** [necolas/react-native-web#389]
I'm trying to use this react-native-svg, getting lots of errors, that might be because they have specific versions of react-native-svg matching specific versions of react-native and react.

```
react-native-svg >= 3.2.0 only supports react-native >= 0.29.0
react-native-svg >= 4.2.0 only supports react-native >= 0.32.0
react-native-svg >= 4.3.0 only supports react-native >= 0.33.0
react-native-svg >= 4.4.0 only supports react-native >= 0.38.0 and react >= 15.4.0
react-native-svg >= 4.5.0 only supports react-native >= 0.40.0 and react >= 15.4.0
```
which api version is react-native-web using?

**Comment by necolas** [comment]
Yeah it looks like that library is looking for `react-native` and isn't compatible with a DOM environment (e.g., it uses native APIs or private RN APIs)

**Comment by code-by** [comment]
I'm use RN 0.5.1, which is most new version of RNW I could use?
