### ISSUE TITLE
something wrong when using with react-native-router-flux

### ISSUE THREAD

**Issue by prolok** [necolas/react-native-web#392]
**What is the current behavior?**

When a new scene is pushed by the router with redux, all the elements inside the div cannot be clicked. If the scene is replaced by the same router, all elements work fine. The parent div with absolute position seems blocking the elements.

**What is the expected behaviour?**

When a new scene is pushed by the router with redux, all the elements should be able to be clicked as normal

**Steps to reproduce**

1. Create the router following their ([example](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md))
2. Create the first page with a simple action to push the second page, while the second page has any TextInput and/or TouchableOpacity component(s)
3. Build the project using react-native-web
4. load the built bundle in a html page, try navigate to the second page
5. The input or button element in the page cannot be clicked (the mouse even cannot detect it)

**Environment (include versions)**

OS: MacOS 10.11.5
Browser: Chrome 56.0.2924.87, FireFox 51.0.1
(But Safari 9.1.1 works fine)
react-native-web: 0.0.75
react: 15.4.2
react-native: 0.40.0
react-native-router-flux: 3.38.0
react-redux: 5.0.3
redux: 3.6.0

**Comment by necolas** [comment]
Hi please can you make a repo that reproduces the issue.

**Comment by prolok** [comment]
This is my first creating [a repo](https://github.com/prolok/rnrf-web-demo) on github, hope I have not missed any files.
Since the case is only happened when using with react-native-web (the same code works perfectly fine on iOS and android), thus I only put the related part in the repo.

Many thanks!

**Comment by necolas** [comment]
The build failed

```
ERROR in ./src/views/MainView.js
Module build failed: SyntaxError: Unexpected token (27:12)

  25 |     render() {
  26 |         return (
> 27 |             <Provider store={store}>
     |             ^
  28 |                 <RouterWithRedux
  29 |                     panHandlers={null} >
  30 |                     <Scene key="modal" component={Modal} >

BabelLoaderError: SyntaxError: Unexpected token (27:12)

  25 |     render() {
  26 |         return (
> 27 |             <Provider store={store}>
     |             ^
  28 |                 <RouterWithRedux
  29 |                     panHandlers={null} >
  30 |                     <Scene key="modal" component={Modal} >
```

**Comment by necolas** [comment]
It's likely that a router for native apps isn't going to work as desired on web (which needs the URL to be updated)

**Comment by prolok** [comment]
I missed the hidden config files.... The [repo](https://github.com/prolok/rnrf-web-demo) has been updated, can you help to check again? Many thanks, @necolas

**Comment by prolok** [comment]
Found that after any actions by the router, the components' "pointer-events" are set to "none", thus the components cannot be targeted by the mouse:
![before](https://cloud.githubusercontent.com/assets/5403854/23982847/212611f0-0a4b-11e7-89d5-9fe1da7c906f.png)

Setting it to "auto" using the inspector can make all the things work again, however I have no idea on how I can implement it from my source code:
![after](https://cloud.githubusercontent.com/assets/5403854/23982846/2125ba16-0a4b-11e7-976f-299ec37423d1.png)

**Comment by necolas** [comment]
This should be fixed in v0.0.79

**Comment by DivyanshuAlok** [comment]
@prolok this completely off the topic but can you just help me by sharing a sample project which has react native router flux in react native web project

**Comment by prolok** [comment]
@DivyanshuAlokmy my project is actually using very old version (react-native is 0.40.0 and react-native-router-flux is just 3.38.0), not sure whether the new version is good to use with react-native-web or not.

You may see my [demo](https://github.com/prolok/rnrf-web-demo) for the old setup.
