### ISSUE TITLE
AsyncStorage.getAllKeys() does not behave like React Native's API

### ISSUE THREAD

**Issue by aaroncraig10e** [necolas/react-native-web#399]
The documentation for React Native's AsyncStorage API's `getAllKeys()` says that the function should take a callback as the first argument which is a "Function that will be called the keys found and any error."

However, the react-native-web version does not accept any parameters.

While it is possible to use the API with the promise object returned by the function, it probably should also handle the callback, as documented.

I'll open a PR for this in the morning with a fix, unless there is some reason for the omission.

**Comment by necolas** [comment]
All the functions support the callback style usage in RN: https://facebook.github.io/react-native/docs/asyncstorage.html
