### ISSUE TITLE
StyleSheet: shorthand properties overriding specific values

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#40]
Example:

```js
const style = StyleSheet.create({
  root: {
    borderStyle: 'none',
    borderBottomStyle: 'solid'
  }
})
```

The generated CSS depends on alpha-sorting style properties, so the `borderStyle` rule comes after `borderBottomStyle` and means the second style is never applied.

Options:

1. Redo the logic, probably to expand shorthand styles. At the least, the sorting needs to be fixed as alpha-sort places shorthands after longhands for some properties.
2. Do not respect order of styles (i.e., it doesn't work like CSS)

**Comment by necolas** [comment]
This is relatively easy to fix if we followed RN in only allowing a single value for the shorthand properties (see below). But that is quite tricky to do if you want to support non-px units. For example, you could have a value like `padding: 'calc(100% - 5px)'`

```js
var styleShortHands = {
  borderWidth: [
    'borderBottomWidth',
    'borderLeftWidth',
    'borderRightWidth',
    'borderTopWidth'
  ],
  borderColor: [
    'borderBottomColor',
    'borderLeftColor',
    'borderRightColor',
    'borderTopColor'
  ],
  borderRadius: [
    'borderBottomLeftRadius',
    'borderBottomRightRadius',
    'borderTopLeftRadius',
    'borderTopRightRadius'
  ],
  borderStyle: [
    'borderBottomStyle',
    'borderLeftStyle',
    'borderRightStyle',
    'borderTopStyle'
  ],
  margin: [
    'marginBottom',
    'marginLeft',
    'marginRight',
    'marginTop',
  ],
  padding: [
    'paddingBottom',
    'paddingLeft',
    'paddingRight',
    'paddingTop'
  ]
}

const explodeStyle = (style) => {
  return Object.keys(style).reduce((resolvedStyle, key) => {
    var expandedProps = styleShortHands[key]
    var value = style[key];
    if (expandedProps) {
      expandedProps.forEach((prop, i) => {
        resolvedStyle[expandedProps[i]] = value;
      })
    } else{
      resolvedStyle[key] = value;
    }
    return resolvedStyle;
  }, {});
}
```

**Comment by phuu** [comment]
@necolas Isn't tricky case something like `padding: 1px 2px 4em`, rather than the `calc` example?

**Comment by necolas** [comment]
That's pretty easy because you can split on the space and determine there are 3 values. But splitting on space is problematic because the string value could be more complicated and contain CSS functions.

**Comment by vjeux** [comment]
The way it works on React Native is that the more specific takes priority.

So {borderTopWidth: 5, borderVerticalWidth: 2, borderWidth: 1} will result in {top: 5, right: 1, bottom: 2, left: 1}

**Comment by vjeux** [comment]
Also react native doesn't accept composite string values, only numbers. You can't do borderWidth: '5px 3px'.

In practice, while handy, a lot of people get confused as to what numbers represent what. Being explicit here was a win for react native, I haven't seen anyone struggle with this.

**Comment by necolas** [comment]
Thanks!
