### ISSUE TITLE
General: RN4W app as React component?

### ISSUE THREAD

**Issue by greenais** [necolas/react-native-web#403]
Is it possible to warp RN4W into React component and use it along with other regular React components (i.e. on one web page) or inside them (as a child)?

All examples are about RN4W as root component, could it be child?

**Comment by RangerMauve** [comment]
`View` components in react-native-web are just regular React components that eventually render DOM nodes. I don't see why it wouldn't work.

**Comment by necolas** [comment]
Yes that will work as it uses react-dom

**Comment by greenais** [comment]
Could you please give some short example of such wrapping? I mean example of RNW exportable React component which could be imported as a child to another React component? Each example ends with RNW own renderer while React uses it's own one. I just don't see how to proceed with such embedding
What I'm looking for:
```
import RnwComponent from 'rnw-component'
<ReactComponent>
  <MyRnwComponent {...props} />
</ReactComponent>
```

How this <MyRnwComponent> should look like in order to be exported/imported?
I've tried several options (with and without AppRegistry) but with no good yet
Thank you in advance!
