### ISSUE TITLE
Content of ScrollVirew hide the scrollbar

### ISSUE THREAD

**Issue by BobCaSUaL** [necolas/react-native-web#405]
**What is the current behavior?**
The scrollbar of the scrollview is hidden by the scrollview content

**What is the expected behaviour?**
The scrollbar should appear in front of the content.
 
**Steps to reproduce**
make a scrollview with a full width content

<ScrollView style={{backgroundColor: '#AAA'}}>
  <View style={{height: 500, width: null, backgroundColor: '#FFF'}} />
</ScrollView>

**Environment (include versions)**

OS: MacOS
Device: iMac
Browser: Electron (Chrome)
React Native for Web (version): 0.0.72
React (version): ^15.3.2

This problem can be solved by applying the `transform: translateZ(0);` property to root element of the scrollview instead of the the contentContainer.

**Comment by necolas** [comment]
I can't reproduce this issue in Chrome on Mac https://www.webpackbin.com/bins/-Kh-2ZeEI6U3GjHmpD6B

Do you have a screenshot / video of the issue and fix in Electron?

Please can you also upgrade to the latest version of RNW to confirm the issue still exists.

**Comment by necolas** [comment]
Ping

**Comment by BobCaSUaL** [comment]
Sorry for the late response. The problem is not present in newer release of our app. We do not known what the matter was.
