### ISSUE TITLE
Error importing react-native-web, version >0.0.72

### ISSUE THREAD

**Issue by hedegren** [necolas/react-native-web#407]
Awesome library first of all! :) 

When importing:
`import ReactNative from 'react-native-web';
`
on version >0.0.72 i get error: 
`TypeError: Cannot read property 'addEventListener' of null
`

Version 0.0.72 works as expected.

**Comment by necolas** [comment]
Please can you include more some more information:

1. Can you reproduce with 0.0.80?
2. What environment, node or browser?
3. What is the stacktrace?

**Comment by necolas** [comment]
I'm going to close this until there's enough info
