### ISSUE TITLE
package bundle.js is too big

### ISSUE THREAD

**Issue by shinehuang** [necolas/react-native-web#410]
**What is the current behavior?**
I run the React-native sample HelloWorld，and i try to package my bundle.js with react-native-web；
It is success！But the bundle is too big，about 1191kb；

**What is the expected behaviour?**
I would like to package my bundle as i import.For example,my code has not ListView components，but my bundle.js is contain it；

**Environment (include versions)**
Mycode is here：
`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class ReactNativeWeb extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.web.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('ReactNativeWeb', () => ReactNativeWeb);
AppRegistry.runApplication('ReactNativeWeb', { rootTag: document.getElementById('react-app') });`

I want to know can i use some params to make my bundle.js not contains something i am not import？As Listview？

**Comment by necolas** [comment]
Is that the non-compressed bundle size? #102 will help
