### ISSUE TITLE
Jest throw error during import of SampleApp component

### ISSUE THREAD

**Issue by ramki1979** [necolas/react-native-web#412]
**What is the current behavior?**
TypeError: Cannot read property 'id' of null

      at Function.runApplication (node_modules\react-native-web\dist\apis\AppRegistry\index.js:73:34)
      at Object.<anonymous> (src\App.js:89:52)
      at Object.<anonymous> (src\App.test.js:4:38)
      at process._tickCallback (internal\process\next_tick.js:103:7)

Link to minimal test case:
App.test.js with only import's without any test case.
`import React from 'react'`
`import App from './App'`

**What is the expected behaviour?**
Console test output: Your test suite must contain at least one test.

**Steps to reproduce**
I have the default jest test file with App component import..
1. `import App from './App'` throwing the above error in Jest

**Environment (include versions)**
I used create-react-app and installed RNW and replaced the default App component of React with Sample App component provided at RNW.

OS: Windows 10
Device:
Browser:
React Native for Web (version): 0.0.80
React (version):15.4.2

I believe I missed some settings, though `moduleNameMapper` is already configured in `createJestConfig.js`
>

**Comment by necolas** [comment]
Looks like you're running `AppRegistry` in your `App` file (it's throwing an error because there's no root node). If so, you shouldn't be testing a file that contains your app's top-level render function

**Comment by ramki1979** [comment]
Thanks After seeing the RNW source, I got what I am doing wrong, so I moved My App component to separate file with an export and loading new component file, and came here to close the issues.
@necolas closed the issue already by saying what I should do. Thanks for quick reply.
