### ISSUE TITLE
Jest reports: Cannot read property 'tagName' of null when simulate click on Text Wrapper component.

### ISSUE THREAD

**Issue by ramki1979** [necolas/react-native-web#413]
**What is the current behavior?**
jest reports Cannot read property 'tagName' of null when simulate click on Text component.
Link to minimal test case: (template: )

**What is the expected behaviour?**
Expect Jest to pass this test case.

**Steps to reproduce**
```javascript
import TestUtils from 'react-addons-test-utils'

const FacebookLoginButton = props => {
    return (
        <Text onClick={props.clicked}>{props.children}</Text>
    )
}

it('facebook button click', () => {
    function fbButtonClick() {
      console.log('button clicked!!')
    }
    let fbButton = TestUtils.renderIntoDocument(
    <FacebookLoginButton clicked={fbButtonClick}>Login</FacebookLoginButton>)
    TestUtils.Simulate.click(ReactDOM.findDOMNode(fbButton))
  })
```

**Environment (include versions)**

OS: Windows 10
Device: PC
Browser: jsDOM
React Native for Web (version): 0.0.80
React (version): 15.4.2

fbButton  is null, When I replace FacebookLoginButton with Text the test case is passed.

with Enzyme it work!
```javascript
it('facebook button click', () => {
    let fbButton = mount(
    <FacebookLoginButton clicked={fbButtonClick}>Login</FacebookLoginButton>)
    console.log(fbButton)
    fbButton.simulate('click')
    //TestUtils.Simulate.click(ReactDOM.findDOMNode(fbButton))
  })
```
What I am doing wrong with `react-addons-test-utils`

**Comment by necolas** [comment]
Sorry, I don't know!
