### ISSUE TITLE
ScrollView.scrollToEnd is not a function

### ISSUE THREAD

**Issue by dsernst** [necolas/react-native-web#416]
**What is the current behavior?**

Calling `scrollView.scrollToEnd()` triggers a fatal error:

```
Uncaught TypeError: _this2.scrollView.scrollToEnd is not a function
```

**What is the expected behaviour?**

It should match the [native ScrollView.scrollToEnd method](https://facebook.github.io/react-native/docs/scrollview.html#scrolltoend).

**Environment (include versions)**

Browser: Chrome
React Native for Web (version): 0.0.81
React (version): 15.4.2

**Comment by dsernst** [comment]
Related to #381

**Comment by necolas** [comment]
Moved to #434
