### ISSUE TITLE
Better "Getting Started" instructions for webpack / babel?

### ISSUE THREAD

**Issue by dsernst** [necolas/react-native-web#417]
This is a really incredible library, but I found it had a surprisingly steep learning curve for setting everything up.

It took me a while to get everything working. In particular, the webpack / babel config was not intuitive.

Once I got it working, I created this simple little `Hello world` example: https://github.com/dsernst/react-native-web-hello-world

Are you looking for PRs to improve to Getting Started guides?

**Comment by necolas** [comment]
Hey, did you see the existing guides?

**Comment by necolas** [comment]
I pushed a change that hopefully clarifies some details

**Comment by dsernst** [comment]
Yes, I studied the existing guides, but didn't find them nearly as simple as react-native.

Anyway, renaming them to `Getting-Started.md` is good.

Hopefully other people will find it easier, or if they need a reference they can use the [simple Hello World I put together](https://github.com/dsernst/react-native-web-hello-world).

---------------

Great work overall with this project, it's super cool and let me relaunch a native app (6 months of work) on the web in under a day.

**Comment by necolas** [comment]
> let me relaunch a native app (6 months of work) on the web in under a day.

Nice!

**Comment by necolas** [comment]
Was the barrier mainly setting up webpack/babel correctly?

**Comment by necolas** [comment]
OK I'll see what I can do to provide a more complete introduction/suggestion for getting started from scratch with those. Thanks

**Comment by hzoo** [comment]
Mind writing what was difficult about setting up the Babel config?

**Comment by dsernst** [comment]
Thanks for asking, @hzoo.

I remember having trouble figuring out that I need to install a `stage-0` preset, and to support JSX. And that I needed a `.babelrc` and what it needed to look like.

I also spent a while going through the webpack tutorials again, getting re-familiarized with `webpack-dev-server` etc.

These are all things I had done a long time ago, but hasn't messed with in a while since React Native ships with them already.

**Comment by hzoo** [comment]
Huh interesting, @skevy is that also a result of the issues with plugin ordering? Will be trying to solve that in https://github.com/babel/babel/issues/5623
