### ISSUE TITLE
How can I support EXIF to display images uploaded from iPhone properly?

### ISSUE THREAD

**Issue by sertony** [necolas/react-native-web#419]
**What is the current behavior?**

Images uploaded from the phone are rotated in Image component due to unsupported EXIF orientation.

**What is the expected behaviour?**

Images should be displayed in a proper orientation.

**Environment (include versions)**

OS: iOS
Device: iPhone
Browser: Safari
React Native for Web (version): 0.0.81
React (version): 15.4.2

**Comment by necolas** [comment]
You'll probably want to use an image library when uploading to correct for that. This project is just a renderer
