### ISSUE TITLE
View: perf optimizations for non-Chrome browsers

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#42]
In non-Chrome browsers, especially Safari, performance is crippled by nested flexbox columns. Performance is not quite so bad, but still bad, when nesting flexbox columns and rows.
- [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=150445)
- [Anecdotal IE report](https://mobile.twitter.com/cameronhunter/status/667762118817484800)

It can be worked around by interrupting the chain of nested flexboxes with an element that is not `display:flex`. This is bad news for `flexGrow:1` propagation. I wonder if RNW could determining when it is safe to insert a non-flex wrapper (i.e., when there's no use of `flex-*` sizing properties on child elements). Could also log a warning when we know there is deep nesting.

**Comment by dorthwein** [comment]
Any progress on this?  Half day later of banging my head on my safari was running so slow.... ;(

**Comment by necolas** [comment]
For now, you can set `display:block` on a `View` that you know doesn't need flexbox layout.

**Comment by dorthwein** [comment]
Thanks!!!!

**Comment by necolas** [comment]
I'm going to close this and will add a note to the docs

1. The next version of Safari fixes their flexbox performance issues.
2. Using `display:block` is the workaround and there's no good way to apply it automatically.
