### ISSUE TITLE
Invalid props.style key `aspectRatio`

### ISSUE THREAD

**Issue by jasonfma** [necolas/react-native-web#420]
**What is the current behavior?**
Adding aspectRatio to a style results in a warning and is not respected.

```javascript
import React from 'react';
import { 
  View,
  Text,
  StyleSheet,
} from 'react-native';


const App = () => {
  return (
    <View style={{ aspectRatio: 1 }}>
      <Text>Hello world</Text>
    </View>
  );
};

export default App;
```
Error:
```
bundle.js:823 Warning: Failed prop type: Invalid props.style key `aspectRatio` supplied to `View`.
Bad object: {
  "aspectRatio": 1
}
```
**Environment (include versions)**

OS: macOS 10.12.4
Device: 
Browser: Chrome
React Native for Web (version): 0.0.81
React (version): 15.4.2

**Comment by necolas** [comment]
Yeah, web doesn't support `aspectRatio` (yet, although may be tricky). Which version of React Native introduced it?

**Comment by jasonfma** [comment]
Looks like RN 0.40 introduced it - that's when it shows up in their docs. http://facebook.github.io/react-native/releases/0.40/docs/layout-props.html

**Comment by necolas** [comment]
Next version it won't error but won't do anything either. See #427

**Comment by yairopro** [comment]
There's no plan to develop this feature in RN-web ?
