### ISSUE TITLE
NODE_ENV == 'production' then View.propTypes = undefined

### ISSUE THREAD

**Issue by KjellConnelly** [necolas/react-native-web#423]
One of the plugins I use uses View.propTypes to get style information. While it works with webpack-dev-server, webpack -p fails due to `View.propTypes = undefined`

While looking through my bundle.js, I came across this line of code:
`process.env.NODE_ENV !== "production" ? View.propTypes = _ViewPropTypes2.default : void 0;`

Is there a reason this is here? Why would you want View.propTypes to be void in production, but not in development? If not, can we fix this?

**Comment by necolas** [comment]
That plugin needs to import `ViewPropTypes` from React Native

**Comment by necolas** [comment]
Proptypes aren't used in production so including them is a waste

**Comment by RangerMauve** [comment]
@necolas A dependency in my project, [react-native-hyperlink](https://github.com/obipawan/react-native-hyperlink) is relying on [Text.propTypes](https://github.com/obipawan/react-native-hyperlink/blob/master/Hyperlink.js#L98) to be defined so that it can define it's own propTypes. Any suggestions on what to do to make this work for the production build?

**Comment by KjellConnelly** [comment]
RangerMauve - The component I was working with also had Text.propTypes. Unfortunately there wasn't TextPropTypes to import, so as a workaround, I just made a pull request to this person's project and used ViewPropTypes in place of Text.propTypes and View.propTypes. For this component, it looks the same to me, so whatever style differences there may be, they weren't significant enough for me to care. 

You could do this, or possibly define your own TextPropTypes by copying the styles from the React Native GitHub page, though you would have to maintain that and any changes yourself.

**Comment by RangerMauve** [comment]
Thanks for the suggestion, @KjellConnelly
I was trying to monkey-patch Text.propTypes at runtime, but was unable to because the library code would be loaded before my code (curse you, es6 imports!).

I'l see what I can do with modifying the library directly.

**Comment by necolas** [comment]
Oh I see. I think the fix is to patch the babel plugin so that it assigns an empty object to proptypes in production, rather than void. That will at least avoid errors if a module is trying to access a specific proptype

**Comment by RangerMauve** [comment]
@necolas Where would I find the relevant code to modify?

**Comment by necolas** [comment]
Looks like it's here: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/src/remove.js#L34

**Comment by RangerMauve** [comment]
@necolas That's what I thought, but you're using the `wrap` mode so that code shouldn't be executing.

**Comment by galkahana** [comment]
There's a new version of babel-plugin-transform-react-remove-prop-types which updates wrap to replace with empty instead of replacing with null.

**Comment by necolas** [comment]
Fix is in v0.0.89
