### ISSUE TITLE
Investigate implementing yoga 'aspectRatio'

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#427]
aspectRatio: https://facebook.github.io/yoga/docs/aspect-ratio/

https://codepen.io/aghassemi/pen/RpdaKM

**Comment by jordwalke** [comment]
I don't happen to know anything about the future direction. Are you looking to reimplement the behavior?

**Comment by necolas** [comment]
I think it would be relatively easy to implement. However, if the only way to trigger "RTL mode" in React Native is to use `I18nManager`, and that _also_ flips `right` to `left`, then it doesn't seem very useful to support `start/end`. And Yoga doesn't flip values, right (`textAlign:left`)?

**Comment by MoOx** [comment]
Would love to see this available in RNW. Anything planned? Can I help?

**Comment by necolas** [comment]
Feel free to investigate. I haven't got any plans. I don't know if building this into StyleSheet for web is viable; maybe needs an `AspectRatio` component a bit like RN needs `LinearGradient` component but RNW supports `backgroundImage: linear-gradient(...)`.

**Comment by MoOx** [comment]
Indeed, that could be tricky to implement in StyleSheet.

I tried to make a component based on the absolute stretch + padding-bottom trick, but that don't work correctly on Firefox with flexbox (this require display block to get this working - at least for now - see https://stackoverflow.com/a/39069462/988941)

I may try to share this one day or another (but my current code is in reasonml so I would have to convert I guess).

**Comment by necolas** [comment]
I think you could use JS rather than CSS to calculate the dimensions once you're in a component

**Comment by necolas** [comment]
Here is the `AspectRatio` component I wrote for Twitter Lite. (It doesn't handle everything the Yoga aspect ratio does. Only width-based)

```js
import { any, func, number } from 'prop-types';
import { createElement, StyleSheet, View, ViewPropTypes } from 'react-native';
import React, { Component } from 'react';

class AspectRatio extends Component {
  static displayName = 'AspectRatio';

  static propTypes = {
    children: any,
    onLayout: func,
    ratio: number.isRequired,
    style: ViewPropTypes.style
  };

  render() {
    const { children, onLayout, ratio, style } = this.props;
    const percentage = 100 / ratio;

    return (
      <View onLayout={onLayout} style={[styles.root, style]}>
        {createElement('div', {
          style: [styles.ratio, { paddingBottom: `${percentage}%` }]
        })}
        {createElement('div', {
          children,
          style: styles.content
        })}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  root: {
    display: 'block',
    overflow: 'hidden'
  },
  ratio: {
    display: 'block',
    width: '100%'
  },
  content: {
    bottom: 0,
    height: '100%',
    left: 0,
    position: 'absolute',
    top: 0,
    width: '100%'
  }
});

export default AspectRatio;
```

**Comment by necolas** [comment]
I think React Native should move this style property to `View`/`Image` props like it does for non-standard `pointerEvents`. Then it would simpler to mimic on web too.

**Comment by necolas** [comment]
No good way to do this right now, and there's little progress getting this feature into CSS.

**Comment by petrbela** [comment]
An alternative solution involves calculating the size using `onLayout`. Note that this may appear janky as the first render will not know the right size. Credit goes to Evan https://baconbrix.gitbook.io/react-native-web/styling/aspect-ratio

```tsx
import React, { useState } from 'react'
import { LayoutRectangle, StyleSheet, View, ViewProps } from 'react-native'

export interface AspectRatioProps extends ViewProps {
  children?: React.ReactNode
}

export default function AspectRatio({
  children,
  style,
  ...props
}: AspectRatioProps) {
  const [layout, setLayout] = useState<LayoutRectangle>()

  const { aspectRatio = 1, ...s } = StyleSheet.flatten(style) || {}

  style = [s, { aspectRatio }]

  if (layout) {
    const { width = 0, height = 0 } = layout
    if (width === 0) {
      style.push({ height, width: height * aspectRatio })
    } else {
      style.push({ height: width / aspectRatio, width })
    }
  }

  return (
    <View
      onLayout={({ nativeEvent: { layout } }) => setLayout(layout)}
      style={style}
      {...props}
    >
      {children}
      /* Or, to wait before rendering children until we know the size: */
      /* {layout ? children : undefined} */
    </View>
  )
}
```

**Comment by robert-nash** [comment]
Since aspect-ratio is now available in Chrome, would it be appropriate to 'translate' this to a native css property now?

I don't know much about the internals of React Native for Web but at the minute setting the aspectRatio style property on an element doesn't cause aspect-ratio to be added to the CSS which would be useful, to me at least, even though it only works in Chrome (and I assume Edge).

**Comment by yairopro** [comment]
Is this issue abandoned ?
