### ISSUE TITLE
position: fixed not working under ScrollView

### ISSUE THREAD

**Issue by xiaohanzhang** [necolas/react-native-web#430]
So I was try to implement a Modal like component. But seems "position: fixed" doesn't work under ScrollView.

I think it is because "position: fixed" and "transform" won't work together. [More info here](http://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children)

So I was wondering could we take out default "translateZ: 0" from ScrollView ?

**Comment by necolas** [comment]
Probably not a good idea to use position fixed in a scrollview (or in general anywhere other than near top-level nodes)

**Comment by RangerMauve** [comment]
You [can't use](https://facebook.github.io/react-native/docs/layout-props.html#position) `position: fixed` in react-native regardless, so this approach isn't scale-able.

**Comment by xiaohanzhang** [comment]
@necolas In that case, what will you recommend to implement Modal? I can't think anything else that can open a full screen size Modal from a small child component.

@RangerMauve react-native already have built in Modal. And it also have other native way to handle absolute positioning to viewport. I thought `position: fixed` will be the web equivalent for that.

**Comment by RangerMauve** [comment]
@xiaohanzhang A good approach with modals is to actually place the modal content outside of wherever the component is defined in the document. Essentially, your Modal component will create an element under `document.body` to actually store the content, and will use it's children to render to that DOM node when `visible=true`.

The main advantage to using this approach is that your modal can't be clipped in `overflow: hidden` containers that are higher up in the tree, as well as any other size or opacity related props.

If you're interested in adding a modal component to RNW, I'd suggest looking at how [material ui](http://www.material-ui.com/#/components/dialog) does it to see if their approach can be used here.

**Comment by xiaohanzhang** [comment]
@RangerMauve Thanks for your resources. I think I will take this approach.

**Comment by RangerMauve** [comment]
Awesome! Hopefully it goes well for you and you can get a PR into this repo so that everyone can use your hard work. :D

Also, I'm 99% sure that react-native takes a similar approach for rendering modals in native-land

**Comment by Rajkugupta** [comment]
how to use position fix in react native

**Comment by jailsonpaca** [comment]
I resolve this problem in this way: 
```
<View>
      <ScrollView style={{ marginTop: 50 }}>
        {...content...}
      </ScrollView>
      <FabVideo /> <--- putting the absolute element after the scrollview
    </View>
```
