### ISSUE TITLE
use with redux and react-native-router-flux error

### ISSUE THREAD

**Issue by xiaomilii** [necolas/react-native-web#433]
![qq 20170420113112](https://cloud.githubusercontent.com/assets/18210277/25212784/1681ca0c-25bf-11e7-879a-f380299396b2.png)

OS: windows7
Device:
Browser:chrome
React Native for Web (version): 0.0.81
React (version):15.4.2
"react-redux": "^5.0.3",
"redux": "^3.6.0",

**Comment by necolas** [comment]
Looks like a Babel configuration error in your app as it is telling you it doesn't recognize jsx
