### ISSUE TITLE
ScrollView: implementation updates

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#434]
Need to remove legacy props and add support for:

* ~scrollToEnd~
* ~animated scroll~
* sticky headers

Investigate `pagingEnabled`

**Comment by hfter789** [comment]
@necolas Hi. Is there any update on scrollToEnd? Our application needs this to work because we want to show the latest message in the conversation which is at the bottom. What is the current workaround for this problem?

**Comment by mroswald** [comment]
@necolas is `onMomentumScrollBegin` supposed to work? If not I could image tackling that

https://www.webpackbin.com/bins/-KmQzsTmW19caKVtxf4w

**Comment by necolas** [comment]
No, it was an iOS-specific property that has been removed from the latest version of RN: http://facebook.github.io/react-native/releases/0.45/docs/scrollview.html

**Comment by Connorelsea** [comment]
Anyone working on scrollToEnd()? Would be extremely useful and if not I could try to tackle it.

**Comment by lishoulong** [comment]
@necolas ,when the sticky headers is supported? Now my project use the stickyHeaderIndices props, but the react-native-web is not docked to the top of the screen.

**Comment by WillSquire** [comment]
Any elegant workarounds in the meantime for the `stickyHeaderIndices ` issue?
