### ISSUE TITLE
Get rid of outlineColor warning

### ISSUE THREAD

**Issue by KjellConnelly** [necolas/react-native-web#435]
``` javascript
<TextInput style={{outlineColor:"red"}} />
```

Even though this seems to actually work in the browser, I get a React warning for React-Native-Web in the console for this. Strangely enough, I don't get a warning for React-Native on iOS. Haven't check android though.

Can we silence this warning since it actually does work?

**Comment by necolas** [comment]
Why are you using that style prop?

**Comment by KjellConnelly** [comment]
On iOS, I don't expect there to be a focus ring color, so it makes sense for React Native to not have that. But for web, by default, there is a light blue focus ring color when I use the TextInput component and it is focused. 

So in a way, yes, I am asking for support to change the focus ring color when using the keyboard. But due to the way web is already handled, outlineColor already works exactly how I would expect it to, other than the issue with React shouting that it isn't a valid prop in the console.

**Comment by necolas** [comment]
> there is a light blue focus ring color when I use the TextInput component and it is focused

Yeah that's true. RNW will display a focus ring on TextInput even if you're using touch/mouse rather than keyboard. Is it the whole ring you want to remove?

**Comment by KjellConnelly** [comment]
@necolas I don't want to remove the whole ring. That's accomplished by:
```javascript
<TextInput style={{outline:"none"}} />
```

The application I'm working on has a specific color palette, and the default blue isn't the color I want showing up. I still do want a glow though, just not that color.
```javascript
<TextInput style={{outlineColor:"rgb(30,212,40)"}} />
```

**Comment by necolas** [comment]
Thanks. Added support in 0.0.85
