### ISSUE TITLE
Missing React Native version compatibility documentation

### ISSUE THREAD

**Issue by ttraenkler** [necolas/react-native-web#436]
Thanks for this great pioneering project. I would love to see the idea of sharing code between React and React Native flourish.

As a current user of react-native-web, I cannot find a documentation of which react-native version (latest: 0.43) react-native-web (latest: 0.0.85) targets to be compatible with. I have found some references in the docs to 0.21, which may have been the version react-native-web may have been "forked" from. 

It would be helpful if there is a statement in the readme which version react-native-web is compatible with.

**Comment by annelorraineuy** [comment]
Bump. Since this is especially important.

**Comment by necolas** [comment]
Moving into #491
