### ISSUE TITLE
CSS filters, such as filter: blur(10px);

### ISSUE THREAD

**Issue by ndbroadbent** [necolas/react-native-web#437]
**What is the current behavior?**

I want to create a blurred overlay, so I want to use this style:

```
    const style = {
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      filter: `blur(10px)`,
    }
```

`filter` is ignored, but `background-color` is present.

**What is the expected behaviour?**

I expect to see some inline CSS with `filter: blur(10px)`.

Is there an escape-hatch I can use that will allow me to use any CSS in a web-specific component? As a workaround, I wouldn't mind defining some CSS in a separate file, but then I can't figure out how to add classes or ids to the HTML tags.

**Comment by necolas** [comment]
You can use className or setNativeProps on an instance. But I'll add support for filter

**Comment by ndbroadbent** [comment]
Oh wow, sorry the `className` does work fine, I was just looking at the wrong element in the inspector. Haha it can be hard to see what's going on with all the `rn-*` classes.

Anyway, I submitted a PR - #438

**Comment by ndbroadbent** [comment]
Wow my trackpad just went crazy, sorry!!

**Comment by necolas** [comment]
Best to use the react devtools when debugging

**Comment by ndbroadbent** [comment]
... I can't believe I forgot about react devtools. Thanks!!

**Comment by ndbroadbent** [comment]
By the way, just wanted to say thanks for the incredible work you're doing! This is such an amazing project.

I'm gradually adding `react-native-web` support to a bunch of different libraries. I've got [react-native-sound](https://github.com/zmxv/react-native-sound) working with a tiny wrapper around [howler.js](https://github.com/goldfire/howler.js). Right now I'm working on [react-native-blur](https://github.com/react-native-community/react-native-blur), and then I'll start adding support for [react-native-svg](https://github.com/react-native-community/react-native-svg).

It's an absolutely incredible feeling to write code once, and it all just works on iOS, Android, and the browser. So thanks again!

**Comment by necolas** [comment]
Thanks! That's great to here and thanks for helping to update other libraries

**Comment by RangerMauve** [comment]
@ndbroadbent Is there somewhere I can look to track your progress, or should I just stalk you on github?

**Comment by ndbroadbent** [comment]
@RangerMauve hey, I actually just realized that svg and sound were both going to be huge jobs , so for now I'm just written the bare minimum that my app needs, and it's not really worth sending a PR. But I did finish web support for react-native-blur: https://github.com/react-native-community/react-native-blur/pull/190

FWIW, this is all the code I'm using for SVG: https://gist.github.com/ndbroadbent/37e00e42a41ee71cee67950779be051a

And for sound, I just needed play and stop: https://gist.github.com/ndbroadbent/b406283041135b57288dbd11e114e1ac

**Comment by RangerMauve** [comment]
@ndbroadbent Nice! I've actually made polyfills for sound and blur in my own project, but didn't send them as PRs cause it was messy. I might need to do the SVG integration in a few months so I'll ping you if nobody beats me to it. :P

**Comment by glthomas** [comment]
@ndbroadbent  and @RangerMauve , I am seeking some assistance on the svg filter implementation on the react-native-svg library.  I've been trying to add the filter support with the help of @msand.  But I'm feeling like I'm in over my head a bit.  Any way you guys can take a peek at the filter-support branch over at react-native-svg.  

Please take a look this issue if you get a chance:
[https://github.com/react-native-community/react-native-svg/issues/150](url)
Any help is greatly appreciated.
