### ISSUE TITLE
fontSize >= 20 gets set as an inline style instead of a rn-* class

### ISSUE THREAD

**Issue by ndbroadbent** [necolas/react-native-web#439]
UPDATE: I just remembered that I'm using setNativeProps to hide the text:

```
this.textRef.setNativeProps({ style: { opacity: visible ? 1 : 0 } })
```

So that explains why the font-size style was getting removed.

-----------------------------------------------

**What is the current behavior?**

I am dynamically calculating some font sizes in my app. Something very strange is happening when I increase the browser size, and the font size hits "20". Instead of creating a `rn-*` class, it sets the font size in an inline style attribute. When I hide the Text component, the inline style is cleared, and when I show the Text again, the inline style is not updated. This causes the text to be really small (because the font size is set to `inherit`.) .

It works totally fine for `fontSize: 18` and `fontSize: 19`, but `fontSize: 20` or larger triggers the bug.

Here is the Text div when the font size is set to `19`:

```
<div dir="auto" class="rn-borderTopWidth-13yce4e rn-borderRightWidth-fnigne rn-borderBottomWidth-ndvcnb rn-borderLeftWidth-gxnn5r rn-color-1xmx4u1 rn-display-1471scf rn-font-1lw9tu2 rn-fontFamily-baq3cm rn-fontSize-1b6yd1w rn-marginTop-1mnahxq rn-marginRight-61z16t rn-marginBottom-p1pxzi rn-marginLeft-11wrixw rn-paddingTop-wk8lta rn-paddingRight-9aemit rn-paddingBottom-1mdbw0j rn-paddingLeft-gy4na3 rn-pointerEvents-633pao rn-textDecoration-bauka4 rn-whiteSpace-q42fyq rn-wordWrap-qvutc0" style="">4</div>
```

`fontSize` CSS:

```
.rn-fontSize-1b6yd1w {
    font-size: 19px;
}
```

I can hide/show the Text, and there's no problem, since the `fontSize` class is persistent. 

Here is the Text div when I increase the window size and change the `fontSize` to 20:

```
<div dir="auto" class="rn-borderTopWidth-13yce4e rn-borderRightWidth-fnigne rn-borderBottomWidth-ndvcnb rn-borderLeftWidth-gxnn5r rn-color-1xmx4u1 rn-display-1471scf rn-font-1lw9tu2 rn-fontFamily-baq3cm rn-marginTop-1mnahxq rn-marginRight-61z16t rn-marginBottom-p1pxzi rn-marginLeft-11wrixw rn-paddingTop-wk8lta rn-paddingRight-9aemit rn-paddingBottom-1mdbw0j rn-paddingLeft-gy4na3 rn-pointerEvents-633pao rn-textDecoration-bauka4 rn-whiteSpace-q42fyq rn-wordWrap-qvutc0" style="font-size: 20px;">4</div>
```

When I hide the Text, the style attribute is cleared. And when I unhide the Text, the style attribute is not updated.

OS: OS X
Device: MacBook Pro
Browser: Chrome Version 58.0.3029.81 (64-bit)
React Native for Web (version): I'm using the latest commits from `master`
React (version): 16.0.0-alpha.6

**Comment by ndbroadbent** [comment]
I just remembered that I'm using `setNativeProps` to hide the text:

```
this.textRef.setNativeProps({ style: { opacity: visible ? 1 : 0 } })
```

So that explains why the `font-size` style is getting removed.

For now I'll just make sure I'm setting `fontSize` any time I update the `opacity`. But I would still be interested to find out what causes font-size to get moved into an inline style.

**Comment by necolas** [comment]
Please can you create a reduced test case from this base: https://www.webpackbin.com/bins/-KgucwxRbn7HRU-V-3Bc

**Comment by ndbroadbent** [comment]
Yep, I'll try to reproduce it in there.

Do you know what might cause a `Text` component to produce a `div` instead of a `span`? I'm getting a `span` in the webpackbin.com example, but it's a `div` in my code. Or am I using an outdated version of something?

**Comment by necolas** [comment]
This looks like the issue: https://www.webpackbin.com/bins/-KiRT3N4cvV3Td6E5YYO. I think I know what the problem and fix is.

> Do you know what might cause a Text component to produce a div instead of a span? 

Yes, Text is now backed by `div` since 7705f521c85d5ad2db5801b5a99faf74388d98ab.

**Comment by ndbroadbent** [comment]
Oh nice, thanks for figuring that out! I guess it's only happening when you don't use a Stylesheet to set fontSize.

**Comment by necolas** [comment]
Try latest HEAD - a3362e1f38c5ee130a7cbbd07e79ddda230844bf

**Comment by ndbroadbent** [comment]
Fixed! Thankyou so much!

**Comment by necolas** [comment]
You're welcome, thanks reporting

**Comment by necolas** [comment]
0.0.88 includes this fix
