### ISSUE TITLE
StyleSheet: add support for 'boxShadow'

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#44]
Not sure what to do about this. React Native adds [shadow properties](https://facebook.github.io/react-native/docs/view.html#style):

```
shadowColor
shadowOffset
shadowOpacity
shadowRadius
```

Web has [`box-shadow`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow), and it supports multiple shadows.

```
blurRadius
color
inset
offsetX
offsetY
spreadRadius
```

I can't see a clear mapping between the two. At least for now we can add `boxShadow: string` as another web-specific style prop.

**Comment by lsps9150414** [comment]
How to use `boxShadow: string`?
Like this? 
`boxShadow: 'color: #000; spreadRadius: 5px',`

**Comment by chandlervdw** [comment]
@necolas is this working? My styles don't seem to be coming through on web. I'm using a custom made shadow conversion util:

```
export function shadow({ color, opacity, radius, offsetWidth, offsetHeight, elevation }) {
  return Platform.select({
    ios: {
      shadowColor: color,
      shadowOpacity: opacity,
      shadowRadius: radius,
      shadowOffset: {
        width: offsetWidth,
        height: offsetHeight,
      }
    },
    android: {
      elevation
    },
    web: {
      boxShadow: `${offsetWidth}px ${offsetHeight}px ${radius}px ${rgba}`
    }
  });
}
```

**Comment by necolas** [comment]
Looks like `rgba` isn't defined?

**Comment by chandlervdw** [comment]
@necolas it was, above that function. Actually, my issue stemmed from not using `'box-shadow'` for `web`. All good.

**Comment by chandlervdw** [comment]
@necolas I updated my comment above. I'm testing our project side-by-side in simulator and in the browser and I think some caching was happening with hot-loading. I thought I had figured out the issue but I hadn't.

**Comment by necolas** [comment]
If you can provide a test case and/or what the browser is showing in the dev tools, that would help

**Comment by chandlervdw** [comment]
I've got a stateless, functional component that returns a`<View style={styles.dishShadow} />` with children components. The `dishShadow` style is computed with the following (I've condensed here but the helper functions are imported). `colors` is also imported.

```
const rgba = (color, opacity) => colors.opacity(color, opacity);
const shadow = ({ color, opacity, radius, offsetWidth, offsetHeight, elevation }) => {
  return Platform.select({
    ios: {
      shadowColor: color,
      shadowOpacity: opacity,
      shadowRadius: radius,
      shadowOffset: {
        width: offsetWidth,
        height: offsetHeight,
      }
    },
    android: {
      elevation
    },
    web: {
      boxShadow: `${offsetWidth}px ${offsetHeight}px ${radius}px ${rgba}`
    }
  });
};

const styles = StyleSheet.create({
  dishShadow: {
    borderRadius: 3,
    ...shadow({
      elevation: 3,
      color: 'rgba(2,0,0,1)',
      opacity: 0.15,
      radius: 2,
      offsetWidth: 0,
      offsetHeight: 1
    })
  }
});
```

Output in native has the correct shadow. Output in web does not. In Chrome dev tools, the div that `react-native-web` creates does have `border-radius: 3px` on it, but no `box-shadow` styles.

![image](https://d17oy1vhnax1f7.cloudfront.net/items/2G1u273Z2V092j3q3R0x/%5B86ed7a5d0f66a44fb8b2902d07214087%5D_Image%25202016-12-23%2520at%25201.49.33%2520PM.png?v=9e6bf9a7)

**Comment by necolas** [comment]
`rgba` is a function but you haven't passed it any values. It looks like it should be:

```js
      boxShadow: `${offsetWidth}px ${offsetHeight}px ${radius}px ${rgba(color, opacity)}`
```

**Comment by necolas** [comment]
I'm going to fudge this for web since it seems to be used quite a lot.

**Comment by Victor7095** [comment]
> @necolas it was, above that function.
> 
> ```
> const rgba = (color, opacity) => colors.opacity(color, opacity);
> ```
> 
> where `colors` is imported above.

Where does `colors` is imported from?

**Comment by hungspritely** [comment]
how can I add multiple shadows which have inset shadows and not have inset shadows?
