### ISSUE TITLE
ScrollView: when nested, inner instance triggers outer instance onScroll event

### ISSUE THREAD

**Issue by Kinka** [necolas/react-native-web#440]
**What is the current behavior?**

http://codepen.io/kklogger/pen/NjrJBV

**What is the expected behaviour?**

onScroll should not be triggered by the inner scrolling

**Steps to reproduce**

1. scroll the inner scrollview
2. see the console output

**Environment (include versions)**

OS: ubuntu
Device: thinkpad x1
Browser: chrome 58
React Native for Web (version): 0.0.86
React (version): 15.3.1

**Comment by Kinka** [comment]
@necolas any clues to fix this? Maybe I can help making a pull request.

**Comment by necolas** [comment]
Likely related to event propagation. I haven't yet checked the behavior in React native
