### ISSUE TITLE
How to disable hover for touch events?

### ISSUE THREAD

**Issue by dsernst** [necolas/react-native-web#442]
https://github.com/necolas/react-native-web/issues/205 and https://github.com/necolas/react-native-web/issues/379 suggest using `onMouseEnter` and `onMouseLeave` (presumably combined with `this.setState`) to handle hover effects.

I got this working. 👍👍

But on my mobile device, these elements now requires 2 presses: the 1st to activate the hover, and then a 2nd to activate the element's `onPress`. 

How can `onMouseEnter` and `onMouseLeave` be disabled on a touch device, to require only a single press?

-----------

This is a [common problem for CSS `:hover`](https://stackoverflow.com/questions/8291517/disable-hover-effects-on-mobile-browsers). Is there an equivalent solution for React CSS-in-JS?

**Comment by dsernst** [comment]
Nevermind, false alarm.

I had introduced a bug when adding the hover effects. 

This is what was causing the `onPress` to not work on first press.

**Comment by FCapplemanLynes** [comment]
@dsernst 
What was the bug on your end? I'm having a similar issue and would be interested to know.
Thanks

**Comment by necolas** [comment]
Here's an example component to manage/apply hover styles only when a mouse is in use: https://glitch.com/edit/#!/imaginary-lycra?path=src/Hoverable/index.js:73:10

**Comment by hakunaMarotta** [comment]
@FCapplemanLynes Late to the party, but in case anyone else is still suffering... I had this issue too and was able to fix with a ternary on the onMouseEnter handler:

`onMouseEnter={isMobile ? () => { return false; } : this.doTheThing}`
