### ISSUE TITLE
ReactNative.render results in a broken layout

### ISSUE THREAD

**Issue by ndbroadbent** [necolas/react-native-web#446]
**What is the current behavior?**

```js
ReactNative.render(<App />, document.getElementById('react-root'))
```

![screenshot 2017-04-25 20 14 50](https://cloud.githubusercontent.com/assets/139536/25387122/ea34210a-29f3-11e7-9d26-f568c6ad9bc8.png)

```js
AppRegistry.registerComponent('ExampleApp', () => App);
AppRegistry.runApplication('ExampleApp', {
  rootTag: window.document.getElementById('react-root'),
});
```

![screenshot 2017-04-25 20 15 03](https://cloud.githubusercontent.com/assets/139536/25387156/057d09d6-29f4-11e7-9542-41a8d1df69b8.png)

**What is the expected behaviour?**

I would expect both rendering methods to have the same result. (Although I'm probably misunderstanding how this is supposed to work.)

**Steps to reproduce**

```bash
cd react-native-web
git remote add ndbroadbent https://github.com/ndbroadbent/react-native-web.git
git fetch ndbroadbent
git checkout ndbroadbent/rn-render
cd example_app/
yarn
npm run web

# visit http://localhost:3000/
```

**Comment by necolas** [comment]
This is expected and not a bug. AppRegistry wraps your component whereas render simply renders it into a node (not what you'd typically reach for to mount your whole app)

**Comment by ndbroadbent** [comment]
Ah thanks, yeah I just figured it out while setting up pre-rendering with webpack. Now I understand how to use `const { element, stylesheet } = AppRegistry.getApplication('sudoblock', {})`
