### ISSUE TITLE
TouchableHighlight throwing several errors

### ISSUE THREAD

**Issue by kennethlynne** [necolas/react-native-web#447]
**What is the current behavior?**

![image](https://cloud.githubusercontent.com/assets/390817/25387467/3ce1c23c-29cb-11e7-8742-06a7f12e4740.png)

```
warning.js:36 Warning: Unknown props `onStartShouldSetResponder`, `onResponderTerminationRequest`, `onResponderGrant`, `onResponderMove`, `onResponderRelease`, `onResponderTerminate` on <div> tag. Remove these props from the element.
````

Using the TouchableHighlight component throws lot's of warnings

Link to minimal test case: [https://codepen.io/kennethlynne/pen/MmbaRW](https://codepen.io/kennethlynne/pen/MmbaRW)

**Environment (include versions)**

OS: MacOS
Device: Mac
Browser: Chrome
React Native for Web (version): latest
React (version): 15.3.1

**Comment by necolas** [comment]
Use React@15.4 with latest RNW version. And I suspect the errors are only with the codepen build and something you'd see in your app

**Comment by kennethlynne** [comment]
@necolas thanks for the reply.

I tried using react 15.4:

![image](https://cloud.githubusercontent.com/assets/390817/25422875/c1c5b408-2a62-11e7-9324-16964ec61d19.png)

Updated codepen: https://codepen.io/kennethlynne/pen/MmbaRW

Also, if I instead use a View rather than TouchableHighlight the warnings go away, so it does not seem like an issue with codepen

**Comment by necolas** [comment]
The invariant error is telling you the are probably multiple copies of react installed https://facebook.github.io/react/docs/error-decoder.html?invariant=119
