### ISSUE TITLE
Would it be feasible to add an option to minify the class names in production?

### ISSUE THREAD

**Issue by ndbroadbent** [necolas/react-native-web#449]
I'm pre-rendering my app as static HTML, and I think these `rn-*` classes are adding up to a lot of data.

Would it be possible to minify all these class names as much as possible in production, or at least provide a configurable setting? For example, instead of:

```
div class="rn-1oszu61 rn-1efd50x rn-14skgim rn-rull8r rn-mm0ijv rn-13yce4e rn-fnigne rn-ndvcnb rn-gxnn5r ...
```

It would be great if it was just a sequence of characters, starting at `a`, then `a0` through `az`, etc.:

```
<div class="a b c d e f g h i ...
```

Thanks

**Comment by RangerMauve** [comment]
It's also a PINTA when hovering over an element in the Chrome inspector and getting a wall of text pop up over top of all the content.

**Comment by necolas** [comment]
No, the class names intentionally do not change between apps or deploys. Once your HTML is gzipped the size impact is inconsequential. For debugging, you should rely more on react dev tools.

**Comment by ndbroadbent** [comment]
Sorry you're right, 45k gets shrunk down to 5k. Won't worry about this then

**Comment by RangerMauve** [comment]
@necolas Is there an extension I can use for react dev tools that will let me modify the styles for an element?

**Comment by necolas** [comment]
Not that I know of; that needs to be built into their extension (for general React development purposes too)
