### ISSUE TITLE
Add "advanced usage" guide

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#450]
Include:

- How to build a styled-components API on top of React Native: https://codepen.io/necolas/pen/BpgQJo
- How to wrap ReactDOM components so that they can be styled using the RN API: https://www.webpackbin.com/bins/-KiTSGFw3fB9Szg7quLI
- How to use with [react-sketchapp](https://github.com/airbnb/react-sketchapp) – basically [this](http://airbnb.io/react-sketchapp/docs/guides/universal-rendering.html) without the `react-primitives` indirection.

**Comment by jeffgorder** [comment]
Wanted to say that this is super helpful! I have one issue that I'm struggling with. How would you suggest avoiding sending unknown props when you create a styled component. For example if I create a Divider component from a View, but create a boolean 'line' prop, you get the unknown prop error. Usually, you can get rid of unexpected props as described here https://facebook.github.io/react/warnings/unknown-prop.html but not sure when to do it using the styled-component API as you've described. Thanks for your help.

**Comment by necolas** [comment]
Yeah that's been a common problem with their API. I think they might be changing it to allow you to specific which props to remove, i.e., pass an array of the prop names to filter. I should also mention that the API adds significant performance overhead  by wrapping everything in another component, using context, and allocating objects - using RN directly is a simpler and more flexible solution imo
