### ISSUE TITLE
Warning: "textDecoration" is not a valid style property.

### ISSUE THREAD

**Issue by kennethlynne** [necolas/react-native-web#451]
**What is the current behavior?**

Link to minimal test case: [webpackbin](https://www.webpackbin.com/bins/-KidQ1s9GOt3A8MgwHx2)

![image](https://cloud.githubusercontent.com/assets/390817/25425738/2cb07320-2a6d-11e7-9f09-c9fa2be1b44e.png)

**What is the expected behaviour?**
It should allow web specific style properties

**Environment (include versions)**
React Native for Web (version): latest
React (version): 15.4.2

**Comment by necolas** [comment]
That's right, it's not a valid style. Use textDecorationLine
