### ISSUE TITLE
Dimensions: are window measurements correct?

### ISSUE THREAD

**Issue by sopaco** [necolas/react-native-web#453]
the `Dimensions.get('window').height` is not equals with the actual window height, what's wrong?
```
version=0.86.0
webbrowser:Chrome
```

**Comment by RangerMauve** [comment]
@sopaco What does it equal if not the window height?

**Comment by necolas** [comment]
Please include a reduced test case and more details (as asked for in the issue template). I could reproduce using the [webpackbin playground](https://www.webpackbin.com/bins/-KgucwxRbn7HRU-V-3Bc). I'll reopen the issue once there's an indication that there's a bug to be fixed

**Comment by dsernst** [comment]
I'm running into a similar issue:

### Code

```js
import {
  Dimensions,
} from 'react-native'

function myComponent() {
  console.log('width:', Dimensions.get('window').width)
  return null
}
```

### Results

#### In Chrome Dev Tools simulated responsive screen — `iPhone 6 375 x 667` setting — this prints:
```
width: 375
```

#### On an actual device — using Safari's Web Inspector over a USB cable — this prints:
```
width: 980
```

**Comment by dsernst** [comment]
As a workaround, [`react-responsive`](https://github.com/contra/react-responsive) reports consistent values 👍

**Comment by necolas** [comment]
Consistent values for what? Media queries don't measure screen dimensions

**Comment by dsernst** [comment]
I needed to display different text depending on the width of the screen. 

Using [`react-responsive`](https://github.com/contra/react-responsive) like this worked for me:

```jsx
<MediaQuery maxWidth={370}>
  {verySmall => (
    <MyDynamicComponent message={verySmall ? 'Short message' : 'Can afford more verbosity'} />
  )}
</MediaQuery>
```

---

I had first tried using `Dimension.get('window')` but it was reporting much greater widths than expected when tested on actual mobile devices vs a laptop. My guess is due to screen density, but didn't research this in depth.

**Comment by necolas** [comment]
Do you have a meta viewport tag in your HTML page?

**Comment by dsernst** [comment]
Yes

**Comment by necolas** [comment]
OK, what does it look like please?

**Comment by dsernst** [comment]
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

**Comment by necolas** [comment]
I haven't been able to reproduce this in browserstack. I [tested](http://jsbin.com/viwolohuvi/9/edit?html,js,output) on iPhone 6 in Safari and Chrome and got these results:

```
{
  "window": {
    "fontScale": 1,
    "height": 515,
    "scale": 2,
    "width": 375
  },
  "screen": {
    "fontScale": 1,
    "height": 667,
    "scale": 2,
    "width": 375
  }
}
```

<img width="357" alt="ios-result" src="https://cloud.githubusercontent.com/assets/239676/26479812/e921f1c6-418a-11e7-9fc4-46a3397291e6.png">

**Comment by necolas** [comment]
Any follow up?

**Comment by necolas** [comment]
I'll reopen the issue once there's is more to go on, as I still haven't been able to reproduce.

**Comment by lingxiao** [comment]
what's the update on this issue? In my case I'm using this lib : https://github.com/ladas-larry/react-native-responsive-image#readme, which requires an actual screen width value, not conditional rendering based on predefined width. 

Please see SO question here: https://stackoverflow.com/questions/51510543/react-native-detected-screen-width-using-dimension-getwindow-width-is-differ
