### ISSUE TITLE
TouchableOpacity broken on iOS 9.3.5

### ISSUE THREAD

**Issue by RangerMauve** [necolas/react-native-web#454]
**What is the current behavior?**

When upgrading to react-native-web 0.0.80 or greater all TouchableOpacity buttons stop working (not sure about other kinds of buttons since haven't used them for this project). 

**What is the expected behaviour?**

Buttons work

**Steps to reproduce**

1. Use any page with a TouchableOpacity button
2. Press the button
3. Uncaught error shows up in console and button doesn't work

**Environment (include versions)**

OS: iOS 9.3.5
Device: iPad
Browser: Webview within a Cordova app
React Native for Web (version): > 0.0.80
React (version): 15.4.2

It fails with a cryptic error saying that you can't assign a read-only value. Looking into it further, it appears that when [TouchableOpacity#setOpacityTo](https://github.com/necolas/react-native-web/blob/master/src/components/Touchable/TouchableOpacity.js#L87) uses [setNativeProps](https://github.com/necolas/react-native-web/blob/master/src/modules/NativeMethodsMixin/index.js#L69), the call to [StyleRegistry.resolveStateful](https://github.com/necolas/react-native-web/blob/master/src/apis/StyleSheet/StyleRegistry.js#L91) ends up returning an object that contains `transitionDuration`, the webkit prefixed version, and a `length: 0` property. This in turn causes a runtime error when the style is applied in [UIManager.updateView](https://github.com/necolas/react-native-web/blob/master/src/apis/UIManager/index.js#L69) because `length` is a ready-only property of `style`.

I'm kind of stuck in debugging this because I don't understand how the style object gets generated and where the `length` property is being generated.

For now I've reverted to version 0.0.80 of the library, but it would be nice to be able to use the newer versions eventually. I'll see if I can get more details later this week or early next week.

**Comment by necolas** [comment]
Please can you include the error stacktrace

**Comment by RangerMauve** [comment]
Sadly I'm using create-react-app for bundling and it minifies the code so the stack trace looks awful. I'll see about building a non-minified version either tomorrow afternoon or next week (EST timezone). But I can tell that it's throwing [here](https://github.com/necolas/react-native-web/blob/master/src/vendor/setValueForStyles/index.js#L231) and was a result of  [this](https://github.com/necolas/react-native-web/blob/master/src/components/Touchable/TouchableOpacity.js#L87) and, the `length` property is being generated somewhere in [here](https://github.com/necolas/react-native-web/blob/master/src/apis/StyleSheet/StyleRegistry.js#L91)

**Comment by RangerMauve** [comment]
Since the issue is an invalid style prop is being generated in `StyleRegistry.resolveStateful`, it wouldn't be in the stack trace regardless.

**Comment by necolas** [comment]
Looks like iOS 8/9 leave the length property on the new object when copying the DOM style over

**Comment by necolas** [comment]
Try using the latest master. I'll cut a new version if things look good

**Comment by RangerMauve** [comment]
Awesome! Thank you so much for the fix! I'll test it out this morning.

**Comment by RangerMauve** [comment]
We've tested it out and can confirm that the fix is working properly. Thank you!

**Comment by necolas** [comment]
Great, thanks for reporting :) This will be available in 0.0.90
