### ISSUE TITLE
How to stop unnecessary Image flashing?

### ISSUE THREAD

**Issue by dsernst** [necolas/react-native-web#455]
Whenever I transition to a new route (using `react-router`), my Menu component unmounts and re-mounts, causing the logo `<Image />` to disappear and then flash back.

(The `Image` is using base64 imports for `source`.)

Is there a good way to address this at the Image level? I tried setting `componentShouldUpdate` for the Menu, but it's not so easy because its container, and its container's container are all being unmounted with the `<Route>` transitions.

Here's an animated gif (click if frozen)

<img src="https://cloud.githubusercontent.com/assets/6340841/25516471/aa09d43c-2b9f-11e7-9009-3d35cd753fe1.gif" width="350" />

**Comment by necolas** [comment]
Looks like a bug in your app is causing that whole area to rerender on every click

**Comment by agusvazquez** [comment]
It is happening on my app upon load and refreshing manually with F5. Should we reopen this? @necolas
