### ISSUE TITLE
type definitions for typescript

### ISSUE THREAD

**Issue by Introvertuous** [necolas/react-native-web#458]
are there plans to create a definitions entry for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by necolas** [comment]
No plans. We don't use TypeScript right now, but if others want to maintain those types that would be cool

**Comment by goldcaddy77** [comment]
@Introvertuous - did you ever look into this?  Seems like one could get pretty close by starting with https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native

**Comment by dalcib** [comment]
`npm i @types/react-native` works well.
It even support `Platform.OS === 'web'`

**Comment by goldcaddy77** [comment]
@dalcib how do you get typescript to look at that path instead of 'react-native-web'?

**Comment by dalcib** [comment]
I am using create-react-app, with react-scripts-ts where in webpack config there is an alias to react-native-web.
You can see an example here: https://github.com/dalcib/react-native-material-ui-web-app

**Comment by goldcaddy77** [comment]
That example seems to use `react-scripts`, not `react-scripts-ts`.  Do you have another project that uses the typescript version?

**Comment by dalcib** [comment]
You are right. I mistook about that.
But react-scripts-ts also have [this](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/config/webpack.config.dev.js#L121) code in webpack config that do the same:
```
    alias: {
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },
```
