### ISSUE TITLE
Sound for react-native-web

### ISSUE THREAD

**Issue by tgh** [necolas/react-native-web#459]
My apologies as this isn't really a bug but an inquiry, and I didn't know where else to post this (I assume SO would downvote this kind of question).

Has anyone gotten sound to work for devices *and* web with react-native-web?  I have gotten sound to work for web with react-sound, but this doesn't work with iOS (e.g. “SoundManager requires a browser with window and document objects.”). I have gotten sound to work in iOS with react-native-sound, but this doesn't work with web (e.g. "Can't resolve 'react-native/Libraries/Image/resolveAssetSource' in '/Users/thayes/workspace/AquaReactNative/node_modules/react-native-sound'").

Is there an npm package out there that will get along with both react-native and web?

**Comment by necolas** [comment]
@ndbroadbent said he had a working version of `react-native-sound` https://github.com/necolas/react-native-web/issues/437#issuecomment-296383126. you might want to discuss with him

**Comment by ndbroadbent** [comment]
Hi @tgh, I use `react-native-sound` on native, and the [howler.js](https://howlerjs.com/) library on web.

You should install howler with: `npm install howler --save`

Then create two files: `sound.js` and `sound.web.js`. This is the code I'm using: https://gist.github.com/ndbroadbent/64d71fc1f1f522e059676934b06f1a30

Then to play a sound:

```
import Sound from './sound'

new Sound(url).play()
```

**Comment by afilp** [comment]
@ndbroadbent I did this and passed the compile errors, however I get runtime errors because of this method:

```
  window.sound_background.getCurrentTime((seconds: number, isPlaying: boolean) => {
  if (isPlaying) {
     return;
  }
```

Do you think we can have the `getCurrentTime` exposed in howler similarly?

Thanks a lot!

**Comment by dusekdan** [comment]
@ndbroadbent - apologies for necroing this thread. I am now facing the very same problem, using expo, unable to compile my project for web. I think your solution from here is still valid, but I do not understand the instructions you previously provided.

How does the `sound.js` vs `sound.web.js` file work? Do I just create them wherever in the project and make sure that I am importing and using the `react-native-sound` only in the `sound.js`, while I put your implementation of howler into `sound.web.js`? And then the bundler will figure this out and let me continue?

I am currently hitting:

```
ERROR in ./node_modules/react-native/Libraries/Image/AssetSourceResolver.js:24:17
Module not found: Can't resolve '../Utilities/Platform'
  22 |
  23 | const PixelRatio = require('../Utilities/PixelRatio').default;
> 24 | const Platform = require('../Utilities/Platform');
     |                 ^
  25 | const {pickScale} = require('./AssetUtils');
  26 | const {
  27 |   getAndroidResourceFolderName,
```

Whenever I try to import Sound (from `react-native-sound`).
