### ISSUE TITLE
Release #0.0.88 broke AnimatedView in FireFox 

### ISSUE THREAD

**Issue by jeffberry** [necolas/react-native-web#460]
**What is the current behavior?**

When trying to apply an array of styles for the transform attribute, Firefox now throws a `TypeError: 0 is read-only` error. This issue is caused by something that was changed in 0.0.88. I have tested 0.0.87 and the issue goes away. 

```javascript
render() {
    const rootStyle = {
      transform: [{
        translateX: this.state.position.interpolate({
          inputRange: [0, 1],
          outputRange: [0, -this.props.width],
        }),
      }],
    };

    return (
      <AnimatedView
        canvas
        zDepth={2}
        style={[styles.root, this.props.style, rootStyle]}
        ref={(dialog) => {
          this.dialog = dialog;
        }}
      >
        {this.renderTitleBar()}
        <ScrollView style={styles.scrollView} contentContainerStyle={styles.scrollContent}>
          {this.props.children}
        </ScrollView>
        {(this.props.leftButtons || this.props.rightButtons) && this.renderActionBar()}
      </AnimatedView>
    );
  }
```

The error is thrown on this line: https://github.com/necolas/react-native-web/blob/master/src/vendor/setValueForStyles/index.js#L231 

The `styles` variable involved in the loop there can potentially be an animated structure like: `['opacity', 0.555]` or `['transform', [{translateX: '...'}]` which causes this loop to occasionally have the numbered index as `styleName`, thus breaking the building of the object.

**What is the expected behaviour?**
For the element to successfully animate.

OS: OS X,
Device: MacBook...
Browser: FireFox
React Native for Web (version): 0.0.88
React (version): 15.4.2

**Comment by necolas** [comment]
Try upgrading to latest release

**Comment by jeffberry** [comment]
I've tried the latest release. We started at 0.0.91 and kept stepping down to 0.0.90, 0.0.89, etc until we found the build that worked for us. The latest tag and the master branch both exhibit this issue.

**Comment by necolas** [comment]
Try 0.0.92
