### ISSUE TITLE
Server rendering with Next.js

### ISSUE THREAD

**Issue by scf4** [necolas/react-native-web#462]
Hey, I've managed to get things running with Next.js, but it seems server rendering doesn't include CSS.

Is there an API to grab the CSS for the page when server rendering? Like in this example with styled-components: https://github.com/zeit/next.js/blob/master/examples/with-styled-components/pages/_document.js

Thanks!

**Comment by scf4** [comment]
Sorry, I jumped the gun a little. It does actually work, but there's a discrepancy between the server and client renders.

Example code:

```js
import React from 'react';
import { View, Text } from 'react-native';

export default () =>
  <Text style={{ fontFamily: 'Times'}}>
    it works?!
  </Text>
```

**Server render**

![screen shot 2017-05-02 at 17 20 30](https://cloud.githubusercontent.com/assets/768234/25627833/e3290606-2f5b-11e7-8ee6-debb8d032b5c.png)

**Client render**

![screen shot 2017-05-02 at 17 20 37](https://cloud.githubusercontent.com/assets/768234/25627840/e8c59db8-2f5b-11e7-816b-5121816ba82f.png)

In this case it appears to be padding.

**Comment by scf4** [comment]
Ok this seems pretty strange to me...

**Example:**

```
export default () =>
  <View style={{ backgroundColor: 'blue' }}>
    <Text style={{ fontFamily: 'Comic Sans MS'}}>
      testing
    </Text>
  </View>
```

The server-rendered version doesn't have a blue background. But if I set `{{ background: 'blue' }}` (background isn't a valid RN prop) it does, because it sets it as inline CSS on the div's `style` property.

The text is also in Comic Sans because of this inline CSS.

**Comment by necolas** [comment]
Server-rendering guide: https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#server-side-rendering

If there's an issue with the server-rendering styles, please open a separate issue with steps to reproduce. Thanks

**Comment by scf4** [comment]
Not sure how I missed that. Thanks Nicolas!

**Comment by scf4** [comment]
Here's my solution below for anyone looking to integrate with Next.js, or if anyone has a better solution to propose:

**pages/_document.js:**

```js
import Document, { Head, Main, NextScript } from 'next/document'
import { AppRegistry } from 'react-native-web';

export default class MyDocument extends Document {
  static async getInitialProps ({ renderPage }) {
    AppRegistry.registerComponent('Main', () => Main);
    const { stylesheet } = AppRegistry.getApplication('Main');
    const page = renderPage();
    const styles = <style dangerouslySetInnerHTML={{ __html: stylesheet }} />;
    return { ...page, styles };
  }

  render () {
    return (
      <html>
        <Head>
          <title>My page</title>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}

```

**Comment by necolas** [comment]
We could add an example to the Next.js repo

**Comment by dcalhoun** [comment]
I've added a [react-native-web example](https://github.com/zeit/next.js/pull/3781#issuecomment-365234989) to the Next.js repository.

**Comment by 5ervant** [comment]
**May I ask how will you make `react-navigation` work on a Next.js application?** @scf4

**Comment by Gregoirevda** [comment]
@dcalhoun This is working well for inline styles and styles generated with the StyleSheet api, but I'm using classes and that doesn't seem to work.
The reason seems simply because my tailwind classes are defined before the `react-native-stylesheet` styles.
So the default styles are overriding my tailwind classes. Do you know how I could set them after? tailwind classes are imported from _app.tsx

**Comment by dcalhoun** [comment]
👋🏻 @Gregoirevda. This issue is very old. Also, it has been a while since I worked with Next.js and React Native for Web. 

I recommend opening a [new discussion](https://github.com/necolas/react-native-web/discussions/new/choose) in this project seeking help. Doing so is more likely to gain visibility and assistance from the maintainers or others. Hope this helps. 🙇🏻‍♂️
