### ISSUE TITLE
Use new flexbox instead of old box property

### ISSUE THREAD

**Issue by brunolemos** [necolas/react-native-web#468]
If you use tool like Google's [Lighthouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk) you will get an message like this: 

> Avoids old CSS flexbox   
The 2009 spec of Flexbox is deprecated and is 2.3x slower than the latest spec. [Learn more.](https://developers.google.com/web/tools/lighthouse/audits/old-flexbox)

![image](https://cloud.githubusercontent.com/assets/619186/25774536/185eae44-3267-11e7-8b3a-1b5e36f9781c.png)

Any code that has a `display: flex` causes this.

**Comment by brunolemos** [comment]
@necolas apparently this comes from the https://github.com/rofrischmann/inline-style-prefixer dependency. Any way I can config it without a fork? cc @rofrischmann

**Comment by necolas** [comment]
Isn't old flexbox just a fallback value? In which case this would be a false positive in lighthouse

**Comment by brunolemos** [comment]
Yeah apparently it's a false positive for `display` but not for `box-direction`/`box-orient`:

![image](https://cloud.githubusercontent.com/assets/619186/25774932/7953e98c-326f-11e7-9ec4-b832dce89007.png)

![image](https://cloud.githubusercontent.com/assets/619186/25774913/1d44574e-326f-11e7-9a4c-7fee4aa17aed.png)

**Comment by necolas** [comment]
Nope

**Comment by necolas** [comment]
Also, from looking at those class names it looks like you're using a very old very of the library

**Comment by brunolemos** [comment]
You closed the issue door in my face but thanks for the upgrade tip, it fixed this issue!
![image](https://cloud.githubusercontent.com/assets/619186/25776187/24cbfa8e-328e-11e7-97bd-84ee8d508aa6.png)

**Comment by necolas** [comment]
\o/

(Yeah sorry I bias pretty heavily to closing issues to keep things manageable)
