### ISSUE TITLE
Idea: "Native" Animation Driver for web, using CSS transitions

### ISSUE THREAD

**Issue by ndbroadbent** [necolas/react-native-web#470]
Hi there,

I just wanted to throw out an idea that I've been successfully implementing in my own app. The app was barely useable on the web, because I use a great deal of animations (it's a game), and they perform very badly when run purely from JavaScript. So what I've started to do is add a lot of Platform specific code to my animation calls. I add a CSS transition and duration with setNativeProps, then I set the animation duration to 0, and run it. I also inject an `Animated.delay` into the sequence, which just waits for the CSS transition to finish.

This pattern has worked really well for me so far, so I would like to talk about bringing this into react-native-web, in the form of `useNativeDriver`. iOS and Android already have their own native animation drivers, and I think it makes a lot of sense to build a native driver for web using CSS transitions.

The idea would be to wrap animations with something like this:

```js
// Returns an object that conforms to the Animated.Animated API
// (with start and stop functions)
const wrapAnimatedTimingWithCSSTransition = (animatedValue, { toValue, duration }) => {
  // Sets the value immediately, but also waits for the given duration
  const animation = Animated.sequence([
    Animated.timing(animatedValue, { toValue, duration: 0 }),
    Animated.delay(duration),
  ])

  return {
    start: (callback) => { 
      // Not sure how this would be done
      setTransitionPropertiesForAnimatedValue(animatedValue)

      animation.start(() => {
        resetTransitionPropertiesForAnimatedValue(animatedValue)
        if (callback) callback
      })
    },

    stop: () => { 
      animation.stop() 
    },
  }
}
```

There's a lot of things I'm not sure how to do, but that's the general idea.

One major caveat: you can't set separate transition durations for multiple transform properties. e.g. rotation and scale can't be controlled independently. In practice, this hasn't been an issue for me. I think a sane default would be to just choose the minimum duration, if multiple are provided. Or if all of the animations are started at the same time, then [we could use the longest duration with keyframes](http://stackoverflow.com/a/3679459/304706).

That's really nothing compared to the caveats (and bugs) I've already worked through on Android, so I think most people would be happy with this trade-off.

Look forward to hearing your thoughts, and I would be happy to help, although I'm still not very confident in my ability to contribute code to this project.

**Comment by necolas** [comment]
FYI `Animated` is maintained here: https://github.com/animatedjs/animated. And RNW supports both CSS transitions and CSS animations.

I mentioned something similar to @lelandrichardson recently in https://github.com/lelandrichardson/react-primitives/pull/58. Modern browsers have APIs that might allow `Animated` to offload work to the browser so the app can get off the main thread.

**Comment by necolas** [comment]
> Would that be the right place to implement a native driver for web?

Yeah I'm not sure. They're trying to include the DOM integration over there, so maybe.

I've gone out of my way to avoid depending on `Animated` for any of the `react-native-web` implementations (e.g., Touchables, ProgressBar) to avoid the performance issues you've experienced. I too used CSS transitions and animations to lean more on the underlying platform.

**Comment by ndbroadbent** [comment]
Will come back to this a bit later

**Comment by robertherber** [comment]
Has there been any more progress on this? How big of a task would it be to implement? Now that the Web Animations API has 94% browser support it would provide a lot of value.

**Comment by fershibli** [comment]
I'm needing this today... Did someone find any workaround?
