### ISSUE TITLE
ScrollView: investigate expensive layout measurements

### ISSUE THREAD

**Issue by brunolemos** [necolas/react-native-web#473]
**What is the current behavior?**

When scrolling, there is a huge lag.
Chrome shows some warnings on console that could help find the issue.

Most violations point to UIManager [measureLayout](https://github.com/necolas/react-native-web/blob/761c42301d1e913c0a9181262cab9107abd10d8d/src/modules/ScrollResponder/index.js#L441)), the last one to a debounce function:

```
[Violation] 'requestAnimationFrame' handler took 93ms
[Violation] Forced reflow while executing JavaScript took 184ms
[Violation] 'requestIdleCallback' handler took 242ms
[Violation] 'setTimeout' handler took 74ms
```

![image](https://cloud.githubusercontent.com/assets/619186/25853741/31da682e-34a4-11e7-987f-05348d32cb7b.png)

**Steps to reproduce**

_Tried to create a minimal test case on codepen but could not. Maybe it's because my component tree is relatively deep and heavy styled (ps: using styled-components). Added you to the [repository](https://github.com/brunolemos/devhub) so you can run it. PS: On mobile, works fine. Bad performance only on web._

1. Accept my invitation to the [repo](https://github.com/brunolemos/devhub)
2. yarn
3. cd web/
4. yarn
5. npm start (on web folder)
6. Open notifications tab
7. Scroll vertically

**Environment (include versions)**

OS: macOS 10.12.4
Device: Macbook Pro 2016
Browser: Chrome 58.0
React (version): 16.0.0-alpha.6
React DOM (version): 15.5.4 _(react-native-web does not support >= 16)_
React Native (version): 0.43.2
React Native for Web (version): 0.0.94

**Comment by brunolemos** [comment]
I'm running some profiling to try to narrow it down...

`UIManager/index.js`
<img height="300" src="https://cloud.githubusercontent.com/assets/619186/25869011/2874e49a-34d5-11e7-9727-1f52a1f7bd44.png" />

**Comment by brunolemos** [comment]
Maybe some tips so my component measure layouts faster?

**Comment by RangerMauve** [comment]
Maybe there's a way to improve performance by using [Element.getBoundingClientRect()](https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect)

**Comment by necolas** [comment]
Are you using the `onContentSizeChange` callback?

If you're using styled-components with RN/RNW that is also likely to be very slow and wasteful.

**Comment by brunolemos** [comment]
@necolas thanks for the answer.

I'm not using `onContentSizeChange` or something similar on my code, but there is indead a `onLayout=bound_handleContentOnLayout` on my react tree that internally calls `onContentSizeChange` and apparently it's coming from the react-native-web [ListView](https://github.com/necolas/react-native-web/blob/master/src/components/ListView/index.js#L236) Component 

![image](https://cloud.githubusercontent.com/assets/619186/25872163/240e610a-34e0-11e7-8edc-f0157187b150.png)

**Comment by RangerMauve** [comment]
@brunolemos Is your ListView deeply nested within your app?

**Comment by brunolemos** [comment]
@RangerMauve yes, it's trello-like

**Comment by RangerMauve** [comment]
The `getRect` function you pointed up above will be slower depending on how deeply nested it is within the DOM. I'm not 100% certain, but I think that Element.getBoundingClientRect() might be faster alternative. Regardless, this means that ListViews are a huge performance issue if they're not near the root of your DOM, and more generally onLayout is a huge performance issue if it's not called near the root.

**Comment by brunolemos** [comment]
Found out something.

The ListView is initially rendering 10 item.
When I scroll, it adds more items.

If I set `initialListSize={100}`, app is slower to start but the scroll gets much better.
I guess this multiple row addition + measureLayout on a deep listview is making things slow.

**Comment by necolas** [comment]
Yeah the `ListView` is not really worked on, not performant, and will be removed once React Native deprecates it. `getBoundingClientRect` doesn't return the correct values (for RN) when scale transforms are applied to the element, but I'll look at alternative ways to correct the value without iterating up the tree.

**Comment by tazsingh** [comment]
I've done a benchmark of `getBoundingClientRect` yesterday to see if it would be any faster for #474, but the performance of it was generally 20% slower than the current method.

**Comment by necolas** [comment]
o_O

**Comment by tazsingh** [comment]
Haha I was also shocked as I was expecting it to be faster for sure. Thought it would be quick win but nope... And I'm kind of confused why as everything that I know suggests that it should be faster... But hey if it doesn't work then it doesn't work. Thought I'd loop back here to say that it's also not more performant.

**Comment by jefferscn** [comment]
I have a question,why on web , we need to know position of Node?
On Native, render view need this info,but on web ,browser give us  a rule to maintain node position automatic.
How about to remove left&top attrs from getRect's result.

**Comment by tazsingh** [comment]
Can you let me know if #490 solves some of this for you?

**Comment by necolas** [comment]
Might still be worth using `getBoundingClientRect` if there are performance issues with the current approach in deeply nested trees of nodes

**Comment by brunolemos** [comment]
I just noticed my component tree go down to ~100 items deep. That's insane. Full of `Connect(XXX)`, `withXXX` and other wrappers. 

So although there are improvements to be made on `react-native-web` code, I certainly have a lot of responsability on performance issues.

![image](https://cloud.githubusercontent.com/assets/619186/26760559/5c666234-48f2-11e7-8357-bd19233f6537.png)

**Comment by RangerMauve** [comment]
@brunolemos Yeah, I had a similar problem. I also hacked React.createElement so that it would execute any stateless functions as functions if they didn't need to be components for stuff like context

**Comment by aFarkas** [comment]
@brunolemos 
Can I have access to your repo. I'm interested to look into this. (Although, I'm only interested in perf issues that are caused by forced sync reflows.)

**Comment by brunolemos** [comment]
@aFarkas you can see it running here: http://brunolemos.github.io/devhub/
Didn't make the code public yet neither shared the project, pivoting.

**Comment by brunolemos** [comment]
I rewrote my app from scratch and I don't have this issue anymore. Performance is great.

As I didn't isolate the issue, I don't know the real cause of it, but one of the changes was that I removed styled-components and took extra care to avoid unnecessary re-renders.

**Comment by necolas** [comment]
Thanks for following up!
