### ISSUE TITLE
Request for example app on glitch.com

### ISSUE THREAD

**Issue by furball514** [necolas/react-native-web#475]
There are a lot of helpful examples to get started with react-native-web on codepen.io , I request the same for glitch.com it would be very helpful.

**Comment by necolas** [comment]
I'd like to do that eventually. I've also been moving examples to webpackbin. There are some complications with reaching into react-dom internals, which prevents the current versions from running in most of these online editors. Those issues overlap with the changes Facebook are making for React 16, but I haven't any response from them yet about how we can move forward.

**Comment by necolas** [comment]
Moving into #491
