### ISSUE TITLE
Add `className` and `id` props to `Button` component (and others?)

### ISSUE THREAD

**Issue by jtag05** [necolas/react-native-web#481]
I'm beginning to use e2e testing on our application and found that the `Button` component does not pass through the `id` and `className` properties like many other components do. I'm not sure if this is by design, but having the ability to declare selectors for use with testing is really helpful. 

I'm sure this wouldn't be a big issue and I'd be happy to tackle it. I'll do some more research into what other components may not pass through these props as well if you think this is a worthwhile effort.

**Comment by necolas** [comment]
You can use `testID` for e2e testing

**Comment by jtag05** [comment]
Always a step ahead of the game. Thanks :)
