### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#482]
I am going to be short but can expand if you have any question (technical or not).

Are you interested in getting a website for the documentation?
With @bloodyowl, we are currently working on a revamp of [phenomic](https://github.com/MoOx/phenomic), a static site generator (no, it's not "another one", as this one is modular: we have "plugins" to choose bundler (eg: webpack), renderer (eg: react) etc).

The idea here is to generate a website from current documentation.... and using react-native-web itself for the UI.

If you are interested I can prepare a minimal PR. We plan to release an first stable-alpha (we are creating a concept haha) at the end of the month and I will use react-native-web for our own doc, I was thinking it can be fun (and meta) to use RNW for the doc of RNW :)

This might help to solve #168.

(We can also discuss about this at react-europe ^^)

**Comment by necolas** [comment]
Moving to #491, but I think I want to have a simple app rather than building on top of another framework of sorts. Thanks
