### ISSUE TITLE
How to make custom webpack.config for ReactNativeWeb project with different platforms

### ISSUE THREAD

**Issue by code-by** [necolas/react-native-web#483]
I have React Native project and make them to be work in browser using React Native Web
For some React components I made different files for different platforms, like this
index.ios.js
index.android.js
index.web.js

When I make storybook webpack.config with
```
  resolve: {
    alias: {
      'react-native': 'react-native-web',
    },
    extensions: ['.js', '.jsx', '.web.js'],
  },

```

I got errrors like this:
```
ERROR in multi manager
Module not found: Error: Cannot resolve 'file' or 'directory' /home/user/prj/RNWApp/node_modules/@kadira/storybook/dist/server/config/polyfills.js in /home/user/prj/RNWApp
 @ multi manager
```

How I need resolve them in Storybook webpack.config.js ?

**Comment by necolas** [comment]
I think you should open an issue against the storybook project to see if they can help you get to the bottom of this. It doesn't seem to be an issue with RNW
