### ISSUE TITLE
Workarounds for severe bugs and crashes related to CSS transitions, on iOS WebKit

### ISSUE THREAD

**Issue by ndbroadbent** [necolas/react-native-web#484]
I'm currently dealing with something [similar to this issue on StackOverflow](http://stackoverflow.com/a/15989719/304706). Right now my app kind of looks like I dropped my phone in a pool, and it's completely unusable on iOS Safari and Chrome (WebKit). It's working fine on desktop browsers (Chrome, Safari, Firefox, and Edge), Android Chrome, and native iOS, Android, and Windows UWP. 

If I can't get CSS transitions working properly then I might have to just drop support for mobile browsers and redirect straight to the native app store pages. But it would be really awesome if I could show a usable demo in a web browser, so you don't have to install anything before trying it out.

Have you experienced stuff like this, do you have any tips for things I could try? I tried to dump out all the CSS on the page and looked for the transitions, but they're all dynamically added, so it's hard to track down. I'm not sure if I'm ever using `transition-property: all`, but I don't think I've done that manually, and I don't think RNW ever uses it.

Let me know if you want to see a video that shows the flickering and blanking, and I can PM you an unlisted YouTube video. I can also send you a link to the beta version that's online, and I'm happy to give you access to my git repo.

In the meantime I might just detect mobile browsers and redirect straight to the app store pages. The UX actually works, but it's just too slow with JS animations, and CSS transitions totally destroy the app with blank pages and weird flickering.

**Comment by necolas** [comment]
I can't help you debug something without you sharing any code or an isolated test case. It sounds like you're experiencing a general iOS Safari issue?

**Comment by ndbroadbent** [comment]
Yep, I'm happy to share my git repo and PM you some links to the video and beta version, but not sure how to send that privately. I hesitate to build a reproducible test case because it sounds like it should be a known issue on Safari, and just wanted to see if you're familiar with it (because of your work on normalize.css). But if this a new thing, then I'll definitely find some time to put together a repro, and maybe submit a bug report to Apple as well.

**Comment by ndbroadbent** [comment]
Never mind, I think I'm going to pull out lldb and see if it's possible to turn this into ~$50k
