### ISSUE TITLE
.web.js naming convention

### ISSUE THREAD

**Issue by vaukalak** [necolas/react-native-web#488]
**What is the current behavior?**

There's no documented convention on how to name web specific files.

**What is the expected behaviour?**

There should be a documented (I propose `.web.js`) convention for naming platform dependent code.

**Comment by MoOx** [comment]
It's visible in "Getting Started" webpack config https://github.com/necolas/react-native-web/blob/124de7562d36a51d1eccc3e0a2faef52b67979b4/docs/guides/getting-started.md#webpack-and-babel

**Comment by vaukalak** [comment]
@MoOx that's great, but I think, it should be documented explicitly. Probably in platform specific code topic. https://github.com/necolas/react-native-web/blob/124de7562d36a51d1eccc3e0a2faef52b67979b4/docs/guides/getting-started.md#web-specific-code

**Comment by necolas** [comment]
Please make a pull request
