### ISSUE TITLE
Documentation backlog

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#491]
- [ ] Provide versioned documentation
- [x] Align with React's README
- [ ] Document `Animated` (link to RN and add examples)
- [ ] Document `ART` (link to docs)
- [ ] Create documentation app (remove storybook)
- [x] Include React Native version compatibility
- [x] Merge 'examples' and 'docs' directory on master branch
- [x] Update live examples in documentation
- [x] Add example on glitch.com
- [x] Fix online code editor example (i.e., webpackbin; requires React 16 and solution to #364)

Ref #168, #436, #475, #482

**Comment by peterschussheim** [comment]
@necolas I'd like to help with transitioning off of storybook. Do you have any notes on your ideas for the new documentation app?

**Comment by necolas** [comment]
Most of the docs are not coupled to storybook anymore. Replacing storybook could be done with a simple menu + content layout, where the menu is a drawer on smaller screens and fixed in place on wider screens (a bit like the current storybook UI). Storybook still doesn't have a mobile-friendly UI, so I'm still interested in this.

**Comment by MoOx** [comment]
I guess you should take a look to https://docusaurus.io if you want something dead simple. Otherwise, I can still help to setup https://phenomic.io (which should be really easy and could use RNW itself for the UI).

**Comment by kristerkari** [comment]
@necolas It would also be good to have better documentation for supported browsers. 

Currently the README just says `Browser support: Chrome, Firefox, Safari >= 7, IE 10, Edge`. 

From that I understand that Android stock browser is not supported, however the code has some references to supporting Android 4 / 4.4:
https://github.com/necolas/react-native-web/blob/e0d6ffa4a0d97bf8033bc0e55cb61e5b72f0fe72/packages/react-native-web/src/exports/AppState/index.js#L17-L19
https://github.com/necolas/react-native-web/blob/7f45c52ce78b21087f45bf8e5ac0a25b2eea5794/scripts/inline-style-prefixer/create.js#L8

If Android 4.4 stock is not supported it would be good to clearly document that and remove the references from code. It would also personally for me be interesting to know why Android stock is not supported.

I'm willing to help with documenting that if you let me know what the current browser support is.

**Comment by necolas** [comment]
Rethinking how to provide documentation, so closing this
