### ISSUE TITLE
TextInput not working in android chrome or firefox browsers, when touch on TextInput, mobile Keyboard open and close and not allow to writing

### ISSUE THREAD

**Issue by hosseinvadi777** [necolas/react-native-web#493]
**What is the current behavior?**

Link to minimal test case: (template: [codepen](https://codepen.io/necolas/pen/PZzwBR?editors=0010))

**What is the expected behaviour?**

**Steps to reproduce**

1.create text input
2.and open it in android mobile browsers

**Environment (include versions)**

OS: android
Device: mobile
Browser: chrome, firefox
React Native for Web (version): 0.0.77
React (version):15.4.2

**Comment by necolas** [comment]
Please upgrade the library version and then see if there is still a problem

**Comment by necolas** [comment]
Let me know if you still have issues with the latest version of the library

**Comment by weihuali0509** [comment]
@amirhosseinvz94 did you end up fixing it?
