### ISSUE TITLE
support enablesreturnkeyautomatically on TextInput ?

### ISSUE THREAD

**Issue by AlmaasAre** [necolas/react-native-web#495]
`If true, the keyboard disables the return key when there is no text and automatically enables it when there is text. The default value is false.`

https://facebook.github.io/react-native/docs/textinput.html#enablesreturnkeyautomatically

**Comment by necolas** [comment]
How would you do that on web?

**Comment by necolas** [comment]
`enablesReturnKeyAutomatically` is iOS only for now. I'm open to any viable PR that can provide similar functionality on web, but will close this issue in the mean time. Thanks
