### ISSUE TITLE
Backbutton Override?

### ISSUE THREAD

**Issue by tonyneel923** [necolas/react-native-web#497]
Is there a way to override the browsers native back button functionality?

**Comment by RangerMauve** [comment]
[Not really](https://stackoverflow.com/questions/24033040/override-browser-back-button), but you can do it with [Cordova apps](https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.backbutton.html)

**Comment by RangerMauve** [comment]
You can do some fancy stuff with [the history api](https://developer.mozilla.org/en-US/docs/Web/API/History_API?redirectlocale=en-US&redirectslug=DOM%2FManipulating_the_browser_history#Adding_and_modifying_history_entries) if you _have_ to use a browser
