### ISSUE TITLE
Link to client and server rendering guide is broken

### ISSUE THREAD

**Issue by karanjthakkar** [necolas/react-native-web#498]
**What is the current behavior?**
Link to `client and server rendering guide` in [AppRegistry](https://github.com/necolas/react-native-web/blob/master/docs/apis/AppRegistry.md) api doc is broken

**What is the expected behaviour?**
The document should either exist or the reference should be removed. Ideally I'd like to know what it pointed to so I can read more details.

**Comment by necolas** [comment]
Thanks. It should say and point to the "getting started" guide
