### ISSUE TITLE
Support Specifying Platform.OS

### ISSUE THREAD

**Issue by RyanThomas73** [necolas/react-native-web#499]
I have some projects that use react-native-web and a variety of other libraries and internal components to support cross-platform development between iOS, Android, and web. Due to the context of the projects it made more sense to label the 3rd platform as 'browser' instead of web and this is working fairly well for these projects.

For consistency it would be nice if we could specify that the api `Platform.OS` value will be 'browser' in lieu of 'web' for these projects. Currently the projects handle this by importing platform from a module within the project; a `Platform.browser.ts` override exists that sets the OS value. While this works It would be nice to minimize the the number of use cases where the normal imports e.g. `import { Platform } from 'react-native'` cannot be used.

My thoughts on this would be to update the Platform api module to check for the presence of a global/environment variable and to default to 'web' if the environment variable does not exist.
Then consumers who have uses cases where they needed something other than 'web' could specify it, via the webpack DefinePlugin for example, on a case by case basis.

Please let me know if you would accept a PR to support this.

**Comment by RangerMauve** [comment]
Using `.web.js` is standard practice with Webpack, you seem to have chosen a non-standard name. Even if this library gets patched, other tools that use the `.web.js` pattern will get in your way in the future.

**Comment by necolas** [comment]
I don't see why it needs to change from `web` to `browser`. Sounds like that's a decision you made in your internal codebase?

**Comment by RyanThomas73** [comment]
An example use case:
A cross platform react-native project targeting Android, iOS, a website, and a Electron. We want to be able to specify different .OS values between the website and Electron and this would provide such a mechanism.

**Comment by necolas** [comment]
Electron is still using the web platform. If you need to detect whether a web app is running in an electron context, I believe that information is added to the `window` object: https://github.com/electron/electron/issues/2288
