### ISSUE TITLE
createDOMElement causes underlying underlying components to remount

### ISSUE THREAD

**Issue by sondremare** [necolas/react-native-web#503]
**What is the current behavior?**

It is obvious that createDOMElement will create a new DOM-Element and thus cause any underlying components to be remounted. However I need to be able to set a className on a View so I can target it for some vanilla CSS. This webpackbin demonstrates how I have implemented my own "ViewWithClassName" to be able to set a className on it.
Link to minimal test case: https://www.webpackbin.com/bins/-KlcUt9VPOf4CPWpEcBQ

**What is the expected behaviour?**
I am basically asking for advice on how to add a className to a View, without having the side-effect of all children remounting upon a render.

**Steps to reproduce**

Just click the button and watch the console log out 'didMount' and 'willUnmount'

**Environment (include versions)**

OS: macOS Sierra 10.12.4
Device: MacBook Pro
Browser: Chrome (newest)
React Native for Web (version): 0.0.94
React (version): 15.5.4

**Comment by necolas** [comment]
Hi, that webpackbin throws errors and won't let me edit it. Can you repost a test case?

```
Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.r [as function] (main.d9727f1780b0b716e60b.js:1)
    at e.value (common.63a2669d700bfcbf45d0.js:1)
    at l (common.63a2669d700bfcbf45d0.js:1)
    at common.63a2669d700bfcbf45d0.js:1
    at e.value (common.63a2669d700bfcbf45d0.js:1)
    at l (common.63a2669d700bfcbf45d0.js:1)
    at common.63a2669d700bfcbf45d0.js:1
    at e.value (common.63a2669d700bfcbf45d0.js:1)
    at l (common.63a2669d700bfcbf45d0.js:1)
    at l (common.63a2669d700bfcbf45d0.js:1)
```

**Comment by sondremare** [comment]
https://www.webpackbin.com/bins/-Km_hJf4M_c6VAbsrmjv. Reposted @necolas

**Comment by necolas** [comment]
`ViewWithClassName` doesn't do anything that `View` doesn't do – `className` will pass through to the underlying DOM element (that's [documented here](https://github.com/necolas/react-native-web/blob/47ba46780c469038cd7336c9f54c83d0e633d90f/docs/components/View.md#props)). Example:

https://www.webpackbin.com/bins/-Kmncq1je6DlYTWmkBUm

You're also using `createDOMElement` in a way that is creating new functions and objects. If you simply to `createDOMElement('div', props)` (as `react-native-web` [does too](https://github.com/necolas/react-native-web/blob/47ba46780c469038cd7336c9f54c83d0e633d90f/src/components/View/index.js#L67))) the inner children don't unmount. Example:

https://www.webpackbin.com/bins/-KmnbBroSY4IUGR9GpW1
