### ISSUE TITLE
StyleSheet.renderToString() limitation what about a alternative renderToComponent()?

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#504]
Currently for SSR we only have `StyleSheet.renderToString()` which produce raw html.
If you wrap your SSR pages with... React, this method might not be appropriate as you have to rely on dangerousInnerHTML (and in head it's not optimal as div/span are not appropriate)

Are you open to add a new method (should be pretty easy according to the code in StyleManager) that basically wrap in jsx instead of raw html?

**Comment by necolas** [comment]
What is the return value were:

```js
{
  element: <App />
  stylesheets: [
    <style ...>,
    <style ...>
  ]
}
```

Then you can use React's `renderToString` to convert the app tree and style sheets to HTML string.

**Comment by MoOx** [comment]
Sorry I am not sure to follow you here.

Currently I have to do this (example simplified, I also have other stuff in practise, like react-helmet static rendering)

```js
const Html = (props: HtmlPropsType) => {
  const helmet = Head.renderStatic();
  // https://github.com/necolas/react-native-web/issues/504
  const styles = StyleSheet.renderToString().split("</style>");
  const staticStyles = styles[0].replace(
    '<style id="react-native-stylesheet-static">',
    ""
  );
  const mainStyles = styles[1].replace(
    '<style id="react-native-stylesheet">',
    ""
  );
  return (
    <html>
      <head>
        <style id="react-native-stylesheet-static">{staticStyles}</style>
        <style id="react-native-stylesheet-static">{mainStyles}</style>
      </head>
      <body>
        {props.body}
      </body>
    </html>
  );
};
```

but it not really great.

**Comment by necolas** [comment]
> Sorry I am not sure to follow you here.

`AppRegistry` would return an array of `style` elements alongside the app's element. That should allow you to use:

```js
{stylesheets.map((stylesheet) => stylesheet)}
```

…in your React HTML document, or allow people to use:

```js
const styleHTML = stylesheets.map((stylesheet) => ReactDOMServer.renderToString(stylesheet)).join('')
```

…if they are using string templates

**Comment by MoOx** [comment]
The thing is: I am not using AppRegistry 🙃.
Will have a look if I can adjust this since in my project, I don't know if RNW is used or not.

**Comment by MoOx** [comment]
According to [tests](https://github.com/necolas/react-native-web/blob/77fd8674215c0c2bd1ea447786df4f981d08a1c8/src/apis/AppRegistry/__tests__/renderApplication-test.js#L10) there is no "stylesheets" but a single "stylesheet" (which is [a string](https://github.com/necolas/react-native-web/blob/77fd8674215c0c2bd1ea447786df4f981d08a1c8/src/apis/AppRegistry/__tests__/__snapshots__/renderApplication-test.js.snap#L12) - because rendered via `renderToString()` (which use [StyleRegistry.getStyleSheetHtml()](https://github.com/necolas/react-native-web/blob/77fd8674215c0c2bd1ea447786df4f981d08a1c8/src/apis/StyleSheet/index.js#L29)).
So this does help me.
I could hack the thing by importing StyleRegistry and accessing StyleManager, but I won't be able to benefit of [this particular piece of code](https://github.com/necolas/react-native-web/blob/65055028c681927448774eb61d53e777acbf9ece/src/apis/StyleSheet/StyleManager.js#L89-L99) - which I am pretty sure exist for a reason :)

**Comment by MoOx** [comment]
So this **doesn't** help me.*

**Comment by necolas** [comment]
Yes, `AppRegistry` is the main API and whatever it needs is going to be what I build into something like `StyleSheet`. Anyway, I'll return React elements rather than string

**Comment by necolas** [comment]
Let me know if [this branch](https://github.com/necolas/react-native-web/tree/necolas/style-elements) is any better. Patch https://github.com/necolas/react-native-web/commit/cd87a62b11d26d63de91dbc47a67526a1259b39a
