### ISSUE TITLE
Ability to use this package without using Webpack?

### ISSUE THREAD

**Issue by joncursi** [necolas/react-native-web#505]
Is there a way to conditionally import `react-native` or `react-native-web` based on the target platform other than using the module aliasing feature in webpack?

I'm using [Meteor](https://www.meteor.com/) as my web client, which has it's own built-in build tool, so I don't have webpack in my stack. So webpack configuration is unfortunately not an option for me. I'm guessing I need something along the lines of...

```js
const {
  Text,
} = require(SOME_CONDITION ? 'react-native' : 'react-native-web');
```

... but I'm not sure what that condition would be or if this is the next best way to do it.

For more information, refer to [this StackOverflow question](https://stackoverflow.com/questions/44376957/how-to-alias-imports-in-meteor-react-native-web) I just posted.

Thanks!

**Comment by necolas** [comment]
Looks like there is a known Meteor issue: https://github.com/meteor/meteor/issues/5869

If there's no way for Meteor apps to alias paths, you could try using this wrapper around `react-native` and `react-native-web`: https://github.com/lelandrichardson/react-primitives

**Comment by joncursi** [comment]
For anyone else that is interested, I've opted to go with:

```js
const {
  Platform,
  StyleSheet,
} = RUNTIME_PLATFORM === 'web' ? require('react-native-web') : require('react-native');
```

Where `RUNTIME_PLATFORM` is:

```js
const RUNTIME_PLATFORM = global.__meteor_runtime_config__
  ? 'web'
  : 'native';

```

**Comment by joncursi** [comment]
@benjamn ^ is this a "good" / reliable way to detect if the current node environment is Meteor?

**Comment by benjamn** [comment]
@joncursi That works, though I would recommend `global.Meteor && global.Meteor.isClient` instead. Thanks for asking!
