### ISSUE TITLE
StyleSheet: "cursor" not a valid prop type

### ISSUE THREAD

**Issue by kennethlynne** [necolas/react-native-web#506]
One is not able to style `cursor` using StyleSheet. 

One should be able to set cursor. 

```
Warning: Failed prop type: Invalid props.style key `cursor` supplied to `Image`.
Bad object: {
  "cursor": "default",
...
```

**Comment by necolas** [comment]
You can supply cursor to view https://github.com/necolas/react-native-web/blob/master/src/components/View/ViewStylePropTypes.js

**Comment by roysG** [comment]
any update?

**Comment by roysG** [comment]
The link os not active, any update?

**Comment by aizotov** [comment]
I'm getting a 404 at that link. Would you paste the solution here?

**Comment by toto1384** [comment]
@aizotov just supply `cursor: 'pointer'` to your View stylesheet. 

If typescript throws an error just do

```
<View style={{
      alignItems:'flex-end',
      //@ts-ignore
      cursor:'pointer'
  }} >{text}</View>
```

**Comment by jchook** [comment]
`cursor` apparently exists on [`InteractionStyles`](https://github.com/necolas/react-native-web/blob/dc9ecfbc84c7e6cbf0c36c537ac1b0a86b7e43c1/packages/react-native-web/src/types/styles.js#L132) which are spread on [`ViewStyle`](https://github.com/necolas/react-native-web/blob/dc9ecfbc84c7e6cbf0c36c537ac1b0a86b7e43c1/packages/react-native-web/src/exports/View/types.js#L82).

**Comment by jchook** [comment]
In TypeScript you may still get this error, even with `// @ts-ignore`:

```error
Invariant Violation: "cursor" is not a valid style property.
```

You can resolve this with `Platform.select()`, e.g.

```typescript
import { Platform } from 'react-native'

<View style={{
  alignItems: 'flex-end',
  ...Platform.select({ web: {
    cursor: 'pointer',
  }}),
}} />
```

**Comment by hardrese7** [comment]
@jchook thank you! the solution works perfectly, but it doesn't when there's only one style property `cursor: pointer`

example:
```
const styles = StyleSheet.create({
  hoverable: {
    ...Platform.select({
      web: {
        cursor: 'pointer',
      },
    }),
  },
});
```

error:
`Type '{ cursor?: string | undefined; }' is not assignable to type 'ViewStyle | TextStyle | ImageStyle'.`

I can add some property to fix it, like `testID`, but maybe there's more a clean way to do it?

**Comment by Snegirman** [comment]
@hardrese7 You can add default property for view `display: flex`. Like: 
```
const styles = StyleSheet.create({
  hoverable: {
      display: 'flex',
    ...Platform.select({
      web: {
        cursor: 'pointer',
      },
    }),
  },
});
```
