### ISSUE TITLE
Touchable's onPressIn() have wrong nativeEvent payload since 0.0.78

### ISSUE THREAD

**Issue by cloudle** [necolas/react-native-web#508]
**On 0.0.77 and before, the Touchable components's `onPressIn(e)` e.g:**
```
onPressIn(e) {
  console.log(e.nativeEvent)
}
```
Have `event.NativeEvent` look like this (which is accurate/similar to Native Mobile event):

<img width="536" alt="screen shot 2017-06-07 at 5 03 34 pm" src="https://user-images.githubusercontent.com/11600914/26873223-43dd2b40-4ba3-11e7-9140-b8f50ebfd339.png">

**But starting on 0.0.78, it look totally different.. like this:**

<img width="542" alt="screen shot 2017-06-07 at 4 52 37 pm" src="https://user-images.githubusercontent.com/11600914/26872786-0073d58a-4ba2-11e7-8ee9-26c8b791440b.png">

We lost { `locationX`, `locationY`, `pageX`, `pageY`... } (it also cause some library like `react-native-drawer` bahave buggy on Browser) - and I couldn't found them inside `touches` array too.. we.

Is it a bug or we do have different way to handle this place?

**Comment by necolas** [comment]
Doh. Thanks! This should be fixed in 0.0.98
