### ISSUE TITLE
[View]: Specify the HTML element type to render into?

### ISSUE THREAD

**Issue by joncursi** [necolas/react-native-web#509]
I noticed that my rendered output from `react-native-web` is div soup. Is it possible to specify, perhaps via prop to each `View` component, which HTML element it should render to?

E.g. default behavior is:

```
<div>
  <div></div>
  <div></div>
<div>
```

Desired behavior is:

```
<section>
  <main></main>
  <footer></footer>
</section>

```

**Comment by MoOx** [comment]
See https://github.com/necolas/react-native-web/blob/master/docs/components/View.md#props & https://github.com/necolas/react-native-web/blob/master/docs/guides/accessibility.md

**Comment by joncursi** [comment]
Thanks for the second link, that was helpful.

I was able to verify that `accessibilityRole="main"` rendered to a `<main />` DOM node, but `accessibilityRole="section"` and `accessibilityRole="footer"` still render to `<div />`

**Comment by joncursi** [comment]
Ah, I think I found the mapping I was looking for: https://github.com/necolas/react-native-web/blob/ae13873c2cb9a932bd4f82bcec4dad96c8eed56c/src/modules/AccessibilityUtil/propsToAccessibilityComponent.js#L3-L16

**Comment by joncursi** [comment]
Is there a way to render a `span` instead of a `div`, to take advantage of automatic `display: inline`?

I don't see `span` in the mapping: https://github.com/necolas/react-native-web/blob/ae13873c2cb9a932bd4f82bcec4dad96c8eed56c/src/modules/AccessibilityUtil/propsToAccessibilityComponent.js#L3-L16

**Comment by MoOx** [comment]
All RN(W) components are flex. No display block or inline (because RNW mimic RN that rely on yoga engine which only implement display flex).

**Comment by joncursi** [comment]
Ah gotcha, thank you again!
