### ISSUE TITLE
pointerEvents not working correctly as of 0.98

### ISSUE THREAD

**Issue by appden** [necolas/react-native-web#513]
As of [d08a1c8](https://github.com/necolas/react-native-web/commit/77fd8674215c0c2bd1ea447786df4f981d08a1c8), I'm finding that `pointerEvents` isn't quite working right because the `AppContainer` sets `pointerEvents="box-none"` on its `View`. This would be fine, but there a couple issues with the current pointer-events CSS:

- The class name rules should have `!important` so they aren't overridden by the `.box-none *` (et al) selectors, which have higher specificity.
- The `box-none` and `box-only` should use direct descendant selector (e.g. `> *`)

Here's an example of the specificity issue:

![image](https://user-images.githubusercontent.com/70904/27007787-5048301e-4e14-11e7-99ad-bdea166ea813.png)

**What is the current behavior?**

Link to minimal test case: https://codepen.io/anon/pen/pwyEJQ?editors=0010

**What is the expected behaviour?**

`pointerEvents="none"` applies to descendants unless overridden by them.

**Environment (include versions)**

OS: Mac
Device: Mac
Browser: Chrome
React Native for Web (version): 0.98+

**Comment by appden** [comment]
@necolas You're freakin awesome. Thanks so much for fixing this issue so quickly!

**Comment by necolas** [comment]
No problem, thanks for reporting the issue and describing the fix. It should be in 0.0.100. Let me know if you notice any other problems
