### ISSUE TITLE
CSS rendering much slower than html output in iOS webview

### ISSUE THREAD

**Issue by Kinka** [necolas/react-native-web#517]
I'm encoutering a rendering problem in ios browser, ios version 10.6. This is the test page: https://fudao.qq.com/rn4web/discover.html

The problem is that there is before the content with CSS styles applied I can saw the version without CSS styles yet. Android browser has no such problem. I tried extracting the css using `StyleSheet.renderToString`, and copy them into page's html, then got a better performance.

So it seems to be a problem css rendering slower than html output?

**Comment by necolas** [comment]
I thought this might come up at some point. Try commenting out the requestAnimationFrame wrapper in `node_modules/react-native-web/dist/apis/StyleSheet/StyleManager.js`

**Comment by Kinka** [comment]
Yes, commenting out makes better result. So what's your concern adding requestAnimationFrame, the problem I mention above occurs almost every time.

**Comment by necolas** [comment]
Yeah we'll want to remove the use of requestAnimationFrame

**Comment by Kinka** [comment]
I think of another question, is mobile.twitter.com using react-native-web?  I wonder how does it merge so many classnames into just several ones. Too many classnames would influence the rendering performance?

**Comment by necolas** [comment]
mobile.twitter.com was already using css-modules, so it uses a limited fork of react-native-web that replaces the library's styles with css-modules definitions. There doesn't appear to be a problem with using many class names
