### ISSUE TITLE
TextInput: onKeyPress does not return correct values

### ISSUE THREAD

**Issue by sondremare** [necolas/react-native-web#518]
**What is the current behavior?**

onKeyPress does not trigger when backspace is pressed.
Link to minimal test case: https://codepen.io/anon/pen/PjGJyx?editors=0010

**What is the expected behaviour?**
That onKeyPress triggers when backspace is pressed. 

I know that onKeyPress is not triggered for backspace on regular html input-fields.
However, with those one has the option to listen to onKeyDown, which is triggered for backspace. 

**Steps to reproduce**

1. Open dev tools, more specifically the console.
2. Focus the TextInput and type something, every key is logged.
2. Hit backspace, nothing is logged. 

**Environment (include versions)**

OS: macOS Sierra 10.12
Device: Macbook Pro
Browser: Chrome 58
React Native for Web (version): 0.0.94
React (version): 15.5.4

**Comment by necolas** [comment]
It looks like `onKeyPress` should be returning the string value of each key too
