### ISSUE TITLE
react update

### ISSUE THREAD

**Issue by punksta** [necolas/react-native-web#525]
Hello! Thanks for nice library. 
Last versions of `react-native` uses  newer version of `react `

```
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.0",
```

**Comment by necolas** [comment]
You'll have to keep using 15.5 or 15.6 rather than alpha versions

**Comment by zarcode** [comment]
@necolas yes, but is it possible to use them both react-native-web and react-native in same project and not to downgrade react-native version?

**Comment by RangerMauve** [comment]
@zarcode Not easily. At that point it'd be easiest to split your project into two. You could try to install the older verision of React manually in the `node_modules/react-native-web` folder and then add an alias in your webpack config to map `"react": "./node_modules/react-native-web/node_modules/react"`. That way when the react-native bundler runs it'll use the more recent React version, and when you build for web using webpack, it'll use the older version of React that you bundled in react-native-web. This approach is pretty fragile, however.

**Comment by necolas** [comment]
Also see #364, which is about getting React 16 to expose enough APIs for RNW to use the ResponderEventPlugin. Please comment on the relevant React issue too if this matters to you
