### ISSUE TITLE
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner'

### ISSUE THREAD

**Issue by damiaozi** [necolas/react-native-web#529]
./node_modules/.bin/webpack-dev-server --inline
can not run

package.json
`{
    "name": "ReactNativeWeb",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest"
    },
    "dependencies": {
        "babel-core": "^6.25.0",
        "babel-loader": "^7.0.0",
        "babel-preset-es2015": "^6.24.1",
        "babel-preset-react": "^6.24.1",
        "react": "^16.0.0-alpha.6",
        "react-dom": "^15.6.1",
        "react-native": "^0.44.0",
        "react-native-web": "0.0.103",
        "webpack": "^2.6.1"
    },
    "devDependencies": {
        "babel-jest": "20.0.3",
        "babel-preset-react-native": "2.0.0",
        "jest": "20.0.4",
        "react-test-renderer": "^16.0.0-alpha.6",
        "webpack-dev-server": "^2.4.5"
    },
    "jest": {
        "preset": "react-native"
    }
}`

ERROR in ./~/react-dom/lib/traverseAllChildren.js
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner' in 'E:\rn4web\ReactNat                                                                                                                       iveWeb\node_modules\react-dom\lib'
 @ ./~/react-dom/lib/traverseAllChildren.js 15:24-62
 @ ./~/react-dom/lib/ReactChildReconciler.js
 @ ./~/react-dom/lib/ReactMultiChild.js
 @ ./~/react-dom/lib/ReactDOMComponent.js
 @ ./~/react-dom/lib/ReactDefaultInjection.js
 @ ./~/react-dom/lib/ReactDOM.js
 @ ./~/react-dom/index.js
 @ ./~/react-native-web/dist/module.js
 @ ./~/react-native-web/dist/index.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.web.js
webpack: Failed to compile.

**Comment by necolas** [comment]
React 16 is not currently supported, as mentioned in the Readme

**Comment by damiaozi** [comment]
thank you
