### ISSUE TITLE
unable to resolve module react/lib/ReactPropTypes

### ISSUE THREAD

**Issue by damiaozi** [necolas/react-native-web#530]
I only npm install rn4web,

am trying to connect the react component with my native android app(Time being am experimenting with hello world project ) but its failing with following error. Any help would be appreciated.

Pkg.json config

            "react": "^16.0.0-alpha.6",
	"react-dom": "^15.6.1",
	"react-native": "^0.44.0",
	"react-native-web": "0.0.103",
	"webpack": "^2.6.1"
StackTrace

bundling: UnableToResolveError: Unable to resolve module react/lib/ReactPropTypes from /Users/myMac/Documents/Androidapps/TestReactNative/node_modules/react-native/Libraries/Image/Image.android.js: Module does not exist in the module map or in these directories:

**Comment by necolas** [comment]
React 16 is not currently supported

**Comment by damiaozi** [comment]
thank you
