### ISSUE TITLE
What version of react-native is supported?

### ISSUE THREAD

**Issue by zhangking** [necolas/react-native-web#532]

**Comment by damiaozi** [comment]
i use 0.39.2

**Comment by RyanThomas73** [comment]
**'react-native' version:** 0.42.3

From v0.43.0+ react-native has a react peer dependency of `16.0.0-alpha.X` and react-native-web won't currently work with the 16.0 versions of react.

**Comment by necolas** [comment]
Closing as a duplicate of a task in #491
