### ISSUE TITLE
flex Not in force

### ISSUE THREAD

**Issue by damiaozi** [necolas/react-native-web#533]
why items can't Vertically-center?
why container can't full-screen？

[package.json](https://github.com/damiaozi/ReactNativeWeb/blob/master/package.json)
`"babel-core": "^6.25.0",
		"babel-loader": "^7.0.0",
		"babel-preset-es2015": "^6.24.1",
		"babel-preset-react": "^6.24.1",
		"react": "^15.4.0",
		"react-dom": "^15.4.0",
		"react-native": "^0.41.0",
		"react-native-web": "0.0.103",
		"webpack": "^2.6.1"`

[code:index.web.js](https://github.com/damiaozi/ReactNativeWeb/blob/master/index.web.js)
`
class ReactNativeWeb extends Component {
  render() {return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native For Web!</Text>
        <Text style={styles.instructions}>
          To get started, edit index.web.js</Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload</Text>
      </View>);  }}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
`

**Comment by necolas** [comment]
Try the latest version
