### ISSUE TITLE
React-Navigation

### ISSUE THREAD

**Issue by damiaozi** [necolas/react-native-web#534]
The react native React-Navigation library is approaching maturity, and I'd like to add it into RN-web. I'm working on allowing routing and navigation code to be shared between web and RN.

Would this be accepted?

**Comment by necolas** [comment]
Hi. No, `react-navigation` is a separate project. Any bridging code for web should be added to `react-navigation`. Thanks

**Comment by damiaozi** [comment]
but，my RN project use `react-navigation` now。now，I‘d like to shared code between web and RN.How to replace it？

**Comment by necolas** [comment]
You can share the code as a pull request to `react-navigation`. Why do you want to add code to this project?

**Comment by damiaozi** [comment]
Sorry, my English is rather poor, can I speak Chinese?I never say accurately  my question

**Comment by necolas** [comment]
I don't understand Chinese
