### ISSUE TITLE
how can I know what library I can use？

### ISSUE THREAD

**Issue by damiaozi** [necolas/react-native-web#535]
how can I know what library I can use？
there are all the library on my RN project。

  ```
  "react": "16.0.0-alpha.6",【need use，15.4】
    "react-native": "0.44.0",【need use，0.41.0】
   "react-native-vector-icons": "^4.2.0",【can use】
    "react-navigation": "^1.0.0-beta.9"【can use】
```
    "react-native-actionsheet": "^2.1.0",
    "react-native-check-box": "^1.0.4",
    "react-native-image-progress": "^0.6.0",
    "react-native-loading-spinner-overlay": "^0.5.0",
    "react-native-progress": "^3.2.1",
    "react-native-qq": "^2.0.5",
    "react-native-scrollable-tab-view": "^0.6.6",
    "react-native-simple-radio-button": "^2.5.0-alpha.1",
    "react-native-snackbar-dialog": "^1.3.0",
    "react-native-star-rating": "^1.0.7",
    "react-native-swiper": "^1.5.4",
   
Last time I checked，Four in the front row can use on web。
But, other library, how do I know if I can use?
Please give me some advice
@ericwooley
@agrcrobles
@ngduc
@necolas

**Comment by necolas** [comment]
Use on web? You probably can't know without reading the code or trying to run it

**Comment by ericwooley** [comment]
You can usually search the issues for `react-native-web` and someone has probably already opened an issue. You can see what their issues are.

**Comment by damiaozi** [comment]
@ericwooley thank you. I well do
