### ISSUE TITLE
too much useless class names

### ISSUE THREAD

**Issue by VincentWang1009** [necolas/react-native-web#538]
when i use react native web,i found there are too much useless classnames on dom. for an example .rn-paddingLeft-gy4na3 {
  padding-left: 0px;
} on div. it result in bigger html file.
Is there some solutions to solve it?

**Comment by zhangking** [comment]
yep~   It makes my files too large . Wether I can use webpack plugins to merge the classNames .
Expect good solutions

**Comment by necolas** [comment]
After gzip the size difference for HTML files is not substantially different
