### ISSUE TITLE
Forward arrow key presses on text input

### ISSUE THREAD

**Issue by kennethlynne** [necolas/react-native-web#539]
React-native will forward key press events like enter and backspace as "Enter" and "Backspace" for the key property of the nativeEvent payload. 

React-native-web probably needs to support some more use cases since it is used on desktop. 

I currently miss being able to listen for left and right arrow key presses.

I suggest firing events for arrow presses, with the key payload set to "Left arrow", "Up arrow", "Down arrow" and "Right arrow" respectively. I can send a PR for this ASAP if this is agreed on.

**Comment by necolas** [comment]
What is the use case though?

**Comment by necolas** [comment]
We can discuss on the PR instead
