### ISSUE TITLE
Image: SSR

### ISSUE THREAD

**Issue by jeans11** [necolas/react-native-web#543]
First, good job for this amazing lib, I love it.

**What is the current behavior?**

I meet a little mistake with the **Image** component. In fact, he is not render with SSR. The **img** element is not created.

**What is the expected behaviour?**

The **Image** component should be render with SSR

**Steps to reproduce**

Render an **Image** with [RNW AppRegistry](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#server-side-rendering)

**Environment (include versions)**

OS: Mac Os Sierra 10.12.1
Device: Desktop
Browser: NodeJS V7.4.0
React Native for Web (version): 0.0.105
React (version): 15.5.4

**Comment by necolas** [comment]
Thanks, this should be fixed in master

**Comment by jeans11** [comment]
Amazing !

**Comment by necolas** [comment]
Thinking about this some more, I think I'll have to revert the change.

1. Client-side render won't know the image is already rendered/loaded, so there will be a checksum mismatch _and_ the image will be reloaded.
2. The browser will download images from the SSR HTML and that can compete for bandwidth with the scripts, slowing down time-to-interactivity.

**Comment by AlexBrasileiro** [comment]
Hello guys :)

I'm also having problems rendering the images on SSR, In my case with ImageBackground component.

I have two webpack configs:

**webpack.client.config**
```javascript
const path = require('path');
const merge = require('webpack-merge');
const baseConfig = require('./webpack.base');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const config = {
  entry:  './src/client.js',
  mode: 'none',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'client')
  },
};

module.exports = merge(baseConfig, config);
```

**webpack.server.config**
```javascript
const path = require('path');
const merge = require('webpack-merge');
const baseConfig = require('./webpack.base');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const webpackNodeExternals = require('webpack-node-externals');

const config = {
  target: 'node',
  entry:  './src/server.js',
  mode: 'none',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'server')
  },
  plugins: [
    new ExtractTextPlugin('./client/css/app.css'),
  ],
  externals: [webpackNodeExternals()],
  module: {
    rules: [
      {
        test: /\.woff|.woff2|.ttf|.eot*.*$/,
        loader: 'file-loader',
      },
      {
        test: /\.(png|jpe?g|gif)$/,
        loader: 'react-native-web-image-loader?name=[path][name].[ext]'
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('css-loader', 'style-loader')
      }
    ]
  },
};

module.exports = merge(baseConfig, config);
```

And on my componente: **BG.js**
```javascript
import React, { Component } from 'react';
import { StyleSheet, ImageBackground } from 'react-native';

const BG = props => (
  <ImageBackground style={[styles.backgroundImage, props.style]} source={require('../../../img/bg.jpg')}>{props.children}</ImageBackground>
)

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1
  }
});

export { BG }
```

I tried several webpack (server and client) configurations and tried to change the path of the images in my component, but without any success.

Any idea?
Many thanks Necolas :)

**Comment by MoOx** [comment]
I spend a few hours debugging some mess created by duplicated source/defaultSource with inline styles on some images...

So if anyone have weird issue with SSR & React.hydrate: just don't add inline styles on `<Image`. Add style around + overflow hidden if you got radius. Hope this advice help.
