### ISSUE TITLE
Module not found: Error: Can't resolve 'react-native/Libraries/EventEmitter/EventEmitter'

### ISSUE THREAD

**Issue by damiaozi** [necolas/react-native-web#545]
what can I do？

ERROR in ./~/react-native-root-siblings/lib/AppRegistryInjection.js
Module not found: Error: Can't resolve 'react-native/Libraries/EventEmitter/EventEmitter' in 'E:\workspace\fjsgo\node_modules\react-native-root-siblings\lib'
 @ ./~/react-native-root-siblings/lib/AppRegistryInjection.js 4:18-77
 @ ./~/react-native-root-siblings/lib/SiblingsManager.js
 @ ./~/react-native-snackbar-dialog/dist/SnackBarManager.js
 @ ./~/react-native-snackbar-dialog/dist/index.js
 @ ./src/common/ToastUtil.js
 @ ./src/ImageVerificationCode.js
 @ ./src/Navigator.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server react-hot-loader/patch ./index.web.js

**Comment by necolas** [comment]
There's no reason to expect that react native internals are going to be available from this package. If you're using external packages that depend on react native internals you won't be able to use them on web, and you could ask them to fix the issue

**Comment by damiaozi** [comment]
thank you
