### ISSUE TITLE
SSR mistakes

### ISSUE THREAD

**Issue by jeans11** [necolas/react-native-web#546]
**What is the current behavior?**

**TouchableOpacity** no fire event when you click on it after that the page was loaded with SSR.
**ScrollView** no scroll when the page was loaded with SSR.

**What is the expected behaviour?**

**TouchableOpacity** should be fire event even if the page was loaded with SSR.

**Steps to reproduce**

1. Render a TouchableOpacity with [RNW AppRegistry for server](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#server-side-rendering)
2. Render client side with [RNW AppRegistry for client](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#client-side-rendering)

**Environment (include versions)**

OS: MacOs Sierra 10.12.1
Device: Desktop
Browser: Chrome 58.0.3029.110 (64-bit)
React Native for Web (version): 0.0.105
React (version): 15.6.1

**Comment by necolas** [comment]
Have you loaded the JavaScript on the client after the SSR?

**Comment by necolas** [comment]
Please share an example. Like make a GitHub repo and host the output on gh-pages

**Comment by jeans11** [comment]
Yes, I load the JavaScript on the client after the SSR. I prepare an example.

**Comment by jeans11** [comment]
My test repo is here: https://github.com/jeans11/react-native-web-ssr

In fact, when the server render the **stylesheets**, TouchableOpacity component no fire event after SSR. But, if the stylesheets are not loaded by the server, it's works.

**Comment by necolas** [comment]
Thanks for this. It was a bug in the `AppRegistry` that caused CSS text to be escaped when rendered on the server, and all pointer events got disabled on the document!

**Comment by jeans11** [comment]
Awesome ! Thank you !
