### ISSUE TITLE
adding a brief descrip about why is it useful

### ISSUE THREAD

**Issue by dnecklesportfolio** [necolas/react-native-web#547]
"This guide will help you to correctly configure build and test tools to work with React Native for Web"

for beginners, can you explain a little bit about why someone may want to do this?  I didnt get it.

Thanks a lot

**Comment by necolas** [comment]
You can't build or test your app without it. If you're new to React, you should probably use the starter kits that are referenced (like create-react-app) instead of spending time setting up your own build/test workflow. You can learn about the build tools later.
