### ISSUE TITLE
Suggested workaround for tintColor

### ISSUE THREAD

**Issue by netlogic** [necolas/react-native-web#548]
#362 is only editable by collaborators.  So I apologize if this is not the correct way to add a comment.
Please feel free to close this after reading.

Would just like to add to #362 I was able to simulate tintColor with Image by always having a white image and then by adding the following two properties to my style:

backgroundBlendMode: 'multiply',  backgroundColor: YOURCOLORTOTINT

Thank you for a great package.
regards,
Bret

**Comment by netlogic** [comment]
Not sure this is working on all platforms closing until sure.

**Comment by AryanJ-NYC** [comment]
Any updates on this workaround?

**Comment by jrc** [comment]
I'm unable to get this workaround to work (tried on both MS Edge for Mac 99.0.1150.52  and iOS 14.5 Safari). The `backgroundBlendMode: 'multiply'` part seems to have no effect.
