### ISSUE TITLE
Timeline for react 16

### ISSUE THREAD

**Issue by TikiTDO** [necolas/react-native-web#553]
We're using react-native-web in production for a mutli-platform system, including a variety of different apps (some native, some web, some both) using a few common modules. I would like to unify these apps into one code base, however I have not had much success because react-native-web depends on react 15, while several tools and libs we use depend on react 16.

I was wondering what the timeline for migrating react-native-web to react 16 was, and whether anyone has experimented with this in a fork.

**Comment by necolas** [comment]
See #364

**Comment by TikiTDO** [comment]
Thanks for the link. May I recommend changing the title of that issue to include react 16 so that it's easier to find using the built in search.
