### ISSUE TITLE
Links: new component for web or add `href` prop?

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#56]
The project currently includes an undocumented hack of sorts for anchors: using `accessibilityRole='link' +`href`(undocumented prop / all unknown props are passed through). I think it would be preferable not to pass through unknown props (other than perhaps`aria` for now) so that means either:
1. Add `href` prop to `View`, `Text`, and `Touchable`
2. Create a `Link` component based on `Text`

This issue isn't really encountered if using react-router because it provides its own `Link`, but it might also be useful to port the react-router `Link` component (as a separate module) so the styles can be prefixed and className-ified.

**Comment by grigio** [comment]
Personally I don't like `<Link />` an alternative way is is to use [browserHistory](https://github.com/reactjs/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md) from react-router, but it doesn't work with React Native, so the most neutral approach should be to dispatch a generic (router independent) action

``` javascript
...
import { browserHistory } from 'react-router'

export default class AboutPage extends Component {
  render() {
    return (
      <View>
        <Text>About or</Text><Text onPress={() => browserHistory.push('/home') }>Go home</Text>
      </View>
    )
  }
}
```

**Comment by faceyspacey** [comment]
I personally like being able to apply an `href` to the mentioned elements and for it to become an `<a>` tag. For SEO, it can't just be a *browserHistory* solution. 

One issue I found: I'm currently using `accessibilityRole` and the href doesn't work on `touchable` only `<View>` and `<Text>`.

**Comment by mattferrin** [comment]
I like this:
> Create a `Link` component based on `Text`

It seems worthwhile, not only to support SEO and code portability, but to help map existing `<a />` tag standard attributes to sane defaults like the `Linking` API or `WebView` component when each is applicable.

**Comment by RangerMauve** [comment]
Wouldn't the [Linking API](https://facebook.github.io/react-native/docs/linking.html) be more appropriate for this? Sure we're used to anchors and `href` in HTML, but it the goal is to be one-to-one compatible with React-Native, then people should be using the same APIs for opening links. It would be easy enough for people to create userland libraries that abstract over this for web-specific projects, however.

**Comment by necolas** [comment]
There's now support for `Linking` an pass-through of `href` (not for Touchables yet)
