### ISSUE TITLE
TextInput: support placeholderTextColor

### ISSUE THREAD

**Issue by Hkmu** [necolas/react-native-web#560]
### Code 
```javascript
<TextInput placeholderTextColor={'#FFF'} />
````

### Result
![demo](https://user-images.githubusercontent.com/3169251/28014533-8c50f5d0-659f-11e7-9c47-7f9ce6e4938c.png)

**Comment by RyanThomas73** [comment]
@necolas Do you have any thoughts on how you would like to approach this? I didn't want to have to implement my own placeholder functionality when browsers already support this.

Currently I have two workarounds to achieve this functionality, but I wouldn't mind contributing towards direct support if you have thoughts on how you would like to implement it.

For those that need to create a workaround I've managed to roughly support this using the below two approaches.

1) The first workaround approach I've used depends on having an id (or adding a class after the fact using ref) and inserting my own stylesheet rules.

2) The alternate workaround is a monkey patch to `StyleManager.setDeclaration` and to `TextInputStylePropTypes`. In the patch I check for a special style prop name 'placeholderColor'
and create a separate flow of the setDeclaration logic that generates the css in the format:
`.${className}${psuedoElement} { color: ${value} }`.


```
export class MyTextInput extends Component {
    ....
    render() {
         ... doing stuff ...
         let placeholderColorStyle = undefined;
         if( web platform ) {
               // with my monkey patch in place the placeholderColor
               // prop name generates the class name like `rn-placeholderColor-${hashValue}`
               // and then generates the css in the format `.${className}${pseudoElement} { color: ${value} }`
              placeholderColorStyle = StyleRegistry.register({ placeholderColor: calculatedPlaceholderColor }); 
         }

         const computedStyles = [.... some styles ..., placeholderColorStyle, .... remaining styles ...];
         return (
               <TextInput style={computedStyles} {...otherTextInputProperties} />
         )
    }
}  
```

**Comment by VinceBT** [comment]
I'd like this feature a lot

**Comment by wordyallen** [comment]
@RyanThomas73 
Could you please elaborate a little more on approach #2 ?

**Comment by leggomuhgreggo** [comment]
@necolas hey, apologies if this is subject of `placeholderTextColor` has become at all tiresome, but:

I was reviewing the patch where support was deprecated / the PRs it referenced, and it wasn't immediately clear to me what the impetus for dropping it -- was it api inconsistencies with placeholder positioning with RN? 

It's the type of thing I'd be happy to work on if you'd be able to give a little background / direction. 

Appreciate your time, man, thanks.

**Comment by nikoloza** [comment]
This workaround helped me:
```
import { Platform } from 'react-native'
const placeholderTextColor = '#123'

if (Platform.OS === 'web') {
  const placeholderStyle = document.createElement('style')
  placeholderStyle.innerHTML = `
    ::-webkit-input-placeholder { color: ${placeholderTextColor} }
    ::-moz-placeholder { color: ${placeholderTextColor} }
    :-ms-input-placeholder { color: ${placeholderTextColor} }
    :-moz-placeholder { color: ${placeholderTextColor} }
  `
  document.head.appendChild(placeholderStyle)
}
```
---
Or implementing it by more React way:
```
class WebPlaceholderColor extends React.Component {
  static defaultProps = {
    selector: '',
    color: '#CCC',
  }

  render() {
    const { color, selector } = this.props
    return Platform.OS === 'web' ? (
      <style>
        {`
          ${selector}::-webkit-input-placeholder { color: ${color} }
          ${selector}::-moz-placeholder { color: ${color} }
          ${selector}:-ms-input-placeholder { color: ${color} }
          ${selector}:-moz-placeholder { color: ${color} }
        `}
      </style>
    ) : null
  }
}
```

and just put `<PlaceholderWebColor />` somewhere in the root.

PS: You can consider [Helmet](https://github.com/nfl/react-helmet) for putting it inside `<head>`

**Comment by zingerj** [comment]
This is still not working for me on web. I have tried using `styled-components` and vanilla RN, and neither seems to change the color from the default gray.

### `styled-components`
```
import styled from 'styled-components/native'

const Input = styled.TextInput.attrs({
  placeholderTextColor: 'white'
})`
...
`
```

### React Native
```
import { TextInput } from 'react-native'

const Form = props => <TextInput placeholderTextColor='white' />
```
