### ISSUE TITLE
webpack config

### ISSUE THREAD

**Issue by chinaxiaoyy** [necolas/react-native-web#564]
I have two js file : abc.js and abc.web.js ,then i import abc from 'abc.js' , how to do that webpack get abc.web.js but not abc.js???

**Comment by chinaxiaoyy** [comment]
What do I need to do in webpack.config.js?

**Comment by timche** [comment]
https://webpack.js.org/configuration/resolve/#resolve-extensions

Example:

```js
extensions: [".web.js", ".js", ".json"]
```

**Comment by chinaxiaoyy** [comment]
thankyou so much
