### ISSUE TITLE
Elements library?

### ISSUE THREAD

**Issue by piranna** [necolas/react-native-web#568]
Is there any `react-native-web` compatible elements library that can be used? How to know if a ReactNative element is compatible with `react-native-web`? Could it be added a list of known ones?

**Comment by necolas** [comment]
You can try it out or ask the author of the component library

**Comment by piranna** [comment]
Couldn't it be added to the readme a list of already tested ones?

**Comment by dalcib** [comment]
@piranna, you can try [react-native-material-ui](https://github.com/xotahal/react-native-material-ui).
There is an example here:  https://github.com/dalcib/react-native-material-ui-web-app

**Comment by piranna** [comment]
@dalcib looks realy nice, thank you! :-D Do you know if `react-native-material-ui` offer support for `react-native-web`? Looking so good, at least they could add a statement about that... Do you think if it makes sense I ask them about it?

**Comment by dalcib** [comment]
It'd be good.
I didn't have any problem in approving this PR https://github.com/xotahal/react-native-material-ui/pull/169 that enabled better compatibility with RNW.

**Comment by piranna** [comment]
Ok, forgot I opened an [issue](https://github.com/xotahal/react-native-material-ui/issues/176) asking for that one month ago :-P
