### ISSUE TITLE
Add ListView to UI Explorer

### ISSUE THREAD

**Issue by piranna** [necolas/react-native-web#569]
`ListView` is not available on UI Explorer nor there's references, making it mostly a "hidden" component. I think there are other ones in a similar situation.

**Comment by necolas** [comment]
That's intentional as `ListView` is going away in React Native and was never properly implemented here

**Comment by piranna** [comment]
What's the newer alternative to ListView?

**Comment by necolas** [comment]
In React Native, it's `FlatList` etc
