### ISSUE TITLE
Add FAQ to README

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#57]
Move section of media queries to FAQs, and answer questions:

* what is the project aim?
* how does it relate to React Native?
* what are the benefits of this over something like Radium or CSS modules?
* has this been validated in a real app ;)
* what is the roadmap?

**Comment by mvayngrib** [comment]
amazing work guys! 

could you comment on the difference between [react-native-web](https://github.com/necolas/react-native-web) and [react-web](https://github.com/taobaofed/react-web). Are the approaches used different?
