### ISSUE TITLE
"react": "16.0.0-alpha.12"

### ISSUE THREAD

**Issue by sm2017** [necolas/react-native-web#570]
Please don't close issue , I really need your help

`react-native init` currently install `react@16.0.0-alpha.12` and `react-dom@15.6` is not compatible 

```
Module not found: Error: Can't resolve 'react-dom/lib/EventPluginHub' 
Module not found: Error: Can't resolve 'react-dom/lib/ResponderEventPlugin' 
Module not found: Error: Can't resolve 'react-dom/lib/ResponderTouchHistoryStore' 
```

I try install `react-dom@16.0.0-alpha.12` but same issue

**Comment by necolas** [comment]
You can't use React 16 yet. But once the next alpha is published I'll be able to support 16

**Comment by sm2017** [comment]
@necolas can I have you're discord username (Or any other way to chat with you)

**Comment by scf4** [comment]
@necolas I'm having this problem too. Is react 16 still not supported? It's in rc stage now.

**Comment by JayHuang** [comment]
would also like to know if there's updated support for this
