### ISSUE TITLE
scrollView set scrollEnable to false,but also can scroll

### ISSUE THREAD

**Issue by chinaxiaoyy** [necolas/react-native-web#573]
same as title, i set the scrollEnable to false,but i also can scroll it.

![wechatimg173](https://user-images.githubusercontent.com/20460743/28519609-d7ffefea-709e-11e7-9c83-6a01e041004c.jpeg)
![wechatimg6757](https://user-images.githubusercontent.com/20460743/28519608-d7d701d4-709e-11e7-98dd-30a2f5aecd8d.jpeg)
who can help me , thanks so much

**Comment by chinaxiaoyy** [comment]
i use chrome

**Comment by damiaozi** [comment]
横向的?加个Q不？我也在研究这个，一起学习呀

**Comment by necolas** [comment]
Please include a link to a demo, the version of the library, and what browser version and OS

**Comment by necolas** [comment]
I can't reproduce this in the docs with the latest version (for example, change this component - https://github.com/necolas/react-native-web/blob/master/docs/storybook/1-components/ScrollView/examples/Horizontal.js).
