### ISSUE TITLE
resolvedStyle.flexBasis = '0%' or  resolvedStyle.flexBasis = 'auto'

### ISSUE THREAD

**Issue by damiaozi** [necolas/react-native-web#574]
loaction：..\react-native-web\src\apis\StyleSheet\createReactDOMStyle.js
on 172line

```
 case 'flex': {
        if (value > 0) {
          resolvedStyle.flexGrow = value;
          resolvedStyle.flexShrink = 1;
          resolvedStyle.flexBasis = 'auto';   //172line
        }
```
1、
  resolvedStyle.flexBasis = '0%';
I run web on iphone,but The layout of many interfaces are compressed on my  project。
on chrome and on android phone are no problem。 

2、
then I change react-native-web's  source code,
become resolvedStyle.flexBasis = 'auto';
I run web on iphone,The layout of many interfaces are Become very normal.
the same as on android phone。
but，The interface jump is very slow。After the button is clicked, it will take a long time to respond.
Is this a performance problem or a compatibility issue？
Or what's the other problem?

3、I've changed react-native-web's source code, and I'm not going to have a problem？
resolvedStyle.flexBasis = '0%' or  resolvedStyle.flexBasis = 'auto'
Will it affect the rest of the world?

**Comment by necolas** [comment]
When you report an issue, please include a link to a demo of the problem. You're asked to do so in the issue template, and it makes it a lot easier to get help

**Comment by damiaozi** [comment]
@necolas demo [https://github.com/agrcrobles/react-native-web-boilerplate](https://github.com/agrcrobles/react-native-web-boilerplate)  have the same issue。
update it's react-native-web to Latest version(0.0.113) then，Its bottom navigation menu layout is missing

**Comment by necolas** [comment]
What browser version? (This is easier when you provide the information asked in the issue template)

**Comment by damiaozi** [comment]
@necolas IE11   and  all iphone

**Comment by damiaozi** [comment]
It is the same issue on my project.
you can open [here](https://y.fjsgo.com/mobile/) to see.
I use  react-native-web is Latest version(0.0.113)
then，use android phone or chrome is No problem。
but use all iPhone and IE11 open on web，the bottom navigation menu layout is missing,
and The layout of many interfaces are compressed on my project。open [here](https://y.fjsgo.com/mobile/) to see.
if I change     
```
 .rn-1ro0kt6 {
    flex-basis:0%;
}
```
to
```
 .rn-1ro0kt6 {
    flex-basis:auto;
}
```

then all  interfaces are become ok on iphone and IE
then，I don't know what can I do to let   flex-basis:auto？

**Comment by necolas** [comment]
Sorry, I don't have time to try and debug you app. Small test cases are the best way to get help quickly, as it saves me a lot of work trying to figure out how to even reproduce a problem

**Comment by damiaozi** [comment]
I've solved my problem。
It‘s  react-navigation bug。
but I don't know why change resolvedStyle.flexBasis value.web use iphone will become slowly

**Comment by necolas** [comment]
ok, thank you. i'll be curious to know if you find out more

**Comment by f3ist** [comment]
@necolas I recently upgraded react-native-web to the newest version (0.0.119) and have determined that version 0.0.104 breaks flex-box features in Safari 10.1.2. Sorry my web debug skills aren't as good, otherwise I would dig deeper. I'm using react and react-dom 15.6.1. Everything works when downgrading to 0.0.103.

**Comment by necolas** [comment]
Do you have an example of code that reproduces the problem

**Comment by f3ist** [comment]
@necolas I modified the boilerplate repo to reproduce it. It's using 0.0.119 and the header line items are visible in chrome, but not in Safari.

https://github.com/f3ist/react-native-web-boilerplate

**Comment by necolas** [comment]
Please can you reproduce the issue with a simple example hosted on glitch: glitch.com/edit/#!/rnw

**Comment by billouboq** [comment]
@necolas  Hi, We are having issues with the default flex basis on IE 11, it is 0% and should be 'auto', is it possible to change the default one for IE specificaly without changing every View in my application (some can't be changed unfortunatly...)

**Comment by necolas** [comment]
This issue is over a year old. If there is something you want to suggest please create a new one
