### ISSUE TITLE
Recommended approach for big lists?

### ISSUE THREAD

**Issue by MovingGifts** [necolas/react-native-web#575]
I know many people use RNW and I've also have been following implementation of lists. When I have things like comments for example, in React Native, I load 20 at a time of 1000 comments with a `FlatList`, and load 20 more as I scroll to the end of the list. But since these lists aren't in RNW yet, what is the recommended approach to handle lists for the time being?

**Comment by ericwooley** [comment]
In some cases code won't be 100% shareable, so I would recommend making a list.native.js and a list.web.js file and using something like 

https://github.com/bvaughn/react-virtualized

In cases like this. To maximize code reuse, abstract both of them so they have the same api.

**Comment by necolas** [comment]
^ is a good idea. There's some work going on to support the RN lists, but I'm not working on it as it's not something we need at Twitter yet

**Comment by MovingGifts** [comment]
Thank you both for the info :)

**Comment by damiaozi** [comment]
@ericwooley how to use react-virtualized on web？
