### ISSUE TITLE
ios 下listview 样式style及性能bug

### ISSUE THREAD

**Issue by wollld** [necolas/react-native-web#576]
[see code ](https://github.com/wollld/mydoc/blob/master/test/ioslistviewstylebug)

**Comment by wollld** [comment]
version
 react-native-web 0.0.113
"react": "^16.0.0-alpha.12",
    "react-dom": "^15.6.1",

**Comment by wollld** [comment]
true react: "react": "^15.6.1",

**Comment by damiaozi** [comment]
加个好友不，好不容易找到一个中国人用rnw

**Comment by wollld** [comment]
350856733
