### ISSUE TITLE
Investigate using Cosmos / React Component Playground for gh-pages

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#58]
The CodePen setup is cool for building example UI's. But showcasing the components with editable props and state would be a clearer way for people to explore what the React Native components offer. These projects look like a good starting point.
 
https://github.com/skidding/cosmos
https://github.com/skidding/react-component-playground

**Comment by necolas** [comment]
Dropping this idea

**Comment by MoOx** [comment]
Hi @necolas. This is not directly relevant, but if you plan to make an online documentation, I am currently working on a "static" website generator using React https://github.com/MoOx/statinamic
(well, as you might expect, it does not produce static website ^^).

**Comment by necolas** [comment]
thanks for letting me know
