### ISSUE TITLE
How to use standard react components successfully?

### ISSUE THREAD

**Issue by Tredis** [necolas/react-native-web#580]
I assumed I could use standard react components in web specific sections of my react-native-web app, but nearly all standard react components do not appear on web as expected. Most come out with funky style, alignment issues, and incomplete visuals. I have tried using straight html in the web specific sections, and it works great and as expected.
Unfortunately, many of the more complex web components use jQuery, bootstrap, etc. and so I look to ready built react components for my web needs, but there seems to be an issue going through react-native-web.
Is there a way to tell RNW to use react instead of RN for certain components?

Thanks!

**Comment by necolas** [comment]
I don't understand what you're asking. RNW uses ReactDOM. If you're asking how to use RNW to style components built with ReactDOM, you should read the guides: https://github.com/necolas/react-native-web/blob/master/docs/guides/advanced.md

**Comment by Tredis** [comment]
Thanks for the quick reply.
No, I am not asking how to style components built with ReactDOM.
I only want to use standard react components with default styling.

As an example. I am trying to use react-datetime-calendar. This is what I did, does it look right?:

```import DateTimePicker from "react-datetime-calendar"
import { createDOMElement } from 'react-native';
const DateTime = (props) => createDOMElement(DateTimePicker, props);
...
<DateTime theme='window'/>```

It does not look right in the browser, and I don't know why. Any help would be appreciated.

**Comment by Tredis** [comment]
In fact, it looks the same whether I use createDOMElement or not. 
Using <DateTimePicker theme='window'/> results in the exact same issues.

**Comment by Tredis** [comment]
Thisa is what it looks like:
<img width="360" alt="screen shot 2017-07-28 at 7 37 48 pm" src="https://user-images.githubusercontent.com/22584383/28739885-d596704a-73cc-11e7-96d2-7f9a315b4fcc.png">

This is how it should look:
<img width="520" alt="screen shot 2017-07-28 at 7 40 06 pm" src="https://user-images.githubusercontent.com/22584383/28739898-e6c94928-73cc-11e7-808e-cb95776883a0.png">
