### ISSUE TITLE
TouchableOpacity intermittently fails to call onPress handler

### ISSUE THREAD

**Issue by sam-10e** [necolas/react-native-web#585]
Thanks for all the great work! We're using this project extensively and it has been a pleasure to work with.

**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
When a TouchableOpacity is used to toggle a change that changes the position of the `TouchableOpacity` view, subsequent clicks may fail to trigger the `onPress` handler when using a Mac touchpad. 

This bug is not reproducible with an external mouse, or when a "tap" on the touchpad is used.

**If the current behavior is a bug, please provide the steps to reproduce.**

[https://codepen.io/sam-10e/pen/RZajrV?editors=0010](https://codepen.io/sam-10e/pen/RZajrV?editors=0010)

1. Open the demo, click the black box using a Mac touchpad (make sure to click and not tap)
2. The box should move to a new position, click again.
3. Repeat until the box fails to move. It will still change opacity.
4. Click again and the box will move.

**What is the expected behavior?**
The TouchableHighlight should consistently detect presses, regardless of input type (mouse, touchpad, etc).

**Environment (include versions). Did this work in previous versions?**

* OS: OSX Version 10.12.6 (16G29)
* Device: Macbook Pro
* Browser: Chrome, Firefox (latest)
* React Native for Web (version): 0.0.114+ (may also happen on older versions)
* React (version):

** Additional Notes **

This _only_ happens with TouchableOpacity and _not_ TouchableHighlight. It appears that when `touchableGetHighlightDelayMS()` returns 0, the `this._handleDelay` method is called immediately, and it may complete before the callback passed to `UIManager.measure` in  `this._remeasureMetricsOnActivation` has been executed. Thus the check to determine if the action occurred within the bounds of the TouchableOpacity component fails, and it does not call the `onPress` handler.

**Comment by necolas** [comment]
Fixed in 4fa6f77d2542cb7c582a36918ef7fc38207a8357
