### ISSUE TITLE
How to use react navigation in react-native-web

### ISSUE THREAD

**Issue by ashanjayasundara** [necolas/react-native-web#588]
**How to use react navigation in react-native-web**

react navigation does not work in react-native-web.
Initially there were many compilation issues i have fixed it but  page navigation does not work

**Comment by necolas** [comment]
That project needs to fix its web support
https://github.com/react-community/react-navigation/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20react-native-web

**Comment by damiaozi** [comment]
No problem，navigation ，It's a good run
