### ISSUE TITLE
Add styled-components usage in the docs?

### ISSUE THREAD

**Issue by leggomuhgreggo** [necolas/react-native-web#591]
Got a little turned around when trying to use RNW with styled-components, on account of styled-component's implicit import of primitives, and thought it might be helpful to add a clarifying section somewhere in the docs. If you don't think it's too far-field, let me know which doc file you think'd be best suited for a PR.

Thanks

**Comment by necolas** [comment]
Using styled-components on top of RNW is something I think that project could document, but it is going to be slow (see the benchmark results). Thanks

**Comment by MiLeung** [comment]
I'm trying to use styled-components with react-native-web. I've installed `react-art`, `react-native-web`, and `styled-components`. but I'm not sure what to do next.
