### ISSUE TITLE
Is it possible to go fullscreen on mobile browsers (hide address/navigation)?

### ISSUE THREAD

**Issue by emef** [necolas/react-native-web#592]
I've searched the docs and code looking for a reference to enabling a 'fullscreen' mode. Is there a way to do this? There are a number of explanations of the hacks required to do this around the web that don't work out of the box with react-native-web (that I've found). Any ideas?

**Comment by necolas** [comment]
You'll need to use meta tags and manifest.json file. Google for "web app capable" and "progressive web app"

**Comment by emef** [comment]
I see, thanks for the tip. Seems like safari doesn't support a lot of this PWA stuff ,and the workaround to hide the address bar is to mess with scrollTo... eh, maybe not worth it. Thanks again for the quick reply, really quite impressed with this library... pretty novel experience to have things look good on all sorts of devices without dicking around with a million css rules and fallbacks

**Comment by necolas** [comment]
:)
