### ISSUE TITLE
Is there a recommended way to do smooth scrolling?

### ISSUE THREAD

**Issue by dsernst** [necolas/react-native-web#593]
@necolas: Do you have a recommended way to do animated smooth scrolling?

**Comment by mikeaustin** [comment]
I've been using smoothscroll. Nothing fancy, but it works well. You can pass a number as the parameter also, not only an element. This is not react-native-web specific, it should work anywhere.

https://www.npmjs.com/package/smoothscroll

**Comment by mikeaustin** [comment]
Just curious if this could be closed? I'm not an admin or anything, but fewer open issues is always better. Do you know how React Native deals with smooth scrolling?

**Comment by necolas** [comment]
I have a local branch to add "native" web smooth scrolling in supporting browsers. Hoping to land it soon

**Comment by mikeaustin** [comment]
Nice! Smooth scrolling is def a better user experience, since you can literally see what's happening. Just curious, what's a similar experience in React Native? Maybe tapping a Table of Contents item in a document app?

**Comment by flip-it** [comment]
`ScrollableView`'s has the default option `animated: true` for `scrollTo()`, but it doesn't do anything. Is this because it's also waiting for the smooth scrolling to be implemented?
