### ISSUE TITLE
normalizeTouchEvent() and normalizeMouseEvent() crashes on events created by React Test Utils

### ISSUE THREAD

**Issue by kim-10e** [necolas/react-native-web#598]
*bug*

The two functions normalizeTouchEvent() and normalizeMouseEvent() in `module/normalizeNativeEvent/index.js` assume the native event object contains the following three functions:

- preventDefault
- stopImmediatePropagation
- stopPropagation

However, events simulated by React Test Util (e.g. via Enzyme) do not contain these three functions, causing a crash when React Native Web tries to normalize (simulated) native events.

Adding a simple check before attempting to bind said three properties fixes the problem and enables click and touch events to be simulated when testing React components using Enzyme and JSDOM.

See https://github.com/necolas/react-native-web/pull/597

* React Native for Web (version): 0.0.119
* React (version): 15.4.2

**Comment by necolas** [comment]
Moving discussion to #597
