### ISSUE TITLE
Fire 'onLayout' when elements are resized

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#60]
Polymer has a DOM strategy for something very similar: https://github.com/PolymerElements/iron-resizable-behavior. This should allow styling comparable to 'element queries' with the addition of adjustments based on screen position.

**Comment by calebhskim** [comment]
I am trying to use `onLayout` and it seems to only get fired once when the View is rendered. I have something like this:
```
function handleLayout(event) {
    const { width } = event;
    console.log(width);
}

class Foo extends Component {
    render() {
        return(
            <View onLayout={ handleLayout }>
                Blah ...
             </View>
        );
     }
}
```
I am trying to get around media queries. I have also tried using `Dimension.get('window').width` but that seems to return the width of the previous screen size. I am resizing the window using Chrome's developer tools and toggling it's mobile inspector. I am wondering if `Dimension.set` being [debounced 50ms](https://github.com/necolas/react-native-web/blob/945fff00159f521becdb499439e38538889313cd/src/apis/Dimensions/index.js#L41) is causing it to return the previous width. My current workaround is to add an event listener to window for `resize`:
```
window.addEventListener('resize', () => { this.updateView() }, true);
```
Any help would be greatly appreciated!

**Comment by souporserious** [comment]
How would you feel about using [React Measure](https://github.com/souporserious/react-measure) underneath the hood for `onLayout`? It would only be used  if the `onLayout` prop was present to avoid unnecessary listeners. I could put together a PR if this sounds like something you would be interested in @necolas :) please let me know.

**Comment by necolas** [comment]
Yeah I'm interested in seeing if something performant can be done with the resize observer. Thanks for taking a look

**Comment by RangerMauve** [comment]
It doesn't look like onLayout is firing on window resize in `0.0.80`, was the recent commit not released yet?

**Comment by RangerMauve** [comment]
Whoops! nevermind, got it working

**Comment by txs** [comment]
@RangerMauve  How do you got it working? with React Measure? I have this issue too!

**Comment by RangerMauve** [comment]
@Txs I was putting the `onLayout` listener on my custom component instead of on a View component.

**Comment by souporserious** [comment]
Sorry, I've been meaning to submit a PR for this, just been swamped lately. I don't think it should use React Measure, but the [Resize Observer Polyfill](https://github.com/que-etc/resize-observer-polyfill). Should be a simple addition that way.

**Comment by txs** [comment]
The React Measure is better not only solving the width issue but also the height issue!

**Comment by necolas** [comment]
@souporserious are you still planning to try this out?

**Comment by souporserious** [comment]
Yeah, sorry I've been swamped with work lately. I can help out by commenting on a PR, but I won't be able to try any code out for at least another week.
