### ISSUE TITLE
Usage Question: Rendering into constrained <div>...</div> element

### ISSUE THREAD

**Issue by DaKaZ** [necolas/react-native-web#600]
Thank you @necolas for your active work and support of this project!  I have a usage question: I spent a day in the docs and closed issues and I haven't found the answer.  

For business reasons, I need to embed the output of react-native-web (which we have working well) into a div element on an existing app.  The app is a Rails app and we have wired up react_on_rails and our react-native app is running EXCEPT that it is not rendering inside the DIV.  

I have tried every combination of CSS layout/styling I can think of but I cannot get app to render inside the div.  Eventually I will make this responsive, but for now I am just trying to render into a fixed size div (900x700).  Is there a trick to doing this or is this behavior known and expected?

Note: it does work if we use an iFrame however the customer does not want an iFrame approach, so... trying to figure this out.

Thanks for any help / advice!

* OS: MacOS/Ubuntu
* Device: N/A
* Browser: Chrome/Firefox
* React Native for Web (version): 0.112
* React (version): 15.6.1

--Mike

**Comment by necolas** [comment]
Render into the target div and give it position relative
https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#client-side-rendering
