### ISSUE TITLE
StyleSheet: `sticky` not considered valid value for `position`

### ISSUE THREAD

**Issue by paularmstrong** [necolas/react-native-web#604]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using `position: 'sticky'`, the following warning is thrown to the dev console:

```
Warning: Failed prop type: Invalid prop `position` of value `sticky` supplied to `View`, expected one of ["absolute","fixed","relative","static"].
```

Support is spotty, but coming along. Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/position

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. Use `position: 'sticky'` in a StyleSheet
2. Load application

**What is the expected behavior?**
No warning

**Environment (include versions). Did this work in previous versions?**

* OS: All
* Device: All
* Browser: All
* React Native for Web (version): 0.0.119
* React (version): 15.6.1

**Comment by RangerMauve** [comment]
Hi, since this library is trying to emulate the APIs in React-Native, it doesn't support sticky since React-Native does not either. According to the React-Native docs, they only support [`absolute` and `relative](https://facebook.github.io/react-native/docs/layout-props.html#position) for `position`

**Comment by paularmstrong** [comment]
I understand that, but RNW does have "web-only" options in many of its APIs and components as well.

**Comment by necolas** [comment]
Thanks. Fixed in master
