### ISSUE TITLE
StyleSheet: `borderSpacing` and `borderCollapse` not considered valid style props

### ISSUE THREAD

**Issue by paularmstrong** [necolas/react-native-web#605]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
All(?) HTML table-specific CSS properties are considered invalid. Specifically seeing `borderSpacing` and `borderCollapse` throwing warnings:

```
Warning: "borderSpacing" is not a valid style property.
Warning: "borderCollapse" is not a valid style property.
```

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar**

https://glitch.com/edit/#!/sponge-albatross

**What is the expected behavior?**

No warnings on valid CSS properties

**Environment (include versions). Did this work in previous versions?**

* OS: All
* Device: All
* Browser: All
* React Native for Web (version): 0.0.119
* React (version): 15.6.1

**Comment by necolas** [comment]
I'll add these styles, but you shouldn't expect all CSS properties to be supported as React Native implements a _subset_ of CSS.
