### ISSUE TITLE
ReferenceError: Unknown plugin "transform-react-remove-prop-types"

### ISSUE THREAD

**Issue by jasonfma** [necolas/react-native-web#607]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error on launch 

1. Install latest `react-native-web`
2. Run webpack

`ReferenceError: Unknown plugin "transform-react-remove-prop-types"`

**What is the expected behavior?**
Web app starts

**Environment (include versions). Did this work in previous versions?**
Worked in previous versions

* OS: macOS 
* Device: 
* Browser: Chrome
* React Native for Web (version): 0.0.119
* React (version): 15.4.2

**Comment by jasonfma** [comment]
Fixed after installing `babel-plugin-transform-react-remove-prop-types`

Should we add this to the peerDeps?

**Comment by necolas** [comment]
You don't need babel use react-native-web. Sounds like you have Babel trying to build from source code and using the project's development babelrc

**Comment by jasonfma** [comment]
Interesting. This was working with `0.0.89` but upgrading to `0.0.119` with no other changes causes this error. I'll dig into our babel configs.

**Comment by jasonfma** [comment]
Oh yep ok thanks. I added an exclude for `react-native-web` in my webpack config and that solved the issue. Thanks!
