### ISSUE TITLE
ScrollView can`t run "onScrollBeginDrag"

### ISSUE THREAD

**Issue by shijinwu** [necolas/react-native-web#611]
ScrollView can`t run "onScrollBeginDrag"  version:0.0.120

**Comment by necolas** [comment]
`onScrollBeginDrag` is not part of the RN `ScrollView` interface anymore https://facebook.github.io/react-native/docs/scrollview.html

**Comment by acamari** [comment]
But as 8 aug 2018 it still shows in ScrollView docs: https://facebook.github.io/react-native/docs/scrollview#onscrollbegindrag 

any workaround for this?

thanks
