### ISSUE TITLE
TouchableHighlight: underlayColor press bug

### ISSUE THREAD

**Issue by joncursi** [necolas/react-native-web#618]
I noticed that when you click on a `TouchableHighlight`, it will turn black as expected, but when you release the click, the element *stays black*, which is not desired. Only during the duration of the press should the element receive the `underlayColor`

**Comment by necolas** [comment]
Please provide the information requested in the issue template

**Comment by joncursi** [comment]
```jsx
import { TouchableHighlight } from 'react-native-web';

...

<TouchableHighlight
  onPress={() => {}}
>
  {...}
</TouchableHighlight>
```

* Bug
* Current behavior described above
* Repro code provided above
* OS: macOS
* Device: MacBook Pro 2017
* Browser: Chrome
* React Native for Web (version): `0.0.120`
* React (version): `15.6.1`

**Comment by necolas** [comment]
Do you know why it isn't reproducible in the RNW storybook?

**Comment by joncursi** [comment]
I'm not sure! This may in fact be an issue local to me. I'm going to close for now, I'll re-open if this props up again. Thanks!
