### ISSUE TITLE
Equivalent of react-native-cli

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#62]
https://facebook.github.io/react-native/docs/getting-started.html#quick-start

React Native has relatively simpler setup compared to contemporary React-based web apps. At the expense of absolute customization comes better ecosystem consistency and fewer barriers to entry. This is something we're intent of improving internally at Twitter too, because we want someone to be able to start building their web app ASAP, rather than doing setup work and making divergent choices.

A web equivalent might include:

* react-native-web
* Babel 6 (and initial config)
* Webpack + middleware (and initial config – simpler without css loaders)
* ESLint
* react-router + history
* express

Probably a test setup for client and server code? I wrote a bundled package for client-side testing at Twitter for this. One dependency + ~5 lines of code across 2 files and you get: karma, mocha (we go with the tdd ui), sinon, all browsers launchers (inc. browserstack), phantom, jsdom, rerunning of changed tests, and the ability to bundle subsets of your tests. Don't think we want to get into integration testing though.

**Comment by mattapperson** [comment]
Hapi > express IMHO

**Comment by genxium** [comment]
Hope I understand this issue correctly. I'm working on a small project which tries to provide scripts for creating a mixed react-native + react-native-web project [here](https://github.com/genxium/ReactNativeStarterPackage/tree/master/create_project_by_name) and comments are welcome :)

**Comment by RangerMauve** [comment]
Looking at [this tutorial](https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/) it seems that the things needed to do that are different from react-web would be to install React/React-Dom, Webpack, and a dev server. A react-native-web CLI would be useful if it included those things as dependencies and provided a `react-native-web run-web` command, or maybe some sort of wrapper that would relay android/ios react-native commands back to the original, while treating web related ones differently.

**Comment by RangerMauve** [comment]
Maybe [create-react-app](https://github.com/facebookincubator/create-react-app/pull/407) would be a good place to start because they're working on having react-native-web be a first class citizen.

**Comment by necolas** [comment]
I think that's a good idea! Going to close this. Thanks
