### ISSUE TITLE
how can i add custom fonts 

### ISSUE THREAD

**Issue by 2248157705** [necolas/react-native-web#620]
how can i add custom fonts  for example iconfont 
http://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.13&helptype=code

**Comment by necolas** [comment]
Import them in the HTML shell of your app or lazy load them from js

**Comment by 2248157705** [comment]
thanks!

**Comment by PrinzAndreVonLandmann** [comment]
can someone maybe provide some example? because i really dint get it where i have to put what to make it work
sorry for the maybe dumb request but i´ve never worked with HTML, fontface and all this stuff before

**Comment by xiswar** [comment]
Hi I had the same issue. Here one solution:

1. Get a link for your font. For example from Google Fonts:
`<link href="https://fonts.googleapis.com/css?family=Your First Font | Your Second Font">`
2. Add this link into the `/public/index.htlml` file. Insert it in the head tag.
`<head> some where here </head>`
3. In your styles use:
`
    fontFamily: "Your First Font"
`
