### ISSUE TITLE
Add Keyboard API

### ISSUE THREAD

**Issue by joncursi** [necolas/react-native-web#621]
** Feature Request **

Most react native apps make use of the built-in `Keyboard` API to do things like dismissing the Keyboard. To allow native code to run on the web, it would be great if the Keyboard API were supported on RNW. Even if it is just stubbed out with `noop` functions, that would be valuable to prevent platform-specific code.

**Comment by remon-georgy** [comment]
Yes please! I was trying the very simple [react-native-autosuggest](https://github.com/silesky/react-native-autosuggest), when it failed becuase of lack of `Keyboard` API (below). Even a `noop` stuch as @joncursi suggested would be great.

```
TypeError: Cannot read property 'addListener' of undefined
AutoSuggest.componentDidMount
node_modules/react-native-autosuggest/src/AutoSuggest.js:92
  89 | }
  90 | componentDidMount () {
  91 |   // when user hits the return button, clear the terms
> 92 |   Keyboard.addListener('keyboardDidHide', () => this.clearTerms())
  93 | }
  94 | 
  95 | getAndSetWidth () {
```

**Comment by necolas** [comment]
Yeah, sounds good. I can review a patch

**Comment by VinceBT** [comment]
#610 Got the same answer

**Comment by joncursi** [comment]
Looks like this can be closed now! https://github.com/necolas/react-native-web/commit/b23a4f55dc1571b1e5e99c7d84aadd034df5177b 🎉
