### ISSUE TITLE
StyleSheet: map 'System' font-family to web equivalent

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#622]
**Do you want to request a *feature* or report a *bug*?**

Feature/bug

**What is the current behavior?**

"System" is used as a `font-family` in RN apps but doesn't really work for web apps.

**What is the expected behavior?**

"System" should use the OS system font, the web equivalent is something like this:

```
-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Ubuntu,Helvetica Neue,sans-serif
```

**Environment (include versions). Did this work in previous versions?**

* OS: all
* Device: all
* Browser: all
* React Native for Web (version): all
* React (version): all

**Comment by SuhairZain** [comment]
@necolas Hi, I'm sorry if I'm getting this wrong, but I thought this issue might be related to what I'm having. It's more of a query than a problem, so I didn't want to create a new issue.

We're trying to migrate an RN app to also work on web. For a certain part, we need to code the UI using `div` to set the `innerHtml` directly. However, inside this `div`, the `font-family` doesn't get set as the rest of the app. I tried setting the `font-family` to `System`, but it doesn't seem to work. Is this particular case an issue or am I missing something?

**Comment by SuhairZain** [comment]
I did use the `dangerouslySetInnerHTML` prop, it was a mistake while I typed the comment. And you're right, putting the `div` inside a `Text` did the trick. Thanks a lot. :)
