### ISSUE TITLE
delete 'unknown props'  on view

### ISSUE THREAD

**Issue by aizigao** [necolas/react-native-web#623]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
when I use props like this 
```jsx
<View {...this.props}/>
```
then It will trigger some warning like 
![](https://user-images.githubusercontent.com/14126445/29918397-f62674ca-8e77-11e7-8c97-57c059306ed8.png)

so maybe  View should delete not support props

**Comment by necolas** [comment]
don't pass down props that View doesn't support
