### ISSUE TITLE
KeyboardAvoidingView is undefined

### ISSUE THREAD

**Issue by CoreyAR** [necolas/react-native-web#628]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
KeyboardAvoidingView is undefined
**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. import {KeyboardAvoidingView} from 'react-native'
2. Element is undefined

[Demo](https://glitch.com/edit/#!/holistic-slicer)

**What is the expected behavior?**
[KeyboardAvoidingView](https://github.com/necolas/react-native-web/blob/master/src/components/KeyboardAvoidingView/index.js) should be defined 

**Environment (include versions). Did this work in previous versions?**
Not sure.

* OS: Web
* Device: All
* Browser: All
* React Native for Web (version): ^0.0.124
* React (version): 16.0.0-alpha.6

**Comment by necolas** [comment]
You example is using `0.0.119`, which doesn't include `KeyboardAvoidingView`. And React 16 is not yet supported either

**Comment by CoreyAR** [comment]
Ok, Thanks for the quick reply. I am not very familiar with glitch and just remixed the link provided.

**Comment by CoreyAR** [comment]
I believe this still may be an issue. I am creating a storybook in my fork for KeyboardAvoidingView to start debugging and am also seeing that it is undefined.
