### ISSUE TITLE
color.indexOf is not a function

### ISSUE THREAD

**Issue by VinceBT** [necolas/react-native-web#630]
When you use [this quite famous package](https://www.npmjs.com/package/color) for colors, [this line](https://github.com/necolas/react-native-web/blob/master/src/propTypes/ColorPropType.js#L39) throws this error ```color.indexOf is not a function``` if you don't specify to output the color as a string, which do not fire any error in mobile React Native.
One quick way to fix this is to replace the line by 
```js
if (color === 'currentcolor' || color === 'inherit' || (typeof color.indexOf === 'function' && color.indexOf('var(') === 0)) {
```

**Comment by necolas** [comment]
What is React Native doing with a non-string/number/null/undefined color value? Just dropping it on the floor?

**Comment by VinceBT** [comment]
I know it seems weird but when RN gets a color from anywhere , string or object, it still calls it's .toString() method, and it works in mobile RN.

In the way I described it, calling toString() on the object gives the prop a last chance to give a meaningful color before throwing an error.
