### ISSUE TITLE
Stop putting children propType in TouchableWithoutFeedback

### ISSUE THREAD

**Issue by VinceBT** [necolas/react-native-web#634]
Facebook [stopped putting children in propTypes](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L50) for some time now, I have errors firing for nothing because of [this check](https://github.com/necolas/react-native-web/blob/641c8c47e0f115c8b4a655a1ad0b093af23b7f97/src/components/Touchable/TouchableWithoutFeedback.js#L47) when TouchableOpacity has multiple children because it inherits TouchableWithoutFeedback propTypes which forces it to have only 1 child

I think we could delete it, since Facebook did the same.

EDIT: added some clarifications

**Comment by necolas** [comment]
I don't understand. What errors?

**Comment by VinceBT** [comment]
TouchableWithoutFeeback takes only 1 child and TouchableOpacity can take several since it's just an Animated.View. But, since [TouchableOpacity inherits TouchableWithoutFeedback](https://github.com/necolas/react-native-web/blob/641c8c47e0f115c8b4a655a1ad0b093af23b7f97/src/components/Touchable/TouchableOpacity.js#L58), it's not possible to put several children inside a TouchableOpacity in RNWeb, whereas in plain React Native there is no problem because they've entirely [removed the propType check](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L50)
