### ISSUE TITLE
UnimplementedView should have a proper style propTypes check

### ISSUE THREAD

**Issue by VinceBT** [necolas/react-native-web#635]
[This line](https://github.com/necolas/react-native-web/blob/0d8aa24ff3b70320c26ab482b52882eb51145993/src/components/UnimplementedView/index.js#L23) generates issues when you put array styles for example, we could either use PropTypes.any, delete the check, use ViewStylePropTypes or even put the ViewPropTypes as a base.

**Comment by necolas** [comment]
Ok, not sure this really matters though, as it's unlikely you want to render an unimplemented component

**Comment by VinceBT** [comment]
It's only for the cases where you have a View that is unimplemented in the web version but implemented on mobile and the props don't check because it casts the component to UninmplementedView.
For example Animated.ScrollView

**Comment by necolas** [comment]
`Animated.ScrollView` is supported https://github.com/necolas/react-native-web/blob/master/src/apis/Animated/index.js#L24

**Comment by VinceBT** [comment]
I finally found out what's happened haha, I had to search so deep for that.

Indeed Animated.ScrollView is supported sorry, the problem came from ScrollViews that have a refreshControl prop, I wondered why the problem came only from the ScrollViews

Since ScrollViews [copy the style attribute to the refreshControl](https://github.com/necolas/react-native-web/blob/90724b2cef4eb3cf50526084a5c339e59bb3693b/src/components/ScrollView/index.js#L202) when a refreshControl is passed, and RefreshControl is not implemented, then the style prop was reported onto the UnimplementedView that was rendered and then threw an error since the propType was too restrictive.

Now it should be ok with your fix :)
