### ISSUE TITLE
can I initial styles to <Text/>

### ISSUE THREAD

**Issue by aizigao** [necolas/react-native-web#640]
I updated rn-web from 0.0.120 to 0.0.125, and I see in [0.0.122](https://github.com/necolas/react-native-web/commit/5ed2127175c710e972c4e28ae84e9f3e3c105f77) version has add initial fontSize to Text, but it case my App's styles works wrong, because I had setting body fontSize to initial  fontSize of Text . but in new version can't use it . So, has some code to setting initial styles? 

https://github.com/necolas/react-native-web/blob/master/src/components/Text/index.js#L98

**Comment by necolas** [comment]
You should follow the advice here https://facebook.github.io/react-native/docs/text.html#limited-style-inheritance
