### ISSUE TITLE
Media query, transitions, pseudo-elements, semantic HTML, SEO best practices?

### ISSUE THREAD

**Issue by mikeaustin** [necolas/react-native-web#646]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Someone looking to write code compatible with both React Native and React Native for Web, what resources can I read that describe the best options for media queries, transitions, pseudo-elements, semantic HTML, and SEO? Some of these topics are covered by https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md, but not in depth.

**What is the expected behavior?**

A short article about the differences between native and web with regards to these topics, and how to code in a way that works for both platforms, if possible. I'm doing some research myself (for example, https://github.com/FormidableLabs/radium), but wanted to see how people currently deal these and start a conversation.

**Comment by necolas** [comment]
I think this is all covered in the style and accessibility guides. Transitions are supported too if you look at the View docs.

**Comment by mikeaustin** [comment]
Maybe I'm a little confused since transition* is web-only. I'm asking about something that works for both React Native and for Web. I'll update the title.

transitionProperty ‡ (web only)

**Comment by necolas** [comment]
Yeah, on native you may need to use the `Animated` library
