### ISSUE TITLE
Easing module not found

### ISSUE THREAD

**Issue by finian** [necolas/react-native-web#649]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When `import { Easing } from 'react-native'`
Got:
```
Module not found: Error: Can't resolve 'react-native-web/dist/apis/Easing'
```

And I've checked out the `react-native-web/dist` folder, there is no **Easing** files in `apis` folder. Am I missing something?

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1.
2.

**What is the expected behavior?**

**Environment (include versions). Did this work in previous versions?**

* OS: OS X 10.11.6
* Device:
* Browser:
* React Native for Web (version): 0.0.125
* React (version): 15.6.1

**Comment by wollld** [comment]
export { default as Dimensions } from './apis/Dimensions';
export { default as Easing } from 'animated/lib/Easing';

your should run `npm install animated --save` because this module is not in rnw

**Comment by necolas** [comment]
Are you using the Babel plugin?
