### ISSUE TITLE
Touchable: additional props for web

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#65]
Determine whether `Touchable` should pass through all other props or selectively add specific props (e.g., `onFocus`, `href`, `target`, `aria-*`).

**Comment by c-h-** [comment]
Is this as simple as adding `href` (and other props) around [here](https://github.com/necolas/react-native-web/blob/master/src/components/Touchable/TouchableHighlight.js#L241) in the Touchable Modules? Or did you have something more sophisticated in mind??

Right now when I add `role="link" href="/"` to TouchableHighlight it renders an `<a>` tag without the `href` attribute.

Would be great to be able to get the interactivity of Touchable components with the proper link attributes added. I'll stick to `<Text>` components for now.
