### ISSUE TITLE
Uncaught SyntaxError in some browsers that specified as supported

### ISSUE THREAD

**Issue by kuznetsov0209** [necolas/react-native-web#650]
**Bug**
Default demo app (https://react-native-web-playground.glitch.me/) not working in IE10 and default browser Android 4.4 (Chrome 28)

**Current behavior**
Blank screen.
Exception message:
> In strict mode, function declarations cannot be nested inside a statement or block. They may only appear at the top level or directly inside a function body.

**Steps to reproduce**
Open https://react-native-web-playground.glitch.me/ in IE10 or default browser Android 4.4

**Expected behavior**
Working demo on browsers specified as supported in README.md:

> Browser support: Chrome, Firefox, Safari >= 7, IE 10, Edge

**Environment**

* Browser: IE10, Android 4.4 default browser
* React Native for Web (version): v0.0.124

**Comment by kuznetsov0209** [comment]
It started reproducing since v0.0.117

**Comment by necolas** [comment]
Does the stack trace indicate where in the code it's seeing that?

**Comment by necolas** [comment]
Stack trace in Chrome 28 points to `warnValidStyle/index.js`.

**Comment by necolas** [comment]
Hopefully fixed in master? Attempting to support IE10 will likely be dropped soon - Twitter doesn't support it and usage is relatively low.

**Comment by necolas** [comment]
Confirmed this is fixed in the glitch example. It might be that storybook doesn't support IE10 though
