### ISSUE TITLE
BackgroundImage support or importing replace

### ISSUE THREAD

**Issue by cherniv** [necolas/react-native-web#652]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
> Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

React Native 0.48 now has two components for images: Image and BackgroundImage. 
React-native-web 0.125 doesnt have BackgroundImage, so `<BackgroundImage ... >` obviously doesnt work. 
How can i solve it on the settings level, may be replace/redirect it with Image by Babel or Webpack somehow?

**Comment by necolas** [comment]
`ImageBackground` was only recently added to React Native. I've included it in the components backlog #91 to add here
