### ISSUE TITLE
Checkbox a11y role

### ISSUE THREAD

**Issue by ktj** [necolas/react-native-web#653]
**Do you want to request a *feature* or report a *bug*?**
Request a feature: accessibilityRole support for checkbox

**What is the current behavior?**
No aria attributes added

**What is the expected behavior?**
https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/checkbox/checkbox-1.html

**Comment by ktj** [comment]
I think I could try implementing this. I just need some ideas on how to handle aria-selected

**Comment by necolas** [comment]
Checkbox interfaces should be built upon the `checkbox` element using `ReactNative.createElement`. See the `Switch` implementation for ideas.
