### ISSUE TITLE
StyleSheet: flex lead to height problem

### ISSUE THREAD

**Issue by jefferscn** [necolas/react-native-web#654]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I use react-navigation with reate-native-web(last release).
In ReactNative,react-navigation work well,but when I use react-native-web instead,
BottomBar's Text lose its height.
After debugging, I found this problem is caused by flex-basis, in last release of RNW,when
set flex=1,lead to a css result "flex:1 1 0%", and when a div with css 
`{
    flex:1;
    flex-direction:row;
}` and without definite height.
its height will be zero.
But same code in ReactNative,component's height is determined by it's children.

**What is the expected behavior?**
flex=1's behavior should be consistent with ReactNative

**Environment (include versions). Did this work in previous versions?**

* OS:Window7
* Device:PC
* Browser:chrome( 61.0.3163.79 )
* React Native for Web (version):0.0.129
* React (version):15.5.4

**Comment by necolas** [comment]
Example code that reproduces the problem please

**Comment by bakso** [comment]
+1

**Comment by bakso** [comment]
@jefferscn old guys, did you resolved it?

**Comment by necolas** [comment]
I think I've done everything I can here. This is a problem with how browsers have implemented flexbox, and there is no value for `flex-basis` that can be used without causing other differences from React Native (which seems to have a better flexbox implementation than the web). Hopefully projects like React Navigation can make small adjustments to their code to account for this. Thanks

**Comment by ahmedu007** [comment]
Thanks for this amazing repo. Is there any workaround for this bug? Has anyone else encountered this issue? Things work as expected on chrome but break on firefox

**Comment by hosseinmd** [comment]
I have the same issue
this problem solve when I add absolutely fit
