### ISSUE TITLE
TextInput in TouchableHighlight cannot be focus

### ISSUE THREAD

**Issue by jefferscn** [necolas/react-native-web#655]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A TextInput whthin TouchableHighlight, when i click on TextInput,TouchableHighlight is clicked,
and TextInput cannot be focusd in.

**If the current behavior is a bug, please provide the steps to reproduce and

**What is the expected behavior?**
TextInput should be able to focus.

**Environment (include versions). Did this work in previous versions?**

* OS:Win7
* Device:PC
* Browser:chrome( 61.0.3163.79 )
* React Native for Web (version):0.0.129
* React (version):15.5.4

**Comment by necolas** [comment]
I can't reproduce this issue. There's an example using `TouchableWithoutFeedback` here: https://github.com/necolas/react-native-web/blob/26bdf44a4c1f796ab3d438e6b60fecb3fb5e6f41/docs/storybook/1-components/TextInput/examples/TouchableWrapper.js

**Comment by grit96** [comment]
This appears to be an issue when using a `TouchableWithoutFeedback` with `onPress={Keyboard.dismiss}` (this is done to allow dismissing the keyboard when tapping outside a text input - https://akshay-s-somkuwar.medium.com/dismiss-hide-keyboard-on-tap-outside-of-textinput-react-native-b94016f35ff0).
