### ISSUE TITLE
StyleSheet: investigate using Map

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#656]
Since React 16 requires a Map/Set polyfill for older browsers, it's worth assessing use in RNW and whether there are performance benefits

**Comment by jaredly** [comment]
I profiled this a while ago, and Map was **much** slower than using an object, if your keys are strings. If you want complex (object) keys, then Map is what you want, but it's definitely not a perf gain.

**Comment by necolas** [comment]
OK, thanks for the tip. I'll skip on this
