### ISSUE TITLE
React 16.0 support?

### ISSUE THREAD

**Issue by JayHuang** [necolas/react-native-web#658]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Not working for 16.0.0-alpha.12

https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html

React 16.0 is out, just wondering if there's a plan to make `react-native-web` work for that and if so, what the timeline is like?

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/releases/tag/0.1.0
