### ISSUE TITLE
Update NetInfo API to conform to new React-Native spec

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#662]
**Do you want to request a *feature* or report a *bug*?**
Feature update

**What is the current behavior?**
NetInfo API only returns the ConnectionType and onLine status of the browser.

**What is the expected behavior?**
The [React Native NetInfo Spec](https://facebook.github.io/react-native/docs/netinfo.html) was updated to include a few new changes:

- fetch() is deprecated in favor of getConnectionInfo()
- eventName 'change' was deprecated in event handlers for 'connectionChange'
- returns from getConnectionInfo() and eventHandlers are now objects instead of string ConnectionType

**What is proposed**
I'd like to update the RNW NetInfo API to conform to the new specs. I plan to add code to note the deprecations since otherwise this would result in a breaking change. In addition, now that the getConnectionInfo is an object, I'd like to find a way to maximally include whatever information browsers provide so that users don't feel the need to work around this NetInfo impl and write their own.

**Comment by ThaJay** [comment]
https://facebook.github.io/react-native/docs/netinfo.html
```
Uncaught TypeError: _reactNative.NetInfo.isConnected.fetch(...).then(...).done is not a function
```
```
    NetInfo.isConnected.fetch().then(isConnected => {
      this.handleConnectionStatusChange(isConnected)
      NetInfo.isConnected.addEventListener(
        'connectionChange', this.handleConnectionStatusChange
      )
    })
```

**Comment by ThaJay** [comment]
```
NetInfo.addEventListener(
  'connectionChange',
  this.handleConnectionStatusChange
)
```
> Network Connection API is not supported. Not listening for connection type changes.
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/connection
```
This is an experimental technology
Check the Browser compatibility table carefully before using this in production.
```
