### ISSUE TITLE
ERROR: Touchable child must either be native or forward setNativeProps to a native component

### ISSUE THREAD

**Issue by mikeaustin** [necolas/react-native-web#664]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When wrapping a custom component with TouchableHighlight, React throws this error:
Touchable child must either be native or forward setNativeProps to a native component

If I use TouchableOpacity, or use View directly, the error is not thrown. Possibly related to https://github.com/react-native-training/react-native-elements/issues/407

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

    const BugTest = props => <Text>Hello</Text>;

    render() {
      <TouchableHighlight onPress={event => alert(event)}>
        <BugTest />
      </TouchableHighlight>
    }

**What is the expected behavior?**

No error is thrown. Using the <Text> tag directly or using TouchableOpacity fixes the error. Possibly related to https://github.com/react-native-training/react-native-elements/issues/407

**Environment (include versions). Did this work in previous versions?**

* OS: MacOS 10.12.6 (16G29)
* Device: MacBook Pro (Retina, 15-inch, Late 2013)
* Browser: Version 61.0.3163.100 (Official Build) (64-bit)
* React Native for Web (version): ^0.1.0
* React (version): ^16.0.0

**Comment by mikeaustin** [comment]
I can take a look at TouchableOpacity and see what's different.

**Comment by necolas** [comment]
see https://github.com/necolas/react-native-web/blob/master/docs/guides/direct-manipulation.md#composite-components-and-setnativeprops

**Comment by mikeaustin** [comment]
Thanks for the links. Ok, so a composite component _renders_ a native component, but _doesn't have one_ itself. It fixed the problem, but still feels unexpected, awkward and leaky. i.e. it is special, but TouchableOpacity is not. Anyway, it's fixed, thanks!
