### ISSUE TITLE
Problem with a ScrollView cutting off nested Views with absolute positioning

### ISSUE THREAD

**Issue by vget98** [necolas/react-native-web#672]
**Do you want to request a *feature* or report a *bug*?**
Question bug could be a bug.

**What is the current behavior?**
When adding a tooltip with position absolute the scrollView still cuts off the element at the border of the scrollview. Even with given a z-index of 9999

![screen shot 2017-10-04 at 8 43 05 am](https://user-images.githubusercontent.com/14142879/31185540-13921edc-a8e1-11e7-98d0-a33aa3f444bd.png)

**What is the expected behavior?**
I would expect the behavior to be that any element that is nested inside the ScrollView with position absolute to be over the ScrollView

* OS: IOS
* Device: Macbook
* Browser: Chrome 
* React Native for Web (version):  "react-native-web": "~0.0.120",
* React (version): "react": "~15.6.1",

**Comment by Monte47** [comment]
Did you end up finding a solution to this? Am having a similar issue?

**Comment by EyMaddis** [comment]
React Native treats every component as `position: relative` which means that all nested absolute positions are relative to this, z-index does not matter in that case.
So this behaves like React Native does.

You, unfortunately, have to move the modal component to a higher position in the DOM. I had to solve this in the past by having the modal set up globally, reposition its `x` and `y` and pass its content as a function call.

**Comment by vget98** [comment]
@Monte47 Eymaddis' solution is what I did.

**Comment by necolas** [comment]
React Native also clips the overflow perpendicular to the direction of scroll, so this seems to be working as intended

**Comment by TheChanDI** [comment]
How to solve this ?? I dont get EyMaddis solution.

**Comment by vinaysharma14** [comment]
Is there any solution so far?
