### ISSUE TITLE
Add Fusebox Example/Guide

### ISSUE THREAD

**Issue by pyros2097** [necolas/react-native-web#674]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Not There

It would be great if we would have a fuse-box example/guide. I had got it setup and working. But I'm unable to use the react-native-web/babel to replace react-native calls with react-native-web. So right now I'm importing directly from react-native-web for it to work.

**Comment by necolas** [comment]
What is fusebox?

**Comment by pyros2097** [comment]
fusebox is a module bundler just like webpack but it way way faster and has hot reloading inbuilt. http://fuse-box.org/

It seems to be coming up and I wanted to try it out with react-native-web. It seems to be working expect the importing from 'react-native-web' part which I will post an issue in that project. But It would be good If a guide for it can be added. I can do it if need be.

**Comment by VinceBT** [comment]
Seems you can do [aliases with FuseBox](http://fuse-box.org/page/configuration#alias)

**Comment by pyros2097** [comment]
@VinceBT Tried it before and it didn't seem to work. I tried it again and now it works. Nice. Thanks. Now it might be time to add a PR.
But anyway then this 'react-native-web/babel' plugin is of no use then and didn't work also. I thought this was the new way of doing it instead of aliases.

**Comment by necolas** [comment]
Ok. I don't think we need examples for every bundler at the moment. If fusebox integrates with Babel you just need to add the RNW plugin to your Babel config
