### ISSUE TITLE
BUG in Getting Started webpack.config.js

### ISSUE THREAD

**Issue by ricklove** [necolas/react-native-web#678]
Need to add this at the top of the webpack.config.js:

```
var path = require('path');
var webpack = require('webpack');
```

**Comment by necolas** [comment]
It's not intended to be a compete and working js file

**Comment by mikeaustin** [comment]
Maybe simply stating that it's not a complete example would make it clear? Personally, I've run into many 'almost complete' examples on sites and it's a little frustrating when it doesn't work.

**Comment by ricklove** [comment]
When the instructions say "Create a web/webpack.config.js file:" It should be a complete example from scratch.

There should be a pathway from:

- "react-native init Project"
- Update Babel
- Add webpack.js
- Build and run

At this point, the Getting Started (but not really because there are some gaps and you'll just have to figure that out - good luck searching google for a webpack.config that will work for you).
