### ISSUE TITLE
Babel plugin misses a case

### ISSUE THREAD

**Issue by JakeCoxon** [necolas/react-native-web#679]
**Do you want to request a *feature* or report a *bug*?**
This is a bug

**What is the current behavior?**
libraries calling ```require('react-native')``` without a variable declaration isn't replaced. EG mobx-react uses the folllwing
```
typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('mobx'), require('react'), require('react-native')) :
```

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

```
const func = x => x
func(require('react-native'))
```

**What is the expected behavior?**

All requires to react-native should be replaced with react-native-web

**Environment (include versions). Did this work in previous versions?**

* OS: mac osx
* Device:
* Browser:
* React Native for Web (version): 0.0.130
* React (version): 15.6.1

**Comment by necolas** [comment]
Hmm ok but importing like this doesn't seem like a good idea

**Comment by paularmstrong** [comment]
IIRC, we didn't include commonjs `require` statements for a reason. Was it because there are just too many possible ways that they can be used?

**Comment by necolas** [comment]
Yeah we chose to only support basic usage of `require` at this time.
