### ISSUE TITLE
Recommended practice for using this module with React Native project

### ISSUE THREAD

**Issue by oney** [necolas/react-native-web#68]
I have had a React Native project that was created by `react-native init MyApp`. How to use this module with it? Put it in the same directory or separate it? Thanks!

**Comment by yujiangshui** [comment]
@oney I recommend this similar project which I already use in my project. [React-web](https://github.com/taobaofed/react-web) and the README shows how to use it.

**Comment by yuanyan** [comment]
React Web +1

**Comment by necolas** [comment]
resolved in 1c7fb4cb45d28e02e2e782d62b7a0e93b0f6911d

see: https://github.com/necolas/react-native-web/blob/f8554ecc1edebcf4354eb3d80a0e1d06ebfd02fa/docs/guides/react-native.md
