### ISSUE TITLE
onTap as onClick

### ISSUE THREAD

**Issue by txs** [necolas/react-native-web#683]
**Do you want to request a *feature* or report a *bug*?**
I have a sidebar drawer using react-native-drawer. It's working with the RNW
However, when I use mouse drag open and click mask to close. it's fine with a mouse.
But when I use my finger touch the screen, the tap mask require me to hold so that the menu could close.

Is there any method to make the touch event as the mouse event in RNW? Thanks
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1.
2.

**What is the expected behavior?**

**Environment (include versions). Did this work in previous versions?**

* OS:
* Device:
* Browser:
* React Native for Web (version):
* React (version):

**Comment by necolas** [comment]
Hi, I'll reopen this once you've filled out the requested information and put an example app on glitch that reproduces the problem (this helps me help you). Thanks for understanding
