### ISSUE TITLE
What is the future of react-native-web?

### ISSUE THREAD

**Issue by ryanoglesby08** [necolas/react-native-web#687]
Hi @necolas,

I'm evaluating this package for potential adoption at a large organization across multiple teams. We really like the philosophy and implementation of it! Thank you so much for all your work so far in making it.

I'm wondering what you see as the future of react-native-web? Is this just an experiment you did and used on Twitter Lite? Will it be maintained/backed by Twitter at some point? Do you have a long-term vision and roadmap?

Any info or thoughts you have would be much appreciated.

**Comment by ericwooley** [comment]
This has a lot of momentum, I think if @necolas gave up on it, someone would step forward to maintain it.

**Comment by necolas** [comment]
Yes it's used to implement almost every component in Twitter Lite / Web. It was experimentally validated against production traffic including in emerging markets. There are other companies looking to do the same.

I think there are many possibilities for the project just in terms of future optimizations, tighter integration with tools in the React ecosystem, and the kinds of web apps people will be able to create. I think collaboration with the React and Expo teams (as well as any companies using RN and RNW) is where most of this can be figured out.

**Comment by necolas** [comment]
On the issue on maintenance. Twitter will not be maintaining this project, and I think that's a good thing. Twitter does not have a good record maintaining frontend OSS, nor does it currently have the means to do so. As an organization, React Native isn't on their radar. Essentially I'm saying that if this project were "maintained by Twitter", it would still be me doing all the work. If there is the need to add/change maintainers that's also easier to do at the moment.

**Comment by ryanoglesby08** [comment]
Thanks for the info. This is very enlightening. If you think of anything else relevant please post it here, otherwise feel free to close this issue whenever you like.

**Comment by necolas** [comment]
Sounds good. Thanks. Let me know how you get on and if you have other questions
