### ISSUE TITLE
PanResponder: locationX is not relative to the element and is not deterministic

### ISSUE THREAD

**Issue by notgiorgi** [necolas/react-native-web#693]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**

First take a look at demo gif: https://giphy.com/gifs/3ohhwHRjf4RCpEmmNq/fullscreen

I've `panHandlers` attached on the red container, and I'm logging `locationX` from `onPanResponderMove`. `locationX` changes in a weird way, and is not relative to red box when outside of the red box. 

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

here's the glitch link: https://glitch.com/edit/#!/statuesque-bedbug
checkout the `App.js`

**What is the expected behavior?**

`locationX` should be relative to parent.

**Environment (include versions). Did this work in previous versions?**

* OS: MacOS Sierra
* Device: MacBook Pro 13 (early 2015)
* Browser: Google chrome 61
* React Native for Web (version): 0.1.0
* React (version): 16.0.0

**Comment by teabyii** [comment]
I find it also happens in iOS by react-native:
https://github.com/facebook/react-native/issues/15290

I guess the locationX is relative to the element which the event occurred but not the element which the event attched.

**Comment by necolas** [comment]
> I guess the locationX is relative to the element which the event occurred but not the element which the event attached

I think this is right.

You can see [here](https://github.com/necolas/react-native-web/blob/0.4.0/packages/react-native-web/src/modules/normalizeNativeEvent/index.js#L24-L32) that the event normalization calculates `location{X,Y}` by measuring the target node of the event. It doesn't know anything about which element has the listeners and should be the relative context.

**Comment by arg1998** [comment]
ammm. im still having this problem, any fix????

**Comment by necolas** [comment]
Moved this into #1219 and updated the test case so that it is pinned to specific package versions
