### ISSUE TITLE
Don't optimize css for development

### ISSUE THREAD

**Issue by notgiorgi** [necolas/react-native-web#695]
Feature request:

It would be convenient if I could use devtools to debug my css, now they're optimized, every property in separate classes so I cannot play with them.

If rnw only optimized them for production would be better.

**Comment by necolas** [comment]
It's not just for optimization. You can use the React Dev Tools to inspect your RN styles instead. see https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md
