### ISSUE TITLE
Consistent with react-native rendering

### ISSUE THREAD

**Issue by cpunion** [necolas/react-native-web#697]
**Do you want to request a *feature* or report a *bug*?**

Request Feature: Make some rendering consistent with react-native.

**What is the current behavior?**

See https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/81, I created a repo to try to make NativeBase-KitchenSink working on react-native-web (Try not to modify code), it works not bad and has some problems that seems difference with on react-native:

1. Some style problems, e.g. Button's border, it rendered as 3 pixels width, but in Chrome DevTool I didn't see that style. Also reproduce this in a small example, it just render a NativeBase's Button in a View.

2. Some API it's not supported, I can patch in my environment. e.g. Dimensions, Platform.getInitialURL etc.

So just need fix some style problem. I don't know it should be fixed in react-native-web's or NativeBase's.

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

See the link above.

**What is the expected behavior?**

Consistent with react-native.

**Environment (include versions). Did this work in previous versions?**

* OS: macOS 10.13
* Device: MBP 2012 late
* Browser: Chrome  62.0.3202.75
* React Native for Web (version):0.1.12
* React (version):16.0.0

**Comment by necolas** [comment]
Please can you make some isolated test cases and specify which APIs. I'll reopen when there is that actionable info. Thanks

**Comment by cpunion** [comment]
https://glitch.com/edit/#!/sable-suit

Made a smallest test to reproduce without NativeBase, show a View with `borderWidth: null`, it displays a 3-pixel width blue border.

**Comment by cpunion** [comment]
I will see the other problems and try to make smallest test case.

**Comment by necolas** [comment]
Thanks. The border issue should be fixed in 0.1.13

**Comment by cpunion** [comment]
I checked more issues and record here to avoid a new post.

- [ ] Wrong right alignment in ListItem: Can't reproduce in a simple case.
- [ ] ActionSheet: We can implement Modal by wrap react-native-modal or react-native-modalbox, and then implement the ActionSheetIOS.
- [ ] Layout different in Card/Card Showcase.
- [ ] Layout different in Deck Swiper/Advanced Deck Swiper.
- [ ] Layout different in Form & Inputs/Stacked Label.
- [ ] Style different in List/List Header.
- [ ] Style different in List/List Icon: Seems it's problem about unimplemented Modal too, more cases in Picker.
- [ ] Layout different in SearchBar.
- [ ] Layout different in Tabs/Scrollable Tabs.
- [ ] Drawer layout defferent

And other cases are perfect, I think the consistency is very high. :thumbsup::thumbsup::thumbsup:

So Modal is important to make some components work. And I will try to check and simplify other cases.

**Some snapshots: (The picture with a big black border is capture on iOS Simulator, it run in react-native)**

<img width="340" alt="2017-11-01 11 01 11" src="https://user-images.githubusercontent.com/8459/32258810-bb32ab62-bef7-11e7-95eb-96ee38c16461.png">
<img width="346" alt="2017-11-01 11 01 18" src="https://user-images.githubusercontent.com/8459/32258811-bb81173e-bef7-11e7-8f3f-dbcddcc9271d.png">
<img width="344" alt="2017-11-01 11 08 53" src="https://user-images.githubusercontent.com/8459/32258814-c0c02df2-bef7-11e7-9a3b-1ba6b90e3388.png">
<img width="339" alt="2017-11-01 11 08 58" src="https://user-images.githubusercontent.com/8459/32258816-c0f0a77a-bef7-11e7-8251-1da383696870.png">
<img width="344" alt="2017-11-01 11 09 14" src="https://user-images.githubusercontent.com/8459/32258820-c6dd5e1c-bef7-11e7-96bf-d7a5e79fd69d.png">
<img width="335" alt="2017-11-01 11 09 20" src="https://user-images.githubusercontent.com/8459/32258821-c70c0b5e-bef7-11e7-9135-26e005a90053.png">
<img width="343" alt="2017-11-01 11 15 27" src="https://user-images.githubusercontent.com/8459/32258826-ce883bbe-bef7-11e7-9678-a06224bd7d89.png">
<img width="339" alt="2017-11-01 11 15 31" src="https://user-images.githubusercontent.com/8459/32258828-ceb93a98-bef7-11e7-8035-b47f70a02e5a.png">
<img width="338" alt="2017-11-01 11 16 29" src="https://user-images.githubusercontent.com/8459/32258836-d38eb69c-bef7-11e7-9d94-7b9a01f60815.png">
<img width="339" alt="2017-11-01 11 16 33" src="https://user-images.githubusercontent.com/8459/32258837-d3be25ee-bef7-11e7-996b-56adea168acf.png">
<img width="342" alt="2017-11-01 11 16 53" src="https://user-images.githubusercontent.com/8459/32258843-d8e60cbc-bef7-11e7-8862-36528427c942.png">
<img width="346" alt="2017-11-01 11 16 58" src="https://user-images.githubusercontent.com/8459/32258845-d919674c-bef7-11e7-9db6-558bbf9a0fd9.png">
<img width="341" alt="2017-11-01 11 18 12" src="https://user-images.githubusercontent.com/8459/32258846-dc52b7a6-bef7-11e7-8df2-d801146dc998.png">
<img width="336" alt="2017-11-01 11 18 17" src="https://user-images.githubusercontent.com/8459/32258847-dcb5001e-bef7-11e7-90ef-a4214683f900.png">
<img width="343" alt="2017-11-01 11 34 55" src="https://user-images.githubusercontent.com/8459/32259040-d617126e-bef8-11e7-8b86-f56b125806b9.png">
<img width="341" alt="2017-11-01 11 35 06" src="https://user-images.githubusercontent.com/8459/32259041-d646845e-bef8-11e7-8e41-85b777c285ab.png">

**Comment by murtraja** [comment]
That red bordered box is still present when we have <Root/> component from NativeBase. @cpunion, did you find any workarounds for this since no matter howsoever I style it, it still is visible :)

**Comment by tonypee** [comment]
Is there an update on the red box issue? Im seeing it also

**Comment by jmatsushita** [comment]
Also seeing this with ActionSheet on `native-base@2.13.8` with `react-native-web@0.11.7`
CC https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/81

**Comment by jmatsushita** [comment]
Oh, is it that Modal isn't implemented yet? https://github.com/necolas/react-native-web/issues/1020 ?
