### ISSUE TITLE
Add ListView

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#7]
docs: https://facebook.github.io/react-native/docs/listview.html

datasource: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListViewDataSource.js

component: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js

**Comment by phuu** [comment]
Probably going to take a run at this. Do you think there's a way we can reuse some of the component from the main library?

**Comment by necolas** [comment]
Polymer's strategy: https://github.com/PolymerElements/iron-list

**Comment by IjzerenHein** [comment]
@phuu Have you given it a go at this? If not I'm willing to have a go at it.

**Comment by IjzerenHein** [comment]
For the record, I have started work on the ListView implementation, progress can be tracked here:
https://github.com/IjzerenHein/react-native-web/tree/feature-listview

**Comment by IjzerenHein** [comment]
I've implemented a basic version of the ListView component, see more details in the pull request here:
#87
