### ISSUE TITLE
StyleSheet: wrong border when borderXWidth set to null

### ISSUE THREAD

**Issue by cpunion** [necolas/react-native-web#700]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
The style 
```js
{borderLeftWidth: null, borderRightWidth: null, borderTopWidth: null, borderBottomWidth: null}
```
be rendered to:
```css
{borderLeftWidth: 'NaNpx', borderRightWidth: 'NaNpx', borderTopWidth: 'NaNpx', borderBottomWidth: 'NaNpx'}
```

I'm not sure, just saw in React DevTool, not DOM inspector.

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

I tried but can't reproduce in a small case, can you find some in the snapshots? Seems it converts `null` to `'NaNpx'`.

The `style` property of View in DevTool:

<img width="623" alt="2017-11-01 12 30 18" src="https://user-images.githubusercontent.com/8459/32260168-2ff23ae0-bf01-11e7-9367-34338b7d8bd0.png">

The `style` property of div in DevTool:

<img width="594" alt="2017-11-01 2 56 05" src="https://user-images.githubusercontent.com/8459/32263437-e0a7c6d0-bf14-11e7-8c72-4e51ae30f5cd.png">

Full styles on div:

<img width="388" alt="2017-11-01 12 40 22" src="https://user-images.githubusercontent.com/8459/32260575-b6649648-bf03-11e7-8187-3b47e732bdec.png">
<img width="281" alt="2017-11-01 12 40 37" src="https://user-images.githubusercontent.com/8459/32260576-b6a88f6a-bf03-11e7-846a-5d12e1acae9a.png">
<img width="517" alt="2017-11-01 12 40 48" src="https://user-images.githubusercontent.com/8459/32260577-b6ddbdfc-bf03-11e7-8f04-e7083d29e779.png">
<img width="519" alt="2017-11-01 12 41 01" src="https://user-images.githubusercontent.com/8459/32260578-b71025a8-bf03-11e7-8b05-1ea1a6526d13.png">

**What is the expected behavior?**

Expect it show a rectangle without border.

**Environment (include versions). Did this work in previous versions?**

* OS: macOS 10.13
* Device: MBP 2012 late
* Browser: Chrome 62.0.3202.75
* React Native for Web (version): 0.1.13
* React (version): 16.0.0

**Comment by cpunion** [comment]
Added logs in normalizeValue to detect the NaN and found it, and same in StyleRegistry. But I can't locate the problem.

**Comment by necolas** [comment]
What library keeps using `null` values instead of `0`? Is this React Native Base again?

**Comment by cpunion** [comment]
Yes, is NativeBase again. :joy: I think it uses in theme to clear/override some basic theme style.

This is useful in some other place, e.g. to clear a component's default style. Sometimes we can't using `null` instead of `0`, e.g. setting Image style to `width: null` to clear default width, it's different with `width: 0`, and very common and simple for make a fullscreen image (or full size to parent).

**Comment by necolas** [comment]
It doesn't look like there is a problem in RNW. But maybe there is in how React Dev Tools displays `null` values
