### ISSUE TITLE
NativeMethodsMixin: measure/measureInWindow don't take into account scroll

### ISSUE THREAD

**Issue by sidhu663** [necolas/react-native-web#702]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
View.measure does not provide the correct pageX, pageY measurements if the view being measured is inside a ScrollView and the ScrollView is scrolled

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. RNW https://bitter-helicopter.glitch.me. Scroll and note that the number outputted is always 0
2. RN Android snack: https://snack.expo.io/BJV8NAv0-

**What is the expected behavior?**
Both platforms should behave the same (measure taking into account the scroll position)

Additionally, would be nice to take into account body scroll as well in the case of RNW so reliance on getBoundingClientRect could be eliminated

**Comment by necolas** [comment]
Let me know if you have a solution

**Comment by necolas** [comment]
Hey, did you look into this at all?

**Comment by sidhu663** [comment]
I haven't looked into it too much but the 2 options that come to mind are: 
1) As you climb the ancestor tree, read scrollTop and add that to the measurement component 
2) use getBoundingClientRect. 

I seem to recall you mentioning that getBoundingClientRect didn't take into account transforms but some quick testing shows that it does in fact take into account scale / translates so that might be the easiest way to go unless there's some other concerns that I'm not aware of

**Comment by necolas** [comment]
You don't want the values to change with transforms
