### ISSUE TITLE
<View> breaks if it contains a boolean (false) child

### ISSUE THREAD

**Issue by aaroncraig10e** [necolas/react-native-web#703]
A common shorthand for handling potentially empty state / prop entries is:
```
<View>{this.state.foo && <Text>{this.state.foo}</Text>}</View>
```

With the latest version (0.1.13) this construct breaks the View with the error message:
```
A text node cannot be a child of a <View>.
```

The test in `View/index.js` tests for `typeof item !== 'string'`, so the error message makes sense, however I think the behavior is unexpected, as passing a false value means (to me at least) "don't render anything".

Before opening a PR, however, I wanted to make sure that this isn't a desired behavior, and if so, what is the alternative syntax to passing a possibly empty value as a <View> child?

* React Native for Web (version): 0.1.13
* React (version): 16.0.0

**Comment by aaroncraig10e** [comment]
My bad, our code is passing an empty string, not false.

**Comment by jottenlips** [comment]
I notice this when conditionally rendering. 
Should this be valid?
```
{somePossiblyEmptyString ? <Text>{somePossiblyEmptyString}</Text> : <></>}
```
or
```
{somePossiblyEmptyString && <Text>{somePossiblyEmptyString}</Text>}
```


```
{!!somePossiblyEmptyString && <Text>{somePossiblyEmptyString}</Text>}
```
Using !! to fix this feels like a bit much. Thoughts? Thanks!

**Comment by jottenlips** [comment]
Is there an ESLint rule for this?

**Comment by jottenlips** [comment]
https://stackoverflow.com/a/53510213/6207061 Looks like others will run into this as well

**Comment by hamedor** [comment]
wow, its problem from 2017 still occursed,
i fixed this error by wrapping condition by <Text> like this:
<Text>
condition && <Element/>
</Text>

**Comment by aligee12** [comment]
this was causing issue for me: 
<View>{images.length>0 && <ImagesGrid images={images} /> }</View>

But solved by using this: 
<View>{images.length>0 ? <ImagesGrid images={images} /> :null }</View>
