### ISSUE TITLE
Disable warning for certain styles

### ISSUE THREAD

**Issue by miguelocarvajal** [necolas/react-native-web#707]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If a certain style is not supported by React Native, I get a warning in the browser. For example:

Warning: "transition" is not a valid style property.

**What is the expected behavior?**
In certain cases I am certain the stylesheet will not be passed to react-native's Stylesheet and will only be applied in a browser. So it would be nice to disable the warning in certain cases.

**Comment by necolas** [comment]
In this case `transition` isn't supported and you should use the long-hand properties `transitionDelay`, `transitionDuration`, `transitionProperty`, and `transitionTimingFunction` as documented [here](https://necolas.github.io/react-native-web/storybook/?selectedKind=Components&selectedStory=View)

**Comment by miguelocarvajal** [comment]
I should've caught that. Just what I needed.

Thanks! Love your work on this project!

**Comment by necolas** [comment]
No problem. Thank you :)

**Comment by JoseFMP** [comment]
However, it happens for some certainly supported properties, i.e. https://github.com/necolas/react-native-web/issues/1308
