### ISSUE TITLE
`PropTypes` warnings with React 16

### ISSUE THREAD

**Issue by piranna** [necolas/react-native-web#713]
**Do you want to request a *feature* or report a *bug*?**

Bug (sort-of).

**What is the current behavior?**

A lot of warning messages about unknown attributes and/or styles are being shown on the console. Seems React 16 (specially the `fbjs` module) is more picky with the `propTypes`, filling a lot of garbage on the console and making difficult to test the components and applications. Ans example error message is `Warning: <View /> is using uppercase HTML. Always use lowercase HTML tags in React.`.

**Comment by necolas** [comment]
Sounds like a bug in your code. You haven't included enough info to suggest otherwise
