### ISSUE TITLE
`delay` attribute not supported in `Animated.spring()`, is ignored.

### ISSUE THREAD

**Issue by skhameneh-strive** [necolas/react-native-web#714]
Works:
```
      Animated.sequence([
        Animated.delay(delay),
        Animated.spring(this.state.slideX, {
          toValue: 0,
          bounciness: 5,
          speed: 8,
          useNativeDriver: true
        })
      ]).start()
```

Does not work:
```
      Animated.spring(this.state.slideX, {
        delay: delay
        toValue: 0,
        bounciness: 5,
        speed: 8,
        useNativeDriver: true
      }).start()
```

Notes:

1.  `useNativeDriver` has no impact.
2. Both work in iOS and Android.
3. Versions:
- Node v6.11.5, NPM v3.10.10, Chrome v62.0.3202.75
- react-native-web@0.1.13
- react@16.1.0

**Comment by necolas** [comment]
Yeah this is because animatedjs/animated has not been well maintained and the version of Animated in RN has newer features.

**Comment by necolas** [comment]
Closing / folding this issue into #716
