### ISSUE TITLE
Use Animated from React Native

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#716]
`animatedjs/animated` has not kept up with React Native's changes to Animated. Moving back to copy-paste from React Native should make it easier to ensure API compatibility.

See #714 #688 #684

**Comment by vaukalak** [comment]
What is the issue of making `react-native` a dependency of `react-native-web` and just expose there api? Or maybe we should create an issue for `react-native` to move js animations part to separate module?

**Comment by necolas** [comment]
I'm not going to have everyone install the whole of react native to do this. Yeah I don't know why it hasn't been extracted from react native. That was the point of the animated repo but it hasn't worked out that way

**Comment by piranna** [comment]
> Or maybe we should create an issue for react-native to move js animations part to separate module?

We could open the issue, or we could do the separated module ourselves to see if they adopt it.

Anyway, since this is already merged in master, can it be published to npm? :-)
