### ISSUE TITLE
Have a detailed Getting started document？Help me，please！！！

### ISSUE THREAD

**Issue by 438198602** [necolas/react-native-web#717]
Have a detailed Getting started document？Help me，please！！！

**Comment by SRandazzo** [comment]
hi @438198602 👋

check out the  [Getting Started](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md) 

if that's not enough, there is a great [tutorial that uses storybooks here](https://hackernoon.com/up-and-running-with-universal-components-66678132cad) that I found extremely helpful

**Comment by necolas** [comment]
Thanks
