### ISSUE TITLE
Touchable: right-click triggers onPress

### ISSUE THREAD

**Issue by MatthieuLemoine** [necolas/react-native-web#719]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

When I right-click on a Touchable, the onPress event is triggered.

Can be reproduced in the [Storybook](https://necolas.github.io/react-native-web/storybook/?selectedKind=Components&selectedStory=TouchableHighlight&full=0&down=0&left=1&panelRight=0).

**What is the expected behavior?**

When right-clicking in a browser, it should only open the contextual menu but not trigger a click on the underlying view.

While trying to reproduce, I saw that this issue is not present on [Twitter Lite](https://mobile.twitter.com). Either it doesn't use Touchable or there is a way to disable this behavior.

**Environment (include versions). Did this work in previous versions?**

* OS: macOS
* Device: Macbook Air
* Browser: Firefox 57 & Chrome 62
* React Native for Web (version): 0.1.10
* React (version): 16.0.0

**Comment by vaukalak** [comment]
@necolas what is expected behavior here?

**Comment by necolas** [comment]
As described in the OP
