### ISSUE TITLE
Unexpected press event triggered during scroll (without ScrollView)

### ISSUE THREAD

**Issue by GingerBear** [necolas/react-native-web#722]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when scrolling (emulating touch) without using `ScrollView` (let the browser scroll),  unexpected press event get triggered from inner components

**If the current behavior is a bug, please provide the steps to reproduce**

https://glitch.com/edit/#!/petite-suggestion

![nov-27-2017 13-41-20](https://user-images.githubusercontent.com/902357/33283238-309641f8-d379-11e7-8389-5816ee516f70.gif)

**What is the expected behavior?**
when scrolling (emulating touch) without using `ScrollView` (let the browser scroll),  no press event get triggered from inner components

**Environment (include versions). Did this work in previous versions?**

* OS: macOS 10.13.1
* Device: macbook pro
* Browser: chrome 62
* React Native for Web (version): 0.1.14
* React (version):16.1.1

**Comment by necolas** [comment]
That's expected when you use Touchables without a scroll view or the scroll responder mixin. Perhaps the Touchable mixin can account for this web-specific case, or you can use scroll view

**Comment by whhlulu** [comment]
Has the problem been solved yet?

**Comment by whhlulu** [comment]
Mistriggers are still very common, When I wanted to scroll, I triggered a click event.
