### ISSUE TITLE
Use react-native-web-lists to render FlatLists

### ISSUE THREAD

**Issue by entropitor** [necolas/react-native-web#725]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
React-native-web is not rendering FlatList while it is rendering SectionList. https://github.com/react-native-web-community/react-native-web-lists has an implementation for both

**Comment by necolas** [comment]
Is that just a copy-paste from react-native?

**Comment by entropitor** [comment]
They translate FlatList and SectionList to a ListView. As there is a listview implementation in react-native-web, we can re-use that implementation to render FlatList and SectionList

**Comment by necolas** [comment]
They should be using virtualization as list view is going away. I'd rather pick up from one of the PRs that tries to implement them correctly. Thanks

**Comment by entropitor** [comment]
Wouldn't it be useful to have an implementation already? And then replace it later with one using virtualization?

**Comment by piranna** [comment]
> Wouldn't it be useful to have an implementation already? And then replace it later with one using virtualization?

I agree, I'm needing this too.

**Comment by atitpatel** [comment]
Need this feature. @necolas 
Also, those who are looking for options, here is one : https://github.com/Flipkart/recyclerlistview
It has taken care of virtualisation as well.
Do share your views @entropitor @necolas

**Comment by necolas** [comment]
Er, all the lists are available. You can use Flipkart's one too if you want.
