### ISSUE TITLE
Impossible to print image.

### ISSUE THREAD

**Issue by vaukalak** [necolas/react-native-web#726]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`Image` component [has opacity style set to 0](https://github.com/necolas/react-native-web/blob/master/src/components/Image/index.js#L327). This creates problems, when trying to print an image (images are invisible).

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. http://necolas.github.io/react-native-web/storybook/?selectedKind=Components&selectedStory=Image&full=0&down=0&left=1&panelRight=0
just try to print.

**What is the expected behavior?**

Images should be printed correctly.

**Environment (include versions). Did this work in previous versions?**

* OS: all
* Device: all
* Browser: all
* React Native for Web (version): all
* React (version): all

Why at all this view has `opacity: 0`, and are there any suggestions for the fix? Btw if it's a question of children - then react-native has deprecated children inside `Image`.

**Comment by necolas** [comment]
Hmm, I haven't made any allowances for printing apps. I guess background images are not printed? The image is visually hidden because it's only the for accessibility purposes.

**Comment by vaukalak** [comment]
yeah, actually in chrome if you press `extended options` you can select `background graphics` as additional option... Not 100% why of this, but looks it the same behavior in all browsers. What do you  think about reworking image rendering, as in `react-native` children in images are deprecated? Or at least for now, we can mirror new `react-native` `ImageBackground` api, and leave a deprecation note in `Image` where there any children (current behavior of `react-native`)?

**Comment by necolas** [comment]
Rendering children is already removed from `Image` and not related to the rest of the implementation. Going to close this for now, as printing images can be configured at the browser level, and RN is focused more on building apps rather than print content websites.
