### ISSUE TITLE
CameraRoll

### ISSUE THREAD

**Issue by piranna** [necolas/react-native-web#727]
Implement [CameraRoll](https://facebook.github.io/react-native/docs/cameraroll.html) API. On the browser, I think it would be just enough to create a hidden [`<Input type="file">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) tag that open a file selector modal window  pre-set to only accept image files.

**Comment by necolas** [comment]
The CameraRoll API is considerably more complicated than that. I don't think the web has all the necessary APIs

**Comment by piranna** [comment]
For a simple one it would be enough, but a better one would be to use Device Library API. I'm not able to find info about the spec, but I know it was part of FirefoxOS.

**Comment by necolas** [comment]
Closing this as I think bringing this to web is not feasible at the moment, and the CameraRoll API is set to be moved out of RN core in the next few months.
