### ISSUE TITLE
any rich samples?

### ISSUE THREAD

**Issue by fatfatson** [necolas/react-native-web#730]
the only complete sample I can find is [rn-rnw-setup-live-reload](https://github.com/naqvitalha/rn-rnw-setup-live-reload), but it only shows a Text.
I hope there are more demonstration about:
1. how to use image/av assets
2. how to replace native-only component for web when there's no builtin supply from RNW, such as CodePush, it's used in my App.js, then webpack complains:

> ERROR in ./node_modules/react-native-code-push/CodePush.js
> Module parse failed: Unexpected token (30:35)
> You may need an appropriate loader to handle this file type.

**Comment by RangerMauve** [comment]
Any react-native libraries that have bindings to Java or Objective-C code won't work with the web version. You'll need to reimplement the APIs using web standards.

This library doesn't do anything special with regards to image assets, that's up to users to figure out. create-react-app is a great place to start to set up your build tools for web.

**Comment by fatfatson** [comment]
yes I know I should  reimplement any native API for web, maybe some empty functions could address that. but I don't know how to adapt them to this library.

**Comment by RangerMauve** [comment]
Code-push doesn't seem like something that makes sense to port to the web. Maybe separate your UI code from the code used to set up your UI and have the web setup code do whatever makes sense for web.

**Comment by necolas** [comment]
1. Image assets can be used as in RN. You can also look through the storybook and the source code (linked from the storybook)
2. Read about splitting web-specific and native-specific code. It works the same way as splitting ios/android code: https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#web-specific-code

**Comment by sxyshirly** [comment]
hello，I have some similar，can you tell me how to solve this problem？
ERROR in ./node_modules/react-native-fetch-blob/index.js 13:12
Module parse failed: Unexpected token (13:12)
You may need an appropriate loader to handle this file type.
|   AppState,
| } from 'react-native'
> import type {
|   RNFetchBlobNative,
|   RNFetchBlobConfig,
 @ ./src/services/localFile.js 1:433-467
 @ ./src/models/sagas/configSaga.js
 @ ./src/models/sagas/saga.js
 @ ./src/models/store/configStore.js
 @ ./src/app.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js

ERROR in ./node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js 14:12
Module parse failed: Unexpected token (14:12)
You may need an appropriate loader to handle this file type.
| import { isIphoneX } from 'react-native-iphone-x-helper'
|
> import type { KeyboardAwareInterface } from './KeyboardAwareInterface'
|
| const _KAM_DEFAULT_TAB_BAR_HEIGHT: number = isIphoneX() ? 83 : 49
 @ ./node_modules/react-native-keyboard-aware-scroll-view/index.js 3:0-59 9:0-15:1
 @ ./src/scenes/account/open/openAccount.js
 @ ./src/scenes/routes/login.route.js
 @ ./src/scenes/routes/index.js
 @ ./src/appWrapper.js
 @ ./src/app.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js

ERROR in ./node_modules/react-native-code-push/CodePush.js 510:15
Module parse failed: Unexpected token (510:15)
You may need an appropriate loader to handle this file type.
|         }
|
>         return <RootComponent {...props} />
|       }
|     }
 @ ./src/services/thirdSDK.js 1:564-597
 @ ./src/app.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js

**Comment by sxyshirly** [comment]
hello，I have some similar issue，can you tell me how to solve this problem？
ERROR in ./node_modules/react-native-fetch-blob/index.js 13:12
Module parse failed: Unexpected token (13:12)
You may need an appropriate loader to handle this file type.
| AppState,
| } from 'react-native'
import type {
| RNFetchBlobNative,
| RNFetchBlobConfig,
@ ./src/services/localFile.js 1:433-467
@ ./src/models/sagas/configSaga.js
@ ./src/models/sagas/saga.js
@ ./src/models/store/configStore.js
@ ./src/app.js
@ ./index.web.js
@ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js
ERROR in ./node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js 14:12
Module parse failed: Unexpected token (14:12)
You may need an appropriate loader to handle this file type.
| import { isIphoneX } from 'react-native-iphone-x-helper'
|
import type { KeyboardAwareInterface } from './KeyboardAwareInterface'
|
| const _KAM_DEFAULT_TAB_BAR_HEIGHT: number = isIphoneX() ? 83 : 49
@ ./node_modules/react-native-keyboard-aware-scroll-view/index.js 3:0-59 9:0-15:1
@ ./src/scenes/account/open/openAccount.js
@ ./src/scenes/routes/login.route.js
@ ./src/scenes/routes/index.js
@ ./src/appWrapper.js
@ ./src/app.js
@ ./index.web.js
@ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js
ERROR in ./node_modules/react-native-code-push/CodePush.js 510:15
Module parse failed: Unexpected token (510:15)
You may need an appropriate loader to handle this file type.
| }
|
    return <RootComponent {...props} />
| }
| }
@ ./src/services/thirdSDK.js 1:564-597
@ ./src/app.js
@ ./index.web.js
@ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js

**Comment by MahmonirB** [comment]
Is there any update about this?
I have this issue, react-native-code-push with react-native-web,
please help me, how can I resolve it?
Thank you

**Comment by karthick-t2s** [comment]
> Is there any update about this?
> I have this issue, react-native-code-push with react-native-web,
> please help me, how can I resolve it?
> Thank you

How did you resolve it? I have same problem
