### ISSUE TITLE
[React 16] hydrate method

### ISSUE THREAD

**Issue by jeans11** [necolas/react-native-web#733]
**Do you want to request a *feature* or report a *bug*?**
_Feature_

**What is the current behavior?**
`AppRegistry.runApplication` call `ReactDom.render` method.

**What is the expected behavior?**
Call `ReactDom.hydrate` method when React 16 is used.

**Comment by necolas** [comment]
Are there any side-effects from calling `hydrate` if the app wasn't SSR-ed?

**Comment by MoOx** [comment]
Not from my experience. hydrate just tells React to "try to reuse existing markup as much as possible".

**Comment by codejamninja** [comment]
I'm still getting the hydrate error, and I'm using the newest version of react-native-web.

**Comment by MoOx** [comment]
hydrate is used in NODE_ENV production only https://github.com/necolas/react-native-web/blob/7a3a9a5c3ffdbf096150cc940ef542d96af0589e/packages/react-native-web/src/exports/AppRegistry/renderApplication.js#L18

**Comment by codejamninja** [comment]
Ah thanks, why is that?
