### ISSUE TITLE
AppRegistry: add keys to returned style array

### ISSUE THREAD

**Issue by jaydenseric** [necolas/react-native-web#734]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

<img width="755" alt="screen shot 2017-12-15 at 12 43 24 pm" src="https://user-images.githubusercontent.com/1754873/34026259-d4166366-e1a8-11e7-89ad-25b5251d1cd4.png">

There should be a `key` prop on each `<style>` in the array generated [here](https://github.com/necolas/react-native-web/blob/0.1.16/src/apis/AppRegistry/renderApplication.js#L41). Perhaps the `sheet.id` could be used?

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. Render `stylesheets` provided from `AppRegistry.getApplication`. I'm doing this in Next.js SSR.

**What is the expected behavior?**

It renders without React warnings.

**Environment (include versions). Did this work in previous versions?**

* OS: macOS 10.13.2
* Device: MacBook Pro
* Browser: Chrome
* React Native for Web (version): 0.1.16
* React (version): 16.2.0

**Comment by necolas** [comment]
Are you using `ReactDOMServer.renderToStaticMarkup` as recommended? I don't think React cares about keys in that case. I'll add them anyway.
