### ISSUE TITLE
Replace inline-style-prefixer with light version

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#74]
Using `prefixAll` from inline-style-prefixer is simpler for universal rendering, and the difference in gzipped CSS is not substantial. It also makes it possible to drop the caniuse data and bowser dependencies, which will reduce the size of the bundle.

cc @rofrischmann

**Comment by rofrischmann** [comment]
Do you have a real-life example backing this? I'd like to see if the reduced bundle size actually is somewhat equal to the additional prefixed properties.

I might consider using the `prefixAll` for my own projects as well!
We could have a separate package which only does the prefixAll in general.

**Comment by necolas** [comment]
The prefixed properties don't end up in the bundle so dropping the larger dependencies saves a few KB in the bundle. The gzipped size of the CSS generated by RNW is very small and not adversely affected by including all prefixes

**Comment by rofrischmann** [comment]
Oh yeah that seems legit. I was playing a bit with pure prefixAll and I guess I'll switch too.
I thought about pushing an alternative package called `static-inline-style-prefixer` which only includes the prefixAll with simplified plugins. Or what did you think about?

**Comment by necolas** [comment]
Yeah I'd use that. Thanks

**Comment by rofrischmann** [comment]
How about separating the `prefixAll` from the `Prefixer` instance, e.g. that you could use
```javascript
import { prefixAll } from 'inline-style-prefixer'
```
This would keep updates to both in sync (otherwise I'd have to update both if something changes).
We could then also do a much simpler prefixAll as it is now. 
Tree Shaking which ships with build tools like Rollup or Webpack 2 would help to bundle **only** the `prefixAll` in the end.

**Comment by necolas** [comment]
Yeah that will help in the future. Can probably wait for webpack 2 if it's not far off shipping

**Comment by necolas** [comment]
Oh, relying on webpack/rollup won't work when importing transpiled-to-es5 modules from npm. But it could help you automate the publishing of 2 separate packages from a single repo

**Comment by rofrischmann** [comment]
Ya. Just figured that out :( We have to wait until we can npm publish ES2015 code I guess.
I am right now extracting the prefixAll functionality into a new repository and then include that one into the other as fallback, so you could just use the prefixAll I guess. 

It's almost done :P

**Comment by rofrischmann** [comment]
https://www.npmjs.com/package/inline-style-prefix-all Here we go :P

**Comment by necolas** [comment]
Thanks for doing this. It reduced the gzipped bundle size by 5.4 KB.

**Comment by rofrischmann** [comment]
Nice once :P I also switched to this because of the bundle size^^
