### ISSUE TITLE
make a readme Awesome React Native Web

### ISSUE THREAD

**Issue by amorenew** [necolas/react-native-web#742]
**Do you want to request a *feature* or report a *bug*?**
feature

I wonder if you can make a readme for compatible components like 'Linear gradient, Elevation, etc'.
Also, kick starters generators, popular apps that use RNW.
So instead of searching on the web, we can just check that readme.
you can make it or me then you put the link in the main readme.
what do you think?

**Comment by necolas** [comment]
I've updated the readme in this branch: https://github.com/necolas/react-native-web/tree/nicolas/monorepo

At this stage I'd rather not maintain lists of packages - every time I've tried they have gone out-of-date and those packages stopped being maintained. The reactjs website maintains a good list of starter kits.

**Comment by amorenew** [comment]
@necolas thank you for your time to make this awesome library.

I extracted Linear gradient, Elevation lib as 1 file js for each in my project.
and I think as much I practice and others do the same we could have a great list of awesome items which we can share and help each other.
Just I want you to **mention** my list repo so all can share their cross-platform components so we save time for everyone.
I hope you try it and you will be amazed how much it will be useful for all developers.

**Comment by necolas** [comment]
What's the link to the repo?

**Comment by amorenew** [comment]
@necolas 
Link: https://github.com/amorenew/Awesome-React-Native-Web
it's empty now I will add more data in this week.
I will close the issue and when I am ready I will reopen this issue and tell you to check it.

**Comment by necolas** [comment]
I encourage you to continue with your project but I will not be promoting it here. You may want to reach out to the people maintaining similar projects here:
https://github.com/react-native-web-community/contributing/blob/master/README.md

**Comment by blackbing** [comment]
I created a repo and list some repo I have used in real world. pr wellcome.
https://github.com/blackbing/awesome-react-native-web
