### ISSUE TITLE
Support useNativeDriver on Animated API

### ISSUE THREAD

**Issue by jbovenschen** [necolas/react-native-web#744]
**Do you want to request a *feature* or report a *bug*?**
I want to report a feature.

**What is the current behavior?**

Currently all animations build with the Animated API are running on the Javascript thread, this can have a lot of impact on the performance on slower devices.

**What is the expected behavior?**

If supported it would be nice to use [element.animate()](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate) for changes within the dom styles so it uses the native composite thread within the browser.

Because you did use the current Animated implementation from the react-native repo, it would for me be a nice addition to react-native-web, and I am curious if you are willing to accept an addition like this.

I am currently experimenting with implementing this kind of behaviour, will keep you up to date how it would work out.

**Comment by necolas** [comment]
Yeah, I'm happy to review PRs looking to do this. Going to close this issue as it's listed in #527 as part of R&D. Thanks!
