### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by amorenew** [necolas/react-native-web#747]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
You may need an appropriate loader to handle this file type
the link to my bug is here 
https://github.com/react-native-web-community/react-native-web-linear-gradient/issues/1
or stackoverflow
https://stackoverflow.com/questions/48034538/how-to-solve-this-error-you-may-need-an-appropriate-loader-to-handle-this-file-t
may someone can help me here because it is related to RNW
I will give **100 points** of my StackOverflow to who will fix it to me

**Comment by necolas** [comment]
Not a problem with this library. Commented on the other ticket
