### ISSUE TITLE
Importing components from external directory fails

### ISSUE THREAD

**Issue by dave-irvine** [necolas/react-native-web#749]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If I have components in my react-native-web directory, everything works fine.

However, if I take those components and move them in the file structure, to say `shared-components/` directory, and then use npm to `link` to that directory, when I think import those same components they fail to parse.

     project_dir/src/components/TextButton/TextButton.js
     shared-components/TextButton/TextButton.js
     symlink: project_dir/node_modules/shared-components -> ../shared-components

../shared-components/TextButton/TextButton.js
Module parse failed: Unexpected token (10:49)
You may need an appropriate loader to handle this file type.

**What is the expected behavior?**

I'd expect to be able to include components from somewhere else, in this case a different directory, or for example, an npm package.

**Environment (include versions). Did this work in previous versions?**

* OS: OSX
* Device: Macbook Pro
* Browser: Chrome
* React Native for Web (version): Latest
* React (version): Latest

**Comment by dave-irvine** [comment]
As a quick follow up, to make sure it wasn't something weird with symlinks, I've also tried using this component: https://github.com/newsuk/times-components/tree/master/packages/caption

So:
    
    npm i @times-components/caption

    import Caption from "@times-components/caption";

./node_modules/@times-components/caption/caption.js
Module parse failed: Unexpected token (28:4)
You may need an appropriate loader to handle this file type.

**Comment by dave-irvine** [comment]
Ah, I imagine this is the problem: https://github.com/react-native-web-community/react-native-web-linear-gradient/issues/1#issuecomment-354660128

Which I suppose makes sense but totally threw me because the project is obviously able to transpile code found within its own subdirectories.

Is there a way I can tell babel I want to transpile x,y,z import? Bearing in mind I used create-react-app so I don't have any control of babel config :/

**Comment by necolas** [comment]
I don't know if create react app let's you do that. I think all your files need to be under 'src'. People should be publishing packages of compiled code to avoid this problem. You might have to eject CRA 

I'll look into this with the team making CRA when I go to update the RNW support. Thanks

**Comment by dave-irvine** [comment]
@necolas thanks for the reply.

If I go down the route of having my "shared-components" published as compiled, is that going to cause further issues when I try to use them in react-native as opposed to react-native-web?

**Comment by necolas** [comment]
It shouldn't cause any problems
