### ISSUE TITLE
Can this be used to allow access to a RN tablet app through the browser?

### ISSUE THREAD

**Issue by raarts** [necolas/react-native-web#750]
**Do you want to request a *feature* or report a *bug*?**

I guess a bug in the docs.

**What is the current behavior?**

I'd like to know more about how to use this library. My use case: I want to write a RN app (using Expo), which is fit for both phones & tablets. I also want the tablet version to be usable through a browser. 

Can this be accomplished by this library, and if so, how do I configure it with a fresh create-react-native-app setup? 

Which problems will most likely be encountered if I go this path?

**Comment by necolas** [comment]
You need to set up a react web app. The getting started guide has an example setup. Then point the web entry to an app made from the tablet Components

**Comment by raarts** [comment]
I'm sorry for not making myself clear. I followed the Getting Started Guide as follows:

    create-react-native-app test-with-web
    cd test-with-web
    yarn start

and in another terminal:

    yarn run ios

This worked. Next I did:

    yarn add react-native-web

No problems, but how to continue from here? Pointing my browser at localhost:19000 or 19001 (where node was listening on) didn't give me a clue.

I know the guide recommends using create-react-app, but I specifically want to develop a RN app using Expo, and using the app from a browser, where the browser renders the tablet version of my mobile app.

**Comment by necolas** [comment]
There's more info here https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md

**Comment by raarts** [comment]
If someone encounters the same problems as I had. Here's my solution, I wrote a bash script:
[create-expo-web](https://gist.github.com/raarts/8b8637a2a2a04a2ce54214554b1b3468), that takes a directory name, and creates an expo blank template project, with react-native-web support.

I expect more problems going forward, but at least this works as a starting point. It works from ios, android, web, and it builds and deploys correctly.
