### ISSUE TITLE
babel-plugin-react-native-web generic for all RNW community

### ISSUE THREAD

**Issue by amorenew** [necolas/react-native-web#752]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
alias for libraries is made manually 

**What is the expected behavior?**
babel-plugin-react-native-web plugin does not do an alias for the only RNW but for RNW community libraries or a provide a simple guide for RNW community so they can have their own babel plugin.
However that it is better to be one dependency.

**Comment by necolas** [comment]
The plugin doesn't just alias the package, otherwise I'd rely on Babel's alias plugin or a bundler alias, which is what these other packages should do. Better yet would be to add the web implementation to the package with the native implementations
