### ISSUE TITLE
Automate precommit hook

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#755]
**Do you want to request a *feature* or report a *bug*?**

Developer feature

**What is the current behavior?**

When we contribute to RNW, we have to run `yarn precommit` by hand

**What is the expected behavior?**

I would expect that this step is automated via something like husky (which setup precommit hook as soon as you npm/yarn install it - so transparent for contributor).

---

I can setup that in a PR if you want.

**Comment by necolas** [comment]
Yeah that sounds good. Didn't do it before because it wasn't possible to do with Twitter's version of git
