### ISSUE TITLE
StyleSheet: word-break property to wrap long continuous strings

### ISSUE THREAD

**Issue by joncursi** [necolas/react-native-web#760]
**Do you want to request a *feature* or report a *bug*?**

Both.

**What is the current behavior?**

I have a very long string that I need to wrap to multiple lines, but it looks like this CSS property is not supported (`word-break: all`?).

When this component is rendered on native, the text wraps as desired:

![img_5200](https://user-images.githubusercontent.com/4974609/34755403-c729b41c-f591-11e7-8891-c758fecc74d7.PNG)

When rendered on web, the text will not wrap to multiple lines, which causes the component to break out of the layout and create scrollbars.

Demo: https://cheddur-rgsymrxmda.now.sh/story/7NcMectnqEW4QivYj -> the cryptocurrency address.

If you shrink your viewport, you see:

![screen_shot_2018-01-09_at_11_03_36_pm](https://user-images.githubusercontent.com/4974609/34755423-e8025572-f591-11e7-9db1-3e2aaa280650.png)

* Browser: all
* React Native for Web (version): 0.1.16
* React (version): 16.2.0

**Comment by necolas** [comment]
You app doesn't load. Please can you create a simple test case from the glitch demo included in the issue template

**Comment by necolas** [comment]
Going to close this if there's no update soon

**Comment by joncursi** [comment]
@necolas here's another example, this one should load:

https://staging.cheddur.com/story/stB4Lr2Nd9SNL4NFE

Long continuous strings don't seem to wrap to a new line when rendered with `react-native-web`, though they do wrap on `react-native` itself.

**Comment by necolas** [comment]
Please can you make a reduced test case on glitch

**Comment by dmeehan1968** [comment]
In case its of help, as it seems related, I had problems with getting a deeply nested ```Text``` node wrapping correctly. I got it working on Native, but couldn't figure it out on web without a lot of head scratch.  This comment details what worked for me.

https://github.com/facebook/react-native/issues/1438#issuecomment-362949682

**Comment by necolas** [comment]
What's an example of code that produces the issue?

**Comment by export-mike** [comment]
@necolas it appears a single long string that doesn't have spaces causes this issue.

**Comment by necolas** [comment]
I'm just asking for someone to provide a reduced test case on codesandbox, as is mentioned as being required in the issue template. Help me to help you.

**Comment by airandfingers** [comment]
Hi @necolas, I'm seeing this issue now, though I could just be using Flexbox incorrectly.

Here's a reduced case (I could reduce it a bit more, but this shows the Flexbox context I'm operating in): https://codesandbox.io/embed/7wlorrx3p1

**Comment by airandfingers** [comment]
Update: [This SO question](https://stackoverflow.com/a/39480715/877682) pointed me to the answer: `flexShrink: 1` fixes this.

Fixed reduced case: https://codesandbox.io/embed/7wlorrx3p1

**Comment by redefinered** [comment]
@airandfingers that is not the issue. I think just by reading it is pretty easy to understand. It's the long words that does not break and goes off the screen.

**Comment by redefinered** [comment]
to replicate the issue put this component in render <Text>ldjahflkasdjhflakshjflaksjhdflakshdjflaksjhdfalksjdhflaskdfhjlaskdfjhaslkdfhjlaskjdfhlaskjhdfajsdhflaksjdhflaskdfhalskdfhj</Text>

**Comment by redefinered** [comment]
@necolas

**Comment by redefinered** [comment]
It's too easy to understand, our brains are just too complicated.

**Comment by jtomaszewski** [comment]
So `word-break` isn't supported in `react-native-web` at this moment at all? I'm sure it should be supported. That's the only way to wrap long words (like explained above), besides CSS hyphenation maybe. Why is this closed?

**Comment by jtomaszewski** [comment]
This issue should be reopen. There should be a way to specify `word-break: break-word` on the web platform. That's the only way to force long words to be broken on the web. (Unless you know a better cross-browser-platform way to do it, I'm happy to learn. `flex-shrink` won't do it).

Currently our workaround is a bit troublesome and goes like this:

1. Add global `<style>` to our index.html with the following:

  ```css
  [word-break="break-word"] {
    word-break: break-word;
  }
  ```

2. In js code, using `ref` and `setNativeProps` add the `[word-break="break-word"]` attribute to the element like this:

```tsx
  const viewRef = useRef<View>(null);
  useEffect(() => {
    if (Platform.OS !== "web" || !containerRef.current) return;
    viewRef.current.setNativeProps({ ["word-break"]: "break-word" });
  }, [viewRef]);

  return (
    <View ref={viewRef}>...</View>
  );
```

**Comment by nicolaslazzos** [comment]
Or you can simply add `{ wordBreak: "break-word" }` to the `View` style.

**Comment by Abhishek0706** [comment]
why are we setting native props to view and not text

**Comment by srinivasan-fh** [comment]
1.Add global <style> to our index.html with the following:
<style>
#work-break-my-text-view {
   word-break: break-word;
}
</style>

2. Add testID in the View:
<View testId='work-break-my-text-view'></View>
