### ISSUE TITLE
Use library to convert react-native hierarchy to html strings

### ISSUE THREAD

**Issue by alexhuiculescu** [necolas/react-native-web#761]
**Do you want to request a *feature* or report a *bug*?**
feature 
**What is the current behavior?**
 -
**What is the expected behavior?**

Is there a way to use react-native-web to convert react-native pages to html strings ? I know this library maps react-native views to web views, and I would like to use only that fuctionality

**Environment (include versions). Did this work in previous versions?**
- 

* OS:
* Device:
* Browser:
* React Native for Web (version):
* React (version):

**Comment by MoOx** [comment]
You will find your answer here https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#server-side-rendering

**Comment by alexhuiculescu** [comment]
Does ReactDOMServer.renderToString(element) works on react-native mobile ?
I do not intend to run my app on web, only for mobile

**Comment by MoOx** [comment]
I don't understand your need. What it the point of serving HTML is if it's not for a web usage?

**Comment by alexhuiculescu** [comment]
To convert react-native elements into html.  Just for the conversion

**Comment by necolas** [comment]
ReactDOMServer does this
