### ISSUE TITLE
"Can't find variable process" in Android emulator after attempting to add React Native Web to existing React Native Project

### ISSUE THREAD

**Issue by tomalexhughes** [necolas/react-native-web#763]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have an existing React Native app that I want to use React Native Web for, to have both a web and mobile app.

The existing app works within the Android emulator, until adding configuration for React Native Web. The changes I have made include adding a Webpack config, and installing react-dom and react-native-web, as well as adding the 'react-native-web' Babel plugin.

Running my Webpack config outputs a bundle that succesfully compiles my Native code to a web app that works as expected in the browser. however running `react-native run-android` will succesfully build the app however the app shows [this error](https://i.imgur.com/RfI3xxy.png), "Can't find variable process". 

Source code can be found in this [repository](https://github.com/tomalexhughes/Grace), with commit history showing before and after adding React Native Web.

**Steps To Reproduce**

1. Clone down the repository.
2. Run `npm install`.
3. Run `npm start -- --reset-cache`.
4. Run `npm run webpack` to compile bundle to static assets for web.
5. Run `react-native run-android` to start an Android emulator.

**What is the expected behavior?**
Emulator should display app.

**Environment (include versions). Did this work in previous versions?**

* OS: Debian 9 (Stretch)
* Device: Android Emulator
* Browser: N/A
* React Native for Web (version): 0.3.0
* React (version): 16.2
* React Native CLI: 2.0.1
* React Native: 0.52.0

Apologies if there are incompatibility's between versions, I realise there are some issues that were caused by this, however I can't see anything in the README that mentions compatible versions anymore, as far as I'm aware everything is up to date.

Could this be due to not running a server, and instead serving static content, and therefore not having a process variable declared?

**Comment by necolas** [comment]
You should use different Babel configuration for native and web. You don't want to run the web plugins when building native
