### ISSUE TITLE
Approach for preview / non-standard CSS properties

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#765]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When a CSS property that is not included by Stylesheet is passed, an error is thrown into the console. It's unclear at what point a CSS property should be added to Stylesheet.

**What is the expected behavior?**
I wanted to open this for discussion and recommendations about what approach we should take in cases of new CSS properties, especially in the cases where they are not fully standard yet or are perhaps browser specific.

`overscroll-behavior` is a good example we ran into recently. A few months ago, [Chrome added](https://developers.google.com/web/updates/2017/11/overscroll-behavior) CSS functionality to allow people to control scroll bubbling. It seems advantageous for Twitter Lite to use this to improve the experience of certain dropdowns and pages. However, the property isn't included in RNW, so we're hesitant to use it with Stylesheet.

What is the best approach for cases like this that may not have a good React Native equivalent? Just add them to RNW? Wait for them to be standards, in which case perhaps we could statically configure Stylesheet with properties we want to allow? Interested to hear if others have run into this and what the recommended approach should be. Thanks!

**Comment by necolas** [comment]
I just add them as needed.

**Comment by necolas** [comment]
^ does this look good to you?

**Comment by comp615** [comment]
Beauty. I'll just submit these as they come up in the future. Got sidetracked with devEnv stuff!
