### ISSUE TITLE
Be able to override resizeMode with backgroundSize style to support 2x bg images

### ISSUE THREAD

**Issue by madhaze** [necolas/react-native-web#766]
**What is the current behavior?**
Currently backgroundSize isn't a supported prop type for images. Get `Invalid props.style key 'backgroundSize'` resizeMode options always win and backgroundSize is never able to output in styles.

**What is the expected behavior?**
Need to be able to set backgroundSize: and pass a string to be able to support 2x images at specific sizes like `backgroundSize: auto 300px` for a 600px height image to display at half size/2x resolution.

**Comment by necolas** [comment]
You can use a `View` to do that if you need to

**Comment by madhaze** [comment]
Thanks, I don't know how I didn't think of that.
