### ISSUE TITLE
Example of next.js and lerna

### ISSUE THREAD

**Issue by kmalakoff** [necolas/react-native-web#768]
I have spent quite a bit of time trying various things to get react-native-web working with next.js and lerna, but haven't been able to crack it. 

1) webpack aliases
2) adding the lerna modules following a approaches like: https://github.com/zeit/next.js/issues/858
3) babel module aliasing

No dice...does anyone have a working version of react-native-web with next.js and lerna (for shareable components across web and mobile).

**Comment by necolas** [comment]
There's a babel plugin for RNW as mentioned in the docs. You should use that. I don't know much about next.js but it looks like you can make your own renderer as that thread describes, and using the APIs documented both here and in next.js.

I don't see how lerna is related to this.

**Comment by kmalakoff** [comment]
The instructions in the documents using the babel-loader plugin & preset unfortunately don't work with next.js and lerna. 

Does anyone have a working next.js project with react-native-web and lerna? If so, please respond to this thread with a link to an example project or instructions for configuring. Thank you!

**Comment by dcalhoun** [comment]
@kmalakoff I've added a [react-native-web example](https://github.com/zeit/next.js/pull/3781#issuecomment-365234989) to the Next.js repository.

**Comment by kmalakoff** [comment]
Thank you @dcalhoun. 

Unfortunately, getting Next.js and react-native-web working together isn't a problem for me. It's the lerna piece that throws the spanner into the works. 

You can see [here](https://github.com/zeit/next.js/issues/858#issuecomment-359195296) what I tried, but I ended up giving up on lerna and going with straight webpack.
