### ISSUE TITLE
Resolving components

### ISSUE THREAD

**Issue by Ar4ics** [necolas/react-native-web#769]
**Do you want to request a *feature* or report a *bug*?**
Module not found: Error: Can't resolve 'react-native-web/dist/exports/Alert'
Module not found: Error: Can't resolve 'react-native-web/dist/components/View'
**What is the current behavior?**
Incorrect resolving
**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. Install react-native and react-native-web
2. Add webpack config
3. Run bundling

**What is the expected behavior?**
Correct resolving

**Environment (include versions). Did this work in previous versions?**
Yes
* OS: Windows 10
* Device:
* Browser: Chrome 63
* React Native for Web (version): 0.3
* React (version): 16.2.0

**Comment by necolas** [comment]
Alert has never been included. Not sure what is going on with View, maybe some babel/webpack caching?

**Comment by Ar4ics** [comment]
Sure. But it works only when cacheDirectory: false. When its true the error was thrown.

**Comment by necolas** [comment]
You need to wipe out the compiler cache on your computer so a new cache is created

**Comment by Ar4ics** [comment]
thanks
