### ISSUE TITLE
Support React-Native 0.50?

### ISSUE THREAD

**Issue by gaoxiaosong** [necolas/react-native-web#770]
I want to know if it is support react-native 0.50.x ? I have got a lot errors during running it.

Error message is within format:

ERROR in ./node_modules/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Can't resolve 'XXXXXXXX' in '/Users/shallot/Documents/RNModulesNew/node_modules/react-native/Libraries/react-native'
 @ ./node_modules/react-native/Libraries/react-native/react-native-implementation.js 19:35-63
 @........

Here XXXXXXXX is:

- AccessibilityInfo
- ActionSheetIOS
- ActivityIndicator
- Alert
- and any component in react-native-implementation.js

I follow the Guide on this repository and do it on my project. Use follow command

`./node_modules/.bin/webpack-dev-server -d --config/web/webpack.config.js --inline --hot --colors`

Get the errors on the first importing 'react-native' position. My project is no error running on both iOS and Android.

My package.json is:

"devDependencies": {
    "@babel/core": "^7.0.0-beta.37",
    "@babel/plugin-transform-regenerator": "^7.0.0-beta.37",
    "babel-eslint": "^8.0.2",
    "babel-jest": "22.0.4",
    "babel-loader": "^7.1.2",
    "babel-plugin-react-native-web": "^0.3.0",
    "babel-preset-react-native": "^4.0.0",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.11.0",
    "eslint-plugin-react": "^7.4.0",
    "eslint-plugin-react-native": "^3.1.0",
    "jest-cli": "^22.0.5",
    "path": "^0.12.7",
    "react-addons-test-utils": "16.0.0-alpha.3",
    "rn-packager": "^0.12.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.11.0"
  },
  "dependencies": {
    "immutable": "^3.8.2",
    "prop-types": "^15.6.0",
    "react": "16.0.0",
    "react-dom": "16.0.0",
    "react-native": "0.50.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fs": "^2.8.1",
    "react-native-img-cache": "^1.5.0",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-orientation": "^3.1.0",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-sortable-listview": "^0.2.6",
    "react-native-swipe-list-view": "^0.4.6",
    "react-native-web": "^0.3.0",
    "react-navigation": "^1.0.0-beta.13",
  },

* OS: Mac OS X 10.13.2
* Device: Web
* Browser: Safari/Chrome
* React Native for Web (version): 0.3.0
* React (version): 16.0.0

**Comment by Ar4ics** [comment]
disable cache in babel loader settings

**Comment by MoOx** [comment]
You will see here the available list of exported modules: https://github.com/necolas/react-native-web/tree/master/packages/react-native-web/src/exports

You will quickly see what's available and what is not. 

I guess it make sense that native only modules (*IOS & *Android) won't be implemented.

**Comment by necolas** [comment]
Plus those errors are pointing to the react-native package which suggests you haven't aliased it to react-native-web using the babel plugin
