### ISSUE TITLE
Alert proposal: dialog polyfill

### ISSUE THREAD

**Issue by paularmstrong** [necolas/react-native-web#771]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The react-native Alert API is unimplemented in react-native-web

Since browser `window.alert` and `window.confirm` are not sufficient for handling the `Alert` API for react-native, would adding [GoogleChrome/dialog-polyfill](https://github.com/GoogleChrome/dialog-polyfill) be a sufficient addition? Alternatively, RNW could add Alert with a warning that gives a URL to some instructions on implementing the polyfill and your own Alert alternative.

**Comment by necolas** [comment]
I don't think dialog helps with this. No plans to support module injection / aliasing in RNW either. Not everything is implemented yet but I'll look into the modals via portals eventually
