### ISSUE TITLE
Options text missing from iOS picker

### ISSUE THREAD

**Issue by terryttsai** [necolas/react-native-web#774]
## Steps to reproduce

1. Using an iOS 10 or greater device, load a webpage containing the React Native Web Picker component, for example [https://necolas.github.io/react-native-web/storybook/?selectedKind=Components&selectedStory=Picker&full=0&addons=0&stories=1&panelRight=0](url)
2. Click on the Picker component

## Expected behavior
1. I expect to see an iOS Picker component with all my options in it.

## Actual behavior
1. I see an empty iOS Picker component.

![img_0001](https://user-images.githubusercontent.com/5040739/35074668-c7ce8bf0-fba3-11e7-8a4d-aa1423acc1c5.PNG)

![img_0082](https://user-images.githubusercontent.com/5040739/35074644-b435ef7a-fba3-11e7-93ba-f0c11b78288e.PNG)

## Cause of problem
We inspected the DOM and found that the html option elements don't have text in them. iOS Safari does not seem to render the "label" attribute in `<option/>`. Instead it expects a text node inside it. 

For example, if I take this line: 

`<option label="Sourcerer's Stone" value="book-1"></option>`

and change it to this line: 

`<option label="Sourcerer's Stone" value="book-1">Stone</option>`

Then I see "Stone" in the Picker. 

**After change:**
![img_0084](https://user-images.githubusercontent.com/5040739/35074647-b73edc54-fba3-11e7-94a7-9fdf82aaeac6.PNG)

## Environment (include versions)

* OS: iOS 10.0.2 and 11.0.2
* Device: iPhone 5s and iPad Mini
* Browser: iOS Safari
* React Native for Web (version): 0.2.0

**Comment by terryttsai** [comment]
Looks like a possible fix would be to pass the value in as a child in line 23 in https://github.com/necolas/react-native-web/blob/e0d6ffa4a0d97bf8033bc0e55cb61e5b72f0fe72/packages/react-native-web/src/exports/Picker/PickerItem.js ?

**Comment by terryttsai** [comment]
Like `return createElement('option', { label, testID, value }, label);`

**Comment by necolas** [comment]
Thanks for spotting this, I missed it while reviewing the PR.

**Comment by terryttsai** [comment]
Thanks for the quick fix @necolas! Hope a release with this fix will be going out soon?
