### ISSUE TITLE
babel-plugin-react-native-web badcase

### ISSUE THREAD

**Issue by hushicai** [necolas/react-native-web#775]
It seems that `babel-plugin-react-native-web` can not cover this case:

```javascript
var RNDeviceInfo = require('react-native').NativeModules.RNDeviceInfo;
```

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.0
  react-native-web:^0.3.1 => 0.3.1

webpack-dev-server errors:

> ERROR in ./node_modules/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Can't resolve 'takeSnapshot' in '/Users/hushicai/data/work/rnmanager/node_modules/react-native/Libraries/react-native'
 @ ./node_modules/react-native/Libraries/react-native/react-native-implementation.js 115:30-53
 @ ./node_modules/react-native-device-info/deviceinfo.js
 @ ./app/pages/app.js
 @ ./app/root.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

**Comment by necolas** [comment]
That's right, it can't convert those kind of require statements

**Comment by hushicai** [comment]
so can I use webpack `resolve.alias` to fix this case?

**Comment by necolas** [comment]
You should really move the use of `RNDeviceInfo` out of the file that is being loaded for web. Native modules aren't there on web.

**Comment by hushicai** [comment]
Is there a recommended way to patch package that is not supported by official `react-native-web`?

**Comment by necolas** [comment]
Not at the moment

**Comment by hushicai** [comment]
How about this case:

```javascript
var ReactNative = require('react-native');
```

`babel-plugin-react-native-web` also  seems not handle it.

**Comment by necolas** [comment]
What do you mean? There's a unit test for that https://github.com/necolas/react-native-web/blob/master/packages/babel-plugin-react-native-web/src/__tests__/index-test.js

**Comment by hushicai** [comment]
This is an `VariableDeclaration`:

```javascript
var ReactNative = require('react-native');
```

but `babel-plugin-react-native-web` can not convert it to `react-native-web/dist/index`.

AST:

![image](https://user-images.githubusercontent.com/1249423/35136867-1d6042b0-fd21-11e7-95e2-565dd64828ab.png)

`isReactNativeRequire` can not recognize it:

![image](https://user-images.githubusercontent.com/1249423/35136905-53803d8c-fd21-11e7-9328-a870772d6427.png)

Because `t.isObjectPattern(id)` is false.

**Comment by necolas** [comment]
I see, thanks. Want to put a PR together?
