### ISSUE TITLE
Picker not working when selectedValue is not null or undefined

### ISSUE THREAD

**Issue by adrianicv** [necolas/react-native-web#776]
**Do you want to request a *feature* or report a *bug*?**
A bug.
**What is the current behavior?**
 [Demo in Glitch of the bug](https://glitch.com/edit/#!/gorgeous-play)

1. Create a picker with several Items. Set the selected item's value to not null nor undefined
2. Change the selected value.
3. Once you click another value, the selection doesn't change.

**What is the expected behavior?**
1. Create a picker with several Items. Set the selected item's value to not null nor undefined
2. Change the selected value.
3. Once you click another value, the selection must change.

**Environment (include versions). Did this work in previous versions?**

* OS: Ubuntu 16.04
* Device: Acer Laptop
* Browser: Chrome Version 61.0.3163.100 (Build oficial) (64 bits)
* React Native for Web (version): 0.3.1
* React (version): 16.0.0

**Comment by necolas** [comment]
The picker is a controlled component. You can see how to use it by looking at the code in the storybook (/website) or benchmarks (/packages/benchmarks)
