### ISSUE TITLE
babel require default

### ISSUE THREAD

**Issue by hushicai** [necolas/react-native-web#786]
It seams that babel 6 has been killed `CommonJS default export behaviour` , as described in babel/babel#2212.

For now, babel-plugin-react-native-web has transformed 
`const {Stylesheet} = require('react-native')` 
to 
`const Stylesheet = require('react-native/dist/exports/Stylesheet')`.

But `Sheetsheet` is indeed a default export!

so, when I `require('react-native/dist/exports/Stylesheet')`, I will get `{default: Stylesheet, _esModules: true}`, which will cause errors:

![image](https://user-images.githubusercontent.com/1249423/35215306-cf4f9bcc-ff9e-11e7-9655-eb696e8e9ad2.png)

Is there some ideas to fix this problem?

**Comment by hushicai** [comment]
I would want to change `require` to `es6 modules`, like this:

```javascript
import StyleSheet from 'react-native/dist/exports/Stylesheet'
```

Then this will be handled corrrectly by babel.

Do you think so?

**Comment by hushicai** [comment]
may like this:

```javascript
exports[`require "react-native" 1`] = `
"
const ReactNative = require('react-native');
const { View } = require('react-native');
const {  StyleSheet, TouchableOpacity } = require('react-native');

      ↓ ↓ ↓ ↓ ↓ ↓

import ReactNative from 'react-native-web/dist/index';
import View from 'react-native-web/dist/exports/View';
import StyleSheet from 'react-native-web/dist/exports/StyleSheet';
import TouchableOpacity from 'react-native-web/dist/exports/TouchableOpacity';
"
`;
```

**Comment by necolas** [comment]
I don't know if Babel will guarantee transforming those back to `require` if the commonjs plugin is also included.

**Comment by hushicai** [comment]
with commonjs plugin, import will be transformed to:

```javascript

exports[`require "react-native" 1`] = `
"
const ReactNative = require('react-native');
const { View } = require('react-native');
const {  StyleSheet, TouchableOpacity } = require('react-native');

      ↓ ↓ ↓ ↓ ↓ ↓

'use strict';

var _index = require('react-native-web/dist/index');

var _index2 = _interopRequireDefault(_index);

var _View = require('react-native-web/dist/exports/View');

var _View2 = _interopRequireDefault(_View);

var _StyleSheet = require('react-native-web/dist/exports/StyleSheet');

var _StyleSheet2 = _interopRequireDefault(_StyleSheet);

var _TouchableOpacity = require('react-native-web/dist/exports/TouchableOpacity');

var _TouchableOpacity2 = _interopRequireDefault(_TouchableOpacity);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
"
`;
```

**Comment by virtualirfan** [comment]
I get the same issue except for a function of ReactNativePropRegistry.

ReactNativePropRegistry.register is not a function but ReactNativePropRegistry.default.register is.

Any thoughts on whether you guys have converged on a solution?
/cc: @taimuri

**Comment by necolas** [comment]
ReactNativePropRegistry is not part of the public API. What are you importing that produces that error?
