### ISSUE TITLE
babel-plugin-react-native-web doesn't work with bs-react-native

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#787]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

1. Use resonml + bs-react-native + bsbconfig using `"package-specs": {"module": "es6"},`
2. Use babel-plugin-react-native-web
3. Compile with webpack... Boom

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-native' in '/Users/MoOx/Sync/Development/.../node_modules/bs-react-native/lib/es6/src/components'
```

⚠️ It's probably due to the fact that bucklescript generate this kind of import (when using es6 module as mentionned above)

```
import * as ReactNative from "react-native";
```

**What is the expected behavior?**

It should work

**Environment (include versions). Did this work in previous versions?**

-

---

I will try to investigate tomorrow and produce a patch if possible.

**Comment by necolas** [comment]
What is the input that bucklescript converts to this?

```
import * as ReactNative from "react-native";
```

**Comment by MoOx** [comment]
No real input. It's a conjunction of a bsbconfig (`bs-dependencies`) + usage (could be `open BsReactNative;` or directly the usage of `BsReactNative.SomeAPIorComponent`).
I guess we should just care of the JS consumed by babel.... BTW I am thinking that babel should not be required as BS produce very performant ES5 code already. Will try with alias then...

**Comment by necolas** [comment]
The babel plugin doesn't do any optimizations, it rewrites imports to prevent the entire library being bundled (and change 'react-native' to 'react-native-web'). Probably doesn't work on that type of import statement. But even if it did, you'd end up bundling the entire library. Can bs be made to produce js modules that explicitly import only what they need?

**Comment by MoOx** [comment]
Not sure if it's capable.

From this code

```re
[@bs.module "react-native"] external t : t = "StyleSheet";
```

We end up with this

```js
import * as ReactNative from "react-native";
/* later */

/* ... */ ReactNative.StyleSheet...
```

Will see if this can be improved.

**Comment by MoOx** [comment]
Not possible ATM https://github.com/BuckleScript/bucklescript/issues/2113

**Comment by MoOx** [comment]
BTW, code produced by BS should not be "babelified" as it's already es5 code, vey low level and performant (unless you keep es6 module and consume with webpack to get tree shaking or something like that - which is not profitable atm as explained above).
So babel plugin is not the silver bullet when you use reasonml (as you don't have to use babel) :(

**Comment by necolas** [comment]
Sounds like an issue for bucklescript to fix first.

You don't have to use babel but if you do you can rewrite the imports in the `*.bs.js` files (without doing anything else). Maybe one day tree-shaking will actually work too!

**Comment by MoOx** [comment]
At the end it was a PEBKAC issue. Sorry for the false alarm here.
I misconfigured several pieces of my setup.

**Comment by necolas** [comment]
No worries. I'm interested in trying out this tool chain soon
