### ISSUE TITLE
TextInput: onContentSizeChange

### ISSUE THREAD

**Issue by gut4** [necolas/react-native-web#793]
Looks like it's not implemented.

**Comment by WillSquire** [comment]
PR?

**Comment by WillSquire** [comment]
Had a look at doing this. One way is to use `canvas` although this is very 'cross-platform-ie'. In the interim do you recommend any techniques? Thanks

**Comment by rxb** [comment]
I might be able to put together a PR for this, but in the meantime for anyone else looking for a way to handle this:

```
onChange={(event)=>{
const height = event.nativeEvent.srcElement.scrollHeight;
const width = event.nativeEvent.srcElement.scrollWidth;
}}
```
