### ISSUE TITLE
I got file splitting to work with Typescript!! (It's ugly...)

### ISSUE THREAD

**Issue by mosesoak** [necolas/react-native-web#796]
**Do you want to request a *feature* or report a *bug*?**
_Feature (..ish)_

**What is the current behavior?**
_File splitting is not compatible with Typescript, since TS needs to follow the full compile-time path and wants a hard import reference_

# Demo
https://github.com/mosesoak/react-native-web-ts-app

It works! But requires that you package a split component with a vanilla .js file that does the import splitting, then re-export it with a typecast interface from a .tsx file.

Q: Anyone have what it takes to a piece of magic to make this work under the hood?

Or perhaps there's a better way to do this, let me know! 😄 

PS @necolas Thanks for RNW, it's great!

**Comment by necolas** [comment]
I have no idea what this is about, and the link is a 404 ¯\_(ツ)_/¯

**Comment by mosesoak** [comment]
@necolas sorry for the slop. Set public and edited for clarity.

Note that this is not a big report, but was hoping to generate some discussion around it, so please reopen the issue as you see fit. Thanks again, really enjoying your work and hope this contributes

**Comment by necolas** [comment]
Might be worth bringing up with CRA if there is missing typescript or webpack support

**Comment by mattgabor** [comment]
@mosesoak thanks for sharing this demo, it's surprisingly hard to find a working example of folder based imports with RNW + typescript! 

I wonder if it's worth re-opening this issue or filing a new one to get built in support without having to manually create the declaration files. Considering so many projects use typescript now, having to either keep platform specific extensions as top level imports or add this manual workaround is pretty painful.
