### ISSUE TITLE
Custom event plugins will not work in React 17

### ISSUE THREAD

**Issue by paularmstrong** [necolas/react-native-web#797]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`ResponderEventPlugin` is used. Injecting custom event plugins will be deprecated in 16.3.0 and broken in 17.0.0

```
Warning: Injecting custom event plugins (ResponderEventPlugin) is deprecated 
and will not work in React 17+. Please update your code to not depend on React 
internals. The stack trace for this warning should reveal the library that is using 
them. See https://github.com/facebook/react/issues/11689 for a discussion.
```

**What is the expected behavior?**
react-native-web will continue to work with React 17.

**Environment (include versions). Did this work in previous versions?**

* OS: all
* Device: all
* Browser: all
* React Native for Web (version): all
* React (version): react@next (16.3.0)

**Comment by necolas** [comment]
Thanks, I've been talking with the react team about a way forward

**Comment by paularmstrong** [comment]
Could we keep this issue open for tracking purposes?

**Comment by necolas** [comment]
I'll reopen it when it's a problem

**Comment by necolas** [comment]
Event plugins aren't going away any time soon. I'm going to create a PR to remove the warning in React 16.3

**Comment by necolas** [comment]
https://github.com/facebook/react/pull/12167
