### ISSUE TITLE
Fails with react-native-dropdownalert due to missing default props in StatusBar

### ISSUE THREAD

**Issue by raarts** [necolas/react-native-web#799]
Let's consider this a feature request. I'm preparing a PR for this.

**What is the current behavior?**

The package react-native-dropdown alert relies on some properties of the StatusBar that aren't implemented in the current stub.
This resulted in an error.

**What is the expected behavior?**

Should just work.

**Environment (include versions). Did this work in previous versions?**

I am using 0.3.0-rc4.

**Comment by necolas** [comment]
That property is a private property of the class. Libraries shouldn't expect it to be there. I'd suggest making a PR for that library to use a fallback when it's not available. You can probably mutate the StatusBar class in your app until the library safely accesses the private property
