### ISSUE TITLE
Add color to `select`s `option`s

### ISSUE THREAD

**Issue by piranna** [necolas/react-native-web#810]
At https://github.com/necolas/react-native-web/blob/fb4635e0134940f65e646eef42fc52f65c568063/packages/react-native-web/src/exports/Picker/PickerItem.js#L15 the Picker option accept a color, but later it not being used. [HTML `option` accept colors](https://stackoverflow.com/a/8635403/586382) as `style`s, so we should add them too.

**Comment by necolas** [comment]
On macOS, only Firefox applies the `color`
