### ISSUE TITLE
Misc questions

### ISSUE THREAD

**Issue by corysimmons** [necolas/react-native-web#815]
Sorry, didn't see any mention of support for styled-components but noticed your interest in that project. Was wonder if the 2 worked well together.

Also interested if anyone knows of any UI libs like NativeBase or Shoutem that might work with RNW.

**Comment by corysimmons** [comment]
Work with Electron? _Any_ RN routing lib?

**Comment by necolas** [comment]
Yes it works in Electron, it's web.

You can use any styling library that works on top of the React Native API. But I strongly recommend that you avoid it if you care about performance.
