### ISSUE TITLE
Handling `require` or stubbing NativeModules?

### ISSUE THREAD

**Issue by peacechen** [necolas/react-native-web#818]
**Do you want to request a *feature* or report a *bug*?**

Feature.

The babel plugin isn't converting this line to `react-native-web`:
```
var RNDeviceInfo = require('react-native').NativeModules.RNDeviceInfo;
```
From:
https://github.com/rebeccahughes/react-native-device-info/blob/master/deviceinfo.js

Is that a supported use case?

If not, perhaps the package could be modified to either
```
var RN = require('react-native');
var RNDeviceInfo = RN.NativeModules.RNDeviceInfo;
```
or
```
import {NativeModules} from 'react-native';
```

Understandably, NativeModules isn't supported.  Stubbing it would enable packages to detect react-native-web by checking whether NativeModules is an empty object.  Without the stub, it fails to transpile importing NativeModules.

For example, if NativeModules were stubbed as an empty object, packages could do this:
```
import {NativeModules} from 'react-native';

if (!NativeModules.RNDeviceInfo && Platform.OS === 'web') {
  // conditional path for web...
}
```

Stubbing NativeModules alone doesn't get those packages to work, but it allows them to accommodate react-native-web.

**What is the current behavior?**

Transpilation errors (blows up on react-native references which aren't converted to react-native web)

**What is the expected behavior?**

Transpile success :)

**Environment (include versions). Did this work in previous versions?**

* OS:  10.12.6
* Device: iPad
* Browser: Chrome
* React Native for Web (version): 0.49
* React (version): 16.0

**Comment by necolas** [comment]
Those kind of require calls are not supported. Maybe that library can be patched

**Comment by peacechen** [comment]
Is this supported?
```
var RN = require('react-native');
```

Would you be interested in a PR for stubbing NativeModules?

**Comment by necolas** [comment]
Yes that's supported, and it's already stubbed

**Comment by DavitVosk** [comment]
How did you solve getting value of `RNDeviceInfo`?
