### ISSUE TITLE
Proposal of channel discussion

### ISSUE THREAD

**Issue by MichelDiz** [necolas/react-native-web#819]
Hi, I took the liberty of creating a public chat in the discord facing React-Native. With the intention of uniting the React-native community and improving communication.

I'm creating a channel for public discussions about your project. To avoid flooding "chat" on your github. If you can support the initiative, great! Just share the link below xD

I'm adding RN only projects to this public chat service. And I commit myself to manage chat rooms.
You would just need to observe the chat related to your project.

here's the link
https://discord.gg/RvFM97v

Cheers.

**Comment by necolas** [comment]
Thanks, reactiflux already has RN discussion rooms too

**Comment by MoOx** [comment]
Sorry to told you this @necolas but it has been removed for a while (reorganisation of all channels to have less than one per lib)

**Comment by MoOx** [comment]
(I mean for RNW)

**Comment by necolas** [comment]
Yeah just use the RN room

**Comment by MichelDiz** [comment]
No problem, I had not seen a link or notice in this repo. I thought there was not. But there is the room, if you can pass me the link of the channel that you use so I preach there would be good.
