### ISSUE TITLE
Safari is not transparent

### ISSUE THREAD

**Issue by gHashTag** [necolas/react-native-web#821]
#### Why the header in Safari is not transparent, but in Chrome is transparent? 
![2018-02-14 14 46 27](https://user-images.githubusercontent.com/6774813/36245669-330a3c84-123d-11e8-9769-52312e7adbc3.png)

##### How to make transparent in Safari?

![2018-02-15 10 29 47](https://user-images.githubusercontent.com/6774813/36245612-fb9ee74a-123c-11e8-9017-d6ac34e52615.png)

**Comment by necolas** [comment]
Your background color might be invalid. Are there warnings in the console? The issue template asks that you create a test case that reproduces the bug. Once you make one I will reopen the issue
