### ISSUE TITLE
Extend semantic support for non aria-roles such as <p> tags

### ISSUE THREAD

**Issue by colincclark** [necolas/react-native-web#823]
**ENHANCEMENT / PROPOSAL / REQUEST**

Would be great to be able to create elements that are more semantic, such as `<p>` or `<time>`. Currently only `aria-role` with analagous HTML elements are converted into semantic elements. Providing the extra support would be beneficial for a library that convers Native to Web.

https://github.com/necolas/react-native-web/blob/master/website/guides/accessibility.md#accessibilityrole

https://github.com/necolas/react-native-web/blob/86263a2fa0cd591d3fec65b66668eca53a596cff/packages/react-native-web/src/modules/AccessibilityUtil/propsToAriaRole.js#L16

**Comment by necolas** [comment]
I don't think those elements add anything. They aren't necessary to build accessible UIs. If you really want to use them you can make your own elements with `createElement`

**Comment by craigbilner** [comment]
@necolas how would you recommend that we write a React Native component that transpiles to semantic web elements without creating a web counterpart that specifically declares the intended JSX?

We'd ideally like to get as much code reuse out of a single component as possible?

**Comment by necolas** [comment]
They already render to equivalent semantic elements

**Comment by colincclark** [comment]
@necolas we do care about `<p>` tags and so does the JAWS screen reader (biggest market share).

https://webaim.org/projects/screenreadersurvey6/
https://developer.paciellogroup.com/blog/2008/03/how-jaws-reads-text/

You should reconsider this PR request, or at least open it up again so the community can debate it for 10 seconds?

**Comment by MoOx** [comment]
You already have an API to handle this via https://github.com/necolas/react-native-web/blob/master/website/guides/advanced.md#use-with-existing-react-dom-components
Do you really need something else?

**Comment by necolas** [comment]
The fact that JAWS can understand `p` doesn't mean it's necessary to build accessible experiences.

The `Text` component has been developed to account for all the places text can be rendered, and how screen readers group content (https://github.com/necolas/react-native-web/commit/7705f521c85d5ad2db5801b5a99faf74388d98ab).

And more generally this library looks to help developers avoid the foot-guns in the DOM, which includes things like accidentally rendering `p` in the wrong place or adding invalid roles to elements, thereby creating genuinely problematic experiences for screen readers.

I take accessibility seriously and have built a lot of related features into this library. We often got reports from Twitter's screenreader users about problems with the native or desktop web apps, and they'd tell us that switching to Twitter Lite—built with this library—was a better experience for them. This was confirmed by the accessibility professionals that were hired to audit Twitter's apps. So I'm happy with the balance being struck and the ability to create great experiences for everyone with this library

**Comment by leggomuhgreggo** [comment]
hellye @necolas
