### ISSUE TITLE
Investigate focus-based web UIs, e.g., for TVs and Game Consoles

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#827]
Reading material:

+ [Implementing TV remote control navigation](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS_for_TV/TV_remote_control_navigation)
+ [Pass the Remote: User Input on TV Devices](https://medium.com/netflix-techblog/pass-the-remote-user-input-on-tv-devices-923f6920c9a8)
+ [React TV](https://github.com/react-tv/react-tv)
+ [React Native: building for TV devices](https://facebook.github.io/react-native/docs/building-for-apple-tv.html)

**Comment by dcalhoun** [comment]
I (and my employer) am very much interested in shipping products to focus-based platforms using react-native/react-native-web. If you come across work/explorations/investigations that you feel like you can delegate, let me know. I'll see if I can find company time or free time (more likely) to help.

**Comment by necolas** [comment]
PlayStation have done some work in this space, and reached out about this functionality. Hopefully they will share their focus algorithm at some point. /cc @matthargett

**Comment by azogheb** [comment]
The DirectionalNavigation library from Microsoft may be a good place to start from. https://github.com/Microsoft/TVHelpers/blob/master/tvjs/src/DirectionalNavigation/directionalnavigation-1.0.0.0.js

**Comment by steida** [comment]
My own implementation https://github.com/este/este/blob/master/components/RovingTabIndex.js

**Comment by necolas** [comment]
Every focusable element in the DOM will include `data-focusable="true"`. This should be enough for spatial navigation libraries, like the one Playstation wrote, to manage focus.

**Comment by steida** [comment]
Isn't tabIndex="0" good enough?

**Comment by shirakaba** [comment]
Unless anyone's done any further work in this field, I intend to (try) to make some minor changes to the sublime [react-tv-navigation](https://github.com/raphamorim/react-tv/tree/master/packages/react-tv-navigation) project to support React Native Web. We'll see how it goes.

**Comment by shirakaba** [comment]
I experimented with `react-vidio-tv-navigation` for a few hours, but as I converted it to TypeScript, I found many holes and worrying code paths that made me lose faith in it as a solid solution.

I then spent a few hours getting familiar with `react-tv-navigation` (again, by converting it to TypeScript) but couldn't figure out how to decouple it from the DOM in the end.

Finally, at the end of the work day, I found that there is in fact an existing library for Spatial Navigation in React Native, based on the latter (great!). It does matrix algebra and everything, and it's clearly being used in production:

* Medium blog-post: [Smart TV Navigation with React](https://medium.com/norigintech/smart-tv-navigation-with-react-86bd5f3037b7)
* GitHub repo: [`react-spatial-navigation`](https://github.com/NoriginMedia/react-spatial-navigation)

I'd like to thank Search Engine Optimisation for concealing this..!

I'll report back with how it works out for me with React Native Web.

**Comment by shirakaba** [comment]
Update: I'm now using [`react-spatial-navigation`](https://github.com/NoriginMedia/react-spatial-navigation) for a React Native Web + React Native app, and it works like a dream. Will be a while before I can try on tvOS or Android TV, but NoriginMedia are using it in production for those platforms, so it should fit the bill.
