### ISSUE TITLE
SectionList support

### ISSUE THREAD

**Issue by raarts** [necolas/react-native-web#830]
I'd like to implement SectionList support, and will open a PR for this.

**Comment by necolas** [comment]
Duplicates https://github.com/necolas/react-native-web/issues/91

**Comment by udfalkso** [comment]
@raarts Are you actively working on this?  I also have the same need and may work on it myself if not.  Thanks!

**Comment by raarts** [comment]
@udfalkso I was sidetracked, but my need is still there. Be my guest to work on this. Buy the way, @necolas mentioned elsewhere already having done some groundwork for this component, you might want to look into that. The VirtualizedList component is rather complex.

**Comment by udfalkso** [comment]
Ok.  I might be able to live with a ScrollView on web for the moment, but if I end up needing to head down this route I'll drop a note here that I'm proceeding.  Thanks

**Comment by Sixzero** [comment]
As of current date, 'SectionList' shows me 'UnimplementedView' on web, while on mobile devices it is working well.
Are there a workaround for 'SectionList' elements, or should we make our own implementation of this inherited from FlatList?

**Comment by necolas** [comment]
SectionList is available (as you can see in the examples linked to in the readme), just don't use the legacy implementation
