### ISSUE TITLE
can i use `victory-native` with `react-native-web` ?

### ISSUE THREAD

**Issue by geminiyellow** [necolas/react-native-web#833]
**Do you want to request a *feature* or report a *bug*?**

**FEATURE**

**What is the current behavior?**

- i use `victory-native` in my app, it working
- i try to wrap my app by `react-native-web`
- but i got this error

```
ERROR in ./App/node_modules/react-native-svg/lib/SvgTouchableMixin.js
Module not found: Error: Can't resolve 'react-native/Libraries/Components/Touchable/Touchable' in '/Users/Dev/Documents/Sources/hello-react-native-web/App/node_modules/react-native-svg/lib
```

**What is the expected behavior?**

can i use `victory-native` with `react-native-web` ?

**Environment (include versions). Did this work in previous versions?**

* OS: macos
* Browser: chrome
* React Native for Web (version):  ↓
* React (version): ↓

```
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-native": "0.53.3",
    "react-native-web": "^0.5.1"
```

**Comment by geminiyellow** [comment]
and i found this ISSUE: https://github.com/necolas/react-native-web/issues/531#issuecomment-309819564 

by @peggyrayzis , 

> we launched our first site w/ RNW into prod. Everything on the schedule page is built with universal components + several RN libs (react-native-calendars, react-native-svg, victory-native, react-native-vector-icons)

**Comment by necolas** [comment]
Install the Babel plugin as mentioned in the docs. That will alias the packages

**Comment by geminiyellow** [comment]
`babel-plugin-react-native-web` right ? yep, installed .

**Comment by necolas** [comment]
https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#web-packaging-for-existing-react-native-apps

**Comment by geminiyellow** [comment]
oh @necolas thank you sir. but why i create this issues is because i follow ↑ that doc and cannot start.

**Comment by geminiyellow** [comment]
what i do is

1. create a react-native app by `react-native init`
2. add `react-native-svg` and `victory-native` into that app
3. create a `webpack.config.js` follow [Web packaging for existing React Native apps](https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#web-packaging-for-existing-react-native-apps)

what i try is:

Add every directory that `react-native-svg` and `victory-native` to be compiled by Babel during the build.

**Comment by necolas** [comment]
Looks like a problem in `react-native-svg` with a bad import that reaches into React Native package internals

https://github.com/react-native-community/react-native-svg/blob/master/lib/SvgTouchableMixin.js

That first import should be

```
import { Touchables } from 'react-native'
```

**Comment by geminiyellow** [comment]
hmm... `react-native-svg` like import from internal.
so, we should create a PR to `react-native-svg` or create a patch?

**Comment by RangerMauve** [comment]
Instead of trying to get victory-native to compile for web,
you can alias `victory-native` to `victory` when building for the web.
The two modules are API-compativble

**Comment by geminiyellow** [comment]
@RangerMauve thank you, that is a really good solution.

**Comment by omarhimada** [comment]
@RangerMauve can you share an example of how you construct this alias?

**Comment by RangerMauve** [comment]
> @RangerMauve can you share an example of how you construct this alias?

Not sure if any of this still works since it's been a few years, but you can alias stuff with Webpack's `resolve.alias` section in the config. https://webpack.js.org/configuration/resolve/

**Comment by nikodunk** [comment]
This seems like a relatively clean solution to get it working in 2022 - https://github.com/FormidableLabs/victory/issues/2017#issuecomment-961991180

**Comment by adamsimonini** [comment]
> Instead of trying to get victory-native to compile for web, you can alias `victory-native` to `victory` when building for the web. The two modules are API-compativble

This just worked, flawlessly. Thank you!

If you're using expo and need to configure webpack, you can do so with [this official expo dock](https://docs.expo.dev/guides/customizing-webpack/) (which includes aliasing)

**Comment by programminghat** [comment]
> Instead of trying to get victory-native to compile for web, you can alias `victory-native` to `victory` when building for the web. The two modules are API-compativble

This is AMAZING! Thank you for this!! I wasted so much time trying to implement 1 charting solution across native and native web and encountered endless problems. This solved it in about 5 minutes. Awesome.

**Comment by MartijnGevaert** [comment]
I also want to alias `victory-native`  to `victory`  when I compile my react-native app (created using CRA) to web.
But unfortunately none of the suggested fixes here work.
Below you can find the contents of my `config-overrides.js` document used by `react-app-rewired`, to override webpack.

I added in the code suggested by the link of @nikodunk, but I'm still getting lots of `'jsx' isn't currently enabled` errors.
When I create a platform specific copy of my code (graph.tsx with `victory-native` and graph.web.tsx with `victory`) everything works fine. So it really is just the aliassing that's failing.

My `config-overrides.js` webpack override also contains some other code which is needed to make the web page build, so the file certainly isn't ignored.

If I can't get alias working, is there perhaps some other way to make sure that web uses a different import?
```typescript
module.exports = {
  webpack: function (config, env) {
   // victory native specific code
    config.module.rules.push({
      test: /.*victory-native\/.*\.js/,
      use: {
        loader: 'babel-loader',
      },
    });

    // some other code unrelated to victory native
    config.module.rules.push({
      test: /\.js$/,
      exclude: /node_modules[/\\](?!react-native-vector-icons)/,
      use: {
        loader: 'babel-loader',
        options: {
          // Disable reading babel configuration
          babelrc: false,
          configFile: false,

          // The configuration for compilation
          presets: [
            ['@babel/preset-env', {corejs: '3.22.5', useBuiltIns: 'usage'}],
            '@babel/preset-react',
            '@babel/preset-flow',
            '@babel/preset-typescript',
          ],
          plugins: [
            '@babel/plugin-proposal-class-properties',
            '@babel/plugin-proposal-object-rest-spread',
          ],
        },
      },
    });
    return config;
  },
};
```
