### ISSUE TITLE
CSP error in Chrome with Linking.openURL and nonce-sha in script-src

### ISSUE THREAD

**Issue by koulmomo** [necolas/react-native-web#837]
**Do you want to request a *feature* or report a *bug*?**
Feature: Support csp script-src directive with nonce when using `Linking.openURL`.

**What is the current behavior?**
If you call `Linking.openURL` in chrome with a script-src csp directive that has `nonce-<sha>` set, the link will not open instead printing the following error in the console:

```sh
iframeOpen @ index.js:61
openURL @ index.js:29
onPress @ index.js:20
touchableHandlePress @ index.js:145
_performSideEffectsForTransition @ index.js:732
_receiveSignal @ index.js:655
touchableHandleResponderRelease @ index.js:446
domProps.(anonymous function) @ index.js:74
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:452
executeDispatch @ react-dom.development.js:836
executeDispatchesInOrder @ react-dom.development.js:858
executeDispatchesAndRelease @ react-dom.development.js:956
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:967
forEachAccumulated @ react-dom.development.js:935
processEventQueue @ react-dom.development.js:1112
runEventQueueInBatch @ react-dom.development.js:3607
handleTopLevel @ react-dom.development.js:3616
handleTopLevelImpl @ react-dom.development.js:3347
batchedUpdates @ react-dom.development.js:11082
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
index.js:61 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'nonce-2726c7f26c'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. glitch link: https://glitch.com/edit/#!/sprout-jewel 
2. click the blue button in the center of the page, check chrome's console log

**What is the expected behavior?**
Since this is not really a bug, and more of a feature, not sure what exactly should happen to resolve this. 

Although it would break the API compatibility between react-native + react-native-web, but the easiest solution would be to allow `Linking.openURL(url, [opts])` to take an optional `opts` second arg that could contain a `opts.nonce?: string` value used to attach the `nonce` value created by the underlying iframe.

**Environment (include versions). Did this work in previous versions?**
Not sure

* OS: Mac OS High Sierra (10.13.3)
* Device: 2015 MacBook Pro
* Browser: Chrome (Version 64.0.3282.119 (Official Build) (64-bit))
* React Native for Web (version): ^0.5.1
* React (version): ^16.2.0

**Comment by necolas** [comment]
Hmm, I think this could be viewed as a bug because it's exposing that `Linking` is using an `iframe` hack for added security in Safari. Ideally you wouldn't need to use `Linking` any differently or write the nonce to a global for the library to pick up. 

The `iframe` technique is something I learnt from @mathiasbynens and I wonder if has any thoughts about where to go from here.

**Comment by mathiasbynens** [comment]
I spotted another issue while looking into this. Drive-by fix: https://github.com/necolas/react-native-web/pull/846

Which browser versions do you wish to support? Nowadays, [all browsers except Edge]( https://mathiasbynens.github.io/rel-noopener/#bugs) support `rel=noopener`, so this could be an option to avoid the `iframe` hack:

```js
const anchor = document.createElement('a');
anchor.rel = 'noopener';
anchor.href = 'https://www.google.com/';
anchor.click();
```

If you need Edge support, you could consider appending `' noreferrer'` to the `rel` attribute (with the obvious downside of losing referrer information).

**Comment by necolas** [comment]
Thanks for the other fix!

Do you know which version of Safari includes the [webkit fix](https://bugs.webkit.org/show_bug.cgi?id=155166)?

**Comment by mathiasbynens** [comment]
https://caniuse.com/#search=noopener suggests Safari 10.1 (released in March 2017), and iOS Safari 10.3.

**Comment by necolas** [comment]
Thanks. I think the iframe can go and the feature will be conditional on browser built-in support

**Comment by koulmomo** [comment]
I think it should be 

```js
const anchor = document.createElement('a');
anchor.target = '_blank';
anchor.rel = 'noopener';
anchor.href = 'https://www.google.com/';
anchor.click();
```
to keep it backwards compatible.

**Comment by mathiasbynens** [comment]
Ah yes, I forgot to include the `target = '_blank'` line. Without it, we wouldn’t need any of this code at all! :) I went back and fixed my comment to avoid confusion.

**Comment by koulmomo** [comment]
Thanks for the fix guys! 

@necolas any idea which version and when this fix will go out?
