### ISSUE TITLE
DeviceEventEmitter is converted nothing

### ISSUE THREAD

**Issue by Xing-He** [necolas/react-native-web#841]
### DeviceEventEmitter is undefined

```js
TypeError: Cannot read property 'addListener' of undefined
```

* OS: Mac OS
* Browser: Chrome
* React Native for Web (version): 0.5.1
* React (version): 16.2.0

**Comment by necolas** [comment]
Not supported on web

**Comment by hushicai** [comment]
I use different **emitter** on different platform:

rn: react-native/Libraries/vendor/emitter/EventEmitter
web: eventemitter3
