### ISSUE TITLE
Flow typing for react-native-web components not working

### ISSUE THREAD

**Issue by tanneess** [necolas/react-native-web#843]
Hi, I am just starting out with react-native-web and I find it very promising. But I got stuck for too long on getting flow typing for the View component to work (or any other component) to work.

In the following snippet I get 2 errors for `<MyComponent>` and 0 for `<View>`
```jsx
class App extends Component<{},{}> {
    render() {
        return (
            <View blablabla={""}>
                <MyComponent name={"Boris"} age={"this is not a number"} blabla={""}/>
            </View>
        );
    }
}

class MyComponent extends Component<{name:string,age:number}>{
    render(){
        return <h1>Hi {this.props.name} you are {this.props.age} years old</h1>
    }
}
```

As I don't see any mention of flow support in the documentation. I am starting to wonder if there is any for this library.

Does anyone have a clue?

**Comment by RangerMauve** [comment]
If possible, have your tools use the react-native flow types instead.

**Comment by tanneess** [comment]
Hi, have been trying to do this but it does not seem to be trivial. Do you have any pointers on how this can be achieved. 

Also I am not certain that this approach makes sense. This library after all has it's own lifecycle and there is probably some disparity in features between react-native and react-native-web.

For now the only thing that has work is creating my own definition file, but ideally types should come from what already exists in the code.

**Comment by MoOx** [comment]
RN is written using flow types (so flow read it directly), so you will probably not find an interface for it.

**Comment by necolas** [comment]
I don't understand the problem you're having. Can you share the flow errors?

**Comment by necolas** [comment]
View also allows unknown props to pass to the native element

**Comment by necolas** [comment]
The flow types aren't in the compiled modules. Maybe getting Babel to convert them to flow comments would help your case
