### ISSUE TITLE
Getting the browser DOM node

### ISSUE THREAD

**Issue by ThaJay** [necolas/react-native-web#844]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Did not find a way to get a DOM node, refs return a component instance (which is expected but does not fit my use case)

**Environment (include versions). Did this work in previous versions?**
* OS: Ubuntu 17.10
* Device: electron v1.7.12
* Browser: Chrome 59.0.3071.115
* React Native for Web (version): "react-native-web": "^0.3.4",
* React (version): "react": "^16.2.0", 

I would like to have a reference to a real DOM node. Did not find a way to get it.
This is the way in react-native to get it:
https://stackoverflow.com/questions/38651770/how-can-i-get-real-elment-by-node-id-react-native
`ReactNativeComponentTree.getInstanceFromNode(e.target);`

The reason I am asking for this is that I want to focus a TouchableOpacity but the react-native api does not specify it having `.focus()`.
https://github.com/necolas/react-native-web/issues/53#issuecomment-369575811

If I could get the dom node I would be able to call focus on it or do anything else that is not supported by react-native.

I am porting a react-native (iOS and Android) app to electron. There is a dependency structure in place that allows me to rewrite and restructure UI where needed, but also enables me to reuse all of the logic and a big part of the UI components. This way I am able to write for the browser and for native in places that are different, so I don't mind using browser specific api in the parts that are specifically for electron.

(the reason I want focus and maybe change tabindex as well is to implement keyboard navigation in some parts of our electron app. i.e. arrow keys instead of just tab. Manual binding works but then I would have to write a lot more and disable tabindex tab cycling across the whole app.)

**Comment by necolas** [comment]
`focus` is an instance method on the Touchables. And `findNodeHandle` gets the DOM node. And you can use anything in `react-dom` if necessary

**Comment by ThaJay** [comment]
Thank you, I did not find `findNodeHandle` in the docs but it seems to be there anyway. Calling `focus` on the `div` works for me.

Just want to say this project is pretty awesome.

I really cannot find `focus` on the ref to a `TouchableOpacity` though.
```
context: Object,
props: Object,
refs: Object,
setOpacityTo: function (),
state: Object,
touchableGetHighlightDelayMS: function (),
touchableGetHitSlop: function (),
touchableGetInitialState: function (),
touchableGetLongPressDelayMS: function (),
touchableGetPressOutDelayMS: function (),
touchableGetPressRectOffset: function (),
touchableHandleActivePressIn: function (),
touchableHandleActivePressOut: function (),
touchableHandleKeyEvent: function (),
touchableHandleLongPress: function (),
touchableHandlePress: function (),
touchableHandleResponderGrant: function (),
touchableHandleResponderMove: function (),
touchableHandleResponderRelease: function (),
touchableHandleResponderTerminate: function (),
touchableHandleResponderTerminationRequest: function (),
touchableHandleStartShouldSetResponder: function (),
touchableLongPressCancelsPress: function (),
updater: Object,
__isMounted: true,
_cancelLongPressDelayTimeout: function (),
_endHighlight: function (),
_getChildStyleOpacityWithDefault: function (),
_getDistanceBetweenPoints: function (),
_handleDelay: function (),
_handleLongDelay: function (),
_handleQueryLayout: function (),
_isHighlight: function (),
_opacityActive: function (),
_opacityFocused: function (),
_opacityInactive: function (),
_performSideEffectsForTransition: function (),
_reactInternalFiber: FiberNode,
_reactInternalInstance: Object,
_receiveSignal: function (),
_remeasureMetricsOnActivation: function (),
_savePressInLocation: function (),
_startHighlight: function (),
_touchableBlurListener: function (e),
_touchableNode: "div.rn-alignItems-1oszu61.rn-borderTopStyle-1efd50x.rn-borderRightStyle-14skgim.rn-borderBottomStyle-rull8r.rn-borderLeftStyle-mm0ijv.rn-borderTopWidth-13yce4e.rn-borderRightWidth-fnigne.rn-borderBottomWidth-ndvcnb.rn-borderLeftWidth-gxnn5r.rn-boxSizing-deolkf.rn-cursor-1loqt21.rn-display-6koalj.rn-flexShrink-1pxmb3b.rn-flexBasis-7vfszb.rn-flexDirection-eqz5dr.rn-marginTop-1mnahxq.rn-marginRight-61z16t.rn-marginBottom-p1pxzi.rn-marginLeft-11wrixw.rn-minHeight-ifefl9.rn-minWidth-bcqeeo.rn-paddingTop-wk8lta.rn-paddingRight-9aemit.rn-paddingBottom-1mdbw0j.rn-paddingLeft-gy4na3.rn-position-bnwqim.rn-touchAction-1gvxusu.rn-transitionDuration-eafdt9.rn-transitionProperty-1i6wzkk.rn-userSelect-lrvibr.rn-zIndex-1lgpqti",
__proto__: ReactClassComponent
```

**Comment by necolas** [comment]
It's on the prototype
