### ISSUE TITLE
Merge styles into one className

### ISSUE THREAD

**Issue by pronevich** [necolas/react-native-web#845]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/680439/36906728-c00358d0-1e47-11e8-849e-aeaaf2ff15bb.png)

**What is the expected behavior?**
`<div class="rnw-qwe12e3w"></div>`

Sorry if this is currently not possible for some reason, I am just thinking if that could be done with babel.

**Comment by necolas** [comment]
The current output is as intended to correctly implement the library design without performance issues or determinism errors
