### ISSUE TITLE
Ability to render Touchable as <button> on web

### ISSUE THREAD

**Issue by kirill-kruchkov** [necolas/react-native-web#847]
A bug

Button and Touchable components render as `<div>`s though from https://github.com/necolas/react-native-web/issues/391 I can see that if `accessibilityRole=button` then it should render as `<button>`.

**Demo repo**
https://github.com/kirill-kruchkov/react-native-web-button-demo (please see `TouchableHighlight` usage in `src/Home.js`).

**What is the expected behavior?**
Render Touchables with `accessibilityRole=button` as `<button>` on web.

**Comment by dcalhoun** [comment]
>Note: The button role is not implemented using the native button element due to browsers limiting the use of flexbox layout on its children.

This is an intentional decision referenced in the [documentation](https://github.com/necolas/react-native-web/blob/0.5.1/website/guides/accessibility.md#accessibilityrole).

**Comment by kirill-kruchkov** [comment]
@dcalhoun thank you, missed that part

**Comment by efoken** [comment]
I would like to re-open this issue. It would be really nice, if we have the ability to render i.e. `<button>` elements with `type="submit"`.

There is a workaround for the flexbox issue with the `<button>` element according to [Flexbug #9](https://github.com/philipwalton/flexbugs/blob/master/README.md#flexbug-9) and some browsers are already fixed.

**Comment by dcalhoun** [comment]
@efoken I'd recommend opening a new issue specifically outlining the details behind your need for a `<button type="submit" />`. It's more likely that the project maintainer would weigh in on a new issue.
