### ISSUE TITLE
How do you use react-native libraries?

### ISSUE THREAD

**Issue by JerryGreen** [necolas/react-native-web#849]
1. Is this impossible?

Every library should have something like `dist` folder with complied js (from es6 / other babel features). But react-native libs don't have such a folder, they don't need that to work.

Also, there may be some code behind the bridge (c/swift/java code running on ios/android), and there's no such code analogue for web platform, right? How do you use it then?

2. Where/how can I find react-native libs that support react-native-web?

3. How can I upgrade basic react-native lib to use it with react-native-web?

**Comment by necolas** [comment]
You can use js-only react native packages and pass them through the compiler as documented in the getting started guide. Obviously packages with native dependencies won't work
