### ISSUE TITLE
How to remove this lib from my project?

### ISSUE THREAD

**Issue by yoyeung** [necolas/react-native-web#853]
When i try to remove the npm package from package.json and node_modules
After that i rebuild the app and run in the simulator. They still ask for this package.
<img width="369" alt="screen shot 2018-03-06 at 4 15 21 pm" src="https://user-images.githubusercontent.com/451538/37021208-c0fa9f5e-2159-11e8-8a10-6f1aa5ed862d.png">

I try to use this command but still not working
```
watchman watch-del-all && rm -fr $TMPDIR/react-* && rm -rf ios/build/ModuleCache/* && rm -rf ios/build
```

**Environment (include versions). Did this work in previous versions?**

* OS: macOS Higher Sierra 10.13
* Device: IOS 11 Simulator
* React Native for Web (version): 0.5.1
* React (version): 16.2

**Comment by MoOx** [comment]
Why did react-native-web replace react-native in your native implementation? How did you linked it? If babel plugin, then probably clean babel cache.

**Comment by necolas** [comment]
yeah likely a compiler cache issue
