### ISSUE TITLE
SafeAreaView is not implemented

### ISSUE THREAD

**Issue by hugo** [necolas/react-native-web#859]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
`SafeAreaView` is an alias of `View`

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

N/A

**What is the expected behavior?**
SafeAreaView would work on Web as it does on Native. That is, it would be possible to use it to prevent the sensor housing, home indicator, corners, etc. from occluding UI.

**Environment (include versions). Did this work in previous versions?**

* OS: iOS 11.x
* Device: iPhone X
* Browser: Safari, Chrome, etc.
* React Native for Web (version): 0.5.0
* React (version): 16.2

---

I have a [rough version of this](https://gist.github.com/hugo/ca66e2d048a996be6cf112e4f3090adb) that I built for my own use. I'm sure that it is not robust enough for inclusion in this project as is, but I would happy do the work to make it so given sufficient guidance.

**Comment by RangerMauve** [comment]
Maybe we could just add [this pure JS implementation](https://github.com/react-community/react-native-safe-area-view) as a dependency.

**Comment by necolas** [comment]
Are you saying that Safari doesn't prevent OS chrome from covering the web UI by default?

**Comment by hugo** [comment]
No, it’s physical protrusions - such as the iPhone X “notch” - covering the UI.

**Comment by necolas** [comment]
[This documentation](https://webkit.org/blog/7929/designing-websites-for-iphone-x/) claims otherwise:

> Out of the box, Safari displays your existing websites beautifully on the edge-to-edge display of the new iPhone X. Content is automatically inset within the display’s safe area so it is not obscured by the rounded corners, or the device’s sensor housing.

**Comment by hugo** [comment]
Somewhat misleading.

You can observe the issue with a [minimal demo](https://github.com/hugo/safe-area-view-react-native-web).

Safari without `viewport-fit=cover`:
<img width="256" alt="screen shot 2018-03-19 at 22 12 27" src="https://user-images.githubusercontent.com/1704089/37625165-be7ace98-2bc2-11e8-8437-e456454dcdc3.png">
<img width="256" alt="screen shot 2018-03-19 at 22 12 30" src="https://user-images.githubusercontent.com/1704089/37625166-c0b38c7c-2bc2-11e8-8caa-44a330a55696.png">


Safari *with* `viewport-fit=cover`:
<img width="256" alt="screen shot 2018-03-19 at 22 12 17" src="https://user-images.githubusercontent.com/1704089/37625171-c3ef5362-2bc2-11e8-8c45-0dfcb43d3d2a.png">
<img width="256" alt="screen shot 2018-03-19 at 22 12 20" src="https://user-images.githubusercontent.com/1704089/37625172-c5f5a85a-2bc2-11e8-8e83-95dc007fdee3.png">

---

You can see this conflict between app UI and browser chrome when viewing a Medium.com link in the Twitter in-app browser. The *Open in App* link is hidden by browser chrome until you scroll, and even then it's still partially underneath the home indicator.

<img src="https://user-images.githubusercontent.com/1704089/37625542-40bc4156-2bc4-11e8-9274-2b917e59c44e.jpeg" width="256">
<img src="https://user-images.githubusercontent.com/1704089/37625546-43ad16b0-2bc4-11e8-8d8d-8eb9d5df521e.jpeg" width="256">
