### ISSUE TITLE
react-dom/unstable-native-dependencies dependency error with gatbsy

### ISSUE THREAD

**Issue by lolcookie** [necolas/react-native-web#863]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
Fails to compile gatsby project with `gatsby develop` command throwing this error:
```
 ERROR  Failed to compile with 1 errors                                        

This dependency was not found:

* react-dom/unstable-native-dependencies in ./~/react-native-web/dist/modules/injectResponderEventPlugin/index.js

To install it, you can run: npm install --save react-dom/unstable-native-dependencies
```

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. `npm install --global gatsby-cli`
2. `gatsby new gatsby-site`
3. `cd gatsby-site`
4. `npm install --save react-native-web`
5.  Add `import {} from 'react-native-web'` somewhere
6. `gatsby develop`

**What is the expected behavior?**
Should compile without errors
**Environment (include versions). Did this work in previous versions?**

* OS: MacOS
* Device: Macbook pro 2012
* Browser: N/A
* React Native for Web (version): 0.5.2
* React (version): whatever version is with gatbsy at this time

**Comment by necolas** [comment]
Gatsby is not using React 16 yet. You can install RNW 0.0.x for React 15, but it is not up to date with features. Gatsby needs to upgrade React

**Comment by lolcookie** [comment]
Found a work around using `gatsby-plugin-react-next`
