### ISSUE TITLE
Unable to prevent browser default behavior within handlePress for link on cursor click

### ISSUE THREAD

**Issue by dcalhoun** [necolas/react-native-web#864]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**

Invoking `event.preventDefault` does not impact the browser, the `href` is navigated to within the browser.

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. Visit the [test case](https://glitch.com/edit/#!/north-equinox?path=src/App/index.js:40:10) on cursor device (i.e. notebook, desktop).
1. Open browser console.
1. Click (not tap) each of the three buttons.
1. Observe console and browser navigation.

**What is the expected behavior?**

Invoking `event.preventDefault` should stop the browser from navigating to the `href` value.

**Environment (include versions). Did this work in previous versions?**

* OS: macOS 10.13.3
* Device: MacBook Pro
* Browser: Chrome 65.0.3325.162 (and others)
* React Native for Web (version): 0.5.2
* React (version): 16.2.0

**Comment by dcalhoun** [comment]
Updated the title and description, as this is specific to "clicking" a these elements, not tapping them. Am I required invoke `event.preventDefault` within both `onPress` and `onClick` to support both touch and cursor devices?

**Comment by necolas** [comment]
Looks related to https://github.com/necolas/react-native-web/issues/835

**Comment by necolas** [comment]
Closing as a duplicate
