### ISSUE TITLE
Failed to execute 'setSelectionRange' on 'HTMLInputElement'

### ISSUE THREAD

**Issue by johakr** [necolas/react-native-web#869]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.`

gets thrown if you render an TextInput of type `email`.

**What is the expected behavior?**
Don't call `setSelectionRange` if it isn't supported for provided TextInput type.

**Environment (include versions). Did this work in previous versions?**

* OS: Android
* Device: Several Android Devices
* Browser: Chrome Mobile
* React Native for Web (version): 0.5.3
* React (version): 16.3.0-alpha.1

**Comment by necolas** [comment]
Please can you include a **test case** as asked for in the issue template. And you should be aware that react 16.3 is not officially supported while in alpha

**Comment by necolas** [comment]
Selection is performed in a `try`/`catch` and I couldn't reproduce a problem. If you can provide an example test case, I will take a look.
