### ISSUE TITLE
Improvement: InteractionManager.runAfterInteractions promise version

### ISSUE THREAD

**Issue by mauron85** [necolas/react-native-web#875]
Firstly I would like to thank @necolas for this amazing library. It works very well and helped me ported already some projects from native to web without much effort. Thus issue/improvement is very small and only appeared when I tried to port [react-native-motion](https://github.com/xotahal/react-native-motion) to web.

**Do you want to request a *feature* or report a *bug*?**
Well maybe a feature.

**What is the current behavior?**
Currently `InteractionManage.runAfterInteractions` seems to only support callbacks.  But some libraries seems to use Promise variant. 

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:

One example from react-native-motion:

https://github.com/xotahal/react-native-motion/blob/2e44fa2bd1472f484dae4af99ab0b24929ab475b/src/ScaleAndOpacity.js#L31

Side note: Apart from that, it can be ported to web surprisingly easily. All thanks to react-native-web. 

**What is the expected behavior?**
It would be great if `InteractionManage.runAfterInteractions` supported Promises too.

**Environment (include versions). Did this work in previous versions?**
N/A

* OS: not relevant
* Device: not relevant
* Browser: not relevant
* React Native for Web (version): 0.5.3
* React (version): 16

**Comment by NishantZet** [comment]
Hey @mauron85, Did you found any solution for this ?
