### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by jasonleonhard** [necolas/react-native-web#878]
Feature request

simple working routing example

**Comment by necolas** [comment]
Routing is not part of React Native or React DOM, so you can use the structure of examples found in projects like React Router and React Navigation (which is working on adding web support IIRC)

**Comment by English3000** [comment]
`react-router-native` is an ES module (https://github.com/ReactTraining/react-router/issues/6115), meaning it won't be compiled with my build tool unless I use CRNA or `react-native init`

As is, I'm not using any generator for my frontend. Will `react-router-dom` paired with `react-native-web` work for mobile devices?

**Comment by English3000** [comment]
@edupooch  Nice! 

Any example with a frontend directory inside a backend framework (all in one repo, that defaults to web)?

**Comment by Parmar-Bansi** [comment]
http://localhost:8080/about

Cannot GET /about

any idea how to resolved it
