### ISSUE TITLE
Failed prop type: `Picker` children must be of type `Picker.Item`.

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#879]
Not sure what I am doing wrong.

```js
// @flow
import * as React from 'react';
import { View, Picker } from 'react-native';

class AttendanceFilter extends React.PureComponent<{}> {
  render() {
    return (
      <View>
        <Picker
          selectedValue={'js'}
          // onValueChange={(itemValue, itemIndex) =>
          //   this.setState({ language: itemValue })
          // }
        >
          <Picker.Item label="Java" value="java" />
          <Picker.Item label="JavaScript" value="js" />
        </Picker>
      </View>
    );
  }
}

export default AttendanceFilter;
```

**Comment by steida** [comment]
Temp fix: `Picker.propTypes = null;`

**Comment by necolas** [comment]
It helps me fix problems if you can include 1) a reduced test case, 2) the complete error message. I can't reproduce the warning with your code example. One `Picker.Item` produces a warning though

**Comment by steida** [comment]
So I manually updated related code: 

```js
var PickerItemPropType = function PickerItemPropType(
  props,
  propName,
  componentName,
) {
  var prop = props[propName];
  var error = null;
  _react2.default.Children.forEach(prop, function(child) {
    console.log(child.type, _2.default.Item);
    console.log(child.type === _2.default.Item);
    if (child.type !== _2.default.Item) {
      error = new Error('`Picker` children must be of type `Picker.Item`.');
    }
  });
  return error;
};
```

The result is interesting. 

![screen shot 2018-03-31 at 02 34 34](https://user-images.githubusercontent.com/66249/38157917-1209972a-348c-11e8-992b-3032d3ab3661.png)

**Comment by steida** [comment]
That's probably because of Webpack transpilation or something like that.

**Comment by steida** [comment]
@necolas I believe it's because of Webpack or Babel transpilation. Probably impossible to fix. Flow type works.

**Comment by necolas** [comment]
Have you tried using HEAD on master?

**Comment by steida** [comment]
Have you tried to take a look at what I wrote and screenshots I added? I used two children, so it can't be related.

**Comment by necolas** [comment]
Yeah I couldn't reproduce with 2. If you have a test case that shows the issue I'll take a look

**Comment by steida** [comment]
http://github.com/este/este is test case.

**Comment by necolas** [comment]
How is linking to your repo an example of a test case?

**Comment by necolas** [comment]
Going to close this until there's a test case

**Comment by steida** [comment]
Still broken, I don't know why. `NativePicker.propTypes = null;` fixes it.

**Comment by rickysullivan** [comment]
Use `PickerItem` not `Picker.Item`
