### ISSUE TITLE
Recommended boilerplate to start right away

### ISSUE THREAD

**Issue by mewben** [necolas/react-native-web#88]
Hi, is there a recommended setup (boilerplate) so we can start using react-native-web right away for development and deploy into production?

Thanks for the great job on this btw.

**Comment by necolas** [comment]
A recommended web setup? Not yet, but we can start a simple one this week.

**Comment by af7** [comment]
+1 Your project is a great idea BTW!

**Comment by grigio** [comment]
+1 Hi, thanks for this project. I'd like also some more info about the Cordova / Phonegap integration

**Comment by holmesal** [comment]
I put together a [minimal starter kit for react-native-web](https://github.com/holmesal/react-native-web-starter) with just the basics: webpack, babel, and react-native-web. Scripts to run on dev, build, and deploy to a gh-pages. 

Give it a whirl, and do open some issues if you feel it's missing anything!

**Comment by grigio** [comment]
Thanks @holmesal, this is my [example app](https://github.com/corso-javascript/react-native-web-utf8map) with React Native Web.

I think the RNW start kit should have at least the file below

```
web/
index.web.js
```
Just to keep the `react-native` conventions

**Comment by necolas** [comment]
There is now a link to a starter kit project in the README. I think this helps answer the question in this issue for now. Thanks!
