### ISSUE TITLE
Picker (or TextInput) fontFamily breaks another component fontFamily

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#881]
Bug

When I set Picker a fontFamily, completely another component will lost its fontFamily style.

I will try to make and demo, meanwhile, some users can have a similar problem so I created an issue.

Btw, the bug I reported is still there: I updated an issue.
https://github.com/necolas/react-native-web/issues/879

Also, this is very probably related: https://github.com/necolas/react-native-web/pull/860#issuecomment-372147591

**Comment by steida** [comment]
There must be some race condition because I have two almost exactly the same apps. Here it works http://github.com/este/este, but in another private repo, when I add font family, completely another component will lose it.

**Comment by steida** [comment]
As I debug it, it seems fontFamily is somehow incorrectly cached when I slightly change a definition for a picker, it works.

**Comment by steida** [comment]
Just investigated the same behavior exists for TextInput.

**Comment by steida** [comment]
Trying to isolate in glitch, without a success so far :-/

**Comment by steida** [comment]
OMG, I think I got it.

**Comment by necolas** [comment]
I can't tell what you're trying to do in that glitch

**Comment by steida** [comment]
Demonstrate a bug of course. I am using fairly complex setup: http://github.com/este/este
Isolation isn't easy, give me a time, please.

**Comment by steida** [comment]
Anytime I set fontFamily for more components, one of them will lose it. It's happening I don't know why. Trying to isolate as much app code as possible.

**Comment by necolas** [comment]
> Also, this is very probably related: #860 (comment)

Picker doesn't support font family. See https://necolas.github.io/react-native-web/storybook/

**Comment by steida** [comment]
I just tried to replace `import { StyleSheet } from 'react-native';` with stub

```js
const StyleSheet = {
  create: styles => styles,
};
``` 

And bug disappeared. Maybe I am doing something wrong.

**Comment by steida** [comment]
It seems to be related to StyleSheet, not picker. Now I am investigating the same issue with TextInput.

**Comment by steida** [comment]
Btw, so Picker fontSize isn't possible to set for web? It makes sense if RN does not support it.

**Comment by steida** [comment]
It's definitely related to `import { StyleSheet } from 'react-native';` Inline styles works well. Still don't know how to isolate it :-/

**Comment by steida** [comment]
@necolas OK, It's time to give up it. Whenever I set a font family to TextInput, Text will lose it. There is definitely a bug in RNW StyleSheet. This is workaround I am going to use because don't know RNW source enough to be able to fix it.

```js
textInput: StyleSheet.create({
    input: {
      color: colors[textColor],
      fontFamily: fontFamily + ' ',
      marginBottom: rhythm(1),
    },
  }),
```

**Comment by necolas** [comment]
And this is not something you can reproduce in a simple test case?

**Comment by steida** [comment]
No, because there is probably some race condition. As I wrote, I have two almost the same apps, it works in first and doesn't in second.

**Comment by necolas** [comment]
I had a look at https://github.com/este/este/blob/79fac538e710050893f4328eb0e4024bd833ce57/themes/theme.js

This is not needed because it's handled within RNW when you use the `System` font-family: https://github.com/este/este/blob/79fac538e710050893f4328eb0e4024bd833ce57/themes/theme.js#L49

This is not a valid style definition: https://github.com/este/este/blob/79fac538e710050893f4328eb0e4024bd833ce57/themes/theme.js#L55-L58
https://github.com/este/este/blob/79fac538e710050893f4328eb0e4024bd833ce57/themes/theme.js#L230-L234

**Comment by steida** [comment]
@necolas If it was my fault, please tell me where I shall send some bitcoins.

**Comment by necolas** [comment]
Let me know if editing that este code doesn't resolve the issue

**Comment by steida** [comment]
@necolas What's wrong with that? It's normal style definition. color and fontFamily.

**Comment by steida** [comment]
As for "This is not needed because it's handled within RNW when you use the System font-family"

How is it related? I suppose it's perfect valid case to set custom fontFamily even similar to System. Am I wrong?

**Comment by necolas** [comment]
> What's wrong with that? It's normal style definition

Sorry, I was confused by the way you've defined the styles in another object.

> I suppose it's perfect valid case to set custom fontFamily even similar to System

Sure

**Comment by steida** [comment]
As for "Are you mixing RNW with CSS from somewhere else?" I used Next.js example. Nothing more I am aware of.

**Comment by steida** [comment]
I guess there is something wrong with a cache. Este example works well, but the same Este app with less / different order components break everything. I had the same issue when I tried to put styles to anchor manually instead of using Text with role prop.

**Comment by steida** [comment]
@necolas Not sure how the last commit should fix it. I tried fontFamily Arial with the same result.

**Comment by necolas** [comment]
Last commit is unrelated. Without a test case or running example I can't help

**Comment by steida** [comment]
I hope it's broken only for fontFamily. I will keep you informed.

**Comment by steida** [comment]
Hmm, I think I know where is the problem. When I add fontFamily to TextInput, Text font inherit became stronger than fontFamily. That's weird. 

![screen shot 2018-04-01 at 17 46 38](https://user-images.githubusercontent.com/66249/38174968-76050ed6-35d5-11e8-81d1-2bd8328901ad.png)

**Comment by steida** [comment]
Note 

![screen shot 2018-04-01 at 18 16 39](https://user-images.githubusercontent.com/66249/38175192-e29627f8-35d8-11e8-8ab5-6e277521d56f.png)

**Comment by steida** [comment]
Note font inherit is later then fontFamily

![screen shot 2018-04-01 at 18 21 18](https://user-images.githubusercontent.com/66249/38175233-86985f10-35d9-11e8-951f-3bc301c3cf7c.png)

**Comment by steida** [comment]
When I remove fontFamily from TextInput, Text fontFamily is rendered correctly.with correct specificity.

![screen shot 2018-04-01 at 18 23 44](https://user-images.githubusercontent.com/66249/38175252-e9acc758-35d9-11e8-839f-122d7b1b0829.png)

**Comment by steida** [comment]
Thank you a lot for your hard super awesome work. RNW is gold.
