### ISSUE TITLE
Picker itemStyle

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#882]
A feature request.

itemStyle is supported by iOS and would be nice to have it on the web as well.

https://facebook.github.io/react-native/docs/picker.html#itemstyle

**Comment by steida** [comment]
Interesting thing is that fontFamily and fontSize works for style, so it should be easy to implement.

**Comment by necolas** [comment]
I don't think any of the major browsers let you style the `option` element in a meaningful way. Firefox lets you set the color, that's about it.

**Comment by steida** [comment]
What is the recommended fontSize approach?

**Comment by necolas** [comment]
Browsers don't let you change the font size of `option`
