### ISSUE TITLE
ScrollView showsHorizontalScrollIndicator=false doesn't work in Firefox

### ISSUE THREAD

**Issue by Monte47** [necolas/react-native-web#887]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
ScrollView Component showsHorizontalScrollIndicator=false Prop does not change anything in Firefox.

**Environment (include versions). Did this work in previous versions?**

* OS: macOS High Sierra
* Device: MacBook
* Browser: Firefox 59
* React Native for Web (version): 0.3.2
* React (version): 16.2.0

**Comment by necolas** [comment]
Web doesn't really give you control over the scrollbars visibility. Not something I think I can fix here
