### ISSUE TITLE
Add support for Text adjustsFontSizeToFit

### ISSUE THREAD

**Issue by tanx** [necolas/react-native-web#889]
**Do you want to request a *feature* or report a *bug*?**

Feature. See: https://facebook.github.io/react-native/docs/text.html#adjustsfontsizetofit

**What is the current behavior?**

The prop is not implemented. See: https://github.com/necolas/react-native-web/blob/23fa663a6e6b69c76cb6499d0a8656ff938cca02/packages/react-native-web/src/exports/Text/index.js#L44-L45

**What is the expected behavior?**

The prop to be supported :)

**Environment (include versions). Did this work in previous versions?**

* OS: all
* Device: all
* Browser: all
* React Native for Web (version): all
* React (version): all

**Comment by necolas** [comment]
No plans to support this. It's iOS-only in React Native and depends on native functionality that's not available on the web.

**Comment by tanx** [comment]
@necolas gotcha, thanks for the reply. So if we provided a PR to polyfill for the web you wouldn’t accept it either?

**Comment by necolas** [comment]
I'd take a look at a PR that adds this functionality in a reliable and performant way :)

**Comment by tanx** [comment]
Ok cool. We'll give it a try and post PR if we find a clean way to do this. Otherwise I'm sure we can work around the issue as well.

Anyway, this goes without saying but thanks a lot for your work on 'react-native-web'. It's allowing us to build our desktop UI in Electron with shared components for mobile :)

**Comment by magus** [comment]
I wrote something that requires worst case log(n) dom operations might be able to adapt, worth trying to port Nicolas?

https://codesandbox.io/s/nrpqopp18p

**Comment by semiherdogan** [comment]
Android adjustFontSizeToFit is merged but not released yet, see: https://github.com/facebook/react-native/pull/26389 
For the time being for android i am using "onTextLayout" prop of Text component (and calculating font size manually), if onTextLayout is added into Text component, that would work too.

**Comment by RWOverdijk** [comment]
Cool, does that mean this could be considered for react native web?

**Comment by semiherdogan** [comment]
onTextLayout doesn't exists on Web Text compoent, if added i think so..

**Comment by LinusU** [comment]
I think that the biggest issue is that there is no straight forward way to do this on the web platform. The repo owner has already indicated that he would be open to this:

> I'd take a look at a PR that adds this functionality in a reliable and performant way :)

The issue right now is that there is no known way to do this in a reliable and performant way 😅
