### ISSUE TITLE
Game2014 example does not interact

### ISSUE THREAD

**Issue by raytrask** [necolas/react-native-web#892]
**Do you want to request a *feature* or report a *bug*?**
Potential bug on [Example Game2048](https://necolas.github.io/react-native-web/storybook/?selectedKind=Example%20apps&selectedStory=Game2048&full=0&addons=0&stories=1&panelRight=0)

**What is the current behavior?**
I click and slide around and it does not seem to do anything.  

**What is the expected behavior?**

I would expect to be able to interactively add 2 or more numbers together

**Environment (include versions). Did this work in previous versions?**
Running Safari and Chome on MacOS

**Comment by necolas** [comment]
It's a touch-only example from react native. Doesn't work with mouse interactions
