### ISSUE TITLE
intial setup question: error compiling JSX sources in sym-linked subdirectories

### ISSUE THREAD

**Issue by vladp** [necolas/react-native-web#893]
Not a problem with react-native-web, however after following instructions to start a basic app, and then adding my own folders and including components from there -- compilation with Babel is not working.

> Module parse failed: Unexpected token (35:6)
> You may need an appropriate loader to handle this file type.
> |   {
> |     return (
> |       <View>
> |       </View>
> |     );}

Are there any specific configurations that I need to do on top of react-create-app
to allow to include components from symlinked directories underneath the ./src/ folder ?

I cannot copy my components source files over to my web project, because they belong to a working react-native app, I am hoping to leverage the react-native-web to make the app available on the browser.

The web project is setup outside of the current react-native project (which is why I had to create a WinNT symlink (using Cygwin), to include the react-native components under react-native-web project's src directory)

**What is the current behavior?**
getting a compilation error on JSX syntax in render() function.

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

I created the new web app using react-create-app. so I believe the behavior is reproducible by others who would follow same steps. 
My understanding is that, the glitch was created using create-react-app plus addition of react-native-web and babel plugin for react-native-web.  (which is what I have done).

My issue is with compilation of additional sources in directories, so not exactly matching the sample app on glitch.

**What is the expected behavior?**
no errors for components that compile without errors in react-native packages
**Environment (include versions). Did this work in previous versions?**

* OS: Windows 10
* Device: laptop
* Browser: IE 11
* React Native for Web (version): 0.5.4
* React (version):16.3.1

----------------

package.json

> {
>   "name": "ua1b",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "create-react-class": "15.6.3",
>     "react": "^16.3.1",
>     "react-dom": "^16.3.1",
>     "react-native-deprecated-custom-components": "github:facebookarchive/react-native-custom-components",
>     "react-native-material-kit": "github:xinthink/react-native-material-kit#master",
>     "react-native-section-list-get-item-layout": "2.2.1",
>     "react-native-vector-icons": "^4.5.0",
>     "react-native-web": "^0.5.4",
>     "react-scripts": "1.1.4",
>     "tree-model": "^1.0.6"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test --env=jsdom",
>     "eject": "react-scripts eject"
>   },
>   "devDependencies": {
>     "babel-plugin-react-native-web": "^0.5.4"
>   }
> }
> 

.babelrc

> {
>   "plugins": ["react-native-web"]
> }

**Comment by necolas** [comment]
I think you're best asking about this on stackoverflow or create-react-app. Not something I can help you with

**Comment by vladp** [comment]
thank you.
I entered a bug for create-react-app.  As the setup does not process JS files under ./src/<sym linked directories>.
If directories are real (not symlinked) -- the everything works.

https://github.com/facebook/create-react-app/issues/4295

Symlinked directories are needed when developer wants to share common library between react/react-native/react-native-web project (which I assume is often the case for react-native-web users).

**Comment by ott-web** [comment]
I actually have this problem with JSX not working for `react-native-web` and I started from a react-native-cli project, followed the advanced guide here. I have no symlinking, my `src` a real directory and no matter what I do, JSX is not parsed. I'm pulling out my hair because I've worked with many React/Webpack projects and never have I had this issue.

**Comment by vladp** [comment]
it is hard to suggest something @ott-web .   
Since this worked for you in other projects and you have no symlinks, it should work.
In basic configs react-native-web works out of the box with CRA.
CRA has recently been updated to use webpack 4x -- I have not migrated to that version.
So do not have any particular experience to share

I am a 100% sure there is nothing wrong with react-native-web distro. since 0.6 to 0.10 I did not need to change anything in my setup.

Perhaps you could pull from git an existing project with rnw that was generated with the new CRA
and go from there?
