### ISSUE TITLE
RNW createElement - a11yComponent can conflict with passed element

### ISSUE THREAD

**Issue by comp615** [necolas/react-native-web#895]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
When using RNW in conjunction with other libraries, it's sometimes necessary to use createElement on the 3rd party component to conform them to RNW styles. Right now, if RNW detects a11y props, it will [ignore the passed component](https://github.com/necolas/react-native-web/blob/a53372ceb3a5ce9707e7a8a60139434025df5722/packages/react-native-web/src/exports/createElement/index.js#L87) and use it's own tags instead, sometimes leading to unexpected behavior.

**If the current behavior is a bug, please provide the steps to reproduce**

https://glitch.com/edit/#!/react-native-web-react-router-a11y-bug

1. Use createElement on a component like Link from React-Router
2. Pass accessibility props as part of the rendering (anything that triggers an accessibility component)
3. Observe that the Link does not work (it's not used)

**What is the expected behavior?**
4. The passed component is used.

It might be right to overwrite it, but it might be helpful to have tools or guidance to handling mixing things properly. Thanks!

**Comment by necolas** [comment]
Looks like it should probably not override the provided component unless it is a string
