### ISSUE TITLE
Layout regression in 0.6.0 vs 0.5.4?

### ISSUE THREAD

**Issue by sgalabov** [necolas/react-native-web#902]
Possible bug.

I have created 2 examples, the only difference between which is the react-native-web version:
0.5.4: https://glitch.com/edit/#!/saber-racer
0.6.0: https://glitch.com/edit/#!/necessary-amusement

In 0.5.4, the behaviour is as follows:
The View with style header is fixed to the top of the screen, the View with style footer is fixed to the bottom and the ScrollView takes all the space in between and is, as expected, scrollable.

In 0.6.0 the entire screen (e.g., not only the ScrollView) is scrollable the header and footer are not fixed to their expected places.

The behaviour on iOS is the same as the one in react-native-web 0.5.4, which I guess should be the correct behaviour.

**Comment by MoOx** [comment]
I guess that's related to the first breaking change listed here https://github.com/necolas/react-native-web/releases. So I would say it's normal and not an issue. You can fix this very easily.

**Comment by sgalabov** [comment]
I saw the first breaking change and tried to add StyleSheet.absoluteFill to the styles of the top view to check if it fixes the issue, but it didn't fix the issue...
I am certain it would be an easy fix, but I can't see it at the moment, so I'd appreciate a pointer... 
Also, the main reason I reported the issue for was that iOS and web behave differently, so I thought it was worth pointing out.

**Comment by sgalabov** [comment]
OK, I will probably go with something along the lines of:
https://glitch.com/edit/#!/mercury-hook

It seems to work on both web and iOS and it even seems to handle rotation and resize pretty well.d

**Comment by necolas** [comment]
You need to set the body/html/react-root elements to 100% height if you're rendering the app full screen. Not something the framework can do for you as you might be rendering into a subview of an existing app
