### ISSUE TITLE
Conditional Import of Modules between React-Native and React-Native-Web

### ISSUE THREAD

**Issue by gauthampait** [necolas/react-native-web#907]
Hi

I have an existing iOS app which works fine. I want to reuse some of the components on my ReactJS web using react-native-web. I am aware of the module that are not supported currently by the developers. Eg : react-navigation does not have a web support.

I have a LoginView Component which uses react-navigation which works fine on iOS/Android. I want to use react-router for web.

<img width="359" alt="screen shot 2018-04-20 at 3 43 39 pm" src="https://user-images.githubusercontent.com/2095256/39045803-a064cdd4-44b1-11e8-92c3-0b86b61a5550.png">

<img width="461" alt="screen shot 2018-04-20 at 3 44 15 pm" src="https://user-images.githubusercontent.com/2095256/39045833-b953ce30-44b1-11e8-8935-31488e571ca8.png">

I get the above error when I run the web.

Is there a way I can prevent this module from loading in the web and have it used only in my mobile platforms ? 

If this is not the way to do it, is there any other right way of dealing with such situation ?

I am sorry, I come from an iOS background and new to this.

**Comment by necolas** [comment]
You can also use platform-specific files to avoid importing things like react-navigation in the web bundle, or react-router in the native bundles. There's more info about platform file extensions in the documentation "guides" in the readme, and the react native docs
