### ISSUE TITLE
Module parse failed: Unexpected token ...

### ISSUE THREAD

**Issue by ahmedu007** [necolas/react-native-web#912]
I'm sorry if this is not the right place to ask, but I've been stuck with this for a while now. I'm using [React-native-material-ui](https://github.com/xotahal/react-native-material-ui) for components and everything works fine on the Native side, but the web server throws an error on the `spread operator`. I've tried installing Babel loader, updated presets to stage 0 and stage 2, even created a new webpack config so I can override default settings but still stuck at the same place.

Anyone came across this problem before? Any solutions, or suggestions would be really appreciated.

**Comment by MoOx** [comment]
See https://github.com/necolas/react-native-web/issues/809#issuecomment-364959750

**Comment by necolas** [comment]
The "getting started" documentation also explains how to compile RN dependencies

**Comment by luongs3** [comment]
@ahmedu007 did you find out the solution. I got the same one.

**Comment by ahmedu007** [comment]
I did, check the getting started guide as necolas mentioned. I cant remember what we did but it did fix the issue

**Comment by tkow** [comment]
I use webpack and the configurations resolve mine.
```js
const path = require('path')
const glob = require('glob')

let  includedBabel= [...someDefultIncludedPath]

if(isStorybook) 
  includedBabel= [
      ...includedBabel,
      ...glob.sync('./node_modules/react-native-*',{ignore: './**/react-native-web'}).map( _path => 
     path.join(__dirname, _path))
  ]
}

// about rules
...
{
   test: /\.jsx?$/,
   include: includedBabel,
   use: {
       loader: 'babel-loader',
          options: {
            presets: ["module:metro-react-native-babel-preset"],
          },
       },
   },
}
```
