### ISSUE TITLE
How do I run after integration?

### ISSUE THREAD

**Issue by Sxiaobai** [necolas/react-native-web#913]
How do I run after integration?

**Comment by MoOx** [comment]
Can you be more specific?
You mean build/deploy? If so, like any web app. Build and deploy the builded files to a static hosting.

**Comment by Sxiaobai** [comment]
@MoOx I want to know how to use react-native-web  But the integration into the newly created project does not know how to start? Can you tell me how to get started or related websites?Like how to run react-native project(react-native run-ios)

**Comment by MoOx** [comment]
You need to look at CRA (https://github.com/facebook/create-react-app/) or similar (or even raw build via webpack etc).

**Comment by Sxiaobai** [comment]
@MoOx Thank you very much
