### ISSUE TITLE
Support Layout Properties as View and Image props

### ISSUE THREAD

**Issue by brunolemos** [necolas/react-native-web#914]
**Do you want to request a *feature* or report a *bug*?**

Feature / React Native Parity

**What is the current behavior?**

This is supported by `react-native`: `<View flex={1} />`, `<View width={200} />`, etc.
But not by `react-native-web`.

**What is the expected behavior?**

All props from the [LayoutPropTypes](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/LayoutPropTypes/index.js) file  should be supported as props for the `View` and `Image` components.

**Environment (include versions). Did this work in previous versions?** No

* OS: macOS 10.3.4
* Device: iOS 11.3 Simulator / iPhone X
* Browser: Chrome
* React Native for Web (version): 0.6.0
* React (version): 16.3.2

**Comment by necolas** [comment]
Apparently this was an early accident in React Native. I don't think it needs to be repeated here

**Comment by brunolemos** [comment]
This's been working for years and there is no intention to be dropped any time soon.

Anyways,
Ok, I'll support this locally by using patch-package.
