### ISSUE TITLE
Can this  be used as a pc web project

### ISSUE THREAD

**Issue by pinkyblue** [necolas/react-native-web#915]
Can this project be used as a PC project? I would like to use RN as the project of Android and IOS, and then use RNW as a Web project to run on the PC, can it be compatible with the layout?

**Comment by pinkyblue** [comment]
And I compiled the document according to the instructions, generated only JavaScript files, can I generate Html and Css files, and generated local files that I can style and logically modify?Looking forward to your answer,Thanks a lot

**Comment by MoOx** [comment]
See https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#adding-to-a-new-web-app

**Comment by necolas** [comment]
Yes it will work in a web browser and election. The documentation has links to projects that help you get started with web development
