### ISSUE TITLE
Can't type in multiline TextInput with cursor at very end when not in production env

### ISSUE THREAD

**Issue by sunweiyang** [necolas/react-native-web#917]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When `process.env.NODE_ENV !== 'production'`, user can't add to the end of a multi-line TextInput field.

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. Put the following in a component's render method to create a multiline TextInput with `textInputContents` in state initialized with some multi-character and multi-line string:
```
          <TextInput
            multiline={true}
            style={{
              borderRadius: 5,
              borderWidth: 1,
              borderColor: "black",
              width: 300,
              height: 200,
              paddingHorizontal: 5
            }}
            value={this.state.textInputContents}
            onChangeText={text => {
              this.setState({ textInputContents: text });
            }}
          />
```
2. Run `npm start` with an environment different from production.
3. Type any characters (letter, space, return, etc.) with the cursor in the middle of the TextInput's contents (characters both before and after the cursor). Observe it working as expected.
4. Type any character (letter, space, return, etc.) with the cursor at the very end of the TextInput's contents (no characters after the cursor). Observe it immediately break the web app; console would display:
```
Uncaught Error: Unexpected text node: 
. A text node cannot be a child of a <View>.
```

**What is the expected behavior?**
A user should be able to type in multiline TextInput anywhere in the TextInput field, including the very end.

**Current workaround**
I have isolated it to the following lines in react-native-web's `View/index.js`:
```
    if (process.env.NODE_ENV !== 'production') {
      _react2.default.Children.toArray(this.props.children).forEach(function (item) {
        (0, _invariant2.default)(typeof item !== 'string', 'Unexpected text node: ' + item + '. A text node cannot be a child of a <View>.');
      });
    }
```

When these lines are removed, this bug does not appear. I have been removing these lines manually as a workaround.

**Environment (include versions). Did this work in previous versions?**

* OS: macOS 10.13.4
* Device: MacBook Pro 2016
* Browser: Chrome Version 65.0.3325.181
* React Native for Web (version): 0.5.3
* React (version): 16.3.1

**Comment by necolas** [comment]
`TextInput` doesn't use `Text` or `View`. The error might be somewhere else in your UI unrelated to `TextInput`. If you provide a reduce test case using glitch (see issue template), I can take a look.
