### ISSUE TITLE
something wrong with '' 4.0.0

### ISSUE THREAD

**Issue by tangkunyin** [necolas/react-native-web#920]
Hi there, I got an blank screen error after RNW installed with babel-preset-react-native 4.0.

I change the version to 1.9.0, It works!  

Why ?

**Environment (include versions)**

"react": "16.3.0",
"react-native-web": "^0.6.1",
"react-native": "0.54.4",

**Comment by necolas** [comment]
If you provide the error and an example using glitch I can take a look.
