### ISSUE TITLE
SUGGESTION: make Button component stylable

### ISSUE THREAD

**Issue by English3000** [necolas/react-native-web#921]
As implemented, `Text` wrapped by a `TouchableOpacity`.

Easy to add a `style` prop that is passed to `Text` (especially as that's the more flexible option with React Native).

How my current code looks:

```js
<View style={{width: "20%"}}>
  <Button title="Create Link" onPress={this.createLink}/>
</View>
```

**Comment by necolas** [comment]
`Button` is React Native cannot be styled. The RN docs mention:

> If this button doesn't look right for your app, you can build your own button using TouchableOpacity or TouchableNativeFeedback.
