### ISSUE TITLE
Can't style `flex-basis` on react-native-web Views using `styled-components`

### ISSUE THREAD

**Issue by Zacqary** [necolas/react-native-web#922]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using react-native-web in conjunction with styled-components, setting the `flex-basis` property on a react-native-web element doesn't apply, because of a `flex-basis: auto !important` in the base style sheet.

**Glitch demo**
https://glitch.com/edit/#!/majestic-snow

**Steps to reproduce**
1. Create a `styled(View)` and apply a `flex-basis` property to it
2. Observe that the `flex-basis` is still set to `auto` instead

**What is the expected behavior?**
The `flex-basis` property should be correctly overridden by `styled-components`

**Environment (include versions). Did this work in previous versions?**

* OS: MacOS 10.13.4
* Browser: Firefox 60.0b13 and Chrome  65.0.3325.181
* React Native for Web (version): 0.6.0
* React (version): 16.3.0-alpha.1
* styled-components (version): 3.2.6

**Comment by necolas** [comment]
This is not likely to be an issue much longer. But it's not a great idea to use s-c on top of RNW, as it means you have 2 style systems in use at the same time with different performance characteristics and resolution algorithms

**Comment by Zacqary** [comment]
Can you clarify why this isn't likely to be an issue much longer? Is there an upcoming change to RNW that would fix this?

**Comment by leggomuhgreggo** [comment]
FWIW I also seem to be encountering this issue. Not using styled-components, but I am doing some hinky stuff with render functions, and cloning children. LMK if it'd be worth making a test case.

Thanks!
