### ISSUE TITLE
Module not found: Error: Can't resolve 'react-art'

### ISSUE THREAD

**Issue by ab-mannan** [necolas/react-native-web#929]
I recently tried this plugin to use one of the react native component to be used in the react web app.

**What is the current behavior?**
It throws an error the following error.

"Module not found: Error: Can't resolve 'react-art'"

Here is the complete stack trace.

`ERROR in ./node_modules/react-native-web/dist/exports/ART/index.js
Module not found: Error: Can't resolve 'react-art' in 'E:\xampp\htdocs\offerengine-react-frontend-new\node_modules\react-native-web\dist\exports\ART'
 @ ./node_modules/react-native-web/dist/exports/ART/index.js 5:16-36
 @ ./node_modules/react-native-web/dist/index.js
 @ ./src/components/OfferPreview/OfferPreview.js
 @ ./src/containers/OffersTable/CreateOffer.js
 @ ./src/components/PageLayout/PageLayout.js
 @ ./src/components/index.js
 @ ./src/containers/App/App.js
 @ ./src/client.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/client.js

ERROR in ./node_modules/react-native-web/dist/modules/injectResponderEventPlugin/index.js
Module not found: Error: Can't resolve 'react-dom/unstable-native-dependencies' in 'E:\xampp\htdocs\offerengine-react-frontend-new\node_modules\react-native-web\dist\modules\injectResponderEventPlugin'
 @ ./node_modules/react-native-web/dist/modules/injectResponderEventPlugin/index.js 11:34-83
 @ ./node_modules/react-native-web/dist/exports/createElement/index.js
 @ ./node_modules/react-native-web/dist/exports/Text/index.js
 @ ./node_modules/react-native-web/dist/index.js
 @ ./src/components/OfferPreview/OfferPreview.js
 @ ./src/containers/OffersTable/CreateOffer.js
 @ ./src/components/PageLayout/PageLayout.js
 @ ./src/components/index.js
 @ ./src/containers/App/App.js
 @ ./src/client.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/client.js`

**If the current behavior is a bug, please provide the steps to reproduce and

1. Installed this plugin as mentioned in the docs
2. Had an error on compiling

**What is the expected behavior?**
I was expecting it to work as mentioned in the docs but somehow it doesn't work.
**Environment (include versions). Did this work in previous versions?**

* Browser: Google Chrome
* React Native for Web (version): ^0.6.1
* React (version): ^15.6.1

**Comment by ab-mannan** [comment]
Apart from this error, i would also like to know that whether the requirement i have is possible or not. So i am posting my requirement here as well..

> Recently I have a requirement where I need to use the react native component in react web app. I have searched and found one component i.e React Native Web.

That converts the react native component to work in react web app. Although I am having some errors but I actually wanted to confirm that whether it is doable to use the react native component in react web app SO that whenever we make changes in React Native Component, that will automatically be handled to be shown in the web. Because for react-native-web, we need to provide the react native file that will be converted into the web view. But how we can make sure that whenever we update the mobile component, changes will automatically be reflected on the web without making any changes.

**Comment by necolas** [comment]
Please read the readme/docs about installing peer dependencies

**Comment by ab-mannan** [comment]
I am not sure about which document you are referring too.  I have gone through [this](https://github.com/necolas/react-native-web) but couldn't find the topic that covers installing peer dependencies. And also can you please answer the question i asked in the comment please. Plus please mention the link as i am unable to find that. Thanks

**Comment by vladp** [comment]
@ab-mannan, React Native components that are referenced by the RNW documentation and [story book](http://necolas.github.io/react-native-web/storybook/?selectedKind=Components&selectedStory=ActivityIndicator&full=0&addons=0&stories=1&panelRight=0)
will work on web.

If you have a custom react native component, that underneath uses *only* RN components that are described in the story book, noted above, then most likely,  your custom react native component, will work on web (or will be at least possible to make some source code changes to it, to work on web).

If your custom react native component uses components/functions that are *not* mentioned in the story book and RNW documentation -- then, most likely, you will have do your own development/code changes (perhaps, non-trivial) -- to get that component to work on web, under RNW
