### ISSUE TITLE
View: guard against flexbox bugs

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#93]
Chrome for one has a bug that can cause flexboxes to grow too tall or tall wide for their containing element. This is usually fixed with `min-height:0` and `min-width:0`. Need to investigate adding these to the default `View` styles.

**Comment by necolas** [comment]
Should be fixed by ad4a6c5be754570202433a084c8b24e63938e975

**Comment by th317erd** [comment]
This is causing issues for me. Nearly every view I have is collapsing to zero width or zero height, and overriding the styles (forcefully) to `minWidth: auto` and `minHeight: auto` instead of zero is fixing the issue for me

**Comment by necolas** [comment]
Are you not using flex:1 or something?

**Comment by th317erd** [comment]
No, `flex: 0` on nearly every parent leading up to the problem. I have a button bar, where the contents of the button decide the size of the bar. It is entirely collapsed.

I found out this isn't the `minHeight`/`minWidth`, but rather the `flexBasis: 0%` (the other issue I put in). Here are some screenshots (for reference) of what things are looking like for me though:

Before (having`minWidth`/`minHeight: 'auto'` does help as you can see... but the real issue ended up being flexBasis: 0%):

![screenshot from 2019-03-02 14-01-38](https://user-images.githubusercontent.com/4420452/53698500-cae87280-3d9a-11e9-8176-195fb0154ca4.png)

After (minWidth/minHeight auto):
![screenshot from 2019-03-02 13-58-10](https://user-images.githubusercontent.com/4420452/53698527-1569ef00-3d9b-11e9-9fb8-11b9c3aa7489.png)

**Comment by necolas** [comment]
Why are you using flex:0 everywhere?

**Comment by th317erd** [comment]
I just said @necolas, because I have a button bar that auto-sizes itself based on the contents of the buttons. It already works fine in RN and on the Web. I moved over to using your library instead of my own shims. There is nothing wrong with using flex: 0 everywhere. It is fully supported in standards, on the web, and in RN. This is a bug and behavior that goes outside of the standards and outside of the normal working of RN, so I would consider that a bug.

**Comment by necolas** [comment]
Yes I'm not suggesting otherwise. This sounded unusual though

> flex: 0 on nearly every parent
