### ISSUE TITLE
Have to set fontSize on each instance of `Text`

### ISSUE THREAD

**Issue by English3000** [necolas/react-native-web#930]
I tried setting a new font size for all text via CSS and noticed that my `Link` component (via `react-router-dom`) resized but my `Text` components didn't. I have to add `style={{fontSize: "1em"}}` to each one to make it adjust.

See: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Text/index.js#L108

**Comment by necolas** [comment]
Yes that's by design. No global styles

**Comment by nealoke** [comment]
@petekp I have implemented this but how do you handle nested Text elements where the wrapper `Text` has an increased `fontSize` or another property that overrides your `styles.baseText`?

Currently I get this as a result
![image](https://user-images.githubusercontent.com/17417414/66488832-e80ebd80-eaae-11e9-9954-816e520deeba.png)
