### ISSUE TITLE
onValueChange not triggered on input based elements for touch events

### ISSUE THREAD

**Issue by mauron85** [necolas/react-native-web#932]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Elements like Switch, Input... doesn't fire `onValueChange` on mobile browsers and Chrome when switched to emulate touch events.

**If the current behavior is a bug, please provide the steps to reproduce and
Not sure if this is needed but issue can be easily reproduced on simple Switch component.

Switch `onValueChange` on mobile browsers and Chrome is not called.

How to reproduce:
1. Create Switch component with onValueChange event handler
2. In Chrome switch to emulate touch events
3. Click on Switch

**What is the expected behavior?**
Switch `onValueChange` will be called

**Environment (include versions). Did this work in previous versions?**
Yes it did. Not sure about exact version number, but version used following [createElement](https://raw.githubusercontent.com/mauron85/react-native-web/extended/src/modules/createElement/index.js) works.
I think problem is related to line: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/createElement/index.js#L56

* OS: Ubuntu 16.04
* Device:
* Browser: Chrome 66
* React Native for Web (version):0.6.1
* React (version):16.3.2

**Comment by necolas** [comment]
I can't reproduce this in the RNW storybook. Switch and onValueChange work as expected in Chrome on my mobile device and when emulating touch events in desktop Chrome on macOS.

**Comment by mauron85** [comment]
Seems to be cause by other plugin messing up with events. Will update if I find the real cause. Closing for now.

**Comment by mauron85** [comment]
Sorry for false report.

**Comment by mauron85** [comment]
I've found conflicting library. It's [nativebase](https://github.com/GeekyAnts/NativeBase). Inputs doesn't trigger `onValueChange` when inside [nativebase List](https://docs.nativebase.io/Components.html#list-def-headref).

Create repo, which demonstrates the issue https://github.com/mauron85/rn-switch-glitch

**Comment by mauron85** [comment]
@necolas I did some additional research and it might be issue with react-native-web after all.

The problem seems to occur when `Switch` component is wrapped with touchable eg. `TouchableHighlight`.

Example:
```
<TouchableHighlight>
  <Switch value={this.state.switch2Enabled} onValueChange={this.toggleSwitch2}/>
</TouchableHighlight>
```
This only works with mouse events. Touch event is not propagated correctly.

Interestly wrapping touchable in another touchable works:
```
<TouchableHighlight>
  <TouchableHighlight onPress={() => console.log('btn pressed')}>
    <View style={styles.btn}>
      <Text>I can be touched</Text>
    </View>
  </TouchableHighlight>
</TouchableHighlight>
```

I've created example you can reproduce this issue: https://grateful-stem.glitch.me/

**Comment by mauron85** [comment]
Reverting createElement to https://raw.githubusercontent.com/mauron85/react-native-web/extended/src/modules/createElement/index.js fixes the problem. So it really seems to be related https://github.com/necolas/react-native-web/commit/893963a79932a4faa79432690858f3504e3c2ba1

**Comment by necolas** [comment]
Try this branch https://github.com/necolas/react-native-web/tree/react-native-web/mouse-event-filter

**Comment by mauron85** [comment]
Hi @necolas. Reading commit comment and previous issues, seems like kind of hard to solve problem, specially not breaking something else. But just tried mouse-event-filter branch and it's seems like fix for this particular issue.
