### ISSUE TITLE
always get Warnings in Chrome

### ISSUE THREAD

**Issue by Xing-He** [necolas/react-native-web#933]
**What is the current behavior?**

many warnings in console and there are the same as below.

```
Warning: React does not recognize the `underlayColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `underlaycolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element

Warning: Received `true` for a non-boolean attribute `borderless`.

If you want to write it to the DOM, pass a string instead: borderless="true" or borderless=
```

**Environment (include versions). Did this work in previous versions?**

* OS: Mac OS
* Browser: Chrome
* React Native for Web (version): 0.5.4 
* React (version): 16.2.0

**Comment by necolas** [comment]
Needs example code

**Comment by zivchen** [comment]
I have an example for this issue, but i think its a problem of the other package owner an not yours, so im putting this here for future searches.
Example:
react native elements, SearchBar component can have noIcon attribute which after using react-native-web gives this warning

> react-dom.development.js?61bb:506 Warning: React does not recognize the `noIcon` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `noicon` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> in input (created by TextInput
> 

Ref to the other package
https://github.com/react-native-training/react-native-elements/tree/master/src/searchbar
