### ISSUE TITLE
View with onLayout method cause 'Unable to find node on an unmounted component'

### ISSUE THREAD

**Issue by ishaba** [necolas/react-native-web#941]
**The problem**
After unmounting component with ```<View onLayout={this.onLayout} />``` we steel have some event listeners for this View that fires ```Invariant Violation: Unable to find node on an unmounted component.```

**How to reproduce**
Test case: https://codesandbox.io/s/xp9780v4jp

Steps to reproduce:
1. Open https://codesandbox.io/s/xp9780v4jp in safari on ios ~~or chrome on adroid~~
2. Click "goto Page B"
3. Click "back to Page A"
4. Try to scroll

```Invariant Violation: Unable to find node on an unmounted component.```

[img_e8407dc8ae19-1](https://user-images.githubusercontent.com/1162501/39873578-a0bb773c-546b-11e8-886b-92746a7d15c0.jpeg)

**Expected behavior**
Should work with no errors

**Environment (include versions). Did this work in previous versions?**
Not tested

* OS: iOS/~~Android~~
* Device: Mobile
* Browser: Safari/~~Chrome~~
* React Native for Web (version): 0.6.1
* React (version): 16.3.2

**Comment by necolas** [comment]
Can't reproduce the issue in chrome for Android

**Comment by ishaba** [comment]
Sorry my bad, didn't test codesandbox on Android, looks like something different cause same error in my project, anyway it constantly reproduces on iOS, here is stack trace ```[Error] Invariant Violation: Unable to find node on an unmounted component.
	invariant (invariant.js:42)
	findCurrentFiberUsingSlowPath (react-dom.development.js:3516)
	findCurrentHostFiber (react-dom.development.js:3624)
	findHostInstance (react-dom.development.js:12750)
	measure (index.js:56)
	_handleLayout (index.js:132)
	(anonymous function) (index.js:52)
	forEach
	triggerAll (index.js:50)
	later (index.js:28)```

where `triggerAll (index.js:50)` it is `react-native-web/dist/ApplyLayout/index.js:50` looks like it happens cos safari on iOS triggers window resize event when hiding address bar

**Comment by ishaba** [comment]
with `0.5.4` works fine

**Comment by ishaba** [comment]
isn't it is related to https://github.com/necolas/react-native-web/pull/939 ?

**Comment by necolas** [comment]
It's not. But it looks like a regression from the introduction of `ResizeObserver`. Don't have time to look into the cause right now /cc @giuseppeg

**Comment by giuseppeg** [comment]
I think it is happening because of https://github.com/necolas/react-native-web/pull/939/files#r186849996 You can reproduce in Firefox stable or any other browser that doesn't support `ResizeObserver`.
