### ISSUE TITLE
Broken layout in Safari

### ISSUE THREAD

**Issue by gHashTag** [necolas/react-native-web#946]
**The problem**
In Safari, the layout is broken, and in all other browsers is normal. In what there can be an error?

**How to reproduce**
http://www.cityretreat.ru/timetable

# Safari
![2018-05-13 21 01 20](https://user-images.githubusercontent.com/6774813/39970233-d67191c2-56f0-11e8-9959-c310c4bcb772.png)

# Chrome
![2018-05-13 21 02 11](https://user-images.githubusercontent.com/6774813/39970249-eece71fe-56f0-11e8-8dd9-4fcaf67125d2.png)

**Expected behavior**
Also, when pressed, incorrect behavior occurs.

**Environment (include versions). Did this work in previous versions?**

* OS: MacOS Sierra
* Device: MacBook
* Browser: Safari 10.1.2
* React Native for Web (version): 0.6.1
* React (version): 16.3.2

**Additional context**
My code:
```javascript
class TimeTable extends Component {
  render() {
    return (
      <View>
        <Header title="Расписание" />
        <View style={{ marginTop: Y(1), marginBottom: 300 }}>
          <Day
            StartDate={moment()}
            EndDate={moment().add(0, 'days').endOf('day')}
          />
          <Day
            StartDate={moment().add(1, 'days').startOf('day')}
            EndDate={moment().add(1, 'days').endOf('day')}
          />
          <Day
            StartDate={moment().add(2, 'days').startOf('day')}
            EndDate={moment().add(2, 'days').endOf('day')}
          />
          <Day
            StartDate={moment().add(3, 'days').startOf('day')}
            EndDate={moment().add(3, 'days').endOf('day')}
          />
          <Day
            StartDate={moment().add(4, 'days').startOf('day')}
            EndDate={moment().add(4, 'days').endOf('day')}
          />
          <Day
            StartDate={moment().add(5, 'days').startOf('day')}
            EndDate={moment().add(5, 'days').endOf('day')}
          />
          <Day
            StartDate={moment().add(6, 'days').startOf('day')}
            EndDate={moment().add(6, 'days').endOf('day')}
          />
        </View>
      </View>
    )
  }
}
```

[Day.js](https://gist.github.com/gHashTag/26d3052752339f32d4b4a892811dd9d1)
[Accardion.js](https://gist.github.com/gHashTag/790cfbf24648a6bc9c0540d67003ab1d)
[Collapsible.js](https://gist.github.com/gHashTag/54d5d422859253c514e31c38f2b8b767)

**Comment by necolas** [comment]
Can you provide a reduced test case please, not just a link to your app?

**Comment by ral51** [comment]
Using Safari 11.0.3 and the given link looks good on my side.

**Comment by gHashTag** [comment]
I apologize - this is my mistake, put not there flex: 1
