### ISSUE TITLE
Unable to stop propogation on Touchable Components inside of a link

### ISSUE THREAD

**Issue by joncursi** [necolas/react-native-web#951]
**The problem**
When rendering a Touchable component inside of a link, the link's `href` will fire in addition to the Touchable's `onPress` handler.

**How to reproduce**
```js
<a href="https://www.google.com" style={{backgroundColor: 'green', padding: 20}}>
  <TouchableHighlight
    onPress={(event) => {
      console.log('Clicked');
      event.stopPropagation();
    }}
  >
    <View>
      <Text>Click me</Text>
    </View>
  </TouchableHighlight>
</a>
```
Steps to reproduce: see above.

**Expected behavior**
In the example above, the browser should not navigate to `https://www.google.com` when clicking on the Text.

**Environment (include versions). Did this work in previous versions?**

* OS: Mac OS High Sierra (10.13.4)
* Device: Macbook Pro
* Browser: Chrome
* React Native for Web (version): 0.6.1
* React (version): 16.3.2

**Comment by necolas** [comment]
I'll take a look but also try to avoid having `a` tags outside rather than inside a Touchable.

**Comment by necolas** [comment]
Yeah the problem here is that you need to call `e.preventDefault()` on events occurring on the `a`. Stopping propagation doesn't work with vanilla DOM or React DOM either, the browser will still perform navigation.

You can do this:

```js
<TouchableHighlight
  href={href}
  onPress={(e) => {
    e.preventDefault();
    // navigate('some-page');
  }}
/>
```

Or make sure the wrapping `a` is set up to preventDefault on events.

**Comment by necolas** [comment]
Related to #970
