### ISSUE TITLE
Different styles react-native && react-native-web

### ISSUE THREAD

**Issue by gHashTag** [necolas/react-native-web#952]
Created two projects with the same code
 
[Reframe ](https://github.com/reframejs/reframe)
 https://github.com/gHashTag/rnw-reframe-flex/blob/master/pages/WelcomePage.config.js
![2018-05-15 21 39 46](https://user-images.githubusercontent.com/6774813/40077135-5e80f55a-5889-11e8-9f96-920cf5099786.png)

React-Native
https://github.com/gHashTag/rnReframeFlex/blob/master/App.js  
![2018-05-15 21 38 53](https://user-images.githubusercontent.com/6774813/40077014-15f338ac-5889-11e8-8bc3-b4557d7a7df3.png)

Why are they not similar in style?

**Comment by cymen** [comment]
https://github.com/necolas/react-native-web/issues/940
