### ISSUE TITLE
The new version does not work - flex: 1

### ISSUE THREAD

**Issue by gHashTag** [necolas/react-native-web#953]
**The problem**
Same problem #940 
I added code in index.html

```html
<body style="height: 100%">
  <div id="root" style='display:flex; height:100%'></div>
</body>
```

but this did not solve the problem

now so:
![2018-05-15_21 39 46](https://user-images.githubusercontent.com/6774813/40133268-eb616888-5947-11e8-8113-2a749787b47d.png)

, but should be like this:
![2018-05-16 19 04 20](https://user-images.githubusercontent.com/6774813/40133241-d53e4210-5947-11e8-89dc-b1ca38179879.png)

**How to reproduce**
[My code](https://github.com/gHashTag/native-web-starter)

* OS: MacOS Sierra
* Device: MacBook Pro (13-inch, Mid 2012)
* Browser: All
* React Native for Web (version): 0.6.1
* React (version): 16.1.1

**Comment by necolas** [comment]
Fix the `html` element too
