### ISSUE TITLE
Firefox crashes with array of styles, works with Object.assign

### ISSUE THREAD

**Issue by msand** [necolas/react-native-web#954]
**The problem**
Firefox crashes when given an array of styles in svgs content, works fine in Chrome. Can be worked around by removing Stylesheet.create and merging the objects into one, causing redundant pressure on memory and gc.

**How to reproduce**
Repo demonstrating issue:
https://github.com/msand/InfiniDraw/tree/1c0dde0d27973ac2ab5395050d56ab4609aa0801
https://infinidraw-dtpllelbcg.now.sh/

Workaround
https://github.com/msand/InfiniDraw/commit/ea5bcf877f67570d5c1aa5b754e6169c11016d59
https://infinidraw-zjiwdgcsln.now.sh/
diff:
https://github.com/msand/InfiniDraw/commit/ea5bcf877f67570d5c1aa5b754e6169c11016d59?diff=split#diff-69d9debdf72cd9b066e7c68525a840d4L252

Example 1:
 ```jsx
const styles = {
   brushIcon: {
     alignSelf: 'center',
   },
 };
 function BrushIcon({ bg, fill, opacity }) {
    return (
      <Svg
        xmlns="http://www.w3.org/2000/svg"
        width="45"
        height="45"
        viewBox="0 0 768 768"
        style={[
          styles.brushIcon,
          {
            opacity,
          },
        ]}
      >
        <Defs>
          <RadialGradient id="grad" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
            <Stop offset="0%" stopColor={bg} stopOpacity="1" />
            <Stop offset="80%" stopColor={bg} stopOpacity="0.8" />
            <Stop offset="100%" stopColor={bg} stopOpacity="0" />
          </RadialGradient>
        </Defs>
        <Rect x="0" y="0" width="768" height="768" fill="url(#grad)" />
        <Path
          fill={fill}
          transform="translate(128, 128)"
          d="M242.544 352.215L464.363 14.398 207.615 325.049zM214.395 412.631l16.2-49.275-30.812-24.546-47.083 24.668zM195.983 422.748s8.397 105.595-148.337 65.945c0 0 26.419-.604 26.266-29.563 0 0 14.5-97.403 76.462-75.981l45.609 39.598z"
        />
      </Svg>
    );
  }
```

0 is read-only

setValueForStyles@http://localhost:3000/_next/static/commons/main.js:26179:7
updateDOMProperties@http://localhost:3000/_next/static/commons/main.js:27263:7
updateProperties$1@http://localhost:3000/_next/static/commons/main.js:27619:3
commitUpdate@http://localhost:3000/_next/static/commons/main.js:28726:7
commitWork@http://localhost:3000/_next/static/commons/main.js:22791:15
commitAllHostEffects@http://localhost:3000/_next/static/commons/main.js:23845:13
callCallback@http://localhost:3000/_next/static/commons/main.js:12537:9
invokeGuardedCallbackDev@http://localhost:3000/_next/static/commons/main.js:12575:7
invokeGuardedCallback@http://localhost:3000/_next/static/commons/main.js:12624:5
commitRoot@http://localhost:3000/_next/static/commons/main.js:23996:9
completeRoot@http://localhost:3000/_next/static/commons/main.js:24939:36
performWorkOnRoot@http://localhost:3000/_next/static/commons/main.js:24889:11
performWork@http://localhost:3000/_next/static/commons/main.js:24807:9
performSyncWork@http://localhost:3000/_next/static/commons/main.js:24784:5
requestWork@http://localhost:3000/_next/static/commons/main.js:24684:7
scheduleWorkImpl@http://localhost:3000/_next/static/commons/main.js:24559:13
scheduleWork@http://localhost:3000/_next/static/commons/main.js:24519:12
scheduleRootUpdate@http://localhost:3000/_next/static/commons/main.js:25147:5
updateContainerAtExpirationTime@http://localhost:3000/_next/static/commons/main.js:25175:12
updateContainer@http://localhost:3000/_next/static/commons/main.js:25202:14
./node_modules/react-dom/cjs/react-dom.development.js/ReactRoot.prototype.render@http://localhost:3000/_next/static/commons/main.js:28506:3
legacyRenderSubtreeIntoContainer@http://localhost:3000/_next/static/commons/main.js:28940:7
render@http://localhost:3000/_next/static/commons/main.js:28980:12
renderReactElement@http://localhost:3000/_next/static/commons/main.js:6452:5
_callee4$@http://localhost:3000/_next/static/commons/main.js:6419:15
tryCatch@http://localhost:3000/_next/static/commons/main.js:32383:37
invoke@http://localhost:3000/_next/static/commons/main.js:32617:22
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/static/commons/main.js:32435:16
step@http://localhost:3000/_next/static/commons/main.js:166:22
_next@http://localhost:3000/_next/static/commons/main.js:181:9
_asyncToGenerator/</<@http://localhost:3000/_next/static/commons/main.js:188:7
Promise@http://localhost:3000/_next/static/commons/main.js:3255:7
_asyncToGenerator/<@http://localhost:3000/_next/static/commons/main.js:161:12
doRender@http://localhost:3000/_next/static/commons/main.js:6361:10
_callee2$@http://localhost:3000/_next/static/commons/main.js:6267:20
tryCatch@http://localhost:3000/_next/static/commons/main.js:32383:37
invoke@http://localhost:3000/_next/static/commons/main.js:32617:22
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/static/commons/main.js:32435:16
step@http://localhost:3000/_next/static/commons/main.js:166:22
_next@http://localhost:3000/_next/static/commons/main.js:181:9
_asyncToGenerator/</<@http://localhost:3000/_next/static/commons/main.js:188:7
Promise@http://localhost:3000/_next/static/commons/main.js:3255:7
_asyncToGenerator/<@http://localhost:3000/_next/static/commons/main.js:161:12
render@http://localhost:3000/_next/static/commons/main.js:6239:10
_callee$/<@http://localhost:3000/_next/static/commons/main.js:6210:13
notify/<@http://localhost:3000/_next/static/commons/main.js:8716:16
./node_modules/core-js/library/modules/_collection.js/module.exports/</<@http://localhost:3000/_next/static/commons/main.js:1316:22
notify@http://localhost:3000/_next/static/commons/main.js:8715:7
update@http://localhost:3000/_next/static/commons/main.js:8127:9
./pages/index.js/</<@http://localhost:3000/_next/-/page/index.js:34144:11
./pages/index.js/<@http://localhost:3000/_next/-/page/index.js:34131:6
./pages/index.js@http://localhost:3000/_next/-/page/index.js:34024:29
__webpack_require__@http://localhost:3000/_next/static/commons/manifest.js:715:13
hotApply@http://localhost:3000/_next/static/commons/manifest.js:637:14
cb@http://localhost:3000/_next/static/commons/main.js:37416:25
check/<@http://localhost:3000/_next/static/commons/main.js:37432:13

    in svg (created by Svg)
    in Svg (at drawing.js:247)
    in div (created by View)
    in View (created by TouchableOpacity)
    in TouchableOpacity (at drawing.js:423)
    in div (created by View)
    in View (at drawing.js:422)
    in div (created by View)
    in View (at drawing.js:410)
    in div (created by View)
    in View (at drawing.js:391)
    in App (created by Mutation)
    in Mutation (created by Apollo(App))
    in Apollo(App) (created by Query)
    in Query (created by Apollo(Apollo(App)))
    in Apollo(Apollo(App)) (at index.js:23)
    in Root (at _app.js:13)
    in ApolloProvider (at _app.js:12)
    in Container (at _app.js:11)
    in App (at with-apollo-client.js:67)
    in withApollo(App)
    in AppContainer

Example 2:
https://github.com/msand/InfiniDraw/commit/ea5bcf877f67570d5c1aa5b754e6169c11016d59?diff=split#diff-c64aef9b30e33dd3b13558f94cf9ebc5L40

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Svg, Rect, LinearGradient, Defs, Stop } from 'svgs';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
});

const Gradient = ({
  name,
  style,
  gradientSteps,
  maximumValue,
  getStepColor,
}) => {
  const rows = [];
  for (let i = 0; i <= gradientSteps; i++) {
    const ratio = i / gradientSteps;
    rows.push(
      <Stop
        key={i}
        offset={`${ratio * 100}%`}
        stopColor={getStepColor(ratio * maximumValue)}
      />,
    );
  }
  const id = `Gradient${name}`;
  return (
    <Svg
      width="100%"
      height="100%"
      viewBox="0 0 100 100"
      preserveAspectRatio="none"
      style={[styles.container, style]}
    >
      <Defs>
        <LinearGradient id={id}>{rows}</LinearGradient>
      </Defs>
      <Rect x="0" y="0" width="100" height="100" fill={`url(#${id})`} />
    </Svg>
  );
};

export default Gradient;

Gradient.propTypes = {
  gradientSteps: PropTypes.number.isRequired,
  maximumValue: PropTypes.number.isRequired,
  getStepColor: PropTypes.func.isRequired,
};
```

CSS2Properties doesn't have an indexed property setter for '0'

setValueForStyles@http://localhost:3000/_next/static/commons/main.js:26179:7
setInitialDOMProperties@http://localhost:3000/_next/static/commons/main.js:27220:7
setInitialProperties$1@http://localhost:3000/_next/static/commons/main.js:27412:3
finalizeInitialChildren@http://localhost:3000/_next/static/commons/main.js:28676:5
completeWork@http://localhost:3000/_next/static/commons/main.js:21814:19
completeUnitOfWork@http://localhost:3000/_next/static/commons/main.js:24108:20
performUnitOfWork@http://localhost:3000/_next/static/commons/main.js:24268:14
workLoop@http://localhost:3000/_next/static/commons/main.js:24280:26
renderRoot@http://localhost:3000/_next/static/commons/main.js:24311:9
performWorkOnRoot@http://localhost:3000/_next/static/commons/main.js:24886:24
performWork@http://localhost:3000/_next/static/commons/main.js:24807:9
performSyncWork@http://localhost:3000/_next/static/commons/main.js:24784:5
interactiveUpdates@http://localhost:3000/_next/static/commons/main.js:25034:9
interactiveUpdates@http://localhost:3000/_next/static/commons/main.js:14395:10
dispatchInteractiveEvent@http://localhost:3000/_next/static/commons/main.js:16696:3

    in rect (created by Rect)
    in Rect (at Gradient.js:45)
    in svg (created by Svg)
    in Svg (at Gradient.js:35)
    in Gradient (at HueGradient.js:12)
    in HueGradient (at HueSlider.js:10)
    in div (created by View)
    in View (at GradientSlider.js:41)
    in div (created by View)
    in View (at GradientSlider.js:40)
    in GradientSlider (at HueSlider.js:9)
    in HueSlider (at picker.js:362)
    in div (created by View)
    in View (at picker.js:361)
    in div (created by View)
    in View (at picker.js:332)
    in div (created by View)
    in View (at picker.js:331)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at fade.js:53)
    in Fade (at picker.js:324)
    in SlidersColorPicker (at drawing.js:459)
    in div (created by View)
    in View (at drawing.js:458)
    in div (created by View)
    in View (at drawing.js:366)
    in App (created by Mutation)
    in Mutation (created by Apollo(App))
    in Apollo(App) (created by Query)
    in Query (created by Apollo(Apollo(App)))
    in Apollo(Apollo(App)) (at index.js:23)
    in Root (at _app.js:13)
    in ApolloProvider (at _app.js:12)
    in Container (at _app.js:11)
    in App (at with-apollo-client.js:67)
    in withApollo(App)
    in AppContainer

Steps to reproduce:
1. Give array of styles to svgs content
2. Firefox crashes

**Expected behavior**
No exceptions, and allowing the same code using Stylesheet create and arrays of styles to work with svgs content in firefox the same way as in Chrome.

**Environment (include versions). Did this work in previous versions?**
Latest versions, nothing outdated, don't know if it worked before.
* OS: MacOS 10.13.3
* Device: MacBook Pro
* Browser: Firefox Quantum 60.0 (64-bit)
* React Native for Web (version): 0.6.1
* React (version): 16.3.2

**Comment by msand** [comment]
I just realised this might belong in the svgs repo, not really sure, as it works in Chrome.

**Comment by necolas** [comment]
Yes this is a bug in the svg's repo and one of the reasons I asked for react-native-svg to bake in web support instead. The svg repo is not exporting components with the RN API. To do so requires wrapping React DOM components like this https://github.com/necolas/react-native-web/blob/master/website/guides/advanced.md#use-with-existing-react-dom-components
