### ISSUE TITLE
'react-native' does not contain an export named

### ISSUE THREAD

**Issue by soyjavi** [necolas/react-native-web#958]
**The problem**
I think you forgot to export this class. In previous versions of `react-native-web` was included.

**How to reproduce**
`import { Platform, Share } from 'react-native';`

**Expected behavior**
I know `Share` is not functional in `react-native-web` but at least should be return an `empty object`.

**Environment (include versions). Did this work in previous versions?**
YES, worked in previous versions.

* OS: all
* Device: all
* Browser: all
* React Native for Web (version): 0.7.2
* React (version): 16.3.2

**Comment by necolas** [comment]
I don't think previous versions worked.

**Comment by vladp** [comment]
same problem https://github.com/necolas/react-native-web/issues/967

**Comment by brunolemos** [comment]
### Workaround

Use [patch-package](https://github.com/ds300/patch-package) to comment the lines that are causing the issue:

```diff
diff --git a/node_modules/react-native-vector-icons/lib/create-icon-set.js b/node_modules/react-native-vector-icons/lib/create-icon-set.js
index 019313b..5b93bf2 100644
--- a/node_modules/react-native-vector-icons/lib/create-icon-set.js
+++ b/node_modules/react-native-vector-icons/lib/create-icon-set.js
@@ -9,8 +9,8 @@ import {
 } from './react-native';
 
 import createIconButtonComponent from './icon-button';
-import createTabBarItemIOSComponent from './tab-bar-item-ios';
-import createToolbarAndroidComponent from './toolbar-android';
+// import createTabBarItemIOSComponent from './tab-bar-item-ios';
+// import createToolbarAndroidComponent from './toolbar-android';
 
 const NativeIconAPI =
   NativeModules.RNVectorIconsManager || NativeModules.RNVectorIconsModule;
@@ -164,6 +164,7 @@ export default function createIconSet(glyphMap, fontFamily, fontFile) {
   }
 
   Icon.Button = createIconButtonComponent(Icon);
+  /*
   Icon.TabBarItem = createTabBarItemIOSComponent(
     IconNamePropType,
     getImageSource
@@ -173,6 +174,7 @@ export default function createIconSet(glyphMap, fontFamily, fontFile) {
     IconNamePropType,
     getImageSource
   );
+  */
   Icon.getImageSource = getImageSource;
   Icon.loadFont = loadFont;
   Icon.hasIcon = hasIcon;

```

**Comment by xiamingyu** [comment]
'react-native' does not contain an export named 'LayoutAnimation'.
Has all familiar problems been fixed？@necolas
