### ISSUE TITLE
0.7.2 probably module error

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#961]
I updated https://github.com/este/este to RNW 0.7.2

I don't know why dist is still imported. Any hint would be appreciated. Is Webpack 4 required? Or? Thank you.

![screen shot 2018-05-21 at 23 13 44](https://user-images.githubusercontent.com/66249/40330265-adc45c84-5d4c-11e8-9c51-6c2d0c6ca3d3.png)

**Comment by necolas** [comment]
You need to provide more information if you expect to get help.

What is this? Your build step? Your test suite? Did you clear the Babel cache? etc

**Comment by steida** [comment]
It's https://github.com/este/este/blob/master/package.json#L20 You can see I always clear babel cache.

**Comment by necolas** [comment]
Ah, it's because `babel-plugin-react-native-web` is rewriting the paths to point to the ES modules. Removing the plugin should fix things and it's not needed if you're using a modern bundler. But I need to update the plugin it to so that it can be configured to rewrite the paths to ES _or_ CJS modules.

Looks like you might want to remove it from the native babel config too: https://github.com/este/este/blob/master/.babelrc.native#L12

**Comment by steida** [comment]
I removed babel plugin, update to 0.7, and then

```
index.js:368 Module not found: Error: Can't resolve 'AccessibilityInfo' in '/Users/steida/dev/este/node_modules/react-native/Libraries/react-native'
ModuleNotFoundError: Module not found: Error: Can't resolve 'AccessibilityInfo' in '/Users/steida/dev/este/node_modules/react-native/Libraries/react-native'
    at factoryCallback (/Users/steida/dev/este/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/steida/dev/este/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/Users/steida/dev/este/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/Users/steida/dev/este/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /Users/steida/dev/este/node_modules/async/dist/async.js:3888:9
    at /Users/steida/dev/este/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/steida/dev/este/node_modules/async/dist/async.js:1062:13)
    at /Users/steida/dev/este/node_modules/async/dist/async.js:969:16
    at /Users/steida/dev/este/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/Users/steida/dev/este/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/Users/steida/dev/este/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/steida/dev/este/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/steida/dev/este/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/steida/dev/este/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/steida/dev/este/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/steida/dev/este/node_modules/tapable/lib/Tapable.js:252:11)
```

**Comment by steida** [comment]
![screen shot 2018-05-22 at 01 34 04](https://user-images.githubusercontent.com/66249/40334804-3d7c414e-5d60-11e8-8f44-1ea0bb1f69cc.png)

**Comment by necolas** [comment]
The stack-trace is showing that you haven't aliased `react-native` to `react-native-web`

**Comment by steida** [comment]
Because you told me to remove babel-plugin-react-native-web. I am confused. Is it required or not? Should I import from react native web instead? Or?

**Comment by necolas** [comment]
You need to alias the package https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md

**Comment by steida** [comment]
It looks like, something requires file without webpack nor babel processed... hmm.

![screen shot 2018-05-22 at 18 08 07](https://user-images.githubusercontent.com/66249/40375174-1faa5d64-5deb-11e8-9c75-872de89ac6fd.png)

**Comment by necolas** [comment]
I don't have time to debug your project. The stacktrace shows that it is still importing from `react-native`, which means you haven't aliased the package to `react-native-web`. Use something like this for Babel https://www.npmjs.com/package/babel-plugin-module-resolver

**Comment by steida** [comment]
In case some other person is reading this. It seems babel-plugin-module-resolver has the same problem as webpack alias. I don't know why yet. Investigating.

![screen shot 2018-05-22 at 20 27 35](https://user-images.githubusercontent.com/66249/40382388-9e1b7fbc-5dfe-11e8-938f-6af7cdee69b2.png)

**Comment by steida** [comment]
I am pretty sure it's a bug in React Native Web.

**Comment by necolas** [comment]
Stacktrace can help you see that the problem is…not here.

```
Could not resolve "react-native-web/Libraries/StyleSheet/StyleSheet" in…
```

That's because you have [this kind of import](https://github.com/este/este/blob/6dadbd8ea54e072935229eedff41180ddc3d62b5/components/core/Block.js#L5) reaching into React Native itself.

```js
import type { ViewStyleProp } from 'react-native/Libraries/StyleSheet/StyleSheet';
``` 

If you want to keep those imports of React Native *internals*, you need to configure the aliasing properly. Look at the docs to see you can use a [regex](https://github.com/tleunen/babel-plugin-module-resolver/blob/HEAD/DOCS.md#alias) for exact matches, e.g.,

```json
{
  "^react-native$": "react-native-web"
}
```

**Comment by steida** [comment]
OMG it works. Thank you very much. Do you accept Bitcoin?

**Comment by MrLoh** [comment]
For anyone else hitting this issue. The latest version of `babel-plugin-react-native-web` has an option to enable commonjs that fixes this error. Just use: 

```json
"plugins": [
  ["react-native-web", {"commonjs": true}]
]
```
