### ISSUE TITLE
Image's source prop handling inconsistent

### ISSUE THREAD

**Issue by sidhu663** [necolas/react-native-web#962]
**The problem**
Image component's `source` prop accepts both strings and objects but when providing an object, and empty string uri cannot be provided.

1. `<Image source="" />` vs 
2. `<Image source={{ uri: '' }}`

The second case results in an error because it falls into the `uri = source || ''` case in this code in image:

```
  let uri;
  if (typeof source === 'number') {
    // get the URI from the packager
    const asset = getAssetByID(source);
    const scale = asset.scales[0];
    const scaleSuffix = scale !== 1 ? `@${scale}x` : '';
    uri = asset ? `${asset.httpServerLocation}/${asset.name}${scaleSuffix}.${asset.type}` : '';
  } else if (source && source.uri) {
    uri = source.uri;
  } else {
    uri = source || '';
  }

 const match = uri.match(svgDataUriPattern);
```

so `uri` ends up being an object which has no `match` function

**How to reproduce**
Test case: 

Steps to reproduce:
1.
2.
3.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* OS:
* Device:
* Browser:
* React Native for Web (version):
* React (version):

**Additional context**

**Comment by sidhu663** [comment]
Yea `<Image source={{ url: '' }} />` will cause an error since `uri = source || ''` => `typeof uri === 'object'`

**Comment by necolas** [comment]
`{ url: '' }` will hit the second condition. But an empty object produces an error

**Comment by sidhu663** [comment]
It won't hit the second condition since the empty string is falsy

**Comment by necolas** [comment]
Oh yeah :)
