### ISSUE TITLE
jest snapshot serializer importing from 'dist' in version 0.7.2

### ISSUE THREAD

**Issue by sidhu663** [necolas/react-native-web#963]
**The problem**
I'm not 100% sure this is a bug but I think it probably is:
Given the following config (without using react-native-web babel plugin, using webpack 2):

```
// jest.config.js
{
  snapshotSerializers: ['enzyme-to-json/serializer', 'react-native-web/jest/serializer'],
  "transformIgnorePatterns": ["node_modules/(?!react-native-web)"],
  "moduleNameMapper": {
    "react-native": "<rootDir>/node_modules/react-native-web"
  },
}
```
Jest snapshots fail since the jest serializer is using StyleSheet from `const { StyleSheet } = require('../dist');`, whereas the components render using the ES6 StyleSheet built by webpack resulting in 2 different registries. 

**How to reproduce**
Test case: 

Steps to reproduce:
1.
2.
3.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* OS: osX
* Device:
* Browser:
* React Native for Web (version): 0.7.2
* React (version): 16.2

**Additional context**

**Comment by necolas** [comment]
Yeah sounds right.

Related to https://github.com/necolas/react-native-web/issues/928

What I'm thinking of doing is removing the serializer and making `StyleSheet.create` the identity function when `NODE_ENV==='test'`. That will be simpler (and work for either cjs or esm) and retain the array of styles in the snapshot. Eventually can provide this as part of a jest preset like React Native's that does things like mock out `View` too.

**Comment by agalatan** [comment]
I got some very good results with this: 
- In a mock file for RNW (```<rootDir>/mocks/react-native-web.js```)
```jest.mock('react-native', () => {
  const ReactNativeWeb = require.requireActual('react-native');
  const StyleSheet = ReactNativeWeb.StyleSheet;

  Object.assign(ReactNativeWeb.StyleSheet, {
    create: StyleSheet.flatten
  });

  return ReactNativeWeb;
});
```
And in jest config:
```
moduleNameMapper: {
  '^react-native$': '<rootDir>/node_modules/react-native-web'
},
setupFiles: {
  <rootDir>/mocks/react-native-web
}
```
Hope there's no caching somewhere that's playing me tricks.
I wasn't very happy with `identity` for StyleSheet.create, because I ended up with things like ```Array[{ color: 'black' }, { color: 'white' }]```, or even the constant `1`(which I think is the absolute fill)
