### ISSUE TITLE
How should I get data from urls via react-navigation

### ISSUE THREAD

**Issue by Pneumatic95** [necolas/react-native-web#965]
**The problem**
My app project use` react-navigation`, in react-native-web, how can I get the data that I want through `path`, or have other api..?

router.js
```javascript
import {StackNavigator, NavigationActions} from 'react-navigation/lib/react-navigation.js';
import { enhance } from './dependence/react-native-addons'
const myApp = enhance(StackNavigator){
  ProductDetailPage:{
    screen: ProductDetailPage,
    path: 'product/:packIdEn',
  }
}
```
ProductDetailPage.js
```javascript
class ProductDetailPage extends Component {
  constructor(props) {
    super(props);
    console.log('props', props);
  }
}
```
![tm20180523180438](https://user-images.githubusercontent.com/20735608/40418124-14c18bce-5eb4-11e8-967b-36dfaf54bb8c.png)

In the props, it shows `props.navigation.state` contain some data. Is there any way I can get `packIdEn` here?

**Environment (include versions). Did this work in previous versions?**

* OS: Windows 7
* Device:
* Browser: Chrome 66.0.3359.181
* React Native for Web (version):  0.5.4
* React (version): 16.0.0-alpha.12
* React Navigation (version):1.0.0-beta.22

**Additional context**
Thank you

**Comment by necolas** [comment]
This is something you should ask the `react-navigation` project. I think it added web support only in v2.0.0 or master
