### ISSUE TITLE
Using middle-click / cmd(or ctrl)-click, with onPress

### ISSUE THREAD

**Issue by Frexuz** [necolas/react-native-web#970]
I don't understand how to combine these two :)

**Is your feature request related to a problem? Please describe.**
WIth normal `<a>` tags (href), you can use javascript to handle it's click, with `preventDefault()`.
Yet you can still ctrl/middle-click to open links in a new tab.

**Describe a solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

```
class X extends Component {
  localeUrl = (locale) => {
    const path = history.location.pathname
    return path.replace(/[a-z]{2}-[a-z]{2}/, locale)
  }
  changeLocale = (locale, event) => {
    if (event) {
      event.preventDefault()
    }
    history.push(this.localeUrl(locale))
  }

  render () {
    return (
       <TouchableWithoutFeedback accessibilityRole="link" href={this.localeUrl('en-gb')} onPress={(event) => this.changeLocale('en-gb', event)} style={styles.link}>English</TouchableWithoutFeedback>
        </Row>
      </View>
    )
  }
}
```

This doesn't seem to work, as the page reloads. What am I doing wrong? And is there a simpler way? Seems awfully a lot of code to do for every clickable component..

**Comment by necolas** [comment]
I think what I can do is cancel click events (without modified keys) on an element that is using the responder event system. That will mean that pressing a `Touchable*` that's being overloaded as a link will behave as it does on iOS/Android: no navigation. Instead, that can be done explicitly in response to press…something like this:

```js
<TouchableOpacity
  accessibilityTraits="link"
  href={href}
  onPress={(e) => {
    Linking.openUrl(href);
  }}
/>
```

In your case it would be:

```js
class X extends Component {
  localeUrl = (locale) => {
    const path = history.location.pathname
    return path.replace(/[a-z]{2}-[a-z]{2}/, locale)
  }
  changeLocale = (locale, event) => {
    history.push(this.localeUrl(locale))
  }
  render () {
    return (
      <TouchableWithoutFeedback
         accessibilityRole="link"
         href={this.localeUrl('en-gb')}
         onPress={(event) => this.changeLocale('en-gb', event)}
         style={styles.link}
       >
         {this.props.children}
       </TouchableWithoutFeedback>
    )
  }
}
```

It might also be nice to allow the underlying `LinkingManager` to be redefined, if people want to do custom work (logging, navigation) each time a link is opened in the app.

**Comment by Frexuz** [comment]
That would be cool :)

**Comment by bzamora** [comment]
Hi @necolas 

Has the behavior quoted below changed? I just updated to v0.14.10 and TouchableOpacity with href="/xroute" doesn't seem to be cancelled any longer on web. 

Thanks!

> I think what I can do is cancel click events (without modified keys) on an element that is using the responder event system. That will mean that pressing a `Touchable*` that's being overloaded as a link will behave as it does on iOS/Android: no navigation. Instead, that can be done explicitly in response to press…something like this:
> 
> ```js
> <TouchableOpacity
>   accessibilityTraits="link"
>   href={href}
>   onPress={(e) => {
>     Linking.openUrl(href);
>   }}
> />
> ```
