### ISSUE TITLE
error when added fast image plugin.

### ISSUE THREAD

**Issue by roysG** [necolas/react-native-web#973]
I get error on build:

ERROR in ./node_modules/react-native/Libraries/Image/resolveAssetSource.js
Module not found: Error: Can't resolve 'AssetRegistry' in '/Users/xxx/www/aaa/app/node_modules/react-native/Libraries/Image'
 @ ./node_modules/react-native/Libraries/Image/resolveAssetSource.js 1:31-55
 @ ./node_modules/react-native-fast-image/index.js
 @ ./components/boxGame.js
 @ ./components/games.js
 @ ./home.js
 @ ./App.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server regenerator-runtime/runtime ./index.web.js

ERROR in ./node_modules/react-native/Libraries/Image/resolveAssetSource.js
Module not found: Error: Can't resolve 'AssetSourceResolver' in '/Users/xxx/www/aaa/app/node_modules/react-native/Libraries/Image'
 @ ./node_modules/react-native/Libraries/Image/resolveAssetSource.js 1:80-110
 @ ./node_modules/react-native-fast-image/index.js
 @ ./components/boxGame.js
 @ ./components/games.js
 @ ./home.js
 @ ./App.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server regenerator-runtime/runtime ./index.web.js

ERROR in ./node_modules/react-native/Libraries/Image/resolveAssetSource.js
Module not found: Error: Can't resolve 'NativeModules' in '/Users/xxx/www/aaa/app/node_modules/react-native/Libraries/Image'
 @ ./node_modules/react-native/Libraries/Image/resolveAssetSource.js 1:1324-1348
 @ ./node_modules/react-native-fast-image/index.js
 @ ./components/boxGame.js
 @ ./components/games.js
 @ ./home.js
 @ ./App.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server regenerator-runtime/runtime ./index.web.js
ℹ ｢wdm｣: Failed to compile.

OS:MAC
Browser:CHROME
RN WEB :0.51.4
React: 16.4.0

Any reason why?

**Comment by necolas** [comment]
Looks like because `react-native-fast-image` is native-only, and is depending on internals of the `react-native` package. You can't use it on web
