### ISSUE TITLE
Is Twitter and React Native's Doc Using this Framework?

### ISSUE THREAD

**Issue by turtlegood** [necolas/react-native-web#974]
**Is your feature request related to a problem? Please describe.**
I have seen some webpages saying that `Twitter` is a native app, instead of building on react native (see here: https://www.quora.com/On-which-framework-is-the-Twitter-app-built-on-React-Native-Ionic-etc). In addition, by examining the dom of react native doc, I find that it does not use any react framework. However, in the readme documentation, it says that "Who is using React Native for Web? Twitter, ..., , React Native's documentation.". Therefore, I am quite confused by the doc and the webpages. I would appreciate it if I could be informed whether twitter and react native documentation use the `react native for web` or not? Thank you very much!

**Describe a solution you'd like**
...

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by necolas** [comment]
Twitter's web app uses RN: m.twitter.com. React Native's docs have some embedded iframes running RN examples on web

**Comment by turtlegood** [comment]
OK. Thank you very much! However, I am still a little bit confused: why does twitter's web app use *react native for web* instead of the normal *react*? Thank you very much!

**Comment by turtlegood** [comment]
@necolas

**Comment by steida** [comment]
@turtlegood The repo maintainer is not your slave. Use Google.

**Comment by turtlegood** [comment]
@steida sorry for my question, although I still found few things about comparison between react native web and react ...
