### ISSUE TITLE
new `stylelint` support.

### ISSUE THREAD

**Issue by gucong3000** [necolas/react-native-web#975]
I am working on `stylelint` and `postcss` that support `StyleSheet` in `react-native`.
I need more testing and feedback. Can someone help me?
All you need to do is just install [postcss-jsx](https://github.com/gucong3000/postcss-jsx)

```bash
npm install --save-dev stylelint/stylelint postcss-jsx
stylelint **/*.{js,jsx,css}
```

**Comment by necolas** [comment]
You might want to ask for feedback on stackoverflow or twitter
