### ISSUE TITLE
IE11 opens blank

### ISSUE THREAD

**Issue by pinkyblue** [necolas/react-native-web#976]
**The problem**
A clear and concise description of the bug or problem.

**How to reproduce**
Test case: 

Steps to reproduce:
1.
2.
3.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* OS:
* Device:
* Browser:IE11
* React Native for Web (version):0.6.1
* React (version):16.3.2

**Additional context**

The project running on IE11 opens blank， shows normal in other browsers，I wonder why and how to solve it

**Comment by necolas** [comment]
This project's storybook works in IE11. I can't guess what the problem is in your project.
