### ISSUE TITLE
`ListFooterComponent` looks invalid

### ISSUE THREAD

**Issue by Pneumatic95** [necolas/react-native-web#977]
**The problem**
The `FlatList` component's `ListFooterComponent` property looks invalid, it doesn't work

**Environment (include versions). Did this work in previous versions?**
* OS: Windows 7
* Device:
* Browser: Chrome 66.0.3359.181
* React Native for Web (version):  0.5.4
* React (version): 16.0.0-alpha.12

**Comment by necolas** [comment]
This will be fixed in 0.8.0
