### ISSUE TITLE
Default global component props?

### ISSUE THREAD

**Issue by Frexuz** [necolas/react-native-web#978]
**Is your feature request related to a problem? Please describe.**
For custom fonts, we don't really want to specify `{{ fontFamily: ... }}` on every single `<Text>`, so we use https://github.com/Ajackster/react-native-global-props

Would it be possible to add this as a feature? I think it's pretty brilliant, and doesn't break react's recommendation of global css styling.

**Describe a solution you'd like**

Current solution with `react-native-global-props` (in react-native). 

```
import {
  setCustomText,
  setCustomTouchableOpacity,
  setCustomTouchableHighlight
} from 'react-native-global-props'
import { Colors } from '../theme'

const customTextProps = {
  style: {
    fontSize: 14,
    fontFamily: 'Nunito-Regular'
  }
}

const customTouchableOpacityProps = {
  activeOpacity: 0.9
}

const customTouchableHightlightProps = {
  underlayColor: Colors.specials.highlightUnderlayColor
}

export function setupGlobalStyles () {
  setCustomText(customTextProps)
  setCustomTouchableOpacity(customTouchableOpacityProps)
  setCustomTouchableHighlight(customTouchableHightlightProps)
}
```

**Describe alternatives you've considered**

I've tried copying the above package's solution:

(Test)
```
const TextRender = Text.prototype.render
Text.prototype.render = function render () {
  let oldProps = this.props
  this.props = { ...this.props, style: [{ fontFamily: 'Nunito' }, this.props.style] }
  try {
    return TextRender.apply(this, arguments)
  } finally {
    this.props = oldProps
  }
}
```
But element style overrides your re-written css-classes.
![screen shot 2018-05-30 at 16 32 21](https://user-images.githubusercontent.com/49692/40709174-fc6c81a4-6427-11e8-807c-02385dfb658c.png)

**Additional context**

The only alternative we have right now is to do a wrapper component:
```
import React, { Component } from 'react'
import { Text } from 'react-native'

class Text extends Component {
  render () {
    return (
      <Text style={{ fontFamily: 'Nunito' }} {...this.props}>{this.children}</Text>
    )
  }
}

export default Text
```

But then we'll have to rewrite all our `import { Text } from 'react-native'` to like `import { Text } from '../components/typography/Text'` 
A little annoying and breaks our current habits or using `Text` from rn/rn-web :)

**Comment by necolas** [comment]
I don't know where those classnames in your screenshot come from, but they aren't from RNW

**Comment by necolas** [comment]
You should also define static styles using StyleSheet.

I don't think there's anything preventing that package from being used with RNW. If you're using a CSS-in-JS in addition, that might be the problem

**Comment by Frexuz** [comment]
Thanks for the answer. I'll investigate more :)
