### ISSUE TITLE
Clipboard doesn't preserve linebreaks

### ISSUE THREAD

**Issue by kyle-ssg** [necolas/react-native-web#979]
**The problem**
Use Clipboard.setText("any multiline \n text"); 

Clipboard is set to "any multiline text"

This can be fixed by adding ```node.style["white-space"] = "pre-wrap";``` before the following line:
https://github.com/necolas/react-native-web/blob/392de22992d69f7718e2694cdceedca4f9ca0d52/packages/react-native-web/src/exports/Clipboard/index.js#L32

**Comment by paularmstrong** [comment]
If you use carriage returns, it will work correctly as well:

```js
Clipboard.setText("any multiline \r\n text");
```
