### ISSUE TITLE
Fill 100% vertical space

### ISSUE THREAD

**Issue by derolf** [necolas/react-native-web#980]
I have a simple flexbox at the root of the application:

`<View  style={{flex: 1,  backgroundColor: "#000000"}}></View>`

How can I achieve that the View covers the entire vertical space?

**Comment by necolas** [comment]
Check out this demo https://codesandbox.io/s/52x1871vjl

**Comment by derolf** [comment]
Wow! Thank you so much!

**Comment by hedikasmanto** [comment]
Hi.. I think, that workaround should be added into getting started guide
