### ISSUE TITLE
[question] How to run android with the create-react-app starter pack?

### ISSUE THREAD

**Issue by Noboxulus** [necolas/react-native-web#983]
I am new to this, sorry if this is the wrong place to ask.

But I referred to the [Getting started guide](https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md) and did `yarn install react react-dom react-native-web` with `create-react-app my-app` as recommended.

I managed to get the web version working by using `npm start` which basically calls `react-scripts start`.

However I can't seem to run the project for mobile app (eg: android).

I tried the below to no avail:
1. `react-native run-android`
2. `react-native-scripts android`

I tried googling but I cannot seem to find the solutions/ tutorials that I want/need besides the templates other people created. I am hoping to be able to use the `create-react-app` or `create-react-native-app` or `react-native web (without template)` instead if possible.

I'd appreciate it if you could let me know if I am using `react-native-web` correctly with `create-react-app` or if you could so kindly give me a quick start guide to create a `react-native-web` project.

**Comment by necolas** [comment]
Use create react native app for multiplatform apps
https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#starter-kits

**Comment by cymen** [comment]
Some files got moved around -- correct link at moment is:

https://github.com/necolas/react-native-web/blob/master/packages/website/guides/getting-started.md#starter-kits
