### ISSUE TITLE
Switch is buggy in example app

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#985]
**The problem**
In the example app, `<Switch>` is only functional on the first press. The same problem is not present in the storybook app.

**How to reproduce**
https://necolas.github.io/react-native-web/examples/

Steps to reproduce:
1. Go to `<Switch>` screen
2. Press a switch
3. Try pressing it again

**Expected behavior**
`<Switch>` should toggle after first press.

**Environment (include versions). Did this work in previous versions?**
React Native for Web (version): 0.8.0. It worked during development of 0.8.0 but I may have broken something recently.

**Comment by necolas** [comment]
Caused by c33699595281416d67faa1d380b7dba812bd8ebe

**Comment by jpstrikesback** [comment]
Thanks for fixing this! Was also affecting file input fields I believe (Although I couldn't reproduce in a codesandbox oddly - this works -> https://codesandbox.io/s/pk1yvn9o10 just not on my machine :D ). After 0.8.1 all is well in file input fields as well.
