### ISSUE TITLE
autoFocus on TextInput stops onSelectionChange

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#988]
**The problem**
I have a TextInput component with onSelectionChange. When I add autoFocus, onSelectionChange isn't dispatched anymore.

**How to reproduce**
I will: Test case: 

Steps to reproduce:
1. Add autoFocus
2. Write some text. onSelectionChange isn't dispatched anymore.

**Expected behavior**
autoFocus should not break onSelectionChange.

**Comment by steida** [comment]
Hmm, I am not sure what I am doing wrong, but controlled selection break typing. Cursor is always moved at first index.

![screen shot 2018-06-10 at 03 37 47](https://user-images.githubusercontent.com/66249/41197461-c5c0696e-6c5f-11e8-835e-ef1f512feaf0.png)

**Comment by necolas** [comment]
I'll reopen this when it includes a reduced test case on codesandbox, as requested in the issue template.

**Comment by steida** [comment]
Sure.

**Comment by necolas** [comment]
Please can you include that test case? What's the hold up?

**Comment by steida** [comment]
I am not using autoFocus anymore because it's not imperative. No time to investigate it further :(

**Comment by necolas** [comment]
You can't even take a moment to put together a test case?

**Comment by steida** [comment]
Can't reproduce it anymore. Sorry for the confusion.
