### ISSUE TITLE
Provide a way to use react components in an RNW app running in the browser.

### ISSUE THREAD

**Issue by darrencruse** [necolas/react-native-web#989]
**Is your feature request related to a problem? Please describe.**
I was attempting to use the react-native-material-dropdown component in my RNW app running in the browser but I couldn't get it to work (it's an RN component that doesn't officially support RNW but I thought it might work anyway - unfortunately it seems to be coded against an out of date version of the RN Animated api or something and after trying for several hours I decided to move on).

**Describe a solution you'd like**
We do mainly React apps at work (I've just been learning RN/RNW on the side), and we use the "react-select" (react) dropdown component a lot and when I couldn't get  react-native-material-dropdown to work in the browser it made me wonder if I could put a Platform.OS check in my code and leave react-native-material-dropdown used on iOS and Android but simply use react-select for my RNW app when running in the browser.

**Describe alternatives you've considered**
I was doubtful I could actually do the above but I wasn't 100% sure so I actually did try it and imported the react-select component and tried to use it my containing component.

I was encouraged when I saw (using developer tools) the DOM elements for the react-select were generated in the page (it was actually trying to work it seemed like).  But the css for the component seemed to be missing it didn't look right both the styling and the actual layout was messed up. 

I also tried this:
https://github.com/necolas/react-native-web/blob/master/packages/website/guides/advanced.md
At first I thought maybe this was the kind of "adapter" I was imagining that might let me use react components this way in RNW but it's not entirely clear from the description and when I tried it out it didn't seem to help:

**Additional context**

The only thing I might add is I was using my select component as just an example.  Where I work they have separate groups doing react web apps and (mostly iOS with Swift) mobile apps.  I was hoping to encourage them to consider using RN and RNW with an eye toward creating components that can be reused for both the web apps and mobile apps.

But considering all the already written react apps, the ability to intermix and use react components this way in the RNW version of mobile apps would likely be desired as apps evolve from being mobile to running in the browser.

And maybe it's best a different feature request but I can imagine the reverse being desireable too!  i.e. as new "universal components" are written intended to be used both in RN mobile and RNW web apps, I can imagine people will want to be able to use those in the currently existing react apps if possible too.

My apologies if this is a dumb request (maybe it's fundamentally not possible to do these things?)  If so I'd love to understand more clearly what makes it not possible if you can explain why I'd appreciate it thanks.

**Comment by necolas** [comment]
I don't understand what you're asking. How to use react-select?

**Comment by darrencruse** [comment]
Sorry if I wasn't clear - this is what I tried, here react-native-material-dropdown is DropdownSelect a proper RN component, and Select is this react-select (plain react) component:
```
<View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 }}>
{Platform.OS !== 'web' ?
    <DropdownSelector
    value={this.state.selectedState}
    label="State"
    options={this.state.states}
    onSelect={value => this.setState({ selectedState: value, selectedRecommendations: [] })}
    />
:
    <Select
    name="stateSelector"
    value={this.state.selectedState}
    onChange={value => this.setState({ selectedState: value, selectedRecommendations: [] })}
    options={makeOptions(this.state.states)}
    />
}
</View>
```

**Comment by necolas** [comment]
Yes that's possible, but when you're importing web-only modules you should do so in separate files as described here https://github.com/necolas/react-native-web/blob/master/packages/website/guides/getting-started.md#multi-platform-applications

**Comment by darrencruse** [comment]
Quick follow up I'm unsure if your reply is saying:

a.  (broadly) Yes you can use react components in a RNW app because it really *is* a react app in which react-native components have been implemented in react.

b.  Yes you can use react components but only in code in a .web.js file otherwise they won't work because the .web.js files are processed differently somehow?

**Comment by necolas** [comment]
Both of those are true. (b) is what you need to do for multiplatform applications that are importing ReactDOM components, otherwise you can't make a bundle that works for iOS/Android.

**Comment by darrencruse** [comment]
Thanks a lot I wasn't thinking right I'd hate to steer my co-workers wrong re this idea that we could in theory move toward sharing components between the react web app guys and the react-native mobile guys...

So it sounds like a web app written top down as a RNW app can incorporate (maybe with a little work re it's css and stuff right) existing react components.

Can an existing react web app pull in a react-native component (that's coded to support RNW of course)?  
 
(I'm thinking of how e.g. an RNW app starts up with AppRegistry.registerComponent/runApplication with that "rootTag" - in a normal react app that wouldn't have been done so I assume the RNW components wouldn't work?)

**Comment by necolas** [comment]
Yes you can do either way. We introduced it to Twitter's React DOM app. This is all in the docs

**Comment by darrencruse** [comment]
thanks again and sorry for the basic questions (re-reading the docs as we speak :).

and RNW is a fantastic project thanks for creating it!!
