### ISSUE TITLE
Icons not working in android

### ISSUE THREAD

**Issue by pruthvip** [necolas/react-native-web#990]
While using fonts how it is used in 'benchmarks/src/app/Icons.js', the code breaks in android.

<img width="311" alt="screen shot 2018-06-12 at 3 06 26 pm" src="https://user-images.githubusercontent.com/1709317/41282714-64609172-6e52-11e8-9bda-fa96dd135f2b.png">

When i take createElement from react instead of react native, it throws 
```Invariant Violation: View config not found for name path```

Is there any way we can use it for both web and android?
* OS: OSX
* Device: 
* Browser: Chrome
* React Native for Web (version): 0.7.2
* React (version): 16.3.1

**Comment by necolas** [comment]
No that code won't run outside a browser
