### ISSUE TITLE
ImageBackground not showing image

### ISSUE THREAD

**Issue by bengyles** [necolas/react-native-web#991]
**The problem**
I had RNW version 0.5.3 installed and then upgraded to version 0.8.0. I updated RN accordingly to 0.55.0 and some other dependencies first and then I saw my image was gone from the ImageBackground, breaking my whole UI. I reversed my changes (I only updated packages) and then it worked again so I tried to install version 0.7.3 (with react-art installed as well) which also lead to this problem. I cannot figure out what is breaking this but I think it might have something to do with react-art? After all these updates it still works on ios so I don't think it's a bug on my side. 

**How to reproduce**

Steps to reproduce:
1. install RNW 0.5.3 or higher and add an ImageBackground to your UI => should work
2. upgrade RNW to version 0.7.3
3. ImageBackground is not visible in the browser but is visible on ios

before
![image](https://user-images.githubusercontent.com/9031491/41294537-8dd3ff52-6e58-11e8-821d-259eba296853.png)
after
![image](https://user-images.githubusercontent.com/9031491/41294584-af78b922-6e58-11e8-86b3-a552fe3cb203.png)

**Expected behavior**
The image should be on the background with the form in the middle as shown in the first image

**Environment (include versions). Did this work in previous versions?**

* OS: Mac High Sierra
* Device: IOS
* Browser: Google Chrome
* React Native for Web (version): at least 0.7.3 and up
* React (version): 16.2.0

**Comment by bengyles** [comment]
Sorry for the change of language, I used a screenshot that I made earlier

**Comment by necolas** [comment]
You can see in the examples that this component works. Perhaps you haven't read the release notes or styled the root elements like this https://codesandbox.io/s/52x1871vjl

**Comment by bengyles** [comment]
@necolas 
Thanks for the quick reply, I forgot to set the styles in my index.html and now it works!
