### ISSUE TITLE
Nested horizontal ScrollView prevents scrolling for vertical parent ScrollView

### ISSUE THREAD

**Issue by WillSquire** [necolas/react-native-web#992]
A nested horizontal ScrollView prevents scrolling for a vertical parent ScrollView while the mouse is hovered over it. By setting `overscrollBehaviorY: 'auto'` all is good again. Happy to do a pull request if needed. 

Thanks

**Comment by necolas** [comment]
Please can you fill out the issue template, including a link to a reduced test case. That's what the template is for.

**Comment by necolas** [comment]
Closing due to lack of requested follow up
